.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Fixes the support link for Ionic Appflow.
I don't know if the services are still correct Ionic View, Ionic Deploy, so you can edit this names if needed
=> chore(issues): fix Ionic Appflow support link

angular/scripts/build-core.js, core/tslint.json
- Added shell: true to build script
- Added "linbreak-style": false to tslint.
If this is true, following is happen:
=> Fixes the build on Windows

core/src/components/button/button.ios.scss, core/src/components/button/button.md.scss, core/src/components/chip/chip.scss
This ensures that all `:hover` styles live inside a `(any-hover: hover)`
media query.
=> fix(button/chip): move hover styles into media query

core/src/components/refresher/refresher.tsx, core/src/themes/ionic.globals.scss
There are several bugs in refresher in Ionic v4 like mentioned in #16254
[x] FIXED: The refresher itself lies above the content, instead of below. This means that the instant you start to pull, it is completely visible above your content, instead of sliding out from underneath it.
[x] FIXED: After completing the refresher action, the content jumps back instantly, instead of sliding back up.
[x] Was already fixed: There is a console.log('start') still in compiled @ionic/core code which triggers when starting to you start to drag on a page with the refresher.
It has now the same optical look like in v3 and is working in Chrome and Firefox. This is how it looks in Firefox:
**Fixes**: #16254
=> fix(refresher): close animation and hidden on pull down - Fixes #16254

angular/src/app-initialize.ts, angular/test/test-app/scripts/sync.sh, core/package-lock.json, core/package.json
=> chore(): update stencil/ionicons

core/src/components/virtual-scroll/readme.md
The ion-virtual-scroll element has a items property, not an item property.
=> Fix property name

core/.stylelintrc.yml, core/src/components/datetime/test/basic/e2e.ts, core/src/components/datetime/test/basic/index.html, core/src/components/picker/picker.scss
=> fix(picker): do not change column order when RTL

angular/test/test-app/e2e/src/slides.e2e-spec.ts, angular/test/test-app/src/app/app-routing.module.ts, angular/test/test-app/src/app/app.module.ts, angular/test/test-app/src/app/slides/slides.component.html, angular/test/test-app/src/app/slides/slides.component.ts, core/package.json
Ion-Slides is not working in production build like mentioned in #17032 and #17033 
This issue was not fixed by #17037 
Fix for no is to remove sideEffects - better solution would be great :)
=> test(angular): add test for slides

angular/src/directives/navigation/ion-back-button.ts, angular/src/directives/navigation/ion-tabs.ts, angular/src/directives/navigation/router-link-delegate.ts, core/api.txt, core/src/components.d.ts, core/src/components/tab/tab.tsx, core/src/components/tabs/readme.md, core/src/components/tabs/tabs.tsx
fixes #17068
-
-
-
**Fixes**: #
=> feat(angular): expose getSelected()

angular/BREAKING.md
Typo fix for one word in two places.
-
-
-
**Fixes**: #
=> docs(BREAKING.md): typo - fortunatelly / fortunately

core/src/components/row/readme.md
Came to fix all three pages (col, row, grid), but seems like the others are fixed and just not live yet (#16859, #16538).
Applied the same fix as those to cross-link the pages.
=> docs(row): fix links to grid and col components

core/src/components/select/select.tsx, core/src/components/select/test/basic/e2e.ts, core/src/components/select/test/basic/index.html
also updates the e2e test so that it will continue to take screenshots after mismatches and adds the popover example to avoid future regressions
references #16715 fixes #17142
=> fix(select): pass click event to popover interface

angular/src/directives/control-value-accessors/value-accessor.ts, angular/test/test-app/src/app/app-routing.module.ts, angular/test/test-app/src/app/app.module.ts, angular/test/test-app/src/app/form/form.component.html, angular/test/test-app/src/app/form/form.component.ts, angular/test/test-app/src/app/home-page/home-page.component.html, core/src/components/checkbox/checkbox.tsx, core/src/components/datetime/datetime.tsx, core/src/components/input/input.md.vars.scss, core/src/components/item/item.scss, core/src/components/range/range.tsx, core/src/components/select/select.tsx, core/src/components/toggle/toggle.tsx, core/src/utils/tap-click.ts
fixes #17171
fixes #16052
fixes #15572
fixes #16452
fixes #17063
=> Fix angular validation

core/src/components/loading/readme.md
closes ionic-team/ionic-docs#254
=> docs(loading): correct loading-controller link path

react/package.json, react/src/components/IonModal.tsx, react/src/components/IonPopover.tsx, react/src/components/createControllerComponent.tsx, react/src/components/createOverlayComponent.tsx, react/src/components/navigation/IonTabBar.tsx, react/src/components/utils.ts, react/src/index.ts, react/src/register.ts, react/src/types.ts
This PR is to fix the duplicate events that occurred in react.  I have resolved it by checking if react will take responsibility for an event and if not then fallback to our own event subscription process.
This also includes a small restructure of the exports but has no impact on what is actually exported.
=> Fix duplicate events being fired in ionic/react

angular/src/providers/platform.ts, core/src/utils/platform.ts
Adds the `mobileweb` platform to the list of platforms
- Add `mobileweb` option to `PLATFORMS_MAP` 
- Add function to check if device is `mobileweb`
**Fixes**: #17335
=> feat(platform): add mobileweb platform

core/src/utils/platform.ts
Adds an additional check for PWAs on iOS
- Check `standalone` status via navigator for iOS
**Fixes**: #17336
=> fix(platform): add additional check for safari PWA

core/src/components/loading/readme.md, core/src/components/loading/usage/angular.md, core/src/components/loading/usage/javascript.md
Resolves outdated Loading docs
- Remove `dismissOnPageChange`
- Change `onDidDismiss` to `ionLoadingDidDismiss`
**Fixes**: #
=> docs(loading): remove dismissOnPageChange, add ionLoadingDidDismiss

core/src/components/loading/readme.md, core/src/components/loading/usage/angular.md, core/src/components/loading/usage/javascript.md
Revises the examples to show proper `onDidDismiss` usage
- Update docs to show how to use the built in `onDidDismiss` method instead of listening to the event directly
**Fixes**: #
=> docs(loading): update example to show proper usage

core/src/components/datetime/readme.md
Datetime doc clean up
- Fix typos
- clean up a code snippet
- reword slightly to use clearer language (in consideration of ESL readers).
**Fixes**: https://github.com/ionic-team/ionic-docs/issues/348
=> docs(angular/datetime): typos and clean up

core/src/components.d.ts, core/src/components/reorder-group/readme.md, core/src/components/reorder-group/reorder-group.tsx, core/src/components/reorder-group/test/basic/index.html, core/src/components/reorder/readme.md
Fixed the incomplete documentation for `reorder` and `reorder-group`
- Fix typos in the doc
- Add `properties` for `reorder`
- Remove incomplete/incorrect information
**Fixes**: https://github.com/ionic-team/ionic-docs/issues/160
=> docs(reorder): Fix incomplete docs

angular/BREAKING.md
The Breaking Changes doc never got updated examples for Loading usage
- Adds new info on how to use `onDidDismiss` since `dismissOnPageChange` got removed
-
-
**Fixes**: #
=> docs(loading): update loading example

angular/BREAKING.md
`async` was missing from the new loading example
- Add `async` to new loading example
**Fixes**: #
=> docs(loading): add missing async to new loading example

core/src/components/searchbar/searchbar.ios.scss, core/src/components/searchbar/test/toolbar/index.html
This PR fixes an issue where users could not set a searchbar color in addition to a toolbar color
- Only apply the toolbar color to the searchbar if the searchbar does not already have a color applied to it
**Fixes**: #17186
=> fix(searchbar): allow setting of toolbar color and searchbar color

core/src/components/popover/readme.md, core/src/components/popover/usage/javascript.md
A minor typo in the documentation. I know that the guidelines say that an issue should be created first but that seemed like an overkill in this case. I hope that's okay.
- Adding the missing comma
**Fixes**: #
=> docs(popover): Add missing comma in example

core/src/utils/config.ts
it fix the definition of scrollPadding, inputBlurring and hideCaretOnScroll in config.ts by declaring it as boolean instead of string
v4
=> fix(config): update types for scrollPadding, inputBlurring and hideCaretOnScroll to boolean

angular/src/directives/proxies.ts, core/api.txt, core/src/components.d.ts, core/src/components/range/range.tsx, core/src/components/range/readme.md, core/src/components/range/test/basic/index.html, core/src/components/range/usage/angular.md, core/src/components/range/usage/javascript.md
Ability to set the neutral point of the picker. Active ticks and bar are measured from the neutral point instead of the min value.
- added neutralPoint prop
- calculate active state of ticks and bar
- set intial value to neutralPoint if not set
4.0.0
=> feat(range): add neutral point

core/src/components/range/range.tsx
Range slider rtl support after introducing the neutralPoint feature.
- correct calculation of barActive and knobStyles  
4.0.1
**Fixes**: in #17400 destroyed rtl support
=> fix(Range): rtl support

core/src/components/item-sliding/item-sliding.tsx, core/src/components/item-sliding/test/interactive/e2e.ts, core/src/components/item-sliding/test/interactive/index.html
Fixes an issue where item-sliding would break when one of the items was removed from the DOM
- Added test to verify proper behavior of component
- clear open item when item is removed
**Fixes**: #15486
=> fix(item-sliding): Sliding no longer breaks after removing an item

core/src/components/datetime/datetime-util.ts, core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/datetime.spec.ts
This PR resolves an issue where the datetime component is not defaulting to the current date when no value is given
-  Add `getDateValue` which will parse a given date OR default to the current date
- Add base spec tests to be built out in future tasks
-
**Fixes**: #14609
=> fix(datetime): default to current date when no value given

core/src/components/button/button.ios.scss
Fixes an issue where the "tinted" color was not being used on buttons with ion-colors applied to them
- Added a rule to apply the tinted color when a button with an ion-color is activated
**Fixes**: #17436
=> fix(button): activated button on ios shows proper shade

angular/src/directives/proxies.ts, core/api.txt, core/src/components.d.ts, core/src/components/range/range.tsx, core/src/components/range/readme.md, core/src/components/range/test/basic/index.html, core/src/components/range/usage/angular.md, core/src/components/range/usage/javascript.md
Reverts the neutral point feature for the range component
-
-
-
**Fixes**: #
=> chore(): revert neutral point

core/src/components/reorder-group/reorder-group.tsx, core/src/components/reorder-group/test/basic/index.html
Allow `ion-item-sliding` items to be reordered inside an `ion-reorder-group`.
- Increase the `gesturePriority` of `ion-reorder-group` from `100` to `110`.
- Add a test case for `ion-item-sliding` in the `reorder-group` basic test.
I'm not sure if there is a reason this was lower priority than `ion-item-sliding` before, but this seems to resolve the issue.
**Ionic Version**: 4.0.2
**Fixes**: #16120
=> fix(reorder): increase gesture priority

core/src/components/img/img.scss
This isn't a bug per se, but rather the behavior of `img` that isn't really desirable. (https://stackoverflow.com/questions/5804256/image-inside-div-has-extra-space-below-the-image)
The result of this default behavior is to display the image `inline`, which causes a small gap to appear below the image. Instead, we have the img display `block`
- Add `display: block` to the `img` element
**Fixes**: #17543
=> fix(img): remove space under img

core/src/components/loading/loading-interface.ts
In loading component, backdropDismiss property is missing.
- In **loading** component, add missing backdropDismiss property 
**Fixes**: https://github.com/ionic-team/ionic/issues/17369
=> fix(loading): add missing backdropDismiss property

core/src/components/split-pane/split-pane.tsx
The former message said: split pane could not found any main node
That was grammatically incorrect and it made it sound like the split pane itself was doing the searching rather than being the entity that did not have a properly specified child "main" element.
On "cannot" vs. "can not" they are both technically correct according to Webster, but "cannot" seems to be preferred in this case with "can not" being preferred in cases where the "not" modifies another word, such as "can not only do this but also..."
- Fix the wording of the warning messages
4.x
=> fix(split-pane): use proper grammar in warnings

core/src/components/datetime/datetime-util.ts, core/src/components/datetime/test/datetime.spec.ts
This PR is a follow up to my previous datetime PR that adds better handling for invalid value edge cases
- Explicitly detect if input dateString is of type `string`, otherwise default to current date
=> fix(datetime): fix edge cases with datetime and invalid values

core/src/components/datetime/datetime.tsx
Fixes scenario where value is not set and so current date was rendered. As a result, placeholder is never used. This PR does not render the current date if there is no value. Current date is still shown in the picker though
- Return early from `getText` if no value set
=> fix(datetime): fix placeholder not being respected

core/src/components/datetime/datetime.tsx
Fixes placeholders for Angular. undefined/null seem to be converts to empty strings in some cases
- Check for empty string
=> fix placeholder again

.github/PROCESS.md, core/src/components/chip/chip.scss
Update to match MD spec so outline has no background, in the future we will want to add an "activated" or "selected" state that fills this in
| `master` | `fix-chip-outline` |
| ---| ---|
| ![master(Galaxy S5) (1)](https://user-images.githubusercontent.com/6577830/54157863-8e161e80-441f-11e9-9966-0924796964ab.png) | ![fix-chip-outline(Galaxy S5)](https://user-images.githubusercontent.com/6577830/54157805-6de65f80-441f-11e9-8129-ea60d0ee8dfa.png) |
=> fix(chip): use transparent outline on color chips

angular/src/util/overlay.ts
Add `undefined` to the return type of `getTop` method in `OverlayBaseController`
**Fixes**: #17801
=> fix(angular): overlay.getTop can return undefined

vue/src/controllers/popover-controller.ts
This PR fixed a typo in the popover controller, https://github.com/ionic-team/ionic/blob/master/vue/src/controllers/popover-controller.ts#L5.
before:
```typescript
export const CTRL = 'ion-modal-controller';
```
- Change the typo line to be:
```typescript
export const CTRL = 'ion-popover-controller'
```
**Ionic Version**: 4.1.2
**Fixes**: #17864
=> [Vue] Fixed popover controller

core/src/components/datetime/datetime-util.ts, core/src/components/datetime/test/basic/index.html
Set datetime picker to 0 instead of current time when value is 0
-
-
-
**Fixes**: https://github.com/ionic-team/ionic/issues/17868
=> fix(datetime): set picker to 0 instead of current time when value is 0

vue/src/components/ion-vue-router.ts
Given nested `ion-vue-router` elements, each is adding a click handler listening to `ion-back-button` events, without stopping propagation user is navigated back as many steps as there are `ion-vue-router` elements.
=> Fix back button event handling

core/src/components/item-option/item-option.scss, core/src/components/item-option/item-option.tsx, core/src/components/item-sliding/test/basic/index.html, core/src/themes/test/css-variables/index.html
This fixes the linked bug whereby the `disabled` attribute was not working on the `ion-item-option` component. This PR includes the styling and applies the disabled class to the component.
- Apply `item-option-disabled` class to the component.
- Update styling in SCSS file.
- Update demo to include `disabled` option.
**Ionic Version**: 4.1.2
**Fixes**: #17905
=> fix(item-option): styling and behaviour for disabled item-option

.github/PROCESS.md
Adds documentation to explain the purpose of version branches, how to create them, and when to merge release branches into them
=> chore(): update release process to document version branches

core/src/components/modal/readme.md, core/src/components/modal/usage/angular.md
Added lazy loading documentation per https://github.com/ionic-team/ionic/issues/17939. Some users have noted that the change from v3->v4 with modals/lazy loading is confusing, so I added an example
=> docs(modal): add lazy loading usage

.github/ionic-issue-bot.yml
Adds `ionitron: capacitor` so we can transfer issues to the capacitor repo if need be
=> chore(): add label for capacitor issues

angular/src/directives/navigation/stack-controller.ts, angular/test/test-app/e2e/src/tabs.e2e-spec.ts, angular/test/test-app/src/app/nested-outlet/nested-outlet.component.html, angular/test/test-app/src/app/tabs-tab2/tabs-tab2.component.html
Issue Number: #17278 #15216
- When using `ion-back-button`, the stack controller will now check to see if there is any savedData in the view. If there is, it will attempt to restore whatever state there was before.
=> fix(angular): back button goes back to proper tab

core/src/components/item/item.scss
The code to make inset highlight work was removed by this commit: https://github.com/ionic-team/ionic/commit/fd79b5774880e499933c19d658ccccac9b7899a5#diff-be35bd653745acb6d128c4ec32dd2e6fL172
This PR adds the code back which makes the highlight work again, but I'm not sure why it was removed in the first place.
The inset highlight is taking up the full width
Issue Number: #18051
The inset highlight has left padding to match the item border.
=> fix(item): use the correct highlight for an inset line input item

core/src/components/loading/loading.tsx, core/src/components/loading/test/basic/e2e.ts, core/src/components/loading/test/basic/index.html
Issue Number: https://github.com/ionic-team/ionic/issues/18135
- Users can now pass an HTML string into the `content` prop
=> fix(loading): allow html content

core/src/components/tabs/tabs.tsx
=> fix(tabs): select the correct tab on load with the select method

angular/src/directives/navigation/ion-router-outlet.ts, angular/src/directives/navigation/stack-controller.ts, angular/src/directives/navigation/stack-utils.ts, angular/src/providers/nav-controller.ts
Issue Number: https://github.com/ionic-team/ionic/issues/16744
Going from` /page1?query=Hello` to `/page2`, and then back would return you to `/page1` instead of `/page1?query=Hello`
`queryParams` and `fragment` options are now preserved when going back in navigation. I originally had only intended to fix `queryParams` but it was easy to also preserve `fragment` too, so I added that in as well. Now, going from `/page1?query=Hello#MyDiv` to `/page2` and then back, will return you to `/page1?query=Hello#MyDiv`.
=> fix(angular): preserve queryParams and fragment when going back

core/src/components/datetime/test/basic/e2e.ts, core/src/components/input/test/spec/e2e.ts, core/src/components/item-sliding/test/basic/e2e.ts, core/src/components/item/test/inputs/e2e.ts, core/src/components/radio/test/basic/e2e.ts, core/src/components/range/test/basic/e2e.ts, core/src/components/searchbar/test/basic/e2e.ts, core/src/components/segment/test/basic/e2e.ts, core/src/components/segment/test/spec/e2e.ts, core/src/components/select/test/basic/e2e.ts, core/src/components/tab-bar/test/scenarios/e2e.ts, core/src/components/toggle/test/basic/e2e.ts, core/src/components/toolbar/test/basic/e2e.ts, core/src/components/toolbar/test/colors/e2e.ts, core/src/components/toolbar/test/components/e2e.ts, core/src/components/toolbar/test/scenarios/e2e.ts, core/src/components/toolbar/test/spec/e2e.ts, core/src/components/toolbar/test/standalone/e2e.ts
Adds the following RTL tests 
Components with RTL tests already
- action-sheet
- alert
- fab
- icon
- item
- loading
- menu
- modal
- picker-column
- popover
- toast
references #17012
=> test(components): add rtl tests and remove skips

core/src/themes/ionic.functions.string.scss, core/src/themes/ionic.mixins.scss
Gist of current root selector function: https://www.sassmeister.com/gist/92595cf40732f426c1684e7e6a3e8d60
Gist of latest root selector function: 
https://www.sassmeister.com/gist/4435596f18655413a5101915ee79aaee
Issue Number: #17012
-
-
-
=> fix(sass): update rtl function to prepend host with context properly

angular/src/providers/nav-controller.ts
Issue Number: patch for https://github.com/ionic-team/ionic/pull/18298
Special chars were being encoded via the router and then re-encoded when creating a UrlTree
- Since we can't prevent the router from encoding the url, decode the url before passing it in to be re-encoded
=> fix(angular): preserve special characters encoding when going back

core/src/components/button/button.tsx, core/src/components/toolbar/test/spec/index.html
Issue Number: fixes #18329 
-
-
-
=> fix(button): do not apply a width if there is button text with an icon

core/api.txt, core/src/components.d.ts, core/src/components/item-options/item-options.tsx, core/src/components/item-sliding/item-sliding.tsx, core/src/components/item-sliding/readme.md, core/src/components/item-sliding/test/basic/index.html, core/src/components/item-sliding/test/standalone/e2e.ts, core/src/components/item-sliding/test/test.utils.ts
The item sliding gesture in RTL was trying to open the opposite side, and the open method was not switching sides based on RTL.
Issue Number: references #17012
- The open method now checks for RTL and switches the side to open
- The gesture will drag open the correct side for RTL
- An e2e test for RTL with the gesture has been added
=> fix(item-sliding): use the correct gesture direction and side for rtl

core/src/components/toast/test/basic/e2e.ts, core/src/components/toast/test/basic/index.html, core/src/components/toast/toast.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/18204
- HTML content can be passed in to the `message` prop
=> feat(toast): allow html content

core/api.txt, core/src/components/buttons/buttons.md.scss, core/src/components/menu-button/menu-button.ios.scss, core/src/components/menu-button/menu-button.md.scss, core/src/components/menu-button/menu-button.scss, core/src/components/menu-button/menu-button.tsx, core/src/components/menu-button/readme.md, core/src/components/menu-button/test/basic/e2e.ts, core/src/components/menu-button/test/basic/index.html
- adds css variables for hover / focused states
- adds styles for background hover and rounds the button 
- updates to match the MD spec for the hover/focus states
- moves width and height to the host element, making it easier to customize
- fixes the color so it uses Ionic colors instead of adding color to the icon
references #18279
=> feat(menu-button): add variables for hover and focused states

core/api.txt, core/src/components/button/button.ios.scss, core/src/components/button/button.md.scss, core/src/components/button/button.scss, core/src/components/button/button.vars.scss, core/src/components/button/readme.md, core/src/components/button/test/basic/index.html, core/src/components/button/test/clear/index.html, core/src/components/button/test/outline/index.html, core/src/components/button/test/standalone/index.html, core/src/themes/test/css-variables/index.html
Issue Number: fixes #17974
- Adds `--background-hover` and `--color-hover` variables to button
- Styles them to have hover states
=> feat(button): add variables for customizing hover

core/api.txt, core/src/components/back-button/back-button.ios.scss, core/src/components/back-button/back-button.ios.vars.scss, core/src/components/back-button/back-button.md.scss, core/src/components/back-button/back-button.scss, core/src/components/back-button/back-button.tsx, core/src/components/back-button/readme.md, core/src/components/back-button/test/basic/e2e.ts, core/src/components/back-button/test/basic/index.html, core/src/components/back-button/test/navigation/index.html, core/src/components/back-button/test/standalone/e2e.ts, core/src/components/back-button/test/standalone/index.html, core/src/components/back-button/test/toolbar/e2e.ts, core/src/components/back-button/test/toolbar/index.html, core/src/components/button/button.scss, core/src/components/buttons/buttons.ios.scss, core/src/components/buttons/buttons.md.scss, core/src/components/menu-button/menu-button.md.scss
also adds e2e tests and adds them to screenshot
Issue Number: references #18279 references #17624 fixes #18465
-
-
-
| ---| ---|
| ![localhost_3333_src_components_back-button_test_basic(iPhone 6_7_8) (2)](https://user-images.githubusercontent.com/6577830/58993789-8bc42600-87bc-11e9-8acd-09726dc9978d.png) | ![localhost_3333_src_components_back-button_test_basic(iPhone 6_7_8)](https://user-images.githubusercontent.com/6577830/58993667-2ff99d00-87bc-11e9-96e8-3262b6ab0d77.png) |
| ![localhost_3333_src_components_back-button_test_basic(iPhone 6_7_8) (3)](https://user-images.githubusercontent.com/6577830/58993858-bf06b500-87bc-11e9-8034-519379b9cdae.png) | …
=> feat(back-button): add variables and support for focused and hover

core/api.txt, core/src/components/item-divider/item-divider.ios.scss, core/src/components/item-divider/item-divider.md.scss, core/src/components/item-divider/item-divider.scss, core/src/components/item-divider/readme.md
Issue Number: fixes #18484
It solves: #18484
All credit goes to @brandyscarney, I just implemented the solution she proposed on #18484
=> feat(item-divider): add inner padding CSS variables

core/src/components/item/item.scss, core/src/components/item/test/basic/index.html
Issue Number: fixes #17670
-
-
-
=> fix(item): inherit overflow but default to hidden

core/src/components.d.ts, core/src/components/footer/footer.tsx, core/src/components/footer/readme.md, core/src/components/header/header.tsx, core/src/components/header/readme.md
Issue Number: https://github.com/ionic-team/ionic/issues/18510#issuecomment-501404919
- Added a note to the `translucent` props on `ion-header` and `ion-footer` that translucency only works in iOS mode.
=> docs(): add iOS only note to translucent props

core/src/components/item/item.scss, core/src/components/item/item.tsx, core/src/components/item/test/disabled/e2e.ts, core/src/components/item/test/disabled/index.html, core/src/components/label/label.scss
View the following Codepen to see the behavior on 4.5.0: https://codepen.io/brandyscarney/pen/KjRqRB
Change the assets to `4.6.0` to see the broken behavior.
Issue Number: fixes #18670
- View the new behavior at the following tests
- `http://localhost:3333/src/components/item/test/disabled`
- `http://localhost:3333/src/themes/test/css-variables`
- Any of the individual input tests (radio, checkbox, toggle, datetime, select, etc.)
=> fix(item): do not disable entire item if there are multiple inputs

angular/package.json
This PR brings support for Angular 8 while still supporting Angular 7 apps and not introducing a breaking change. While #18577 goes all in on Angular 8, it does introduce a breaking change that we'd like to avoid. After talking with the Angular team, they suggesting keeping things built with Angular 7, but allowing peer deps to use Angular 8
https://github.com/angular/angular/issues/30654#issuecomment-495642339
=> chore(): change peer deps to support ng8

angular/src/providers/nav-controller.ts
Started as a simple typo but ended up reviewing all docs items on the page.
Mostly fixed grammar, and some typos.
One mistake I would like to get an opinion on was that `navigateBack` was mentioned twice in one docs block. I changed it to `navigateRoot` but just want to be sure this was the correct change before it ends up in the official docs:
> It's recommended to use `navigateForward()`, `navigateBack()` and `navigateRoot()` instead of `setDirection()`.
This is the only change that was "new" content.
-
-
-
=> docs(nav-controller): full review of docs

core/scripts/testing/scripts.js, core/src/components/content/content.tsx
Still leaving in the `experimentalTransitionShadow` config for now, but defaulting it to true. We can remove the config in the next major release.
=> fix(transition): enable ios transition shadow by default

core/src/utils/animation/animation.ts, core/src/utils/animation/test/display/e2e.ts
Issue Number: css animations do not run on elements that are hidden (via display: none). We had a check for this, but it was very very slow and affected all devices that used the animations.
- We opted to remove this check and will document this behavior for users
=> perf(animation): remove display: none check

core/src/components/menu/menu.tsx, core/src/utils/animation/animation-interface.ts, core/src/utils/animation/animation.ts
when using css animations, toggling an element's display state causes the animation re-run
- on animation finish, remove the `animation-play-state`, `animation-duration`, `animation-delay` from all animated elements to prevent them from "replaying" once they are done. Animations can be actually replayed via the usual `.play()`, method in IonicAnimations
=> fix(animation): prevent animation re-run when toggling element visibility

core/src/components/nav/nav.tsx, core/src/components/router-outlet/route-outlet.tsx, core/src/utils/animation/animation.ts
With both the old animations utility and the new animations utility, a new swipe animation could begin before the previous animation has fully finished, leading to visual glitches and occasionally breaking navigation.
It's a little hard to reproduce and really only happens if you are intentionally trying to break things 😉, but if you try and swipe back as a previous swipe back is finishing, the current view will "jump". Easiest to reproduce on a lower end iPhone with low battery mode enabled. Also helps to be on a larger/slower application.
- Prevent a new swipe gesture from beginning until the previous one has fully resolved.
- This is consistent with the native iOS behavior …
=> fix(nav): prevent completing transition from being interrupted

core/src/utils/animation/animation-interface.ts, core/src/utils/animation/animation-utils.ts, core/src/utils/animation/animation.ts, core/src/utils/animation/test/animation.spec.ts, core/src/utils/animation/test/animationbuilder/index.html, core/src/utils/transition/ios.transition.ts
=> fix(animation): avoid partial keyframes

angular/test/test-app/e2e/src/tabs.e2e-spec.ts, angular/test/test-app/package.json, angular/test/test-app/src/app/tabs-tab1/tabs-tab1.component.html, angular/test/test-app/src/app/tabs-tab1/tabs-tab1.component.ts, angular/test/test-app/src/app/tabs-tab2/tabs-tab2.component.html, angular/test/test-app/src/app/tabs-tab2/tabs-tab2.component.ts, core/src/components/segment/segment.tsx
=> fix(segment): don't emit ionChange until didLoad

core/src/components/menu/menu.tsx, core/src/utils/animation/animation.ts
Issue Number: https://github.com/ionic-team/ionic/issues/19203
With the old animation system, doing `transform: none` was fine, but doesn't work for Web Animations
- explicitly stop the web animation when the animation is done and when the menu is closed
-
-
=> fix(menu): menu is positioned currently on resize

core/src/utils/animation/animation-interface.ts
`onFinish` interface did not show the `opts` parameter and did not show the correct `callback` type.
Added `opts` parameter and corrected the `callback` type.
=> fix(animation): add correct `onFinish` interface parameters

core/src/utils/animation/animation.ts
Issue Number: https://github.com/ionic-team/ionic/issues/19285
There's a quirk on Safari with CSS Animations where a duration of 0 causes the animation not to run (it works fine with CSS Animations on Chrome)
- When running in CSS Animations mode, all durations of 0 are set to `1ms`. It's enough that the animation will run and still look like it's happening instantly.
=> fix(animation): animations of duration 0 run in Safari

core/src/utils/animation/animation.ts
Issue Number: https://github.com/ionic-team/ionic/issues/19272
Methods like `updateTiming` and `getComputedTiming` actually shipped in Chrome 75, not earlier like I had originally thought. For the most part, people should have autoupdating Chrome (and so this shouldn't be an issue), but some either do not have autoupdating enabled _or_ the autoupdating hasn't kicked in yet for whatever reason. As a result, they were running into this issue since older versions of Chrome only had a partial implementation of Web Animations.
- Improve the feature detection to look for `AnimationEffect` support, which should cover the rest of the APIs we use.
=> fix(animation): fallback to CSS Animations on older versions of Chrome

core/src/utils/animation/animation.ts, core/src/utils/animation/test/animation.spec.ts, core/src/utils/animation/test/multiple/index.html
There are a few inconsistencies between Web and CSS Animations. For example, the default easing in css animations is `ease`, but in web animations the default easing is `linear`
Set defaults to avoid any inconsistencies between web and css anims
=> fix(animation): set defaults to avoid inconsistencies

core/src/components/item-options/readme.md
=> docs(item-options): use title case for headers

core/src/components/item/readme.md
=> docs(item): fragment links pointed at root not doc

core/src/components/radio-group/radio-group.tsx
Issue Number: #19277
- Get the radio elements prior to caching radio group value so everything is up to date
=> fix(radio-group): get radios before caching value to avoid infinite loop

core/src/components/menu/test/basic/index.html, core/src/utils/animation/animation.ts, core/src/utils/helpers.ts
Our raf calls did were not using the patched version of raf, so ngzone would have run during animations causing a lot of jank
- updated animations to use a patched version of raf that prevents ngzone from being called
=> perf(animation): avoid ngzone with requestAnimationFrame

angular/src/directives/control-value-accessors/value-accessor.ts, angular/src/directives/navigation/stack-controller.ts, core/src/components/tab/tab.tsx, core/src/components/tabs/tabs.tsx, core/src/utils/animation/animation-utils.ts, core/src/utils/animation/animation.ts, core/src/utils/overlays.ts, vue/src/components/navigation/ion-vue-router.ts
=> fix(ie): classList does not support variadic

core/src/components.d.ts, core/src/components/split-pane/readme.md, core/src/components/split-pane/split-pane.tsx
Split pane allows currently allows users to place the `main` attribute on their content for the split pane to find.
Users should use the `contentId` prop to help split pane find its main content
=> refactor(): remove [main] from split-pane

angular/src/providers/menu-controller.ts
swipeEnable was deprecated but existed alongside swipeGesture 
- Removed swipeEnable. Use swipeGesture instead.
=> refactor(): remove deprecated swipeEnable

core/src/utils/transition/md.transition.ts
Issue Number: https://github.com/ionic-team/ionic/issues/19491
- The leaving view, when navigating back, has `display: none` applied to it at the end of the transition, ensuring that there is no flicker between when the animation is destroyed and when the view is removed from the DOM.
=> fix(md): fix flicker when navigating back in MD mode on certain Android devices

core/src/components/modal/test/test.utils.ts, core/src/utils/overlays.ts
Issue Number: https://github.com/ionic-team/ionic/issues/19576
- Fixed bug to ensure lifecycles are called
- Added tests so this bug doesn't happen again
=> fix(overlay): ensure lifecycles fire properly

core/src/components/searchbar/searchbar.ios.scss, core/src/components/searchbar/test/toolbar/index.html, core/src/components/toolbar/toolbar.ios.scss
Issue Number: fixes #19495 fixes #19502
- Moves the CSS to the searchbar to remove `!important`
- Aligns all slotted content next to a searchbar to the top and adjusts the chip margin
=> fix(searchbar): update alignment of chips and other elements in toolbar

core/src/utils/transition/index.ts, core/src/utils/transition/ios.transition.ts, core/src/utils/transition/md.transition.ts
Issue Number: https://github.com/ionic-team/ionic/issues/19674
- `display: none` is set on the leaving view in the back direction after a successful transition
=> fix(ios): hide leaving view after nav transition to avoid flicker

packages/react/src/components/createControllerComponent.tsx
It doesn't seem like there are any relevant docs to address. I am struggling with how to test for this, and the existing tests seem fairly limited but they do still pass. If you have suggestions in this area I'm happy to work on it.
Issue Number: #19755
-The overlay will now only be created if it doesn't already exist
- And it will only be shown if it hasn't already been dismissed
=> handle asynchronous issues with loading indicator

core/src/components/header/header.ios.scss, core/src/components/header/header.tsx, core/src/components/header/header.utils.ts, core/src/components/tabs/test/basic/index.html
The main header had a transition always applied (even if not using collapsible header). For collapsible headers, this caused the main title/buttons to appear briefly before fading out which was a bit jarring.
I made it so that the transition is only applied a) for the collapsible header and b) after the buttons/title have already been hidden
=> fix(header): avoid flicker on collapsible header load

angular/src/providers/animation-controller.ts, core/src/components/menu/menu.tsx, core/src/components/nav/nav.tsx, core/src/components/router-outlet/route-outlet.tsx, core/src/index.ts, core/src/utils/animation/cubic-bezier.ts, core/src/utils/animation/test/animation.spec.ts
Issue Number: https://github.com/ionic-team/ionic/issues/19789
- Exposed a utility to convert time from easing curve A to easing curve B
=> feat(animation): cubic-bezier easing conversion utility (experimental)

core/src/utils/transition/ios.transition.ts
Issue Number: https://github.com/ionic-team/ionic/issues/19840
- Make sure back button is in start slot before determining whether or not to animate
=> fix(ios): only animate large title if back button is in start slot

packages/react-router/src/ReactRouter/Router.tsx, packages/react-router/src/utils/LocationHistory.ts
=> fix(react): expand the stack to better support back button, fixes #19748

core/api.txt, core/src/components/searchbar/readme.md, core/src/components/searchbar/searchbar.ios.scss, core/src/components/searchbar/searchbar.md.scss, core/src/components/searchbar/searchbar.scss, core/src/components/searchbar/test/basic/index.html
We would like to style the box-shadow property in searchbar and give the parent the ability to control it.
(Sorry running on a windows box and unable to run "sass")
The behaviour modification is simply to expose a css variable that is currently not exposed and set by default for md styles on component searchbar.
- This PR exposes --box-shadow so that we can have control over that property
- Users using md style for searchbar will be able to set the box-shadow on the input with class "searchbar-input"
-
**N/A**
**N/A**
=> feat(searchbar): add --box-shadow variable to style searchbar input

core/api.txt, core/src/components/select/readme.md, core/src/components/select/select.scss, core/src/components/select/select.tsx, core/src/components/select/test/basic/index.html
Issue Number: https://github.com/ionic-team/ionic/issues/17446
- Added `--placeholder-opacity and `--placeholder-color` css variables
- Added shadow parts for relevant elements
=> feat(select): add --placeholder-opacity, expose shadow parts

angular/src/providers/config.ts
Blocked by https://github.com/ionic-team/ionic-docs/pull/1084
After discussion with the team we decided to remove Config.set in Ionic 6, not Ionic 5. This meant the deprecation message was no longer correct. 
- Update deprecation message to include link to docs
=> chore(angular): update Config deprecation message

core/src/components/virtual-scroll/readme.md
On `ion-virtual-scroll` docs it references a `virtualTrackBy` method, which actually does not exist. The correct name of the method is `trackBy`. Many people get confused by this.
Issue Number: #17190, #15258, #16632
The name of the method in the docs is now `trackBy`.
=> docs(virtual-scroll): change virtualTrackBy name

core/package.json, packages/react/package.json, vue/package-lock.json, vue/package.json
The `ionicons/icons` package is now using data urls.
=> chore(ionicons): update ionicons to 5.0.0-13

packages/react-router/src/ReactRouter/Router.tsx, packages/react-router/src/ReactRouter/ViewItem.ts, packages/react-router/src/ReactRouter/ViewStacks.ts
- [X ] Build (`npm run build`) was run locally and any changes were pushed
- [X ] Lint (`npm run lint`) has passed locally and any fixes were made for failures
- [X ] Bugfix
<IonRouterOutlet> does not manage routes where the match contains wildcards. the page would not be added to the navigation stack if a page matching the same route already exists.
Issue Number: 19891
See issue description, changes are described in comment 3
=> fix(react-router): clone ViewItem when a location change returns a ViewItem already in the history (#19891)

core/src/utils/transition/ios.transition.ts
Issue Number: https://github.com/ionic-team/ionic/issues/20028
- [This change](https://github.com/ionic-team/ionic/commit/fc4bb2db5c5715841347135bdfa1bf66718d647d) caused the bug. The top safe area value is already included in the result of `getBoundingClientRect`, so we were essentially adding the top safe area value twice, which resulted in the cloned back button/title being in the wrong location.
=> fix(title): large title nav transition adds correct safe area value

core/src/utils/animation/animation-utils.ts, core/src/utils/animation/animation.ts, core/src/utils/animation/test/basic/index.html, core/src/utils/animation/test/gesture/index.html
Issue Number: https://github.com/ionic-team/ionic/issues/20058
- For Web Animations only, we convert all hyphenated animated properties (`border-radius`) to camel case variants (`borderRadius`). This is a required change in order to allow devs to animate hyphenated CSS properties.
=> fix(animations): convert hyphenated properties to camel case when using Web Animations

core/src/components/modal/animations/ios.enter.ts, core/src/components/modal/animations/ios.leave.ts, core/src/components/modal/gestures/swipe-to-close.ts, core/src/components/modal/modal.ios.scss, core/src/components/modal/test/spec/index.html, core/src/css/core.scss
On devices with a notch, the card style modal would not account for the safe area, pushing the presenting element underneath the status bar.
- Apply `var(--ion-safe-area-top)` where needed to ensure modal/presenting el do not appear under statusbar
=> fix(modal): account for safe area on devices with a notch

core/api.txt, core/src/components/toggle/readme.md, core/src/components/toggle/test/basic/index.html, core/src/components/toggle/toggle.ios.scss, core/src/components/toggle/toggle.md.scss, core/src/components/toggle/toggle.scss
Issue Number: https://github.com/ionic-team/ionic/issues/17166#issue-400786305
- Added --border-radius variable for the track
- Added --handle-border-radius variable for the handle
=> feat(toggle): add --border-radius and --handle-border-radius variables

core/src/components/toast/toast.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/19722
- Exposed shadow parts for the container, header, message, and buttons.
Usage:
```
ion-toast::part(button) {
background-color: "blue";
}
```
This sets the background color to all buttons to be blue.
=> feat(toast): expose shadow parts

packages/react/src/components/IonIcon.tsx, packages/react/src/components/index.ts, packages/react/src/components/inner-proxies.ts, packages/react/src/components/proxies.ts
=> fix(react): supporting ios and md props on icons

core/src/components/content/content.scss
Issue Number: https://github.com/ionic-team/ionic/issues/20185
- `.scroll-content` now takes up 100% of the container height
=> fix(content): scroll-content div now takes up full height of container

core/src/components/header/header.tsx
On non-scrollable pages (I.e. pages that do not scroll but still have the rubber band effect), the opacity on the collapsible titles does not reset properly
Opacity resets properly (added a 1px buffer -- I think this is mostly a safari quirk/rounding quirk)
=> fix(header): header opacity properly resets on collapsible titles

core/src/components/modal/gestures/swipe-to-close.ts, core/src/components/modal/modal.tsx
When dismissing a card-style modal via a swipe, on older/slower iOS devices it is possible to quickly tap the backdrop and have the dismiss animation played again.
Add a flag when dismissing via a gesture which prevents the dismiss method from being called again.
=> fix(modal): prevent double dismiss via gesture and backdrop tap on card-style modal

core/src/components/card-content/card-content.ios.scss
-
-
-
| master | branch |
| ---| ---|
|![localhost_3333_src_components_card_test_translucent_ionic_mode=ios(Galaxy S5) (1)](https://user-images.githubusercontent.com/6577830/72628345-1efd3680-391c-11ea-9617-b6942561636a.png) | ![localhost_3333_src_components_card_test_translucent_ionic_mode=ios(Galaxy S5)](https://user-images.githubusercontent.com/6577830/72628337-1ad11900-391c-11ea-9f7a-c26c94f91de5.png) |
=> fix(card): remove top padding of content in iOS if under header

core/src/components/modal/animations/ios.enter.ts, core/src/components/modal/animations/ios.leave.ts, core/src/utils/animation/animation-utils.ts, core/src/utils/animation/animation.ts, core/src/utils/animation/test/animation.spec.ts, core/src/utils/animation/test/basic/index.html
Issue Number: https://github.com/ionic-team/ionic/issues/20251
- Convert `easing` to `animation-timing-function` for CSS Animations
- Also convert all camel case properties to kebab case for CSS Animations. Properties like border radius should be written as `borderRadius` in order for it to work across Web Animations and CSS Animations.
=> fix(animation): add property conversions for CSS Animations

core/src/components/modal/modal.ios.scss, core/src/components/modal/readme.md, core/src/components/modal/usage/angular.md
Issue Number: https://github.com/ionic-team/ionic/issues/20255
- Card-style modal now opens at width 100%
- Developers can override this by setting the `--width` CSS variable on the modal.
=> fix(modal): card-style modal now opens at full width on larger devices

core/src/interface.d.ts, packages/react/package.json, packages/react/src/components/CreateAnimation.tsx, packages/react/src/components/index.ts
React users would need to use the raw animations API to use Ionic Animations.
- Added an experimental wrapper component. Does not currently support everything (I.e. adding child animations, etc).
- Users can still access the raw animation object for more advanced features.
=> feat(react): add Ionic Animations wrapper (experimental)

core/src/components/refresher-content/refresher-content.tsx, core/src/components/refresher/refresher.utils.ts, core/src/themes/ionic.globals.scss
Native refreshers were not falling back properly. Running in iOS mode on Chrome should fallback to the old refresher but was not.
- Added checks to do a best guess at detecting overflow scrolling support (I don't know if iOS 14 will remove the webkitOverflowScrolling property so I'll need to test the betas as they come out)
- Updated the icon defaults so the iOS fallback doesn't look as bad 
- Fixed the z-index issue with the old refresher
=> fix(refresher): add correct fallbacks for native refreshers

core/src/components/header/header.tsx, core/src/components/header/header.utils.ts
There was a race condition where the outer header had not fully loaded and so its clientHeight was 0. This caused the IntersectionObserver to have the wrong margins causing the collapsible header to sometimes not work.
- Set the IO root to be `ion-content` rather than the document root. Allowed me to remove a DOM read as well.
=> fix(header): fix race condition in collapsible header

core/src/components/refresher/refresher.tsx, core/src/themes/ionic.globals.scss
Issue Number: https://github.com/ionic-team/ionic/issues/20377
- Ensure that we are translating the background element in the content when using the old refresher
- Reverted z-index change for ion-refresher
=> fix(refresher): translate background content when refreshing

core/src/components/segment-button/segment-button.ios.scss, core/src/components/segment-button/segment-button.tsx, core/src/components/segment/segment.ios.scss, core/src/components/segment/segment.tsx
This gets around a bug with Safari where the ::slotted css selector was not working properly
To reproduce, on master:
1. Open the `src/components/segment/test/basic?ionic:mode=ios` test in Chrome
2. Press down on the checked segment button (with the indicator), see the indicator scale smaller and stays as you drag until you let go
3. Repeat the above in Safari and notice the indicator does not transform until you start dragging and doesn't transform back upon letting go
It may help to visualize it better, the `--indicator-transform` property can be changed on the segment buttons like `--indicator-transform: scale(0.5)`
Repeat on this branch, see the scale …
=> fix(segment): add activated class directly to segment button

core/src/components/label/label.ios.scss
Issue Number: https://github.com/ionic-team/ionic/issues/20407
Subpixel font-sizes + CSS animations seem to cause some odd visual glitches in Safari, so I've opted to remove the subpixel font size here. There should be no noticeable difference in most browsers as the difference in size is only 0.4px.
This bug has no impact on browsers that support Web Animations.
- Changed `13.6px` --> `14px`
=> fix(label): remove subpixel font-size to prevent visual glitches

angular/src/schematics/add/index.ts
`ng add @ionic/angular@next` throws error when add to angular project, because it have duplicate project root. 
Example: 
> `Could not find file for path: projects/mobile/projects/mobile/src/app/app.module.ts` this fix will only use project root once
This fix will update for Angular Ivy (Angular 9.0.1)
Already try so much but I unable to make build and test on windows, I getting much error on `sass` so I not tested yet
- Fix schematic for Angular project
`ng add @ionic/angular` or `ng add @ionic/angular@next`
Issue Number: #20435
Unchanges
=> fix(schematic): correct path for angular project

core/src/components/searchbar/searchbar.tsx, core/src/components/searchbar/test/basic/index.html
Issue Number: https://github.com/ionic-team/ionic/issues/20456
- Ensured that placeholder content is being interpreted as plain text.
- Also added an `raf` to help with race conditions when getting the width of the temporary span. It doesn't 100% fix the issue, but it significantly helps.
=> fix(searchbar): properly align placeholder

packages/react/src/components/index.ts
Issue Number: https://github.com/ionic-team/ionic/issues/20489
- Added `close` to internal icons imported. Close icon now shows on expanded FAB.
=> fix(fab): add close icon to internal icons for react

angular/src/directives/control-value-accessors/value-accessor.ts, core/src/components.d.ts, core/src/components/segment-button/segment-button.tsx, core/src/components/segment/readme.md, core/src/components/segment/segment.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/20257 https://github.com/ionic-team/ionic/issues/20500
- `ionChange` is now emitted when the user removes their pointer from screen (And if the value has changed)
- This moves segment back in line with the iOS spec, so it is being considered a bug instead of a breaking change.
=> fix(segment): only emit ionChange when user releases pointer from screen

core/src/utils/gesture/swipe-back.ts
Issue Number: https://github.com/ionic-team/ionic/issues/20505
- Swipe handler for some reason gives values <0 and >1 which is incorrect. Added a TODO to investigate, but for now just clamp the values
=> fix(ios): clamp out of bounds values for swipe to go back

core/src/components/segment-button/segment-button.scss, core/src/components/segment/test/basic/index.html
Issue Number: https://github.com/ionic-team/ionic/issues/20381 Adding divs and other content inside of `ion-segment-button` prevented that button from getting selected when clicking inside of the custom content.
- Inner divs no longer have pointer events, so they cannot interfere with the click events on segment
=> fix(segment): inner div no longer interferes with click events

core/src/components/action-sheet/usage/react.md
The icons in buttons were not working. I've done the following changes:
- added: import { <iconNames> } from 'ionicons/icons'
- changed: removed quotes from "icon" properties inside "buttons" array
- changed: "arrow-dropright-circle" (does not exist in ionicons v5) to "playCircleOutline" (camelCase instead of dashes)
The icons in buttons were not working in the usage exxample code for React.
Icons working :)
- added: import
- changed: strings to variables in buttons.icon
- changed: arrow icon from ionicons v4 to play icon from v5
=> Update react.md - usage example for IonActionSheet

core/src/components/modal/animations/ios.enter.ts
Issue Number: https://github.com/ionic-team/ionic/issues/20572
- BG color for swipeable modal can be overridden now
=> fix(modal): swipeable modal background should be able to be overridden

core/src/components/modal/modal.tsx, core/src/css/core.scss
Issue Number: https://github.com/ionic-team/ionic/issues/20569
- Ensure that global modal card styles only apply to iOS mode
- Ensure that `modal-card` class only added when mode === ios
=> fix(modal): swipeable modal styles only apply to ios

core/src/utils/hardware-back-button.ts, core/src/utils/menu-controller/index.ts, core/src/utils/overlays.ts
Issue Number: https://github.com/ionic-team/ionic/issues/20559
Tapping the hardware back button does not close an open side menu
- Tapping the hardware back button closes the open side menu
=> fix(menu): hardware back button now dismisses side menu if open

.scripts/common.js, .scripts/release.js, package.json
- rename all references of `tag` to either `gitTag` or `npmTag` based on what they contain since this was confusing throughout
- add the code to publish to git as a prerelease if the npm tag is `next`
- log the version when asking if the npm tag is correct
=> chore(release): update to latest octokit and usage

core/src/components/modal/animations/ios.enter.ts, core/src/components/modal/animations/ios.leave.ts, core/src/components/modal/modal.ios.scss
Having both the presenting element's header and the modal's header be the same color, the result looks odd almost like they are the same element. Native iOS adds a bit of contrast on the presenting element (ex: go to dark mode, and open the compose message modal on Messages) that accounts for this.
- Card modal adds contrast to presenting element
- Set backdrop opacity to 0 for this and removed the backdrop animation
=> fix(modal): card style modal now adds appropriate contrast

core/src/components/slides/slides-vendor.scss, core/src/components/slides/test/vertical/e2e.ts, core/src/components/slides/test/vertical/index.html
Slides doesn't take up a set height so it will show some of the inactive slides when direction is set to vertical
Issue Number: fixes #17341
Dev build: `5.1.0-dev.202002241801.ce23bbc`
This sets the slides height to 100% which will ensure that only the active slide is visible until swiping.
=> fix(slides): set height to 100% for vertical slides

core/src/components/select/select.scss, core/src/components/select/select.tsx, core/src/components/select/test/custom/e2e.ts, core/src/components/select/test/custom/index.html
This can be considered a feature or a fix, due to the fact it adds a new part, but we haven't documented any of these yet so I'm not sure which way to lean here.
You cannot change the opacity of the select icon or target the placeholder color with the current parts.
Placeholder - Due to the fact that the placeholder and value share the same div, you would have to be able to target it based on the `select-placeholder` class which does not work with parts. 
Select Icon - The opacity was set on the inner icon, so you can change the color using `::part(icon)` but it will still have the default `.33` opacity. I added a part for `icon-inner` since that is where the actual arrow is …
=> fix(select): add icon-inner & placeholder part

core/src/components/back-button/back-button.scss, core/src/components/back-button/back-button.tsx, core/src/components/button/button.ios.scss, core/src/components/button/button.scss, core/src/components/button/button.tsx, core/src/components/buttons/buttons.ios.scss, core/src/components/buttons/buttons.md.scss, core/src/components/menu-button/menu-button.scss, core/src/components/menu-button/menu-button.tsx, core/src/components/toolbar/test/custom/e2e.ts, core/src/components/toolbar/test/custom/index.html
Ran into issues during the conference app redesign & realized that certain variables when set for buttons in a toolbar did not behave as expected. You can see the below & after images in the next section. The test is under `toolbar/custom`.
| ---| ---|
| ![android-master](https://user-images.githubusercontent.com/6577830/75401362-eb74db00-58cf-11ea-8016-33b9544bb4e6.png) | ![android-branch](https://user-images.githubusercontent.com/6577830/75401269-9b961400-58cf-11ea-821f-91248e5b6508.png) |
| ![ios-master](https://user-images.githubusercontent.com/6577830/75401364-eca60800-58cf-11ea-969a-0ca385954f24.png) | …
=> fix(buttons): use proper button colors with variables set inside of a toolbar

core/src/components/datetime/datetime.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/20652
- The time picker will only polulate 0 when max is set to 0 for hour or minute.
=> fix(datetime): max property now works when hour, minute, or second set to 0

core/src/utils/transition/ios.transition.ts
Issue Number: https://github.com/ionic-team/ionic/issues/20696
I was using `largeTitleEl` instead of `largeTitleBox` which would result in something like ` undefinedpx`. This didn't matter in most cases since the offset was almost always 0px, but in modals it matters.
- Use `largeTitleBox` instead of `largeTitleEl` when determining the offsets
=> fix(ios): large title animation now works properly in a modal

core/src/components/action-sheet/animations/ios.enter.ts, core/src/components/action-sheet/animations/md.enter.ts, core/src/components/alert/animations/ios.enter.ts, core/src/components/alert/animations/md.enter.ts, core/src/components/loading/animations/ios.enter.ts, core/src/components/loading/animations/md.enter.ts, core/src/components/modal/animations/ios.enter.ts, core/src/components/modal/animations/md.enter.ts, core/src/components/picker/animations/ios.enter.ts, core/src/components/popover/animations/ios.enter.ts, core/src/components/popover/animations/md.enter.ts
Issue Number: https://github.com/ionic-team/ionic/issues/20608
Users can accidentally tap the screen twice when opening an overlay such as a modal. This results in a jarring behavior where the modal that was opening suddenly transitions to its closing animation.
- Set `pointer-events: none` on the backdrop on the entering animations, and remove it when the animation is done. This will prevent the double tap issue. There is no need to do the same logic for the dismiss animation as double tapping the backdrop on dismiss currently does nothing.
- No need to do this for toast as there is no backdrop
- Still allow developers to call the dismiss method or tap Esc as it is possible …
=> fix(): prevent accidental dismiss of overlays when tapping screen twice

core/src/components/modal/animations/ios.enter.ts, core/src/components/modal/animations/ios.leave.ts
Issue Number: https://github.com/ionic-team/ionic/issues/20697
- Changed `%` to use `vh`
- This was not an issue in v4 as had some extra hacks to compute the proper offsets (left over from the v3/ days when I presume vh did not have adequate browser support).
=> fix(modal): leave animation transitions modal completely out of viewport on ipad

core/src/components/modal/animations/ios.enter.ts, core/src/components/modal/animations/ios.leave.ts, core/src/components/modal/modal.ios.scss
Issue Number: https://github.com/ionic-team/ionic/issues/20706
- Added fallback for browsers that do not support `max()`. We do not need to worry about statusbar padding since browsers like Gecko/Firefox will not be used as the engine for standalone Cordova/Capacitor apps.
=> fix(modal): swipeable modal now works in firefox

core/src/components/header/header.ios.scss
Issue Number: https://github.com/ionic-team/ionic/issues/20691
- Default to using `--ion-background-color`
=> fix(header): collapsable header should default to using content background

core/src/components/header/header.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/20725
- Adding the `header-collapse-main` class happens in a `writeTask` which is async, so the element may not exist when the callback gets run. Added a check to only add the class if the element exists.
=> fix(header): collapsible header now works when navigating quickly

core/src/components/label/label.scss, core/src/components/label/test/headings/e2e.ts, core/src/components/label/test/headings/index.html
Headings that are put in the slot of an `ion-label` don't inherit the `text-overflow: ellipsis` style.
Issue Number: #17087.
- Adds styling for slotted headings to inherit `overflow` and `text-overflow`.
If anyone really wanted headings inside labels to just have hidden overflow (very unlikely), they'd need to explicitly set the overflow.
Closes #17087.
| ---| ---|
| ![`master`](https://user-images.githubusercontent.com/6577830/76435610-989a2980-638d-11ea-906c-beeebc1dd57d.png) | ![`branch`](https://user-images.githubusercontent.com/6577830/76435623-9b951a00-638d-11ea-9037-c1a56204bc17.png) |
=> fix(label): text overflow for slotted headings

core/src/components/segment/segment.scss
A scrollable segment shows a horizontal scrollbar (e. g. on Windows) even if there is no overflow.
Issue Number: #20758
A scrollable segment only shows a scrollbar if it overflows horizontally.
Closes #20758.
=> fix(segment): scrollable segments only show scrollbar if they overflow

core/src/utils/input-shims/hacks/scroll-assist.ts, core/src/utils/input-shims/input-shims.ts
Issue Number: https://github.com/ionic-team/ionic/issues/19589
At some point, scroll assist broke. I do not know if it was due to Ionic, an upgrade to Cordova/Capacitor, or an upgrade to iOS. The problem that exists now is that scroll assist is trying to scroll the input into view _before_ the browser has rendered any scroll height updates. In other words, scroll assist tries to scroll to a point that is more than the currently rendered max scroll area.
This PR adds the callback to scroll into a resize event listener. This will cause the scroll to either wait for the resize event to happen or until the fallback timer fires after 1000ms -- whichever happens first.
- Listen for …
=> fix(): scroll assist now works properly

core/src/components/slides/slides.tsx
When running `stencil build --prod` in the stencil conference app the following error happens prior to this PR:
```
[12:28.5]  prerendering failed in 4.75
s
[ ERROR ]  Hydrate Error: /tutorial
ReferenceError: MutationObserver is not defined at
Slides.connectedCallback
```
- This fixes that error on the prerender
=> fix(slides): check that mutation observer is defined for ssr

core/src/components/item-sliding/item-sliding.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/20773
- Added gesture offset to ensure swipe to go back can still work with item-sliding
=> fix(item-sliding): account for swipe to go back gesture when opening item-options

angular/src/schematics/add/index.ts, angular/src/schematics/utils/ast.ts, angular/src/schematics/utils/config.ts
Ionic CLI added a new "--multi-app" option for working with mono-repositories in https://github.com/ionic-team/ionic-cli/commit/42c51996632cdbc6ad6e514f36a584e3a450e380, this includes improved support for updating Angular CLI workspaces by using
```
ng add @ionic/angular --project=demo-project
```
This behavior is documented in the new [Angular-Monorepo](https://github.com/ionic-team/ionic-cli/wiki/Angular-Monorepo) wiki page; but the generated `angular.json` file is not valid because some schematic code always uses `app` as the project name.
To reproduce the issue, just follow the steps described in the [Angular-Monorepo](https://github.com/ionic-team/ionic-cli/wiki/Angular-Mon …
=> fix(angular): Fix --multi-app support for ng-add schematic

core/src/components/modal/modal.ios.scss
Issue Number: https://github.com/ionic-team/ionic/issues/20783
- Added `pointer-events: none` to backdrop in card modal to bring it back in line with the native iOS spec
=> fix(modal): backdrop should not be tappable on card-style modal on smaller screens

core/src/components/refresher/refresher.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/20803
- Wrap `resetNativeRefresher` calls in an raf to give the browser a chance to re-render otherwise refresher is left at an inconsistent state. This is only really for when the complete callback is called synchronously (RefresherState updates seem to happen in the same frame in this case which causes issues)
=> fix(refresher): properly dismiss refresher when completed synchronously

core/src/components/textarea/textarea.tsx
Remove setting the nativeInput height to 'initial' before resetting it to scrollHeight in Textarea.runAutoGrow
closes #19193
- [] Tests for the changes have been added (for bug fixes / features)
Issue Number: #19193
When adding text into an autoGrow textarea, the browser window (or scroll element) is no longer automatically scrolled to the top of the textarea
As far as I know, this doesn't introduce any breaking change. I wasn't sure how to add automated tests for this, but I'd be happy to take care of it if someone were able to point me in the right direction.
The function that I changed had the following comment above it: `// TODO: performance hit, this cause layout …
=> fix(textarea): properly adjust auto-grow textarea height on scrolled content

core/src/components/header/header.tsx, core/src/components/title/title.ios.scss
- Sets default for cloned element to be `--ion-text-color`. This helps on dark mode where the large title during the transition used to be black
=> fix(title): large title now inherits global color styling during nav transition

core/src/css/core.scss
Issue Number: https://github.com/ionic-team/ionic/issues/20878
- Previously our workaround applied to card-style modals only, but a user pointed out this issue happens with all modals. I have expanded the CSS workaround to apply to all modals on iOS mode.
=> fix(modal): properly inherit border radius for modals on Safari

core/src/components/slides/slides.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/20356
- Synchronously destroy swiper instances to avoid race conditions in multiple connected/disconnected callbacks
short breakdown of the issue for future reference:
1. Component is added as a sibling to ion-router-outlet.
2. connectedCallback is called. Swiper is initialized.
3. Ionic moves the component to be a child of ion-router-outlet.
4. disconnectedCallback is called. Work begins to tear down Swiper.
5. connectedCallback is called. Swiper is initialized.
The problem lies in step 4. The code to destroy swiper is called after an asynchronous call to get the Swiper instance. In other words, while …
=> fix(slides): slides no longer breaks when Angular Ivy enabled

core/src/utils/input-shims/hacks/scroll-assist.ts
Issue Number: https://github.com/ionic-team/ionic/issues/20922
- Listen for keyboardWillShow event and reduced timeout from 1000 to 300ms
=> perf(all):  improve scroll assist responsiveness

core/src/components/split-pane/split-pane.ios.scss, core/src/components/split-pane/split-pane.md.scss, core/src/themes/ionic.mixins.scss
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been reviewed and added / updated if needed (for bug fixes / features)
Issue Number: 20994
[https://github.com/ionic-team/ionic/issues/20994]()
In split-pane component, RTL mode now shows the border between the two panes
=> fix(split-pane): show border in RTL mode

packages/react/src/components/navigation/IonTabBar.tsx
Solve the problem that IonTabBar type does not have style attributes etc. in JSX.
closes #21006
In JSX, there is no style attribute etc for IonTabBar type.
Issue Number: #21006
- In JSX, style attribute etc are added to the IonTabBar type.
=> fix(react): IonTabBar properly extends IonicReactProps

core/src/components/searchbar/searchbar.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/21013
- Added `aria-hidden` to the search outline icon since it is purely decorative
- Added `aria-hidden` to the div that contains the cancel icon/text. Since either text or an icon is displayed, I didn't think it made sense to add special logic to each one. I added an `aria-label` to the parent button that defaults to the value of `cancelButtonText`. There is no breaking change because `cancelButtonText` defaults to "Cancel", which is what the aria-label value was hardcoded to previously.
=> fix(searchbar): screen readers correctly announce the cancel button text

.github/CONTRIBUTING.md, .github/ionic-issue-bot.yml
Changed a few things:
1. Added a guide on how to create a good code reproduction (see also: https://github.com/ionic-team/ionic-docs/pull/1375)
2. Changed autoclose timeout on `needs reply` from 30 days to 14 days.
3. Added autoreply for `ionitron: needs reproduction` label
4. Added autoclose timeout of 14 days for `ionitron: needs reproduction` label.
=> chore(): update contributing docs, update ionitron bot

core/src/components/textarea/textarea.tsx
Fixes #18993
When an `ion-textarea` element with `auto-grow="true"` is used within an `ion-modal`, it is shown correctly on the first load, but each subsequent load of the modal results in a `textarea` element height of 0.
Issue Number: #18993
The `textarea` now loads with the correct height on subsequent loads of the modal
I went to add tests for this and realised that the problem is not present when used in a pure javascript project. I first saw the issue in an `@ionic/angular` project. I have tested this with a locally linked build of `@ionic/core` and this solves the problem.
=> fix(textarea): set correct height in a modal when auto-grow is set

core/src/components/modal/modal.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/21072
- Swipe To Close gesture is now enabled/disabled is swipeToClose prop is updated.
=> fix(modal): swipeToClose property is now reactive

core/src/components/back-button/back-button.tsx
Issue Number: https://github.com/ionic-team/ionic/issues/21043
- Added `aria-hidden` to back button icon and back button text element
- Added `aria-label` to parent `button` element. Since the icon is sometimes decorative sometimes semantic, I think it makes sense to just place the aria-label on the parent button rather than add logic for the icon and label.
=> fix(back-button): screen readers correctly announce the back button text

angular/src/providers/gesture-controller.ts
blocks https://github.com/ionic-team/ionic-docs/pull/1383
Issue Number: https://github.com/ionic-team/ionic/issues/20529
For performance reasons, we do not run gesture callbacks inside of angular zones. This has a side effect of causing templates to not update when using gesture handlers to alter the state of the app.
- Added an option to run all callbacks inside of angular zone. Defaults to `false`.
Developers can also selectively run their handlers in ngzone by wrapping their callbacks like this:
```typescript
import { NgZone } from '@angular/core';
...
constructor(private zone: NgZone) {}
...
const gesture = this.gestureController.create({
el: …
```
=> feat(gesture): add option to run inside NgZone for Angular apps

angular/src/providers/nav-controller.ts, angular/src/providers/platform.ts, core/src/components/router/router.tsx, core/src/interface.d.ts, core/src/utils/hardware-back-button.ts, core/src/utils/test/hardware-back-button.spec.ts, packages/react-router/src/ReactRouter/NavManager.tsx, vue/src/router.ts
blocks https://github.com/ionic-team/ionic-docs/pull/1356
Issue Number: https://github.com/ionic-team/ionic/issues/17824
- Added feature to allow multiple handlers to be processed sequentially
- Added docs with examples
- Added tests
=> feat(): add ability to continue processing hardware back button events

core/src/components/refresher/refresher.tsx
Refresher was not waiting for content to be ready. In Ionic React this was causing a race condition where the content height was 0.
- Refresher now awaits componentOnReady
=> fix(refresher): properly calculate content dimensions in native ion-refresher

core/src/components/router/router.tsx, core/src/components/router/test/parser.spec.tsx, core/src/components/router/test/path.spec.tsx, core/src/components/router/utils/path.ts
Issue Number: fixes https://github.com/ionic-team/ionic/issues/21062
- Account for presence of query string
=> fix(router): account for query string when pushing page

core/src/utils/input-shims/hacks/scroll-assist.ts
Issue Number: fixes https://github.com/ionic-team/ionic/issues/21196
- For content that is below the fold, we need to wait for the webview to be resized/keyboard to be opened in order for scroll assist to work properly
=> fix(all): improve scroll assist reliability for below the fold inputs

core/src/components/segment-button/segment-button.tsx
Issue Number: fixes https://github.com/ionic-team/ionic/issues/21271
- Added explicit `false` to non-pressed buttons for VoiceOver on macOS announces the selected one properly
=> fix(segment-button): screen readers now announce selected state properly

core/src/themes/ionic.mixins.scss
Dev build: `5.2.0-dev.202005112151.7166a29`
Issue Number: closes #20993 closes #20743 
Currently the `ion-hide-down` breakpoints look like:
```scss
@media (max-width: 576px) {
.ion-hide-sm-down {
display: none !important;
}
}
@media (max-width: 768px) {
.ion-hide-md-down {
display: none !important;
}
}
@media (max-width: 992px) {
.ion-hide-lg-down {
display: none !important;
}
}
@media (max-width: 1200px) {
.ion-hide-xl-down {
display: none !important;
}
}
```
This causes interference when both hide **up** and hide **down** media queries are used for the exact breakpoint.
1. Open the following Codepen: https://codepen.io/brandyscarney/pen/OJyEggx
2. Drag the width of the …
=> fix(display): update breakpoint max to reduce by 0.02px

core/src/components/input/input.tsx, core/src/components/input/test/tabindex/index.html, core/src/components/item/item.tsx
Issue Number: fixes #17515
Dev build: `5.1.0-dev.202005041740.7d6b4b5`
This is not the best code ever written, but it does work. I can't think of a way to ignore `tabindex` on the main host element without removing it after passing it down. Open for review.
- Check if input has a `tabindex` attribute, pass it down if so and then remove it
- Makes it so the `ion-input` is ignored from being tabbed to, but the native input can still be tabbed to
- Delegates focus on the item to the input, can set `tabindex` on `ion-item` and it will pass down to the input in Chrome and Safari ignoring the focus on the item, in Firefox it will tab to the item then the input
To test this PR, …
=> fix(input): check for tabindex and pass it properly to native input

core/src/components/textarea/textarea.scss
Issue Number: fixes https://github.com/ionic-team/ionic/issues/18543
- Uses inheritance for allow for max-width/max-height instead of exposing a CSS variable
- alternative to https://github.com/ionic-team/ionic/pull/19617
=> fix(textarea): native textarea inherits max-width and max-height

angular/src/index.ts, core/src/utils/platform.ts
blocks https://github.com/ionic-team/ionic-docs/pull/1423
Issue Number: resolves https://github.com/ionic-team/ionic/issues/17353
- Export getPlatforms, isPlatform
=> feat(angular): expose getPlatforms and isPlatform

core/src/components/action-sheet/action-sheet.ios.scss, core/src/components/action-sheet/action-sheet.scss, core/src/components/action-sheet/action-sheet.tsx, core/src/components/alert/alert.ios.scss, core/src/components/alert/alert.tsx, core/src/utils/gesture/button-active.ts, core/src/utils/native/haptic.ts
Issue Number: fixes https://github.com/ionic-team/ionic/issues/21052
- Added a custom gesture that a) adds `ion-activated` to action sheet/alert buttons and b) triggers a "selectionChanged" haptic feedback when pointer is over a button
=> fix(ios): add haptic drag gesture for action sheet and alert components

core/src/components/action-sheet/action-sheet-interface.ts, core/src/components/toast/toast-interface.ts
A toast button can't take an async function that returns `Promise<void>` as its handler.
```
Type '() => Promise<void>' is not assignable to type '() => boolean | void | Promise<boolean>'.
Type 'Promise<void>' is not assignable to type 'boolean | void | Promise<boolean>'.
Type 'Promise<void>' is not assignable to type 'Promise<boolean>'.
Type 'void' is not assignable to type 'boolean'. ts(2322)
```
- A toast button can take an async function that returns `Promise<void>` as its handler.
~There might be other button interfaces with this issue...~
**Update:** fixed the same thing for the action sheet (after checking all similar interfaces).
=> fix(toast, action-sheet): button handler can return `Promise<void>`

core/src/components/item/item.scss
Related to #17670 and pull request #18502
Currently, a relatively positioned div within an `ion-item` element cannot overflow any absolutely positioned content it contains.
If the overflow property on the `.input-wrapper` is set to inherit, it is now possible to overflow as expected.
I realise that this is an addition to a previous pull request (#18502) but I could see no reason to not include the `.input-wrapper` in the inheritance.
=> fix(item): input-wrapper now inherits overflow

core/api.txt, core/src/components.d.ts, core/src/components/action-sheet/action-sheet.tsx, core/src/components/action-sheet/readme.md, core/src/components/alert/alert.tsx, core/src/components/alert/readme.md, core/src/components/loading/loading.tsx, core/src/components/loading/readme.md, core/src/components/modal/modal.tsx, core/src/components/modal/readme.md, core/src/components/picker/picker.tsx, core/src/components/picker/readme.md, core/src/components/popover/popover.tsx, core/src/components/popover/readme.md, core/src/components/toast/readme.md, core/src/components/toast/toast.tsx
Current behavior - there is no optional typing of generic usages `OverlayEventDetail`
Issue Number: resolves #21368
- add optional typings of usages `OverlayEventDetail`
=> feat(all): add optional typing of methods with generics of OverlayEventDetail

core/src/components/modal/modal.ios.scss
Issue Number: fixes https://github.com/ionic-team/ionic/issues/21449
- Height was not being set using the css var, so it was annoying to override.
=> bug(modal): set card-style modal height using the --height css variable

core/src/components/router/router.tsx
Fixes #21300 
When navigating from the root route to a sibling and back the animation is "forward" is correctly applied. If you go to a sibling a second time the back animation is lost.
Issue Number: 21300
The animation is applied also the second time the user navigates back to the root.
=> fix(router): going back uses correct nav transition

core/src/components/router-outlet/route-outlet.tsx
Issue Number: fixes https://github.com/ionic-team/ionic/issues/21495
The problem was that when you did not provide an animation via `routerAnimation`, you would get an object that looked like:
```
{
...
animationBuilder: undefined
...
}
```
Due to the way the code was structured, Ionic would properly get `config.get('navAnimation')`, but it would get overridden by the undefined `animationBuilder` in `opts`.
- let the `animationBuilder` option take precedence when using spread on `opts`
=> fix(angular): fix issue where navAnimation was being incorrectly overridden 

core/src/utils/gesture/button-active.ts
Issue Number: fixes https://github.com/ionic-team/ionic/issues/21503
- Only propagate click if the starting button !== current button
=> fix(action-sheet, alert): resolve double click issue when running in iOS mode on chrome

core/src/utils/transition/ios.transition.ts
Page w/ a large title shows its toolbar when transitioning in because the ios transition forces opacity = 1 when --opacity may have been set otherwise
- iOS transition now respects --opacity css var
- Prevents a flicker of the toolbar when doing a transition to a page containing a large title
=> fix(ios): respect toolbar opacity when doing nav transition

core/src/components/input/input.scss, core/src/components/input/input.tsx
Issue Number: fixes https://github.com/ionic-team/ionic/issues/21549
1. The clear button now always appears if there is text in the input regardless of focus state. This brings this inline with similar components on iOS and on the web. (for example, see any of the search boxes on iOS, or see the search on http://google.com/).
2. The clear button can now be tabbed to by removing `tabindex="-1"` which is also more in line with components on the web.
3. When tabbing to the clear button, you can now press "Enter" to click it. The one downside is that it blurs the input, but for touch-based presses, the behavior remains the same.
=> fix(input): clear button can now be tabbed to

core/api.txt, core/src/components/select/readme.md, core/src/components/select/select-interface.ts
`SelectChangeEventDetail` is not generic and `value` has type `any | any[] | undefined | null` (which basically boils down to `any`).
Issue Number: Closes #20220.
- `SelectChangeEventDetail` is now generic so that `value` can be strongly typed, e. g. `CustomEvent<SelectChangeEventDetail<number>>` for a change handler when the values are numbers. By default (if not specified) the generic type is `any` which means that it's fully backwards compatible.
=> feat(select): add optional generic typings

core/api.txt, core/src/components.d.ts, core/src/components/input/input.tsx, core/src/components/input/readme.md, core/src/components/input/test/basic/index.html, core/src/components/textarea/readme.md, core/src/components/textarea/textarea.tsx
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/17363
- The ionBlur and ionFocus events now return the native FocusEvent received. This allows devs to look at `relatedTarget`  I.e. the element that is now focused (useful after another input loses focus)
=> feat(input, textarea): expose native events for ionBlur and ionFocus

core/src/components/virtual-scroll/virtual-scroll.tsx
Virtual scroll will calculate the offset top by traversing the parents until it meets the ion content element.
This is a problem as `offsetTop` is not using the parent element but the `offsetParent` element thus possibly counting the same offsetParent multiple times and returning a wrong offset. That means, it will recount the same `offsetParent` multiple times for each non-positioned element nested between `ion-content` and `ion-list`.
- Calculation of offset is now done by traversing the offsetParents until it finds the ion content
- This ensures the correct offset top regardless of how many nested components there are in-between the ion-content
=> fix(virtual-scroll): fix top offset calculation

packages/react-router/src/ReactRouter/IonReactHashRouter.tsx, packages/react-router/src/ReactRouter/IonReactRouter.tsx, packages/react-router/test-app/cypress/integration/tab-context.js, packages/react-router/test-app/src/App.tsx
=> fix(react): adding custom history to IonReactRouter, closes #20297

core/src/components/card/card.ios.scss, core/src/components/card/card.ios.vars.scss, core/src/components/card/card.md.scss, core/src/components/card/card.md.vars.scss, core/src/themes/ionic.theme.default.ios.scss, core/src/themes/ionic.theme.default.md.scss
Docs PR: https://github.com/ionic-team/ionic-docs/pull/1542
Starters PR: https://github.com/ionic-team/starters/pull/1393
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/21694
- The card bg color on dark mode was wrong because it follows `ion-item`'s background color
- I exposed a `--ion-card-background` global variable so we can separate the two and properly set the background color for the card.
=> feat(card): expose global card css variable

core/src/components/action-sheet/action-sheet.tsx, core/src/components/alert/alert.tsx, core/src/components/loading/loading.tsx, core/src/components/modal/modal.tsx, core/src/components/picker/picker.tsx, core/src/components/popover/popover.tsx, core/src/components/toast/toast.tsx, core/src/utils/overlays.ts
For custom elements builds, overlays cannot use `hasAttribute()` in the constructor, so moving it to connectedCallback instead.
=> Prepare overlay

core/src/interface.d.ts
Ensure 3rd party libraries can read Ionicon's JSX types.
=> fix(jsx): export ionicons jsx interface

core/src/components/action-sheet/action-sheet.tsx, core/src/components/action-sheet/test/basic/e2e.ts, core/src/components/alert/alert.tsx, core/src/components/alert/test/basic/e2e.ts, core/src/components/datetime/test/basic/e2e.ts, core/src/components/loading/loading.tsx, core/src/components/loading/test/basic/e2e.ts, core/src/components/modal/modal.tsx, core/src/components/modal/test/basic/e2e.ts, core/src/components/picker/picker.tsx, core/src/components/popover/popover.tsx, core/src/components/popover/test/basic/e2e.ts, core/src/components/popover/test/basic/index.html, core/src/utils/overlays-interface.ts, core/src/utils/overlays.ts
Issue Number: fixes https://github.com/ionic-team/ionic-framework/issues/21647
- All overlay components (except ion-toast) now have their focus trapped inside the overlay component.
- This is to bring it in line with WCAG recommendations: https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html
=> fix(overlays): trap focus inside overlay components except toast

core/src/components/modal/readme.md, core/src/components/modal/usage/react.md
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/21773
- Updated usage to pass in IonRouterOutlet ref
=> docs(modal): add correct card-style modal usage for react

packages/react-router/test-app/build.sh, packages/react-router/test-app/cypress/integration/routing.spec.js, packages/react-router/test-app/package-lock.json, packages/react-router/test-app/package.json, packages/react-router/test-app/src/pages/routing/Tabs.tsx, packages/react/src/components/navigation/IonTabBar.tsx
=> fix(react): setting active tab properly on mount, closes #21830

core/stencil.config.ts
Stencil 2 will update the extras defaults to not include many of the polyfills and shims by default. Setting the configs here ensures they stay enabled so there isn't a breaking change for Ionic v5 users.
=> chore(build): set stencil extras config

core/src/components/action-sheet/action-sheet.tsx, core/src/components/alert/alert.tsx, core/src/components/back-button/back-button.tsx, core/src/components/button/button.tsx, core/src/components/header/header.tsx, core/src/components/menu/menu.tsx, core/src/components/nav/nav.tsx, core/src/components/slides/slides.tsx, core/src/components/split-pane/split-pane.tsx, core/src/components/tab-button/tab-button.tsx
Stencil 2 is removing deprecated APIs, and these are the remaining ones Ionic has been using.
=> chore(api): internal updates required for stencil 2 upgrade

packages/vue-router/src/router.ts
Previously, we set an initial location history view item no matter the path. This was to work around some undefined errors when on the initial page (if there was no previous page). This was wrong as it set a location history item even for an initial page redirect. This results in canGoBack being wrong as there were always 2+ items in the history stack.
- No longer set initial route, let that happen naturally by listening to the data vue router gives us.
=> fix(vue): canGoBack now returns correct result with initial load redirect

packages/vue/src/hooks.ts, packages/vue/src/index.ts
We need a way to determine if users "canGoBack" when listening to hardware back button events.
Expose a hook that users can use to access the router. This also allows us to selectively expose methods on the Ionic Vue router while keeping other methods accessible for internal component usage.
=> feat(vue): add hook to access Ionic Vue router

core/src/components.d.ts, core/src/components/item/item.tsx, core/src/components/item/test/inputs/index.html, core/src/components/textarea/readme.md, core/src/components/textarea/textarea.tsx
:warning: dev build: `5.4.0-dev.202009081606.5ddd37f` :warning:
Issue Number: fixes #22037 resolves #22032
- Check if the event target is an ion-item before focusing the first input, thus if another input exists it won't change focus
- Add support for focusing ion-textarea if that exists as the first input
=> fix(input): only focus the first input / textarea when clicking on the parent item

core/package-lock.json, core/package.json, packages/vue-router/package-lock.json, packages/vue/package-lock.json, packages/vue/src/vue-component-lib/utils.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22076
- Internal logic was correct in terms of setup, but it was getting wiped with each render. Ensured that correct props were getting set every render.
=> fix(vue): using refs with v-model now works properly

core/src/components/segment/segment.scss
Text can be selected while swiping on desktop, can be reproduced in the demo here: https://ionicframework.com/docs/api/segment
- When swiping between the segment buttons, it doesn't allow text to be selected anymore
When testing this PR, the selection will be fixed for Chrome, but not work in Safari. This is because Stencil generates the prefixed CSS during the build.
=> fix(segment): do not allow text selection on desktop

packages/vue/src/framework-delegate.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22189
- Controllers did not pass props to component, so I updated VueDelegate to do this. Overlay components in template were not affected.
=> fix(vue): pass props to component when using modal and popover controller

core/src/components/datetime/datetime-util.ts
It was previously thought to be the intended behavior to switch from am -> pm and vice versa when going from 12 am / pm to another number but I've discovered this was never how it worked.
Issue Number: fixes #18924 fixes #22171 fixes #22199
- No longer automatically switch between AM/PM when going from or to 12
=> fix(datetime): remove the automatic switching from am to pm and vice versa

.github/ionic-issue-bot.yml, .github/labeler.yml, .github/workflows/label.yml
This adds the Github workflow to automatically label PRs based on the files changed, removing the code that is done by ionitron. I have tested it out in a sample repository here: https://github.com/brandyscarney/testing-labeler/pull/3
It seems to be behaving as desired, removing labels when the changes are reverted and adding them based on the file path.
=> chore(github): add pull request labeler for packages

core/src/components/datetime/datetime-util.spec.ts, core/src/components/datetime/datetime-util.ts, core/src/components/datetime/test/basic/index.html, core/src/components/datetime/test/datetime.spec.ts
When using a format without `a` or `A` the `ampm` value was being set still which was causing it to jump to the incorrect hour values.
Issue Number: fixes #22149
- Set the initial ampm value only when creating the columns, thus if the ampm column doesn't exist it won't get set
- Still gets set when changing am/pm
=> fix(datetime): do not set ampm when the column doesn't exist

core/src/components/popover/readme.md, core/src/components/popover/usage/javascript.md, core/src/components/popover/usage/react.md
Documentation updates to the popover usage
closes ionic-team/ionic-docs#1517
=> docs(popover): add the popover-example-page to core and event to react

packages/vue/src/components/IonRouterOutlet.ts, packages/vue/test-app/package-lock.json, packages/vue/test-app/package.json, packages/vue/test-app/src/views/Tabs.vue, packages/vue/test-app/tests/e2e/specs/navigation.js, packages/vue/test-app/tests/e2e/specs/tabs.js, packages/vue/test-app/tests/e2e/support/commands.js
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22237
- Added new way of checking "entering view"
=> fix(vue): improve swipe to go back reliability

core/src/components/select/select.md.vars.scss, core/src/components/select/select.scss
Label & select placeholder / label are not aligned
Issue Number: fixes #19887
- Properly align
| Before | After |
| ---| ---|
| ![before](https://user-images.githubusercontent.com/6577830/96159077-3a649480-0ee2-11eb-92f3-c9f68ba98961.png) | ![after](https://user-images.githubusercontent.com/6577830/96157422-47808400-0ee0-11eb-9b2a-1c28627347fc.png) |
=> fix(select): properly align label with select in item in md

packages/vue-router/src/router.ts, packages/vue-router/src/types.ts, packages/vue/test-app/src/router/index.ts, packages/vue/test-app/src/views/Routing.vue, packages/vue/test-app/src/views/RoutingParameter.vue, packages/vue/test-app/tests/e2e/specs/routing.js
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22324
- Use the history listener to just grab the action/direction since it fires before `router.beforeEach` and let the `router.beforeEach` callback handle calling the ion router method.
=> fix(vue): going back with query params now goes to correct view

packages/vue-router/src/router.ts, packages/vue/test-app/src/guards/Delay.ts, packages/vue/test-app/src/router/index.ts, packages/vue/test-app/src/views/Home.vue, packages/vue/test-app/tests/e2e/specs/routing.js, packages/vue/test-app/tests/e2e/specs/tabs.js
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22344
- Ionic Vue was reacting too soon to navigation changes by its use of `router.beforeEach`. This would cause transitions to happen before navigation was confirmed, leading to unexpected behaviors.
=> fix(vue): improve compatibility with route guards

core/src/components/app/app.scss
TODO give co-author credit from https://github.com/ionic-team/ionic-framework/pull/18369
`user-select: none` causes contenteditable to be non-selectable in WebKit but input and textarea work fine. This issue does not affect Chromium.
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/18368
- Added user-select: text to contenteditable
=> fix(ios): contenteditable elements are now selectable on iOS

core/src/components/range/range.tsx
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22335
- disconnectedCallback destroyed the range gesture, but it was never re-created on connectedCallback. Added extra code to recreate the gesture
=> fix(range): gesture is now properly re-created on connectedCallback

core/src/components/refresher/refresher.tsx
closes #22256 
Issue Number: #22256 
Like wrote in the linked Issue, the Refresher sometimes starts too early / buggy when used in iOS card style modal. I debugged this today and saw, that the ScrollElement's **offsetHeight** could be zero here:
https://github.com/ionic-team/ionic-framework/blob/c1455a839a25e3e23b7c9e7b7d930055b24c2ecb/core/src/components/refresher/refresher.tsx#L399
This cause the `setupiOSNativeRefresher` to not work properly, as **MAX_PULL** is zero then as well.
- Before loading the ScrollElement from the Content Element, wait for the Content's Component to be ready
=> fix(refresher): force content to be ready before saving the scrollEl

core/src/components/alert/alert.scss
TODO: Give co-author credit when merging
Issue Number: https://github.com/ionic-team/ionic-framework/pull/17776
The alert was not inheriting the height of `ion-app` because it had `position: fixed`. As a result, it was still being sized/positioned relative to the viewport.
- Changing to `position: absolute` now causes ion-alert to inherit the height from ion-app
=> fix(alert): correctly position alert when keyboard is open

core/src/components/segment-button/segment-button.ios.scss, core/src/components/segment-button/segment-button.scss, core/src/components/segment/segment.tsx
This reverts commit 68afc49e9ed27acffb0b765b7be6b03e8574850d in favor of https://github.com/ionic-team/ionic-framework/commit/9f44966d8572a27d8296b38ae4f3e689c76c2e44.
The new fix was supposed to revert this commit, but I must have forgotten to do it. The new fix is a more universal fix that should help us in other scenarios when using translate3d
-
-
-
=> chore(): revert old segment fix in favor of new one

packages/vue/package.json, packages/vue/scripts/build-web-types.js
Issue Number: resolves #19522 
This PR introduces bundling of web-types with `@ionic/vue` for in-editor documentation support. The web-types standard is an open source standard supported so far only by WebStorm and is bundled with various other Vue libraries, like `vuetify`, `bootstrap-vue` or `quasar`.
=> feat(vue): web-types support

core/src/components/textarea/readme.md, core/src/components/textarea/usage/vue.md
##
Current docs have code examples that will not work. `IonLabe` is written instead of `IonLabel`. This PR fixes those.
=> Fix typos in textarea docs (IonLabe -> IonLabel)

packages/vue/src/components/IonTabBar.ts, packages/vue/src/components/IonTabs.ts, packages/vue/test-app/src/views/TabsSecondary.vue, packages/vue/test-app/tests/unit/tab-bar.spec.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22456
- We now add the tab bar to the DOM before tabs-inner if it is supposed to be slotted on top.
=> fix(vue): tab bar now works with slot="top"

core/src/components/refresher/refresher.tsx
Sometimes the scrollEl's clientHeight is zero because the containing element is hidden. This results in the refresher firing too early.
- Added a default MAX_PULL value in the event the content height is 0.
=> fix(refresher): ios native refresher now works in side menu

packages/vue-router/src/types.ts, packages/vue-router/src/viewStacks.ts, packages/vue/src/components/IonRouterOutlet.ts, packages/vue/test-app/tests/unit/routing.spec.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22472
- Pass route props when rendering components
=> fix(vue): correctly pass route props to components

core/src/components/content/content.scss
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22473
- will-change: transform breaks position: fixed (this is the correct behavior according to the spec https://bugs.chromium.org/p/chromium/issues/detail?id=413456) so we use z-index to force a stacking context in WebKit instead.
=> perf(ios): move content to stacking context while preserving position: fixed behavior

core/src/components/backdrop/backdrop.tsx
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22102
- NVDA reads the backdrop as clickable since it has an onClick listener. However, this causes NVDA to announce "clickable" when the popover opens which is confusing
- Where users cannot tab to the backdrop, we chose to remove the backdrop from the screen reader tree entirely
=> fix(backdrop): nvda no longer incorrectly announces backdrop

core/src/components/router/test/guards/index.html, core/src/components/router/test/guards/router-link.e2e.ts, core/src/components/router/utils/matching.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22516
- Ensure that the beforeEnter and beforeLeave functions are preserved when re-mapping the route array
=> fix(router): navigation guards now fire when navigating to a page with params

core/src/components/select/readme.md
Fix broken link to the select-option page. The broken link can be seen here https://ionicframework.com/docs/api/select#styling-select-interface when clicking on "Select Options documentation"
The link "Select Options documentation" on the "Styling Select Interface" paragraph on [this page](https://ionicframework.com/docs/api/select#styling-select-interface) is broken.
The link open the page as expected.
=> docs(select): Fix broken link to select-option

packages/react/src/components/__tests__/createComponent.spec.tsx, packages/react/src/components/createComponent.tsx, packages/react/test/test-app/src/index.tsx
Using Ionic with the latest React strict mode generates lots of warnings.
Issue Number: #20972 
We no longer use the deprecated `ReactDom.findDOMNode` function, instead we use a ref.
Fixes #20972
=> fix(react): eliminate use of deprecated `findDOMNode`

core/src/components.d.ts, core/src/components/alert/alert.tsx, core/src/components/select/select.tsx, core/src/components/select/test/a11y/index.html
=> fix(select): announce placeholder, hide select text from screenreaders

core/src/components/skeleton-text/readme.md, core/src/components/skeleton-text/usage/vue.md
Fix skeleton-text component vue usage example
The skeleton-text usage example is broken.
The skeleton-text vue use example now works correctly.
=> docs(vue): fix skeleton-text usage example

core/src/components/refresher/refresher.tsx, core/src/components/refresher/refresher.utils.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22616
- wait for ion-refresher-content to be ready before checking for pulling/refreshing spinners
- This bug happens when using things like *ngIf in angular where the ion-refresher-content is not ready when connectedCallback is fired. This results in the non-native refresher being created
=> fix(refresher): refresher correctly detects native refresher when shown asynchronously

core/src/components/refresher/refresher.tsx
Issue Number: resolves #22636
- Clear old css set by non-native refresher when setting up native refresher
=> fix(refresher): clean up old css if calling refresh method before native refresher is setup

packages/vue/src/components/IonTabBar.ts, packages/vue/test-app/tests/unit/tab-bar.spec.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22642
- Added a check to make sure we are looking at a tab button and that the element has a tab prop
=> fix(vue): adding non tab button elements inside ion-tab-bar no longer causes errors

BREAKING.md, core/src/components/content/content.tsx, core/src/utils/config.ts
The transition shadow has not been considered experimental since v5, but we forgot to remove the config option.
The `experimentalTransitionShadow` config option has been removed, and the transition shadow is always visible on `ios` mode.
=> breaking(config): remove experimentalTransitionShadow config option

core/src/components/refresher/refresher.utils.ts, core/src/components/refresher/test/basic/index.html
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22706
- Revert to old query. Though not really sure why doing `ion-refresher-content .pulling-icon ion-spinner` works but doing `refresherContentRef.querySelector('.pulling-icon ion-spinner')` does not.
- Also both refresher tests were using the native refresher which is why we did not catch this. Reverted the basic test to using the old refresher.
=> fix(refresher): correctly detect spinner when using native refresher

packages/react/src/components/createOverlayComponent.tsx
Issue Number: resolves a regression in https://github.com/ionic-team/ionic-framework/commit/14e8441706c230da4669afaaf0028aaeaf4dbe0e by adding a better fix for https://github.com/ionic-team/ionic-framework/issues/22761
- Overlay now only unmounts component if overlay is not open or if overlay is in process of dismissing.
=> fix(react): add improved method for not unmounting component until overlay is dismissed

packages/react/src/components/IonRouterContext.tsx, packages/react/src/components/navigation/IonTabBar.tsx, packages/react/src/components/navigation/IonTabs.tsx
When IonTabBar is wrapped by a functional component or fragment, then IonTabs is unable to find it. This is a rare case, but adding the ability for a function component to manually state that is is an IonTabBar. Same for IonTabButtons.
=> refactor(react): find child IonTabBar also w/ a key

core/src/utils/input-shims/hacks/scroll-assist.ts
Issue Number: #21871
- Moving the input/focusing during touchstart seems to cancel the first click event, so we need to manually fire it ourselves.
=> fix(): scroll assist no longer prevents first click event from firing

core/src/components/select/select.tsx
Issue Number: https://github.com/ionic-team/ionic-framework/issues/22801
- Host element now exposes a `select-expanded` class
=> fix(select): class on component now indicates when select is open

core/package-lock.json, core/package.json, core/stencil.config.ts, packages/vue/src/ionic-vue.ts, packages/vue/src/proxies.ts, packages/vue/src/vue-component-lib/utils.ts
Issue Number: resolves #22870
The problem here is that when you do `@ionChange="myFn()"`, Vue does an `addEventListener` for `ionchange`. Since the underlying Web Component fires `ionchange` too, `myFn()` is being called before an `v-model` sync has happened (I.e. before the Vue wrappers have had a chance to react). This causes `v-model` to not be the correct value at the time `myFn` is called.
I previously worked around this by re-emitting the event from the Vue wrappers and calling `stopImmediatePropagation`. This had the unintended side effect of breaking components like `ion-radio` and `ion-radio-group` that rely on the `ionChange` event emitted from other components.
This …
=> fix(vue): ionChange events now propagate correctly

BREAKING.md, core/src/components/toast/toast.scss
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/21486
- `--white-space: normal` is the new default on `ion-toast`.
=> refactor(toast): whitespace variable now defaults to normal

core/src/components/radio-group/radio-group.tsx
Tested on Chrome macOS, Safari macOS, and Chrome Windows
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22716
- prevent browser's default behavior when pressing space bar
=> fix(radio-group): pressing space no longer jumps screen to bottom of page

BREAKING.md, core/src/themes/ionic.theme.default.ios.scss
Starters: https://github.com/ionic-team/starters/pull/1670
Docs: https://github.com/ionic-team/ionic-docs/pull/1835
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22780
- Updated toolbar and tab bar default background colors (fallback values)
=> refactor(ios): update toolbar and tabbar default background colors

packages/react/src/components/navigation/IonTabs.tsx
Issue Number: resolves #21827
- Correctly pass event handler props
=> fix(react): onIonTabsWillChange and onIonTabsDidChange event handlers are now properly bound to IonTabs

BREAKING.md, angular/src/providers/config.ts, angular/test/test-app/src/app/app.module.ts, angular/test/test-app/src/app/providers/providers.component.ts
Issue Number: https://github.com/ionic-team/ionic-framework/pull/19104
The `Config.set()` method has been removed. See https://ionicframework.com/docs/angular/config for examples on how to set config globally, per-component, and per-platform.
=> refactor(angular): remove Config.set

BREAKING.md, packages/vue-router/src/viewStacks.ts, packages/vue/src/components/IonRouterOutlet.ts, packages/vue/src/components/IonTabs.ts, packages/vue/test-app/src/router/index.ts, packages/vue/test-app/tests/e2e/specs/tabs.js, packages/vue/test-app/tests/unit/tab-bar.spec.ts
See https://github.com/ionic-team/ionic-framework/pull/22807
- New routes should be written as sibling routes to tabs.
=> refactor(vue): remove support for child routes nested inside of tabs

core/src/components/header/header.tsx, core/src/components/header/header.utils.ts
Issue Number: resolves #22829
- Check to make sure scrollTop is not 0 or negative before running collapsible large title callbacks.
=> fix(header): collapsed toolbar is no longer incorrectly shown when using ion-refresher

core/package-lock.json
There was a bug in npm <7.5.3 where optional dependencies were being duplicated as dependencies. npm 7.5.3 fixes this, but now we are getting diff issues on CI since it uses 7.5.3.
- Rebuilt package-lock changes with npm 7.5.3 to resolve this issue
=> chore(): update package-lock to account for npm 7.5.3 bug fix

core/src/components/progress-bar/progress-bar.scss, core/src/components/progress-bar/progress-bar.tsx, core/src/components/progress-bar/test/basic/index.html, core/src/themes/test/css-variables/index.html
TODO: Give co-author credit to domske
Issue Number: resolves #20098
- Don't place a white background on the buffer bar to allow theming to work properly
| Before | After |
| ---| ---|
| ![before](https://user-images.githubusercontent.com/6577830/108885194-7d8fec00-75d5-11eb-91ac-d91fe36896ea.png) | ![after](https://user-images.githubusercontent.com/6577830/108885189-7cf75580-75d5-11eb-9d3a-fcf1f2ff1f56.png) |
=> fix(progress-bar): use correct theme colors

core/src/components/progress-bar/progress-bar.scss, core/src/components/progress-bar/progress-bar.tsx
This fixes the previous. attempts of fixes. This pull-request should be the final fix. (Hopefully)
Issue Number: resolves #20098.
Could replace the pull-request: #22964
Now the component uses the Ionic theme colors and the buffer progress works correctly.
I made some changes like flip the component if reverted, instead of handle each child element separately. 
I hope it makes it less prone to error.
=> fix(progress-bar): use correct theme colors in dark mode

packages/vue/src/hooks.ts, packages/vue/src/index.ts, packages/vue/src/utils.ts, packages/vue/test-app/src/views/Home.vue, packages/vue/test-app/src/views/Lifecycle.vue, packages/vue/test-app/tests/e2e/specs/lifecycle.js, packages/vue/tsconfig.json
Docs: https://github.com/ionic-team/ionic-docs/pull/1851
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22769
- Added Composition API-style lifecycle hooks for Ionic Vue
=> feat(vue): add composition API ionic lifecycle hooks

core/src/components/input/input.scss, core/src/components/input/input.tsx, core/src/components/input/test/basic/index.html, core/src/components/input/test/spec/index.html, core/src/components/label/label.ios.scss, core/src/components/label/label.md.scss
- A placeholder with a floating label would appear when unfocused
- If no placeholder exists, then you add one, the label doesn't float
Issue Number: fixes #17571
- Hides the placeholder until it is focused (floating labels only)
- If you add a placeholder after the component is loaded it now updates the item class to float the label properly
This is a design improvement that gets us closer to the MD spec here: 
It is currently applied to iOS too, may need a design decision on this.
=> fix(label): do not show placeholder with floating label until focus

packages/react-router/src/ReactRouter/IonRouter.tsx, packages/vue-router/src/router.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22997
It's currently impossible to do custom click handlers right now because the `href` always takes priority. Leaving the `href` off will cause the click handler to fire, but it causes errors. The underlying WC for tab button allows an undefined href without crashing, so we need to here as well.
- Check if `path` is defined before attempting to switch tabs.
- The `path` prop is optional on the regular web component ion-tab-button, so we should expect it to be undefined here as well. Also allows devs to override the default tab button behavior and add their own click handler.
- I did not apply this …
=> fix(react, vue): tab buttons no longer throw an error if href is undefined

packages/vue/src/components/IonTabBar.ts, packages/vue/test-app/src/router/index.ts, packages/vue/test-app/src/views/Tab4.vue, packages/vue/test-app/tests/e2e/specs/tabs.js
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22597
- Active tab is cleared if no new active tab is found
=> fix(vue): correctly remove active state from tab button when navigating away from tab

core/src/components.d.ts, core/src/components/menu/menu.tsx, core/src/components/menu/readme.md, core/src/components/split-pane/readme.md, core/src/components/split-pane/split-pane.tsx
Issue Number: https://github.com/ionic-team/ionic-framework/issues/22989
We need to make it clear that contentId does not refer to the `ion-content` inside of `ion-menu`. Setting `contentId` to be that `ion-content` causes issues with interacting with the component.
-
-
-
=> docs(menu, split-pane): update contentId docs to be more clear

packages/react/src/components/navigation/IonTabs.tsx
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23023
- Check if tab event props are defined on IonTabs before passing down to IonTabBar
=> fix(react): only pass tab event props from IonTabs to IonTabBar if defined

core/src/utils/helpers.ts, core/src/utils/test/ready.spec.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23029
- Element ref is passed in callback
- We now wait in an raf before calling callback with CE build
=> fix(): overlays now present correctly when using custom elements build

angular/src/directives/virtual-scroll/virtual-scroll.ts
Using the async pipe is considered best practice for angular projects.
When using the `async` pipe with `<ion-virtual-scroll>` with `strictTemplates` set to `true` in `tsconfig.json` we get this error `Type 'null' is not assignable to type 'any[] | undefined'.` during the build phase.
When setting `angularCompilerOptions.strictTemplates=true` in `tsconfig.json` the build fails because there is a type mismatch between async & [items]. This is because the return type of async can be `any[] | null` whereas [items] only accepts `any[] | undefined`. Adding null to the allowed types fixes the issue and allows async to be used with virtual scroll.
=> fix(virtual-scroll): allow null in items prop

core/src/components/refresher/refresher.tsx
Since `ev.data.animation = animation` is set asynchronously, it was possible for `onEnd` to fire before that async task completed resulting in `ev.data.animation` being undefined.
In addition, we need to make sure that `this.state = RefresherState.Pulling;` is set at the beginning of the gesture otherwise dimensions will be incorrect when creating this animation synchronously.
Note: `onMove` is fired in an raf from the gesture utility, so firing something "Synchronously" refers to within the context of the callback function.
This PR ensures that `ev.data.animation` is set synchronously so the undefined error never happens.
=> fix(refresher): resolve progressEnd errors in native MD refresher

angular/src/directives/navigation/ion-router-outlet.ts, angular/src/directives/navigation/stack-controller.ts
closes #15154
Issue Number: #15154 
- the swipe back gesture on the angular ion-router-outlet checks if another navigation task of the stack controller is currently running and if so prevents the swipe back animation to start
reopened from https://github.com/ionic-team/ionic-framework/pull/23117
=> fix(angular): swiping back quickly no longer causes app to get stuck

packages/react/src/components/createOverlayComponent.tsx
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23140
Because `isDismissing` is not a prop, updating it after the overlay is dismissed the render function was not called again.
- Component now re-renders to destroy child component instance after transition is done.
=> fix(react): overlays now correctly unmount any child components after dismissing

core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/a11y/datetime.spec.ts, core/src/components/datetime/test/standalone/index.html, core/src/components/input/input.tsx, core/src/components/input/test/a11y/input.spec.ts, core/src/components/input/test/attributes/index.html, core/src/components/textarea/test/a11y/textarea.spec.ts, core/src/components/textarea/textarea.tsx
Issue Number: resolves #23182 
- Datetime, input, and textarea no longer generate a default aria-labelledby attribute when there is no adjacent ion-label
=> fix(datetime, input, textarea): remove aria-labelledby when there is no adjacent ion-label

packages/react/src/components/IonIcon.tsx, packages/react/src/components/IonPage.tsx, packages/react/src/components/IonRouterOutlet.tsx, packages/react/src/components/__tests__/createComponent.spec.tsx, packages/react/src/components/createComponent.tsx, packages/react/src/components/createControllerComponent.tsx, packages/react/src/components/createOverlayComponent.tsx, packages/react/src/components/inner-proxies.ts, packages/react/src/components/navigation/IonBackButton.tsx, packages/react/src/components/navigation/IonTabBar.tsx, packages/react/src/components/navigation/IonTabButton.tsx, packages/react/src/components/utils/index.tsx, packages/react/src/routing/OutletPageManager.tsx, packages/react/src/routing/PageManager.tsx
React refs can be an object, or a callback - callbacks are
commonly used by 3rd party libraries for combining multiple refs.
https://reactjs.org/docs/refs-and-the-dom.html#callback-refs
Issue Number: #23153
Providing a callback ref breaks internal assumptions that forwardedRefs will always be in the object format.
- Internal ref usage has been decoupled from forwardedRefs.
- Refs may be provided in object or callback format.
=> fix(react): support React refs (object and callback)

core/src/components/action-sheet/readme.md, core/src/components/action-sheet/usage/vue.md, core/src/components/alert/readme.md, core/src/components/alert/usage/vue.md, core/src/components/loading/readme.md, core/src/components/loading/usage/vue.md, core/src/components/modal/readme.md, core/src/components/modal/usage/vue.md, core/src/components/popover/readme.md, core/src/components/popover/usage/vue.md, core/src/components/toast/readme.md, core/src/components/toast/usage/vue.md, packages/vue/src/vue-component-lib/overlays.ts, packages/vue/test-app/src/views/Overlays.vue
Currently Vue users need to listen to overlay events using an `on` prefix which is not very Vue-like. This syntax was carried over from Ionic React, but the `on` prefix is more suitable in a React environment.
- Users can now do `@didPresent` instead of `@onDidPresent`
- Deprecated `@onDid` and `@onWill` events
Only impacts overlay components
=> fix(vue): overlay events can now be listened for without the "on" prefix

BREAKING.md, packages/vue/src/ionic-vue.ts, packages/vue/src/utils.ts, packages/vue/src/vue-component-lib/overlays.ts, packages/vue/test-app/package-lock.json, packages/vue/test-app/package.json
- We deprecated "on" prefixed overlay events in Framework v5 but they were still usable
- Older versions of Vue 3 had a bug with how web component events were transformed that we had to support.
- "on" prefixed events have been removed in favor of non prefixed events
- Support for the old version of Vue 3 has been dropped.
=> refactor(vue): drop support for "on" prefixed overlay events and bump minimum required version of vue to 3.0.6

core/src/components/modal/test/basic/index.html, core/src/css/core.scss
Issue Number: resolves #22778 
- Toolbars in modals on iOS now have additional padding
=> fix(modal): add additional padding to toolbars in iOS modal

packages/vue-router/src/router.ts
if this runs in SSR mode, we are getting history is undefined! so I just initialized the history variable from opts.
Issue Number: #23254 
- No error
- SSR works great
I have just added a line to initialize history variable before using it, so on the server it doesn't break
=> fix(vue): use correct history mode when doing ssr to avoid errors

core/src/components/modal/readme.md
As discussed with @liamdebeasi  ;-) Hope it  makes sense!
-
-
-
=> docs(modal): document stacked modal behavior

core/src/components/refresher/refresher.tsx, core/src/components/refresher/refresher.utils.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23245
- Moved state update back inside `onMove` so that the refresher is only shown when we have verified user is trying to pull to refresh.
- In https://github.com/ionic-team/ionic-framework/pull/23056 I had noted that the previous state update in onStart was necessary otherwise the spinner dimensions were not computed properly. I was able to work around this by taking the dimensions of `ion-refresher` which is always visible. `ion-refresher` is roughly the height of how much we need to offset the spinner by when pulling down.
=> fix(refresher): refresher now only activates when pulling down on MD

packages/react-router/src/ReactRouter/IonReactHashRouter.tsx, packages/react-router/src/ReactRouter/IonReactMemoryRouter.tsx, packages/react-router/src/ReactRouter/IonReactRouter.tsx, packages/react-router/src/ReactRouter/IonRouter.tsx
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23294
- Ionic React now supports history@5x
- Most developers will not notice a difference, and it is not currently recommended to use `history@5` as react router expected `history@4.x` but react router 6 will support `history@5` so we will need to add support anyways.
- I opted to support both so we do not need to make any breaking changes right away (I.e. dropping support for react router 5)
=> fix(react): support history@5 in preparation for react router 6

core/src/components/router/router.tsx, core/src/components/router/test/basic/index.html, core/src/components/router/test/basic/redirect.e2e.ts, core/src/components/router/test/parser.spec.tsx, core/src/components/router/utils/debug.ts, core/src/components/router/utils/interface.ts, core/src/components/router/utils/matching.ts, core/src/components/router/utils/parser.ts, core/src/components/router/utils/path.ts
Issue Number: fixes #23136
when redirect to `/some/path?qs` the query string was not set before this PR.
This PR also adds some comments and renaming in order to make the code easier to understand.
=> fix(router): redirects use the to query string

.github/PROCESS.md
Fixed typo.
```
corrsponding -> corresponding
```
-
-
-
=> docs(process): fix typo

.github/COMPONENT-GUIDE.md, core/src/components/title/title.ios.scss, core/src/components/title/title.tsx
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23371
- RTL mixins do not work on shadow components in Webkit due to its lack of :host-context support, so I needed to set an RTL class on the title component and style based on that.
=> fix(title): large title scale animation is now correct in rtl mode

core/src/components/popover/readme.md, core/src/components/popover/usage/vue.md
There is an `event` variable and a `event` parameter inside the `open` function for Vue which is causing issues. See https://forum.ionicframework.com/t/popover-positioned-in-the-center-of-screen-not-near-the-button-activated/210246/6
- Changed "event" to "ev" in the function
-
=> docs(popover): resolve variable naming conflict

BREAKING.md, core/src/components.d.ts, core/src/components/datetime/datetime-interface.ts, core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/basic/index.html, core/src/components/datetime/test/demo/index.html, core/src/components/datetime/utils/data.ts, core/src/components/datetime/utils/manipulation.ts
=> fix(datetime): events are now emitted, value property now respected

core/src/components/modal/gestures/swipe-to-close.ts
closes #23398
An iOS Card Style Modal is currently able to swipe down on the Footer.
Issue Number: #23398 
- According to @liamdebeasi 's comments in my issue i edited the code to make the gesture not be start-able on the footer as well
=> fix(modal): swipe to close modal is no longer swipeable on footer

core/src/components/modal/test/custom/index.html, core/src/components/title/title.ios.scss
Adjusting the padding top or bottom on the toolbar was not inheriting this padding in the title for iOS only
Issue Number: fixes #23072
It now inherits the top and bottom padding, this is not needed for MD since it doesn't use absolute positioning
View test at http://localhost:3333/src/components/modal/test/custom
| ---| ---|
|![master](https://user-images.githubusercontent.com/6577830/119166375-881f1d80-ba2c-11eb-9582-3b4cfbbc681e.png) | ![branch](https://user-images.githubusercontent.com/6577830/119166421-966d3980-ba2c-11eb-9574-8ff4ae992ea1.png) |
=> fix(title): inherit padding for iOS title in a toolbar

core/package-lock.json, core/package.json, packages/vue/src/vue-component-lib/utils.ts
Vue 3.1.0 introduced a minor breaking change to improve consistency between Vue 2 and Vue 3. Previously, properties there were unused did not show up as keys in the `props` object. Starting in Vue 3.1.0, all properties will show up regardless of whether or not they are used. In the Vue Output Targets, we check for the presence of `modelValue`, the v-model property by checking if the key exists in the `props` object. This no longer works as it was always there in Vue 3.1.0
More context: https://github.com/vuejs/vue-next/issues/3889
- In addition to checking for the presence of the v-model key, we also check to see if it is undefined or not.
=> fix(vue): improve v-model integration for Vue 3.1.0+

core/src/utils/config.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23397
- Removed the `console.error`. We had a similar issue with Angular: https://github.com/ionic-team/ionic-framework/commit/9cb6c80b3db4273e9c003a62a3065427995cb353
=> fix(vue): prevent error from being thrown when testing on certain jest runners

core/src/components.d.ts, core/src/components/modal/modal.tsx, core/src/components/popover/popover.tsx, core/src/utils/overlays.ts
… being used inline or not
Previously you needed to explicitly tell modal/popover that they were not being used inline which caused some breaking changes.
- We can now automatically detect if the overlay is in the correct location (I.e. a direct descendant of ion-app or body) before presenting, and return the correct delegate based on that.
If overlay is in correct location, we just call `present`. Otherwise, we pass in either the value of `this.delegate` or the default core delegate.
=> fix(modal, popover): overlays now automatically determine if they are inline

core/src/components/modal/modal.ios.scss, core/src/components/modal/modal.ios.vars.scss, core/src/css/core.scss
With the conversion to shadow dom, `inherit` no longer worked as a workaround for the border radius bug in WebKit w/ card style modals
- Explicitly set 10px for border radius instead
=> fix(modal): border radius is correctly set on card style modal

packages/vue/src/components/IonTabs.ts, packages/vue/test-app/src/router/index.ts, packages/vue/test-app/src/views/TabsNew.vue
v6 Docs: https://github.com/ionic-team/ionic-docs/pull/1972
v5 Docs: https://github.com/ionic-team/ionic-docs/pull/1973
Vue Tabs Starter: https://github.com/ionic-team/starters/pull/1685
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23321
- IonTabs can now accept an IonRouterOutlet so developers can access the IonRouterOutlet props within a tabs context.
- Existing developers can continue to use the default IonRouterOutlet provided in IonTabs, though this behavior will not be supported in Framework v6.
=> fix(vue): IonTabs can now accept IonRouterOutlet

packages/react/src/components/proxies.ts
Ionic React component wrappers are not auto generated and I forgot to export accordion and accordion group for react
- Accordion and accordion group are now exported
=> fix(react): export accordion and accordion group components

core/src/components/popover/animations/ios.enter.ts, core/src/components/popover/animations/md.enter.ts, core/src/components/popover/test/size/e2e.ts, core/src/components/popover/test/size/index.html
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23528
- the animations (incorrectly) assume that only the `trigger` prop would be used to determine popover dimensions when `size="cover"`. However, the trigger could also be found via `event.target` if `event` is provided.
- I updated the animation code to pass in either the trigger element or the event target if no trigger was found and an event was provided.
=> fix(popover): size property now works when providing only event

core/src/utils/animation/animation-interface.ts
TypeScript interface says `progressStart`, `progressStep`, and `progressEnd` methods return `void`, but they actually return `Animation`: https://github.com/ionic-team/ionic-framework/blob/master/core/src/utils/animation/animation.ts#L661-L740
https://github.com/ionic-team/ionic-docs/issues/1930
- TypeScript interface has correct return value now
=> fix(animation): typescript interface has correct return value for progress methods

core/src/components/popover/animations/md.enter.ts
Popover animation had too big of a scale compared to https://material-components.github.io/material-components-web-catalog/#/component/select, also the scale and opacity finish at the same time.
- Reduced the scale on the popover, and made the opacity animation faster than the scale animation
https://user-images.githubusercontent.com/2721089/124004937-81c67e80-d9a6-11eb-8875-c15ad7a28936.mov
https://user-images.githubusercontent.com/2721089/124004947-8428d880-d9a6-11eb-81c8-1ae690041126.mov
=> fix(popover): update animation to better match MD spec

core/src/utils/transition/index.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/18455
- Remove pointer events from entering and leaving views when transition starts and clear them when transition ends
- This does not impact swipe to go back because that gesture happens on `ion-router-outlet`, and pointer events are being removed deeper in the DOM tree, so router outlet still receives pointer events.
=> fix(ios, md): double tapping back button no longer causes app to go back 2 pages

core/src/components/datetime/datetime.tsx, core/src/components/datetime/readme.md, core/src/components/datetime/test/manipulation.spec.ts, core/src/components/datetime/utils/manipulation.ts
Issue Number: 
- resolves #21553 
- resolves #18122
- Users can now navigate years in `ion-datetime` by pressing (`Shift` + `PageUp`) or (`Shift` + `PageDown`).
- Added accessibility section to `ion-datetime` docs.
Keyboard behavior based on https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html
=> fix(datetime): add keyboard year navigation

core/src/components/loading/readme.md, core/src/components/loading/usage/react.md
The docs don't say how to use dismiss(), this shows that the `useIonLoading` hook returns the present and dismiss functions.
The docs mention quickly using dismiss() to close the IonLoading, but it doesn't say how to access this function.
- Just adds the dismiss as a second return in the react example.
=> docs(loading): show how to use dismiss method returns from useIonLoading for react

core/src/components/button/button.scss
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23588
- During the v4 beta, `pointer-events: auto` was set on `ion-button` to resolve https://github.com/ionic-team/ionic-framework/issues/15623. However, the underlying issue was related to a different issue which was fixed in https://github.com/ionic-team/ionic-framework/commit/e189cc6ec2d5b176914e239927ee40d7fe89a318. The original `pointer-events` fix was never removed. As a result, when we set `pointer-events: none` on `.ion-page` during the page transition, all `ion-button` elements still receive pointer events because they have `pointer-events: auto` set. By removing `pointer-events: auto` on …
=> fix(button): buttons are now disabled during page transitions

.nova/Configuration.json, core/src/components/router-outlet/route-outlet.tsx, packages/react-router/test-app/cypress/integration/swipe-to-go-back.js
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22895
- Implemented a similar fix in `ion-nav` where we only allow the swipe gesture to start if there is not an existing transition.
=> fix(router-outlet): improve reliability of swipe back gesture when quickly swiping back

core/src/components/menu-button/menu-button.tsx, core/src/components/menu-button/test/a11y/e2e.ts, core/src/components/menu-button/test/a11y/index.html, core/src/components/menu-button/test/basic/index.html
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23604
- aria-label is now inherited to inner button inside of shadow dom
- defaults "menu" if not specified
=> fix(menu-button): custom aria-label can now be set

core/src/components/breadcrumb/breadcrumb-interface.ts, core/src/components/breadcrumbs/breadcrumbs.tsx, core/src/components/breadcrumbs/readme.md, core/src/components/breadcrumbs/test/basic/index.html, core/src/components/breadcrumbs/test/breadcrumbs.spec.ts, core/src/components/breadcrumbs/usage/angular.md, core/src/components/breadcrumbs/usage/javascript.md, core/src/components/breadcrumbs/usage/react.md, core/src/components/breadcrumbs/usage/stencil.md, core/src/components/breadcrumbs/usage/vue.md
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23552
- The `ionCollapsedClick` event payload now contains the `collapsedBreadcrumbs` key whose value is an array of collapsed `ion-breadcrumb` elements.
=> feat(breadcrumbs): ionCollapsedClick event payload now contains references to collapsed breadcrumb elements

packages/vue/src/components/IonRouterOutlet.ts
A common issue people run into is not adding `<ion-page>` to their views. This results in ambiguous errors such as https://github.com/ionic-team/ionic-framework/issues/23620 and https://github.com/ionic-team/ionic-framework/issues/22967.
This PR will detect and warn developers if they forgot the `<ion-page>` component in the hopes that it will help developers catch these errors before they happen.
=> chore(): warn if developer forgot to use ionpage component in view

core/src/components/modal/readme.md, core/src/components/modal/usage/react.md, core/src/components/modal/usage/vue.md
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23622
- Added card style modal example for ionic vue
- Did not add example for modal within modal because of https://github.com/ionic-team/ionic-framework/issues/23219, though this should be fixed for Framwork v6 in modals
=> docs(vue): add card style modal example

core/src/components/datetime/datetime.tsx, core/src/components/datetime/readme.md, core/src/components/datetime/test/minmax/e2e.ts, core/src/components/datetime/test/minmax/index.html, core/src/components/datetime/utils/data.ts, core/src/components/datetime/utils/state.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23615
- Max/Min are now accounted for when generating years in MD mode
- Out of bounds years are no longer shown in MD mode, making behavior more consistent with iOS mode
- Datetime renders max year as current year and min year as current year - 100 by default for better consistency with old datetime behavior.
- I also changed the internals so that the years array is passed into the ios and MD functions so something like this doesn't happen again
=> fix(datetime): years displayed now more consistent with v5 datetime, max and min are now accounted for in MD mode

core/src/utils/transition/index.ts
In v6 we use a `deepReady` function to wait for all stencil components to have been initialized. In the lazy loaded version, we wait for the `componentOnReady` function to fire. In the non-lazy loaded version we return immediately. Since `customElements.define` is not synchronous, we were resolving one frame too early.
This resulted in `ion-popover` not computing the height of the content correctly because the inner `ion-content` had not been initialized yet.
https://forum.ionicframework.com/t/ionic-6-popover-tab-problem/212754
- Wait 1 frame for the custom element to be registered
=> fix(vue): popover positioning is now correct with custom elements build

core/src/utils/gesture/pointer-events.ts
Issue Number: resolves #22819
- onEnd and onCancel callbacks are fired even if the target is removed from the DOM.
=> fix(gesture): onEnd now correctly fires even if the event target was removed from the DOM 

packages/vue/src/components/IonTabs.ts
Issue Number: resolves #23719
- Inverted the logic so that the warning is only applied if the user does not provide a router outlet
=> fix(vue): tabs warning about user-provided router outlet change is now correctly logged

core/src/components/datetime/datetime.ios.scss
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23723
- Today date text color now uses color contrast instead of text color (this is what MD does too)
There was also duplicated CSS so I removed that too
=> fix(datetime): text color on ios mode now accounts for color contrast

core/api.txt, core/src/components/action-sheet/action-sheet-interface.ts, core/src/components/action-sheet/action-sheet.tsx, core/src/components/action-sheet/readme.md, core/src/components/action-sheet/test/basic/e2e.ts, core/src/components/action-sheet/test/basic/index.html, core/src/components/action-sheet/usage/angular.md, core/src/components/action-sheet/usage/javascript.md, core/src/components/action-sheet/usage/react.md, core/src/components/action-sheet/usage/stencil.md, core/src/components/action-sheet/usage/vue.md
closes #23700
Issue Number: #23700 
- `data` added to ActionSheet Button Interface
- Use `button.data` in `buttonClick` instead of `undefined` which is the same if the user doesn't enters a `data`
=> feat(action-sheet): add data property to ActionSheetButton

core/package-lock.json, core/package.json, packages/vue/src/vue-component-lib/utils.ts, packages/vue/test-app/package-lock.json, packages/vue/test-app/package.json
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23539
- Update vue framework binding to differentiate between properties that are being used vs properties not being used by developer
=> fix(vue): custom element internal properties are no longer overridden in vue 3.1.0

core/src/components/img/img.tsx
Fix for this issue: https://github.com/ionic-team/ionic-framework/issues/23703
There is a rare race condition you may experience on devices with slower CPU where the Intersection Observer API supplies multiple items to the callback, instead of only a single element which the previous code assumed it would get.  This changes takes the last item (which will be the most current information).
Issue Number: [23703](https://github.com/ionic-team/ionic-framework/issues/23703)
- Instead of keying off of the first item in the callback to the ion-img Intersection Observer API callback, take the last, most recent one to determine whether the img is on screen and should load
=> fix(img): correctly determine when to load image when scrolling quickly on slower devices

core/src/components/datetime/datetime.ios.scss, core/src/components/datetime/datetime.scss
Issue Number: resolves #23690 
- `<ion-datetime presentation="time">` no longer expands to fill the full height of its container.
<!-- If this introduces a breaking change, please describe the impact and migration path for existing applications below. --
=> fix(datetime): time presentation now has correct height

core/src/components/item-option/item-option.tsx, core/src/components/item-sliding/item-sliding.tsx
resolves #19564
Issue Number: resolves #19564 
- Scrolling is now disabled during the slide gesture.
=> fix(item-sliding): prevent scrolling during slide gesture

core/src/components/nav/nav.tsx, core/src/components/router-outlet/route-outlet.tsx
opts will always have animationBuilder prop when used with ion-router and this fix will make sure, that animationBuilder will be set with appropriate value
Issue Number: #23777
Use custom transition if set on ion-nav and page change triggered by ion-router.
=> fix(nav): custom animation is no longer overridden

core/src/components/reorder-group/reorder-group.tsx
Previously the 'to' detail on item reorder events could be one too high if the item was dragged far enough
Issue Number: resolves #23796
The `to` field on the `ItemReorderEventDetail` event is off-by-one (too high) when an item is dragged past the end the list.
- The `to` field will never be more that the number of items - 1.
I haven't modified any tests because I could only find e2e tests, not unit tests. This fix isn't for something which is visible on the screen and therefore cannot be protected against in a e2e test.
I haven't run the linter because it doesn't appear to run at all on my machine - I assume it to be an environment issue for myself but I am confident that this …
=> fix(reorder-group): dragging reorder item to bottom no longer gives out of bounds index

core/src/components/item/item.scss, core/src/components/item/test/alignment/index.html, core/src/components/label/test/basic/index.html
`ion-label` components slotted in `ion-item` always had `flex: 1`. This was fine for labels at the start, but labels slotted in the end slot ended up taking up ~50% of the item width which did not look correct.
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23806
| `main` | `branch` |
| ------- | --------- |
| ![localhost_3333_src_components_item_test_alignment(Moto G4) (1)](https://user-images.githubusercontent.com/2721089/130632351-4f392d64-a8c1-4544-9d9d-eb11f46319e6.png) | ![localhost_3333_src_components_item_test_alignment(Moto G4)](https://user-images.githubusercontent.com/2721089/130632373-07035d35-1d71-4f1b-9d9e-b6a9ae26ca7a.png) |
- Labels …
=> fix(label): label now only takes up as much space as needed when slotted

core/src/components/slides/test/image/index.html
Fixed typo.
```
transistion -> transition
```
-
-
-
=> chore(slides): fix typo in image slides example

angular/src/index.ts, core/src/components/slides/IonicSwiper.ts, core/src/components/slides/readme.md, core/src/components/slides/slides.tsx, core/src/css/ionic-swiper.scss, core/src/index.ts, packages/react/src/components/index.ts, packages/vue/src/index.ts
backports #23447
- Backports #23447 so that developers can migrate to Swiper in v5.
=> feat(slides): add IonicSlides module for Swiper migration, deprecate ion-slides

core/src/components/virtual-scroll/readme.md, core/src/components/virtual-scroll/virtual-scroll.tsx
=> refactor(virtual-scroll): deprecate virtual scroll in favor of JS framework solutions

core/src/components/menu/menu.tsx
Issue Number: resolves #23810 
- A console error will occur if `contentId` refers to the `ion-content` inside of `ion-menu`.
=> feat(menu): add console error for incorrect usage of contentId

core/src/components/modal/modal.scss, core/src/components/modal/test/sheet/index.html
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23874
- Modal subtracts safe area top from height when using sheet modal
=> fix(modal): sheet modal now accounts for safe area

core/src/components/header/header.tsx, core/src/components/header/test/a11y/e2e.ts, core/src/components/header/test/a11y/index.html
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/21327
- Role attribute can now be customized on `ion-header`
=> fix(header): role can now be customized

core/src/components/tab-bar/tab-bar.scss, core/src/components/tabs/test/placements/index.html
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23893
- Safe area padding on the top is now added to the tab bar
=> fix(tab-bar): safe area padding now added when slot="top"

core/src/components/modal/modal.scss
https://github.com/ionic-team/ionic-framework/commit/12216d378df091e16fd77d271b107e819278481c regressed modal positioning on desktop. Sheet modal needs to be fixed at the bottom, but desktop modal should be centered in middle of screen.
- Desktop modal is now centered in middle of screen
=> fix(modal): modal displays in middle of screen on desktop

core/src/components/modal/modal.scss
Issue Number: part of #23878
- Handle is now positioned higher up on the header
| `next` | `FW-182` |
| ------- | ---------- |
| ![IMG_8695](https://user-images.githubusercontent.com/2721089/132585575-975126e0-45a1-44cb-be4c-7818ffd28214.PNG) | ![IMG_8699](https://user-images.githubusercontent.com/2721089/132585604-bb97cfe5-93bb-4a76-8532-e567a7dc7f4b.PNG) |
=> fix(modal): sheet modal handle is now positioned correctly

angular/src/directives/navigation/ion-tabs.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23897
Each tabs instance listens for `ionTabButtonClick`, so if you click a tab button in a child tabs instance, the parent tabs instance will also see that event and try to navigate. But since the event was really only meant for the child tab, the parent tab will try to navigate to a non-existent route.
- When a tabs instance gets the ionTabButtonClick event it will prevent the event  from bubbling so any tabs higher up do not also receive this event and navigate to the wrong url
=> fix(angular): nested tabs now go to correct page

packages/react/src/components/createOverlayComponent.tsx
Currently, when Ion components such as `IonModal` are created using the `createOverlayComponent` HOC, the isDismissing flag is scoped to the definition of the class. So in this case, when IonModal gets exported, the isDismissing flag is scoped to the IonModal class definition and not an instance of the IonModal. 
Consider when you have multiple IonModals controlling different dialogs or whatever. So I believe this `isDismissing` flag should be scoped to the instance of the Overlay class, as if I chose to render 10 IonModals, each should be controlled independently.
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23904
-
-
-
=> fix(react): modal now mounts child component independently of other modals

core/src/components/modal/animations/sheet.ts, core/src/components/modal/gestures/sheet.ts, core/src/components/modal/modal-interface.ts, core/src/components/modal/modal.tsx, core/src/components/modal/test/sheet/index.html, core/src/components/modal/utils.ts
Animation used the max breakpoint value to compute animation offsets, but animation offsets should always be out of 1, so when `breakpoints` did not include `1` as the max, the animation was broken.
- Compute offsets relative to a breakpoint of `1`
=> fix(modal): sheet animation works correctly if breakpoints value does not include 1

core/src/components/item-sliding/item-sliding.tsx, core/src/components/item-sliding/test/basic/index.html
Issue Number: resolves #19312
- item-sliding queries for a new ion-item at the start of every gesture
=> fix(item-sliding): item-sliding accounts for multiple ion-item elements

core/src/components/label/label.ios.scss, core/src/components/label/label.md.scss, core/src/components/label/label.tsx, core/src/components/label/test/color/e2e.ts, core/src/components/label/test/color/index.html
Issue Number: resolves #20125
Label was inheriting the color if any parent element had `color` property set. It should only inherit color if `ion-item` has `color` property set.
- Label now only inherits color if `ion-item` has `color` property set.
=> fix(label): only inherit color if color property is set on ion-item

angular/src/directives/navigation/ion-tabs.ts
Issue Number: resolves #23952
https://github.com/ionic-team/ionic-framework/commit/1ed9f07060736d0c951910427fb12b250d7dd9af regressed the `select` method where uses could pass in a tab string to select a tab.
- Update `select` method to account for both string name and custom event.
=> fix(angular): select method now has correct types

core/src/components/item-sliding/item-sliding.tsx
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23969
- When closing the item, we disable the gesture and re-enable when the animation is done.
=> fix(item-sliding): closing an item can no longer be interrupted

core/src/components/alert/alert.md.vars.scss
Issue Number: Resolves https://github.com/ionic-team/ionic-framework/issues/23760
In `md` mode, alert-style `ion-select`s with more than 5 items don't look scrollable, due to the alert content having the height for exactly 5 items.
- Alert content height increased to allow for 5.5 items (going off the MD spec item height of 48px). The cut-off item makes it clear that the list can be scrolled to reveal more items.
=> fix(alert): allow 5.5 items to show in alert-mode select popup in md

core/README.md
There was a dead link in the file `core/README.md`. 
- The link has been corrected such that it now leads to the contribution guide.
=> docs(readme): Fix broken link to CONTRIBUTE guide

core/src/components/button/button.tsx, core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/basic/index.html
Issue Number: Resolves https://github.com/ionic-team/ionic-framework/issues/23842
Events for `ionBlur` and `ionFocus` aren't firing when clicking in and out of `ion-datetime`.
- `ion-datetime` fires `ionFocus` and `ionBlur` events when clicking in and out of the component host.
- `ionFocus` and `ionBlur` events fired from components inside `ion-datetime`'s shadow DOM are now prevented from bubbling up, to avoid duplicate events appearing at the top level.
Even with this fix, clicking the `ion-button`s in `ion-datetime` (prev/next month, and buttons in the footer) will cause the datetime to lose focus in Safari (only). This does not apply to tabbing to the buttons instead -- …
=> fix(datetime): add ionBlur/ionFocus events to whole component

core/src/utils/status-tap.ts
Issue Number: resolves #20423
- Tapping status bar now interrupts momentum scrolling and scrolls the page to the top.
=> fix(status-bar): tapping status bar now correctly scrolls content to top

packages/react/package.json, packages/react/src/hooks/__tests__/hooks.spec.tsx, packages/react/src/hooks/useController.ts, packages/react/src/hooks/useIonActionSheet.ts, packages/react/src/hooks/useIonAlert.ts, packages/react/src/hooks/useIonLoading.tsx, packages/react/src/hooks/useIonModal.ts, packages/react/src/hooks/useIonPicker.tsx, packages/react/src/hooks/useIonPopover.ts, packages/react/src/hooks/useIonToast.ts, packages/react/src/hooks/useOverlay.ts
Issue Number: resolves #23741
- Hooks are now memoized.
=> fix(react): overlay hooks memorised properly to prevent re-renders

core/src/components/picker-column-internal/picker-column-internal.tsx, core/src/components/picker-internal/test/basic/index.html
Typing to search for a time in ion-datetime was not updating the value because ionChange was only getting fired when the column was scrolled, not when the value prop was changed.
- ionChange is now fired when the value prop changes
=> fix(picker-internal): ionChange now emitted when value is set

.github/workflows/actions/build-core/action.yml
- `npm ci` force reinstalls all node modules, defeating the purpose of the node modules cache on CI. Given that we have mechanisms for automatically and manually busting this cache, I think it's fine to use `npm install` for the speed bump.
=> test(): allow core to use cached node modules

core/src/components/datetime/datetime.scss
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23910
- Instead of using `display: none` we hide the main content offscreen and set `visibility: hidden` to avoid the additional Intersection Observer callback. I did a brief paint test and there should be no significant changes to painting in terms of performance.
=> fix(datetime): resolve month and year jumping issue on ios

core/stencil.config.ts, packages/react/src/components/IonApp.tsx, packages/react/src/components/navigation/IonTabButton.tsx, packages/react/src/components/navigation/IonTabs.tsx, packages/react/src/components/proxies.ts
https://github.com/ionic-team/ionic-framework/issues/23516#issuecomment-953657370
There appear to be type mismatches when using TypeScript + Preact that do not appear when using TypeScript + React. Most Ionic components do not have this issue (the auto-generated ones), but the "hand crafted" ones have this issue.
Also IonApp was being exported twice. Previously IonApp was autogenerated, but is no longer auto generated as of https://github.com/ionic-team/ionic-framework/commit/f3e492c897c8cda2b98050156f130654f4d7014a.
- I updated these "hand crafted" components to be constructed more like the auto-generated components to avoid this mismatch.
- Removed the redundant IonApp export
=> fix(react): improve component compatibility with preact

core/src/components/action-sheet/action-sheet.tsx, core/src/components/alert/alert.tsx, core/src/components/loading/loading.tsx, core/src/components/modal/test/basic/index.html, core/src/components/picker/picker.tsx, core/src/components/toast/toast.tsx, core/src/utils/overlays.ts, core/src/utils/test/overlays/index.html, core/src/utils/test/overlays/overlays.e2e.ts, core/src/utils/test/overlays/overlays.spec.ts
This is a partial fix for https://github.com/ionic-team/ionic-framework/issues/23728
The hardware back button (HBB) listener for overlays always dismissed the last-presented (I.e. top most) overlay. The problem was that it did this regardless of whether or not that overlay was actually presented. So if you created and presented modal A, then created but did NOT present modal B, pressing the HBB would try to dismiss modal B, leaving modal A open.
This has been the behavior in Ionic for years, but it was never a big issue until the declarative overlays were introduced in Ionic 6. With the declarative overlays, the overlays are always in the DOM and so users started running into …
=> fix(overlays): declarative modals now work properly with the hardware back button

core/src/components/virtual-scroll/readme.md
3 links are broken (404) on the Virtual Scroll readme page. For example:
https://ionicframework.com/docs/**api**/angular/virtual-scroll
should be:
https://ionicframework.com/docs/angular/virtual-scroll
- Fix all links
-
-
- [X ] No
=> docs(virtual-scroll): fix url reference paths

core/src/components/action-sheet/action-sheet.ios.scss, core/src/components/action-sheet/action-sheet.scss
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24175
- Safe area now accounted for in both MD and iOS modes
-
=> fix(action-sheet): safe area is now accounted for in MD mode

BREAKING.md, core/src/components.d.ts, core/src/components/modal/modal.ios.scss, core/src/components/modal/modal.md.scss, core/src/components/modal/modal.tsx, core/src/components/modal/test/sheet/index.html, core/src/components/popover/popover.tsx, core/src/css/core.scss, core/src/utils/overlays.ts, core/src/utils/test/framework-delegate/framework-delegate.e2e.ts, core/src/utils/test/framework-delegate/index.html
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23728
- Modal now opens correctly when placed directly inside of ion-app
- Shadows/backdrop opacities are correctly set for the first open modal
- This changes also fixes a "gotcha" I missed when building declarative modals. If you are creating a modal via `document.createElement`, then the modal is no longer automatically removed from the DOM when the modal is dismissed. Impact on this is low since most developers use `modalController`.
Note: I couldn't think of a better way of doing this fix without the `hasController` internal prop, so if you have other ideas definitely let me know!
=> fix(modal, popover): opening modal and popover now works even if overlay was added to ion-app directly

angular/src/directives/proxies.ts, core/api.txt, core/src/components.d.ts, core/src/components/input/input.tsx, core/src/components/input/readme.md, core/src/components/textarea/readme.md, core/src/components/textarea/textarea.tsx
`ionInput` was emitting a value of type `KeyboardEvent`.
Issue Number: #24083
`ionInput` is now emitting a value of type `InputEvent`.
=> fix(core/input): update onInput to InputEvent

BREAKING.md, angular/src/directives/proxies.ts, core/package-lock.json, core/package.json, core/src/components/accordion/accordion.tsx, packages/react/package.json, packages/react/src/components/IonIcon.tsx, packages/vue/package-lock.json, packages/vue/package.json, packages/vue/src/components/IonIcon.ts
Issue Number: resolves https://github.com/ionic-team/ionicons/issues/1011 Most commonly found when updating to Angular 13 + TypeScript 4.4
- Ionic now uses Ionicons 6
Note: Not a breaking change in Ionic 6, but a breaking change in Ionicons.
=> fix(icon): update to ionicons 6 to resolve typescript 4.4 errors

core/src/components/modal/modal.ios.scss, core/src/components/modal/test/card/e2e.ts, core/src/components/modal/test/card/index.html, core/src/components/modal/test/spec/index.html, core/src/css/core.scss
Two issues here:
1. Border radius cannot be overridden with card or sheet modals. This was due to our usage of hard coding the border radius on the modal wrapper inside of the Shadow DOM.
2. Incorrect global styles was applying border radius to every single modal.
- Border radius can now be overridden using the CSS Variable.
- Global border radius style is removed. It was previously there as an `inherit` to workaround some WebKit issues, but with the conversion to shadow DOM + dropping of support for iOS 12 this isn't needed anymore.
=> fix(modal): border radius is now correctly applied to card modals

angular/src/directives/overlays/modal.ts, angular/src/directives/overlays/popover.ts, angular/src/directives/proxies.ts, core/package-lock.json, core/package.json
Changes in `stencil-ds-output-targets` to support strict mode in Angular, caused multiple observers to bind to the same events. This resulted in duplicate events emitting for each change (only in Angular).
Issue Number: #24057
Event types generated through `angular-output-targets` are written to the global type, instead of defined as a class member. This maintains strict type support and solves `proxyOutputs` conflicting with the class members.
Closing #24186 in preference to this PR.
=> fix(angular): prevent duplicate event emissions

core/src/css/core.scss
Date inputs on Safari 15 are center aligning text contents. This is due to a change in the appearance of `input[type="date"]` in Safari, that isn't aligned with the previous design considerations of `ion-input`. 
Issue Number: #24197
Text alignment of `input[type="date"]` pseudo element aligns left on LTR and right on RTL; only when used inside of `ion-input`.
Repo used to replicate/isolate the bug: https://github.com/sean-perkins/24197-date-input-center
Likely this same issue should be resolved in Ionic 5.*.
=> fix(input): safari 15 webkit text alignment issue with input type date

.scripts/common.js
I disabled the publishing to npm for the dev build scripts so that GitHub actions could do it (Access token is stored in GitHub secrets, so the npm publish command needed to be done by GHA). However, I didn't realize this function is also used for production publishes, so everything will build but nothing will get pushed out to npm.
- Prod build scripts now verify packages + publish npm
- Dev build scripts only verify packages
=> build(): publish to prod but not dev builds

core/src/components/item/item.scss, core/src/components/label/label.md.scss
Click targets inside of an `ion-label` are ignored.
Issue Number: #24215
Pointer events are no longer disabled on the `ion-label` when slotted in an `ion-item`. This allows clicking the label to open a select as well as clicking a slotted button inside of an `ion-label`.
Maintains clickable labels used with select:
<video src="https://user-images.githubusercontent.com/13732623/142052631-dd74efca-a878-48f0-ba75-093084cf2d4d.mp4"></video>
=> fix(item): allow click targets inside of label

BREAKING.md, angular/src/index.ts, packages/react-router/test-app/src/App.tsx, packages/react/src/components/index.ts, packages/react/test-app/src/App.tsx, packages/vue/src/index.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24139
With the Custom Elements build, we now need to call `initialize()`: https://github.com/ionic-team/ionic-framework/blob/next/packages/react/src/components/index.ts#L202. The problem is that this call also sets up the Ionic config. Given that Ionic config is not designed to be reactive, subsequent calls to `setupConfig` had no effect.
- After discussing with the team, we feel the best path forward is a (small) breaking change. Developers will be required to add `setupIonicReact` to their `App.tsx`/`App.jsx` file. This function will call `initialize` and allow developers to pass in a config, so it …
=> feat(react): add setupIonicReact function

packages/vue/src/hooks.ts, packages/vue/test-app/src/router/index.ts, packages/vue/test-app/src/views/Home.vue, packages/vue/test-app/src/views/LifecycleSetup.vue, packages/vue/test-app/tests/e2e/specs/lifecycle.js
Issue Number:  #23824
Define a property on vue instance exposed source object make the hooks be public then they can be access and fire;
-
-
-
=> fix(vue): ionic lifecycle hooks now run when using vue 3.2 setup syntax

core/src/components/content/content.tsx
Issue Number: Resolves https://github.com/ionic-team/ionic-framework/issues/24168
- `ion-content` methods for manual scrolling will wait for component ready if `scrollEl` isn't ready yet. This ensures that if those methods are called in certain lifecycle hooks (such as Vue's `onMounted`), `scrollEl` is defined and the method works properly.
=> fix(content): ensure scrollEl is always available in scroll methods

core/src/components/slides/slides.tsx
When having a swiper instance (`ion-slides`) in a modal, subsequent initializations of the component will fail to initialize swiper; resulting in a developer to manually call `.update()` at an unspecified time.
Github repo of issue: https://github.com/dtarnawsky/cs-ion-slides-bug
Forces the swiper instance to update 20ms after the initialization callback. This causes event bindings and instantiation logic to correctly apply when having `ion-slides` in a modal.
Reverts #20899. 
The original repo for that PR/issue is unavailable, attempted to create a new repo here: https://github.com/sean-perkins/ion-slides-issue. 
I could see it making sense to leave the patch …
=> fix(slides): update swiper instance after initialization

package.json
- The interactive Commitizen CLI will no longer run on the `main`, `next`, and `release-` branches. This change is for better compatibility with our release process. All direct commits to feature branches will still utilize the CLI.
=> build(commitizen): do not run on main, next, or release branches

core/src/components/datetime/test/basic/e2e.ts
Removes unsupported `components` option from e2e test for datetime. `components` is a supported property for `newSpecPage` for registering custom elements.
=> refactor(datetime): e2e does not support components option

core/src/components/picker-column-internal/picker-column-internal.tsx
Issue Number: Resolves https://github.com/ionic-team/ionic-framework/issues/24067
- Previously active items now have their highlight removed during initial setup. (Note that cases beyond initial setup were already handled by the scroll listener.)
=> fix(picker-column-internal): prevent multiple items from being highlighted at once

core/src/components/content/content.scss
Issue Number: Resolves https://github.com/ionic-team/ionic-framework/issues/24286
- Items in the `fixed` slot of `ion-content` will now always render on top of the rest of the content.
- See newly added comments for details.
=> fix(content): ensure fixed slot renders on top of content in iOS

packages/vue/src/components/IonTabBar.ts, packages/vue/test-app/src/views/Tab1.vue, packages/vue/test-app/tests/e2e/specs/tabs.js
Issue Number: resolves #23699
`currentRoute.search` does not include the `?` for the query string, so apps were being redirected to `/tabs/tab1/childkey=value` instead of `/tabs/tab1/child?key=value`
- When switching tabs with a query string, IonTabBar now accounts for the `?` in the query string.
=> fix(vue): switching between tabs preserves query string

core/src/components/accordion-group/accordion-group.tsx, core/src/components/accordion/accordion.scss, core/src/components/accordion/test/accordion.e2e.ts, core/src/components/accordion/test/accordion.spec.ts, core/src/components/accordion/test/nested/e2e.ts, core/src/components/accordion/test/nested/index.html, core/src/css/core.scss
Issue Number see internal ticket and https://twitter.com/schlimmson/status/1466015536253480960
The global accordion styles are too general and result in nested accordion groups getting impacts by the state of a parent accordion group. For example, if a parent accordion group is expanded, the icons in a nested accordion group will all be in the expanded state, even if the accordions themselves are not expanded
There was also an issue with keyboard navigation where you could jump between accordion groups by pressing the arrow keys.
- Styles targeting icons only apply to the direct descendant in the "header" slot.
- Styles targeting accordions only target direct descendants of …
=> fix(accordion): improve functionality with nested accordions

core/src/components/content/content.ios.scss, core/src/components/content/content.scss, core/src/components/content/content.tsx, core/src/components/popover/popover.scss, core/src/components/popover/test/basic/e2e.ts, core/src/components/popover/test/basic/index.html
Issue Number: resolves https://github.com/ionic-team/ionic-v3/issues/102
- Scrolling is now handled by the `content` inside the popover, rather than the outer popover viewport.
- Prevents the `.inner-scroll` in the popover's `content` component from overflowing said content's height, through `display: flex` in a couple places. This ensures the content scrolls properly.
=> fix(popover): handle scrolling in content so header can be sticky

core/src/components/router/test/matching.spec.tsx, core/src/components/router/utils/matching.ts
The function used to determine the correct path to resolve for `ion-router` does not take route parameters into consideration. It only compares the route ids, with the first definition always taking priority over all other routes. This means that if a router has multiple routes sharing the same component, the first definition will always be the route that is determined when running the matching algorithm.
i.e.:
```html
<ion-route url="/" component="my-page" />
<ion-route url="/:s1" component="my-page" />
<ion-route url="/:s1/:s2" component="my-page" />
<ion-route url="/:s1/:s2/:s3" component="my-page" />
```
`/` will always resolve as the path when determining the route to …
=> fix(router): pop to previous route with params

core/package-lock.json, core/package.json, core/src/components/item/test/a11y/e2e.ts, core/src/components/segment/test/a11y/e2e.ts
CI issues with M1 Macs and < v8 of puppeteer.
Issue Number: N/A (Internal Infrastructure)
Updates dependencies for puppeteer and dependents (axe-core) to v10.
There are multiple components in our system that make use of nested-interactive controls. Due to the complexity of these decisions to account for platform restrictions with accessibility, I've disabled that rule set for the two tests that fail as a result.
The rule was introduced in the 4.2 ruleset, before these components were architected. They are valid warnings that we will evaluate against platform changes.
=> chore(deps): update puppeteer to v10

core/src/components/item/item.ios.scss, core/src/components/item/item.md.scss, core/src/components/item/item.scss, core/src/components/item/item.tsx, core/src/components/item/test/css-variables/e2e.ts, core/src/components/item/test/css-variables/index.html
The `.item-bottom` implementation for `ion-item`, incorrectly pushes the item's contents regardless if help/error text is present.
Issue Number: Resolves #23892
The reserved space for the help/error text will not push the container space when the slot is unused.
Changes for help/error text and the item bottom container were introduced with: #23354
=> fix(item): remove empty padding space for item bottom

core/src/components/content/content.tsx
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24359
See https://github.com/ionic-team/ionic-framework/issues/24359#issuecomment-990417805 for context
- Removed the global click listener on `ion-content`
=> perf(content): remove global click listener to improve interaction performance

core/src/utils/overlays.ts
The child custom element `ion-picker-column` is never defined by `ion-picker`. 
Issue Number: #24366
`ion-picker` will define `ion-picker-column` when the controller is constructed. 
Updated our internal API for `createController` and `createOverlay` to support defining custom children elements.
=> fix(overlays): define children custom elements

.github/workflows/release.yml
This adds a new GitHub action workflow that will let us release Ionic via CI. Lets us specify the kind of release, the tag to release it under on npm, and if this is a beta/alpha/rc.
For testing purposes, this script right does not publish to NPM or GitHub. This is only to test the functionality of the GHA workflow to ensure inputs are working and builds are being generated properly.
Assumptions prior to releasing:
1. Changelog has already been generated and committed at this point. Script to generate changelog will come in a separate PR.
=> build(lerna): add release script

angular/src/directives/proxies.ts, core/api.txt, core/src/components.d.ts, core/src/components/select/readme.md, core/src/components/select/select.tsx, core/src/components/select/test/basic/e2e.ts, packages/vue/src/proxies.ts
This reverts commit c1ecf94e4e6e320b61606da3c889926f7372ced7.
-
-
-
=> Revert "feat(select): add event for when overlay is dismissed (#24099)"

packages/vue/src/controllers.ts
All generated controllers for the Vue package have a return type of `any`.
Issue Number: Resolves #24387
All controllers for the Vue package will return the original type of the controller exported from `@ionic/core/components`.
=> fix(vue): strongly typed controller methods

core/src/components/datetime/datetime.tsx
Issue Number: Resolves https://github.com/ionic-team/ionic-framework/issues/24112
When `datetime` is used in a modal etc, there is a race condition between the `datetime` instance loading and the modal animation starting. This sometimes causes the `intersectionObserver`s that handle the `datetime-ready` class to erroneously fire with a visibility of 0 from the beginning, so `datetime-ready` is never added.
The observers that flag whether the `datetime` instance is ready now wait a frame before starting.
=> fix(datetime): fix content sometimes not loading due to race condition

packages/vue/src/components/IonRouterOutlet.ts, packages/vue/test-app/tests/e2e/specs/tabs.js
Attempting to modify the `.ion-page-hidden` class for the transitioning element (typically the leaving element), causes an occasional JavaScript exception to throw when the element is already destroyed.
Issue Number: Resolves #24332
Aligns the Vue implementation for `IonRouterOutlet` against additional safety checks that exist in the React implementation.
=> fix(vue): tabs no longer get unmounted when navigating back to a tabs context

.github/workflows/pre-release.yml, .github/workflows/release.yml
To do a alpha/beta/rc release, we need to pass `--preid` to lerna. For stable releases, there is no `preid` but lerna does not accept undefined as a value for `--preid`. 
Rather than try to do some condition logic with the build file, I decided to split things out into 2 separate files.
- Created a file for doing stable releases of Ionic
- Created a file for doing pre-release versions of Ionic (beta/rc not dev build)
- Configured the git identity for each script. GitHub Actions comes with a built in token under the "github-actions" user, so I am using that.
=> build(lerna): split release and next builds out into separate tasks

core/src/components/item/test/disabled/index.html, core/src/components/radio/radio.tsx, core/src/components/radio/test/basic/e2e.ts, core/src/components/radio/test/basic/index.html
Issue Number: https://github.com/ionic-team/ionic-framework/issues/24291
If an `ion-radio` is not part of an `ion-radio-group`, clicking it does not apply the `radio-checked` class, making it look like nothing happened. However, the native `input` *does* get correctly set to `checked=true`.
This bug looks to be masquerading as the one described in the issue linked above. While having multiple inputs in an `ion-item` and disabling one of them does *not* currently disable the other inputs, using an `ion-radio` as the enabled input can make it look that way.
The `checked` property of the `ion-radio` component is updated on click to match the native input. This is then picked up by …
=> fix(radio): fix radio not showing checked state when not in a group

angular/src/directives/overlays/popover.ts
The `side` property for `ion-popover` is not being passed to the HTML element with the Angular proxies.
Issue Number: Resolves #24466
Adds missing `side` input binding for the `ion-popover` Angular proxies.
=> fix(angular): popover will respect side attribute value

core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/basic/e2e.ts
Selecting a new day value in the calendar will update the local value, but will not update the visual "active day" of the calendar.
Issue Number: Resolves #24414, #24451
When a new day value is selected, the active day will render correctly.
- The `activePartsClone` which is used for the `isActive` calculation, is now updated with the value of the `activeParts` new value.
Introduced in #24414
- https://github.com/sean-perkins/gh-24414-datetime-active-day/tree/main (issue is present)
- https://github.com/sean-perkins/gh-24414-datetime-active-day/tree/fix (issue is resolved)
|Before|After|
|---|---|
|<video src="https://user-images.githubusercontent.com/13732623/147128163-7aa0edb7 …
=> fix(datetime): update active day styling when day is selected

core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/basic/e2e.ts, core/src/utils/rtl/dir.spec.ts, core/src/utils/rtl/dir.ts, core/src/utils/rtl/index.ts
The date picker will infinitely scroll on initialization when using RTL. 
Issue Number: Resolves #24472
The calculations for scroll positioning will account for RTL. 
- Fixes the next/previous icons to flip in RTL
|Before|After|
|---|---|
|<video src="https://user-images.githubusercontent.com/13732623/147143117-574617b4-f66b-4a7e-bddb-e03b645b1d46.mp4"></video>| <video src="https://user-images.githubusercontent.com/13732623/147142970-d7cd570b-5080-4f6a-a02a-5400f8cc5c8f.mp4"></video> |
=> fix(datetime): RTL will no longer infinitely scroll

core/src/components/datetime/test/data.spec.ts, core/src/components/datetime/test/minmax/index.html, core/src/components/datetime/utils/data.ts
The time picker display ignores the value of hour cycle. The time picker will also restrict all hour selections to the minimum minute range; even though the time is above the min range.
i.e.: When the minimum time is 19:30, you are unable to select any value under 20:30 when the hour is 20.
Issue Number: Resolves #24474
- Time picker will return the hours back in 24 hour format when hourCycle is h23
- Time picker allows minute selection above the min range, when the hour is above the min hour (if specified)
|Before|After|
|---|---|
|<video src="https://user-images.githubusercontent.com/13732623/147148436-637d0bfb-6437-4583-be96-26f1513886b2.mp4"></video>| <video …
=> fix(datetime): time picker format with hourCycle h23

core/src/components/popover/popover-interface.ts, core/src/components/popover/readme.md
You are unable to turn off the arrow when using the controller approach for displaying a popover.
Issue Number: Resolves #24487
You can specify to disable the arrow from displaying when displaying a popover with the controller approach:
```ts
.create({
component: ExampleComponent,
arrow: false
});
```
Technically this is supported today, if you type cast on top of the `.create` props type signature. This PR corrects the missing type configuration.
=> fix(popover): allow arrow configuration with controller approach

packages/react/src/components/createInlineOverlayComponent.tsx
Users are unable to scroll to the bottom of modals that have overflow.
Issue Number: #24478
The wrapper for inline overlays will fill its height based on the contents.
=> fix(react): scrolling to bottom of modal contents

core/package-lock.json, core/package.json, packages/react/src/components/createInlineOverlayComponent.tsx, packages/react/src/components/createRoutingComponent.tsx, packages/react/src/components/react-component-lib/createComponent.tsx, packages/react/src/hooks/useOverlay.ts
Issue Number: resolves #24229
- According to https://github.com/vitejs/vite/issues/6104#issuecomment-999050698, using the `createElement` named import from `react` as opposed to `React.createElement` fixes the issue. I have verified that this is true. Rather than wait on a fix from the Vite team, I propose we merge this PR to get developers unblocked sooner. 
Dev build: 6.0.1-dev.1641403994.7fd2e69
=> fix(react): building app for production now works correctly with vite

core/src/components/datetime/datetime.md.scss
The selected day in the MD mode for datetime will clip the box shadow appearance.
Issue Number: Resolves #24408
The calendar month grid has extra padding to no longer clip the selected day in the first row.
|Before|After|
|---|---|
|<img width="412" alt="Screen Shot 2022-01-05 at 11 38 04 PM" src="https://user-images.githubusercontent.com/13732623/148328935-ca5682bf-ec2c-442b-a3c5-18c3e27bdf5a.png">|<img width="410" alt="Screen Shot 2022-01-05 at 11 36 43 PM" src="https://user-images.githubusercontent.com/13732623/148328826-cc732b3e-b357-4d0f-8d5b-dcce9763fe10.png">|
=> fix(datetime): add top padding to MD calendar month grid

core/src/utils/overlays.ts, packages/react/src/components/IonActionSheet.tsx, packages/react/src/components/IonModal.tsx, packages/react/src/components/IonPopover.tsx, packages/react/src/components/createInlineOverlayComponent.tsx, packages/react/src/components/createOverlayComponent.tsx, packages/vue/scripts/copy-overlays.js, packages/vue/src/components/Overlays.ts, packages/vue/src/vue-component-lib/overlays.ts
In the React target, inline overlays (`ion-popover` and `ion-modal`) will not define their nested children custom elements (`ion-backdrop`), when in a production tree-shaken build.
Issue Number: #24449
Inline overlays will share the same custom element definition logic as the regular overlays. This correctly defines `ion-backdrop` for popover/modal inline overlays.
=> fix(react): backdrop for inline modal/popover overlay

packages/vue-router/src/router.ts, packages/vue/test-app/tests/e2e/specs/routing.js
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24226
Previously I had thought that issue was related to ion-router-outlet not waiting for the previous transition to finish. This finding was incorrect. The real issue was that the replace logic inside of `IonRouter` was replacing the wrong route.
Currently, IonRouter gets the last item in the Location History array for the route that should be replaced: https://github.com/ionic-team/ionic-framework/blob/77f8412b746222793cd9d17f12f50d512ab5e886/packages/vue-router/src/router.ts#L241
This line (incorrectly) assumes that the last item in the Location History is the current route. Consider the following …
=> fix(vue): correct route is replaced when using router.replace

core/stencil.config.ts, packages/react/src/components/proxies.ts, packages/react/src/components/routing-proxies.ts
`ion-breadcrumb` does not support the routable behaviors of similar components (i.e. `routerLink`) and `href` causes a full refresh.
Issue Number: Resolves #24493
`ion-breadcrumb` is treated as a routable component for React and now supports `routerLink`.
=> fix(breadcrumb): support routerLink on breadcrumb

core/src/components/picker-internal/picker-internal.scss, core/src/components/picker/test/basic/index.html
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24378
- Added `direction: ltr` to the picker component to force columns to preserve their direction. This is the same technique employed by the public picker: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/picker/picker.scss#L123
- When comparing with the public picker I also found a typo in the test file, so I fixed that.
Note: Screenshot tests automatically run all tests in RTL mode in addition to LTR mode, so the existing tests written for picker-internal should now capture this layout fix.
=> fix(datetime): wheel picker shows correct column order in rtl

packages/react/src/components/IonOverlayManager.tsx
Issue Number: Resolves https://github.com/ionic-team/ionic-framework/issues/24349
(This is a recreation of https://github.com/ionic-team/ionic-framework/pull/24544 to attempt to get around a Github Actions error separate from these code updates.)
If two modals are open at the same time, both using `useIonModal` (doesn't happen with any other frameworks/modal implementations), the contents of the first modal are unmounted. This is most obvious with nested modals, but can also be seen by opening the second modal via the console while the first is still open even if they are at the same level of nesting.
This happens because when the second modal is opened, the `overlays` state in …
=> fix(react): add useRef wrapper to useIonOverlay state to avoid stale references

.github/workflows/dev-build.yml, .scripts/bump-version.js
Lerna expects that the version number changes in between releases, even if you are adding a string to the end of the version to make it unique. This means that if you are currently on 6.0.2, then a dev build need to have 6.0.3 (plus whatever unique string you add).
Previously, the `lerna.json` file had `6.0.0` as the version because we used the old release scripts to release `6.0.1`, so `lerna.json` never got updated. As a result, whenever we tried to do a dev build we released `6.0.1-[dev hash]` that passed because lerna looks to `lerna.json` for the version (which in this case was `6.0.0`).
Starting with 6.0.2, we release using the lerna scripts so the version in `lerna.json` …
=> chore(dev-build): bump patch version for lerna dev builds

core/src/components/datetime/datetime.scss
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24405
This fix is a monkey patch and should be removed when iOS 14 support is dropped in the future. There was a bug in iOS 14 where the month would move back by 1 month when switching from the month/year picker to the calendar grid. A fix was created in https://github.com/ionic-team/ionic-framework/pull/24142. This fix inadvertently introduced the same issue, but only on iOS 15 and with the month moving forward by 1.
I investigated other ways to fix the iOS 14 issue, but nothing was sufficient so I opted for this hacky (and temporary!) approach. The code will apply the iOS 14 fix if it detects a WebKit …
=> fix(datetime): showing calendar grid no longer causes month to switch on ios 15

core/src/components/modal/modal.tsx
The life cycle events related to unmounting/destroying a component were not being fired for modals that were opened with a controller.
Issue Number: #24460
`ngOnDestroy` is correctly called when the modal is destroyed using a controller.
Reverts #24380 
We may want to re-open FW-349 to track that issue. I'd advocate that life cycle methods firing are higher severity than rapid close/open modals destroying the element.
=> fix(modal): destroy life cycle events for controller modals

angular/src/directives/control-value-accessors/value-accessor.ts, angular/test/test-app/e2e/src/form.spec.ts, angular/test/test-app/src/app/form/form.component.html, angular/test/test-app/src/app/form/form.component.ts
Monkey patched methods for form controls are not applied, resulting in Ionic classes not being applied when the methods are programmatically called. 
Issue Number: #24483
Removes the invalid check used for accessing form controls, not public API methods. This will apply the monkey patch for the individual dirty, pristine and touch methods to sync related Ionic classes. 
I believe unintentionally in #23970 the incorrect check was introduced.
=> fix(angular): apply touch, dirty and pristine form control classes

core/src/components/item/item.scss
The error slot of the `ion-item` is never visible in Safari. 
Issue Number: #24575
Adjusts the style ordering so that the error slot display overrides correctly on all browser targets.
You can verify this change by running the Core project:
- http://localhost:3333/src/components/item/test/bottom
- Toggle the "Toggle Error" control
- See that the error slot becomes visible
=> fix(item): error slot visible in Safari

core/src/components/toggle/test/rtl/e2e.ts, core/src/components/toggle/test/rtl/index.html, core/src/components/toggle/toggle.tsx
`ion-toggle` only supports RTL when the direction is set at the document level.
Issue Number: Tech Debt
- `ion-toggle` will respect dir specified on the host element (overrides the document value)
- `ion-toggle` uses the isRTL utility
=> fix(toggle): setting dir on ion-toggle to enable rtl mode now supported

packages/react/src/components/index.ts, packages/vue/src/ionic-vue.ts
When fixing https://github.com/ionic-team/ionic-framework/issues/24481 I discovered that Next.js crashes on the `setupIonicReact` check because `document` is not defined.
- Ensure document is defined before calling it
- I also use the same pattern in Ionic Vue now for consistency, but the functionality is exactly the same
- Note: The `initialize` function has its own `window` undefined check, so we do not need to repeat that in IonicVue: https://github.com/ionic-team/ionic-framework/blob/223f36f6adacf8adce47cee4809a60c94a9e0efa/core/src/global/ionic-global.ts#L17
=> fix(react): setupIonicReact no longer crashes in SSR environment

core/src/components/input/input.tsx, core/src/components/input/test/masking/e2e.ts, core/src/components/input/test/masking/index.html
Updating the value of the `ion-input` during the `ionInput` event callback, will not be reflected in the control. This means you cannot have functionality such as trimming white spaces from an input. 
Issue Number: #19884
The native input is updated when the attribute change callback is fired for the `value` prop. This forces the input element to always be in sync with the value of the `ion-input` web component.
This allows implementations such as preventing whitespace in an `ion-input`.
=> fix(input): ion-input accepts any string value

core/src/components/spinner/spinner.scss, core/src/components/spinner/test/transform/e2e.ts, core/src/components/spinner/test/transform/index.html
Issue Number: Resolves https://github.com/ionic-team/ionic-framework/issues/19247
When a CSS `transform` is applied to an `ion-spinner` of type `circular`, the spinner slides down and to the right during its animation. (This only happens with this particular combination, not necessarily with `position: absolute` as the issue notes, or with any other spinner types.)
The `animation` now applies to the internal `svg`, not the host. This way, an applied `transform` won't overwrite parts of the animation keyframes.
The `circular` spinner was introduced in Ionic 4.8.x and is the default for `md` mode.
=> fix(spinner): ensure transform doesn't overwrite circular animation

core/src/components/menu/menu.tsx, core/src/components/menu/test/focus-trap/e2e.ts, core/src/components/menu/test/focus-trap/index.html, core/src/utils/overlays.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24491 resolves https://github.com/ionic-team/ionic-framework/issues/24361
There are two issues in one here.
1. The overlay focus trapping code was firing whenever the menu was focus, but it should have only been firing on the overlay that was open. This resulted in the focus trapping code continually firing (cause of the infinite loop).
2. Even after this was resolved, the menu focus trapping code was always firing on an overlay. So even if you got the overlay to open, focus would never be moved to it since menu would keep claiming it.
- Overlay focus trapping does not fire if `ion-menu` is focused.
- …
=> fix(menu): focus trapping with menu and overlays no longer results in errors

core/src/components/modal/gestures/sheet.ts, core/src/utils/gesture/index.ts
The swipe gesture for the modal bottom sheet will trigger when a form element (input, textarea, etc.) receives focus and opens the native keyboard. This causes the sheet gesture to become unresponsive and free scroll. 
Issue Number: Resolves #23878
- Swipe gestures will be disabled when the keyboard is immediately open (form element has focus).
- Swipe gestures will be re-enabled on the next frame (after the keyboard has repositioned the view)
- The swipe gesture for the sheet modal will dismiss any active keyboards (this aligns with native behavior, see: Maps sheet implementation on iOS)
|Before|After|
|---|---|
|<video …
=> fix(modal): native keyboard will dismiss when bottom sheet is dragged

core/src/components/modal/gestures/sheet.ts, core/src/components/modal/modal.tsx, core/src/utils/gesture/index.ts
- Moves keyboard interaction behavior into the modal to work for both the sheet modal and card display
- Reverts the minor feature change to the gesture API from #24642
=> refactor(modal): move keyboard behavior for gestures into component

core/src/components/router/router.tsx, core/src/components/router/test/e2e.spec.tsx, core/src/components/router/test/matching.spec.tsx, core/src/components/router/test/parser.spec.tsx, core/src/components/router/test/path.spec.tsx, core/src/components/router/utils/debug.ts, core/src/components/router/utils/dom.ts, core/src/components/router/utils/interface.ts, core/src/components/router/utils/matching.ts, core/src/components/router/utils/parser.ts, core/src/components/router/utils/path.ts
The main thing is to rename path to segments when the router deals with an array of segments.
The word "path: is reserved for the string version to remove confusion.
=> refactor(router): code cleanup.

core/api.txt, core/src/components.d.ts, core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/position/e2e.ts, core/src/components/datetime/test/position/index.html, core/src/components/picker-column-internal/picker-column-internal.tsx, core/src/components/popover/popover.tsx, core/src/components/popover/readme.md
The popover positioning within datetime can result in the popover element being placed outside of the trigger/click target. Additionally, rapidly opening the timepicker within the datetime, can result in the timepicker not scrolling to the correct time.
Issue Number: #24531, #24415
- Presenting the popover within datetime will use the internal API for `ionShadowTarget` to consistently position the popover when the click target/trigger is within a shadow DOM.
- Rapidly toggling the timepicker popover will consistently scroll the picker columns to the correct time.
Extension of #24535 (will close in favor of this, if accepted).
|Before|After|
|---|---|
|<video …
=> fix(datetime): timepicker popover will position relative to click target

packages/vue/src/components/IonRouterOutlet.ts, packages/vue/test-app/src/main.ts, packages/vue/test-app/tests/e2e/specs/tabs.js
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24654
- When going back to the tabs context, the inner tabs outlet no longer attempts to setup a new view item/perform a page transition.
=> fix(vue): going back to a tabs outlet no loger causes classList error

packages/react-router/src/ReactRouter/IonRouteInner.tsx, packages/react-router/src/ReactRouter/StackManager.tsx, packages/react/src/components/navigation/IonTabs.tsx, packages/react/test-app/src/App.tsx, packages/react/test-app/src/pages/Tabs.tsx
On initial load, when using nested router outlets with React, another outlet can briefly display before the enter view & outlet has mounted.
Issue Number: #24666
- Page transitions that are deferred as a result of the outlet not being rendered yet, happen immediately after the outlet is mounted.
- Add note about using a deprecated private API from react-router (`computedMatch`) that is no longer available in v6.
- Removes `tabs` attribute when cloning the page element
- Cannot find a single reference to why we have this code. Looks like carry over from the Angular router integration, which also has no functional code tied to it.
|Before|After|
|---|---|
|<video …
=> fix(react-router): remove page transition flicker on outlet mounting

packages/vue-router/src/locationHistory.ts, packages/vue-router/src/router.ts, packages/vue/test-app/src/App.vue, packages/vue/test-app/tests/e2e/specs/routing.js, packages/vue/test-app/tests/e2e/support/commands.js, packages/vue/test-app/tests/unit/routing.spec.ts
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23873
- After going "back" to a new route that previously never existed, Ionic Vue will clear the future location history as it is no longer relevant.
- When pushing new history after going back, Ionic Vue now clears out future location history items as they are no longer relevant. This also applies when setting the "root" route (I.e. routerDirection="root") as the first item in the location history array is being replaced. As a result, everything after that is no longer relevant.
=> fix(vue): routing history is correctly replaced when overwriting browser history

core/src/components/modal/modal.scss, core/src/components/modal/modal.tsx, core/src/components/popover/popover.scss, core/src/components/popover/popover.tsx, core/src/utils/overlays.ts
Given a button that calls `modalController.create` and `modalController.present`, double clicking it currently results in 2 modals being presented. This is technically the correct behavior, but it is undesirable to some developers.
In Ionic 5, the modals/popovers would receive `pointer-events` the moment the presenting animation began, so this double modal behavior never happened. On the second click, the modal would receive the click causing the 2nd modal to not get presented.
In Ionic 6, modals/popovers did not receive pointer events by default causing the behavior to reproduce more easily. The reason why it changed was due to a workaround to get inline modals to behave …
=> fix(modal, popover): quickly opening modal/popover no longer presents duplicates

core/src/components/datetime/readme.md
Based on discussion in an issue, we determined that our documentation surrounding the requirements for formatting date values for `ion-datetime` is unclear.
Issue Number: #24578
- Renamed `Parsing Dates` to `Timezones` and added sub-sections for input vs. output requirements
- Added usage examples for formatting date string to ISO-8601 for ion-datetime
- Tweaked language for parsing dates section
=> docs(datetime): example formatting date values in ISO-8601

core/README.md, core/src/utils/overlays.ts, packages/react/src/hooks/useController.ts, packages/react/src/hooks/useIonActionSheet.ts, packages/react/src/hooks/useIonAlert.ts, packages/react/src/hooks/useIonLoading.tsx, packages/react/src/hooks/useIonModal.ts, packages/react/src/hooks/useIonPicker.tsx, packages/react/src/hooks/useIonPopover.ts, packages/react/src/hooks/useIonToast.ts, packages/react/src/hooks/useOverlay.ts, packages/vue/src/controllers.ts
Issue Number: resolves #24549, resolves #24590
In order to get custom elements defined when using controllers, we import the source component which would trick Stencil into including the compiled components in the overlays file. From there, we would register those compiled components with the Custom Elements Registry.
Unfortunately, this resulted in two issues:
1. Action Sheet was being initialized after it was referenced by its controller (https://github.com/ionic-team/ionic-framework/issues/24549).
2. Registering the components this way assumed that everyone was using the custom elements build. This resulted in controllers breaking for Angular users …
=> fix(angular, react,  vue): overlays no longer throw errors when used inside tests

packages/angular-server/package.json, packages/angular-server/tsconfig.json
Issue Number: resolves #24605
Similar to the Angular package, the Angular Server package expects only the dist directory to be published at the root, otherwise files will fail to load.
Additionally, with the Angular 12 build (https://github.com/ionic-team/ionic-framework/commit/3451a34ad0c893be0b6c17dc91ac9a75d2b9b52c) we now pass in tsconfig.json to `ng-packagr`. The tsconfig.json tells the compiler to build for Common JS, instead of ES2015 (what the @ionic/angular package currently does). This CJS instruction has been around for a while, but up until that commit we never passed tsconfig to ng-packagr
- Updated the package.json config to only publish `dist` as the root in …
=> fix(angular-server): publish only the dist directory to avoid import errors

core/src/components/datetime/datetime.tsx
The next/previous buttons in the datetime is offset by 2 months. This is because the intersection observer is pre-maturely firing twice, during the re-render of the navigation to the desired month.
Issue Number: #24712
The intersection observer is disconnected before the state update/re-render and re-attached after the render and scroll offset has completed. This allows the swipe gesture behavior to operate correctly and fixes the issue for next/previous button to navigate to the desired month (1 month offset).
=> fix(datetime): disable intersection observer during month update

core/src/components/datetime/test/data.spec.ts, core/src/components/datetime/utils/data.ts
The `max` value for `ion-datetime` will filter the minute selection for all hours. This means if the max value is "19:30", users are only able to select minutes 0-30 within hour 19 (correct), but when within hour 18, they are still only able to select minutes 0-30 (incorrect).
Issue Number: #24702
The max time constraint will only filter minute selections when the max time hour matches the current hour. This means that when max constraint is "19:30" and the hour is 19, users will only be able to select 0-30. When the hour is 18, users will be able to select 0-60.
=> fix(datetime): minutes only filtered when max hour matches current hour

core/src/components/action-sheet/action-sheet.ios.scss, core/src/components/action-sheet/action-sheet.md.scss, core/src/components/action-sheet/action-sheet.md.vars.scss, core/src/components/action-sheet/action-sheet.scss
The safe area is being applied to the action sheet container, which does not have the background appearance applied to it. This pushes the container up, but leaves an empty space between the last group in the action sheet and the bottom bevel of the screen.
Issue Number: #24699
Safe are padding is applied to the last group of the action sheet, which has the background appearance applied to it. This will extend the container's visual appearance to the bottom bevel on an Android device.
=> fix(action-sheet): background includes safe area margin

packages/vue-router/__tests__/locationHistory.spec.ts, packages/vue-router/src/locationHistory.ts, packages/vue-router/src/router.ts, packages/vue/test-app/tests/e2e/specs/routing.js, packages/vue/test-app/tests/e2e/specs/tabs.js, packages/vue/test-app/tests/e2e/support/commands.js
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24432
There are a few related issues:
1. When the incoming route had `routeAction === 'replace'` Ionic Vue would determine the leaving location by getting the second to last item in location history. This was fine when popping would remove items from location history automatically (I.e. what Ionic React does), but when you support `router.go(n)` you cannot do that. As a result, the `locationHistory.previous()` call was not always returning the correct previous route based on where the user was in location history.
2. The `routeInfo.tab === undefined` check was actually a bandaid for an issue I had run …
=> fix(vue): replacing routes now updates location state correctly

core/src/components/input/input.tsx
Setting the cursor position to the middle of an `ion-input` with an existing value and typing a new character, would result in the cursor position to reset to the end of the input.
Issue Number: #24727
When assigning the native input value, persist the cursor position so that the cursor stays in place and no longer jumps to the end of the line.
=> fix(input): cursor position does not jump to end

core/src/components/input/input.tsx
IMEs (input method editors) intercept keyboard events and conflict with the patch in #24606, since both are assigning a value to the native input, resulting in duplicate values on keypress. This also breaks the back button behavior (observed in Japanese IME). 
Issue Number: #24669
To prevent conflicts with IMEs and preserve the patch from the PR that introduced the new issue, it is recommended that we bind event listeners to `compositionstart` and `compositionend` to detect when a composition event from an IME is occurring and skip writing the value to the native input control while the event is in flight (inspired from: https://github.com/ng-select/ng-select/pull/1274)
- Usage …
=> fix(input): IME composition mode

core/src/components/modal/test/inline/e2e.ts, core/src/utils/framework-delegate.ts
Inline modals do not inherit CSS classes that are forwarded when the modal is presented. This results in implementations that make use of an `ion-header`, `ion-content` with overflow scroll, inside an inline modal, are unable to reach the end of the contents.
Issue Number: #24706
Inline modals now inherit CSS classes that are forwarded when the modal is presented (aligning with the controller implementation).
This results in the user being able to correctly scroll to the end of the contents, when using the above scenario.
- Inline modal templates are appended to a new parent element that inherits the CSS classes
- Inline modal template is replaced with the new parent element …
=> fix(modal): inline modals inherit ion-page styling

core/src/components/select/select.tsx, core/src/components/select/test/compare-with/e2e.ts, core/src/components/select/test/compare-with/index.html
This commit fixes an issue that caused selected options to not be selected when using the `multiple` option.
Matching options are not selected by default if an array `value` is passed with `multiple` set to `true`.
Issue Number: #24742
Matching options are selected by default if an array `value` is passed with `multiple` set to `true`.
The first two argument names and their argument types for `isOptionSelected(currentValue: any | any[], compareValue: any, compareWith`) was the main indicator aside from the apparent bug that the parameters were out of order.
=> fix(select): value is selected when given array

core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/minmax/e2e.ts, core/src/components/datetime/test/minmax/index.html
When providing a `min` value to `ion-datetime` that includes a day, the month of the `min` value will be disabled and once you have navigated away from it, you will be unable to return to it. 
This is because the `isBefore`/`isAfter` checks additionally compare the day value, when min/max includes it. This is correct for date comparisons, but isn't a 1:1 with rules surrounding disabling months.
Issue Number: #24757
Users can navigate to min/max months, when the `min`/`max` value includes a day constraint. 
i.e.: If the `min` is `2022-02-09`, users should still be able to navigate to February, since days 10-28 are enabled.
=> fix(datetime): navigate to month within min range

core/api.txt, core/src/components/nav/view-controller.ts, core/src/components/router-outlet/route-outlet.tsx, core/src/components/router-outlet/test/basic/e2e.ts, core/src/components/router-outlet/test/basic/index.html, core/src/utils/helpers.ts
It it possible to activate the same component as long as parameters are different to match the behavior of <ion-nav>
If 2 routes share the same component and the first is active, the router outlet will not allow activating the second even if the parameters are differents
Issue Number: fixes #24653
A route route using the same component as the current one can be activated as long as parameters are differents.
=> fix(router-outlet): add ability to active the same component.

core/src/components/router-outlet/readme.md, core/src/components/router/readme.md
The router outlet can be used without any framework (see the [test app](https://github.com/ionic-team/ionic-framework/tree/main/core/src/components/router-outlet/test/basic)) so the document was misleading and this PR removes the part saying otherwise.
The documentation is still not quite right because the standalone version of the router outlet is quite different from the versions available for the different framework. The standalone version is a simple outlet that only can load a component.
I am wondering how to document components that are different standalone vs framework. Do you have guidelines/examples ? In the meantime I think this PR is still valuable as I think most …
=> docs(router-outlet): clarify usage when not using a framework

core/src/components/datetime/datetime.scss, core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/helpers.spec.ts, core/src/components/datetime/test/locale/e2e.ts, core/src/components/datetime/utils/helpers.ts
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24548
- Ordering of month and year columns now takes into account locale.
=> fix(datetime): month and year column order is now locale aware

core/src/css/structure.scss
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24435
- body is now always promoted to its own layer. It was supposed to be its own layer even before this change, but there is a quirk in WebKit where this does not always happen.
Typically we do not want to "force" layer promotion but given this is an instance where `body` is truly supposed to be its own layer, this seems like an acceptable exclusion to the rule.
=> fix(react, vue): scroll is no longer interrupted on ios

core/src/components/select/select.tsx
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24807
In dev mode, overlay components are not treeshaken, so they are defined in the custom elements registry. In prod mode they are, so these overlays do not show when using ion-select.
- Overlay components are added to `ion-select` such that Stencil will automatically define them when calling `defineCustomElement`
=> fix(select): interface components now show correctly

core/src/components/toast/toast.tsx, core/src/utils/overlays.ts, core/src/utils/test/overlays/index.html, core/src/utils/test/overlays/overlays.e2e.ts, core/src/utils/test/utils.ts
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24733
There are a few issues here:
1. Opening an overlay adds a global `focus` event listener that activates focus trapping. However, we had special logic to prevent toast from adding that global listener. The problem is that this listener is added once globally, so if you open a focus trapping overlay before you open toast, you can defeat this special logic.
2. The focus trapping utility doesn't actually exclude ion-toast like it says it should.
3. The `ion-menu` check in `overlays.ts` was redundant because focus trapping there only ever runs on overlay components.
- Removed the `OverlayListenerOptions` …
=> fix(toast): toast is now correctly excluded from focus trapping

core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/sub-pixel-width/e2e.ts, core/src/components/datetime/test/sub-pixel-width/index.html, core/src/components/datetime/test/zoom/e2e.ts, core/src/components/datetime/test/zoom/index.html
When an `ion-datetime` has a sub-pixel width (either explicitly or through an auto-sizing layout), the intersection observer is unable to detect the intersecting threshold of 100% (`1`).
This results in the month navigation breaking, months updating sporadically on click and overall broken functionality. 
Issue Number: #23992
By applying a root margin to the intersection observer of `1px`, it accounts for the difference of the sub-pixel sizing and appropriately fires the intersection observer when the month is intersecting.
This fixes all the broken behavior with the calendar month not appropriately updating.
=> fix(datetime): improve datetime sizing in modals

core/src/components/datetime/test/format.spec.ts, core/src/components/datetime/utils/data.ts, core/src/components/datetime/utils/format.ts
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24663
- Force all timezones to be interpreted as UTC when formatting.
=> fix(datetime): month picker no longer gives duplicate months on ios 14 and older

core/src/components/menu/test/focus-trap/e2e.ts, core/src/components/modal/modal.tsx
When a modal is opened, the `.show-modal` class is applied. This class prevents the gesture for opening `ion-menu`. The class is never removed when a modal is dismissed, so when the modal is closed, users are unable to open menus through swipe gestures. 
Issue URL: #24817
When the modal is dismissed, the `.show-modal` class is removed from the host element. This allows the menu to be opened through a swipe gesture when the modal is dismissed.
Confirmed in the reproduction app with dev build `6.0.10-dev.1645727760.16b0a89`.
=> fix(modal): re-enable swipe gestures when modal is dismissed

core/src/components/item-sliding/item-sliding.tsx
When calling the `close()` API, it will always re-enable the swipe gesture regardless of the disabled state. This is undesired behavior, as it will make disabled items interactive. 
Issue URL: #24747
When closing items, the API will set the state of the gesture to the opposite of the disabled state. This is consistent with the behavior of the disabled changed behavior. This keeps disabled items disabled from swiping.
Writing a test for this behavior was unsuccessful, open to input/suggestions. Tried to write an extension of the interactive test that disables all items, closes all items and then attempts to swipe to check if there is an active item. Doing this test, I could not …
=> fix(item-sliding): close() will maintain disabled state

core/src/components/item/readme.md, core/src/components/item/usage/react.md
changed
``<IonIcon icon={home} slot="end" />>``
to 
``<IonIcon icon={home} slot="end" />``
on usage react example code
=> docs(item): remove extra > in react example

core/src/components/datetime/readme.md
We have two time zone docs. https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/datetime/readme.md#time-zones and https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/datetime/readme.md#timezones.
The first one has more detail so we should stick with that one.
- Removed the duplicate time zone docs
=> docs(datetime): remove duplicate timezone info

core/src/components/datetime/datetime.tsx, core/src/components/picker-column-internal/picker-column-internal.tsx, core/src/components/picker-column-internal/test/basic/e2e.ts, core/src/components/picker-column-internal/test/basic/index.html
When using a `min` value on `ion-datetime` and changing the hour value, the state of the component is updated and re-renders. This causes the minutes column to become disconnected from the actual selected minutes value. This results in the displayed time value being different than the column picker display.
Issue URL: #24821
When the picker column is re-rendered, if the value is out of bounds or not scrolled correctly in the view, the picker will attempt to set the active item or scroll the active item into view.
=> fix(datetime): persist minutes column on hour change

core/src/components/picker-column-internal/picker-column-internal.tsx
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24878
The problem is that `scrollActiveItemIntoView` is called before `isColumnVisible` is set to `true`: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/picker-column-internal/picker-column-internal.tsx#L100
This did not used to be a problem, but with the introduction of the `isColumnVisible` check in https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/picker-column-internal/picker-column-internal.tsx#L152, this caused the initial scroll to no longer happen.
- Moved `isColumnVisible` to be set to `true` before calling the scroll operation.
I opted not to …
=> fix(datetime): time picker now scrolls to correct value

core/src/components/modal/gestures/sheet.ts
When building the library, you will receive an error:
> [ ERROR ]  TypeScript: ./src/components/modal/gestures/sheet.ts:191:62
>           Object is possibly 'undefined'.
>
>    L190:       */
>    L191:      const processedStep = isAttempingDismissWithCanDismiss ? secondToLastBreakpoint + calculateSpringStep((st
> [17:58.9]  build failed in 11.12 s
- Fixes spelling of a variable
- Adds undefined check
=> chore(modal): typo for variable / undefined check

packages/vue-router/src/locationHistory.ts, packages/vue-router/src/router.ts, packages/vue/src/components/IonTabButton.ts, packages/vue/test-app/tests/e2e/specs/tabs.js
Issue URL: resolves #24934
- Tapping the active tab button now goes back to the initial tabs entry instead of pushing a new entry.
Note: This issue has always been present in Ionic Vue, but users always ran into https://github.com/ionic-team/ionic-framework/issues/23873 first so this issue never appeared.
=> fix(vue): tapping the active tab button now correctly resets the tab stack

core/src/components/toast/readme.md, core/src/components/toast/test/a11y/index.html, core/src/components/toast/test/a11y/toast.e2e.ts, core/src/components/toast/toast.tsx
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/22333
- Screen readers now announce the toast content when it is presented
- Screen readers now announce the toast as a single unit rather than announcing only the changed nodes.
=> fix(toast): screen readers now announce toasts when presented

angular/src/directives/navigation/router-link-delegate.ts
There is a left-over subscription in our router link directive that no longer is initialized/set in the implementation.
Confirmed through git history that we used to subscribe to router events with this subscription, but it was ultimately removed. 
Removed unused code/logic/imports.
=> refactor(angular): unused subscription in routerlink

angular/src/directives/navigation/stack-controller.ts, angular/test/test-app/e2e/src/nested-outlet.spec.ts, angular/test/test-app/src/app/nested-outlet-page/nested-outlet-page.component.ts, angular/test/test-app/src/app/nested-outlet-page2/nested-outlet-page2.component.html, angular/test/test-app/src/app/nested-outlet-page2/nested-outlet-page2.component.ts
When using `ion-router-outlet`, the page components will execute `ngOnDestroy` life cycle hooks outside of the Angular zone. 
Issue URL: #22571
- `ngOnDestroy` will execute inside of Angular zones when pages are unmounted inside `ion-router-outlet`
=> fix(angular): ngOnDestroy runs inside angular zone

core/src/components/datetime/test/presentation/e2e.ts, core/src/components/picker-column-internal/picker-column-internal.tsx, core/src/components/picker-column-internal/test/basic/e2e.ts
When modifying the value of an `ion-datetime[presentation="time"]` with the picker wheel visible in the viewport; the datetime component will emit 4 `ionChange` events, resulting in an incorrect value and in Angular, an incorrect display of the picker wheel.
For example, when setting the value to `06:02:40`, the emitted events will be:
```
{ value: '06:02:40' }
{ value: '2022-03-20T06:57:00-04:00' }
{ value: '2022-03-20T00:02:00-04:00' }
{ value: '00:02' }
```
This corresponds to:
- The first emission is the `ion-datetime` watch callback for the value being modified/ionChange.
- The second emission is the `ion-picker-column-internal` hour column detecting a change/modifying the …
=> fix(datetime): presentation time emits ionChange once 

core/src/components.d.ts, core/src/components/item-sliding/item-sliding.tsx, core/src/components/select/select.tsx
The links in the documentation point to a relative path that doesn't exist. Docusaurus is able to remap it, but with the docs migration the MDX files are imported and docusaurus does not "fix" the URL.
Fixes the relative path for the two offending locations.
=> docs(select,item-sliding): relative link paths

core/src/components/picker-column-internal/test/basic/e2e.ts
The test for validating that `ionChange` is emitting when `ion-picker-column-internal` is scrolled, will occasionally fail. 
- Scroll the element to the bottom of the container to force `ionChange` to emit consistently 
I had issues with getting the test case to fail prior (locally). Ran the updated test 10+ times with passing results. Will see if it passes in CI as well.
=> test(picker-column-internal): emit ionChange on scroll

.github/workflows/actions/update-reference-screenshots/action.yml, .gitignore
Screenshot files are not gitignored. This means that users testing screenshots locally can accidentally push screenshots to git. We only want screenshots generated by CI allowed on git.
- All files in `core/**/*-snapshots` directories (I.e. the directories that playwright puts screenshots in) are now gitignored
- the GH actions task that updates screenshots now uses `--force` when doing `git add` to ensure that CI generated screenshots are added to the repo.
=> chore(playwright): screenshots are now ignored locally

.github/workflows/actions/build-core/action.yml, .github/workflows/build.yml
The latest SHA in a branch was not always being used. This resulted in screenshot comparisons referencing old screenshot results and subsequently failing.
Example: https://github.com/ionic-team/ionic-framework/runs/5792049288?check_suite_focus=true
This checked out the following commit https://github.com/ionic-team/ionic-framework/commit/8754235 which did not have the latest screenshots.
=> chore(ci): ensure that the latest commit is pulled when checking out

core/src/utils/test/playwright/eventSpy.ts, core/src/utils/test/playwright/fixtures.ts, core/src/utils/test/playwright/index.ts
There is no easy way to wait for CustomEvents in order to fail/pass a test.
- Added a new spy functionality to our custom `test` fixture. It is based off the event spy found in Stencil's puppeteer E2E testing.
- I also created a `playwright` directory that exports multiple utilities to make things easier to manage as we add more utils. The import path is the same.
Usage:
```js
const ionPopoverDidPresent = await page.spyOnEvent('ionPopoverDidPresent');
// click a button to present the popover
await ionPopoverDidPresent.next();
```
If `ionPopoverDidPresent` is never emitted, the `ionPopoverDidPresent.next()` check times out, and the test fails.
Note: Currently this is limited to …
=> test(playwright): add event spies

core/src/components/accordion-group/accordion-group.tsx, core/src/components/accordion/test/a11y/e2e.ts, core/src/components/accordion/test/a11y/index.html
Keyboard interaction on accordions applies when focus is in the accordion body. This causes conflicts with form controls and other interactable elements. For example, if you have an `ion-textarea` in the accordion body, hitting the up/down arrow keys to move the textarea cursor will instead move focus between accordions.
The docs say that keyboard controls should only apply when focus is in the header: https://ionicframework.com/docs/api/accordion#keyboard-navigation
Issue URL: https://github.com/ionic-team/ionic-framework/issues/24819
Keyboard controls only apply when focus is in the accordion's header.
=> fix(accordion-group): only allow keyboard interaction if header is focused

core/playwright.config.ts, core/src/components/ripple-effect/test/basic/index.html, core/src/components/ripple-effect/test/basic/ripple-effect.e2e.ts, core/src/utils/tap-click.ts, core/src/utils/test/playwright/fixtures.ts
The ripple effect is broken and does not display when clicking or tapping a button.
Issue URL: #25094
Reverts the optional chaining fixes for eslint and restores the original behavior for ripple effect.
Dev build: `6.0.17-dev.11649730310.17726968`
=> fix(ripple-effect): ripple displays on click or touch

core/src/components/footer/footer.tsx, core/src/components/header/header.tsx, core/src/components/infinite-scroll/infinite-scroll.tsx, core/src/components/refresher/refresher.tsx, core/src/components/reorder-group/reorder-group.tsx, core/src/utils/input-shims/hacks/scroll-assist.ts, core/src/utils/input-shims/hacks/scroll-padding.ts, core/src/utils/input-shims/input-shims.ts, core/src/utils/status-tap.ts
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25122
This appears to be a Stencil bug, but using a Stencil library with aliased paths inside of another Stencil library causes import errors. This does not happen in non-Stencil apps.
- Imports are now correct in Stencil apps
=> fix(all): import path is now correct when using ionic in a stencil app

core/src/components/modal/modal.tsx, core/src/components/popover/popover.tsx
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25124
Modal and popover listen for a generic `ionDismiss` event. This was added years ago, but the event itself has not been used for a long time: https://github.com/ionic-team/ionic-framework/blob/bd5b67304d365594ba3a0ead33dacba9b5a584e4/packages/ionic/src/modal/modal.tsx#L32
`ionDismiss` appears to have been added as a testing API during the early development of Ionic v4: https://github.com/ionic-team/ionic-framework/blob/bd5b67304d365594ba3a0ead33dacba9b5a584e4/packages/ionic/src/core-hn/comments-page.tsx#L12
Perhaps it was indeed meant to be a public API, but it was never documented. We also have …
=> fix(modal, popover): do not dismiss when ionDismiss is emitted

core/src/components/datetime/test/data.spec.ts, core/src/components/datetime/utils/data.ts
- The current fix for https://github.com/ionic-team/ionic-framework/pull/25120 works, but it is overly complex: https://github.com/ionic-team/ionic-framework/commit/96b2003b2bd5089d1faafe262e96c7445c5c3349
- The reason is that we get the time zone offset in minutes, yet we convert to hours and then back to minutes. We should just be using the minutes value directly.
- Simplifies getToday by just passing the current minutes + the time zone offset to `setMinutes`.
=> refactor(datetime): simpler way of accounting for time zone offsets in getToday

core/src/components/modal/modal-interface.ts
`canDismiss` is not available in the modal options.
Issue URL:  #25143
- Adds `canDismiss` type to the `ModalOptions` interface
- Adds deprecated flag to the `swipeToClose` option
Dev-build: `6.1.2-dev.11650303569.14bacac1` ✅
=> fix(modal): add canDismiss option to modal options

core/src/components/picker-column-internal/picker-column-internal.tsx
When rapidly open `ion-picker-internal` in iOS mode within a popover, the picker columns will not center the active item.
Issue URL: #25154
Adjusted the threshold for the intersection observer used for firing & centering the active item. This resolves the issue of rapidly opening the `ion-picker-internal` in a popover. 
This PR is currently what is blocking #25150 for capturing screenshots consistently.
=> fix(picker-column-internal): center active item when rapidly opened

.github/workflows/build.yml, .github/workflows/update-screenshots.yml
Given that we are adding 1000s of tests, 5 test runners is not enough to run our tests in a timely manner. I am bumping the max number of concurrent playwright tests from 5 to 20. We can expand in the future.
=> ci(github): increase test runner limit to 20 for e2e tests

core/src/components/back-button/back-button.tsx, core/src/components/breadcrumb/breadcrumb.tsx, core/src/components/button/button.tsx, core/src/components/header/header.tsx, core/src/components/input/input.tsx, core/src/components/menu-button/menu-button.tsx, core/src/components/menu/menu.tsx, core/src/components/range/range.tsx, core/src/components/textarea/textarea.tsx, core/src/utils/helpers.ts, core/src/utils/test/attributes.spec.ts
ARIA attributes specified on the host element are not reflected to the cloned element in the light DOM. For example, with `ion-button` we create a `button` and clone it into the light DOM so that screen readers can correctly interact with the element. Currently, we are only supporting `aria-label` to be reflected to the HTML `button`.
Issue URL: Enterprise FW-1138, Enterprise FW-1071, #20127
All WAI-ARIA attributes, as listed [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes) are reflected to the following components:
- `ion-button`
- `ion-back-button`
- `ion-breadcrumb`
- `ion-header`
- `ion-input`
- `ion-textarea` 
- `ion-menu`
- …
=> fix(core): inherit aria attributes on host elements

core/src/components/modal/test/sheet/modal.e2e.ts
The test itself was flaky, but I realized that the test is made redundant by `should dismiss the sheet modal when clicking the active backdrop` in the same file. Clicking the backdrop when it is active should dismiss the sheet. When the backdrop is presented, you are never going to be able to click the input with a pointer as the backdrop will receive the click event first.
=> test(modal): remove redundant test

.github/workflows/actions/test-core-screenshot/action.yml, .github/workflows/actions/update-reference-screenshots/action.yml
The update screenshots test had an issue where updating existing screenshots (as opposed to adding new screenshots) was not working as intended.
Given two test runner:
Runner A that updates Screenshot 1
Runner B that updates Screenshot 2
When the results from Runner A were added to the project, we got an updated Screenshot 1 and the old Screenshot 2.
When the results from Runner B were added to the project, we got an updated Screenshot 2 and an old Screenshot 1. The result is that the updated Screenshot 1 was overwritten by the old Screenshot 1 that got added from Runner B.
-------
This new approach ensures that only the changed screenshots per-runner are added to the archive. …
=> chore(ci): fix update screenshot action to account for existing screenshot

core/src/components/select/select.tsx, core/src/components/select/test/basic/select.e2e.ts
Rapidly clicking an `ion-select` can produce multiple `ion-alert` and backdrops. This is because the internal state flag is only set after the overlay is created (before presenting). You can produce this reliably by manually calling `.click()` multiple times on the same element reference.
Issue URL: #25126
Sets the flag prior to the overlay being created, this prevents multiple alert/backdrops from being presented.
Dev-build: `6.1.3-dev.11650650446.100eff34` 🟨
=> fix(select): avoid duplicate dialogs and backdrops when clicking

.github/workflows/actions/test-core-lint/action.yml, core/src/components/footer/footer.tsx, core/src/components/infinite-scroll/infinite-scroll.tsx, core/src/components/modal/modal-interface.ts, core/src/components/refresher/refresher.tsx, core/src/components/reorder-group/reorder-group.tsx, core/src/utils/test/playwright/playwright-page.ts
Lint results must be pushed up to the branch before it can be merged. We do not have any way of automatically checking this. As a result, developers can easily forget to run the linter.
- The core-lint check now fails if there are any changes from running `npm run lint`. (in addition to failing if there are lint failures)
=> ci(lint): ensure linted results are pushed for build to pass

core/playwright.config.ts
Right now flaky tests are a bit unforgiving on CI resulting in a lot of wasted time waiting for builds to run (and then re-run 2-3 times).
- This PR allows 2 retries per test on CI only. This will allow us to avoid additional test runs. 
Note: This is not an alternative to fixing the flaky tests. This change gives us a bit more breathing room while we work to investigate and fix any flaky tests.
=> test(ci): allow 2 retries on CI

.github/workflows/actions/build-angular-server/action.yml, .github/workflows/actions/build-angular/action.yml, .github/workflows/actions/build-core/action.yml, .github/workflows/actions/build-react-router/action.yml, .github/workflows/actions/build-react/action.yml, .github/workflows/actions/build-vue-router/action.yml, .github/workflows/actions/build-vue/action.yml, .github/workflows/actions/test-core-clean-build/action.yml, .github/workflows/actions/test-core-e2e/action.yml, .github/workflows/actions/test-core-lint/action.yml, .github/workflows/actions/test-core-screenshot/action.yml, .github/workflows/actions/test-core-spec/action.yml, .github/workflows/actions/test-react-e2e/action.yml, .github/workflows/actions/test-react-router-e2e/action.yml, .github/workflows/actions/test-vue-e2e/action.yml, .github/workflows/actions/update-reference-screenshots/action.yml, angular/package-lock.json, packages/react/package-lock.json, packages/vue/package-lock.json, packages/vue/src/components/Overlays.ts
- The `canDismiss` property was not auto generated on the ion-modal instance.
- This PR also updated the GitHub Actions workflows to ensure that all framework integration build results have been committed to the repo (to avoid this issue in the future).
Note: I bumped the Node version on CI from 15.x to 16.x. There were some fixes in node 16 that caused `package-lock` files to be generated differently.
- Added the canDismiss property to the modal vue wrapper
=> fix(vue): canDismiss definition is now exposed

core/src/components/modal/test/card-scroll-target/modal.e2e.ts
The purpose of the `card-scroll-target` tests is to verify that swiping on the custom content scroll target works as intended. Swiping on the header is not needed as the regular `card` tests already check for this.
- Removed the redundant swiping on the header test for the custom scroll target
=> test(modal): remove redundant header swipe test

packages/react/src/hooks/useIonModal.ts, packages/react/src/hooks/useOverlay.ts, packages/react/test-app/cypress/integration/overlay-hooks/useIonModal.spec.ts, packages/react/test-app/src/pages/overlay-hooks/ModalHook.tsx
You can pass back `data` or `role` information in the `dismiss` function for both the modal and popover usage of hooks.
Issue URL: #25208
You can pass `data` and `role` information in the `dismiss` function.
Dev-build: `6.1.4-dev.11651091997.1bc6fa6b` ✅
Updated reproduction with the dev-build: https://stackblitz.com/edit/react-1udk9j?file=main.js
=> fix(react): useIonModal/useIonPopover dismiss accepts data and role

core/src/utils/test/playwright/playwright-page.ts
I am seeing intermittent test failures here: https://github.com/ionic-team/ionic-framework/runs/6277771155?check_suite_focus=true
I can reproduce the issue locally. However, the tests still failed even when removing the body of my test. I dug deeper and received this error:
```
1) [firefox] › src/components/modal/test/card-refresher/modal.e2e.ts:6:8 › card modal - with refresher › it should not swipe to close on the content due to the presence of the refresher 
page.exposeFunction: Target closed
at initPageEvents (/Users/liamdebeasi/Ionic/ionic/core/src/utils/test/playwright/page/event-spy.ts:72:14)
at Object.page [as fn] …
```
=> test(playwright): wait for events to be ready before proceeding

packages/react/src/hooks/useIonPopover.ts
The type of the dismiss function returned by `useIonPopover` does not account for the `data` and `role` parameters added here: https://github.com/ionic-team/ionic-framework/pull/25209 Note that this change was already made to `useIonModal`, but was missed for popovers.
Issue URL: N/A
Parameters added to function type.
Dev build: `6.1.7-dev.11652895286.14d01bc9`
=> fix(react): add param types to useIonPopover dismiss function

core/src/utils/tap-click.ts
According to https://developer.mozilla.org/en-US/docs/Web/API/EventTarget, EventTarget can be an element, document, window, AudioContext, etc. So just doing `ev.composedPath()` will lead to TypeScript errors.
For example, checking `el.classList` on an item in the path array does not work. This is because one of those items could be `Window` which does not have `classList`.
However, we know that the composedPath for tap click …
=> chore(): add stronger typing to the tapclick utility

angular/test/test-app/e2e/src/accordion.spec.ts, angular/test/test-app/src/app/accordion/accordion-modal/accordion-modal.component.html, angular/test/test-app/src/app/accordion/accordion-modal/accordion-modal.component.ts, angular/test/test-app/src/app/accordion/accordion.component.html, angular/test/test-app/src/app/accordion/accordion.component.ts, angular/test/test-app/src/app/app-routing.module.ts, angular/test/test-app/src/app/app.module.ts, angular/test/test-app/src/app/home-page/home-page.component.html, core/src/components/accordion/accordion.tsx
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25307
- If we need to expand the accordion but the refs are not setup, the internal state is just set to "Expanded" and the accordion will automatically open (I.e. no animation)
=> fix(accordion): accordions expand when using binding

core/src/components/item/item.tsx, core/src/components/list/list.tsx, core/src/components/list/test/a11y/index.html, core/src/components/list/test/a11y/list.e2e.ts
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/19939
- `ion-list` now has `role="list"` set on the host.
- `ion-item` now has `role="listitem"` set on the host when used inside of an `ion-list`.
=> fix(item, list): list aria roles are added

core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/basic/datetime.e2e.ts
If you have an `ion-datetime` with no default value (causing its value to init to `undefined`), and then call `confirm` on it without first selecting a date, the value will be updated to today. Because we updated the behavior such that no day is visually pre-selected until you pick one, this no longer makes sense.
Screencast: https://user-images.githubusercontent.com/90629384/169901184-eeb228f1-766b-4ce7-a818-f5d087d094ba.mp4
Issue URL: N/A
The value is …
=> fix(datetime): don't update value on confirm call if no date was selected

packages/react/src/components/createControllerComponent.tsx
Starting in React 18, while in development mode, React will unmount and re-mount a component: https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors. 🙃
This causes issues with internal logic within the `createControllerComponent` that will not present an overlay, if the component will be unmounted.
Issue URL: #25247
- Resets the flag for unmounting when the component is re-mounted.
- `IonLoading` will present when `isOpen` is set to …
=> fix(react): present controller overlays in React 18

core/src/components/label/label.ios.scss
In Mobile Safari, when conditionally rendering an `ion-item` next to another `ion-item` with a floating `ion-label` and dynamic text, the text node will not repaint correctly within the same frame.
For example: (Pseudo code)
```html
<ion-button (click)="update()">Update</ion-button>
<ion-item *ngIf="shouldRender">
<ion-label position="floating">Text</ion-label>
<ion-input></ion-input>
</ion-item>
<ion-item>
<ion-label position="floating">{{ dynamicText …
```
=> fix(label): text contents will repaint on change

angular/src/di/r3_injector.ts, angular/src/directives/navigation/ion-router-outlet.ts, angular/src/providers/angular-delegate.ts, angular/src/providers/modal-controller.ts, angular/src/providers/popover-controller.ts, angular/src/util/util.ts
Applications that are upgrading from Angular 13 to Angular 14 will receive an exception that breaks the entire app experience. 
```
TypeError: resolver.resolveComponentFactory is not a function
```
This is due to the deprecation and removal of `ComponentFactoryResolver` in Angular 14.
Issue URL: #25353
- Adds backwards compatibility for Angular 13 applications
- Adds compatibility for Angular 14 applications
Dev-build: `6.1.9-dev.11654275237.1b595be3` …
=> fix(angular): add support for Angular 14

core/src/components.d.ts, core/src/components/modal/modal.tsx, core/src/components/popover/popover.tsx
Issue URL: Part of https://github.com/ionic-team/ionic-framework/issues/25461
Some developers think the `showBackdrop` controls whether or not the backdrop is active/receiving click events.
- Updated the prop description to indicate that `showBackdrop` only controls whether or not the backdrop darkens the screen when present.
=> docs(modal, popover): improve showBackdrop clarity

core/src/components/picker-column-internal/picker-column-internal.tsx, core/src/components/picker-internal/test/basic/picker-internal.e2e.ts
Sean noted in https://github.com/ionic-team/ionic-framework/pull/25389#issuecomment-1154653491 that tabbing between columns broke as a result of our usage of `<button>` for each picker item in picker column internal.
- This PR removes each `<button>` from keyboard tabbing via `tabindex="-1"`. This causes tabbing the focus between columns. Users can still use the arrow keys to select items up/down within a column (this is the behavior that existed prior to …
=> fix(picker-column-internal): tabbing between columns works

core/src/components/picker-column-internal/picker-column-internal.tsx
Sean reported an issue where quickly blurring a picker column with `numericInput="true"` causes the scroll position to get reset back to whatever it was at when the scroll gesture started. This was because we updated `this.isActive` mid-scroll. `isActive` is a state variable which causes a re-render whenever its value changes. This resulted in a re-render happening mid scroll.
- Updated the internal logic to only update `isActive` once scrolling is done. …
=> fix(picker-column-internal): switching off an input mode column preserves scroll

core/src/components/refresher/refresher.tsx
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25418
See https://github.com/ionic-team/ionic-framework/issues/25418#issuecomment-1156532270 for explanation of why this happens
- Reset `this.progress` to `0` in the `onStart` callback. This is the same as what the non-native refreshers do.
- This uncovered another issue where quickly swiping to complete caused an error because we were not disabling the gesture correctly. I changed …
=> fix(refresher): quickly swiping down no longer causes duplicate refresh

core/src/utils/overlays.ts, core/src/utils/test/overlays/overlays.e2e.ts
⚠️  Give co-author credit to [MarkChrisLevy](https://github.com/MarkChrisLevy) prior to merge
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24127 resolves https://github.com/ionic-team/ionic-framework/issues/24820
- Opening an overlay no longer focuses the overlay container if the currently focused element is already inside of the overlay.
=> fix(overlays): focus is not moved if active element is in overlay

core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/minmax/datetime.e2e.ts, core/src/components/datetime/utils/comparison.ts
Originally, assigning a `value` to `ion-datetime` that's sufficiently earlier than the `min` or later than the `max` would lead to a disabled month being displayed, and the user being unable to navigate in either direction. This was mostly resolved here https://github.com/ionic-team/ionic-framework/pull/25351 since both assigning a value and leaving it to the default go through the `processValue` function. The dev experience just needs some polish.
Issue …
=> fix(datetime): add dev warnings when setting out of bounds value

angular/src/directives/navigation/ion-router-outlet.ts
When developers make use of routable standalone components with Ionic, they will receive a generic error that gives no context to the issue or current support status of the feature.
- Warn developers when they attempt to use standalone components with `ion-router-outlet`
Dev-build: `6.1.11-dev.11655864040.13968d31`
You can test with this demo repo and the dev-build: https://github.com/sean-perkins/angular-14-demo
=> fix(angular): warn devs that standalone components are not supported

angular/src/directives/proxies.ts, core/api.txt, packages/vue/src/proxies.ts
The built outputs for https://github.com/ionic-team/ionic-framework/commit/bc0bdc438ba72c695f9d961ddf837ec45e7816dd did not get merged in. Unclear why this did not cause the CI tests to fail.
- Ran build to generate API
=> chore(toggle): run build to generate api

angular/test/test-app/cypress/support/commands.js, angular/test/test-app/cypress/support/index.d.ts, angular/test/test-app/e2e/src/tabs.spec.ts
The Angular e2e test for tabs will occasionally fail (not reproducible on local). 
Issue URL: N/A
Introduces a timeout delay for the click events to offset what I believe to be the issue in Cypress.
If the test continues to break after this change, we can revert this commit. 
Tested on 3 CI runs and it did not fail once.
=> test(angular): add timeouts to tabs navigation extras test

core/src/components/fab-button/fab-button.tsx, core/src/components/fab-button/test/fab-button.spec.ts
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25633
- Aria attributes are now inherited to the native `<button>` element inside of `ion-fab-button`.
=> fix(fab-button): aria attributes are inherited

core/src/components/datetime/test/prefer-wheel/datetime.e2e.ts, core/src/components/datetime/utils/data.ts
As noted in https://github.com/ionic-team/ionic-framework/pull/25432/files#diff-2096901ec14aa009bc4a017f56dd504533b6e1c2fb939717be4fe18f331f7a9fR457, `preferWheel` with `date-time` or `time-date` does not show last/next years dates. The problem is functions like `getMonthColumnData` was built to only work within a single year. With the exception of the date+time wheel picker, all datetime variants work within a single year at a …
=> fix(datetime): account for previous years with preferWheel

packages/react/src/components/navigation/IonNav.tsx, packages/react/test-app/cypress/integration/navigation/IonNav.spec.ts, packages/react/test-app/src/pages/navigation/NavComponent.tsx
Developers cannot assign a `ref` to `IonNav` in React.
Issue URL: #25652
- Developers can assign a `ref` to `IonNav` in React.
- Uses a forwarded ref for the React component
=> fix(react): can assign ref to IonNav

core/src/components/datetime/datetime.tsx, core/src/components/datetime/test/presentation/datetime.e2e.ts
While testing https://github.com/ionic-team/ionic-framework/pull/25655 I noticed that opening the month/year picker, dismissing the overlay, then opening the time picker caused the time picker to not show up. The reason was that the month/year picker, which is not available in time interfaces, was still considered "open". As a result, a blank datetime component was shown.
- Switching between presentation modes now closes the month/year picker.
=> fix(datetime): switching presentation closes month/year picker
