ionic-team/ionic-framework

core/src/components/title/readme.md
core/src/components/title/usage/angular.md
core/src/components/title/usage/javascript.md
core/src/components/title/usage/react.md
core/src/components/title/usage/stencil.md
core/src/components/title/usage/vue.md

Noticed some confusion on the forums over how to style the large title
- Added guidance on styling

docs(title): clarify background-color styling with collapsible large title

---

.scripts/common.js
.scripts/prepare.js
.scripts/release-dev.js
.scripts/release.js
package.json

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21347
- Removed turbocolor, using colorette instead

chore(): update scripts to use colorette instead of turbocolor

---

angular/src/directives/navigation/ion-router-outlet.ts

Issue Number: resolves https://github.com/ionic-team/ionic/issues/16834
- Expose activatedView so users can keep track of active tab

feat(angular): expose activatedView

---

core/package.json
core/src/components/slides/swiper/swiper.bundle.js

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21138
- Update swiper dep

fix(slides): update Swiper dependency to resolve error when doing SSR

---

core/package.json
core/src/components/input/input.tsx
core/src/components/searchbar/searchbar.tsx
core/src/components/textarea/test/standalone/index.html
core/src/components/textarea/textarea.tsx

- Updates to stencil v1.13.0 and gets spellcheck type working with it

chore(stencil): update to latest stencil version v1.13.0

---

core/src/components/alert/alert-interface.ts
core/src/components/alert/alert.tsx
core/src/components/select-option/readme.md
core/src/components/select-option/usage/javascript.md
core/src/components/select-option/usage/react.md
core/src/components/select-option/usage/stencil.md
core/src/components/select-option/usage/vue.md
core/src/components/select-popover/select-popover-interface.ts
core/src/components/select-popover/select-popover.tsx
core/src/components/select/readme.md
core/src/components/select/select.tsx
core/src/components/select/test/custom/index.html

- Adds the `select-interface-option` class to the `ion-select-option` that is passed to the dialog
- Passes the class set on the `ion-select-option` to the option in the dialog
- Adds documentation and usage information for customizing the options
:warning: Commit message :warning:
```
Co-authored-by: Robb Wright <audaxion@gmail.com>
```

feat(select-option): pass class from the option to the interface for individual styling 

---

core/src/components/reorder-group/reorder-group.tsx

Issue Number: #19128
- Passing `false` will complete the reorder with the item reverting to its original position.
Closes #19128

fix(reorder-group): false not reverting item to its original position

---

core/src/utils/input-shims/hacks/scroll-data.ts

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21409
- Only scroll inputs that are out of the safe area

fix(scroll-assist): improve scroll detection accuracy

---

.github/ionic-issue-bot.yml

chore(): exempt bugs and feature requests from stale issues

---

angular/src/directives/control-value-accessors/boolean-value-accessor.ts
angular/src/directives/control-value-accessors/numeric-value-accesssor.ts
angular/src/directives/control-value-accessors/radio-value-accessor.ts
angular/src/directives/control-value-accessors/select-value-accessor.ts
angular/src/directives/control-value-accessors/text-value-accessor.ts
angular/src/directives/control-value-accessors/value-accessor.ts
angular/test/test-app/e2e/src/form.e2e-spec.ts
angular/test/test-app/src/app/form/form.component.html
angular/test/test-app/src/app/form/form.component.ts

Issue Number: fixes https://github.com/ionic-team/ionic/issues/18426, fixes https://github.com/ionic-team/ionic/issues/20650, fixes https://github.com/ionic-team/ionic/issues/17414
- Patch the `markAs*` methods to manually sync the Ionic form classes after calling the native Angular method
This will be merged in place of https://github.com/ionic-team/ionic/pull/21412 with that author being listed as a co-author.

fix(angular): patch FormControl methods to properly sync Ionic form classes

---

CHANGELOG.md
angular/package.json
angular/src/directives/control-value-accessors/value-accessor.ts
core/package.json
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

Release 5.2.1

---

.github/ISSUE_TEMPLATE/bug_report.md

update(template): Add Ionic version 5.0

---

packages/react-router/src/ReactRouter/IonRouter.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react/src/components/createComponent.tsx
packages/react/src/components/hrefprops.ts
packages/react/src/components/navigation/IonBackButton.tsx
packages/react/src/contexts/NavContext.ts
packages/react/src/models/RouteInfo.ts
packages/react/src/routing/NavManager.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/18209
- Adds support for feature in Ionic React

feat(react): add support for configuring animations on a per-page basis

---

core/src/components/input/input.tsx

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21537
- Adds aria-label to clear button

fix(input): add aria-label to clear button

---

core/src/components/segment/segment.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/21546
- Manually call `setCheckedClasses` when needed

fix(segment): ensure checked classes get set after not having a value

---

core/src/components/modal/readme.md
core/src/components/modal/usage/angular.md
core/src/components/modal/usage/javascript.md
core/src/components/modal/usage/react.md
core/src/components/modal/usage/stencil.md

Issue Number: https://github.com/ionic-team/ionic/issues/21551
- Clarify usage

docs(modal): clarify backdrop usage for card modals

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
angular/package.json
core/package.json
core/src/components/input/input.tsx
core/src/components/modal/readme.md
core/src/components/modal/usage/angular.md
core/src/components/modal/usage/javascript.md
core/src/components/modal/usage/react.md
core/src/components/modal/usage/stencil.md
core/src/components/router-outlet/route-outlet.tsx
core/src/components/segment/segment.tsx
core/src/utils/gesture/button-active.ts
core/src/utils/transition/ios.transition.ts
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

Release 5.2.2b

---

core/src/components.d.ts
core/src/components/select-option/readme.md
core/src/components/select-option/select-option.tsx

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21578
-
-
-

docs(select-option): clarify that disabled does not apply for action sheets

---

angular/src/index.ts

Closes #21615
Issue Number: fixes #21615 
- exports createAnimation for @ionic/angular to be used in IonicModule.forRoot()'s Config object

fix(angular): expose createAnimation

---

core/src/components/textarea/textarea.tsx

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21600
- Adds aria-labelled by to native textarea

fix(textarea): add aria-labelledby to native textarea

---

core/src/components/slides/swiper/swiper.bundle.js
core/src/components/slides/swiper/swiper.js
core/src/components/slides/test/basic/index.html

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21554
- Added keyboard plugin. This feature is opt-in, initial testing yielded no issues

fix(slides): enable keyboard integration

---

core/src/components/select/select.tsx

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21601
- The role here should be "listbox" as `ion-select` does not contain an input box.
Combobox (https://www.w3.org/TR/wai-aria-1.1/#combobox):
> A composite widget containing a single-line textbox and another element, such as a listbox or grid, that can dynamically pop up to help the user set the value of the textbox.
Listbox (https://www.w3.org/TR/wai-aria-1.1/#listbox):
> A widget that allows the user to select one or more items from a list of choices.

fix(select): change role to listbox

---

core/.npmrc
core/package-lock.json
core/package.json

- Update to Ionicons 5.1.1
- Added package-lock.json
-

chore(ionicons): bump to ionicons 5.1.1, add package-lock.json

---

core/api.txt
core/src/components/segment-button/readme.md
core/src/components/segment-button/segment-button.tsx
core/src/components/toast/readme.md
core/src/components/toast/toast.tsx

-
-
-
Is this actually a feature? The API to do this has been there for a while, we just forgot to document it.

feat(segment-button, toast): add additional parts docs

---

core/src/components/datetime/datetime.tsx

Issue Number: fixes https://github.com/ionic-team/ionic-framework/issues/21667
- Removed combox role from `ion-datetime` as the component itself is merely a trigger that opens a picker.
Note: `ion-picker-column` _should_ have `role="listbox"`, but due to the way it is constructed it is not accessible when doing that. When we redesign the picker, we should ensure that it is accessible. I ended up leaving out `role="listbox"` because it just made the component harder to interact with via keyboard.

fix(datetime): remove unneeded combox role

---

angular/src/directives/navigation/stack-controller.ts

Issue Number: fixes https://github.com/ionic-team/ionic-framework/issues/21692
- Framework now explicitly looks for per-page animation and passes it to transition method

fix(angular): per-page animations now work with swipe to go back

---

core/src/utils/input-shims/hacks/scroll-assist.ts

Issue Number: fixes https://github.com/ionic-team/ionic-framework/issues/21688
- Framework now waits for the 2nd keyboard event before scrolling

fix(ios): improve scroll assist reliability on password inputs

---

core/src/utils/keyboard/keyboard.ts
core/src/utils/keyboard/test/index.html
core/src/utils/keyboard/test/keyboard.spec.ts

Issue Number: fixes https://github.com/ionic-team/ionic-framework/issues/21734
- removed dependency on layout viewport not changing since it was the wrong assumption this would never change

fix(keyboard): keyboard events now consistently fire on android

---

core/src/components/segment-button/segment-button.md.scss
core/src/components/segment/test/spec/index.html

Issue Number: fixes https://github.com/ionic-team/ionic-framework/issues/21105
- Users can override the min width by setting `min-width` on the host segment button
- In the main segment button file, `.button-native` has `min-width: inherit`, so this should not cause regressions to the default sizing of the button.

fix(segment-button): allow min-width to be overridden

---

packages/react-router/test-app/cypress/integration/tab-context.js
packages/react-router/test-app/src/App.tsx
packages/react-router/test-app/src/pages/Main.tsx
packages/react-router/test-app/src/pages/tab-context/TabContext.tsx
packages/react/src/components/navigation/IonTabBar.tsx

fix(react): fix regression on IonTabsContext not working properly

---

.scripts/release.js

chore(release): update repo name

---

core/src/components/header/header.utils.ts
core/src/components/title/title.ios.scss
docs/package.json

Issue Number: fixes https://github.com/ionic-team/ionic-framework/issues/21761
- Set transform origin on host `ion-title` and have inner div inherit it.
- only affects large title

fix(title): allow overriding of large title transform origin

---

packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/test-app/build.sh
packages/react-router/test-app/cypress/integration/outlet-ref.spec.js
packages/react-router/test-app/src/App.tsx
packages/react-router/test-app/src/pages/Main.tsx
packages/react-router/test-app/src/pages/outlet-ref/OutletRef.tsx
packages/react/src/components/IonRouterOutlet.tsx
packages/react/src/components/inner-proxies.ts
packages/react/src/routing/OutletPageManager.tsx

fix(react): fixing ion-router-outlet ref regression

---

packages/react-router/src/ReactRouter/IonRouter.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/test-app/cypress/integration/dynamic-routes.spec.js
packages/react-router/test-app/cypress/integration/outlet-ref.spec.js
packages/react-router/test-app/cypress/integration/swipe-to-go-back.js
packages/react-router/test-app/cypress/support/commands.js
packages/react-router/test-app/src/App.tsx
packages/react-router/test-app/src/pages/Main.tsx
packages/react-router/test-app/src/pages/outlet-ref/OutletRef.tsx
packages/react-router/test-app/src/pages/swipe-to-go-back/SwipToGoBack.tsx
packages/react/src/routing/RouteManagerContext.ts

fix(react): fixes swipe to go back regression

---

core/src/utils/overlays.ts

fix(overlay): do not try to trap focus on hidden inputs

---

core/src/components/route/readme.md

docs(route): add correct interface name

---

core/src/components/loading/readme.md
core/src/components/loading/usage/angular.md
core/src/components/loading/usage/javascript.md
core/src/components/loading/usage/stencil.md
core/src/components/loading/usage/vue.md

In some of the examples, the `cssClass` property is being set twice, which causes an error.
- The `cssClass` property is set only once.

docs(loading): remove duplicated cssClass property

---

packages/react-router/test-app/package.json
packages/react/src/components/navigation/IonTabs.tsx

fix(react): using autonomous web component for safari support, closes #21803

---

core/package-lock.json
core/package.json

chore(): bump stencil to 1.17.1

---

packages/react-router/test-app/cypress/integration/routing.spec.js
packages/react/src/components/navigation/IonTabBar.tsx

fix(reat): fix tab currentHref when changing tabs, closes #21834

---

core/src/components/segment-button/readme.md

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/21961
-
-
-

docs(segment-button): add correct usage for checking segment button

---

packages/react/src/components/index.ts

https://twitter.com/joshuamorony/status/1296595258453581825
-
-
-

fix(react): export correct animation types

---

.npmrc
.scripts/common.js
CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

Release 5.3.2

---

core/src/components/infinite-scroll/readme.md

chore(): run build on infinite scroll docs

---

.scripts/common.js
core/package-lock.json
core/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue-router/src/index.ts
packages/vue-router/src/router.ts
packages/vue-router/src/types.ts
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/hardware-back-button.ts
packages/vue/src/index.ts

Adds a hook vue users can use to listen for hardware back button events

feat(vue): add hardware back button hook

---

core/src/components/datetime/datetime-util.spec.ts
core/src/components/datetime/datetime-util.ts
core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/basic/index.html

Dev build: `5.4.0-dev.202009102321.26d3971`
Open a datetime with an hour, minute and ampm column. Change to "pm" then change the hour. See the pm switch to am.
Issue Number: fixes #19175 fixes #19260 fixes #20026 references #16630
Correctly remains on pm by setting it on the datetime value.

fix(datetime): do not reset to am when changing hour and pm is set

---

core/src/components/textarea/textarea.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/21542
- Textarea has its own unique ID now

fix(textarea): do not generate duplicate IDs between ion-input and ion-textarea

---

.scripts/common.js
.scripts/release.js
CHANGELOG.md
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/react-router/package.json
packages/react/package.json

Release 4.11.11

---

.circleci/config.yml
core/package-lock.json
packages/vue-router/__tests__/locationHistory.spec.ts
packages/vue-router/__tests__/viewStacks.spec.ts
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue-router/src/locationHistory.ts
packages/vue-router/test/jest.preprocessor.js
packages/vue/package-lock.json

tests(vue): add spec tests, gh actions integration

---

packages/vue-router/src/index.ts

chore(vue): wrap isReady for potential future use

---

packages/vue-router/src/index.ts

Vue Router allows for 2 additional history types that Ionic Vue does not currently expose
- expose `createWebHashHistory` and `createMemoryHistory` functions

feat(vue): add webHashHistory and memoryHistory options for router

---

core/package-lock.json
core/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

chore(): release Ionic Vue 0.4.0

---

core/src/components/picker-column/picker-column.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22137
- We now check `detail.event.cancelable` before attempting to call `preventDefault`

fix(picker-column): add cancelable check to avoid intervention error in chrome

---

packages/vue-router/src/viewStacks.ts
packages/vue/src/components/IonRouterOutlet.ts

- Check to make sure page is a child of a tabs before deciding where to render

fix(vue): correctly render child pages in tabs

---

packages/vue/src/hooks.ts
packages/vue/src/index.ts

- Adds keyboard hook so developers can listen for keyboard open/close events

feat(vue): add keyboard hook

---

core/src/components/reorder-group/readme.md
core/src/components/reorder-group/usage/angular.md

Improve Angular example by adding missing (`any`) typehint of the event
-
-
-

docs(reorder-group): add type to the event param

---

CHANGELOG.md
core/package-lock.json
core/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

ionic vue 0.5.0

---

core/src/components/action-sheet/readme.md
core/src/components/action-sheet/usage/vue.md
core/src/components/alert/readme.md
core/src/components/alert/usage/vue.md
core/src/components/loading/readme.md
core/src/components/loading/usage/vue.md
core/src/components/modal/readme.md
core/src/components/modal/usage/vue.md
core/src/components/popover/readme.md
core/src/components/popover/usage/vue.md
core/src/components/toast/readme.md
core/src/components/toast/usage/vue.md

docs(vue): add revised overlay examples

---

core/stencil.config.ts
packages/vue/src/components/IonIcon.ts
packages/vue/src/index.ts
packages/vue/src/proxies.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/19078
- Added logic similar to Ionic React to switch icons based upon mode

fix(vue): correctly handle platform specific icons

---

core/src/components/modal/readme.md
core/src/components/modal/usage/vue.md

docs(modal): fix props on vue example

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

Release 5.3.4

---

core/src/components/datetime/datetime-util.ts

fix(datetime): remove the automatic switching from am to pm and vice versa

---

packages/vue/src/components/IonNav.ts
packages/vue/src/framework-delegate.ts
packages/vue/src/index.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22184
- IonNav was missing a framework delegate in order to handle Vue components properly. This PR adds it.

fix(vue): ion-nav now handles Vue components properly

---

core/package-lock.json
core/package.json
packages/vue/src/vue-component-lib/utils.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22079
Updates stencil ds dep

fix(vue): correctly update property values

---

packages/vue/src/components/IonTabs.ts

fix(vue): add missing tabs attribute to router outlet inside ion-tabs

---

packages/vue-router/src/router.ts
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/cypress.json
packages/vue/test-app/package-lock.json
packages/vue/test-app/package.json
packages/vue/test-app/src/views/Navigation.vue
packages/vue/test-app/tests/e2e/specs/navigation.js
packages/vue/test-app/tests/e2e/support/commands.js

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22229
- Add query string to url
- Check if entering and leaving view items are same, if so do nothing

fix(vue): correctly handle query params

---

core/src/components/radio-group/radio-group.tsx

Dev build: `5.4.0-dev.202009292111.04fb00f`
Issue Number: fixes #22179
-
-
-

fix(select): do not close popover or set value when switching with arrow keys

---

core/package-lock.json
packages/vue/src/components/IonTabBar.ts
packages/vue/test-app/src/views/Tab1.vue
packages/vue/test-app/src/views/Tabs.vue
packages/vue/test-app/tests/e2e/specs/tabs.js

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22255
- Fixed undefined check when selecting tab

fix(vue): ion-tab-bar no longer throws undefined error when re-creating tabs

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

Release 5.3.5

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

5.4.0-rc.1

---

packages/vue/test-app/package.json
packages/vue/test-app/scripts/sync.sh

chore(vue): add sync script

---

packages/vue/src/components/IonPage.ts
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/src/components/ModalContent.vue

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22300
- Check `isInOutlet` prop that is only set true when an ion router outlet renders the ionpage component

fix(vue): do not hide page content when using ion-page in non-routing contexts

---

packages/vue-router/src/viewStacks.ts
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/package-lock.json
packages/vue/test-app/package.json
packages/vue/test-app/scripts/sync.sh
packages/vue/test-app/src/router/index.ts
packages/vue/test-app/src/views/Home.vue
packages/vue/test-app/src/views/NestedChild.vue
packages/vue/test-app/src/views/RouterOutlet.vue
packages/vue/test-app/src/views/Tab1.vue
packages/vue/test-app/src/views/Tab1Secondary.vue
packages/vue/test-app/src/views/Tab2Secondary.vue
packages/vue/test-app/src/views/Tab3Secondary.vue
packages/vue/test-app/src/views/TabsSecondary.vue
packages/vue/test-app/tests/e2e/specs/nested.js
packages/vue/test-app/tests/e2e/specs/tabs.js

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22286
- Add checks in IonRouterOutlet to make sure that each outlet is only rendering content that should be rendered

fix(vue): pages now render in correct outlet when using multiple nested outlets

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

5.4.0-rc.2

---

core/src/components/virtual-scroll/readme.md

docs(vue): add note on virtual scroll

---

core/src/components/infinite-scroll-content/readme.md
core/src/components/infinite-scroll-content/usage/vue.md
core/src/components/infinite-scroll/readme.md
core/src/components/infinite-scroll/usage/vue.md

docs(vue): add infinite scroll examples

---

packages/vue-router/README.md
packages/vue/CHANGELOG.md
packages/vue/README.md

chore(): add vue and vue-router readmes

---

packages/vue-router/src/types.ts
packages/vue/src/components/IonPage.ts
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/src/views/TabsSecondary.vue

Issue Number: when HMR replaces an entire component, a new `ion-page` instance is created. This new instance is not linked to its ViewItem and is hidden by default.
This causes for a frustrating development experience as it requires users to reload the entire app every time they make a change.
Note: This only applies when changing the logic of the component. Changing the template/styles is not impacted.
- Properly re-register an ionpage every time it is re-mounted

fix(vue): ion-page component is properly shown with HMR

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

5.4.0-rc.3

---

packages/vue-router/package-lock.json
packages/vue-router/package.json

chore(vue): update @ionic/vue-router dependency version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/support_question.md
angular/README.md
core/README.md
packages/react/README.md

chore(): point people to the forum

---

core/src/components/menu/readme.md
core/src/components/menu/usage/vue.md

docs(vue): fix menuController import

---

core/src/components/segment-button/segment-button.tsx
core/src/components/segment/segment.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/20831
- Listen for ionStyle changes in ion-segment to know when to update ion-segment-button

fix(segment-button): color property is now reactive if previously undefined

---

packages/vue-router/src/router.ts
packages/vue/test-app/src/views/Routing.vue
packages/vue/test-app/tests/e2e/specs/routing.js

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22412
- Checked `history.state.replaced` to see if route was replaced

fix(vue): ensure view is updated correctly when replacing a route outside of a nav guard

---

README.md

chore(): fix vue readme path

---

.scripts/common.js
.scripts/release.js
CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

Release 5.4.2

---

core/src/components/refresher/refresher.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/20832
- Increased gesture priority to be 1 higher than side menu's gesture priority

fix(refresher): refresher gesture now works in side menu

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
core/stencil.config.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

Release 5.4.3

---

core/src/components/checkbox/readme.md
core/src/components/checkbox/usage/vue.md

It looks like the docs are still using the Vue 2 syntax for binding events, I thought I was doing something wrong but Vue DevTools clearly states that the components emits an update:modelValue event instead of the input event. I also fixed the name for the checked key.
The docs for Vue show a wrong two-way binding (it's Vue 2 style).
Now it works with Vue 3.
-
-
-

docs(checkbox): fix vue 3 event binding example

---

.circleci/config.yml
CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
core/stencil.config.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

Release 5.4.4

---

core/src/components/input/input.tsx
core/src/components/textarea/textarea.tsx
core/src/utils/helpers.ts
core/src/utils/test/attributes.spec.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22055
- title attr is inherited on input and textarea

fix(input): title attribute is automatically inherited

---

.scripts/release.js

This reverts commit 0eb643d5637b30b5790a55bb383c987cf8ad0502.
We re-added the es5 build after an error on our end, so we should re-add the production check
-
-
-

chore(): re-add es5 check

---

core/src/components/tab/readme.md
core/src/components/tabs/readme.md
core/src/components/tabs/usage/vue.md

docs(tabs): add correct vue examples

---

angular/test/test-app/package.json

test(angular): fix e2e tests

---

.github/ionic-issue-bot.yml

Ideally what we want is the issue reproduced in a starter app, and people don't always know that (they don't click into the "Contributing Guide")
Additionally, some people have been confused when this label is added but they have already provided a code snippet which is a "code reproduction" to them. This PR clarifies that if they are seeing this message, then their code snippet was not enough to reproduce the issue.
-
-
-

chore(): update "needs reproduction" wording for clarity

---

core/src/components/modal/readme.md
core/src/components/modal/usage/angular.md
core/src/components/modal/usage/javascript.md
core/src/components/modal/usage/react.md
core/src/components/modal/usage/stencil.md
core/src/components/modal/usage/vue.md

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22514
- Added docs on the usage of ion-page when wrapping modal component
- Also fixed the vue example

docs(modal): include note on using ion-page when wrapping modal component

---

packages/react-router/package.json
packages/react/package.json

There was an issue in @types/react@16.14.1 (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49713) that caused build errors when trying to build Ionic React. This PR fixes the version to 16.14.0 until a fix is released.
-
-
-

chore(): fix @types/react to avoid 16.14.1 release

---

angular/test/test-app/package.json
core/src/components/checkbox/checkbox.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22557
- moved preventDefault/stopPropagation to the inner input instead

fix(checkbox): click events on ion-item now fire properly

---

packages/react/src/components/__tests__/createComponent.spec.tsx
packages/react/src/components/createComponent.tsx
packages/react/test/test-app/src/index.tsx

fix(react): eliminate use of deprecated `findDOMNode`, closes #20972

---

core/src/components/checkbox/checkbox.tsx
core/src/components/checkbox/test/basic/index.html
core/src/components/radio-group/radio-group.tsx
core/src/components/select/select.tsx
core/src/components/toggle/toggle.tsx

resolves https://github.com/ionic-team/ionic-framework/issues/22557

fix(a11y): only preventDefault for the onClick event 

---

CHANGELOG.md

chore(): add note on 5.5.1 upgrading

---

packages/vue/src/components/IonRouterOutlet.ts
packages/vue/src/utils.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22567
- Add config check for swipeBackEnabled

fix(vue): swipe back gesture is properly disabled when swipeBackEnabled config is false

---

packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/tests/e2e/specs/routing.js
packages/vue/test-app/tests/unit/lifecycle.spec.ts
packages/vue/test-app/tests/unit/routing.spec.ts
packages/vue/test-app/tests/unit/tabs.spec.ts
packages/vue/test-app/tests/unit/utils.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22492
- Added additional check to see if we should unmount components that have been replaced

fix(vue): correctly remove old view when replacing route

---

core/src/components/app/app.tsx
core/src/utils/hardware-back-button.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/18237
- Add a no-op backbutton event listener to block default webview behavior.

fix(android): setting hardwareBackButton: false in config now disabled default webview behavior

---

packages/vue-router/src/router.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22591
- Look at `failure` param before moving forward with ion router logic

fix(vue): correctly handle navigation failures

---

packages/react-router/src/ReactRouter/IonRouter.tsx
packages/react/src/components/IonRouterContext.tsx
packages/react/src/models/RouterOptions.ts
packages/react/src/routing/NavManager.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22611
-
-
-

React Android Back Button Fixes

---

packages/vue-router/src/types.ts
packages/vue-router/src/viewStacks.ts
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/tests/unit/routing.spec.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22602
- Correct injectedRoute is now passed into props fn
- Props fn is now only called on initial render

fix(vue): pass in correct route to props function

---

core/src/components/menu/readme.md
core/src/components/menu/usage/vue.md

The element id referenced on the menu is being declared incorrectly, causing the menu component to not work.
The menu vue use example now works correctly.
I was unable to build, it seems that I don't have the necessary packages (even after running the 'npm install').

docs(vue): fix menu usage example

---

core/src/components/button/button.tsx
core/src/components/button/test/standalone/index.html

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22629
- Inherit aria-label to inner button element

fix(button): allow aria-label to be inherited to inner button

---

packages/vue-router/src/router.ts

> Using APIs built into Vue Router and not doing anything custom so I decided not to add tests as we'd just be testing the vue router functionality.
Issue Number: resolves #22517
- Use correct vue-router api for navigating

fix(vue): query strings are now correctly handled when navigating back

---

packages/react-router/package.json
packages/react/package.json

Issue Number: resolves #22644
- Peer deps requirement is now similar to Ionic Angular's

chore(react): relax peer dependency requirements

---

core/src/components/item/test/disabled/index.html

The item disabled test is broken.
-
-
-

test(item): fix disabled test script path

---

.circleci/config.yml
packages/vue-router/src/router.ts
packages/vue-router/src/types.ts

chore(vue): import animation types from @ionic/vue instead of @ionic/core

---

core/src/components/tab-button/readme.md
core/src/components/tab-button/usage/vue.md

Vue example currently implies that a route might be constructed from the tab name like we do in Angular.
Provides a more real-world short of example

doc(tab-button): use an href in vue sample

---

core/src/components/tab-bar/tab-bar.tsx

Since events are all lowercase for Vue, tab bar was listening for `keyboardwillshow`. However, Capacitor/Cordova emit `keyboardWillShow` so we need to eject from the lowercasing for tab bar.
- Tab bar correctly listens for `keyboardWillShow` and `keyboardWillHide`

fix(vue): tab bar is now correctly hidden when keyboard is open

---

.github/ionic-issue-bot.yml

chore(): start holiday triage mode

---

core/src/components/datetime/test/basic/e2e.ts

test(datetime): improve reliability of focus trap test

---

.github/ionic-issue-bot.yml

chore(): end holiday triage mode

---

core/package-lock.json
core/package.json
core/stencil.config.ts
packages/vue/src/proxies.ts
packages/vue/src/vue-component-lib/utils.ts

fix(vue): all ionic vue components can now use router link

---

core/package-lock.json
core/package.json
packages/vue/src/vue-component-lib/utils.ts

Issue Number: resolves #22731
Updating v-model multiple times caused the wrappers to get out of sync and render an old value
- Wrappers now render correct value based upon the model change events

fix(vue): improve v-model binding sync between vue wrappers and web components

---

packages/react-router/src/ReactRouter/IonRouter.tsx
packages/vue-router/src/router.ts
packages/vue/test-app/src/views/Home.vue
packages/vue/test-app/tests/e2e/specs/routing.js
packages/vue/test-app/tests/e2e/support/commands.js

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22528
- Check if the pushedByRoute is equal to the new route pathname first instead of just assigning the pushedByRoute value

fix(react, vue): do not show back button when replacing to root page

---

core/src/utils/transition/ios.transition.ts

Issue Number: resolves #22760
- Only select title when used in ion-content

fix(title): only add large title transition when using collapsible header

---

core/package-lock.json
core/package.json
packages/vue/src/vue-component-lib/utils.ts

Issue Number: resolves #22610
- ionChange is now emitted from the vue wrapper instance, ensuring that any v-model bindings are updated before the change event is fired to the user.

fix(vue): ensure v-model value is properly synced before ionChange event

---

packages/react/src/components/createOverlayComponent.tsx

Issue Number: resolves #22761
- Removed `isOpen` check

fix(react): do not unmount overlay inner component until overlay is dismissed

---

packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue-router/rollup.config.js
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/rollup.config.js
packages/vue/tsconfig.json

Issue Number: #22765
- adds dist/index.esm.js
- makes dist/index.js as module es2015 instead of esnext
I wanted to dive into SSR and @ionic/vue but found these inconsistencies. I mainly compared it with @ionic/react, which works in node env.

chore(vue): make @ionic/vue build usable in node envs

---

core/src/utils/input-shims/hacks/input-blurring.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22856
- Added `[contenteditable]` to skip selector list in blurring util.

fix(app): keyboard no longer hides when using contenteditable

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/schematics/add/index.ts
angular/src/schematics/utils/config.ts
core/package-lock.json
core/package.json
core/src/components/select/select.tsx
core/src/utils/input-shims/hacks/input-blurring.ts
core/src/utils/input-shims/hacks/scroll-assist.ts
core/stencil.config.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/react/src/components/IonRouterContext.tsx
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/components/navigation/IonTabs.tsx
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/ionic-vue.ts
packages/vue/src/proxies.ts
packages/vue/src/vue-component-lib/utils.ts

Release 5.5.4

---

core/src/themes/test/css-variables/css/dark.css
core/src/themes/test/css-variables/css/toolbar.css
core/src/themes/test/css-variables/index.html

Docs PR: https://github.com/ionic-team/ionic-docs/pull/1830
Starters PR: https://github.com/ionic-team/starters/pull/1667
Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22779
- Applies dark mode theme to body, not every element that has `.ios` or `.md`
- Add new dark theme for modal

fix(): update modal dark theme, fix styles test

---

BREAKING.md
core/src/components/header/header.ios.scss

Issue Number: resolves #22777
- Uncollapsed large title no longer has border

refactor(header): removed border from last toolbar when using collapsible large title

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/schematics/add/index.ts
angular/src/schematics/utils/config.ts
core/package-lock.json
core/package.json
core/src/components/select/select.tsx
core/src/themes/test/css-variables/css/dark.css
core/src/themes/test/css-variables/css/toolbar.css
core/src/themes/test/css-variables/index.html
core/src/utils/input-shims/hacks/input-blurring.ts
core/stencil.config.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/ionic-vue.ts
packages/vue/src/proxies.ts
packages/vue/src/vue-component-lib/utils.ts

chore(): sync with master branch

---

packages/react/src/components/createComponent.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22903
- Removed string type check and allowed any prop values

fix(react): IonRouterOutlet now respects animated={false} prop

---

core/src/themes/test/css-variables/css/dark.css
core/src/themes/test/css-variables/index.html

test(): update theming test with latest dark mode values

---

core/src/components/progress-bar/progress-bar.scss

https://github.com/ionic-team/ionic-framework/pull/22957#issuecomment-784474986
- changing width now animates
-

fix(progress-bar): add width transition

---

packages/react-router/src/ReactRouter/IonRouter.tsx
packages/vue-router/src/router.ts

Issue Number: resolves #22830
- When going back, check if the prev route we have in the stack history matches the "pushedByRoute" value in addition to checking if the last path name equals pushedByRoute

fix(react, vue): navigating using ion-back-button now selects correct page

---

core/package-lock.json
core/package.json
core/stencil.config.ts
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/ionic-vue.ts
packages/vue/src/proxies.ts
packages/vue/src/vue-component-lib/utils.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22977
- Account for vue changing event bindings from "ionRefresh" to both "ionrefresh" and "ion-refresh".

fix(vue): account for event name changes in vue 3.0.6+

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
core/stencil.config.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/ionic-vue.ts
packages/vue/src/proxies.ts
packages/vue/src/vue-component-lib/utils.ts

Release 5.5.5

---

angular/test/test-app/package.json

chore(): update web driver

---

core/src/components/modal/readme.md
core/src/components/modal/usage/react.md

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23005, resolves https://github.com/ionic-team/ionic-framework/issues/22774
- Removed recommendation to use IonPage -- doesn't seem to be needed for Ionic React

docs(modal): remove incorrect ion-page note for react

---

.github/COMPONENT-GUIDE.md

adds a notice of webkit bug with VoiceOver

docs(github): update component guide to include switch

---

core/src/components/item/item.md.scss

chore(): remove duplicate --color definition in ion-item

---

core/src/components/router/utils/matching.ts

`{...obj, ...undefined}` equals `obj` so the code could be simplified.
The original code might have an edge on perf on memory usage but I don't think merging router parameter is on any critical perf path. Improved readability and less lines of code should be better.
I have also added types and comments which are always nice :)

[Router] code simplification

---

packages/vue-router/src/viewStacks.ts
packages/vue/test-app/tests/unit/routing.spec.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23043
- Update the params object and bust the props function result cache if params have changed.

fix(vue): correctly pass params as props

---

core/src/components/item/item.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23054
- added aria-hidden to detail icon so screen readers no longer announce it

fix(item): detail icon is no longer announced by screen readers

---

core/src/components/input/input.scss
core/src/components/label/label.ios.scss
core/src/components/label/label.md.scss
core/src/components/label/test/floating/index.html
core/src/components/textarea/test/spec/index.html
core/src/components/textarea/textarea.scss

- Floating labels properly "float" (behave same as stacked) for items that are not inputs (datetime, select)
- Textarea behaves the same as input with floating label but the transform is over the placeholder text
- Test this at either of these:
-  http://localhost:3333/src/components/label/test/floating
- http://localhost:3333/src/components/textarea/test/spec

fix(label): properly float labels for non-input items

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/directives/virtual-scroll/virtual-scroll.ts
core/package-lock.json
core/package.json
core/src/components/input/input.scss
core/src/components/item/item.md.scss
core/src/components/item/item.tsx
core/src/components/label/label.ios.scss
core/src/components/label/label.md.scss
core/src/components/label/test/floating/index.html
core/src/components/refresher/refresher.tsx
core/src/components/router/utils/matching.ts
core/src/components/textarea/test/spec/index.html
core/src/components/textarea/textarea.scss
core/src/utils/helpers.ts
core/src/utils/test/ready.spec.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/react/src/components/navigation/IonTabs.tsx
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue-router/src/viewStacks.ts
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/test-app/tests/unit/routing.spec.ts

Release 5.6.1

---

packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/test-app/cypress/integration/routing.spec.js
packages/react-router/test-app/src/pages/routing/Details.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22692
- Check if entering view was pushed by a page, if so then there's a page to go back to

fix(react): correctly show ion-back-button when going back

---

core/package-lock.json
core/package.json

Stencil uses a newer version of TypeScript which must not be compatible with our old installation of tslib.
- Updating tslib to latest solves error we received in https://github.com/ionic-team/ionic-framework/issues/23090

chore(): update tslib dependency to latest

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/test-app/cypress/integration/routing.spec.js
packages/react-router/test-app/src/pages/routing/Details.tsx
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

Release 5.6.3

---

.github/PROCESS.md

chore(): update process guide for needs reproduction label

---

core/package-lock.json
core/package.json
packages/vue/src/vue-component-lib/utils.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22886
- Bumped stencil ds output target to ensure that model prop value is updated during render

fix(vue): components now integrate properly with vee-validate

---

core/package-lock.json
core/src/components/modal/readme.md
core/src/components/modal/usage/angular.md

fixes ionic-team/ionic-docs#1872
Documentation content fix.

fix modal controller doc error

---

core/src/components/reorder-group/readme.md
core/src/components/reorder-group/usage/vue.md

Issue Number: resolves ionic-team/ionic-docs#1804

docs(reorder-group): fix vue usage of reorder-group

---

core/src/components/alert/readme.md
core/src/components/alert/usage/angular.md
core/src/components/alert/usage/javascript.md
core/src/components/alert/usage/react.md
core/src/components/alert/usage/stencil.md
core/src/components/alert/usage/vue.md

Issue Number: resolves ionic-team/ionic-docs#1819

docs(alert): add input handler to usage examples

---

core/src/components/action-sheet/readme.md
core/src/components/action-sheet/usage/angular.md
core/src/components/action-sheet/usage/javascript.md
core/src/components/action-sheet/usage/stencil.md
core/src/components/action-sheet/usage/vue.md
core/src/components/alert/readme.md
core/src/components/alert/usage/angular.md
core/src/components/alert/usage/javascript.md
core/src/components/alert/usage/stencil.md
core/src/components/alert/usage/vue.md
core/src/components/popover/readme.md
core/src/components/popover/usage/angular.md
core/src/components/popover/usage/javascript.md
core/src/components/popover/usage/stencil.md
core/src/components/popover/usage/vue.md
core/src/components/toast/readme.md
core/src/components/toast/usage/angular.md
core/src/components/toast/usage/javascript.md
core/src/components/toast/usage/stencil.md
core/src/components/toast/usage/vue.md

Issue Number: resolves ionic-team/ionic-docs#660

docs(action-sheet, alert, popover, toast): update usage to show onDidDismiss

---

.circleci/config.yml
packages/react-router/test-app/cypress.json
packages/react-router/test-app/cypress/integration/swipe-to-go-back.js
packages/react-router/test-app/cypress/support/commands.js
packages/react-router/test-app/package-lock.json
packages/react-router/test-app/package.json
packages/react-router/test-app/scripts/sync.sh

tests(react): run e2e tests on CI

---

core/src/components/toggle/test/basic/index.html
core/src/components/toggle/toggle.scss

fix(toggle): prevent click event on toggle from double firing

---

packages/react-router/src/ReactRouter/IonRouter.tsx
packages/react-router/test-app/cypress/integration/tabs.js
packages/react-router/test-app/src/App.tsx
packages/react-router/test-app/src/pages/tabs/Tabs.tsx
packages/react-router/test-app/src/pages/tabs/TabsSecondary.tsx
packages/vue-router/src/router.ts
packages/vue/test-app/tests/e2e/specs/tabs.js

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23087 resolves https://github.com/ionic-team/ionic-framework/issues/23101
- Previous fix assumed that navigation is linear, but this is not always the case when using tabs. Tabs are now excluded from this change.

fix(react, vue): correct view now chosen when going back inside tabs

---

core/src/components/slides/test/basic/index.html

Fixed typo.
```
transistion -> transition
```

test(core): Fix typo in basic/index.html

---

core/src/components/input/input.tsx

Issue Number: resolves #22814 
- `aria-label` is now inherited from Host element to inner input element.

fix(input): inherit aria-label to input

---

core/src/components/content/content.tsx

Issue Number: resolves #22808
- When `ion-content` is a child of `ion-menu`, child content is now wrapped in a `div` rather a `main` element.

fix(content): change main child element to div when parent is menu

---

packages/vue/src/vue-component-lib/overlays.ts

chore(vue): fix typo in comments

---

packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/src/router/index.ts
packages/vue/test-app/src/views/Folder.vue
packages/vue/test-app/src/views/RoutingParameter.vue
packages/vue/test-app/tests/e2e/specs/tabs.js
packages/vue/test-app/tests/unit/routing.spec.ts

- Listen for route object changes instead of matchedRouteRef

fix(vue): update props when navigating to new parameterized route

---

packages/vue/src/components/IonTabBar.ts
packages/vue/test-app/src/views/Tabs.vue
packages/vue/test-app/tests/e2e/specs/tabs.js

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22847
- Add support for dynamic tabs generated in a v-for

fix(vue): dynamic tabs are now supported

---

core/src/components/slides/slides.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22289
- Add an undefined check in `optionsChanged` before updating swiper instance

fix(slides): undefined error is no longer thrown after destroying and quickly re-creating ion-slides

---

packages/vue/src/components/IonApp.ts
packages/vue/src/components/IonNav.ts
packages/vue/src/framework-delegate.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23233
- Components are now rendered inside of `ion-nav` instead of in `ion-app`

fix(vue): components inside of ion-nav are now unmounted properly

---

core/src/css/core.scss

Reverts ionic-team/ionic-framework#23181

chore(): revert #23181

---

core/src/components/modal/test/basic/index.html
core/src/css/core.scss

Issue Number: resolves #22778 
- Toolbars in modals on iOS now have additional padding

fix(modal): add additional padding to toolbars in iOS modal

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/app-initialize.ts
core/package-lock.json
core/package.json
core/src/components/modal/readme.md
core/src/components/refresher/refresher.tsx
core/src/components/refresher/refresher.utils.ts
core/src/css/core.scss
core/src/utils/overlays.ts
core/src/utils/test/overlays.spec.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue-router/src/router.ts
packages/vue/package-lock.json
packages/vue/package.json

Release 5.6.7

---

.circleci/config.yml

- We persist the build results from the `build-core` step,  so rebuilding in `test-core-e2e` is just doing unnecessary work.
- Vue spec tests take so little time that it takes longer to setup/teardown the CI environment than it takes to run the actual tests. Since E2E and spec tests depend on the same test app directory, just have them be run in the same job.

chore(): do not rebuild core when doing e2e tests, run vue spec and e2e tests together

---

core/src/components/range/range.tsx
core/src/components/range/test/a11y/index.html
core/src/components/range/test/a11y/screen-readers.md
core/src/components/range/test/basic/index.html
core/src/components/range/test/standalone/index.html

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23295
- Inherited any aria-label, label, or ion-label values to the inner knob in the shadow dom

fix(range): knob can now have an accessible name

---

core/src/components/skeleton-text/skeleton-text.scss

- [ X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ X] Build (`npm run build`) was run locally and any changes were pushed
- [X ] Lint (`npm run lint`) has passed locally and any fixes were made for failures
- [X ] Bugfix
https://github.com/ionic-team/ionic-framework/issues/22694
Issue Number: #22694
- Smooth Animation even if the width is more then 800px
- [X ] No

fix(skeleton-text): animation no longer jumps on large skeleton text elements

---

packages/react-router/package.json
packages/react-router/src/ReactRouter/IonRouter.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23346
- React router only needed the AnimationBuilder interface from @ionic/core, but that interface is also exported from @ionic/react. I changed the import from core to react and removed @ionic/react-routers's dependency on core.

fix(react): remove @ionic/core dependency in @ionic/react-router to resolve yarn install warning

---

core/src/components/fab/readme.md
core/src/components/fab/usage/vue.md

See: https://forum.ionicframework.com/t/ion-icon-not-visible-on-ion-fab-button/209961/3
Incorrect `ion-icon` usage was documented for vue, so icons were not showing up.
- Switched example to use local icon registration in the fab docs

docs(fab): document correct ion-icon usage for vue

---

core/src/components/accordion/test/a11y/e2e.ts
core/src/components/accordion/test/basic/e2e.ts
core/src/components/accordion/test/standalone/e2e.ts

Screenshots do not like that I placed a `e2e.ts` file in the root `test` directory as it expected an `index.html` file to be there as well.
- Placed separate e2e files in each of the test directories

chore(): update e2e structure for accordion tests so screenshots run

---

core/src/components/router/router.tsx
core/src/components/router/utils/dom.ts
core/src/components/router/utils/parser.ts
core/src/components/router/utils/path.ts

A few minor changes that make the code easier to read (IMO).
I am wondering there is a need for the chain abstraction ?
Every single branch of the route tree is converted to a list of "chain". 
It might be as simple (also simplify the code and be a little more efficient) to work with the tree directly.
@liamdebeasi any thoughts on that ?

cleanup(router): Cleanup code, add comments

---

angular/src/providers/platform.ts

chore(angular): fix typo in platform provider

---

core/src/components/radio-group/radio-group.tsx

https://github.com/ionic-team/ionic-framework/pull/23386
- n/a

chore(radio-group): use existing helper function for getting all radios

---

core/src/components/radio-group/radio-group.tsx

…all radios (#23394)"
This reverts commit 62ed9712e1239499742ba5bd6030d9f9e3512ecc.
-
-
-

chore(): revert incorrect co-author credit

---

core/src/components/radio-group/radio-group.tsx

https://github.com/ionic-team/ionic-framework/pull/23386
Used `this.getRadios()` instead of re-writing contents of function.

chore(radio-group): clean up code to reuse helper function

---

core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/data.spec.ts
core/src/components/datetime/test/state.spec.ts
core/src/components/datetime/test/values/e2e.ts
core/src/components/datetime/test/values/index.html
core/src/components/datetime/utils/data.ts
core/src/components/datetime/utils/parse.ts
core/src/components/datetime/utils/state.ts

feat(datetime): implement dayValues, minuteValues, monthValues, and yearValues

---

core/src/components/datetime/datetime.tsx

fix(datetime): prevent IO from incorrectly firing when overlays open

---

core/src/components/item/item.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23427
- Wrapped the setMultipleInputs call in `componentDidLoad` in an `raf

fix(item): using multiple items with inputs no longer results in console warnings

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/providers/platform.ts
core/package-lock.json
core/package.json
core/src/components/modal/gestures/swipe-to-close.ts
core/src/components/modal/test/custom/index.html
core/src/components/popover/readme.md
core/src/components/popover/usage/vue.md
core/src/components/radio-group/radio-group.tsx
core/src/components/router/router.tsx
core/src/components/router/utils/dom.ts
core/src/components/router/utils/parser.ts
core/src/components/router/utils/path.ts
core/src/components/title/title.ios.scss
core/src/utils/config.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/vue-component-lib/utils.ts

Release 5.6.9

---

core/src/components/popover/utils.ts

feat(popover): account for ionShadowTarget elements

---

core/src/components/popover/popover.tsx

When documenting the shadow parts in `ion-popover` I forgot to actually add them to the element 🤦 
- The shadow parts are actually there now

fix(popover): shadow parts now correctly added 

---

BREAKING.md

Framework v6 is going to better define exactly which browser, JS framework, and mobile platform versions it supports as it has been a source of confusion in the past.
Additionally, we are dropping support for iOS 11 and iOS 12.

refactor(all): update required browser, framework, and mobile platform versions for v6

---

core/src/components/datetime/datetime.tsx

changing the time only updated working parts, which did not cause ionChange to fire
changing the time now updated active parts, which will cause ionChange to fire

fix(datetime): changing time emits ionChange

---

packages/vue/package.json

Unless the core CSS is explicitly marked as a sideffect, Webpack will eliminate the CSS when doing a prod build, even if you explicitly import those files in your Vue `main.ts` file
- CSS is marked as a sideeffect so webpack should bundle it now.

fix(vue): ensure webpack does not eliminate core css

---

packages/vue/src/components/IonTabs.ts
packages/vue/src/components/Overlays.ts
packages/vue/test-app/src/views/TabsNew.vue

chore(): sync with master

---

package.json

chore(): add missing dependency

---

BETA.md

chore(): add v6 beta instructions

---

BETA.md

chore(): add v6 beta note on starting a new app

---

BETA.md

chore(): fix typos in v6 beta doc

---

.github/ISSUE_TEMPLATE/feature_request.md

chore(): add 6.x to feature request template

---

.github/ISSUE_TEMPLATE/bug_report.md

chore(): add 6.x to bug report template

---

README.md

chore(): add link to v6 beta onboarding guide

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

6.0.0-beta.0

---

core/src/components/accordion-group/readme.md

docs(accordion-group): fix link to accordion

---

core/src/components/slides/readme.md
core/src/components/virtual-scroll/readme.md

docs(virtual-scroll, slides): add correct links to migration guides

---

core/src/components/virtual-scroll/readme.md

docs(virtual-scroll): fix ion-img link

---

angular/src/directives/proxies.ts
core/api.txt
core/src/components.d.ts
core/src/components/accordion-group/accordion-group.tsx
core/src/components/accordion-group/readme.md
core/src/components/accordion/accordion.tsx
core/src/components/accordion/test/accordion.spec.ts
packages/vue/src/proxies.ts

Issue Number: required for https://github.com/ionic-team/ionic-framework/tree/accordion-anim as animations + state changes are now async to fix a bug/improve performance, so just doing `page.waitForChanges` is not enough to get tests to pass since state change is done 1 frame after.
- Accordion group has an `animated` property that can be used to disable animations on all child accordions

feat(accordion-group): add animated property to disable animations

---

core/src/components/accordion/accordion.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23504
- Previous force paint hack was getting built out, so the code never made it to applications
- Instead, I opted to make the state change + animation async but without breaking up the transition + height animation (which would cause the animations to get out of sync with other accordion animations)

fix(accordion): improved reliability of accordion animations

---

core/src/components/card/readme.md
core/src/components/card/usage/vue.md

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23533
- Example now correctly imports IonCardHeader and provides it to Vue component.

docs(card): fix usage example for vue

---

core/src/components/content/content.scss

Issue Number: resolves #22805 
- `ion-content` now has `touch-action: manipulation` by default. This allows better zooming and panning behaviors when not disabled by the page's `<meta name="viewport">` tag. 
- In order to enable zooming and panning, make sure the page's `<meta name="viewport">` does not contain `user-scalable="no"` or a `maximum-scale` of less than 2.

fix(content): add touch-action manipulation for a11y zoom and pan

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CHANGELOG.md
README.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
core/src/components/card/readme.md
core/src/components/card/usage/vue.md
core/src/utils/animation/animation-interface.ts
core/src/utils/transition/index.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

Release 5.6.11

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CHANGELOG.md
README.md
core/src/components/card/readme.md
core/src/components/card/usage/vue.md
core/src/utils/animation/animation-interface.ts
core/src/utils/transition/index.ts
docs/package.json

chore(): sync next with 5.6.11 changes

---

core/src/components/datetime/readme.md
core/src/components/datetime/usage/angular.md

https://github.com/ionic-team/ionic-framework/issues/23561#issuecomment-872509357
-
-
-

docs(datetime): add correct angular usage example in a modal

---

angular/src/directives/overlays/ion-modal.ts
angular/src/directives/overlays/ion-popover.ts

https://github.com/ionic-team/ionic-framework/issues/23561#issuecomment-872541649
-
-
-

fix(angular): modal and popover now have correct props defined on angular component

---

core/src/components/router-outlet/readme.md

https://github.com/ionic-team/ionic-framework/issues/23575#issuecomment-874754473
-
-
-

docs(router-outlet): add react note to docs

---

core/src/components/accordion-group/accordion-group.tsx
core/src/components/accordion/test/multiple/e2e.ts
core/src/components/accordion/test/multiple/index.html

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23550
- accordion group converts string to array of string prior to checking multiple values

fix(accordion): value can now be set as string when using multiple is true

---

core/src/components/datetime/datetime.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23545
- Ensure that browser rounding does not impact selecting elements in `elementFromPoint`

fix(datetime): selecting time now works correctly on firefox

---

core/stencil.config.ts

Framework v5 enabled support for certain shims for legacy browsers, but these legacy browsers are no longer supported in Framework v6 so the shims are not needed.
- Removed shims for css variables, safari 10, and shadow dom
- Apps should get a very minor perf bump since the JS checks for whether or not to load the shims are no longer present.
Note: dynamicImportShim is still required because we support Firefox 63+ in v6, but dynamic imports were not added until Firefox 67.
- [y] Yes
Note: This is technically a breaking change, but we have already noted this change in https://github.com/ionic-team/ionic-framework/blob/next/BREAKING.md#browser-and-platform-support so as long as …

perf(): remove shims for legacy browsers no longer supported in v6

---

core/src/components/accordion/readme.md
core/src/components/accordion/usage/angular.md
core/src/components/accordion/usage/javascript.md
core/src/components/accordion/usage/react.md
core/src/components/accordion/usage/stencil.md
core/src/components/accordion/usage/vue.md
core/src/components/datetime/readme.md
core/src/components/datetime/usage/angular.md

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23591
-
-
-

docs(accordion): add usage on how to get and set the state programmatically

---

packages/react/README.md

docs(react): install @ionic/cli instead of ionic

---

core/.stylelintrc.yml
core/src/components/content/content.scss
core/src/components/item-options/item-options.scss
core/src/components/item-sliding/item-sliding.scss
core/src/components/menu/menu.scss
core/src/components/progress-bar/progress-bar.scss
core/src/components/range/range.md.scss
core/src/components/range/range.scss
core/src/components/skeleton-text/skeleton-text.scss
core/src/components/virtual-scroll/virtual-scroll.scss

chore(): switch to using disallow terminology

---

.github/ISSUE_TEMPLATE/bug_report.yml

chore(): fix yaml typos

---

.github/ISSUE_TEMPLATE/bug_report.yml

chore(): use supported form keys

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/cli.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/support_question.yml

chore(): fix form template typos

---

angular/src/index.ts
core/src/components/action-sheet/readme.md
core/src/components/alert/readme.md
core/src/components/loading/readme.md
core/src/components/modal/readme.md
core/src/components/picker/readme.md
core/src/components/popover/readme.md
core/src/components/toast/readme.md
packages/react/src/components/index.ts
packages/vue/src/index.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/22790
- Interfaces used with overlay components are now exported by Angular, React, and Vue packages (previously only Core exported them)
- Updated the docs for each respective component to document the interfaces and the values to help increase awareness of the types.

fix(overlays): overlay interfaces are now exported from framework packages and documented

---

.github/ISSUE_TEMPLATE/cli.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/support_question.yml

chore(): remove cli, docs, and support templates in favor of directing visitors to correct place url

---

.github/ISSUE_TEMPLATE/config.yml

chore(): fix typo in config

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23647
-
-
-

chore(): add emojis to issue template titles

---

core/src/components/nav/test/nav-controller.spec.ts

Fixed typo.
```
begining -> beginning
```
-
-
-

chore(nav): fix typo in test comment

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

6.0.0-beta.2

---

packages/vue/src/components/IonRouterOutlet.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23675
- Check for existence of ion-page during transition and show warning if does not exist

fix(vue): improve accuracy of ion-page dev warning

---

packages/vue/src/components/IonRouterOutlet.ts

chore(): sync with main

---

angular/src/providers/platform.ts

fixes #23687
Issue Number: #23687
- method documentation updated

docs(platform): add capacitor to method docs

---

core/src/components/list/list.ios.vars.scss
core/src/components/list/test/inset/index.html

- Updates the ion-list inset border to match iOS 15

fix(list): change inset border radius to match iOS 15

---

packages/react/src/components/navigation/IonTabs.tsx
packages/react/src/utils/HTMLElementSSR.ts

Issue Number: resolves #23651 
- IonTabs now checks for SSR when using `window` and `HTMLElement` in React

fix(react): add SSR check to IonTabs

---

core/package-lock.json
core/package.json

chore(): bump ionicons version

---

core/src/components/popover/readme.md
core/src/components/popover/test/basic/e2e.ts
core/src/components/popover/utils.ts

Issue Number: resolves #23512 
- Keyboard navigation now works with arrow keys.
- `Home` and `End` key presses will also navigate to the first and last focusable item, respectively.

fix(popover): fix keyboard arrow navigation

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/providers/platform.ts
core/api.txt
core/package-lock.json
core/package.json
core/src/components/checkbox/checkbox-interface.ts
core/src/components/checkbox/readme.md
core/src/components/item-sliding/item-sliding.tsx
core/src/components/radio-group/radio-group-interface.ts
core/src/components/radio-group/readme.md
core/src/utils/gesture/pointer-events.ts
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/react/src/components/navigation/IonTabs.tsx
packages/react/src/utils/HTMLElementSSR.ts
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/src/components/IonTabs.ts

Release 5.6.13

---

packages/vue/src/components/Overlays.ts

chore(): run build for vue

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

6.0.0-beta.3

---

commitlint.config.js
package.json

- Adds an interactive commit message builder, Commitizen: https://commitizen-tools.github.io/commitizen/
- Adds Husky to override `git commit` with Commitizen

build(commit): add husky and commitizen

---

core/src/components/toast/readme.md
core/src/components/toast/toast-interface.ts

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23736
- Added `icon?: string;` to `ToastOptions` interface

fix(toast): ToastOptions interface now contains icon prop

---

core/src/components/back-button/back-button.scss
core/src/components/back-button/test/basic/index.html

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/23748
- Passed `--ripple-color` to `ion-ripple-effect` inside of `ion-back-button`.

fix(back-button): MD ripple now accounts for --ripple-color

---

CHANGELOG.md
angular/package-lock.json
commitlint.config.js
core/src/components/back-button/back-button.scss
core/src/components/back-button/test/basic/index.html
core/src/components/img/img.tsx
core/src/components/item-option/item-option.tsx
core/src/components/item-sliding/item-sliding.tsx
core/src/components/nav/nav.tsx
core/src/components/router-outlet/route-outlet.tsx
package.json
packages/angular-server/package-lock.json
packages/vue-router/__tests__/locationHistory.spec.ts
packages/vue-router/__tests__/viewStacks.spec.ts
packages/vue-router/src/locationHistory.ts
packages/vue-router/src/router.ts
packages/vue-router/src/types.ts
packages/vue-router/src/viewStacks.ts
packages/vue/package-lock.json
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/src/views/Inputs.vue
packages/vue/test-app/tests/e2e/specs/routing.js
packages/vue/test-app/tests/e2e/support/commands.js
packages/vue/test-app/tests/unit/routing.spec.ts

chore(): sync next with main for beta 4

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

6.0.0-beta.4

---

core/src/components/alert/alert-interface.ts
core/src/components/alert/readme.md

`cancel` and `destructive` roles have special meaning internally in `ion-alert`, but they were never documented as possible values
- `cancel` and `destructive` are now documented as possible values in the AlertButton interface.

fix(alert): AlertButton role now has correct types

---

core/src/components/item/item.md.scss
core/src/components/item/item.scss
core/src/components/item/item.tsx
core/src/components/item/test/form/e2e.ts
core/src/components/item/test/form/index.html

Issue Number: resolves #23733 #23850
- Form validation states are now properly configured for each fill mode

fix(item): form validation states are now properly shown

---

CHANGELOG.md
core/src/components/alert/alert-interface.ts
core/src/components/alert/readme.md
core/src/components/item/item.scss
core/src/components/item/test/alignment/index.html
core/src/components/picker/readme.md
core/src/components/picker/usage/vue.md
core/src/components/reorder-group/reorder-group.tsx
core/src/components/slides/test/image/index.html
packages/react/src/components/index.ts
packages/vue-router/src/viewStacks.ts
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/tests/unit/routing.spec.ts

chore(): sync with main for v6 beta 5 release

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

6.0.0-beta.5

---

core/src/components/modal/readme.md

docs(modal): breakpoints explanation is now correct

---

core/src/components/accordion/readme.md
core/src/components/accordion/usage/react.md

change references of ion-list to IonList
-
-
-

docs(accordion): update React usage

---

core/src/components/modal/modal-interface.ts
core/src/components/modal/readme.md

Issue Number: resolves #23866 
- Exposes breakpoint props in ModalOptions interface.

fix(modal): expose breakpoint props in ModalOptions interface

---

core/src/components/modal/modal.tsx
core/src/components/modal/test/sheet/e2e.ts
core/src/components/modal/test/sheet/index.html

Issue Number: part of #23878
- Improved conditional check to ensure handle can be disabled by developer

fix(modal): handle on sheet modal can now be turned off

---

angular/src/directives/overlays/modal.ts

Issue Number: part of https://github.com/ionic-team/ionic-framework/issues/23878
- Added `initialBreakpoint`, `breakpoints`, `backdropBreakpoint`, and 'handle' for the modal in Angular

fix(modal): add sheet modal properties for angular

---

.github/PROCESS.md

(skipped the above since it's just an update to PROCESS.md)
"Support Questions" in PROCESS.md directs users to a Slack channel that no longer exists.
Link to Slack channel removed.
N/A

docs(process): remove old Slack channel reference

---

packages/vue/src/components/Overlays.ts

chore(overlays): run build for vue

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

6.0.0-beta.6

---

core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/minmax/index.html

Issue Number: resolves #23939 
- Scroll listener for time only fires if it has a valid integer value

fix(datetime): ionChange is no longer called for out of range dates

---

core/src/components/title/readme.md
core/src/components/title/usage/angular.md
core/src/components/title/usage/javascript.md
core/src/components/title/usage/react.md
core/src/components/title/usage/stencil.md
core/src/components/title/usage/vue.md

Resolves https://github.com/ionic-team/ionic-docs/issues/1902
- Fixed typo in usage docs for ion-title, specifically a CSS example in all frameworks (`.large-title` changed to `.title-large`)

docs(title): fix typo in usage CSS example

---

core/src/components.d.ts
core/src/components/picker-column-internal/picker-column-internal-interfaces.ts
core/src/components/picker-column-internal/picker-column-internal.ios.scss
core/src/components/picker-column-internal/picker-column-internal.md.scss
core/src/components/picker-column-internal/picker-column-internal.scss
core/src/components/picker-column-internal/picker-column-internal.tsx
core/src/components/picker-column-internal/readme.md
core/src/components/picker-internal/picker-internal-interfaces.ts
core/src/components/picker-internal/picker-internal.ios.scss
core/src/components/picker-internal/picker-internal.md.scss
core/src/components/picker-internal/picker-internal.scss
core/src/components/picker-internal/picker-internal.tsx
core/src/components/picker-internal/readme.md
core/src/components/picker-internal/test/a11y/e2e.ts
core/src/components/picker-internal/test/a11y/index.html
core/src/components/picker-internal/test/basic/e2e.ts
core/src/components/picker-internal/test/basic/index.html

As part of the new datetime time picker changes, we need a way of selecting times via a wheel style picker. We have a wheel style picker for month/year selection, but rather than duplicate that code yet again, I would like to extract that logic to a separate component that will lay the groundwork for a future revamp of the `ion-picker` component.
The existing `ion-picker` component is buggy, has performance issues, and cannot be used inline so I did not want to use the existing picker component on our new `ion-datetime`.
I opted to make this component internal because a) it does not have the same feature set as the existing `ion-picker` and b) replacing `ion-picker` with this …

chore(): add base new picker component for datetime revisions

---

packages/react/package.json
packages/react/src/hooks/__tests__/hooks.spec.tsx
packages/react/src/hooks/useController.ts
packages/react/src/hooks/useIonActionSheet.ts
packages/react/src/hooks/useIonAlert.ts
packages/react/src/hooks/useIonLoading.tsx
packages/react/src/hooks/useIonModal.ts
packages/react/src/hooks/useIonPicker.tsx
packages/react/src/hooks/useIonPopover.ts
packages/react/src/hooks/useIonToast.ts
packages/react/src/hooks/useOverlay.ts

Issue Number: #23741
All hooks are corretly memorised now. 
This should not introduce a breaking change. One could argue that some applications might relay on the previous behaviour. I am not able to properly judge this.

fix(hooks): memorise hook results

---

.github/ISSUE_TEMPLATE/bug_report.yml

chore(): fix typo in bug template

---

.github/ISSUE_TEMPLATE/feature_request.yml

chore(): fix typo in feature request template

---

.github/workflows/actions/build-angular/action.yml
.github/workflows/actions/build-core/action.yml
.github/workflows/actions/build-react-router/action.yml
.github/workflows/actions/build-react/action.yml
.github/workflows/actions/build-vue-router/action.yml
.github/workflows/actions/build-vue/action.yml
.github/workflows/actions/test-angular-e2e/action.yml
.github/workflows/actions/test-core-e2e/action.yml
.github/workflows/actions/test-core-lint/action.yml
.github/workflows/actions/test-core-screenshot-main/action.yml
.github/workflows/actions/test-core-screenshot/action.yml
.github/workflows/actions/test-core-spec/action.yml
.github/workflows/actions/test-react-e2e/action.yml
.github/workflows/actions/test-react-router-e2e/action.yml
.github/workflows/actions/test-vue-e2e/action.yml

- Incrementing version number will invalidate cache due to new cache key

test(): add way of manually busting node module cache

---

core/src/components/infinite-scroll/readme.md
core/src/components/infinite-scroll/usage/react.md

docs(react): fix infinite scroll example to remove extra imports

---

.github/CONTRIBUTING.md

docs(): update table of contents for contributing guide

---

core/package-lock.json
core/package.json
packages/react/package.json
packages/vue/package-lock.json
packages/vue/package.json

chore(): update ionicons and stencil

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

Release 6.0.0-rc.2

---

BREAKING.md

docs(angular): fix breaking change version typo

---

.github/ionic-issue-bot.yml

Ionitron's auto response for `ionitron: support` includes a link to a Slack channel we don't use anymore.
- Link to Slack channel removed.

chore(ionitron): remove reference to old Slack channel

---

.github/workflows/dev-build.yml
.scripts/release-dev.js

Creating dev builds is a manual process and requires every team member to have write access to the NPM organization for Ionic.
- Creates a GitHub Actions dispatch workflow that allows and authorized Ionic team member to create a dev build for their preferred branch without having to create a dev build locally or have write access to the NPM organization.

build(dev-build): add GitHub actions for dev builds

---

.github/workflows/dev-build.yml
.scripts/common.js
.scripts/release-dev.js

build(dev-build): correctly pass secrets to publish task

---

core/src/components/modal/modal.ios.scss
core/src/components/modal/test/card/e2e.ts
core/src/components/modal/test/card/index.html
core/src/components/modal/test/spec/index.html
core/src/css/core.scss

Two issues here:
1. Border radius cannot be overridden with card or sheet modals. This was due to our usage of hard coding the border radius on the modal wrapper inside of the Shadow DOM.
2. Incorrect global styles was applying border radius to every single modal. These styles are only needed to work around a WebKit issue with the card modal on iPad-size displays.
- Border radius can now be overridden using the CSS Variable.
- Made the global modal style specific to card modals.

fix(modal): border radius is now correctly applied to card modals

---

packages/vue/test-app/tests/e2e/specs/routing.js
packages/vue/test-app/tests/e2e/specs/tabs.js

The Vue integration test around tabs/swipe gestures is brittle with Cypress gesture system. 
Skipping the test for tabs swipe gestures and route swipe gestures at this time.

test(tabs): skip tests for vue tabs

---

.github/COMPONENT-GUIDE.md
.github/CONTRIBUTING.md
.github/PROCESS.md
.scripts/release.js
README.md
angular/BREAKING.md
angular/README.md
core/stencil.config.ts
docs/README.md
packages/react/README.md
packages/vue-router/README.md
packages/vue/CHANGELOG.md
packages/vue/README.md

Updates process documentation, links and a script to reference the `main` branch instead of `master.

docs(): update docs usage to reference main instead of master

---

core/src/css/core.scss

Date inputs on Safari 15 are center aligning text contents. This is due to a change in the appearance of `input[type="date"]` in Safari, that isn't aligned with the previous design considerations of `ion-input`. 
Issue Number: #24197
Text alignment of `input[type="date"]` pseudo element aligns left on LTR and right on RTL; only when used inside of `ion-input`.
Duplicate of #24213 (fixing on main / Ionic 5.*).

fix(input): date type in ion-input now aligns correctly on iOS 15

---

core/scripts/screenshot/ionic.js
core/src/components/item/item.md.scss
core/src/components/textarea/test/autogrow/e2e.ts
core/src/components/textarea/test/autogrow/index.html

Both inputs and textareas that are slotted through an `ion-item` using `fill="outline"` and an `ion-label` with `position="floating"` are always translated upwards by 25% of the element's height. With a textarea using auto grow, the contents of the textarea will translate outside of the container.
Issue Number: #24187
Within MD regardless of input or textarea, the control container will translate upwards of 14px, to offset the animation distance of the floating label. This allows auto grow textarea to display consistently.
Split PR #24196 to focus on the overflow issue.

fix(textarea): floating label with autogrow textareas

---

.github/COMPONENT-GUIDE.md
.github/CONTRIBUTING.md
.github/PROCESS.md
.github/workflows/actions/build-react-router/action.yml
.scripts/common.js
.scripts/release.js
CHANGELOG.md
README.md
angular/BREAKING.md
angular/README.md
angular/package-lock.json
core/package-lock.json
core/stencil.config.ts
docs/README.md
packages/angular-server/package-lock.json
packages/react-router/package.json
packages/react/README.md
packages/vue-router/README.md
packages/vue/CHANGELOG.md
packages/vue/README.md

chore(): sync with main for RC 3

---

.github/workflows/dev-build.yml
.scripts/common.js
.scripts/release-dev.js

Dev + prod scripts are intertwined so something broke along the way. Reverting changes so we can get a working prod build out the door.
-
-
-

chore(): revert dev build changes

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

6.0.0-rc.3

---

angular/src/directives/control-value-accessors/value-accessor.ts
angular/src/directives/navigation/stack-controller.ts

Make use of const assertion and more narrow types to solve build errors when compiling Angular in legacy View Engine mode with strict types.

fix(angular): strict type usage

---

.github/workflows/actions/test-vue-e2e/action.yml

'Run e2e ests' -> 'Run e2e Tests'

chore(ci): fix typo for test-vue-e2e step

---

packages/vue/test-app/package-lock.json
packages/vue/test-app/package.json

- Updating vue test app with latest packages. Required to test https://github.com/ionic-team/ionic-framework/pull/24253

chore(): update vue test app

---

core/src/components/popover/readme.md
core/src/components/popover/usage/angular.md
core/src/components/popover/usage/javascript.md
core/src/components/popover/usage/react.md
core/src/components/popover/usage/stencil.md
core/src/components/popover/usage/vue.md

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24266
- Added new popover examples

docs(popover): add popover examples

---

core/src/components/modal/readme.md
core/src/components/modal/usage/angular.md
core/src/components/modal/usage/javascript.md
core/src/components/modal/usage/react.md
core/src/components/modal/usage/stencil.md
core/src/components/modal/usage/vue.md

No issue link, just noticed missing examples while browsing the Ionic 6 docs.
- Added usage examples for inline modals
- Updated styling docs since modal no longer uses scoped components

docs(modal): add inline modal docs

---

packages/react/src/hooks/useIonActionSheet.ts
packages/react/src/hooks/useIonAlert.ts
packages/react/src/hooks/useIonLoading.tsx
packages/react/src/hooks/useIonPicker.tsx
packages/react/src/hooks/useIonToast.ts

All Ionic hooks that use `useController` did not return the promise for the present/dismiss functions. This created inconsistencies in the type signatures when using the hooks and prevented implementations from fully waiting for the present to finish, before dismissing. 
Issue Number: #24293
All implementations making use of `useController` are updated to return the promise instance. All types are updated to reflect that the hooks return a `Promise<void>`.
This allows implementations to correctly wait for present to finish:
```ts
const [showIonLoading, dismissIonLoading] = useIonLoading();
const handleClick = async () => {
await showIonLoading('Loading');
dismissIonLoading(); …
```

fix(react): present and dismiss hooks return promises

---

core/src/components/popover/readme.md

Docs duplicate word typing
Deletes double 'the' typing
-
-
-

docs(): deletes double 'the' typing

---

CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

6.0.0-rc.4

---

packages/vue/src/components/IonTabBar.ts
packages/vue/test-app/tests/e2e/specs/tabs.js

Issue Number: resolves #24353
- Account for falsey query params

fix(vue): improve query params handling in tabs

---

.github/CODEOWNERS

Introduces CODEOWNERS to automatically apply the Framework dev team as the reviewer on new PRs when dependencies are modified or any changes to routing/routing integrations occurs.

chore(tech-debt): codeowners rules

---

.github/CODEOWNERS

Any changes will require the Framework Core team to review.

chore(CODEOWNERS): global owners for framework team

---

README.md

Incorrectly assumed the URL path for the logo.
Fixes the asset path for the logo in the README.

chore(README): logo url asset path

---

README.md

Updates the README logo asset path and migration guide path.

chore(README): update links from next to main

---

angular/src/directives/proxies.ts
core/api.txt
core/src/components.d.ts
core/src/components/select/readme.md
core/src/components/select/select.tsx
core/src/components/select/test/basic/e2e.ts
packages/vue/src/proxies.ts

Issue Number: https://github.com/ionic-team/ionic-framework/issues/24088
- New Event ionDismiss is emitted when the created overlay is dismissed
This is identical to https://github.com/ionic-team/ionic-framework/pull/24099, except merged to the new feature branch.

feat(select): add event for when overlay is dismissed

---

.scripts/common.js
CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
core/src/components/content/content.tsx
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/src/components/IonTabBar.ts
packages/vue/test-app/tests/e2e/specs/tabs.js

Release 5.9.3

---

.scripts/common.js
CHANGELOG.md
angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
docs/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

Release 6.0.1

---

core/package-lock.json
core/package.json

chore(): update to stencil 2.12.0

---

core/src/components/datetime/readme.md

Feedback from https://github.com/ionic-team/ionic-framework/issues/24396
- Added an example on how to manipulate dates with time zones in an app

docs(datetime): add examples on formatting for time zones

---

.github/ionic-issue-bot.yml

Starting holiday triage mode. Ionitron will automatically apply the "holiday triage" label and post a comment on every new issue until this mode is disabled.

chore(): start holiday triage 2021

---

core/src/utils/overlays.ts

Nested custom elements used in overlays are not being defined.
Issue Number: Resolves #24393
Adds missing custom element definitions for the overlay controllers.
Reporter verified this fixes their issue here: https://github.com/ionic-team/ionic-framework/issues/24393#issuecomment-995439076
Continuation of the work effort started here: #24372

fix(overlays): define custom element children

---

core/src/components/modal/modal.tsx

Some ugly rendering of the slots table of the `ion-modal` component.
- StencilJs should render the slot table correctly

docs(modal): fix styling issues in the slot table

---

core/src/components/modal/readme.md

Runs the build output for #24468 to have the generated docs in sync.

chore(): build modal docs formatting

---

packages/vue-router/package-lock.json
packages/vue-router/package.json

Vue Router is hardset to v6 dependency of `@ionic/vue`.
Issue Number: #24467
Updates Vue Router to reference the latest published version of `@ionic/vue`.

chore(vue-router): update @ionic/vue dependencies to v6 latest

---

core/src/components/refresher-content/refresher-content.tsx

Issue Number: resolves #24480
The asset path for Ionicons is not set when using custom elements build. As a result, we cannot lazy load icons internally. We should be using the icon SVG data anyways as it results in additional maintenance overhead (I.e. https://github.com/ionic-team/ionic-framework/blob/main/packages/vue/src/index.ts#L154-L169);
- All ion-icons used internally in refresher-content are now imported rather than referenced by name.
- Note: "lines" is a spinner not an ion-icon, and the spinner SVG data is defined inside of Ionic (not ionicons) so we can leave that as is: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/spinner/spinner-conf …

fix(refresher): import icons to avoid errors in react and vue

---

.github/ionic-issue-bot.yml

This reverts commit 87c51c4a825b647b12d8039784a25492f0da6240.
-
-
-

chore(): end holiday triage 2021

---

.github/workflows/dev-build.yml

Currently, dependencies of Ionic Core for dev builds look like this: 
```json
"@ionic/core": "^6.0.1-dev.1641929112.5a14356"
```
This is causing NPM to install 6.0.1 instead, meaning `@ionic/angular@6.0.1-dev.1641929112.5a14356` has `@ionic/core@6.0.1` instead of `@ionic/core@6.0.1-dev.1641929112.5a14356`.
This is a problem if the code change you want to test is in Ionic Core as the changed version will not get installed.
- For dev builds only, the dependency for Ionic Core will install the exact version:
```json
"@ionic/core": "6.0.1-dev.1641929112.5a14356"
```

chore(dev-build): use exact versioning so npm installs correct Ionic Core

---

core/src/components/menu/menu.tsx

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24563
The main attribute was removed in Ionic 5 but did not actually get removed in Ionic 5 despite being noted in the breaking changes: https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#menu
-  Removed the menu attribute support for real this time. 
- I also updated some of the checks below since the linter pointed out that they were not allowed.

fix(menu): remove main attribute that was supposed to removed in v5

---

core/src/utils/test/overlays/overlays.e2e.ts

Querying elements within a modal or on the main page is flaky.
Wait for the modal events to fire prior to querying the elements. This solves the flaky queries from happening.

test(overlays): wait for modal events to fire

---

core/src/components/menu-toggle/menu-toggle.tsx
core/src/components/menu-toggle/readme.md
core/src/components/menu-toggle/usage/angular.md
core/src/components/menu-toggle/usage/javascript.md
core/src/components/menu-toggle/usage/react.md
core/src/components/menu-toggle/usage/vue.md

Menu toggle documentation is missing slot documentation and usage examples.
Issue Number: https://github.com/ionic-team/ionic-docs/issues/2136
- Adds slot documentation
- Adds usage examples

docs(menu-toggle): add usage examples and slot docs

---

core/src/components/datetime/readme.md

> This is a docs-only change, so most of the above is N/A.
N/A
N/A

docs(datetime): fix typo in overview

---

packages/angular-server/package-lock.json
packages/angular-server/package.json

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24592
- Used ^ to indicate latest minor version

fix(angular-server): use correct @ionic/angular dependency version

---

package-lock.json
package.json

Development of Ionic requires node 15+. This is documented internally, but we need to update the package.json so external contributors are aware of this requirement.
- Bump engines field to use node 15+

chore(package): bump supported node version to 15+

---

core/src/components/range/range.tsx
core/src/components/range/test/rtl/e2e.ts
core/src/components/range/test/rtl/index.html

`ion-range` only supports RTL when the direction is set at the document level.
Issue Number: #20201, Tech Debt
- `ion-range` will respect `dir` specified on the host element (overrides the document value)
- `ion-range` uses the `isRTL` utility

fix(range): setting dir on ion-range to enable rtl mode now supported

---

core/src/components/segment/segment.tsx
core/src/components/segment/test/rtl/e2e.ts
core/src/components/segment/test/rtl/index.html

`ion-segment` only supports RTL when the direction is set at the document level.
Issue Number: Resolves #23978, Tech debt
- `ion-segment` will respect dir specified on the host element (overrides the document value)
- `ion-segment` uses the isRTL utility

fix(segment): setting dir on ion-segment to enable rtl mode now supported

---

core/src/components/searchbar/searchbar.tsx
core/src/components/searchbar/test/rtl/e2e.ts
core/src/components/searchbar/test/rtl/index.html

`ion-searchbar` only supports RTL when the direction is set at the document level.
Issue Number: Tech Debt
- `ion-searchbar` will respect dir specified on the host element (overrides the document value)
- `ion-searchbar` uses the isRTL utility

fix(searchbar): setting dir on ion-searchbar to enable rtl mode now supported

---

core/src/components/modal/modal.tsx
core/src/components/picker-internal/picker-internal.tsx
core/src/components/radio/radio.tsx
core/src/components/range/range.tsx
core/src/components/toggle/toggle.tsx

There are a few instances of shadowed variables reported by the linter in several different components.
- Variables renamed to avoid shadowing.
- For `picker-internal`, `minuteValue` declaration moved to the top of the switch statement.

style(): fix shadowed vars

---

core/src/components/accordion/test/standalone/e2e.ts
core/src/components/accordion/test/standalone/index.html
core/src/css/core.scss

Issue Number: resolves https://github.com/ionic-team/ionic-framework/issues/24613
- Removing the line in core.scss now only targets items that are specifically slotted into the header

fix(accordion): items inside of the content now correct display borders

---

core/src/components/menu-toggle/readme.md

- Runs the build command to update the autogenerated output of the menu toggle documentation

chore(menu-toggle): autogenerated readme contents

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/PULL_REQUEST_TEMPLATE.md

Introduces "Requirements" section to our contributing guide for community pull requests. We ❤️  community contributions, but want to make sure they have the proper details up front, before a community member invests their time. 
- Makes `ionic info` section required in the issue template
- Explicitly notes that issues are required for features/bug fixes in the PR template
- Updates Slack link to Discord

docs(contributing): update requirements for contributing

---

core/src/components/popover/popover-interface.ts
core/src/components/popover/readme.md

The types for `PopoverOptions` specify using `align` to set the `alignment` prop on `ion-popover` when using the popover controller. This does not actually occur. 
Issue Number: #24709
Updates the `PopoverOptions` to match the `ion-popover` prop name. This means the type will recommend using `alignment` and no longer error on the developer.
https://github.com/ionic-team/ionic-framework/blob/2a27befe463832b9ca7709ba22421abbdaa4cfa4/core/src/components/popover/popover.tsx#L193
Note: The type was incorrect, so developers could be referencing the incorrect type that does no functional behavior.

fix(popover): use alignment with popover options

---

core/src/components.d.ts
core/src/components/router/readme.md
core/src/components/router/router.tsx
core/src/components/router/test/basic/index.html
core/src/components/router/test/basic/router-push.e2e.ts

Router.push() is buggy when using a relative path and `useHash` = true or `root` != /
Issue Number: fixes #24718 
Router.push works with relative paths

fix(router): fix router push with relative path

---

core/src/components.d.ts
core/src/components/nav/nav-interface.ts
core/src/components/nav/nav.tsx

This PR do not change the behavior.
It tries to make the code of `<ion-nav>` easier to understand by:
- simplifying some code,
- adding some comments,
- there is also a bit of renaming and formatting (for consistency).

chore(nav): code cleanup

---

packages/vue/src/components/IonPage.ts
packages/vue/test-app/tests/unit/page.spec.ts

Give co-author credit from #24773 when this merges
Issue Number: #24772
- Custom classes are now preserved on IonPage component

fix(vue): preserve custom classes on IonPage

---

.github/workflows/actions/test-react-e2e/action.yml
.github/workflows/actions/test-react-router-e2e/action.yml
angular/test/test-app/package.json
core/src/components/select/select.tsx
packages/react-router/test-app/package-lock.json
packages/react-router/test-app/package.json
packages/react/test-app/package-lock.json
packages/react/test-app/package.json
packages/react/test-app/src/App.tsx
packages/vue/test-app/package.json

Issues such as https://github.com/ionic-team/ionic-framework/issues/24807 currently cannot be caught because none of our E2E tests run in production mode.
- E2E tests on CI are now run in production mode

test(): run e2e tests in production mode

---

core/src/components/datetime/readme.md

docs(datetime): ISO Format examples fix

---

core/src/components/datetime/test/data.spec.ts

N/A
Adds unit tests for the `getToday()` util for datetime's implementation.

test(datetime): getToday unit test

---

core/src/components/datetime/test/zoom/e2e.ts

Removes the last usage of `waitForTimeout` for tests relying on the modal to be presented. Uses the modal event directly.

test(datetime): listen for modal event in zoom out test

---

angular/src/directives/overlays/modal.ts
angular/test/test-app/e2e/src/modal.spec.ts
angular/test/test-app/src/app/modal-inline/modal-inline.component.html

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24809
- Angular component now unmounted .ion-page when the modal is not open

fix(modal): .ion-page element is now correctly added

---

core/src/components/modal/gestures/sheet.ts
core/src/components/modal/readme.md
core/src/components/modal/test/sheet/e2e.ts
core/src/components/modal/test/sheet/index.html
core/src/components/modal/test/test.utils.ts
core/src/utils/overlays.ts
core/src/utils/test/utils.ts
core/stencil.config.ts
core/tsconfig.json

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24581
- Focus trapping is now disabled when the backdrop is disabled according to `backdropBreakpoint`
- Due to `aria-modal="true"`, assistive technologies will not automatically focus outside of the modal. This is aligned with how native sheets behave.
- I also added a path alias so we can easily access test utils so we don't need to keep doing `../../../../`. I have another PR that will update the remaining tests to use this new import syntax.

fix(modal): sheet modal now allows input focusing when backdrop disabled

---

core/src/components/virtual-scroll/readme.md

Documentation links to the following pages:
https://ionicframework.com/angular/virtual-scroll
https://ionicframework.com/react/virtual-scroll
https://ionicframework.com/vue/virtual-scroll
Documentation links to the following pages:
https://ionicframework.com/docs/angular/virtual-scroll
https://ionicframework.com/docs/react/virtual-scroll
https://ionicframework.com/docs/vue/virtual-scroll
Docusaurus is able to intelligently handle inconsistencies due to the presence or lack of a trailing slash if the link references the corresponding Markdown file (i.e. `../angular/virtual-scroll.md` rather than `../angular/virtual-scroll`).

docs(virtual-scroll): fix links to guides

---

.github/workflows/update-screeshots.yml

Working on finishing up the Playwright flow inhttps://github.com/ionic-team/ionic-framework/pull/24871
I need to test the GH Action where devs can update the reference screenshots whenever they make intentional changes. In order to do that, I need to merge a stubbed version of the action into `main`. By default the workflows in https://github.com/ionic-team/ionic-framework/actions are only picked up from the default branch.  (See https://github.community/t/workflow-files-only-picked-up-from-master/16129)
- Adds a stubbed GH Action for updating test screenshots

test(): add stubbed update screenshot action

---

core/src/components/action-sheet/readme.md
core/src/components/alert/readme.md
core/src/components/popover/readme.md
core/src/components/select/readme.md

As part of https://github.com/ionic-team/ionic-framework/pull/24810, stencil now detects component dependencies inside of `ion-select`. This means that the dependency graph should be updated. I forgot to run `npm run build`, causing the readme files to not get updated.
- The readme files have been updated with the updated dependencies

chore(): run build to update readme files

---

core/src/components/content/content.scss
core/src/components/content/content.tsx
core/src/utils/gesture/swipe-back.ts
core/src/utils/gesture/test/e2e.ts
core/src/utils/gesture/test/index.html
core/src/utils/test/utils.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/19488
- Swipe to go back gesture now accounts for RTL swiping directions
- Transition shadow now displays correctly in RTL mode
| before | after |
| ------- | ----- |
| <video src="https://user-images.githubusercontent.com/2721089/156410532-b39ed5ab-2fb5-472f-b2a8-260a80826bf8.mov"></video> | <video src="https://user-images.githubusercontent.com/2721089/156410564-948938b3-5368-47bc-b282-246bfde14d79.mov"></video> |

fix(ios): swipe to go back now works in rtl mode

---

core/src/components/button/readme.md

docs(button): fix fill attribute typo

---

core/package-lock.json
core/package.json

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24280
- Updates Ionic Core to Stencil 2.14.1 that includes a treeshaking fix
- I also changed this to include the latest minor version of Stencil rather than the latest patch. Previously was latest patch due to an issue with an older version of Stencil, but we are well past that so it seem safe to go to the latest minor version again.

fix(all): improve treeshaking functionality

---

packages/vue/test-app/tests/unit/routing.spec.ts

Integration tests for Vue routing will error/fail.
Issue URL: 
Tests will pass (fixed missing `,` for arrays)

test(vue): formatting error in test

---

core/src/components/infinite-scroll/test/basic/e2e.ts
core/src/components/infinite-scroll/test/basic/index.html
core/src/utils/test/utils.ts

There are no integration tests that validate infinite scroll fires correctly.
Tests have been added to cover that infinite scroll correctly fires events to load more items (once scrolling to the bottom).

test(infinite-scroll): scroll threshold

---

core/src/components/footer/test/fade/e2e.ts
core/src/utils/test/utils.ts

- Fade test is ran on iOS and Android, even though it is only implemented for iOS
- Screenshot doesn't scroll the container, so the screenshot never captures the fade effect
- Test only for iOS (fade effect only exists on iOS mode)
- Test will capture screenshot initially and after scroll

test(footer): fade e2e test

---

core/src/components/refresher/test/basic/e2e.ts
core/src/components/refresher/test/basic/index.html
core/src/components/refresher/test/test.utils.ts
core/src/utils/test/utils.ts

There are no tests for validating that pull-to-refresh completes successfully (after a successful pull and release).
Added missing tests to validate pull to refresh fires and completes.

test(refresher): pull to refresh test

---

core/src/components/footer/readme.md

N/A
Documents the usage pattern for using the `ion-footer` fade with the `.ion-content-scroll-host` class selector.

docs(footer): usage with virtual scroll

---

core/src/components/header/readme.md

N/A
Documents the usage pattern for using the `ion-header` fade/collapsible large titles with the `.ion-content-scroll-host` class selector.

docs(header): usage with virtual scroll

---

core/src/components/infinite-scroll/readme.md

N/A
Documents the usage pattern for using `ion-infinite-scroll` with the `.ion-content-scroll-host` class selector.

docs(infinite-scroll): usage with virtual scroll

---

core/src/components/reorder-group/readme.md

N/A
Documents the usage pattern for using the `ion-reorder-group` with the `.ion-content-scroll-host` class selector.

docs(reorder-group): usage with virtual scroll

---

core/src/components/refresher/readme.md

N/A
Documents the usage pattern for using `ion-refresher` with the `.ion-content-scroll-host` class selector.
Note: The heading is slightly different than the other virtual scroll examples, to match the writing style of this specific docs page.

docs(refresher): usage with virtual scroll

---

core/package-lock.json
core/package.json

chore() bump stencil to 2.14.2

---

core/src/components/popover/popover.scss
core/src/components/popover/test/nested/e2e.ts
core/src/components/popover/test/nested/index.html

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24954
We only render a backdrop element on the root/parent popover so we can easily dismiss multiple levels of nested popovers.
However, the nested popover container was receiving pointer events, so users could never click/hover over root backdrop to dismiss nested popovers.
- Nested popovers no longer have pointers events on the container. Pointer events still remain on the content.

fix(popover): dismissing nested popover via backdrop now works

---

core/src/components.d.ts
core/src/components/slides/readme.md
core/src/components/slides/slides.tsx
core/src/components/slides/usage/angular.md
core/src/components/slides/usage/javascript.md
core/src/components/slides/usage/react.md
core/src/components/slides/usage/stencil.md
core/src/components/slides/usage/vue.md

Swiper API references point to a 404.
Updates the link to the point to the current swiper API documentation.
Closing #24908 in favor of this PR, as I did not receive a response.

docs(swiper): update swiper api link

---

packages/react/src/routing/OutletPageManager.tsx

An import from `@ionic/core` in the react package caused Ionic to be bundled twice (once with `@ionic/core` and once with `@ionic/core/components`). This created two instances of controllers, specifically the menu controller. This prevented developers from being able to control the correct instance of the menu controller from react.
Issue URL: #24497
- `@ionic/core` isn't bundled twice
- Menu controller has a single instance for the react package
- Developers can control menus with the menu controller in react
I will get a dev build to have others confirm, but I have locally validated against the reproduction app (Toggle Second Menu button).

fix(react): treeshake ionic/core bundle

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
core/src/components.d.ts
core/src/components/item-sliding/item-sliding.tsx
core/src/components/picker-column-internal/test/basic/e2e.ts
core/src/components/select/select.tsx
docs/CHANGELOG.md
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/react/src/routing/OutletPageManager.tsx
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.0.14

---

core/.prettierignore
core/package-lock.json
core/package.json

This PR installed prettier to run on core (except for the swiper bundle). It configured to use shared rules defined in https://github.com/ionic-team/prettier-config/.

chore(prettier): install prettier

---

core/tsconfig.json

There are several typescript errors that show up with the recent enabling of type checking in test files. We decided to turn off typechecking for the old Stencil test files. Typechecking remains enabled for the new Playwright test files. These files will be typechecked as they are migrated to Playwright.

chore(): exclude stencil tests from type checking

---

core/scripts/testing/scripts.js
core/src/utils/test/playwright.ts

test(playwright): test new method of waiting

---

.github/workflows/build.yml

This was causing builds to not run on PRs due to this error. Typically GH Actions will inform you of errors, but this time it did not.

chore(ci): fix workflow for build

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/directives/navigation/router-link-delegate.ts
angular/src/index.ts
angular/src/ionic-module.ts
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.0.16

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
core/playwright.config.ts
core/src/utils/test/playwright/eventSpy.ts
core/src/utils/test/playwright/fixtures.ts
core/src/utils/test/playwright/index.ts
docs/CHANGELOG.md
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

chore(): sync feature-6.1 with main for playwright utilities

---

core/src/components/reorder-group/readme.md

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25060
- Improve docs to clarify how to correctly use the complete method.

docs(reorder): improve docs on how to use complete method

---

core/src/components/accordion-group/accordion-group.tsx
core/src/components/accordion/test/a11y/e2e.ts
core/src/components/accordion/test/a11y/index.html
core/src/components/menu/menu.tsx
core/src/components/menu/test/basic/e2e.ts
core/src/components/menu/test/basic/index.html
core/src/components/menu/test/focus-trap/e2e.ts
core/src/components/menu/test/focus-trap/index.html
core/src/components/reorder-group/readme.md
packages/vue-router/src/router.ts
packages/vue/test-app/tests/e2e/specs/tabs.js

chore(): sync feature-6.1 with main

---

core/src/components/datetime/datetime.tsx

Components that use our custom import paths create exceptions when imported into another Stencil project.
Issue URL: #25101
Temporarily reverts back to relative paths to resolve the exceptions.
Dev build: `6.0.17-dev.11649725371.11cd4764` ✅

fix(datetime): import from relative path

---

core/src/components/datetime/datetime.tsx
core/src/components/item/item.tsx
core/src/components/modal/modal.tsx

The custom import alias path will break Stencil projects importing Ionic.
Issue URL: 
Updates 6.1.0 features to use the relative import paths in the interim to discovering the root cause.

chore(datetime,item,modal): use relative import paths

---

CHANGELOG.md

chore(): add correct changelog

---

.github/workflows/nightly.yml

I mistyped the cron schedule. Currently it will do a build on days 1 and 5 of the week (Monday and Friday)
- Now the build happens Monday **through** Friday

ci(nightly): use correct cron syntax

---

.github/workflows/build.yml

Each new commit on a PR can cause >20 test runners to be consumed at a time. The more commits you push in rapid succession, the more test runners are used. Pushing 3 commits one after the other can cause >60 test runners to be consumed. However, pushing commit n+1 means that the results from commit n are no longer valuable. This results in wasted test runners.
Adding this concurrency rule will automatically abort tests runs for commit n when commit n+1 is pushed. We group by ref so cancelling should only be scoped to the PR.

ci(github): add concurrency restrictions

---

core/playwright.config.ts

Running Playwright tests while developing is useful for quickly verifying changes. Unfortunately, running the tests currently tries to start a new dev server on `3333` when one is already running.
- This PR allows playwright to reuse the existing dev server when running locally only. There are no changes to the setup for running on CI.
Note: Be aware that this may cause screenshot tests to fail if the Stencil server is actively hot reloading (the progress bar at the top of the screen will show up). It is still recommended to verify screenshot tests on CI. To avoid this, wait for hot reloading to finish before starting the tests.

test(config): reuse existing dev server for local playwright tests

---

core/src/components/back-button/back-button.tsx
core/src/components/button/button.tsx
core/src/components/header/header.tsx
core/src/components/input/input.tsx
core/src/components/menu-button/menu-button.tsx
core/src/components/menu/menu.tsx
core/src/components/range/range.tsx
core/src/components/textarea/textarea.tsx
core/src/utils/helpers.ts
core/src/utils/test/attributes.spec.ts

Most ARIA attributes are not reflected to the light DOM. 
Issue URL: Enterprise
Back ports the solution for #25156 to 5.9.x.

fix(core): inherit aria attributes on host elements (#25156)

---

core/src/components/modal/gestures/swipe-to-close.ts
core/src/components/modal/test/card-refresher/index.html
core/src/components/modal/test/card-refresher/modal.e2e.ts

No issue link, but I discovered this issue when Venmoing someone last night 😂 . I had a native card modal open that used a refresher. The refresher always took priority over the swipe to dismiss gesture when swiping on the content.
- Swiping to dismiss from the content no longer happens if a refresher is present.
- You can also implement this fix by changing the `gesturePriority` of the modal gesture. However, I opted not to do that for a few reasons:
1. The refresher component has 3 different gestures in it (iOS native, MD native, and legacy). If any of those change, this will break.
2. I was not able to easily evaluate what effect this priority change will have on the swipe …

fix(modal): card modal no longer dismisses from content with refresher

---

.github/workflows/actions/build-vue/action.yml
.github/workflows/release.yml
CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.1.4

---

core/package-lock.json
core/package.json

The `@axe-core/playwright` dependency was mistakenly added as a `dependency` of `@ionic/core`. This would cause CI environments to fail, when trying to load the playwright binaries.
Issue URL: #25242
- `@axe-core/playwright` is a `devDependency`

fix(core): `@axe-core/playwright` should be a devDependency

---

core/src/components/picker-internal/test/basic/picker-internal.e2e.ts

The current skip criteria does not seem to be correct as it is still running on other PRs: https://github.com/ionic-team/ionic-framework/runs/6359480521?check_suite_focus=true
- I changed the criteria to just skip WebKit in general until we can resolve this issue.

test(picker-internal): skip overlay test on webkit

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.1.5

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

We've moved all manually-written documentation to the `ionic-docs` repo. The contributing guide and PR template are now outdated and unclear respectively when it comes to where and how to update the docs.
Issue URL: N/A
Process clarified.

chore(templates): clarify process for updating docs

---

core/api.txt
core/src/interface.d.ts

Props that have a type of `Colors`, do not auto-complete with the list of available options. Instead they are replaced with a type of `string`.
Issue URL: N/A (internal)
- Modified `Colors` type to maintain the list of custom options along with a string literal
Example of the toast controller with this change: 
Related to: #22151
Dev-build: `6.1.7-dev.11653446971.11d80e4c`

fix(types): improve intellisense with colors

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.1.7

---

core/src/components/refresher/test/test.utils.ts
core/src/utils/test/playwright/drag-element.ts

N/A
- Splits out the behavior for dragging an element on the Y-axis over a loop, into a separate util that other tests can take advantage of (mainly gesture related tests).

chore(playwright): dragElementByYAxis util

---

core/package-lock.json
core/package.json
packages/react/package-lock.json
packages/react/package.json
packages/vue/package-lock.json
packages/vue/package.json

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/23823
- Updates Stencil and Ionicons

fix(all): improve compatibility with vite

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
core/src/components.d.ts
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.1.8

---

.github/CONTRIBUTING.md

Issue URL: N/A
Adds notes about our internal design process for feature PRs.

chore(contributing): add process notes for feature PRs

---

angular/src/directives/proxies.ts
core/api.txt
core/src/components.d.ts
core/src/components/datetime/datetime.tsx
packages/vue/src/proxies.ts

Issue URL: Part of https://github.com/ionic-team/ionic-framework/issues/23981
- Adds API for controlling wheel preference with dateetime

feat(datetime): add preferWheel property

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.1.9

---

packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue-router/test/jest.preprocessor.js
packages/vue/package-lock.json
packages/vue/package.json

Packages are build using outdated versions of Vue + Vue Router
- Build using latest versions of Vue + Vue Router
- Update testing infrastructure

chore(vue, vue-router): update dev dependencies

---

angular/src/directives/navigation/ion-router-outlet.ts

Issue URL: N/A
Updates the documentation surrounding the class-level `ComponentFactoryResolver` and that it is required for Angular 12.

chore(angular): document class-level resolver required for angular 12

---

package-lock.json
package.json

According to https://github.com/lerna/lerna/releases/tag/v5.0.0, we should be fine to upgrade to lerna v5. Our CI is not impacted by the Node version breaking changes, and we _should_ be fine with the `@npmcli/run-script` changes (we make use of `prepublishOnly`, but that appears to still be part of the API).
- There appear to be intermittent failures with the Ionic Angular Server package after these changes: …

chore(lerna): downgrade lerna for now

---

core/src/components/datetime/datetime.scss

Issue URL: 
Duplicate of #25484. Accidentally referenced the wrong issue in the commit description. This PR includes 2 commits, one to revert the commit with the incorrect description and another to re-commit the fix with the appropriate description/issue.

fix(item): multiple input appearance when using datetime

---

core/package-lock.json
core/package.json

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25485
- Updated Stencil DS Output Target dep. See https://github.com/ionic-team/stencil-ds-output-targets/pull/263 for a full explanation of the issue.

fix(vue): components have correct type definitions

---

.github/workflows/codeql-analysis.yml
angular/src/providers/platform.ts
angular/test/test-app/e2e/src/providers.spec.ts
angular/test/test-app/src/app/providers/providers.component.html
angular/test/test-app/src/app/providers/providers.component.ts

Add CodeQL workflow

---

LICENSE

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25542
- Updates MIT license to use correct format so that GitHub can auto-detect it.

chore(): update license to use correct format

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.1.12

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.1.13

---

core/src/components/datetime/utils/comparison.ts

Stencil does not rewrite path aliases during build. This causes consuming Stencil apps to throw an exception when trying to resolve the custom path alias. 
For Ionic, this results in datetime breaking Stencil apps.
Issue URL: #25591
- Updates import to relative path
- Datetime works within Stencil apps
Dev-build: `6.1.14-dev.11657236641.106931ae`

fix(datetime): datetime works within stencil apps

---

core/src/components/item/test/inputs/item.e2e.ts

Tests are failing consistently as a result of this test. 
Issue URL: N/A
- Skips the test for now. Resolution for this flaky test is in the active sprint.

test(item): skip flaky inputs test

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.1.14

---

core/src/components/picker/picker-interface.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25631
- Deprecates the refresh key in the PickerColumn interface. I also added a ticket internally to remove this key in the next major release of Ionic.

chore(picker): deprecate the refresh key

---

core/package-lock.json
core/package.json
core/src/components/action-sheet/test/basic/action-sheet.e2e.ts
core/src/components/datetime/test/minmax/datetime.e2e.ts
core/src/components/toggle/test/basic/toggle.e2e.ts

Issue URL: https://github.com/microsoft/playwright/issues/14135
There was a bug in Playwright where `toHaveJSProperty` would not let you check boolean values. This was fixed in 1.23 and is needed for https://github.com/ionic-team/ionic-framework/pull/25643.
- Updated Playwright dependency to v1.23.
- It appears there is a behavior change where `toBeDisabled` does not work as expected in non-form components (in our case, setting `disabled` on a web …

test(playwright): update to playwright 1.23

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.1.15

---

core/package-lock.json
core/package.json
core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/presentation/datetime.e2e.ts
core/src/components/nav/nav.tsx
core/src/components/nav/test/modal-navigation/index.html
core/src/components/nav/test/modal-navigation/nav.e2e.ts
packages/vue/src/vue-component-lib/utils.ts

chore(): sync feature-6.2 with main

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/api.txt
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.2.0

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.2.1

---

.github/workflows/release.yml

The script that purges the JSDelivr cache on release was missing some quotes. As a result, the cache purge request failed.
- Add missing quotes

chore(ci): add missing quotes to cache script

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.2.2

---

.github/workflows/actions/build-core/action.yml
core/src/components.d.ts

We were not checking for diffs with `core/src/components.d.ts` so some build changes slipped through.
- Check `core/src/components.d.ts` when looking for diffs.

chore(ci): account for components.d.ts in clean build

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/directives/proxies-list.ts
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.2.3

---

core/package-lock.json
core/package.json

Issue URL: https://github.com/ionic-team/stencil/issues/3461
Saving changes to CSS in components would cause the styles in any HTML test file to get wiped.
- Styles no longer get wiped

chore(): update stencil to resolve css hmr issue

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/directives/proxies-list.ts
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.2.4

---

BREAKING.md
core/src/css/core.scss

Issue URL: resolves #17583 
- The global `hidden` attribute has been removed. Developers can continue to use the `hidden` attribute, but they will be getting the native implementation here: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden
The main difference is that the native `hidden` attribute is easier to override (there is no `!important`) than the Ionic one, so developers relying on the `!important` in Ionic's implementation …

refactor(core): remove global hidden attribute

---

core/package-lock.json
core/package.json

Issue URL: resolves #25830
- Updates to Ionicons 6.0.3 to resolve sanitizer bug.

chore(icon): update ionicons dependency

---

core/src/components/datetime/datetime.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25844
- Narrators no longer read the icon aria-label. Instead, they read the custom "previous month" or "next month" labels we have assigned to the buttons.

fix(datetime): next and previous buttons have correct labels

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.2.5

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/directives/proxies-list.ts
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.2.6

---

core/src/components/tab-bar/tab-bar.tsx

When running a stencil application with the latest `@ionic/core@6.2.6` the ion-tab-bar component has an unresolved import:
```
Bundling Warning UNRESOLVED_IMPORT '@utils/keyboard/keyboard-controller' is imported by ./node_modules/@ionic/core/dist/collection/components/tab-bar/tab-bar.js, but could not be resolved – treating it as an external dependency
```
Issue URL: https://github.com/ionic-team/ionic-framework/issues/25897
Now importing via relative …

fix(tab-bar): use correct import path

---

angular/test/README.md

Issue URL: N/A internal ticket
- Test directory for angular now has info on how to disable the `.angular` cache.

test(angular): add info on how to disable cache

---

core/src/components/input/test/input-events.e2e.ts

N/A
Issue URL: N/A
- Skip `ionChange` related tests on RTL

test(input): skip ionChange test on RTL

---

packages/react/src/components/CreateAnimation.tsx

Issue URL: https://twitter.com/schlimmson/status/1569677817935446017
The `CreateAnimation` component did not use the correct type so TypeScript did not know about the `children` prop.
- `CreateAnimation` now uses `PropsWithChildren`

fix(react): add correct type for CreateAnimation

---

angular/src/directives/proxies.ts
core/api.txt

Forgot to run the build output after making changes to the input `ionChange` feature. 
- Runs `npm run build` to update the generated output

chore(input): build output

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/directives/proxies-list.ts
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.2.7

---

core/src/utils/test/overlays/overlays.e2e.ts

test(overlay): fix test flakiness

---

core/.eslintrc.js

Issue URL: N/A When syncing `feature-6.3` with `main`, I noticed some new boolean expression violations. Since this rule is only configured to warn, we did not catch this. This rule helps avoid situations where numbers are used boolean expressions (like the bug we had in https://github.com/ionic-team/ionic-framework/issues/25714), so I think this should error instead of warn.
- Updated strict boolean expression to error.

chore(eslint): strict boolean expressions now error

---

core/src/utils/animation/animation-utils.ts
core/src/utils/animation/animation.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25987
- Animation util only does feature detection on the `window` if it is defined.

fix(animation): improve compatibility with ssr

---

.github/CODEOWNERS

GitHub team permissions are now managed through terraform, so we should use the terraform-created team.
-
-
-

chore(codeowners): update global owners

---

.github/workflows/actions/build-angular/action.yml
angular/package.json
angular/scripts/sync.sh

Issue URL: N/A
Amanda noticed that running `npm run build` in `feature-7.0` leads to build errors. This is happening because the local build of Ionic Angular still install `@ionic/core@6` instead of the local core build.
This was never caught on CI because the CI scripts were symlinking core.
- Add a sync script to ensure that project maintainers can use the local build of core when building angular.
- Updated CI scripts to use this script too.

chore(angular): properly sync core changes

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/directives/proxies-list.ts
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.2.9

---

.github/workflows/release.yml
package-lock.json
package.json

Prior to Lerna 5.4, Lerna did not update the `package-lock` files when releasing Ionic. As a result, we added a step to our release process that ran `npm install --package-lock-only --legacy-peer-deps` on all the packages we release in order to update the package lock files. 
This resulted in intermitted failures when updated from NPM: https://github.com/ionic-team/ionic-framework/actions/runs/3098246427/jobs/5015916944
- Lerna 5.x now updates the package …

chore(lerna): update lerna

---

angular/.prettierignore

The `.prettierignore` file in `angular` excludes `src/directives/proxies.ts` which is an autogenerated file from `stencil-ds-output-target`. However, it does not exclude `proxies-list.ts` which is another autogenerated file from the same package. As a result, we are getting lint failures every time `proxies-list.ts` is re-generated: https://github.com/ionic-team/ionic-framework/actions/runs/3143985277/jobs/5109467104
- Adds …

chore(angular): exclude proxies-list from lint

---

core/src/components/radio-group/radio-group.tsx

Issue URL: N/A
- Document the purpose behind `ion-radio-group`.

docs(radio-group): document radio-group purpose

---

BREAKING.md
angular/test/apps/ng12/src/app/modal-example/modal-example.component.ts
angular/test/apps/ng13/src/app/modal-example/modal-example.component.ts
angular/test/base/e2e/src/form.spec.ts
angular/test/base/e2e/src/inputs.spec.ts
angular/test/base/e2e/src/modal.spec.ts
angular/test/base/src/app/inputs/inputs.component.html
angular/test/base/src/app/modal-example/modal-example.component.html
angular/test/base/src/app/modal-example/modal-example.component.ts
core/src/components/datetime/test/color/datetime.e2e.ts
core/src/components/select/select.tsx
core/src/components/select/test/basic/select.e2e.ts

⚠️ Be sure to set commit message to the breaking change note when merging 
Issue URL: N/A internal ticket
- `ionChange` will now fire as a result of user-generated actions only.

feat(select): ionChange will only emit from user committed changes

---

core/package.json

Issue URL: N/A
`npm run lint.fix` only fixes the ESLint errors that can be automatically fixed. It does not run prettier at all. In order to do that, `npm run lint` must be run again. This is confusing as `npm run lint.fix` should attempt to fix any lint problem.
- `npm run lint.fix` now runs prettier.

chore(core): lint.fix command now runs prettier

---

.github/workflows/actions/build-angular-server/action.yml
.github/workflows/actions/build-angular/action.yml
.github/workflows/actions/build-core/action.yml
.github/workflows/actions/build-react-router/action.yml
.github/workflows/actions/build-react/action.yml
.github/workflows/actions/build-vue-router/action.yml
.github/workflows/actions/build-vue/action.yml
.github/workflows/actions/download-archive/action.yml
.github/workflows/actions/test-angular-e2e/action.yml
.github/workflows/actions/test-core-clean-build/action.yml
.github/workflows/actions/test-core-e2e/action.yml
.github/workflows/actions/test-core-lint/action.yml
.github/workflows/actions/test-core-screenshot/action.yml
.github/workflows/actions/test-core-spec/action.yml
.github/workflows/actions/test-react-e2e/action.yml
.github/workflows/actions/test-react-router-e2e/action.yml
.github/workflows/actions/test-vue-e2e/action.yml
.github/workflows/actions/update-reference-screenshots/action.yml
.github/workflows/actions/upload-archive/action.yml
.github/workflows/build.yml
.github/workflows/dev-build.yml
.github/workflows/nightly.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/update-screenshots.yml

Issue URL:  N/A
GitHub noted that Node.js 12 actions are deprecated: https://github.com/ionic-team/ionic-framework/actions/runs/3229200184
```
[dev-build](https://github.com/ionic-team/ionic-framework/actions/runs/3229200184/jobs/5286217525)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to …
```

chore(ci): update actions versions

---

packages/vue/src/components/IonApp.ts
packages/vue/src/components/IonBackButton.ts
packages/vue/src/components/IonIcon.ts
packages/vue/src/components/IonNav.ts
packages/vue/src/components/IonRouterOutlet.ts
packages/vue/src/components/IonTabBar.ts
packages/vue/src/components/IonTabButton.ts
packages/vue/src/utils.ts

Issue URL: N/A  A bug was reported internally that the ripple effect was not working. This was because `ion-tab-button` was not registering it's child `ion-ripple-effect` component: https://github.com/mhartington/ionic-vue-vite-test
- "Hand crafted" Ionic Vue components (as opposed to autogenerated components in proxies.ts) now import and all the `defineCustomElement` function for each custom element provided by Stencil.

fix(vue): routing components define child components

---

core/src/components/item-sliding/test/basic/item-sliding.e2e.ts

The gesture test for `ion-item-sliding` is flaky.
Issue URL: https://github.com/ionic-team/ionic-framework/actions/runs/3251629505/jobs/5336937862
Skips the test for now until we can improve our gesture testing.

test(item-sliding): skip flaky gesture test for now

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
angular/src/directives/proxies-list.ts
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.3.2

---

core/src/components/segment/segment.tsx

When manually calling the `.click()` method for a segment button, the `ionChange` event is not emitted.
Results in failing tests when trying to sync feature 7.0 with main: https://github.com/ionic-team/ionic-framework/actions/runs/3314035504
Issue URL: N/A
- When calling `.click()` manually on a segment button, `ionChange` is emitted.

fix(segment): click event triggers ionChange

---

core/src/components/menu-toggle/test/basic/index.html
core/src/components/menu-toggle/test/basic/menu-toggle.e2e.ts

`ion-menu-toggle` doesn't currently have any tests, so this PR adds a basic one that just makes sure it can open the selected menu. The existing `button` and `list` HTML files seem redundant, so I didn't add E2E tests for those.

test(menu-toggle): add basic Playwright test

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.3.3

---

BREAKING.md
angular/src/index.ts
core/src/components.d.ts
core/src/components/action-sheet/action-sheet-interface.ts
core/src/components/action-sheet/action-sheet.tsx
core/src/components/alert/alert-interface.ts
core/src/components/alert/alert.tsx
core/src/components/loading/loading-interface.ts
core/src/components/loading/loading.tsx
core/src/components/modal/modal-interface.ts
core/src/components/modal/modal.tsx
core/src/components/picker/picker-interface.ts
core/src/components/picker/picker.tsx
core/src/components/popover/popover-interface.ts
core/src/components/popover/popover.tsx
core/src/components/toast/toast-interface.ts
core/src/components/toast/toast.tsx
packages/react/src/components/index.ts
packages/vue/src/index.ts

⚠️ Add breaking change to commit message on merge.
Issue URL: N/A
The overlay attributes interfaces were deprecated in favor of using `{ [key: string]: any }`.
- Removed all overlay attribute interfaces.

refactor(types): remove overlay attribute interfaces

---

core/src/components/item/item.mixins.scss
core/src/components/item/item.vars.scss

This mixin is currently unused and the code, if used, results in CSP violations. The `svg-background-image` mixin used, inlines the SVG contents to `data:`, which violates CSP. 
Issue URL: N/A
- Removes the unused mixin.

chore(item): remove unused item SCSS mixins

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.3.4

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.3.5

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.3.6

---

angular/test/base/e2e/src/form.spec.ts

This test has a `cy.wait(300)` in it that was added to work around a bug which has since been fixed in v7. (See ticket mentioned in the TODO)
Wait removed.

test(angular): remove unnecessary wait

---

.github/workflows/actions/release/action.yml

`npm publish` could not find the correct publish token because it was being set in the wrong directory. The `.npmrc` file was set at the project root, but `npm publish` was being called from `inputs.working-directory`.
This is different from our old release process where both `.npmrc` and `lerna publish` were being called from the project root.
- Updated the release script to set the `.npmrc` token in `inputs.working-directory`

chore(ci): .npmrc set in working directory

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.3.7

---

.github/workflows/dev-build.yml

chore(ci): dev build runs in parallel

---

.github/workflows/nightly.yml

Nightlies are failing to push to GitHub because I named the temp branch in such a way that it falls under branch protection rules for our version branches: https://github.com/ionic-team/ionic-framework/actions/runs/3494606832/jobs/5850589152
- Nightly branches are now prefixed with "tmp-" to indicate that they are temporary and to avoid falling into branch protection for version branches.

chore(ci): nightly is pushed to temp branch

---

angular/test/apps/ng12/package-lock.json
angular/test/apps/ng12/package.json
angular/test/apps/ng13/package-lock.json
angular/test/apps/ng13/package.json
angular/test/apps/ng14/package-lock.json
angular/test/apps/ng14/package.json

The test apps for Angular have an unused dependency.
Issue URL: N/A
- Removes unused dependency from base test app projects

chore(angular): remove unused dep from test apps

---

.github/workflows/release.yml

I forgot to update the a dependency for the "purge-cdn-cache" job when releasing.
- The Purge CDN Cache job now depends on completion of  the "release-ionic" job instead of non existent jobs.

chore(ci): fix release dependency

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.3.8

---

core/src/components/input/input.scss

Issue URL: N/A
- Updates the documentation around `--border-width` to specify width instead of color.
- Updates the documentation around `--border-style` to specify style instead of color.

docs(input): border style/width documentation

---

core/src/components/textarea/test/a11y/index.html
core/src/components/textarea/test/a11y/textarea.e2e.ts
core/src/components/textarea/textarea.tsx

- Adds a `<label>` and `<textarea>` elements inside of the new textarea render function
- Adds tests for the modern layout and a11y 
This is one of many PRs for FW-2764

feat(textarea): add base functionality and tests

---

BREAKING.md
core/src/components/action-sheet/action-sheet.scss

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25368
(Technical detail available in issue)
- The action sheet container now only takes up as much space as needed to render the content.
- Changed the `--height` default to `auto`
| `main` | branch |
| - | - |
| <video src="https://user-images.githubusercontent.com/2721089/203424136-a3d0e517-188c-472f-98e5-216f7f0fffd2.mov"></video> | <video …

fix(action-sheet): container animates in correctly

---

BREAKING.md
angular/src/directives/control-value-accessors/boolean-value-accessor.ts
angular/src/directives/control-value-accessors/value-accessor.ts
angular/test/base/e2e/src/inline-overlays.spec.ts
angular/test/base/e2e/src/inputs.spec.ts
core/src/components/datetime-button/datetime-button.tsx
core/src/components/datetime/datetime.tsx

`null` values for form components have been converted to `''` for years in Angular. This has resulted in confusing developer experiences such as https://github.com/ionic-team/ionic-framework/issues/26116. It appears that this change was originally made to better support IE9, so it should be safe to remove.
- `null` is no longer converted to the empty string in Ionic Angular apps.

fix(angular): null values are not converted to falsy value

---

core/src/components/input/test/bottom-content/index.html
core/src/components/input/test/bottom-content/input.e2e.ts

The input test for bottom content does not target the correct container when checking if the bottom container should not render.
Issue URL: N/A
- Updates the test to target the `.input-bottom` container instead of `.item-bottom`

test(input): validate input-bottom container is not rendered

---

BREAKING.md
core/src/components/picker-column-internal/picker-column-internal.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25508
The haptics were originally intended for iOS only but were also enabled on Android. The haptics on Android are reported to be more obtrusive than some would like, so we decided it would be best to disable the haptics on Android.
- The haptics when swiping the picker now are enabled on iOS only.

fix(datetime): haptics are enabled only on ios

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.3.9

---

core/api.txt
core/src/components/toast/test/basic/toast.e2e.ts
core/src/components/toast/toast.tsx
core/src/utils/config.ts

This PR is identical to https://github.com/ionic-team/ionic-framework/pull/26401, but made against the feature branch instead of `main`.

feat(toast): add global config toastDuration

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.4.0

---

core/src/components/searchbar/test/basic/searchbar.e2e.ts

The searchbar basic screenshot test is flaky for the animated searchbar: https://github.com/ionic-team/ionic-framework/pull/26427/files#diff-68bab2c563977d999e5ae3508790ba16a0a20ceef6538919d2b306ed08bd60b9
Issue URL: N/A
- Introduces delay before capturing the screenshot. 
- The animated searchbar requires the searchbar to render before the cancel button is positioned. This results in potentially flaky screenshot captures.

test(searchbar): flaky searchbar screenshot capture

---

core/src/components/modal/gestures/utils.ts

Stencil applications or libraries using Ionic Framework will receive an exception when using `ion-modal`.
Issue URL: https://github.com/ionic-team/stencil/issues/3893
- Reverts the import path change from using an alias to a relative path. Stencil has an open issue with aliases: https://github.com/ionic-team/stencil/issues/3826
Dev-build: `6.4.1-dev.11670531659.1bd9a8b7`

fix(modal): compatibility with stencil libraries/apps

---

core/playwright.config.ts
core/src/components/datetime/test/basic/datetime.e2e.ts
core/src/components/datetime/test/presentation/datetime.e2e.ts
core/src/components/item-sliding/test/basic/item-sliding.e2e.ts
core/src/components/item-sliding/test/scroll-target/item-sliding.e2e.ts
core/src/components/picker-column-internal/test/disabled/picker-column-internal.e2e.ts
core/src/utils/tap-click/test/tap-click.e2e.ts
core/src/utils/test/overlays/overlays.e2e.ts

Tests currently take a long time to run. Additionally, flaky tests are easy to miss.
- Disabled test retries. This will speed up tests and also cause flaky tests to error instead of warn (the warning messages are easy to miss on CI unless you know to look for them)
- Added a max test failure of 1 on CI. This will cause tests to fail fast so developers can get to fixing their tests sooner. A single test is run on multiple configurations, so subsequent …

test(config): tests now fail fast

---

core/src/components/accordion/test/accordion.e2e.ts
core/src/components/action-sheet/test/basic/action-sheet.e2e.ts
core/src/components/alert/test/basic/alert.e2e.ts
core/src/components/datetime-button/test/basic/datetime-button.e2e.ts
core/src/components/datetime-button/test/overlays/datetime-button.e2e.ts
core/src/components/datetime/test/prefer-wheel/datetime.e2e.ts
core/src/components/fab/test/basic/fab.e2e.ts
core/src/components/picker-internal/test/basic/picker-internal.e2e.ts
core/src/components/radio-group/test/search/radio-group.e2e.ts

Several tests are not waiting for their assertion promises to resolve. This can make the tests flake on CI.
- Added `await` to all assertions that returned a promise
- x ] No

test(many): add await to async asserts

---

core/src/utils/animation/test/multiple/animation.e2e.ts

The CSS Animation group test is flaky on CI.
- Skip the CSS Animation group test

test(animation): skip group css animation test

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.4.1

---

core/src/components/select/test/color/index.html
core/src/components/select/test/color/select.e2e.ts
core/src/components/select/test/fill/index.html
core/src/components/select/test/fill/select.e2e.ts
core/src/components/select/test/highlight/index.html
core/src/components/select/test/highlight/select.e2e.ts

Select does not have tests for fill, shape, color, highlight functionalities
- Added base templates and test shells for future feature work.
Note: The lint step will fail here due to empty arrow functions and unused imports. This will be resolved once the implementation is added in future PRs.

test(select): add base tests files for fill, shape, color, highlight

---

core/src/components/toggle/toggle.tsx

As noted in https://github.com/ionic-team/ionic-framework/pull/26499#discussion_r1051097483, the emitStyle function only applies to the legacy toggle.
- emitStyle now only fires with legacy toggle

fix(toggle): emitStyles only fires with legacy control

---

core/src/components.d.ts
core/src/components/select/select.tsx
core/src/components/select/test/a11y/index.html
core/src/components/select/test/a11y/select.e2e.ts
core/src/components/select/test/label/index.html
core/src/components/select/test/label/select.e2e.ts
core/src/components/select/test/states/index.html
core/src/components/select/test/states/select.e2e.ts

Select does not support the new label syntax
- Added test templates for label, state, and a11y tests
Note: The lint step will on these files. This will addressed in future PRs.

test(select): add base label templates

---

.github/ionic-issue-bot.yml
.github/workflows/nightly.yml

Issue URL: 
- Adds holiday triaging to the repo

chore(): start holiday triage 2022

---

core/src/components/item/item.tsx

This changes the deprecation notice for a few `@slot` tags on the `ion-item` component. Previously the lines in question looked something like this:
```ts
/**
* @slot a slot that does something @deprecated this is going away!
*/
export class Item { ...
```
The intention behind formatting the JSDoc this way was to mark the `@slot` itself as deprecated, to advice users that it will be removed in the future.
Unfortunately, JSDoc tooling doesn't interpret the `@deprecated` tag as referring to the `@slot` tag here, but instead as one of the tags applied to the `Item` class. If we wanted to use `@deprecated` to mark only a slot as deprecated then we'd need a way to write a JSDoc just for that slot itself.
Since we don't want to mark the whole class as deprecated, as a workaround, we can change …

chore(item): modify slot deprecation notice to avoid JSDoc formatting issue

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.4.2

---

angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
packages/react/package-lock.json
packages/react/package.json
packages/vue/package-lock.json
packages/vue/package.json

Issue URL: N/A
Ionic's internal icons are using an old version of Ionicons.
- Updates the ionicons deps to use 6.1.0 or newer

feat(deps): update ionicons to 6.1.0

---

angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
packages/react/package-lock.json
packages/react/package.json
packages/vue/package-lock.json
packages/vue/package.json

Turns out the `<title>` for icons was being added in another place: https://github.com/ionic-team/ionicons/issues/1168 I published Ionicons 6.1.1 with a fix.
- Update deps to Ionicons 6.1.1

feat(deps): update ionicons to 6.1.1

---

.github/workflows/release.yml
CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.4.3

---

core/src/components/modal/modal.tsx
core/src/utils/overlays.ts

See https://github.com/ionic-team/ionic-framework/pull/26650
- Updated `triggerController` to warn about missing trigger elements
- Migrated `ion-modal` to use `triggerController`.
Note: I did not migrate popover because it has more complex trigger requirements than what `triggerController`  supports (trigger actions for example)

fix(overlays): triggerController warns about missing triggers

---

angular/src/directives/proxies.ts
core/api.txt

chore(): run build

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
core/src/components/select/select.tsx
core/src/components/select/test/basic/select.e2e.ts
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Sync beta 0

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/components/IonApp.ts
packages/vue/src/framework-delegate.ts
packages/vue/test/base/src/components/ModalContent.vue
packages/vue/test/base/tests/e2e/specs/overlays.cy.js

Resolves #26644
Issue URL: 
-
-
-

fix(vue): unmount teleported components (#26647)

---

CHANGELOG.md

chore(): clean up changelog

---

.github/ISSUE_TEMPLATE/bug_report.yml

Issue URL: N/A
- Adds a "v7.x" section to the issue template

chore(github): update issue template for v7 beta

---

.github/ISSUE_TEMPLATE/bug_report.yml
.gitignore
angular/scripts/sync.sh
angular/test/base/scripts/sync.sh
core/src/components/select/select.tsx
core/src/components/select/test/async/index.html
core/src/components/select/test/async/select.e2e.ts
core/src/utils/test/overlays/overlays.e2e.ts
packages/react-router/test-app/scripts/sync.sh
packages/react/test-app/scripts/sync.sh
packages/vue-router/scripts/sync.sh
packages/vue/scripts/sync.sh
packages/vue/test/base/scripts/sync.sh

Sync main scripts

---

core/src/components/textarea/textarea.scss

Textarea container does not inherit height from the host container. 
- Aligns textarea wrapper container implementation with the input wrapper container implementation
- Textarea wrapper inherits height vs. sizing the maximum available space
Dev-build: `7.0.0-dev.11675196564.12c5f9a0`

fix(textarea): textarea wrapper inherits height

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.5.2

---

.github/workflows/release.yml
CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.0-beta.1

---

core/src/components/datetime-button/datetime-button.tsx
core/src/components/popover/utils.ts
core/src/components/select/select.tsx
core/src/utils/theme.ts

Recently we bumped the Stencil dependency to v3. If locally you do not install the latest, these import paths will cause a build-time exception.
Issue URL: N/A
- Updates the import paths to pull from their source location instead of a barrel file
This change isn't required - updating the dependency locally should resolve these build errors, but since we are wanting to move away from the `interface` barrel file anyways and it was causing issues with …

chore(many): import types from source path

---

core/src/components/range/range.tsx

This is a really minor fix.
If we use legacy code, you'll get the following warnings:
```
Example: <ion-range>Volume:</ion-toggle>
```
Issue URL: 
```
Example: <ion-range>Volume:</ion-range>
```

chore(range): fix v7 range warning

---

BREAKING.md

Formatting issue within `BREAKING.md`.
Issue URL: 
- Updates the code formatting to display correctly within `BREAKING.md`

chore(BREAKING): code syntax formatting 

---

.github/workflows/build.yml

We recently gained access to the [GitHub Merge Queue Beta](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)
- Adds a "merge_group" workflow trigger to our CI test process so that these checks are run during the merge queue validation process

chore(ci): enable merge queue trigger

---

BETA.md

chore(): merge test B

---

core/src/components/input/input.utils.ts
core/src/components/item/item.tsx
core/src/components/picker-column-internal/picker-column-internal.tsx
core/src/components/select/select.tsx
core/src/utils/overlays.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26778
- Removes TSConfig alias usage from publicly consumed files

fix(many): resolve import errors with stencil apps

---

core/src/utils/input-shims/hacks/test/scroll-assist.e2e.ts

The scroll assist tests continue to be flaky: https://github.com/ionic-team/ionic-framework/actions/runs/4138397596/jobs/7154799903
I'm not 100% sure why this is, but I have a feeling it is related to `setTimeout` not necessarily firing on the specified timeout. I'd like to try giving this test triple the timeout via `test.slow()` to see if that alleviates the flakiness.
- Added `test.slow()` to scroll assist tests.

test(scroll-assist): mark test as slow

---

core/src/utils/tap-click/test/tap-click.e2e.ts

This test continues to be flaky despite a refactor: https://github.com/ionic-team/ionic-framework/actions/runs/4138711751/jobs/7155481256
Given that this test is dependent on a user gesture (clicking and holding) I'd like to skip the test until Playwright handles gestures a bit better.
- Skips the tap-click test

test(tap-click): skip flaky test

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.5.4

---

core/src/components/datetime/datetime.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26811
- Days of weeks label are not announced by screen readers
- Spacing buttons are not announced by screen readers

fix(datetime): days of week and spacing buttons are not announced by screen readers

---

angular/scripts/sync.sh
packages/vue-router/scripts/sync.sh
packages/vue/scripts/sync.sh

The sync scripts for the Angular and Vue package attempt to package themselves, which results in an infinite-running process. Only the test apps need to pack these packages (as part of their own sync scripts). 
Issue URL: N/A
- Remove the unnecessary pack step

chore(angular,vue): remove sync script packing itself

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.5.5

---

core/src/components/input/input.tsx
core/src/components/textarea/textarea.tsx

When fixing https://github.com/ionic-team/ionic-framework/issues/25740, I discovered that we had extra `aria-disabled` attributes on the modern input and textarea. These are not needed because the native `input` or `textarea` element receives focus now and already has the `disabled` prop set.
- Removes `aria-disabled` from the host of the modern input and textarea layouts.

refactor(input, textarea): remove extra aria-disabled

---

core/src/utils/input-shims/hacks/test/scroll-assist.e2e.ts

Test is frequently flaky on CI https://github.com/ionic-team/ionic-framework/actions/runs/4234444446/jobs/7356803376
- Skipped tests and added a ticket in our backlog to investigate

test(scroll-assist): skip flaky test

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.5.6

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.0 beta.4

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.0 beta.5

---

core/src/components/modal/test/sheet/modal.e2e.ts

One of the sheet modal tests is flaky in the v7 branch due to improvements in scroll assist: https://github.com/ionic-team/ionic-framework/actions/runs/4285060609/jobs/7462908962
- Updated logic to only get the first instance of the native input to avoid collisions with scroll assist running
- Removed `await` because `page.locator` does not return a promise

test(modal): improve stability of sheet test

---

core/src/components/popover/test/basic/popover.e2e.ts

The `basic` tests for `ion-popover` have a few utils that check various things about the active element without using Playwright assertions.
Issue URL: N/A
Tests migrated fully.

test(popover): convert focus tests to Playwright assertions

---

core/package-lock.json
core/package.json

Ionic Framework v7 is using a pre-release version of Stencil Sass
Issue URL: N/A
this commit bumps the version of `@stencil/sass` from its pre-release
version (3.0.0-0) to the general availability version (3.0.0). no
changes between the two versions exists, other than the version number
itself.

chore(deps): upgrade @stencil/sass to v3.0.0 

---

core/package-lock.json
core/package.json
core/stencil.config.ts

Framework v7 currently uses Stencil 3.0.0
Issue URL: 
this commit increments the version of stencil used to v3.1.0. this release of stencil fixes an issue for the ionic framework, where module aliases from `tsconfig.json#paths` can be transformed by setting `transformAliasedImportPaths: true` in a stencil configuration file
changelog: https://github.com/ionic-team/stencil/releases/tag/v3.1.0
documentation: …

chore(deps): upgrade stencil to v3.1.0

---

core/src/components/popover/test/basic/popover.e2e.ts

Getting test flakiness: https://github.com/ionic-team/ionic-framework/actions/runs/4297666592/jobs/7490964884
It looks like the checks do not wait for scrolling to finish, so slower test runs may fail. Additionally, checking the exact scroll positions seems to be testing browser functionality which I don't think we need to do. What's more important is that the textarea remains focused when using the arrow keys.
- Update test to only check textarea focus …

test(popover): reduce test flakiness

---

core/src/components/img/test/basic/img.e2e.ts

The ionImgDidLoad event test is also flaky: https://github.com/ionic-team/ionic-framework/actions/runs/4324026004/jobs/7548381641
- Skipped the entire block with the same tech debt ticket

test(img): skip flaky event loading tests

---

angular/package-lock.json
angular/package.json
core/package-lock.json
core/package.json
core/src/components/range/test/a11y/index.html
core/src/components/refresher-content/refresher-content.tsx
core/src/components/reorder/reorder.tsx
core/src/components/toast/toast.tsx
packages/react/package-lock.json
packages/react/package.json
packages/vue/package-lock.json
packages/vue/package.json

Ionic Framework v7 still used Ionicons v6
I also noticed some issues with toast, reorder, and refresher-content where decorative icons were not hidden from assistive tech.
- Updates ionicons deps to v7.0.0
- Adds `aria-hidden="true"` to the icons in refresher-content, reorder, and toast. (I am considering this a fix due to the aria-hidden changes here)

fix(many): add aria-hidden to decorative icons

---

core/src/components.d.ts
core/src/components/modal/modal.tsx

I did not do the following, as it is only a comment change.
Autogenerated documentation is incorrect.
Issue URL: 
Autogenerated documentation is correct.

docs(modal): typo on didPresent description

---

README.md

N/A
- Adds the migration guide for v6 to v7

chore(readme): v7 migration guide

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.6.1

---

core/src/components/input/input.md.scss
core/src/components/input/input.md.solid.scss
core/src/components/input/input.scss
core/src/components/select/select.md.solid.scss
core/src/components/textarea/textarea.md.solid.scss
core/src/components/textarea/textarea.scss

Issue URL: See ticket for issue description
- `--border-color` is now updated on the host instead of a child element

fix(input, select, textarea): border color is set on host

---

.github/dependabot.yml

This PR adds Stencil to the dependabot list. Dependabot will submit a PR whenever there is a new version of Stencil so we can always stay on the latest version. Note: This will cause Dependabot to only submit Stencil v2 PRs for now due to our package.json requirements: https://github.com/ionic-team/ionic-framework/blob/d6c06ecfe85e25d7c055e08054755f249ae48cbd/core/package.json#L34
Once Ionic v7 releases and `feature-7.0` is merged into `main` we can get the latest v3 changes.
Please check the type of …

chore(dependabot): add stencil

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.6.2

---

core/src/components/radio/test/a11y/radio.e2e.ts

Similar to https://github.com/ionic-team/ionic-framework/pull/26946 the radio keyboard test is also flaky: https://github.com/ionic-team/ionic-framework/actions/runs/4428254914/jobs/7767134734?pr=26958
- Skipped the flaky test
- Added tech debt ticket to backlog to investigate

test(radio): skip flaky test

---

README.md

the link in readme is not working (404 not found)
Link in readme is not working
Issue URL: 
-
-
-

chore(): fix link in readme

---

.github/dependabot.yml

`versioning-strategy` should be placed inside of the `updates` block. Dependabot did not inform me of this error until the config had been merged: https://github.com/ionic-team/ionic-framework/runs/12133205044
Moves `versioning-strategy` inside of the `updates` block.

chore(dependabot): move versioning-strategy to correct block

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.7.0

---

core/src/components/alert/alert.tsx

Alert uses `ev.code` to determine the value of the key being pressed.
Issue URL: N/A
- Switched from `ev.code` to `ev.key`
Alert uses `ev.key` to determine the value of the key being pressed.
N/A

refactor(alert): switch ev.code to ev.key

---

core/package-lock.json

Dependabot only updates @playwright/test: https://github.com/ionic-team/ionic-framework/pull/27036
This causes the Axe playwright plugin to warn about TypeScript errors because it still has `playwright@1.32.0`.
Issue URL: 
-
-
-

chore(): update playwright

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.7.1

---

core/README.md

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/27094
-
-
-
Co-authored-by: Sean Perkins <sean-perkins@users.noreply.github.com>
BREAKING CHANGE:
This is a breaking change.

fix(card): test 123

---

.github/PULL_REQUEST_TEMPLATE.md

As per the Merge Queue design doc, we are updating the PR template.
- Removes the checklist section
- Removes the type section
- Adds a comment to explains where to add docs changes to

chore(): update PR template

---

core/src/components/popover/test/size/popover.e2e.ts

Popover test is still flaky: https://github.com/ionic-team/ionic-framework/actions/runs/4611219177/jobs/8150680142
- Re-open tech debt ticket and skip test

test(popover): skip flaky screenshot test

---

.github/workflows/release.yml

v6 is no longer the latest version of Ionic. Any new v6 fixes should be released to the v6-lts tag.
- Removes `latest` as an option and adds `v6-lts`.
- Also removes the v5-lts and v4-lts tags as options.

chore(): update v6 release scripts to use v6-lts

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.7.3

---

core/src/components/segment-button/segment-button.tsx
core/src/components/segment/test/segment.spec.ts

This backports https://github.com/ionic-team/ionic-framework/pull/26970 to v6.
resolves https://github.com/ionic-team/ionic-framework/issues/26830

fix(segment-button): update checked state on render

---

core/src/components/textarea/test/legacy/basic/index.html

The legacy test template for the textarea test does not use a label and does not specify `legacy="true"`.
Issue URL: N/A
- Adds the `legacy="true"` property to the legacy template

test(textarea): use legacy form syntax for legacy test

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.7.4

---

core/src/components/datetime/test/prefer-wheel/datetime.e2e.ts

---------
These tests are flaky on CI: https://github.com/ionic-team/ionic-framework/actions/runs/4757321510/jobs/8454046190?pr=27247
Looks like we are not waiting long enough for scrolling to finish.

test(datetime): skip flaky tests

---

.github/workflows/actions/publish-npm/action.yml
.github/workflows/dev-build.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
angular/package.json
angular/scripts/package.json
core/package.json
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json
packages/vue-router/package.json
packages/vue/package.json

See https://github.blog/2023-04-19-introducing-npm-package-provenance/

chore(ci): enable npm package provenance

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.5

---

core/src/components/reorder-group/test/interactive/reorder-group.e2e.ts
core/src/components/reorder-group/test/nested/reorder-group.e2e.ts
core/src/components/reorder-group/test/scroll-target/reorder-group.e2e.ts

---------
Skipped reorder group tests were missing `page` which caused compilation errors on re-build
- Added `page` to affected tests

test(reorder-group): add page to skipped tests

---

core/README.md

---------
We've been using the custom elements bundle in Ionic for a few years now. The underlying behavior is stable in Stencil, so we should remove the "experimental" verbiage from the README.
- Removed experimental wording

chore(readme): remove experimental wording

---

core/src/components/popover/test/size/popover.e2e.ts

---------
A skipped popover test was missing a screenshot function
- Added missing screenshot function

test(popover): add missing screenshot function

---

.github/ionic-issue-bot.yml

---------
The text appears too cramped. I'd like there to be more space between each paragraph.
- Increase spacing between paragraphs

chore: add more spacing to automated message

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.6

---

.github/workflows/actions/build-core/action.yml
.github/workflows/build.yml
core/README.md

---------
Screenshots in a branch are currently compared against the screenshots on `main`. While we ultimately need to compare against ground truths in `main`, this can cause tests to seemingly fail at random. For example, this branch was created based on https://github.com/ionic-team/ionic-framework/commit/eb2772c0ce623de70cce42b5d36e86cdbba7bafb. However, https://github.com/ionic-team/ionic-framework/commit/381de0b3d324805161232d8556fffd7022fcd84c was added to `main` after the first commit and has new screenshot diffs. 
I do not have the latest ground truths for the changed screenshots in this branch, so the screenshot tests failed in https://github.com/ionic-team/ionic-framework/actions/runs/4995702351/jobs/8947969061 even though I did not change any component …

chore: remove ref from checkout workflow

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.8

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.9

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.10

---

core/src/components/select/select.scss
core/src/components/select/test/basic/index.html

Reverts ionic-team/ionic-framework#27570
-------
The team is reconsidering this approach as it causes us to fight against the browser. Discussions are ongoing internally, so I am going to revert this patch until we can reach consensus.

Revert "fix(select): prevent click event from firing twice"

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 6.7.5

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.12

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.0.13

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.1.0

---

CHANGELOG.md
angular/CHANGELOG.md
angular/package-lock.json
angular/package.json
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.1.1

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.1.2

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.1.3

---

core/src/components/badge/badge.ios.scss
core/src/components/badge/badge.vars.scss

---------
Badge does not support dynamic type
- Convert fonts to rem
- Add minimum font size for iOS to ensure legibility
Demo Video:  https://github.com/ionic-team/ionic-framework/assets/2721089/725e9f14-1c11-4861-9fb7-a3d462cb4d30

feat(badge): support dynamic type

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.1.4

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.2

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.2.1

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.2.2

---

core/playwright.config.ts

---------
Shawn noted that I had an outdated comment in the `playwright.config.ts` file when working on https://github.com/ionic-team/ionic-framework/pull/27961: https://github.com/ionic-team/ionic-framework/pull/27961#pullrequestreview-1572374939
- Remove the old comment

chore: remove old comment from playwright config

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.2.4

---

.github/workflows/actions/download-archive/action.yml
.github/workflows/actions/test-core-spec/action.yml
.github/workflows/stencil-nightly.yml
CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

chore: sync with main

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.3.1

---

.github/CODEOWNERS

chore(codeowners): add Amanda to checkbox and radio

---

.github/CODEOWNERS

---------
Maria isn't part of the codeowners.
- Maria has been added to the Angular and Vue folders.
N/A

chore(CODEOWNERS): add Maria to Angular and Vue

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.3.2

---

packages/angular/test/README.md

---------
- The instructions doesn't provide clear directory paths for syncing local changes.
- The instructions has clear directory paths for syncing local changes.
- Switched to the `[!NOTE]` for notes.
N/A

docs(angular): update README for clear directory paths

---

.stackblitz/codeflow.json

---------
Team isn't using the integration. 
- Disables the Codeflow integration on pull requests

chore: disable codeflow for pull requests

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.3.3

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.3.4

---

packages/vue/README.md
packages/vue/test/README.md

---------
The instructions doesn't provide clear directory paths for syncing local changes.
- The instructions has clear directory paths for syncing local changes.
- Updated out of date information.
N/A

docs(vue): update README instructions

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.4.1

---

packages/angular/test/apps/ng14/package-lock.json
packages/angular/test/apps/ng14/package.json
packages/angular/test/apps/ng15/package-lock.json
packages/angular/test/apps/ng15/package.json
packages/angular/test/apps/ng16/package-lock.json
packages/angular/test/apps/ng16/package.json
packages/react-router/test/apps/reactrouter5/package-lock.json
packages/react-router/test/apps/reactrouter5/package.json
packages/react/test/apps/react17/package-lock.json
packages/react/test/apps/react17/package.json
packages/react/test/apps/react18/package-lock.json
packages/react/test/apps/react18/package.json
packages/vue/test/apps/vue3/package-lock.json
packages/vue/test/apps/vue3/package.json

---------
CI is failing for Cypress apps due to https://github.com/cypress-io/cypress/issues/27804#issuecomment-1721476731.
- All Cypress test apps have been updated to Cypress 13.2.0 which is not affected by this issue.

test: update test apps to cypress 13

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.4.2

---

core/src/utils/test/playwright/docs/README.md
core/src/utils/test/playwright/docs/usage-instructions.md

---------
During planning the team discussed that some of our internal docs are outdated. Additionally, some of this info would be useful for contributors.
- Ported remaining E2E docs to GitHub
- Added info on installing deps, running tests, and updating screenshots. API and best practices are already on the repo.

test(docs): add info on how to run tests and update screenshots

---

core/package.json
core/src/utils/test/playwright/docs/usage-instructions.md

---------
Team members often need to update the ground truth screenshots when validating visual regressions or working on a design change. The command may be unfamiliar to them or they may be new to the project/playwright.  
- Adds a new script to the `core` package for updating the local (to the file system) ground truth screenshots.

chore: add script for updating local snapshots

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.4.3

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.4.4

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.5.1

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.5.2

---

core/src/components/alert/test/a11y/alert.e2e.ts

---------
I forgot to add annotations to tests to indicate the bug fix they are validating: https://github.com/ionic-team/ionic-framework/pull/28408
- Added annotations

test(alert): add annotations

---

.github/CONTRIBUTING.md

---------
i found a small typo in the contributing guide
update the relative path for updating ionic angular, now that it's code lives under the `packages/` directory

chore(repo): update angular path

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.5.3

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.5.4

---

BREAKING.md
core/src/components/content/content.scss

---------
While evaluating step colors for high contrast themes I discovered that this code is not actually applied anywhere.
- Remove unused code

chore: remove unused code

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.5.5

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.5.6

---

core/src/components/toast/toast-interface.ts

---------
I forgot to update ToastOptions with the new `swipeGesture` property. This prevents developers from using the feature with the toastController.
- Added swipeGesture as an option on `ToastOptions`

fix(toast): add swipeGesture to ToastOptions

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.5.7

---

.github/labeler.yml
.github/workflows/label.yml
core/package-lock.json
core/package.json
core/src/components.d.ts
core/src/components/action-sheet/action-sheet.tsx
core/src/components/alert/alert.tsx
core/src/components/input/input.tsx
core/src/components/loading/loading.tsx
core/src/components/modal/modal.tsx
core/src/components/picker/picker.tsx
core/src/components/popover/popover.tsx
core/src/components/searchbar/searchbar.tsx
core/src/components/textarea/textarea.tsx
core/src/components/toast/toast.tsx
packages/react-router/src/ReactRouter/ReactRouterViewStack.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/src/ReactRouter/utils/matchPath.ts
packages/react-router/test/base/src/pages/routing/Details.tsx
packages/react-router/test/base/tests/e2e/specs/routing.cy.js
packages/vue/src/components/IonNav.ts
packages/vue/test/base/src/components/Nav.vue
packages/vue/test/base/src/components/NavRoot.vue
packages/vue/test/base/tests/e2e/specs/navigation.cy.js

chore: sync feature-8.0 with main

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.5.8

---

core/api.txt
core/src/components.d.ts
core/src/components/datetime/datetime.tsx
core/src/components/datetime/utils/data.ts
core/src/components/picker-column-option/test/picker-column-option.spec.ts
core/src/components/picker-column/picker-column-interfaces.ts
core/src/components/picker-column/picker-column.ios.scss
core/src/components/picker-column/picker-column.md.scss
core/src/components/picker-column/picker-column.scss
core/src/components/picker-column/picker-column.tsx
core/src/components/picker-column/test/disabled/picker-column.e2e.ts
core/src/components/picker/test/keyboard-entry/picker.e2e.ts
packages/angular/src/directives/proxies.ts
packages/angular/standalone/src/directives/proxies.ts
packages/vue/src/proxies.ts

---------
There were a number of TODOs to clean up the remaining code for this feature.
- Many of the changes are autogenerated diffs. I added comments to diffs that I felt were not obvious for why they changed.

chore: clean up TODOs

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.6.1

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.6.2

---

.github/ionic-issue-bot.yml
.github/workflows/nightly.yml

This PR begins holiday triage mode for the Ionic Framework repo.

chore: start holiday triage 2023

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.6.3

---

.github/ionic-issue-bot.yml
.github/workflows/nightly.yml

Reverts ionic-team/ionic-framework#28757

chore: end holiday triage 2023

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
package-lock.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.6.4

---

.github/workflows/release.yml
CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
package-lock.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.6.5

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.6.6

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.6.7

---

core/src/css/core.scss

---------
The default light theme defines the colors by manually setting them even though the values are already defined in `ionic.theme.default.css` as Sass variables.
- The default light theme defines the colors by using the Sass variables. This will decrease the amount of files needed to update when changes are made.
N/A

refactor(core-styles): use sass variables in global styles

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.7.1

---

.github/CONTRIBUTING.md

---------
Updates the screenshot commands in contributing.

docs(contributing): update screenshot commands

---

core/src/components/textarea/textarea.ios.scss
core/src/components/textarea/textarea.md.scss

Removes missed legacy textarea styles

refactor(textarea): remove unused legacy styles

---

core/src/css/themes/dark.scss
core/src/themes/ionic.theme.default.scss

This PR makes adjustments to the standard contrast light and dark themes as defined in https://github.com/ionic-team/ionic-framework-design-documents/pull/248.

refactor: update styles according to design document

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

merge release-v7.7.3

---

.github/workflows/assign-issues.yml

I'm back!
Reverts ionic-team/ionic-framework#29066

chore: revert remove liam from auto-assign issues while out of office

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

v8.0.0-beta.0

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

merge release-7.7.4

---

.github/ISSUE_TEMPLATE/bug_report.yml

---------
N/A
- Code reproductions are now required for all new issue reports. The description around a reproduction and how developers can create one has been adjusted.
- We only support Ionic v7 to LTS at this point in time. Sending developers to a readonly repository where they cannot file issues doesn't add any value. I've updated the description and link to the relevant support page and enterprise offering.

chore: update bug report template descriptions and required fields

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.7.5

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.8.0

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.8.1

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.8.2

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
docs/CHANGELOG.md
docs/package-lock.json
docs/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 8.0.0 rc.0

---

core/src/components/checkbox/checkbox.ionic.scss
core/src/components/checkbox/checkbox.ionic.vars.scss
core/src/components/checkbox/checkbox.tsx

---------
- Adds the new ionic theme stylesheet and sass variables file for checkbox
- Sets the ionic theme stylesheet as the default when: `<ion-checkbox theme="ionic">`
Co-authored-by credit will be applied to the merge commit.

feat(checkbox): add ionic stylesheet and vars files

---

core/src/components/chip/chip.ionic.scss
core/src/components/chip/test/theme-ionic/index.html

Issue number: resolves #ROU-4838
---------
- Added styles for icons inside Chip (Ionic Theme)
- Fixed an issue related to hover status, after tokens integration

feat(Chip): Add styles for icons inside Chip Ionic Theme

---

.github/workflows/assign-issues.yml

This PR revises the list of who gets automatically assigned to issues.

chore: update issue assignment list

---

core/package-lock.json
core/package.json

---------
- Updates to the latest version of Stencil
- Includes a fix for the api.txt diff issue we are experiencing off `next`

chore(deps): update stencil to v4.17.1

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/docs/CHANGELOG.md
packages/docs/package-lock.json
packages/docs/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 8.0.1

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/docs/CHANGELOG.md
packages/docs/package-lock.json
packages/docs/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 7.8.6

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/docs/CHANGELOG.md
packages/docs/package-lock.json
packages/docs/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 8.0.2

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/docs/CHANGELOG.md
packages/docs/package-lock.json
packages/docs/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

Release 8.1.0

---

.github/CODEOWNERS
.github/workflows/assign-issues.yml

This PR removes me from the Codeowners file as well as the issue triage list.

chore: remove liam from codeowners and issue triage

---

docs/core/testing/usage-instructions.md

The original command does not exist.

docs(testing): add correct command

---

.github/workflows/assign-issues.yml

---------
- Removes me from being auto-assigned to issue triage
- I was already removed from CODEOWNERS, so no changes are needed there.

chore(internal): remove sean from issue triage

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
core/README.md
packages/vue-router/README.md
packages/vue/README.md

---------
The bug report points to an old location of the Contributing doc.
- Updated the link to point to the new location under the docs folder.
N/A

docs(many): update Contributing links

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/docs/CHANGELOG.md
packages/docs/package-lock.json
packages/docs/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

merge release-8.1.2

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/docs/CHANGELOG.md
packages/docs/package-lock.json
packages/docs/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

merge release-8.1.3

---

.github/workflows/assign-issues.yml

- Add UI Component team members to the Ionic Framework team:
- joselrio,
- rugoncalves,
- BenOsodrac,
- JoaoFerreira-FrontEnd,
- OS-giulianasilva

chore(github): add new team members to auto-assign issue action

---

docs/core/testing/usage-instructions.md

---------
There is no documentation on how to use the input field in the screenshots GH actions.
- Added steps and examples on how to specify a component within screenshots GH actions.
N/A

docs(screenshots): add step for specific component testing

---

packages/vue/test/apps/vue3/package.json

---------
Vue input values cannot accept a string object without causing it's behavior to fail. This is happening because a change that happened through Vue.
- Vue released a fix, verified that fixes the issue, upgraded the version

chore(vue): unpin version

---

core/src/components/refresher/test/fullscreen/index.html

---------
The test page has the wrong title text.
- Updated the text to reflect the purpose of the page.
N/A

test(refresher): update test page fullscreen title

---

core/package-lock.json
core/package.json
lerna.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/package-lock.json
packages/angular/package.json
packages/docs/package-lock.json
packages/docs/package.json
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react-router/test/apps/reactrouter5/package-lock.json
packages/react/package-lock.json
packages/react/package.json
packages/react/test/apps/react17/package-lock.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

merge release-8.2.3

---

core/src/css/display.scss

---------
- Add new display-contents and display-flex classes.

feat(css): add new display classes

---

core/src/components/modal/modal.ionic.scss

---------
- Fixed the tokens used on background and text.
- [Ionic Custom Dialog](https://ionic-framework-git-rou-11900-ionic1.vercel.app/src/components/modal/test/custom-dialog?ionic:theme=ionic)

fix(modal): fix color tokens on ionic theme
