ionic-team/ionic-framework

.github/workflows/release.yml

JSDeliver caches resources for ~7 days: https://github.com/jsdelivr/jsdelivr#caching. This means that for up to 7 days after a release, the component playgrounds load an outdated version of Ionic. This is problematic with feature releases where the playgrounds for the new features will not work as an old version of Ionic is loaded.
- On successful release, a request will be made to JSDeliver to purge the JS and CSS files for the `6` and `latest` tags for …

ci(release): purge JSDelivr cache on release

---

core/src/css/core.scss

Issue URL: resolves #25688, resolves #25677
The issue was caused by this commit: https://github.com/ionic-team/ionic-framework/commit/a6f3ae67ab91ab95408ad425156167edc3570978
We targeted `ion-modal .ion-page` but did not consider that `.ion-page` is also used inside of `ion-nav`. As a result, this changed the styles for pages in `ion-nav` and broke page transitions.
We also considered just doing `ion-modal .ion-page`, but there is an existing issue where …

fix(nav): exclude nav from custom dialog

---

core/src/components/datetime/datetime.tsx

Sean noted that https://github.com/ionic-team/ionic-framework/actions/runs/2776107067 was failing due to an unrelated test. Upon further investigation it was determined that selecting today's date with `multiple="true"` does not work on the first click. 
When we call `setActiveParts` on clicking the day button, we pass in `isActive`. Presumably this was done to ensure that we can toggle dates: https://github.com/ionic-team/ionic-framework/blob/61e4ffe47f73 …

fix(datetime): selecting today with multiple date select now works

---

core/src/components/datetime/test/format.spec.ts
core/src/components/datetime/utils/format.ts
core/src/components/datetime/utils/parse.ts

When datetime is rendered initially, the time is formatted with a `tzOffset` of `0`. When the time is manipulated in the time overlay/picker, the `tzOffset` is applied (to the users timezone, i.e. `-240`) and incorrectly formats the displayed time.
Issue URL: #25693
- Removes the `tzOffset` when localizing the time for display
Dev-build: `6.2.1-dev.11659121131.15481a1f` ✅

fix(datetime): display time in user's timezone after selection

---

core/src/components/alert/alert-interface.ts
core/src/components/alert/alert.tsx
core/src/components/alert/test/basic/alert.e2e.ts
core/src/components/alert/test/basic/index.html

Currently Overlays like ActionSheets can accept a Promise for their button handlers to determinate if the overlay should be closed or not. Alert buttons currently don't have the option to do that.
Issue URL: closes #25700
- `await` the handler call to work with promises too
Reopening of #22518

feat(alert): accept Promise for button handler

---

packages/vue-router/src/router.ts
packages/vue/test-app/tests/unit/memory.spec.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25705
The current check did not account for tab values that are `undefined` initially.  As a result, the code was getting pushed into a block that should be only run when in tabs. We should clean this up in the future and converge on either `''` or `undefined`, but for now we can account for both with a false-y check.
- Ionic Vue Router correctly checks to see if a page is/is not in …

fix(vue): go back to correct view with memory history

---

core/src/components/picker-internal/picker-internal.scss

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25755
Safari has some rendering quirks with layers/compositing when using accelerated animations. As a result, the iOS modal animation was causing the picker internal's highlights to not be promoted to their own layers.
Causing a repaint was usually enough to "fix" the issue.
- Highlights are now promoted to their own layers
Note: I could not capture this in a Playwright screenshot. …

fix(datetime): highlights now show above content in modal

---

core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/basic/datetime.e2e.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25787
Hiding the datetime after opening the month/year picker causes the calendar grid to not scroll properly. This is because when re-showing the datetime, we attempt to scroll on the calendar body's scrollable area of 0px. The scrollable area is 0px because the month/year picker is still visible and the calendar body is hidden. As a result, when hiding the month/year picker the …

fix(datetime): close month/year picker when hidden

---

core/src/components/alert/alert.tsx
core/src/components/alert/test/a11y/alert.e2e.ts
core/src/components/alert/test/a11y/index.html

`ion-alert` throws Axe accessibility violations by default due to not having an `aria-label`.
Issue URL: N/A (internal ticket)
Default aria-label added, pulling from the alert's `header` (or `subHeader` if no header is defined) and falling back to simply `'Alert'` if needed. Devs can already define a custom aria-label using the `htmlAttributes` property when presenting the alert.

fix(alert): add default aria-label

---

core/src/components/breadcrumb/breadcrumb.tsx
core/src/components/breadcrumbs/test/breadcrumbs.spec.ts

Issue URL: N/A
The separator for breadcrumbs could be highlighted by narrators. These separators are only visual and do not provide any additional context regarding any of the breadcrumb items.
- All separators are now hidden from screen readers, including custom separators.

fix(breadcrumb): separator is not announced by narrators

---

packages/vue/src/components/IonRouterOutlet.ts
packages/vue/test-app/tests/unit/lifecycle.spec.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25784
When navigating to an inner tabs page (Tab1), the `currentMatchedRouteRef` is the route definition for the Tab1 page and `previousMatchedRouteRef` is `undefined`.  We then set `previousMatchedRouteRef` to  `currentMatchedRouteRef` so that we can have a reference to the last route that this outlet matched next time the `currentMatchedRouteRef` changes.
When navigating away from …

fix(vue): lifecycles now fire on tabs pages

---

packages/react-router/src/ReactRouter/StackManager.tsx
packages/react/src/routing/OutletPageManager.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25797
- If we are mounting an IonPage element on a view that already has a reference to the element, do not fire a new page transition. This ensures that only the initial IonPage registration causes a transition.
Dev build: `6.2.4-dev.11661268305.10458734`
Manually verified that this is fixed on React 18 and does not regress the list starter app on React 17.

fix(react): duplicate page transitions do not happen on react 18

---

core/src/components/modal/modal.tsx
core/src/components/modal/test/a11y/index.html
core/src/components/modal/test/a11y/modal.e2e.ts

Issue URL: N/A
During our discussions about https://github.com/ionic-team/ionic-framework/issues/23108 I realized that the `role` attribute could not be customized. Long term I think it would be best to move these attribute details to `.modal-wrapper` since that is where the actual modal content is, but that requires some broader focus trapping fixes first. As a result, I propose we move `role="dialog"` to the host for now and make it customizable. …

fix(modal): role attribute can be customized

---

BREAKING.md
core/src/utils/overlays.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25802
It looks like when dismissing an `alert` dialog with the Escape key, Firefox will dispatch a `keyup` event. This causes overlays in Ionic to also dismiss. Other browsers do not emit `keyup` when dismissing an `alert` with the Escape key.
This impacts Firefox (all platforms) and Chrome for Windows. Using `keydown` avoids this bug and better aligns our overlays with what the …

fix(overlays): dismiss on keydown to avoid chrome for windows and firefox bug

---

angular/src/directives/navigation/ion-router-outlet.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25813
- Adds the `mode` property to the list of `inputs` for the `ion-router-outlet` Angular component.

fix(angular): router outlet has mode property

---

BREAKING.md

Issue URL: N/A
As part of Ionic v7 we are updating our platform + browser support. This was already documented in https://github.com/ionic-team/ionic-docs/pull/2502, but we should also note this as a breaking change.
- Add an entry to the breaking changes document for browser, mobile platform, and JS framework support in Ionic 7

docs(breaking): add note on platform support for v7

---

core/src/components/datetime/datetime.tsx

This fixes an issue with the Datetime component where in certain
circumstances a `ref` on an element rendered by the datetime component
would end up erroneously set to `null`, necessitating a yucky
`document.querySelector` based workaround.
The issue arises because of how Stencil's virtual DOM implementation
handles reconciling the children of old and new nodes, and in particular
how it deals with situations in which the order of children changes but
some of the nodes are conserved.
The way this was affecting the datetime component was that in certain
circumstances a method which returns a `<div>` with a `ref` would change
position in the children of another node. In particular, this can happen
if the `presentation` prop changes, causing the return value of the
`renderDatetime` function …

refactor(datetime): use key to preserve calendar body ref node

---

core/src/components/action-sheet/action-sheet.tsx
core/src/components/action-sheet/test/a11y/action-sheet.e2e.ts
core/src/components/action-sheet/test/a11y/index.html

`ion-action-sheet` does not have an `aria-label` or `aria-labelledby` attribute, which his required for the `dialog` role.
Issue URL: N/A (internal ticket)
- If the `header` property is defined, `aria-labelledby` is set to point to that element.
- Note that a fallback to `subHeader` is not included, because if `header` isn't defined, the `subHeader` doesn't render either way due to it being wrapped in the header element.
- Duplicate `role="dialog"` …

fix(action-sheet): add aria-labelledby

---

core/src/components/accordion/test/a11y/accordion.e2e.ts

Issue URL: N/A
Accordion related tests were failing intermittently on Safari. Scroll assist adds a cloned input inside of `ion-input` as part of its adjustment work, and sometimes that would be in the DOM long enough for playwright to pick it up. This led to errors such as the following:
```
expect.toBeFocused: Error: strict mode violation: "#address1 input" resolved to 2 elements:
1) <input type="text" placeholder="" autocorrect="off" aut…/> aka …
```

test(accordion): avoid scroll assist cloned input

---

core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/minmax/datetime.e2e.ts
core/src/components/datetime/test/parse.spec.ts
core/src/components/datetime/utils/parse.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25833
- On component load, we only warn about out of bounds values if the `value` prop was actually set.
- We no longer warn about out of bounds values if we are defaulting to today's date as that date will then be moved in bounds below. The warning is there to inform developers that they set an out of bounds value.

fix(datetime): only log out of bounds warning if value set

---

core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/minmax/datetime.e2e.ts
core/src/utils/test/playwright/matchers/index.ts
core/src/utils/test/playwright/matchers/toHaveReceivedEventTimes.ts
core/src/utils/test/playwright/testExpect.d.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25752
- Scroll position is now corrected in `componentOnRender` when using `min`.

fix(datetime): month grid no longer loops on ios

---

angular/test/base/e2e/src/tabs.spec.ts

Issue URL: N/A The Angular E2E `should navigate deep then go home` test is flaky. The reason is that we try to check the active page title immediately after popping nested tabs pages off the stack: https://github.com/ionic-team/ionic-framework/blob/725b13fa60775dc9f9c3491cb545c70a5a9162eb/angular/test/base/e2e/src/tabs.spec.ts#L117-L118
Sometimes Cypress is able to get the active page title before the nested pages have been removed from the DOM. As a …

test(angular): tabs sibling page test is no longer flaky

---

angular/test/base/e2e/src/tabs.spec.ts

Issue URL: N/A I missed a few other instances where we need to wait for tab switches to complete in order to avoid flakiness.
https://github.com/ionic-team/ionic-framework/runs/8275454426?check_suite_focus=true
https://github.com/ionic-team/ionic-framework/runs/8275447398?check_suite_focus=true
- Both "navigate deep" tests have logic built in to wait for tab switches to complete before proceeding with checks.

test(angular): wait for all tab switches in tests

---

BREAKING.md
angular/src/directives/proxies.ts
core/src/components.d.ts
core/src/components/accordion-group/accordion-group.tsx
core/src/components/accordion/accordion.tsx
core/src/components/accordion/test/basic/accordion.e2e.ts
packages/vue/src/proxies.ts

Issue URL: N/A Internal ticket
- `ionChange` will now fire as a result of user-generated actions only.
- The one exception is when an app passes an array of values to a single-select accordion. When that happens, we set the `value` to be the first item in the array and re-emit `ionChange`.
`ionChange` will no longer be emitted when the `value` of `ion-accordion-group` is modified externally. `ionChange` will only be emitted from user committed changes, …

feat(accordion): ionChange will only emit from user committed changes

---

BREAKING.md
angular/src/directives/proxies.ts
angular/test/base/e2e/src/inputs.spec.ts
angular/test/base/src/app/inputs/inputs.component.html
core/src/components.d.ts
core/src/components/checkbox/checkbox.tsx
core/src/components/checkbox/test/basic/checkbox.e2e.ts
core/src/components/datetime/test/color/datetime.e2e.ts

Issue URL: N/A internal ticket
- `ion-checkbox` now emits `ionChange` whenever the native `change` event fires on `<input type="checkbox" />`.
`ionChange` is no longer emitted when the `checked` property of `ion-checkbox` is modified externally. `ionChange` is only emitted from user committed changes, such as clicking or tapping the checkbox.

feat(checkbox): ionChange fires on user interaction

---

core/src/utils/overlays.ts
core/src/utils/test/overlays/overlays.e2e.ts

Issue URL: N/A internal ticket
When a hidden interactive if the first element, the focus trapping module tries to focus that element on tab. Since the element is hidden and not focusable, focus can escape from the overlay.
- Focus trapping excludes elements hidden with the `hidden` attribute.

fix(overlays): focus trapping no longer includes hidden elements

---

BREAKING.md
core/src/components.d.ts
core/src/components/input/input.tsx

The `debounce` property on `ion-input` controls the delay in milliseconds when emitting `ionChange`.
Issue URL: N/A
- The `debounce` property applies to `ionInput` instead of `ionChange`
`debounce` is not applicable to `ionChange` with the change in behavior to emit `ionChange` from user committed actions. Developers should no longer use `debounce` to delay `ionChange` event emission.

feat(input): debounce controls the timing to delay the ionInput event

---

core/src/components/datetime-button/datetime-button.tsx
core/src/components/datetime-button/test/multiple/datetime-button.e2e.ts
core/src/components/datetime-button/test/multiple/index.html

- Datetime button now supports datetimes with `multiple="true"`.

feat(datetime-button): support multiple date selection

---

core/src/components/input/test/masking/input.e2e.ts

The test is flaky again when trying to sync `feature-7.0`: https://github.com/ionic-team/ionic-framework/actions/runs/3160231835/jobs/5144478692
- I added some delays to typing each character to help reduce flakiness. Playwright calls this out as a way of simulating a user typing: https://playwright.dev/docs/api/class-keyboard#keyboard-type

test(input): reduce masking test flakiness

---

BREAKING.md
core/src/components.d.ts
core/src/components/accordion-group/accordion-group.tsx
core/src/components/accordion/test/accordion.spec.ts
core/src/components/accordion/test/basic/accordion.e2e.ts

⚠️ Be sure to set commit message to the breaking change note when merging 
Issue URL: N/A
As per our `ionChange` revision requirements, components should avoid updating `value` internally unless by a user-committed action.
- Accordion group no longer updates the `value` property internally when passed an incorrect value. It will now log a warning message to the console.

fix(accordion-group): do not adjust incorrect values

---

BREAKING.md
angular/src/directives/proxies.ts
angular/test/base/e2e/src/inputs.spec.ts
core/src/components.d.ts
core/src/components/toggle/test/basic/toggle.e2e.ts
core/src/components/toggle/toggle.tsx

`ion-toggle` will emit an `ionChange` event if the value of the `checked` property is changed programmatically.
Issue URL: N/A
`ionChange` is now only emitted from the user clicking or dragging the handle to toggle it.

feat(toggle): ionChange will only emit from user committed changes

---

core/src/components/modal/modal.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26108
The sheet modal dismiss behavior changed as a result of our strict-boolean-expressions refactor: https://github.com/ionic-team/ionic-framework/commit/ae6aa0cb8e158783c09adc2f64e607505be55a28#diff-fe05ef73704648b399bf1ae571ca7b507d02accd5a42ce8081bc9fd778c81ba9R707
In particular, this line changed: https://github.com/ionic-team/ionic-framework/blob/bbd6c9ae6cb69eca1847524cd17b19d …

fix(modal): sheet modal dismisses correctly

---

core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/multiple/datetime.e2e.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26116
The title formatter logic only checked if `activeParts` was an array, not if `multiple="true"`. As a result, when the `activeParts` variable was refactored to an array in https://github.com/ionic-team/ionic-framework/commit/0aee328b4b84d5668752e5ae0792334d0173c2bb, "0 days" started showing on single-select datetimes with no value.
This does not impact `ion-datetime-button` as …

fix(datetime): header renders correct date

---

angular/package-lock.json
angular/package.json
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/package-lock.json
packages/vue/package.json

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26137
Packages that depend on other Ionic packages currently use `^` which tells package managers to install the latest minor version of the package. This means that when downgrading a package, it is possible to still get the latest version of a dependency.
Example:
**package.json** for `@ionic/angular`:
```
"version": "6.3.0"
"dependencies": {
"@ionic/core": "^6.3.0"
}
```
When …

fix(dependencies): latest patch is installed

---

core/api.txt
core/src/components.d.ts
core/src/components/loading/loading.tsx
core/src/components/loading/test/isOpen/index.html
core/src/components/loading/test/isOpen/loading.e2e.ts
core/src/utils/framework-delegate.ts
core/src/utils/overlays.ts
packages/react/src/components/IonLoading.tsx
packages/react/test-app/tests/e2e/specs/overlay-components/IonLoading.cy.ts
packages/vue/src/components/Overlays.ts

`ion-loading` cannot be used inline. 
- `ion-loading` supports `isOpen` property to present and dismiss the loading indicator
- Framework delegate will skip cloning element to a parent when there are no CSS classes to append to the parent

feat(loading): isOpen presents and dismisses loading overlay

---

BREAKING.md
core/src/components/datetime-button/datetime-button.tsx
core/src/components/datetime/datetime-interface.ts
core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/basic/datetime.e2e.ts
core/src/components/datetime/test/format.spec.ts
core/src/components/datetime/test/minmax/datetime.e2e.ts
core/src/components/datetime/utils/format.ts
core/src/components/datetime/utils/manipulation.ts
core/src/components/datetime/utils/parse.ts

⚠️ Add breaking change to commit message on merge.
Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25577
Datetime incorrectly reports the timezone information when the `value` property is updated.
- Datetime now follows the [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) implementation and does not return the time zone information.
- All timezone information has been removed …

fix(datetime): do not report timezone in ionChange

---

core/src/components/datetime/test/prefer-wheel/datetime.e2e.ts

Issue URL: N/A
The affected test was selecting the first day of the current month in order to check that `ionChange` is emitted. Since today is November 1st, this test broke 😄 
Example test run: https://github.com/ionic-team/ionic-framework/actions/runs/3370282282/jobs/5591073359
- The date is now mocked so that the 1st day of the month is never selected initially.

test(datetime): fix ionChange wheel test

---

packages/vue/scripts/build-web-types.js

When moving the docs and usage examples out of the `ionic-framework` repository to `ionic-docs`, the script that generates web-types for Vue broke. It no longer had the `.usage.vue` property in the generated `docs.json`, resulting in no component types being generated.
Issue URL: #26198
- Web-types are generated for all components, unless manually excluded in the `excludeComponents` array (within the script file for now)
- Excluded components are loosely …

fix(vue): generate web-types for components

---

core/src/components/datetime/test/data.spec.ts
core/src/components/datetime/utils/data.ts

When the `min` was for 11am and the `max` was for 12pm, the "pm" day period option was not available for selection. 
Issue URL: https://github.com/ionic-team/ionic-framework/issues/26216
- Day periods render correctly based on min/max
Dev-build: `6.3.5-dev.11667857244.18413739`

fix(datetime): day periods render correctly based on min/max

---

packages/react/src/components/createInlineOverlayComponent.tsx
packages/react/test-app/tests/e2e/specs/overlay-components/KeepContentsMounted.cy.ts

Presenting an inline overlay multiple times in React will hide the overlay contents on the second+ open.
Issue URL: #26253
- Adds the `ion-delegate-host` class to the React wrapper, so the additional element is not created
- Inline overlay contents are consistently displayed when presenting
Testing these changes:
- Run the React test-app
- Visit the Keep Contents Mounted test suite
- Present a modal
- Observe: Contents load/display
- Dismiss modal
- …

fix(react): inline overlays display contents consistently

---

angular/src/directives/overlays/popover.ts
core/src/components.d.ts
core/src/components/popover/popover.tsx
core/src/components/popover/utils.ts

Inline popovers with a width of `auto` or `fit-content` are incorrectly positioned when the popover is presented. 
This bug would apply to _any_ enter animation for overlays that relies on the dimensions of the content inside of the overlay, to position the overlay during the transition.
Issue URL: #24716
- Inline popovers with a width of `auto` or `fit-content` are positioned correctly when presented.
- `AnimationBuilder` can be resolved asynchronously, …

fix(popover): inline popover positioning with fit-content or auto width

---

core/src/components/input/test/a11y/input.e2e.ts

The new standalone input has an a11y page, but it does not run automated Axe checks.
- The input component now runs automated Axe checks.

test(input): add missing a11y test

---

.github/workflows/nightly.yml

A couple things I missed in my previous nightly build PR:
1. The version was not passed to `lerna version` correctl. As a result, lerna tried to create the wrong version.
2. The nightly build branch was not created. As a result, lerna tried to push to the wrong branch.
- A nightly branch is now created on run and then cleaned up after the version is created
- The correct nightly version is passed to `lerna version`

chore(ci): clean up nightly builds

---

core/src/components/range/test/range-events.e2e.ts

The gesture-based range tests are very flaky: https://github.com/ionic-team/ionic-framework/actions/runs/3518210747/jobs/5897125963#step:11:1158
At the moment we do not have a good solution for gestures in Playwright: https://github.com/microsoft/playwright/issues/2903
- Disabled the dragging test for ion-range

test(range): disable gesture test

---

BREAKING.md
core/src/components/picker/picker-interface.ts

The `refresh` method is private but was accidentally exposed on a public interface: https://github.com/ionic-team/ionic-framework/issues/25631
- The `refresh` key is no longer exposed on `PickerColumn`

refactor(picker): remove refresh key

---

core/src/components/button/button.tsx
core/src/components/button/test/basic/button.e2e.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25886
- Button checks to see if `fill` is both `null` or `undefined` to avoid the Stencil bug.

fix(button): fill can be set to undefined

---

angular/src/directives/proxies-list.ts
angular/src/directives/proxies.ts
angular/test/base/e2e/src/inline-overlays.spec.ts
angular/test/base/src/app/app-routing.module.ts
angular/test/base/src/app/overlays-inline/index.ts
angular/test/base/src/app/overlays-inline/overlays-inline-routing.module.ts
angular/test/base/src/app/overlays-inline/overlays-inline.component.html
angular/test/base/src/app/overlays-inline/overlays-inline.component.ts
angular/test/base/src/app/overlays-inline/overlays-inline.module.ts
core/stencil.config.ts

During IonPicker inline development I noticed that the Angular components for the other inline overlays were not exported.
- Angular components are now generated for inline overlays
- The e2e apps now test inline overlays

fix(angular): inline overlays are exported

---

.github/workflows/actions/publish-npm/action.yml
.github/workflows/release-ionic.yml

Using `--scope` causes other dependency packages to not be symlinked. For example, using `--scope @ionic/angular` will cause `@ionic/core` to not be symlinked in the angular package. As a result, framework packages do not necessarily build with the latest API information available to them.
This does not impact the contents of releases, but it does impact the ability to release a package if it tries to get a newer API from an older version of Ionic Core. I …

chore(ci): always bootstrap packages

---

core/src/components/input/input.scss
core/src/components/input/test/a11y/input.e2e.ts

When testing the new input changes in an app I notices that the form validation colors were applying to the visible label text:
This likely happened when I made the switch to using a `<label>` to wrap the entire container instead of just using it on the label text. The Playwright diff threshold was likely too high to catch this small of a change.
- The form validation color no longer applies to the input text color.
- I changed the a11y tests to run for …

fix(input): highlight color does not apply to text

---

core/src/components/datetime/datetime.scss

Issue URL: N/A This code was added to account for a pre-iOS 14 bug where pseudo elements in CSS grid were not positioned correctly.
- The pre-iOS 14 fix has been removed.

refactor(datetime): remove ios 13 calendar day fix

---

core/src/utils/test/overlays/overlays.e2e.ts

The `focus()` method needs to run (and be rendered in the browser) before the modal is full presented otherwise the test will fail. This kind of precise timing test is not a good fit for CI.
- Removed the overlay focus test
At the moment I'm not aware of a better way to check this, which is why I removed it instead of skipping it.

test(overlays): remove broken test

---

core/src/components/input/input.scss

The scale transformation is set statically to `0.75`.
Issue URL: N/A
- The scale transformation uses the `$input-floating-label-scale` variable (which currently defaults to `0.75`)

refactor(input): label text wrapper scale uses SASS variable

---

.github/workflows/actions/build-core-stencil-eval/action.yml
.github/workflows/actions/build-core/action.yml
.github/workflows/actions/test-core-screenshot/action.yml

The `@ionic/core` source (including all screenshots) are being stored as a build artifact even though it is not needed anywhere. The e2e tests consume it, but they don't need to because they already clone the core repo.
This slows the build step down and delays any other tests from running.
- the core build step no longer stores the source code as an artifact
- the e2e tests no longer download the source code artifact

test(ci): do not store Ionic Core source as artifact

---

core/src/utils/forms/form-controller.ts

Sean recommended that I pull our the recent form controller changes since the changes are currently in other feature branches: https://github.com/ionic-team/ionic-framework/pull/26470#discussion_r1046570708
- Updates the form controller to account for elements with named  and unnamed label slots.

chore(forms): add revision legacy form detection

---

core/src/components/radio-group/test/basic/radio-group.e2e.ts

`toHaveClass` returns a promise. Since this did not await the promise, the test was flaky on CI.
- Added `await` to the `toHaveClass` assertions

test(radio-group): await toHaveClass assertion

---

core/.eslintrc.js
core/custom-rules/await-playwright-promise-assertion.js
core/custom-rules/index.js
core/custom-rules/no-component-on-ready-method.js
core/src/components/datetime/test/color/datetime.e2e.ts
core/src/components/radio-group/test/search/radio-group.e2e.ts

Many Playwright assertions return Promises. Not properly awaiting these asserts causes flakiness on CI: https://github.com/ionic-team/ionic-framework/pull/26490
However, ensuring that these awaits are added is a manual process and it is easy to miss.
- Add a custom ESLint rule which checks the used asserts against a known list of async Playwright asserts to see if any awaits were missed.
An example of this ESLint rule in action can be found here: …

chore(eslint): add async playwright assert rule

---

core/src/components.d.ts
core/src/components/input/input.tsx

IonInput's `setFocus()` method does not work when called from Angular's `ngAfterViewInit()` lifecycle hook because of how the Ionic Angular components render their contents.  This behavior was not documented alongside the `setFocus()` method.
Issue URL: https://github.com/ionic-team/ionic-framework/issues/26474
The behavior is now documented, with a recommendation to use Ionic's `ionViewDidEnter()` lifecycle method instead.

docs(input): update setFocus description

---

core/src/components/item-sliding/test/basic/item-sliding.e2e.ts

This item sliding test relies on gestures to work. Gestures are currently flaky on CI.
- Disabled the item sliding test

test(item-sliding): skip flaky test

---

core/src/components/datetime/test/locale/datetime.e2e.ts
core/src/components/datetime/test/prefer-wheel/datetime.e2e.ts
core/src/components/datetime/test/presentation/index.html

Certain datetime tests are failing due to the year/month changing: https://github.com/ionic-team/ionic-framework/actions/runs/3833153770
- Affected tests either set a `max` or mock the date so they do not fail every time the year changes.

test(datetime): resolve flaky tests as year changes

---

core/src/components/radio-group/radio-group.tsx

This converts a multiline comment (like `/**...*/`) above the `RadioGroup` component class to be a series of `//` comments instead. This is done to prevent the comment from being accidentally recognized as a JSDoc comment for the class when a Stencil version incorporating this change is installed:
https://github.com/ionic-team/stencil/commit/2e4b1fcdc0b3fd41928d27cf9ee525a15b02d617
If you build and install Stencil from `main` you'll see a change like this …

chore(jsdoc): move comment on RadioGroup

---

core/src/components/modal/modal-interface.ts

The new changes in Ionic 6.4.0 for `canDismiss` to accept `role` and `data` is not reflected on the `ModalOptions` interface.
Issue URL: #26544 
- Adds the missing type definition for `canDismiss` to the `ModalOptions` interface
Related docs PR: https://github.com/ionic-team/ionic-docs/pull/2686

fix(modal): canDismiss type with data and role

---

core/src/components/picker-column-internal/picker-column-internal.tsx

Blurring the picker quickly in certain browsers, such as Firefox, can result in an error being thrown in the console:
```
Uncaught TypeError: activeElement is null
```
Issue URL: #26559
- No exception is thrown when blurring the picker
- Fixes the type casting for `elementFromPoint` to include the potential `null` state

fix(picker-column-internal): blurring picker does not throw error

---

core/src/interface.d.ts

I'd like to import `NavigationHookResult` from @ionic/core. In my case, to generate a typings file that allows SvelteKit developers to have a typings file consistent with the core-package. Now I am adding the `NavigationHookResult` type definition myself in the svelteHTML typings file. Because `NavigationHookResult` is not re-exported to the developer surface.
This change allows me to import it and uses the same pattern for exporting as all other types
No …

feat(router): export hook interfaces 

---

.stackblitz/codeflow.json

Currently we do not use Codeflow. Codeflow would enable us to quickly run, test and verify changes on pull requests, without having to checkout different branches and re-run the Stencil app locally.
By default, once installed, the Codeflow bot will comment on both issues and pull requests. The value of commenting on issues is to have a quick environment to verify against the latest, but that is out of scope at the moment.
Additional information around …

chore(codeflow): disable codeflow on issues

---

core/src/components/tab-button/tab-button.tsx
core/src/components/tab-button/test/a11y/index.html
core/src/components/tab-button/test/a11y/tab-button.e2e.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/23332
This is the same issue as https://github.com/ionic-team/ionic-framework/pull/26575.
- aria-selected and role states on `ion-tab-button` have been moved to the native `<a>` inside of the Shadow DOM.
- aria-disabled has been added so screen readers can indicate that the tab button is disabled (This is a bug I discovered while fixing the original issue)
- `ariaLabel` on …

fix(tab-button): nested interactives are not rendered

---

core/src/components.d.ts
core/src/components/segment-button/segment-button.tsx
core/src/components/segment/segment.tsx
core/src/components/segment/test/a11y/index.html
core/src/components/segment/test/a11y/screen-readers.md
core/src/components/segment/test/a11y/segment.e2e.ts

Axe test warns of nested interactive in `ion-segment-button`. This is happening because `ion-segment-button` has `role="tab"` on the host element but then renders a `<button>` in its Shadow DOM. Axe thinks that both the host and the nested button are interactive.
This was added in https://github.com/ionic-team/ionic-framework/pull/23145 before Axe warned about nested interactive (so this was never caught). The original fix was …

fix(segment): nested interactives are not rendered

---

core/src/components/checkbox/checkbox.scss
core/src/components/input/input.scss
core/src/components/radio/radio.scss
core/src/components/range/range.scss
core/src/components/select/select.scss
core/src/components/toggle/toggle.scss

Issue URL: https://github.com/ionic-team/ionic-docs/pull/2698#discussion_r1067231054
Amanda noted that the component height was taking up the full height of the `ion-content` container. This was caused by us adding `height: 100%` to the component `.*-wrapper` elements.
- Changed the height to `inherit` instead of `100%`. This will allow developers to set the `height` on the host of the component.

fix(many): component wrappers inherit height

---

core/api.txt
core/src/components/breadcrumbs/breadcrumbs.scss

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26625
The `--color` and `--background` vars are documented as being available for `ion-breadcrumbs`. However, these APIs were not implemented in the final release of the component. The APIs were implemented during development but were later removed as they were not necessary (`color` is set on the `ion-breadcrumb` instead and `background` works as it normally does with …

docs(breadcrumb): remove documentation for nonexistent APIs

---

core/src/components/modal/modal.tsx
core/src/components/popover/popover.tsx

Note: I will put up a separate patch for v7 since how triggers are consumed has changed slightly.
There is some developer confusion about how the trigger prop works. See https://github.com/ionic-team/ionic-framework/issues/26648
- Both modal and popover have been updated to a) return early in `configureTriggerInteraction` if no `trigger` prop is set and b) warn if a trigger prop is set but the element was not found in the DOM.

fix(modal, popover): warn if trigger element was not found

---

core/src/components/select/select.tsx
core/src/components/select/test/basic/select.e2e.ts

We had previously disabled the `ion-select` popover focus test on Firefox because it did not work. Upon further investigation, this appears to be a Firefox bug where `delegatesFocus` does not work correctly when manually focusing an element. This appears to be somewhat related to https://github.com/ionic-team/ionic-framework/issues/25070.
As a result of this, the `ion-radio` or `ion-checkbox` was never getting focused only on …

fix(select): focusing item works in firefox

---

core/src/components/select/select.ios.scss
core/src/components/select/select.md.scss
core/src/components/select/select.scss
core/src/components/select/select.tsx

While working on the documentation I discovered that the select was missing `width: 100%` which allows it to take up the full line. This was due to old code that only applied with `.in-item`. 
- Updated select to align with the new `ion-input` code to apply `width: 100%` and remove the `.in-item` code. (The height: 100% should not be needed when inside of ion-item)
- I also added TODOs to remove the legacy syntax

fix(select): modern component takes up full line

---

core/src/components/select/select.tsx
core/src/components/select/test/async/index.html
core/src/components/select/test/async/select.e2e.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/19324
Updating IonSelectOptions does not re-render the IonSelect component (these are not props and ion-select is not using `<slot>`). As a result, the selected text of an IonSelect does not update. I fixed this issue back in 2019 in https://github.com/ionic-team/ionic-framework/commit/1c9c18b5eaa5807b802829586ec5fffb53f0d345. However, this behavior regressed in …

fix(select): setting options async updates rendered text

---

core/src/utils/test/overlays/overlays.e2e.ts

I haven't been able to get this test to fail, either locally or on CI despite many tries, so I've just re-enabled it. It's possible a recent Playwright update fixed the issue that was causing the failure. We can always add the `skip` back if needed later.

test(overlays): re-enable hidden focusable element test

---

.gitignore
angular/scripts/sync.sh
angular/test/base/scripts/sync.sh
packages/react-router/test-app/scripts/sync.sh
packages/react/test-app/scripts/sync.sh
packages/vue-router/scripts/sync.sh
packages/vue/scripts/sync.sh
packages/vue/test/base/scripts/sync.sh

Our sync scripts only copy Ionic dependencies to E2E test applications. This resulted in Stencil Nightly Builds beginning to fail (https://github.com/ionic-team/ionic-framework/actions/runs/3899619536/jobs/6659530912). This was happening because the version of Stencil that Ionic Core required was not installed in the test application. Instead, an older version was installed. Versions of Ionic built with the newer version of Stencil expect a `setNonce` API …

chore(ci): sync scripts now account for dependencies

---

packages/vue/src/framework-delegate.ts
packages/vue/test/base/src/router/index.ts
packages/vue/test/base/src/views/Components.vue
packages/vue/test/base/src/views/Home.vue
packages/vue/test/base/src/views/Select.vue
packages/vue/test/base/tests/e2e/specs/select.cy.js

Developers using Vue can run into an error when using an `ion-select` that presents a popover of options. The Vue delegate was incorrectly assuming that a component instance would always be passed as the argument to `attachViewToDom`.
This is not the case for `ion-select`, where a string of the tag name is used: https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/select/select.tsx#L414
Issue URL: …

fix(vue): cache attached view reference

---

core/src/components/popover/popover.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26704
- Temporarily removes the TSConfig path usage until this issue is resolved in Stencil.

fix(popover): resolve import warning in stencil apps

---

BREAKING.md
core/api.txt
core/src/components/range/range.tsx
core/src/components/range/test/range.spec.ts

Range defaults the `name` property to the empty string which does not align with the other form components. I also noticed that the example usage in the deprecation message is wrong -- it should pass a label into the named slot not the default slot.
- `name` property defaults to `ion-r-${rangeIds++}`.
- Warning message has correct usage
- Added tests

fix(range): assign auto increment id by default

---

core/src/css/core.scss

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26745
We used a complex `:not` selector to fix an issue noted in https://github.com/ionic-team/ionic-framework/pull/25689. The better solution was to use `ion-modal > .ion-page`. However, at the time of #25689 there was a bug where `.ion-page` was mounted multiple times with inline modals in Ionic Angular. This bug no longer reproduces in the Angular playgrounds: …

fix(modal): dialog styles work on old chrome versions

---

core/src/components/checkbox/checkbox.tsx
core/src/components/radio/radio.tsx

resolves https://github.com/ionic-team/ionic-framework/issues/26769
Rendering the label text before a checkbox or radio causes VoiceOver to read the label twice (once when focusing the label, then once when focusing the control)
This does not impact v6 because these components use `aria-label` instead of associating the control with a visible text node.
- Render the hidden input before the label, bypassing this bug.

fix(checkbox, radio): label is announced once on ios

---

angular/src/directives/proxies.ts
core/api.txt
core/src/components.d.ts
core/src/components/textarea/textarea.tsx
packages/vue/src/proxies.ts

Issue URL: N/A
During development I noticed that textarea does not have the `legacy` property. This means developers are unable to forcibly opt-in to the legacy syntax.
- Added `legacy` property to `ion-textarea`

feat(textarea): add legacy property

---

core/src/utils/forms/form-controller.ts

Ken noted that the legacy deprecation message was being logged incorrectly when running Angular unit tests. This was happening because the legacy control check was happening before any slotted content (i.e. a label in `ion-toggle`) was available in the DOM. As a result, the form controller incorrectly thought the control instance was using the legacy syntax.
- Delayed the legacy control check until the first time `hasLegacyControl` is called as opposed to …

fix(form): legacy deprecation is logged correctly

---

core/src/components/content/content.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26743
Rotating the device can cause safe area values to change. This means that the fullscreen values on ion-content, --offset-top and --offset-bottom, can be invalidated. We do not listen for these device orientation changes, so blank space can sometimes appear above headers or below footers.
- Adds a throttled `resize` event listener that calls the `this.resize()` method to …

fix(content): fullscreen works when rotating device

---

core/src/components/picker-column/picker-column.tsx
core/src/components/picker-column/test/picker-column-aria.spec.tsx
core/src/components/picker-column/test/picker-column.spec.tsx
core/src/components/picker/picker-interface.ts

Developers cannot assign an `aria-label` to the individual button items in a picker column.
Issue URL: 
- Developers can optionally assign an `ariaLabel` to a picker column option, to assign the `aria-label` to the rendered button.
Note: Stencil has something strange happening with the spec tests. Since the picker column uses timeouts, you will receive an exception if the tests are located in the same file. The issue doesn't occur if you place the spec …

feat(picker-column): assign custom aria-labels to column options

---

core/src/components/toast/test/basic/toast.e2e.ts

Running subsequent builds of Ionic yields this error:
```shell
TypeScript: ./src/components/toast/test/basic/toast.e2e.ts:40:29
Property 'toHaveScreenshot' does not exist on type
'MakeMatchers<void, E2EPage | Locator>'.Property
'toHaveScreenshot' does not exist on type 'Matchers<...> &
PlaywrightTest.Matchers<...> & { not: MakeMatchers<void, E2EPage
| Locator>; resolves: MakeMatchers<...>; rejects:
MakeMatchers<...>; } & SnapshotAssertions'.
L39:    const …
```

test(toast): toHaveScreenshot signature is correct

---

core/src/utils/sanitization/index.ts
core/src/utils/sanitization/test/sanitization.spec.ts

We received a report about 3 XSS attack vectors:
1. `onload` is fired in Chrome when the untrusted string is appended to the document fragment. Even though we later remove the `onload` attribute, Chrome has already executed the code.
2. `javascript:` code can be executed by adding special characters to the `javascript:` string. For example, adding `java&Tab;script:` is still interpreted by the browser as `javascript:`.
3. Sanitizer is susceptible to DOM …

fix(sanitizer): improve reliability of sanitizer

---

core/src/components/checkbox/checkbox.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/25740
`aria-hidden` was originally added to the  host of `ion-checkbox` in https://github.com/ionic-team/ionic-framework/commit/7214a8401b709e1353155304cf6e9f97b2b4d294. This was done to work around some older iOS/VoiceOver quirks. However, it is no longer needed with the new checkbox syntax. I also discovered that the checked state was not being announced correctly because we never …

fix(checkbox): screen readers announce state correctly

---

core/package-lock.json
core/package.json

The existing version of `@stencil/sass` uses a version of Sass that is [almost a year and a half old](https://github.com/sass/dart-sass/releases/tag/1.42.1)
Issue URL:  N/A
this commit increments the version of `@stencil/sass` used by the ionic framework to include a version of the package that uses sass v1.58.3
I'm marking this PR as introducing a major change as we're bumping a core library to a new major version. However, I believe we have minimized …

chore(sass): upgrade sass, @stencil-sass

---

.github/workflows/stencil-eval.yml

Debugging this workflow requires opening a new PR, even if it fails due to a temporal issue (e.g. a flaky test)
Issue URL: 
this commit adds the `workflow_dispatch` event to trigger a stencil
nightly build workflow. this is being done to make it easier to debug the
nightly stencil build, by allowing us to invoke it without opening a pr
against the framework repo.
this commit also renames the 'build-core' job to
'build-core-with-stencil-eval', to help …

refactor(ci): allow manual 'stencil nightly' builds 

---

core/src/components/checkbox/checkbox.tsx
core/src/components/input/input.tsx
core/src/components/radio/radio.tsx
core/src/components/range/range.tsx
core/src/components/select/select.tsx
core/src/components/textarea/textarea.tsx
core/src/components/toggle/toggle.tsx

Developers have noted that the form control deprecation warning is confusing: https://github.com/ionic-team/ionic-framework/issues/26829
This is because we assume devs always use `ion-label`. However, devs could use `<ion-select>` without a label and they would still get the deprecation warning. The deprecation warning should be logged, but the reason we give for why it is logged is confusing since it assumes the presence of `ion-label`. 
Additionally, …

refactor(many): clarify deprecation warning

---

core/src/components/content/content.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26844
I did not account for the case where `ion-content` was active but not visible. This caused the fix in https://github.com/ionic-team/ionic-framework/commit/7b879fec3d30b61c00faad035698ff643afaa78e to not work correctly for non-active tabs.
- `this.resize()` only fires on the `resize` event if the content is visible

fix(content): fullscreen values are recomputed on visible content

---

core/src/components/modal/modal.tsx

Part of https://github.com/ionic-team/ionic-framework/issues/26833
The keyboard listener is added after the transition completes. This means that if you present and dismiss a modal quickly, the dismiss method will run before the keyboard listener is added. This is because the dismiss method only waits for the transition to finish before proceeding. As a result, the keyboard listener is never removed.
- Updated the present method to create the keyboard …

fix(modal): keyboard listener removed on dismiss

---

core/src/utils/overlays-interface.ts
core/src/utils/overlays.ts

Part of https://github.com/ionic-team/ionic-framework/issues/26833
Our focus trapping util stores the last element that was focused in `overlayEl.lastFocus`. However, this is never cleared when the overlay is dismissed. This results in the overlay keeping a strong reference to some other element. `lastFocus` is only utilized while the overlay is presented, so we should clear it on dismiss.
- `lastFocus` is cleared when the overlay is dismissed.

fix(overlays): focus trap refs cleared on dismiss

---

core/src/components/datetime/test/presentation/datetime.e2e.ts

This test suite was previously flaky and was skipped as a result: https://github.com/ionic-team/ionic-framework/actions/runs/3652722081/jobs/6171464242
Made a few changes:
- Skipped the test on RTL mode and MD mode. This test behavior does not differ between configurations.
- Updated the fixture to initialize the page with the starting value instead of updating the value mid test and waiting. This significantly improves the performance of the test.
- The …

test(datetime): fix flaky test

---

core/package-lock.json
core/src/components/ripple-effect/test/basic/ripple-effect.e2e.ts
core/src/components/tab-button/test/a11y/tab-button.e2e.ts

I am getting the following TypeScript error
```
TypeScript: ./src/components/accordion/test/standalone/accordion.e2e.ts:9:44
Type 'Page & E2EPage' is not assignable to type 'Page'.
L9:      const results = await new AxeBuilder({ page }).analyze();
```
It looks like Playwright and Axe are using different `playwright-core` versions:  
```
@ionic/core@6.6.0 /Users/liamdebeasi/Ionic/ionic/core
├─┬ @axe-core/playwright@4.6.0
│ └─┬ playwright@1.29.2
│   └── …
```

chore(tests): update tests and deps for playwright

---

core/src/components/slides/IonicSlides.ts

Repo/branch for testing: https://github.com/amandaejohnston/sandbox-ionic-angular/tree/swiper-migration-testing
When using the `IonicSlides` module with Swiper Element (https://swiperjs.com/element) and setting `autoplay` to `true`, a conflict occurs that leads to the slider flipping wildly between slides:
https://user-images.githubusercontent.com/90629384/223832678-21eaf2f2-1903-4268-af99-49a0d3084275.mp4
Issue URL: N/A
`autoplay` removed from the …

fix(IonicSlides): remove unnecessary autoplay option

---

core/src/components/radio/radio.tsx
core/src/components/radio/test/radio.spec.ts

If a radio initializes with a `value` that does not match the parent radio group `value` but then has its value updated to match the parent radio group value, the checked state does not update. This is because we only run `this.updateState` on `connectedCallback` and whenever the value of the parent radio group changes.
```html
<ion-radio-group value="a">
<ion-radio value="other-value"></ion-radio>
</ion-radio-group>
```
Using …

fix(radio): checked state is updated when value changes

---

core/src/components/input/test/input.spec.ts
core/src/components/textarea/test/textarea.spec.ts
core/src/components/textarea/textarea.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/26944
Input inherits tabindex, but textarea does not.
- Added tests
- Textarea now inherits tabindex

fix(textarea): inherit tabindex to inner textarea

---

core/src/components/segment/test/a11y/segment.e2e.ts

The segment focus test is occasionally flaky: https://github.com/ionic-team/ionic-framework/actions/runs/4405347963/jobs/7716168450
- I tried to see if checking the native `button` focus state (rather than `ion-segment-button` which isn't actually a semantic button) resolves the issue, but it did not https://github.com/ionic-team/ionic-framework/actions/runs/4409151360/jobs/7725137802. I ended up skipping the test and creating a ticket in our backlog.

test(segment): skip flaky test

---

core/src/components/segment/segment.tsx
core/src/components/segment/test/segment-events.e2e.ts

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/27002
The `onClick` listener checks to see if the currently checked `ion-segment-button` is different than the `ion-segment-button` that was clicked in order to determine if it needs to fire `ionChange`: https://github.com/ionic-team/ionic-framework/blob/79ba8816f4d073ba553df58f06b53ee83705aef7/core/src/components/segment/segment.tsx#L466
We determine the current button by looking at …

fix(segment): change events fires when clicking

---

BREAKING.md
core/src/components/alert/test/alert.spec.ts
core/src/components/alert/test/basic/index.html
core/src/components/infinite-scroll-content/test/infinite-scroll-content.spec.ts
core/src/components/loading/test/basic/index.html
core/src/components/loading/test/loading.spec.ts
core/src/components/refresher-content/test/refresher-content.spec.ts
core/src/components/toast/test/basic/index.html
core/src/components/toast/test/toast.spec.ts
core/src/utils/config.ts

As per the `innerHTMLTemplatesEnabled` design doc, this flag should default to `false` on Ionic 7 to de-risk the use of `innerHTML` functionality in Ionic. This change requires developers to opt-in to dangerously setting `innerHTML` content inside of Ionic components. As a result of this change (and combined with documentation published on our site), developers should be more informed of the risks of using `innerHTML` as well as the need for using a …

fix(many): innerHTML is disabled by default

---

core/api.txt
core/src/components/breadcrumbs/breadcrumbs.tsx
packages/vue/test/base/src/router/index.ts
packages/vue/test/base/src/views/Breadcrumbs.vue
packages/vue/test/base/src/views/Components.vue
packages/vue/test/base/tests/e2e/specs/breadcrumbs.cy.js

Issue URL: 
- Duplicate of https://github.com/ionic-team/ionic-framework/pull/27040, just fixing the commit description to follow conventional commits

fix(breadcrumbs): color attribute shows on DOM for Vue

---

README.md

The links for the migration guides in the README are incorrect: https://github.com/ionic-team/ionic-framework/blob/main/README.md#migration-guides

chore(readme): update migration guides to correct links

---

core/src/components.d.ts
core/src/components/content/content.tsx

Issue URL: Resolves https://github.com/ionic-team/ionic-docs/issues/2874
Typo fixed.

docs(content): fix typo in forceOverscroll description

---

core/src/components/textarea/test/autogrow/textarea.e2e.ts
core/src/components/textarea/test/legacy/autogrow/textarea.e2e.ts

The autogrow tests are flaky and tend to fail.
Issue URL:  N/A
- Skipping tests until they are fixed at a later time.
N/A

test(textarea): skip autogrow test due to flakiness

---

core/src/components/picker-column-internal/picker-column-internal.tsx

backport https://github.com/ionic-team/ionic-framework/pull/27038 to 6.7

fix(picker-column-internal): hide empty picker items from screenreaders

---

core/src/components/action-sheet/test/isOpen/action-sheet.e2e.ts
core/src/components/action-sheet/test/trigger/action-sheet.e2e.ts
core/src/components/alert/test/isOpen/alert.e2e.ts
core/src/components/alert/test/trigger/alert.e2e.ts
core/src/components/loading/test/isOpen/loading.e2e.ts
core/src/components/loading/test/trigger/loading.e2e.ts
core/src/components/menu/test/a11y/menu.e2e.ts
core/src/components/modal/test/isOpen/modal.e2e.ts
core/src/components/modal/test/sheet/modal.e2e.ts
core/src/components/picker/test/isOpen/picker.e2e.ts
core/src/components/picker/test/trigger/picker.e2e.ts
core/src/components/toast/test/isOpen/toast.e2e.ts
core/src/components/toast/test/trigger/toast.e2e.ts

Issue URL: N/A
Playwright recommends using Locators with web-first assertions instead of using `waitForSelector`: https://playwright.dev/docs/api/class-frame#frame-wait-for-selector
- Removes waitForSelector usages for checking if components are visible in favor of the `toBeVisible` or `toBeHidden` assertions.

test(many): use web-first assertions

---

core/src/components/radio/test/legacy/a11y/radio.e2e.ts

Similar to the other keyboard tests, this one is flaky on CI: https://github.com/ionic-team/ionic-framework/actions/runs/4620380152/jobs/8170437661
- Skipped flaky test and added tech debt ticket

test(radio): skip flaky test

---

core/src/components.d.ts
core/src/components/input/input.tsx
core/src/components/searchbar/searchbar.tsx

The `setFocus` method does not mention extra implementation details required when working within an overlay. 
Issue URL: N/A
- Adds additional detail about how to use `setFocus()` when inside an overlay
- Aligns the `ion-searchbar` documentation to match the `ion-input` documentation

docs(input,searchbar): setFocus usage within overlays

---

core/src/components/radio/test/legacy/a11y/radio.e2e.ts

I forgot to skip the legacy radio test in https://github.com/ionic-team/ionic-framework/pull/27126.
I also discovered we had duplicate flaky radio keyboard test tech debt tickets.
https://github.com/ionic-team/ionic-framework/actions/runs/4658963827/jobs/8245309480?pr=27125
- skipped legacy radio test
- closed FW-3956 in favor of FW-3747

test(radio): skip legacy flaky test

---

core/src/components/menu/menu.tsx

Issue URL: resolves https://github.com/ionic-team/ionic-framework/issues/24907
`ion-menu` currently clears the `menuInnerEl` and `backdropEl` refs created by Stencil when `disconnectedCallback` is fired. If the `ion-menu` component is re-mounted but _not_ re-rendered, those refs will still be `undefined` when the `open` method is called, resulting in the linked issue. Note that if the `ion-menu` re-renders before `open` is called then this issue does not reproduce.
This clearing behavior was added ~6 years ago before we utilized Stencil refs: https://github.com/ionic-team/ionic-framework/blob/687b37ad3e3237b874473817bb7b59143ac113ce/packages/core/src/components/menu/menu.tsx#L136-L137
During this time we had to manually create and clear the element references.
Several years later we moved …

fix(menu): refs are not destroyed on unmount

---

angular/test/base/src/app/form-controls/range/range.component.html
angular/test/base/src/app/form/form.component.html
angular/test/base/src/app/inputs/inputs.component.html
angular/test/base/src/app/searchbar/searchbar.component.html

The Angular test apps use the legacy label syntax for the e2e test templates.
Issue URL: N/A
- Updates the test templates for the Angular test apps to use the modern syntax available in Ionic v7.

chore(angular): test apps use modern label syntax

---

core/src/components/accordion/test/basic/accordion.e2e.ts

The `ionChange` event test occasionally flakes on CI: https://github.com/ionic-team/ionic-framework/actions/runs/4670357292/jobs/8270028536
It appears that when clicking the same accordion again the test expects the `ionChange` event to receive a detail payload of `undefined`. However, this is wrong because `ionChange` should not fire at all if the value does not change.
- Removes the `undefined` check from the test. This check does not seem necessary as clicking the `nth(2)` accordion should then update the payload.

test(accordion): remove undefined check in test

---

core/package-lock.json
core/package.json
packages/vue/src/components/IonApp.ts
packages/vue/src/components/IonBackButton.ts
packages/vue/src/components/IonNav.ts
packages/vue/src/vue-component-lib/overlays.ts
packages/vue/src/vue-component-lib/utils.ts

Issue URL: resolves #25199
Vue components show up as "Anonymous Component" in Vue Dev Tools. This is caused by our use of `displayName` instead of `name`. This required a fix in the Vue Output Target package. See https://github.com/ionic-team/stencil-ds-output-targets/pull/257 for more info.
- Updates the Vue Output Target dependency
- Functional components created manually in Ionic Vue now set `name` instead of `displayName`. Note: Non-functional components were never impacted by this bug.
Dev build: `7.0.2-dev.11681308435.141a05de`

fix(vue): components have correct name in Vue Dev Tools

---

core/src/components/input/input.tsx

Updates the `compositionstart` and `compositionend` events on input to use JSX bindings since issue https://github.com/ionic-team/stencil/issues/3235 was resolved in Stencil v3.

refactor(input): migrate composition events to JSX bindings

---

core/src/components/select/test/legacy/async/index.html
core/src/components/select/test/legacy/custom/index.html
core/src/components/select/test/legacy/standalone/index.html
core/src/components/select/test/legacy/wrapping/select.e2e.ts

There are select controls without a label in the legacy tests, that do not manually specify `legacy="true"`. These will be automatically upgraded to the modern form syntax when async labels are merged.
Issue URL: N/A
- Adds `legacy="true"` to legacy select tests

test(select): use modern form syntax

---

.github/PULL_REQUEST_TEMPLATE.md

Now that the PR description is used as the default commit message, the issue a PR resolves is specified directly in the PR description. However, the conventional-commits tool isn't smart enough to recognize full issue URLs, only the issue number (e.g. `resolves #12345`). This PR updates the template to nudge the description in this direction.

chore(template): ask for issue number instead of URL

---

core/src/components/toast/test/a11y/index.html
core/src/components/toast/test/a11y/toast.e2e.ts
core/src/components/toast/test/toast.spec.ts
core/src/components/toast/toast.tsx

Issue URL: resolves #25866
---------
Docs PR: https://github.com/ionic-team/ionic-docs/pull/2914
NVDA is not announcing toasts on present.
- Toast has a "status" role and "polite" announcement.
- We also revisited the intended behavior of toasts to better align with the Material Design v2 spec: https://m2.material.io/components/snackbars/web#accessibility
Dev build: 7.0.3-dev.11681482468.19d7784f

fix(toast): screen readers announce content

---

core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/minmax/datetime.e2e.ts
core/src/components/datetime/utils/manipulation.ts

When using the dropdown month picker, the value is updated when the month is changed, to follow native behavior. However, because only the month is updated (the day remains the same), it's possible for the newly chosen date to fall outside the min/max bounds of the datetime.
For example, if you have a datetime with `min="2021-01-15" value="2021-02-01"`, then use the month picker to switch to January, the new value will be `2021-01-01` which is earlier than the `min`.
Issue URL: Resolves #27027
When updating the `activeParts` in any scenario, the date to set is now clamped between the max and min.

fix(datetime): clamp date between min and max when using month picker

---

core/src/components/input/input.scss
core/src/components/textarea/textarea.scss

Issue number: resolves #27249
---------
The cloned input/textarea for scroll assist is not sized correctly. For legacy inputs, this causes the clone to be off by ~1px because it does not have the correct height. For modern inputs, this causes the same bug as the legacy inputs plus cloned inputs overlap any floating/stacked labels. This was not a concern for legacy inputs because those inputs did not contain the label element where modern inputs do.
- Sets `bottom: 0` for cloned inputs so they have the correct height
- Sets `position: relative` on the `.native-wrapper` so the cloned input does not flow outside of the parent container.
**Before**
| Modern Input | Legacy Input |
| - | - |
| <video src="https://user-images.githubusercontent.com/2721089/233385644-3c15f98e-2646-41e1-b206-34c5057 …

fix(ios): scroll assist sizes input correctly

---

core/src/components/action-sheet/test/basic/action-sheet.e2e.ts
core/src/components/datetime-button/test/basic/datetime-button.e2e.ts
core/src/components/datetime-button/test/overlays/datetime-button.e2e.ts
core/src/components/img/test/basic/img.e2e.ts
core/src/components/item/test/a11y/item.e2e.ts
core/src/components/loading/test/basic/loading.e2e.ts
core/src/components/loading/test/standalone/loading.e2e.ts
core/src/components/menu/test/basic/menu.e2e.ts
core/src/components/menu/test/focus-trap/menu.e2e.ts
core/src/components/modal/test/basic/modal.e2e.ts
core/src/components/modal/test/can-dismiss/modal.e2e.ts
core/src/components/modal/test/card-refresher/modal.e2e.ts
core/src/components/modal/test/card-scroll-target/modal.e2e.ts
core/src/components/modal/test/card/modal.e2e.ts
core/src/components/modal/test/fixtures.ts
core/src/components/modal/test/inline/modal.e2e.ts
core/src/components/modal/test/sheet/modal.e2e.ts
core/src/components/modal/test/standalone/modal.e2e.ts
core/src/components/popover/test/nested/popover.e2e.ts
core/src/components/select/test/basic/select.e2e.ts
core/src/components/select/test/compare-with/select.e2e.ts
core/src/components/select/test/legacy/async/select.e2e.ts
core/src/components/select/test/legacy/basic/select.e2e.ts
core/src/components/select/test/legacy/compare-with/select.e2e.ts
core/src/components/select/test/legacy/standalone/select.e2e.ts
core/src/components/textarea/test/autogrow/textarea.e2e.ts
core/src/components/textarea/test/legacy/autogrow/textarea.e2e.ts

---------
`page.locator` is synchronous, but we were `await`ing the calls: https://playwright.dev/docs/api/class-page#page-locator
We were also doing `page.locator(...).click()` when we can just do `page.click([selector])` directly,
- Removes `await` usage from `page.locator`
- Removes `page.locator().click()` usage in favor of `page.click()`

test(many): do not await page.locator

---

.github/workflows/dev-build.yml
.github/workflows/nightly.yml

---------
Original Discussion: https://github.com/ionic-team/stencil-ds-output-targets/pull/327#discussion_r1176950960
This flag was left over from our migration from custom build scripts to Lerna. Since we use `npm ci` the `--no-package-lock` flag is not needed.
- Removes `--no-package-lock` from build scripts.
- Here is an example test run of a dev build succeeding without the `--no-package-lock` flag: https://github.com/ionic-team/ionic-framework/actions/runs/4801503002

chore(ci): remove --no-package-lock flag

---

core/src/utils/input-shims/hacks/scroll-assist.ts

Issue number: resolves #27257
---------
1. Scroll assist was appending padding data every time it ran which caused the amount of padding to infinitely grow until an input was blurred
2. Calling `inputEl.focus()` caused scroll assist to run again which caused unexpected scrolls
- `currentPadding` is either preserved or set, never incremented
- Added a special attribute to inputs that are manually focused so scroll assist knows not to re-run

fix(scroll-assist): set correct scroll padding

---

core/src/components.d.ts
core/src/components/tabs/tabs.tsx

When using Angular, React, or Vue, the use of tabs is coupled to the framework's routing. These methods are only available when using tabs with vanilla JavaScript.
---------
- Adds more context to the description of the methods on tabs

docs(tabs): document methods only available for vanilla

---

.github/ISSUE_TEMPLATE.md
angular/README.md
core/README.md

---------
there are a few outdated links to a dead heroku app in the repo
this commit removes old links within the repo that point to a heroku app that is no longer working/maintained. the original intent was to update stencil-related links initially (as stencil still focuses on slack for community communications). however, there were two references to the ionic worldwide slack, which has been since replaced with discord. i've updated those link (which were only in comments) as well. after applying this commit, there are no references to 'heroku' in the repo
Feel free to reject this/request we remove these links altogether.  I'm not entirely sure we want to continue to provide them in the `core/` and `angular/` directories (when we don't have them in `packages/react/` …

chore(repo): update old heroku app links

---

.github/workflows/stencil-nightly.yml

---------
The Stencil nightly job fails with the following error:
```
The workflow is not valid. .github/workflows/stencil-nightly.yml (Line: 101, Col: 13): Job 'test-core-screenshot-legacy' depends on unknown job 'build-core'. 
.github/workflows/stencil-nightly.yml (Line: 122, Col: 12): Job 'verify-screenshots-legacy' depends on job 'test-core-screenshot-legacy' which creates a cycle in the dependency graph.
```
This started to fail last night. I believe this is a result of https://github.com/ionic-team/ionic-framework/pull/27228, specifically this line https://github.com/ionic-team/ionic-framework/commit/4fe8de7df71b0d9fb8d618aca5a428129d96a04b#diff-2f087e8fac034d51c50fc9350e10ceb4034298c16dd0d4f414f79d88ebb71aa0R101
this commit updates the job dependency hierarchy for …

chore(ci): fix stencil nightly job dependencies

---

.github/workflows/stencil-nightly.yml

---------
the legacy screenshot test verification step can fail due to improper configuration
this commit updates the name of the legacy screenshot test so that we properly gate on verifying that the legacy tests passed
I tested this by kicking off the workflow - https://github.com/ionic-team/ionic-framework/actions/runs/4830665737
Yesterday, I [put up a PR](https://github.com/ionic-team/ionic-framework/pull/27298)  that did the same. However, I failed to verify it succeeded (since we don't gate on Stencil nightly) - only that it started (since that was the point of failure yesterday).
Today, I have verified that it passes all the way through

chore(ci): fix stencil nightly legacy check

---

core/src/components/checkbox/checkbox.scss
core/src/components/radio/radio.scss
core/src/components/range/range.scss
core/src/components/select/select.scss
core/src/components/select/test/label/index.html
core/src/components/toggle/toggle.scss

Issue number: resolves #27305
---------
Checkbox, radio, range, select, and toggle take up 100% of its width even when in a start/end slot.
- Checkbox, radio, range, select, and toggle do not take up 100% of its width even when in a start/end slot.
. The "no slot" behavior is unchanged and aligns with the legacy select.

fix(many): form components do not take up full width in slot

---

core/src/components/radio/test/a11y/radio.e2e-legacy.ts
core/src/components/radio/test/legacy/a11y/press-keys.ts
core/src/components/radio/test/legacy/a11y/radio.e2e-legacy.ts
core/src/utils/test/playwright/playwright-page.ts
core/src/utils/test/press-keys.ts

---------
`Tab` keyboard navigation tests are disabled for `ion-radio` because they were extremely flaky in CI.
- Re-enables `ion-radio` `Tab` keyboard navigation tests
- Ports a slimmed down version of Wordpress' playwright utilities for using modifier keys with `Tab` keyboard navigation on environments that do not support "natural tab navigation"
This utility should likely be used in all places where we are using the `Alt+Tab` logic for webkit-based browsers today. If/when the changes are agreed upon, I can follow-up with PR that adds this behavior to those tests.

test(radio): enable keyboard tests

---

core/src/components/item-sliding/test/basic/item-sliding.e2e.ts
core/src/components/list/test/lines/list.e2e.ts

---------
item sliding tests were missing a `screenshot` function
- Added the function
- Also removed stray `config` params
This was not caught because these tests are currently skipped.

chore(): add missing screenshot function

---

.github/PULL_REQUEST_TEMPLATE.md

Removes the comments about reading the contributing guide from our pull request template. GitHub recommends the contributing guide in a popup to new contributors, and it also recommends it if anything has changed recently.

chore: remove unnecessary comments in PR template

---

angular/src/directives/overlays/modal.ts
core/src/components.d.ts
core/src/components/modal/modal.tsx
core/src/components/popover/popover.tsx
core/src/utils/transition/index.ts

Issue number: resolves #27343
---------
In https://github.com/ionic-team/ionic-framework/commit/30e3a1485d9bc94b31c297bdd05fa847b4bcfb56 I removed the `deepWait` call from popover/modal in custom element bundle environments (React and Vue as of writing). This had an unintended side effect where WebKit/iOS would not play the modal enter animation correctly because the inner contents are mounted mid-animation. This does not impact other mobile platforms.
This only impacted the modal because popover had a patch in https://github.com/ionic-team/ionic-framework/commit/be9a399eeed37ae4a67add78ac1283ba0c5e4b14 which causes it to wait for the JS Framework to finish mounting before proceeding with the transition.
- Modal now emits `ionMount` event and waits 2 frames before proceeding with the …

fix(modal, popover): wait for contents to mount

---

.github/workflows/actions/test-core-screenshot/action.yml

---------
`set-output` usage is deprecated in favor of environment files.
- Updates the `test-core-screenshot` workflow to remove `set-output` in favor of environment files.

chore(ci): update workflow for upcoming deprecation

---

core/src/interface.d.ts

Issue number: Resolves #27353
---------
`DatetimeHighlightStyle` is not automatically exported from `@ionic/core`, since the type is not directly referenced on a prop. 
- Manually exports `DatetimeHighlightStyle` to consumers

fix(types): export DatetimeHighlightStyle

---

core/src/components/action-sheet/test/basic/action-sheet.e2e.ts

Changes `mode` to `modes` in action sheet tests to fix failing build

test(action-sheet): change mode to modes

---

.github/ionic-issue-bot.yml

---------
The team would like to provide more context surrounding the `community feedback wanted` label in terms of setting expectations that we may accept or reject the feedback after a community feedback period.
- Ionitron will now comment on `community feedback wanted` issues.

chore: add workflow for commenting on community feedback labels

---

.github/dependabot.yml

---------
`@stencil/core` is the only package checked by dependabot
this commit updates the allow list for dependabot to allow additional stencil-scoped packages. the motivation for this is to allow the other stencil dependencies used in ionic framework to be automatically bumped by automation, rather than making it a manual process. this is intended to help with the stencil v4 rollout, where new versions on stencil packages (other than core) will be released with early v4 support.
I arbitrarily alphabetized the `@stencil/*` section of this allow-list. LMK if you'd prefer something different here

chore(repo): add `@stencil/*` packages to dependabot

---

packages/react/src/components/IonicReactProps.ts

---------
As noted in https://github.com/ionic-team/ionic-framework/issues/27415, `IonicReactProps` still has `class` as an exposed attribute on Ionic React components. React components should use the `className` property instead. It looks like this was left over code from the Ionic React beta that never got removed.
`class` was originally added in https://github.com/ionic-team/ionic-framework/commit/c79e74b91fdfd931f7ae082cfc374b2e55ee6d06#diff-065219c56a8c5dfc32564fac317b8cc9c03f1fbcb7f9cc2de0c5581970f21b51
And `className` was added in https://github.com/ionic-team/ionic-framework/commit/ab0f92e01f892c1c5f0db6e1e8467fe553e48bdd#diff-065219c56a8c5dfc32564fac317b8cc9c03f1fbcb7f9cc2de0c5581970f21b51
- Removes the `class` key

fix(react): remove incorrect class key from IonicReactProps

---

core/src/components/content/content.tsx

Issue number: Resolves #27411, https://github.com/ionic-team/stencil/issues/2429, https://github.com/ionic-team/stencil/issues/4076
---------
Rendering `<ion-content fullscreen="true">` in an Angular Universal project will result in a javascript heap exception and the browser tab timing out.
`forceUpdate` is not a compatible API with pre-rendering and results in calling itself indefinitely.
- Updates the fullscreen implementation of `ion-content` to only call `forceUpdate` and related functionality when running in a browser environment. 
- `<ion-content fullscreen="true">` is compatible with Angular Universal
Dev-build: `7.0.6-dev.11683653232.1ddc5840` ✅

fix(content): prevent forceUpdate in SSR

---

core/src/components/datetime-button/datetime-button.tsx

---------
An issue was filed in https://github.com/ionic-team/ionic-framework/issues/27452 where the `presentation` property was not being respected. The problem ended up being that the ID passed to `ion-datetime-button` was not associated with an `ion-datetime` instance, so it did not pick up on the `presentation` property. I think we can handle this better by logging an error if the ID passed does not belong to an `ion-datetime`.
- Log an error if the ID passed to `ion-datetime-button` exists but does not belong to an `ion-datetime` instance.

fix(datetime-button): log error if non-datetime instance is passed

---

core/src/components/input/input.scss
core/src/components/select/select.scss
core/src/components/textarea/textarea.scss

Issue number: resolves #27116
---------
With `ion-input`, `ion-select`, or `ion-textarea` using `fill="outline"`, applying a large value for the `--border-radius` CSS prop causes the radius to render differently on the left and right sides:
This is due to the structure of the outline container, which is used to render the empty space in the border when a `stacked` or `floating` label floats upwards. The container has three pieces, which combine to form a seamless-looking border:
The issue is that the browser will only render a radius that fits within the element's dimensions, and the piece on the left side (or right on RTL) is not wide enough.
While we could fix this issue by making the left-side piece wider (and there was originally a PR for this at …

docs(input, select, textarea): document workaround for large border-radius with fill="outline"

---

core/src/components/select/select.tsx
core/src/components/select/test/select.spec.tsx

Issue number: resolves #27478
---------
The modern syntax render function was missing `renderHiddenInput` which caused modern `ion-select` instances to not participate in form submission. Legacy syntax is not affected.
- Modern syntax calls `renderHiddenInput`.
Dev build: `7.0.7-dev.11684158250.1920157d`

fix(select): modern syntax works with forms

---

core/src/components/select/test/basic/index.html
core/src/components/select/test/basic/select.e2e.ts
core/src/components/select/test/legacy/basic/select.e2e.ts

---------
The `basic` test for `ion-select` contains a lot of content that is either duplicated within the test, duplicated by other tests, or simply not used/needed. Additionally, some select options (notably gender and hair color) are not inclusive.
Test template cleaned up, and options replaced with less personal ones as needed. Legacy test HTML was intentionally left alone since we'll be removing that in the near future anyway, though I did have to tweak a legacy E2E test since it was visiting the non-legacy page.

test(select): clean up basic test template

---

angular/README.md
core/README.md

[The Stencil team has moved their community from Slack to Discord](https://twitter.com/stenciljs/status/1658561079767887873).
---------
There is a link to the Slack.
- There is a link to the Discord.

docs(angular, core): change link from slack to discord

---

core/src/components/accordion-group/accordion-group.md.scss

Hey guys, I've found a minor issue.
There is a duplicate selector for the same rules. The lines `:24` and `:25` are the same.

refactor(accordion): remove duplicate selector

---

.github/dependabot.yml

---------
This change ensures that Ionicons always stays up to date in Ionic Framework with Dependabot.

chore: add ionicons to dependabot

---

angular/src/index.ts
core/api.txt
core/src/components.d.ts
core/src/components/segment-button/segment-button.tsx
core/src/components/segment/segment-interface.ts
core/src/components/segment/segment.tsx
packages/react/src/components/index.ts
packages/vue/src/index.ts

Issue number: resolves #27221
---------
The value property of the segment component in Ionic Framework currently only accepts string values.
This pull request updates the "value" property of the segment component to accept a union of string and number types. This allows for more versatile data input in the segment component, particularly for users who work with numerical data.
N/A

feat(segment, segment-button): update segment value property to accept numbers

---

core/src/utils/native/keyboard.ts
core/src/utils/native/native-interface.ts

Issue number: Resolves #27503
---------
Ionic Framework wraps the implementation around Capacitor's Keyboard plugin API, to provide additional functionality and behavior "automatically" in Ionic, when the plugin is installed.
Certain methods such as `getResizeMode()` are only available for certain platforms and will cause an error when running in the unsupported platform. 
Ionic Framework does not check to see if that platform is active before calling potentially unsupported methods, which leads to an exception for scenarios such as this - calling `getResizeMode()` on Android. 
- Handles the uncaught exception by returning `undefined` if the plugin method is unavailable.
- Developers do not receive an uncaught exception on Android when using the Capacitor Keyboard plugin with Ionic …

fix(core): handle uncaught native keyboard exceptions

---

core/src/utils/focus-visible.ts

Issue number: resolves #27566
---------
The `touchstart` listener for focus visible is not marked as passive. This causes a browser delay in case `touchstart` calls `ev.preventDefault()`. However, we are not doing that in this block of code.
- Added `passive: true` to the `touchstart` listener to avoid the browser delay.
Note that this is only needed for touch and wheel events which is why I only modified `touchstart`: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

perf: passive event listener for focus visible

---

.github/CODEOWNERS

---------
PRs are first assigned to the team before being assigned to a single team member. This causes reviews to show up https://github.com/notifications for everyone even if they are not the final reviewer. 
- GitHub automatically assigns reviewers now, so I removed the global Framework team codeowner. All PRs in this repo should have a team member automatically assigned.

chore: remove team assignment from codeowners

---

core/src/utils/keyboard/keyboard.ts

Issue number: resolves #27558
---------
The keyboard lifecycle util was always listening on visual viewport events even when in native environments. The visual viewport API is not reliable due to how the Ionic webview customizes how it resizes. We should only be listening on the native keyboard events in native environments.
https://github.com/ionic-team/capacitor/issues/3730
https://github.com/ionic-team/capacitor-plugins/blob/2e883f39329626062bcf876fe7d424432617229d/keyboard/ios/Plugin/Keyboard.m#L90-L98
- Keyboard lifecycle util listens on native keyboard events only when in native environment

fix(keyboard): listen on correct events for keyboard lifecycle

---

core/src/components/select/select.scss
core/src/components/select/test/basic/index.html

---------
The click event was firing twice.
- The click event fires once.
You can use the test file to see that the event now fires once, and before this change it fired twice. I couldn't figure out how to write an automated test for this that fails before the change and passes after the change. (Perhaps because of how Jest "clicks" elements? Not sure.)
Also, you can use the repro repo in the Jira ticket and update it to `"@ionic/angular": "7.0.10-dev.11685472954.170be0cc",` and see that the issue is fixed.

fix(select): prevent click event from firing twice

---

.github/workflows/actions/build-core-stencil-prerelease/action.yml
.github/workflows/stencil-v4.yml

---------
we have no way to test stencil v4 as a part of the nightly build
this commit adds a new ci cron job, 'stencil v4 build'. the purpose of this job is to run the ionic framework ci suite on an nightly basis, similar to the stencil nightly build.
a separate workflow has been created, as opposed to adding a `matrix` to the pre-existing workflow, as doing so would require a great deal of refactoring to the existing workflow. instead, a separate workflow allows us to simply delete the this workflow once stencil v4 is released.
as a part of this commit, we add a new input to the 'build-core-stencil-prerelease' action, allowing users of the action to input the npm tag of `@stencil/core` to install
I tested the Stencil nightly job manually - …

chore(ci): add stencil v4-next workflow

---

.github/workflows/stencil-v4.yml

---------
In https://github.com/ionic-team/ionic-framework/pull/27598, I failed to push a change that used the correct tag in the new Stencil v4 tag
this commit updates the stencil-version field for the Stencil v4 workflow to use the correct tag
[This log](https://github.com/ionic-team/ionic-framework/actions/runs/5190015779) shows it being used properly:

chore(ci): use correct tag for stencil v4

---

core/src/components/item-sliding/item-sliding.tsx
core/src/components/item-sliding/test/async/index.html
core/src/components/item-sliding/test/async/item-sliding.e2e.ts

Issue number: resolves #25578
---------
If `ion-item-option`s are added or removed from an `ion-item-sliding` asyncronously/after it has initialized, the sliding behavior of the item will not update. If options are added to an item that didn't have any, the item will not be openable. If all options are removed, the item will still be openable, though no options will render.
The item now re-checks its options when it detects that any have been added or removed, using the same utility/behavior as `ion-select`.

fix(item-sliding): refresh sliding behavior when options are added or removed asynchronously

---

core/src/components/refresher/refresher.tsx

Issue number: resolves #27601 
---------
The current behavior restores overflow styles while moving (within the setCSS function).
Overflow styles are restored when refresher gesture ends.
Honestly, I don't know exactly. From code perspective I would say 'Yes', but I can't get the impact of the change.
Ionic Team edit: There are no changes to the public API, and this is fixing a behavior that used to work so there are no breaking changes.

fix(refresher): scroll styles are reset when using non-native refresher

---

core/src/global/ionic-global.ts

---------
Ionic Framework references a deprecated object,`Context`, exposed by Stencil
starting with stencil v4, the deprecated `Context` object will no longer be exposed by stencil. this change was introduced in https://github.com/ionic-team/stencil/pull/4437, and will be present in the first v4 prerelease following v4.0.0-beta.2. in anticipation for this change, we seek to remove references to `Context` early.
ATM, the Stencil v4 nightly build is passing, as it's grabbing `@stencil/core@4.0.0-beta.2`. The change in which we remove the `Context` object will occur in the _next_ pre-release. I'm removing `Context` here to try to get a jump on things. 
The current iteration of the code that I'm deleting was added in …

chore(global): remove unused context references

---

core/src/components/select/select.scss
core/src/components/select/select.tsx
core/src/components/select/test/fill/select.e2e.ts

---------
Brandy discovered a bug in input, textarea, and select where the notch cutout remains visible even when no visible label is provided. I fixed this for input in https://github.com/ionic-team/ionic-framework/pull/27636 and for textarea in https://github.com/ionic-team/ionic-framework/pull/27647.
```html
<ion-select fill="outline" label-placement="stacked" value="select" aria-label="my select"></ion-select>
```
- The notch cut out is hidden if no visible label is provided

fix(select): hide notch cutout if no visible label provided

---

core/src/utils/keyboard/keyboard.ts
core/src/utils/keyboard/test/keyboard.spec.ts

Issue number: resolves #27654
---------
When Capacitor and the Keyboard plugin are available, `Keyboard.getEngine()` returns an object: https://github.com/ionic-team/ionic-framework/blob/d3232dcc007738fae851660bd818c8056b48b7d2/core/src/utils/native/keyboard.ts#L19
When Capacitor is _not_ available this method returns `undefined`.
However, when Capacitor is available but the Keyboard plugin is not, `Keyboard.getEngine()` returns `false`.
In https://github.com/ionic-team/ionic-framework/pull/27569 I fixed a bug where the wrong listeners were being used to emit keyboard lifecycle events. However, I did not know that method can return `false`, and our tests only account for the `undefined` or defined edge cases. As a result, if you are using Capacitor in an app that is deployed to the …

fix(keyboard): keyboard events emit correctly when Capacitor is available but the Keyboard plugin is not

---

core/src/components/item-sliding/test/basic/item-sliding.e2e.ts
core/src/components/item-sliding/test/icons/item-sliding.e2e.ts
core/src/components/item-sliding/test/test.utils.ts

Issue number: -
---------
I forgot to address the tests when working on FW-2608 to address issue #26103 
- Updated the visual regressions tests to verify that the item-sliding displays correctly on LTR/RTL. 
- Updated the item sliding tests to use the generators
The tests for item-sliding are disabled due to gesture flakiness. This will be addressed in another ticket. I recommend testing locally by adding the `.only` to all tests called `should not have visual regressions` and running `npm run test.e2e item-sliding`.

test(item-sliding): update visual regressions

---

.github/workflows/actions/publish-npm/action.yml

---------
Package provenance was disabled in #27656.
- Package provenance is enabled.

chore(ci): restore npm package provenance

---

.github/workflows/actions/publish-npm/action.yml

---------
Nightly build and release broken in #27711 due to missing shell property in GitHub Actions workflow.
- Nightly build and release works.

chore(ci): fix npm package provenance

---

angular/src/directives/proxies.ts
core/src/components.d.ts
core/src/components/input/input.tsx
core/src/components/textarea/textarea.tsx

---------
See https://github.com/ionic-team/ionic-framework/issues/27709
The `ionInput` description is vague and does not clarify that it only fires as the user types.
- Clarified the ionInput description for input and textarea

docs(input, textarea): clarify ionInput and ionChange

---

.github/workflows/build.yml
.github/workflows/release-ionic.yml
.github/workflows/stencil-nightly.yml

---------
`@ionic/angular-server` has a dependency on `@ionic/core` not `@ionic/angular` (see https://github.com/ionic-team/ionic-framework/blob/1f06be4a31965f2a949b4866a585aee6af0af29d/packages/angular-server/package.json). As a result, once `@ionic/core` is built there is no reason for `@ionic/angular-server` to also wait for `@ionic/angular` to build before it can build.
- `@ionic/angular-server` now waits for `@ionic/core` to build instead of `@ionic/angular`
Dev build sample run: https://github.com/ionic-team/ionic-framework/actions/runs/5414097033

chore: remove angular dep for angular-server

---

.github/workflows/stencil-nightly.yml

---------
Stencil nightly builds are broken
this commit updates the name of the dependent job for building the angular server (`build-angular-server`).

chore(ci): fix stencil nightly ci job

---

core/src/components/select/select.md.outline.scss

---------
The outline select uses `border-left` and `border-right` properties to handle LTR vs RTL borders. However, our border mixin takes care of this by using logical border properties.
- Updates the outline select to use the border mixin.
Note 1: There should be no visual changes as a result of this. This is simpler way of doing what we are already doing.
Note 2: There do exist logical border radius properties (for the other explicit LTR vs RTL work we do), but Ionic 7 supports browsers that do not support these properties yet. (I created FW-4661 to track this)

refactor(select): use border mixin

---

core/src/components/back-button/back-button.ios.scss

Issue number: resolves #27722
---------
The back button on iOS uses the same background and foreground colors on hover + focus making it impossible to read
- Back button uses a transparent background color on hover + focus to match the behavior of `ion-button`
| `main` | branch |
| - | - |
| <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/e8bed785-66d7-40cd-beb3-54636c7fc59a"></video> | <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/2c4a9a5c-f1a9-4a83-879f-8b0e9ce18558"></video> |

fix(back-button): show correct background on focus + hover with ios

---

core/package-lock.json
core/package.json

Issue number: resolves #27762
---------
Stencil 3.4.1 regressed the tsconfig alias path transpilation. This is fixed in 4.0.0 though.
- Downgrade to Stencil 3.4.0. Stencil 4.0 has breaking changes, so I'd like to wait on upgrading until we can work through any of the changes that impact Ionic.
This reverts commit 9793b3c0a0828b938b825116f78f616b1550d623.
Stencil issue: https://github.com/ionic-team/stencil/issues/4550

fix: avoid unresolved import warning on stencil apps

---

core/src/utils/test/overlays/overlays.e2e.ts

---------
Focus trapping tests were disabled because they were flaky
- Re-enabled the test 
- Migrated the test to use the pageUtils fixture which seems to be more stable with keyboard focus than the built-in page.keyboard commands

test(overlays): migrate to pageUtils and re-enable

---

core/src/utils/overlays.ts

Issue number: resolves #27773
---------
The focus trap util for scoped components moves focus back to the first focusable element inside of `.ion-overlay-wrapper` when clicking the backdrop. The reason for this is it (incorrectly) assumes that all focusable elements will be children of `.ion-overlay-wrapper`. This is true **except** for `ion-backdrop` which overlays the entire screen and therefore cannot be a child of `.ion-overlay-wrapper`.
This does not impact modal and popover as the shadow focus trap utility makes use of the Shadow Root as the parent for all focusable elements, not `.ion-overlay-wrapper`.
- Scoped focus trap util no longer moves focus if the `ion-backdrop` was focused.
I opted to explicitly account for `ion-backdrop` rather than come up with some new private API. As …

fix(overlays): first button is not focused on backdrop tap

---

core/src/components/breadcrumb/breadcrumb.ios.scss
core/src/components/breadcrumb/breadcrumb.md.scss
core/src/components/breadcrumb/breadcrumb.scss
core/src/components/breadcrumb/breadcrumb.vars.scss

---------
Breadcrumb does not support dynamic type
- Convert fonts to rem
- Add maximum font size for iOS to prioritize main content. Note that 22px was chosen to match the [back button max font size](https://github.com/ionic-team/ionic-framework/pull/27750) since breadcrumbs can be used in a toolbar.
Demo Video: https://github.com/ionic-team/ionic-framework/assets/2721089/3e59160b-e18e-4f96-975d-f9dc7f8a49d4

feat(breadcrumb): support dynamic type

---

core/src/css/structure.scss

Issue number: resolves #27782
---------
Ionic uses text-size-adjust to prevent browsers from resizing text in landscape mode in order to match native app behavior. However, WebKit only supports `-webkit-text-size-adjust`, so this fix never applied to iOS devices.
https://caniuse.com/?search=text-size-adjust
- Add `-webkit-text-size-adjust` where we use `text-size-adjust`
**Landscape**
| main | branch |
| - | - |
|  ![IMG_0046](https://github.com/ionic-team/ionic-framework/assets/2721089/d719f495-c051-4f64-a6fa-f17435c68cb5) | ![IMG_0048](https://github.com/ionic-team/ionic-framework/assets/2721089/7a0b5f45-b72a-466d-8e00-846de2572e49) |
**Portrait** (Should be no changes)
| main | branch |
| - | - |
| ![IMG_0045](https://github.com/ionic-team/ionic-framework/assets/2721089/a2324f9f-efcc-4c …

fix: safari no longer adjusts text in landscape

---

.github/dependabot.yml
core/package-lock.json
core/package.json
core/src/components/modal/utils.ts
core/src/components/refresher/refresher.tsx
core/src/utils/input-shims/hacks/scroll-assist.ts
core/src/utils/keyboard/keyboard-controller.ts
core/src/utils/native/capacitor.ts
core/src/utils/native/haptic.ts
core/src/utils/native/keyboard.ts
core/src/utils/native/native-interface.ts
core/src/utils/native/status-bar.ts

---------
Ionic currently detects and uses Capacitor APIs for different plugins (haptics, status bar and keyboard). This implementation does not have type safety and can result in unexpected behaviors. 
- Adds `@capacitor/core`, `@capacitor/keyboard`, `@capacitor/haptics` and `@capacitor/status-bar` as dev dependencies. These should _only_ be used with `import type { }`. 
- Refactors the plugin usages to be typed against the plugin packages, while using a duplicate enum when needing a value. This allows us to not bundle the capacitor plugins with Ionic Framework.
- Introduces a `getCapacitor()` function for interacting with the `window.Capacitor` object through a typed object. 
**How does it work?**
The idea is we want the type safety from the Capacitor packages, …

refactor: use capacitor types for native plugins

---

core/src/components/button/button.tsx
core/src/components/button/test/form-reference/button.e2e.ts

Issue number: resolves #19368 
---------
The form submits when clicking on the `ion-button`. However, users cannot submit the form when focused on a form element and pressing the `enter` button. This does not follow the behavior of the native button on a form.
- Form now submits when a form element is focused and the `enter` button is pressed.
- It also submits regardless of the amount of form elements present.
- Form will not submit if the `ion-button` is disabled.
N/A

fix(button): submit form when pressing enter key

---

core/src/components/menu/menu.tsx
core/src/components/menu/test/basic/index.html

Issue number: Resolves #27524 #22206
---------
After destructive hydration from an Angular Universal build, the `ion-menu` is disabled. This results in a few problematic behaviors:
- If used with an `ion-split-pane`, the split pane will not render with the menu.
- If used with an `ion-menu-button`, the menu icon will not render and the menu will not be accessible.
- Removes automatically disabling the `ion-menu` when in a server environment.
- Prevents setting an `ion-menu` that no longer exists in the DOM, as an active menu. This allows the most recent menu to be enabled when rendered from Angular Universal builds.
Loom recording overviewing the change: https://www.loom.com/share/5a149218adc84cc2af435fc1b1f45124?sid=249028f4-be3d-4d4a-948a-597da83be95a
Dev-build: …

fix(angular): menu button is enabled with Angular Universal builds

---

core/src/components/item-sliding/item-sliding.scss
core/src/components/item-sliding/item-sliding.tsx

Issue number: resolves #22722
---------
Item Sliding Options are not disabled until after a 600ms timeout. This timeout exists to allow the close transition to complete. Without the timeout, the item sliding options disappear without a transition. I explored waiting for the `transitionend` event instead of the `setTimeout`, but the bug persisted.
- If an item sliding is closing then we add a class to the host. This class disables pointer events on all `ion-item-options` children so the buttons cannot be accidentally tapped while closing. This class is then removed after the 600ms timeout.

fix(item-sliding): buttons are not interactive on close

---

core/src/components/modal/animations/ios.leave.ts

Issue number: resolves #27830
---------
Card modals set the body background to `black` to match iOS. This color should be removed once the final card modal has been closed. When modals were updated to work inline, the code that removed the background color was never updated to account for this. As a result, opening multiple inline card modals never removes the background color because there are always >1 modals in the DOM.
- The card modal now queries for _visible_ modals in the DOM to determine if it should remove the background color.
Dev-build: `7.2.1-dev.11689879279.14e28634`

fix(modal): body background is reset with inline card modals

---

core/src/components/item-options/item-options.scss
core/src/components/item-options/item-options.tsx

---------
Item sliding options in the "start" slot use the "left" safe area padding on the end edge. This causes the padding to be added in the wrong place.
During development I also discovered that the RTL padding was wrong for both start and end options.
LTR:
- `side="start"` options set "left" safe area padding on left edge of first child
- `side="end"` options set "right" safe area padding on right edge of last child
RTL:
- `side="start"` options set "right" safe area padding on right edge of first child
- `side="end"` options set "left" safe area padding on the left edge of the last child
| side prop/text direction | `main` | `branch` |
| - | - | - |
| start/LTR | ![start-ltr](https://github.com/ionic-team/ionic-framework/assets/2721089/36fd01c7-0907-4933-b8be-f …

fix(item-options): use correct safe area padding

---

core/package-lock.json
core/package.json

---------
Ionic is using Stencil 3
- Ionic now uses Stencil 4
Dev build: `7.2.1-dev.11690318651.186a9ff5`
I tested this dev build on a Stencil app with Ionic and verified that https://github.com/ionic-team/ionic-framework/pull/27767#issuecomment-1625746820 is resolved. No import warnings are logged on build.

chore: update to stencil 4

---

packages/angular/README.md
packages/angular/common/ng-package.json
packages/angular/common/src/index.ts
packages/angular/standalone/ng-package.json
packages/angular/standalone/src/index.ts

---------
We do not have a way of separating lazy loaded components from standalone components. This is important because developers who wish to use Ionic UI components as standalone components do not want their component implementation to use the lazy loaded component.
This PR creates two submodules within `@ionic/angular`:
`@ionic/angular/common` located at `packages/angular/common`:
- This is where logic that is shared between lazy loaded and standalone components live. For example, if you want to have a lazy loaded IonPopover and standalone IonPopover, you could put the base component implementation here and then have the lazy loaded/standalone implementations extend from this base implementation.
`@ionic/angular/standalone` located at `packages/angular/standalone`: …

chore: add infrastructure for standalone

---

core/src/components/toast/test/a11y/index.html
core/src/components/toast/test/a11y/toast.e2e.ts
core/src/components/toast/toast-interface.ts
core/src/components/toast/toast.tsx

---------
Buttons containing only icons are not accessible as there is no way to pass an `aria-label` attribute (or any other html attribute). 
- Adds the `htmlAttributes` property on the `ToastButton` interface 
- Passes the `htmlAttributes` to the buttons
- Adds a test to verify `aria-label` and `aria-labelled-by` are passed to the button

feat(toast): add htmlAttributes property for passing attributes to buttons  

---

core/src/components/action-sheet/action-sheet-interface.ts
core/src/components/action-sheet/action-sheet.tsx
core/src/components/action-sheet/test/a11y/action-sheet.e2e.ts
core/src/components/action-sheet/test/a11y/index.html

---------
Buttons containing only icons are not accessible as there is no way to pass an `aria-label` attribute (or any other html attribute). 
- Adds the `htmlAttributes` property on the `ActionSheetButton` interface 
- Passes the `htmlAttributes` to the buttons (both the buttons array and the cancelButton)
- Adds two tests to verify `aria-label` and `aria-labelled-by` are passed to a button with and without the cancel role - this was done because action sheet breaks these buttons up when rendering

feat(action-sheet): add htmlAttributes property for passing attributes to buttons

---

core/src/components/alert/alert-interface.ts
core/src/components/alert/alert.tsx
core/src/components/alert/test/a11y/alert.e2e.ts
core/src/components/alert/test/a11y/index.html

---------
Buttons containing only icons are not accessible as there is no way to pass an `aria-label` attribute (or any other html attribute). 
- Adds the `htmlAttributes` property on the `AlertButton` interface 
- Passes the `htmlAttributes` to the buttons
- Adds a test to verify `aria-label` and `aria-labelled-by` are passed to the button

feat(alert): add htmlAttributes property for passing attributes to buttons

---

packages/react-router/src/ReactRouter/IonRouter.tsx
packages/vue-router/src/router.ts

Issue number: resolves #27873
---------
Custom animations are not always used when the `handleNavigateBack` method is called. This impacts both Ionic React and Ionic Vue.
While we do set the `incomingRouteParams` with the animation: https://github.com/ionic-team/ionic-framework/blob/a08a5894baa862bab58cd19030682e6853dac1d6/packages/react-router/src/ReactRouter/IonRouter.tsx#L247-L252
We do sometimes call `handleNavigate`: https://github.com/ionic-team/ionic-framework/blob/a08a5894baa862bab58cd19030682e6853dac1d6/packages/react-router/src/ReactRouter/IonRouter.tsx#L273-L279
This `handleNavigate` method sets `incomingRouteParams` again: https://github.com/ionic-team/ionic-framework/blob/a08a5894baa862bab58cd19030682e6853dac1d6/packages/react-router/src/ReactRouter/IonRouter.tsx#L225-L230 …

fix(react, vue): custom animations are used when going back

---

core/src/components/datetime-button/test/basic/datetime-button.e2e.ts
core/src/components/datetime/utils/format.ts

Issue number: resolves #27797
---------
Datetime Button passes a parsed value to one of the many text formatting utilities we have, such as `getMonthAndYear`. However, developers can pass partial date values such as `2022` or `2022-04` (April 2022). According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format, these are still valid date strings.
However, the `parseDate` utility does not add fallback values. So passing `2022` will cause the `day` and `month` fields to be `undefined`. This means that `getNormalizedDate` passes `'//2022'` to the `Date` constructor.
Some browsers, such as Chrome, will automatically account for the stray slashes and still return a valid date. Other browsers, such as Safari, do not do this and will …

fix(datetime-button): render correct text when passing partial date values

---

core/src/components/nav/nav.tsx

Issue number: resolves #27893
---------
This is another instance of https://github.com/ionic-team/ionic-framework/issues/22895. The `progressCallback` function is fires asynchronously, so it's possible for the gesture start and end callbacks to run before the animation is ever set in `progressCallback`. When this happens, the animation gets locked up.
I previously fixed this in https://github.com/ionic-team/ionic-framework/pull/23527 for `ion-router-outlet`, but I did not fix it for `ion-nav`.
- If the gesture has ended by the time `progressCallback` fires, reset the animation to the beginning so it does not get locked up.
Dev build: `7.2.2-dev.11690896715.12338339`

fix(nav): improve reliability of swipe back gesture when quickly swiping back

---

core/src/components/item-sliding/item-sliding.tsx

Issue number: resolves #27910
---------
There is an edge case in our `ion-item-sliding` code where options can be added after the `querySelectorAll` has been run in `updateOptions` but before `watchForOptions` has been called which causes us to miss the newly created options. These options can never be shown as a result.
- `watchForOptions` is called before the initial `updateOptions` call so that we can re-run `updateOptions` in the event that options are added while that first call is running.
Dev build: `7.2.2-dev.11690983626.19a2a8cb`

fix(item-sliding): account for options added before watcher

---

core/src/components/action-sheet/action-sheet.tsx
core/src/components/action-sheet/test/is-open/action-sheet.e2e.ts
core/src/components/alert/alert.tsx
core/src/components/alert/test/is-open/alert.e2e.ts
core/src/components/loading/test/is-open/loading.e2e.ts
core/src/components/modal/test/is-open/modal.e2e.ts
core/src/components/picker/picker.tsx
core/src/components/picker/test/is-open/picker.e2e.ts
core/src/components/popover/test/is-open/popover.e2e.ts
core/src/components/toast/test/is-open/toast.e2e.ts
core/src/components/toast/toast.tsx

Issue number: resolves #27928 
---------
Action sheet, alert, picker, and toast did not have logic where the overlay presents if `isOpen="true"` on load. Modal, popover, and loading had this logic but did not have test coverage.
- Updated action sheet, alert, picker, and toast to present if `isOpen="true"` on load
- Added test coverage to all overlays for this functionality.
Dev build: `7.2.3-dev.11691156718.1638345c`

fix(many): overlays present if isOpen is true on load

---

core/src/components/button/button.tsx
core/src/components/button/test/form-reference/button.e2e.ts
core/src/components/button/test/form-reference/button.spec.ts

Issue number: resolves #27952
---------
The hidden button in `ion-button` that is responsible for submitting the form does not get added when the `form` property is set async.
- `ion-button` now checks to see if it needs to render a hidden button whenever it re-renders. This allows it to account for changes to the `type` property, `form` property, etc.
Since this code can potentially run multiple times I added an extra check so we don't add multiple buttons to the form.
Dev build: `7.2.3-dev.11691523847.1760ab58`

fix(button): hidden button is added when form is set async

---

core/playwright.config.ts
core/src/components/button/test/basic/button.e2e.ts

---------
The team would like to explore solutions for being informed of flaky tests in a way that is not disruptive to our workflow. Currently, flaky tests fail immediately which means we have to re-run them every time. We'd like flaky tests to be automatically retried but also reported to us so we can address them in a separate PR.
- Enables the Playwright GitHub reporter. This will report about flaky tests on the PR if applicable as well as in the CI results.
- Enables test retries. Tests will be retried up to 2 times before failing.
- Disables reporting slow tests in the GitHub reporter. Some of our tests require gesture interaction which are inherently slow but otherwise working as intended. We don't necessarily need to know about these right now.
- Disables …

test(playwright): enable github reporter, test retries

---

core/src/utils/tap-click/index.ts

---------
While working on getting our starter app tests running on CI, I ran into the following error:
```
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
ReferenceError: document is not defined
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
❯ Module.startTapClick node_modules/@ionic/core/components/index9.js:133:15
131|   };
132|   const doc = document;
133|   doc.addEventListener('ionGestureCaptured', cancelActive);
|               ^
134|   doc.addEventListener('touchstart', onTouchStart, true);
135|   doc.addEventListener('touchcancel', onTouchEnd, true);
❯ node_modules/@ionic/core/components/ion-app.js:21:113
This error originated in "src/App.test.tsx" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
This error was caught after test environment was …
```

fix(tap-click): do not error in document-less environment

---

packages/angular/tsconfig.json

---------
IDEs that perform type checking/include a language service will error on the `@ionic/angular/common` import paths and not provide intelisense or auto import detection.
- `@ionic/angular/common` import paths are detected by IDEs such as VSCode

chore: typescript resolves @ionic/angular/common import paths

---

.github/workflows/actions/download-archive/action.yml
.github/workflows/actions/test-core-spec/action.yml
.github/workflows/stencil-nightly.yml

---------
Stencil v3.4 is being used in the nightly run of these tests
this commit updates the `test-core-spec` action to accept an argument for the version of stencil that should be installed/used. since we do not (and arguably, should not) cache `node_modules/`, we need a way to inform this action that a nightly version of stencil should be installed
I fully expect nightly CI to begin to fail as a result of merging this. We'll fix that next week (in Stencil)

chore(ci): ensure stencil nightly gets installed for spec tests

---

core/src/components/button/button.tsx

As part of our incident learning review, the team would like to add better documentation as to the purpose of `renderHiddenButton` for future reference.

docs(button): add comments to renderHiddenButton

---

packages/angular/src/directives/navigation/ion-router-outlet.ts
packages/angular/src/directives/navigation/ion-tabs.ts
packages/angular/src/directives/navigation/stack-controller.ts
packages/angular/src/directives/navigation/stack-utils.ts

Issue number: Resolves #27212
---------
`ionTabsWillChange` emits _after_ the tab view is activated in the stack. 
- `ionTabsWillChange` emits _before_ the tab view is activated in the stack.
Dev-build: `7.2.4-dev.11692040948.1fd0ecd2`

fix(angular): ionTabsWillChange is fired before tab activation

---

core/src/components/input/input.tsx
core/src/components/input/test/basic/index.html
core/src/components/input/test/clear-on-edit/input.e2e.ts
core/src/components/textarea/test/clear-on-edit/textarea.e2e.ts
core/src/components/textarea/textarea.tsx

Issue number: resolves #27746
---------
Pressing the Tab key when focused on an input/textarea with `clearOnEdit` clears the text field and then moves focus to the next focusable element.
- Pressing the Tab key does not clear the text field even when clearOnEdit is enabled.
- Added test coverage
- I also noticed that input did not have an `index.html` file in the basic directory, so I added that.
Dev build: `7.3.1-dev.11692202566.13cd16c4`

fix(input, textarea): clearOnEdit does not clear when pressing Tab

---

packages/angular/src/directives/validators/index.ts
packages/angular/src/directives/validators/max-validator.ts
packages/angular/src/directives/validators/min-validator.ts
packages/angular/src/index.ts
packages/angular/src/ionic-module.ts
packages/angular/test/base/e2e/src/form.spec.ts
packages/angular/test/base/src/app/form/form.component.html
packages/angular/test/base/src/app/form/form.component.ts

Issue number: Resolves #23480
---------
Angular's min/max validators do not work with `ion-input[type=number]`. Using the built-in validators with `ion-input` will not update the control status to invalid, reflect the `ng-invalid` class or report the correct errors.
- The `IonicModule` now includes two additional directive declarations that extend Angular's built-in min/max validators and target the `ion-input` component when using `type="number"`.

 fix(angular): min/max validator for ion-input type number

---

packages/react/src/components/createInlineOverlayComponent.tsx
packages/react/test/base/src/pages/overlay-components/ActionSheetComponent.tsx
packages/react/test/base/tests/e2e/specs/overlay-components/IonActionSheet.cy.ts

Issue number: Resolves #28010
---------
`onDidDismiss` and `onWillPresent` will fire twice when having a manual binding in your implementation for inline overlays.
e.g.:
```tsx
<IonAlert onDidDismiss={() => console.log('hello world')} />
```
Will result in:
> hello world
> hello world
- `onDidDismiss` and `onWillPresent` do not execute the callback handler twice per invocation
Dev-build: `7.3.1-dev.11692305436.16a4008f`

fix(react): avoid multiple invocations of onDidDismiss and onWillPresent

---

core/src/components/picker/picker-interface.ts

There is no description of how to set the value of a picker.
Readers can find this description in the documentation.

docs(picker): describe how to set the initial value of a picker column

---

.github/workflows/actions/test-core-clean-build/action.yml
core/src/components/button/button.tsx

---------
When the CI process detects a diff between the output in CI after running `npm run build` versus the checked out branch, it will log the diff and exit. It isn't very clear to developers what they need to do or why this job step exists.
- Logs a prettier error message to the developer to let them know the steps they can take when a diff is detected in CI
Example run: https://github.com/ionic-team/ionic-framework/actions/runs/5942940488/job/16117074372?pr=28044

chore(infra): clean build check will log recommended steps

---

core/src/components/menu-button/test/async/index.html
core/src/components/menu-button/test/async/menu-button.e2e.ts
core/src/components/menu/menu.tsx

Issue number: resolves #28030
---------
`ion-menu` registers itself with the menu controller when `connectedCallback` fires and then unregisters itself when `disconnectedCallback` fires. When the menu was removed from the DOM, `disconnectedCallback` was not always being fired due to https://github.com/ionic-team/stencil/issues/4070.
`ion-menu-button` checks to see if it should be visible by grabbing the current menu in https://github.com/ionic-team/ionic-framework/blob/314055cf7a66a58e4e88c22e6e755fadd494ed70/core/src/components/menu-button/menu-button.tsx#L74.
Since `disconnectedCallback` was not being fired, `ion-menu-button` would still find the menu even when it was no longer in the DOM. In this case, the menu was not being unregistered due to `disconnectedCallback` not firing.
When …

 fix(menu): emit ionMenuChange when re-mounted

---

core/src/components/datetime/test/parse.spec.ts
core/src/components/datetime/utils/parse.ts

Issue number: resolves #28041
---------
`parseDate` returns `undefined` when given an invalid value. However, our min/max processing functions did not account for this. As a result, we would attempt to destructure an undefined value which resulted in an error.
Note regarding linked issue: The developer is calling `setMin(undefined)`. However, this is triggering a React quirk with Custom Elements where `undefined` is being set to `null` inside of React. The type signature on min/max is `string | undefined`, so `null` is being treated as an invalid date value.
- Min/Max processing functions now return `undefined` if the input was invalid.
Dev build: `7.3.2-dev.11692887667.1614d10a`

fix(datetime): gracefully handle invalid min/max

---

core/src/components/label/label.ios.scss
core/src/components/label/label.md.scss
core/src/components/label/label.scss

---------
The `text-wrap` attribute was removed in Ionic v5, but references to it still exist in the `ion-label` stylesheets.
https://github.com/ionic-team/ionic-framework/blob/main/BREAKING_ARCHIVE/v5.md#css-utilities
- Removed references to the unsupported `text-wrap` attributed.
Note: This is not a breaking change because support for `text-wrap` was removed in Ionic v5.

chore: remove deprecated attribute selectors

---

packages/vue-router/src/types.ts

---------
The Vue Router implementation [assigns data to the `routerAnimation` on the view item](https://github.com/ionic-team/ionic-framework/blob/cddefd1548be1f43fd529483e3829d3f5719a753/packages/vue/src/components/IonRouterOutlet.ts#L165-L170), but the [type does not exist on the `ViewItem` interface](https://github.com/ionic-team/ionic-framework/blob/main/packages/vue-router/src/types.ts#L62-L76). The actual routing implementation does not make use of the type, but this is backfilling the information when we wire up the types to the implementation. 
- Adds the missing type for `routerAnimation` to the `ViewItem`

chore(vue): add missing routerAnimation type

---

packages/angular/standalone/src/index.ts
packages/angular/standalone/src/navigation/tabs.ts
packages/angular/test/base/e2e/src/standalone/tabs.spec.ts
packages/angular/test/base/src/app/standalone/app-standalone/app.routes.ts
packages/angular/test/base/src/app/standalone/tabs/tab1.component.ts
packages/angular/test/base/src/app/standalone/tabs/tab2.component.ts
packages/angular/test/base/src/app/standalone/tabs/tab3.component.ts
packages/angular/test/base/src/app/standalone/tabs/tabs.component.html
packages/angular/test/base/src/app/standalone/tabs/tabs.component.ts

---------
Tabs cannot be used as a standalone component.
- Added tabs as a standalone component.
- Added a quick test. I included the event checking from the lazy test in the HTML as a smoke check, but didn't bring over the Cypress tests for them since I noticed the other standalone tests have been quick, stripped down affairs. I'm assuming I would just be duplicating effort. Let me know if I should bring more tests over from the lazy version, or even get rid of the event logging from the standalone HTML.

feat(angular): add standalone tabs

---

.github/workflows/actions/build-angular-server/action.yml
.github/workflows/actions/build-angular/action.yml
.github/workflows/actions/build-core-stencil-prerelease/action.yml
.github/workflows/actions/build-core/action.yml
.github/workflows/actions/build-react-router/action.yml
.github/workflows/actions/build-react/action.yml
.github/workflows/actions/build-vue-router/action.yml
.github/workflows/actions/build-vue/action.yml
.github/workflows/actions/publish-npm/action.yml
.github/workflows/actions/test-core-clean-build/action.yml
.github/workflows/actions/test-core-lint/action.yml
.github/workflows/actions/test-core-screenshot/action.yml
.github/workflows/actions/test-core-spec/action.yml
.github/workflows/actions/test-react-e2e/action.yml
.github/workflows/actions/test-react-router-e2e/action.yml
.github/workflows/actions/test-vue-e2e/action.yml
.github/workflows/actions/update-reference-screenshots/action.yml

---------
`action/setup-node@v3` shipped a "breaking" change that requires node v18. This breaks our dev build release process. 
https://github.com/ionic-team/ionic-framework/actions/runs/6044495970/job/16403194005
- Updates the publish action to use node v18
Here is a successful run with these changes: https://github.com/ionic-team/ionic-framework/actions/runs/6044521110

chore(ci): use node v18 for github actions

---

.github/workflows/actions/update-reference-screenshots/action.yml

---------
When the "Update Reference Screenshot" job is run but no new screenshots are generated, the following error is logged:
```
nothing added to commit but untracked files present (use "git add" to track)
Error: Process completed with exit code 1.
```
This is happening because there are no files to commit when running `git commit`. Brandy noted that this was confusing since it doesn't actually tell you why there are no files to commit.
- If there are no diffs to commit then the update screenshot script will log a message saying that no screenshot diffs were generated.
Example:
```
⚠️ Error: No new screenshots generated ⚠️
This means that there were zero visual diffs when running screenshot tests.
Make sure you have pushed any code changes that would result in visual …
```

chore: add error when no new diffs generated

---

core/src/components/item-options/item-options.scss

---------
Item options defines a font-size that is unnecessary because `ion-item-option` also defines it. 
Remove the font-size from `ion-item-options`.

refactor(item-options): remove unnecessary font-size styles

---

core/src/components/header/header.ios.scss

---------
When testing Dynamic Type I discovered that the searchbar has the wrong height when placed inside of a toolbar inside of a collapsible header.
- Removed the additional CSS. This is no longer needed because `ion-searchbar` has `min-height: 52px`
| `FW-4146` | branch |
| - | - |
| ![IMG_0148](https://github.com/ionic-team/ionic-framework/assets/2721089/d9e5c0ce-98a1-4e5e-9365-9487b00bb602) | ![IMG_0147](https://github.com/ionic-team/ionic-framework/assets/2721089/7ac1b08f-809e-4c2b-868f-3294f6448555) |

fix(searchbar): searchbar in collapsible header has correct height

---

core/scripts/testing/styles.css
core/src/css/typography.scss

---------
The team discussed offline that there are a few issues with the current name of `--ion-dynamic-type`:
1. It's not clear what this does. Dynamic Type is an iOS-specific term, but this feature is for all Ionic apps.
2. It's inconsistent with the other Dynamic Font Scaling variable named `--ion-default-dynamic-font`.
3. The naming does not align with how the variable is applied via the `font` CSS property.
- Renames `--ion-dynamic-type` to `--ion-dynamic-font`.
(This feature has not shipped yet, so it's not a breaking change)

refactor: rename dynamic font variable

---

.github/workflows/actions/update-reference-screenshots/action.yml

---------
We checked `git diff` to see if new screenshots were generated. If no new screenshots were generated then we print a user-friendly message informing the dev what happened. However, `git diff` does not account for untracked changes (i.e. new screenshots).
As a result, this prevented new screenshots from being committed.
- To fix this we use the `-N` flag which is short for `--intent-to-add`. This adds an entry with no content which causes the new screenshots to show up when running `git diff`. We later add the contents of the image.
Example test run of this working: https://github.com/ionic-team/ionic-framework/actions/runs/6174263712/job/16759260534

chore(ci): account for new screenshots in error logging

---

packages/vue/src/vue-component-lib/overlays.ts
packages/vue/test/base/src/views/OverlaysKeepContentsMounted.vue
packages/vue/test/base/tests/e2e/specs/overlays-keep-contents-mounted.cy.js

Issue number: resolves #28165
---------
The overlay implementation in Vue only checks for truthy `keepContentsMounted` values. When setting this prop as an attribute, the value of it is `''` which is falsy. As a result, content does not get mounted.
One of Vue's ESLint rules states that this should be supported: https://eslint.vuejs.org/rules/prefer-true-attribute-shorthand.html
Part of the issue may also be that Vue does not know the type of this property and so it assume "any":
> The shorthand form is not always equivalent! If a prop accepts multiple types, but Boolean is not the first one, a shorthand prop won't pass true.
- The overlay wrapper now checks for `''` values. If `keepContentsMounted === ''` then the inner contents will be mounted because this means the prop is being set …

 fix(vue): respect keepContentsMounted if passed as attribute

---

core/playwright.config.ts

---------
We currently use retries on CI to help catch flaky tests. However, retries are enabled even when testing locally. This is not ideal because a failing test will be re-run multiple times before erroring out which increases the time it takes to run tests locally. I typically write tests before fixes so I can verify my test is checking the correct behavior. In this case I don't need it to be re-run twice -- I already know it's supposed to fail.
- Test retries are only enabled on CI

test(playwright): only use retries on CI

---

core/src/components/menu/menu.tsx
core/src/utils/overlays.ts
core/src/utils/test/overlays/overlays.spec.ts

Issue number: resolves #28180
---------
When presenting an overlay, we remove the root (usually `ion-router-outlet`) from the accessibility tree. This makes it so you cannot accidentally focus elements behind the overlay. When dismissing an overlay we re-add the root to the accessibility tree. However, we fail to consider if there are multiple presented overlays. For example, if you present a modal, then an alert, then dismiss the alert, then the root is re-added to the accessibility tree even though the modal is still presented.
- The root is now re-added to the accessibility tree only if it is the last presented overlay.
Dev build: `7.4.1-dev.11694783260.13da477f`

fix(overlays): correctly re-add root to accessibility tree

---

core/src/utils/input-shims/hacks/scroll-assist.ts
core/src/utils/input-shims/hacks/scroll-data.ts

Issue number: Part of #22940
---------
While working on a fix for #22940, I discovered another bug that impacted the reliability of my proposed fix for #22940. When we compute the scroll data (i.e. how much the input needs to be scrolled by), we subtract the `keyboardHeight` from the `platformHeight` (i.e. the viewport height): https://github.com/ionic-team/ionic-framework/blob/1015c06cbef4ceb10d43e722157c04844d984509/core/src/utils/input-shims/hacks/scroll-data.ts#L34
Every time we tap between inputs (even if the keyboard is already open) we re-run scroll assist because the newly focused input could be partially obscured by the keyboard. However, in this case we scroll by too much because we effectively subtract the keyboard height twice. This is because by the time we compute …

fix(scroll-assist): improve input scroll accuracy with native resizing

---

core/src/utils/test/playwright/docs/best-practices.md

---------
I needed this constant for a different PR but realized the docs were outdated: https://github.com/ionic-team/ionic-framework/blob/81714d45bd97f0ba91729959b60a0dc1d1d06533/core/src/utils/test/playwright/viewports/index.ts
- Docs reference correct constant name

test(docs): update viewport docs

---

packages/react/src/components/navigation/IonNav.tsx
packages/react/src/framework-delegate.tsx
packages/react/test/base/src/pages/navigation/NavComponent.tsx
packages/react/test/base/tests/e2e/specs/navigation/IonNav.cy.ts

Issue number: Resolves #27798
---------
React IonNav component's views are missing keys, leading to unnecessary duplicate mounting of components.
- Adds key to views of React IonNav component.

fix(react): Nav unmounts component while invoking popTo or popToRoot

---

core/src/components.d.ts
core/src/components/item/item.tsx

---------
The `fill` prop on `ion-item` is currently deprecated (see warning [here](https://github.com/ionic-team/ionic-framework/blob/main/core/src/components/item/item.tsx#L248-L253)) but the docs have not been updated to reflect this.
`@deprecated` flag added to the `fill` prop.

chore(item): add deprecated flag to fill prop

---

core/src/components/title/title.ios.scss

---------
When testing Dynamic Font Scaling with a custom font I noticed that the large title does not respect `--ion-font-family` on transition.
- The cloned large title now respect `--ion-font-family`
Note: This happens in `main` too which is why I am merging into there instead of the Dynamic Font Scaling branch.
| `main` | branch |
| - | - |
| ![IMG_0182](https://github.com/ionic-team/ionic-framework/assets/2721089/8e09669b-5e76-4736-a1cb-bea87dc25258) | ![IMG_0183](https://github.com/ionic-team/ionic-framework/assets/2721089/bde88ff1-6024-40ec-99ab-c71e73386dc9) |

fix(title): large title uses custom font on transition

---

core/api.txt
core/src/components.d.ts
core/src/components/datetime-button/datetime-button.tsx
core/src/components/datetime/datetime-interface.ts
core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/data.spec.ts
core/src/components/datetime/test/format.spec.ts
core/src/components/datetime/test/helpers.spec.ts
core/src/components/datetime/test/hour-cycle/datetime.e2e.ts
core/src/components/datetime/test/hour-cycle/index.html
core/src/components/datetime/utils/data.ts
core/src/components/datetime/utils/format.ts
core/src/components/datetime/utils/helpers.ts

Issue number: resolves #23750
---------
Datetime does not support h11 and h24 hour formats
- Datetime supports h11 and h24 formats
Implementation Notes:
1. I broke up the `is24Hour` function into two functions:
- The first function, `is24Hour`, accepts an hour cycle and returns true if the hourCycle preference uses a 24 hour format
- The second function, getHourCycle, accepts a locale and an optional hour cycle and returns the computed hour cycle. I found that the hour cycle is not always set via `hourCycle` (such as when we are using the system default if it's specified in the `locale` prop using locale extension tags). This was coupled to is24Hour, but I needed this functionality elsewhere to add support for this feature, so I decided to break the functions up.
2. We were using the hour …

feat(datetime): add support for h11 and h24 hour formats

---

core/src/components/range/range.tsx

Issue number: Resolves #25444
---------
In the custom elements build, currently used by React and Vue packages, the range knob can be rendered incorrectly if the value is assigned after the `connectedCallback` but before the initial render of the component. This is most apparent with the dual knobs implementation in React (referenced issue). 
This results in the range's value being correct, but the visual representation of the range to be incorrect.
This also causes issues with the custom elements build in the standalone implementation of Ionic's components in Angular. If a range is presented in a modal via a controller, the range will never render with the value that is initially assigned to it. 
- Updates the range knob positioning when the range has initially rendered. 
This change …

fix(range): knob positions are correct on initial render with custom elements build

---

core/src/components/select/select.tsx

---------
`ion-select` uses the `aria-haspopup="listbox"` even though the popup is a dialog.
- `ion-select` triggers a dialog, the value for `aria-haspopup` now reflects that
N/A

fix(select): use correct aria-haspopup value

---

core/src/components/router-outlet/router-outlet.tsx

---------
Code is duplicated between the router outlet and the overlays
- Code is reused between the router outlet and the overlays

refactor(router-outlet): reuse lock controller

---

core/src/components/segment/segment.tsx
core/src/components/segment/test/scrollable/segment.e2e.ts

Issue number: resolves #28096
---------
When a segment button is clicked, the segment will auto-scroll to position the newly active button fully in view. However, this behavior does not occur on first load. This means that when a segment is initialized with a `value` corresponding to an off-screen button, the button will remain off-screen.
The same auto-scroll behavior from button click now also occurs on component load.

fix(segment): scroll to active segment-button on first load

---

core/src/components.d.ts
core/src/components/content/content.tsx
core/src/components/tab-bar/tab-bar.tsx

Issue number: resolves #21130
---------
IonContent sets `--offset-top` and `--offset-bottom` variables to allow the content to scroll under headers, footers, and tab bars. This is essential to creating the translucency effect on these components.
IonContent does this by computing its offsetHeight and offsetTop coordinates which take into account the dimensions of headers, footers, and tab bars. Occasionally, this code will run before the IonTabBar has been hydrated which means that the offset will be wrong because the IonTabBar will have a dimension of 0x0 prior to hydration.
This impacts Ionic Angular devs who are using the lazy loaded build of Ionic. React and Vue devs are not impacted because they are using the dist-custom-elements build of Ionic which does not have hydration.
- …

fix(content): fullscreen offset is computed correctly with tab bar

---

core/src/components/header/header.ios.scss

Issue number: resolves #27060
---------
The main header is controlled by the header with `collapse="condense"` set: https://github.com/ionic-team/ionic-framework/blob/a04a11be3571faa99c751edc034462e94a977e95/core/src/components/header/header.tsx#L144
The collapse header will hide the main header and then show it once the user has scrolled enough. However, if the main header is rendered before the collapse header is rendered, then the main header will be visible for a brief moment before being hidden by the collapse header. This gives the perception of flicker that is reported on the linked issue.
- The main header will be hidden on load if it loads before the collapse header
The selector was written in a way such that once the collapse header loads, this CSS no longer applies (since the …

fix(header): collapsible large title main header does not flicker on load

---

.github/workflows/stencil-nightly.yml

---------
when the stencil team wants to test a dev build of stencil against the framework team's ci, they  push a branch to this repo that overrides the stencil nightly job's npm tag (replacing 'nightly' with the dev build version) and manually kick off the nightly workflow. this commit would eliminate the need for that first step there
update the stencil nightly job to accept any npm release tag, rather than always default to 'nightly'. doing so allows the stencil team to reuse this workflow for cases where we'd like to test a _dev_ build of stencil by running it through the framework's ci process, without landing the feature in stencil first.
I was able to test that `nightly` gets set by default (and the field is required) by running the workflow from this branch.
I …

chore(repo): parameterize stencil nightly

---

core/src/utils/gesture/swipe-back.ts

Issue number: resolves #28303
---------
- Swipe back gesture is inconsistently clobbered by ion-item-sliding's gesture.
- Swipe back gesture now has a higher priority than ion-item-sliding
-
-
This patch has been in use in [Voyager](https://github.com/aeharding/voyager) for the past couple months to great success!

fix(core): swipe to go back gesture has priority over other horizontal swipe gestures

---

core/src/index.ts
packages/angular/src/index.ts
packages/react/src/components/index.ts
packages/vue/src/index.ts

Issue number: resolves #27911 
---------
The `openURL` utility is not available to developers. 
- Export `openURL` utilities from `@ionic/core`, `@ionic/angular`, `@ionic/react` and `@ionic/vue`.

feat(angular, react, vue, core): export openURL utility

---

core/src/components/checkbox/checkbox.tsx
core/src/components/checkbox/test/checkbox.spec.ts
core/src/components/radio-group/radio-group.tsx
core/src/components/radio/radio.tsx
core/src/components/radio/test/radio.spec.ts
core/src/components/toggle/test/toggle.spec.ts
core/src/components/toggle/toggle.tsx

Issue number: resolves #28293
---------
Disabled toggles, radios, and checkboxes can still be enabled by manually dispatching a click event on them.
- Toggles, radios, and checkboxes no longer activate if `disabled` is set to `true`
Dev build: `7.4.4-dev.11696545130.1171e7a9`

fix(checkbox, radio, toggle): disabled elements are not interactive

---

README.md
core/package-lock.json
core/package.json

---------
The Dynamic Font Scaling branch was using an outdated version of Ionicons which did not support Dynamic Font Scaling. There were no visual diffs because we typically override the size of the icon internally, but still good to be on the latest version.
- Ionic Core uses Ionicons 7.2 internally

chore: use ionicons 7.2

---

core/src/components/select/select.tsx
core/src/components/select/test/disabled/select.e2e.ts

Issue number: resolves #28284
---------
Select focuses the first popover option when no value is provided. This means that the first option is focused even if it disabled.
- Select focuses the first **enabled** popover option when no value is provided.

 fix(select): do not focus disabled popover option

---

packages/react/src/routing/OutletPageManager.tsx
packages/react/src/routing/PageManager.tsx

---------
While debugging #28186, Maria and I identified that Ionic's lifecycle event listeners (`ionViewWillEnter`, etc.) were being registered multiple times on the same `.ion-page` element. This resulted in problematic behavior, where a user's implementation of our lifecycle hooks, would execute their callback multiple times. 
```ts
useIonViewWillEnter(() => {
// This is called 2x for every time the `ionViewWillEnter` event is emitted (in React 18, dev mode)
console.log('hello world'); 
});
```
When the Ionic lifecycle event listeners are registered in React, we bind the scope of the class to the callback function. When removing the event listener we additional use the `.bind` syntax. 
```tsx
componentDidMount() {
element.addEventListener('ionViewWillEnter', …
```

fix(react): lifecycle events are removed on page unmount

---

packages/react/src/contexts/IonLifeCycleContext.tsx
packages/react/src/lifecycle/hooks.ts
packages/react/src/routing/OutletPageManager.tsx
packages/react/src/routing/PageManager.tsx

Issue number: Resolves #28186
---------
Ionic lifecycle hooks do not execute a cleanup function when the underlying `useEffect` is unmounted.
```ts
useEffect(() => {
return () => {
console.log('cleanup'); // called
};
});
useIonViewWillEnter(() => {
return () => {
console.log('cleanup'); // never called
};
});
```
Ionic's implementation registers the lifecycle callback to be handled at a later time, by the page managers. However, it does not keep a reference to the returned callback, so it cannot execute it when the `useEffect` is unmounted.  
- Ionic lifecycle hooks execute dev-specified cleanup functions
Dev-build: `7.4.4-dev.11696956070.1faa3cfe`
This PR builds on the changes in #28316.

fix(react): cleanup functions are execute for lifecycle hooks

---

core/src/components/menu/menu-interface.ts
core/src/utils/menu-controller/index.ts
packages/angular/common/src/providers/menu-controller.ts
packages/angular/src/index.ts
packages/angular/src/providers/menu-controller.ts
packages/angular/standalone/src/directives/proxies.ts
packages/angular/standalone/src/index.ts
packages/angular/standalone/src/providers/menu-controller.ts
packages/angular/test/base/e2e/src/lazy/providers.spec.ts
packages/angular/test/base/e2e/src/standalone/menu-controller.spec.ts
packages/angular/test/base/src/app/lazy/providers/providers.component.html
packages/angular/test/base/src/app/lazy/providers/providers.component.ts
packages/angular/test/base/src/app/standalone/app-standalone/app.routes.ts
packages/angular/test/base/src/app/standalone/menu-controller/menu-controller.component.html
packages/angular/test/base/src/app/standalone/menu-controller/menu-controller.component.ts

Issue number: resolves #28337
---------
Duplicate instances of `menuController` are being created in `@ionic/angular`. `ion-menu` registers itself in the `menuController` from `@ionic/core`, but the `MenuController` from `@ionic/angular` uses the `menuController` from `@ionic/core/components`. This is how the overlay providers work too. Normally, this is not a problem. However, `menuController` caches references to registered menus in each controller instances: https://github.com/ionic-team/ionic-framework/blob/dcbf45101f4c0dc3541cd4c19186daa3766a6ce7/core/src/utils/menu-controller/index.ts#L14
This means that since there are two different controllers, `menuController` B does not know about the menus in `menuController` A. The end result is that the menu controller used in developer …

fix(angular): do not create duplicate menuController instances

---

.github/workflows/actions/build-core/action.yml
.github/workflows/build.yml

---------
Testing Ionicons in Ionic is currently difficult. Developers need to a) create a dev build of Ionicons, b) create a branch in Ionic, c) install the dev build in Ionic core, d) push the branch, and e) create a draft PR to watch the CI process run.
- Introduces a workflow dispatch option for our CI process. This allows developers to run the CI process for any branch without creating PR.
- I also added an optional input so devs can specify the ionicons version if they want to pass a special version.

chore(ci): add workflow for testing ionicons dev build

---

packages/angular/standalone/src/directives/checkbox.ts
packages/angular/standalone/src/directives/datetime.ts
packages/angular/standalone/src/directives/input.ts
packages/angular/standalone/src/directives/radio-group.ts
packages/angular/standalone/src/directives/radio.ts
packages/angular/standalone/src/directives/range.ts
packages/angular/standalone/src/directives/searchbar.ts
packages/angular/standalone/src/directives/segment.ts
packages/angular/standalone/src/directives/select.ts
packages/angular/standalone/src/directives/textarea.ts
packages/angular/standalone/src/directives/toggle.ts
packages/angular/test/base/e2e/src/standalone/value-accessors.spec.ts
packages/angular/test/base/src/app/standalone/app-standalone/app.routes.ts
packages/angular/test/base/src/app/standalone/value-accessors/checkbox/checkbox.component.html
packages/angular/test/base/src/app/standalone/value-accessors/datetime/datetime.component.html
packages/angular/test/base/src/app/standalone/value-accessors/input/input.component.html
packages/angular/test/base/src/app/standalone/value-accessors/radio-group/radio-group.component.html
packages/angular/test/base/src/app/standalone/value-accessors/range/range.component.html
packages/angular/test/base/src/app/standalone/value-accessors/searchbar/searchbar.component.html
packages/angular/test/base/src/app/standalone/value-accessors/segment/segment.component.html
packages/angular/test/base/src/app/standalone/value-accessors/select/select.component.html
packages/angular/test/base/src/app/standalone/value-accessors/select/select.component.ts
packages/angular/test/base/src/app/standalone/value-accessors/textarea/textarea.component.html
packages/angular/test/base/src/app/standalone/value-accessors/toggle/toggle.component.html

Issue number: resolves #28358
---------
https://github.com/ionic-team/ionic-framework/commit/28f2ec9c62fc301b432a7bca9a985b8ce90ef843 exposed a (possible) `ng-packagr` bug where the form control components were being re-assigned, which breaks treeshaking. These components were considered side effects and were always being pulled into the bundle.
This resulted in a higher than expected bundle size. This issue appears to be caused by using 2 decorators **and** referring to the class in `useExisting` (for providers). Doing just one of these does not reproduce the issue.
The compiled output looks something like this:
```typescript
let IonToggle = IonToggle_1 = /*@__PURE__*/ class IonToggle extends ValueAccessor {
constructor(c, r, z, injector) {
super(injector, r);
this.z = z;
c.detach(); …
```

fix(angular): remove form control side effects

---

packages/angular/.prettierignore
packages/angular/standalone/src/directives/proxies.ts

---------
Prettier is configured to ignore the `proxies.ts` file in the `src` directory only. This means it is adjusting whitespace/commas/etc on the `proxies.ts` file in the `standalone` directory which we do not want because we will always get diffs whenever `npm run build` is run in `core`.
- Updated prettier config to ignore all `proxies.ts` files in the `angular` package
- Re-generated the proxies file

chore(angular): proxies file is ignored by prettier

---

BREAKING.md

---------
As part of our Ionic 8 work, the team would like to define which browsers and platforms we will support.
- Chromium (Chrome + Edge) support has changed from 79+ to 89+
- Firefox support has changed from 70+ to 75+
- Safari/WebKit support has changed from 14+ to 15+
- Angular support has changed from 14+ to 16+
A few notes on why I made these changes:
- These browsers have full support for [Web Animations Level 1](https://caniuse.com/?search=web%20animations). This allows us to remove the old CSS Animation fallback support from our animation library.
- These browsers have [native image lazy loading](https://caniuse.com/?search=image%20lazy%20loading) support (iOS has it starting in iOS 15.4) which allows us to reduce our dependency on `ion-img`.
- These browsers …

docs(breaking): add v8 browser and platform support

---

core/src/components/menu/menu.tsx
core/src/components/split-pane/test/multiple/index.html
core/src/components/split-pane/test/multiple/split-pane.e2e.ts

Issue number: resolves #18683, resolves #15538, resolves #22341
---------
Menus in a split pane are hidden when a second split pane is mounted/made visible. This is because the `onSplitPaneChanged` callback does not take into account whether the it is a child of the split pane that emitted `ionSplitPaneVisible`.
When split pane 2 is shown, that causes the menu is split pane 1 to hide. When split pane 1 is shown, the menu inside of it _is_ shown. However, since split pane 2 is then hidden that component also emits `ionSplitPaneVisible`, causing the menu inside of split pane 1 to hide.
- Menus are only hidden when its parent split pane changes visibility
Dev build: `7.5.1-dev.11697568647.1ac87d08`

fix(menu): menu no longer disappears with multiple split panes

---

core/src/components/radio/test/legacy/a11y/radio.e2e.ts

---------
Legacy radio has tests that use `Tab` key presses. These tend to flake at unknown moments and were skipped until a fix can be implemented.
Unable to replicate the flakiness locally or on GitHub. However, it only fails on Safari so the tests were re-enabled except for Safari.
This only happens on legacy. The legacy form controls will also be removed in the future. Due to this, these tests will be removed anyways at that time.

test(radio): skip Safari on legacy tab key tests

---

core/src/components/action-sheet/action-sheet.scss
core/src/components/alert/alert.scss

Issue number: resolves #18487 
---------
Web-based users do not get a scrollbar when:
- alert has a long list of inputs (this also happens on `ion-select` with the alert interface)
- `ion-select` uses the action-sheet interface and has a long list of options
This makes it difficult for users to navigate through the options by forcing them to use their keyboards. Some users may also not be used to using their keyboards for navigation. Additionally, this can lead to potential confusion that there are no other options.
Web-based users get a scrollbar when:
- alert has a long list of inputs (this also happens on `ion-select` with the alert interface)
- `ion-select` uses the action-sheet interface and has a long list of options
The issue was filed for the alert interface but it's also …

fix(alert, action-sheet): show scrollbar for long list of options

---

packages/angular/common/src/providers/platform.ts

Issue number: #19539 
---------
When an app uses Capacitor, then the platform subscriptions will run outside of the Angular Zone.
- The platform subscriptions will run inside of the Angular Zone regardless if it uses Capacitor or not.
Added an extra `zone.run` within the event listener.
Dev build: `npm install @ionic/angular@7.5.2-dev.11698187124.1b7ea660`

fix(angular): run platform subscriptions inside zone

---

core/src/components/segment/segment.tsx

Issue number: resolves #28373
---------
🚨 Reviewers: Please test this on Chrome, Firefox, and Safari
The fix in https://github.com/ionic-team/ionic-framework/commit/1167a9325fb930b6c727bc26889f5488d9620062 uncovered a WebKit bug where scrolling an element using `scrollIntoView` during an accelerated transition causes the segment to jump during the transition. `scrollIntoView` can cause parent elements to also scroll, and given that the entering view begins outside the viewport, it's possible this triggered some sort of WebKit bug where it was trying to scroll the element into view.
- Updated the internal implementation to use `scrollBy` instead of `scrollIntoView`. `scrollBy` does not attempt to scroll parent elements which avoids the WebKit issue.
- I also updated the initial scroll to …

fix(segment): avoid scrolling webkit bug

---

packages/angular/src/directives/navigation/ion-router-outlet.ts
packages/angular/standalone/src/navigation/router-outlet.ts
packages/angular/test/base/e2e/src/lazy/nested-outlet.spec.ts
packages/angular/test/base/e2e/src/standalone/tabs.spec.ts
packages/angular/test/base/src/app/lazy/nested-outlet-page/nested-outlet-page.component.html
packages/angular/test/base/src/app/lazy/nested-outlet-page/nested-outlet-page.component.ts
packages/angular/test/base/src/app/standalone/tabs/tab1.component.ts

Issue number: resolves #28417
---------
The common `IonRouterOutlet` was trying to inject another common `IonRouterOutlet` into `parentOutlet`: https://github.com/ionic-team/ionic-framework/blob/dc94ae01fe9e6c1b570559f0c8308b31e96cc5bf/packages/angular/common/src/directives/navigation/router-outlet.ts#L119 None existed, so this field was `null`.
This is a problem if developers are using the module `IonRouterOutlet` since parent router outlets will not be currently injected because Angular is trying to use the common `IonRouterOutlet` not the module `IonRouterOutlet`: https://github.com/ionic-team/ionic-framework/blob/main/packages/angular/src/directives/navigation/ion-router-outlet.ts. The same goes for the standalone `IonRouterOutlet`.
This resulted in things such as `NavController.pop` …

fix(angular): NavController works with nested outlets

---

core/package-lock.json
core/package.json
packages/angular/.prettierignore
packages/angular/src/directives/angular-component-lib/utils.ts
packages/angular/standalone/src/directives/angular-component-lib/utils.ts

Issue number: resolves #28418
---------
Due to https://github.com/ionic-team/stencil-ds-output-targets/issues/397, calling `proxyInputs` for the form controls caused an error to be logged in developer applications.
- Updated to a version of the Angular output targets with a patch for this error
- I also excluded the `utils.ts` from all `angular-component-lib` directories from prettier since it was causing a diff. These changes are autogenerated so we should not be linting them anyways.
Dev build: `7.5.3-dev.11698340692.18daff2f`

fix(angular): standalone form components do not error when multiple are used

---

packages/react-router/package.json
packages/react/package.json

---------
These scripts are old and do not do anything (`np` isn't even a dependency).
- Removed the scripts from react and react-router

chore: remove release scripts

---

core/src/components/picker-internal/test/basic/picker-internal.e2e.ts

---------
Sometimes the screenshot gets captured as
when it should be
- Hopefully the screenshot will be more consistent.

fix(test): reduce flakiness of picker internal screenshot test

---

core/src/components/toast/gestures/swipe-to-dismiss.ts

---------
The swipeable toast dismiss animation does not change based on how quickly the toast was swiped. This makes the animation seem sluggish.
- The toast now dismisses quicker depending on how quickly users swipe.

feat(toast): quickly swiping dismisses toast

---

core/src/utils/forms/form-controller.ts

---------
When using an `ion-label` as a `label` slot inside of an `ion-input`, `ion-textarea` or `ion-select` it erroneously flags the input as a legacy component and ignores the `label-placement`:
<table>
<tr>
<td>
Code
</td>
<td>
Result
</td>
</tr>
<tr>
<td>
<pre lang="html">
&lt;ion-item&gt;
&lt;ion-input label-placement="floating"&gt;
&lt;ion-label slot="label"&gt;
&lt;ion-icon name="home"&gt;&lt;/ion-icon&gt;
Slotted Label
&lt;/ion-label&gt;
&lt;/ion-input&gt;
&lt;/ion-item&gt;
&lt;ion-item&gt;
&lt;ion-input label-placement="floating" value="Value"&gt;
&lt;ion-label slot="label"&gt;
&lt;ion-icon name="person"&gt;&lt;/ion-icon&gt;
Slotted Label
&lt;/ion-label&gt;
&lt;/ion-input&gt;
&lt;/ion-item&gt;
</pre>
</td>
<td>
</td>
</tr>
</table>
Adds `ion-input`, …

fix(inputs): remove invalid legacy warnings in input, textarea, and select

---

core/src/components/header/header.ios.scss

Issue number: resolves #28466
---------
In https://github.com/ionic-team/ionic-framework/issues/27060 I fixed an issue where the main title would be visible briefly before the collapsible large title a) was configured and b) hid the main title. I accomplished this by using CSS to target `ion-header[collapse="condense"]`. However, I failed to account for when the property is not reflected on the host. Some JS frameworks allow the property to remain on the element but some do not.
- I improved this fix by also targeting the class set on the host. This class is set regardless of property reflection status.
| main | branch |
| - | - |
| <video src="https://github.com/ionic-team/ionic-framework/assets/2721089/991523da-8549-451b-930f-5df45c2783de"></video> | <video …

fix(header): collapsible large title does not flicker when collapse prop not reflected

---

core/src/components/radio-group/radio-group.tsx

Issue number: resolves #28356 
---------
`ion-radio-group` would not set the radio value when using it as a Angular standalone component and data binding:
```html
<ion-radio-group [value]="fromValue">
<ion-radio value="dogs">Dogs</ion-radio><br />
<ion-radio value="cats">Cats</ion-radio><br />
<ion-radio value="turtles">Turtles</ion-radio><br />
<ion-radio value="fish">Fish</ion-radio><br />
</ion-radio-group>
```
This is happening because the value is set before the [value watcher](https://github.com/ionic-team/ionic-framework/blob/c5dd622bbe353f4d43752ede702f60385160d5fc/core/src/components/radio-group/radio-group.tsx#L34) has been configured. The event, `ionValueChange`, does not get [dispatched](https://github.com/ionic-team/ionic-framework/blob/c5dd622bbe353f4d43752ede702f60385160d5fc …

fix(radio-group): emit value change on componentDidLoad

---

core/src/components/accordion-group/accordion-group.tsx

Issue number: resolves #28506 
---------
ion-accordion-group would not set the value when using it as a Angular standalone component and data binding:
``` html
<ion-accordion-group #accordionGroup [value]="fromValue">
<ion-accordion value="turtles">
<ion-item slot="header" color="light">
<ion-label>First Accordion</ion-label>
</ion-item>
<div class="ion-padding" slot="content">First Content</div>
</ion-accordion>
<ion-accordion value="second">
<ion-item slot="header" color="light">
<ion-label>Second Accordion</ion-label>
</ion-item>
<div class="ion-padding" slot="content">Second Content</div>
</ion-accordion>
</ion-accordion-group>
```
The problem here is Angular is setting the value of the accordion group after the component has been initialized (but not loaded) and before the component …

fix(accordion-group): correct accordion is open on load

---

packages/angular/test/base/cypress/support/commands.js
packages/angular/test/base/e2e/src/lazy/navigation.spec.ts
packages/angular/test/base/e2e/src/lazy/nested-outlet.spec.ts
packages/angular/test/base/e2e/src/lazy/router-link.spec.ts

---------
Our Angular E2E tests are brittle because they rely on arbitrary `cy.wait` calls to account for asynchronous routing. This leads to flaky tests on CI and seemingly random test failures when we make adjustments to the Ionic Anguar routing integration (see: https://github.com/ionic-team/ionic-framework/pull/28188)
Additionally, our test execution for the navigation tests is quite slow because transitions are enabled. As a result, we need to wait hundreds of ms per test just for the transitions to finish.
- Updated the `testStack` command to use a new `getStack` [Cypress query](https://docs.cypress.io/api/cypress-api/custom-queries). These queries come with automatic retrying built-in. By leveraging this query in the `testStack` command, we can avoid the arbitrary …

test(angular): remove routing waits in tests

---

packages/angular/tsconfig.json

---------
Type checking is disabled in the `standalone/` directory of the angular project.
- Enables type checking in the standalone directories.

chore(angular): type checking for standalone directory

---

packages/angular/common/src/providers/nav-controller.ts

Issue number: resolves #16569
---------
Ionic Angular's routing integration disables page transitions when using the browser back/forward buttons.
- Transitions now play when using the back/forward buttons
We're not aware of any breaking changes here, though it's possible some developers were relying on this behavior. As a result, we are targeting Ionic 8 to minimize any potential negative impact this fix may have on developers.
Supersedes https://github.com/ionic-team/ionic-framework/pull/28188
Dev build: `7.5.6-dev.11700068172.15ce9b35`

fix(angular): transition plays when using browser buttons

---

packages/angular/common/src/index.ts
packages/angular/src/index.ts
packages/angular/src/providers/alert-controller.ts
packages/angular/standalone/src/index.ts
packages/angular/standalone/src/providers/alert-controller.ts
packages/angular/test/base/e2e/src/lazy/providers.spec.ts
packages/angular/test/base/e2e/src/standalone/overlay-controllers.spec.ts
packages/angular/test/base/src/app/lazy/providers/providers.component.html
packages/angular/test/base/src/app/lazy/providers/providers.component.ts
packages/angular/test/base/src/app/standalone/overlay-controllers/overlay-controllers.component.html
packages/angular/test/base/src/app/standalone/overlay-controllers/overlay-controllers.component.ts

---------
As a takeaway from our learning session about a menuController bug in Ionic Angular, the team would like to update our other providers to use the same architecture as the menuController to prevent this kind of issue from happening again in the future.
We also noticed that the common provider does not provide much value and it's easier to just have two separate implementations in `src` and `standalone`. (There wasn't much code we could de-duplicate)
- Removed the common alert provider in favor of separate ones in src/standalone

refactor(angular): alert controller uses correct core instance

---

core/src/components/datetime/datetime.tsx

Issue number: resolves #28548
---------
Datetime was not scrolling at all when the `value` prop was changed programmatically. This was due to some logic we had in `componentDidRender` to work around a WebKit bug which was causing the scroll position to be moved back to where it was prior to setting the `value` prop. This caused the scroll position to never move.
- Datetime scrolls to the new value when `value` is updated programmatically even if `min` is set.
Dev build: `7.5.6-dev.11700169088.140f3e6a`
Co-authored-by:  amandaejohnston <amandaejohnston@users.noreply.github.com>

fix(datetime): updating value with min scrolls to new value

---

.github/CODEOWNERS

I noticed that Dependabot PRs never had anyone assigned: https://github.com/ionic-team/ionic-framework/pull/28586
The reason was that we removed `* @ionic-team/framework` when we adjusted the codeowners in https://github.com/ionic-team/ionic-framework/pull/27573. 
My original reasoning for why we should remove it was wrong. GitHub only assigns reviewers within a team if the team itself is assigned. By removing the team from being reviewed, only people listed in the codeowners file would be assigned. As an added example, PRs that do not match codeowners currently have no one assigned: https://github.com/ionic-team/ionic-framework/pull/28430

chore: fallback to framework team with codeowners

---

core/src/components/action-sheet/action-sheet.tsx
core/src/components/alert/alert.tsx
core/src/components/loading/loading.tsx
core/src/components/modal/modal.tsx
core/src/components/picker/picker.tsx
core/src/components/popover/popover.tsx
core/src/components/toast/toast.tsx

Issue number: resolves #28524
---------
Watchers in Stencil are constructed sometime between `connectedCallback` and `componentDidLoad`. If a property is set/changed during that time it is possible for the callback associated with the watcher to not fire because the watcher has not been setup yet. This is most often with `dist-custom-elements` and frameworks such as Angular when using a binding (i.e. `[trigger]` instead of `trigger`)
- The trigger callback associated with the watcher is manually called in `componentDidLoad` for each overlay.
Dev build: `7.5.5-dev.11699974376.13a15397`
Note: This is a timing related bug due to a behavior in Stencil, so I did not write automated tests. However, I manually verified that this issue a) reproduces on `main` and b) is fixed with this dev build …

fix(overlays): trigger is configured on load

---

core/setupJest.js
core/src/components/range/test/range.spec.ts
core/src/jest.d.ts
core/stencil.config.ts

---------
- Adds a custom matcher to the jest configuration for Stencil to enable using `expect(el).toHaveShadowPart('partName')`

chore(jest): toHaveShadowPart custom matcher

---

core/api.txt
core/src/components/checkbox/checkbox.scss
core/src/components/checkbox/checkbox.tsx
core/src/components/checkbox/test/checkbox.spec.ts

Issue number: Part of #28300 
---------
Developers are unable to adjust margin, width, etc. of the checkbox label
- Checkbox label has a shadow part.
As part of this work, I investigated moving `pointer-events: none` up the DOM tree so developers wouldn't be able to override it with the shadow part. In my testing, I was unable to see any difference in behavior with vs without `pointer-events: none`. Therefore, I removed it entirely.

feat(checkbox): add shadow part for label

---

core/api.txt
core/src/components/radio/radio.scss
core/src/components/radio/radio.tsx
core/src/components/radio/test/radio.spec.ts

Issue number: Part of #28300 
---------
Developers are unable to adjust margin, width, etc. of the radio label
- Radio label has a shadow part.
As part of this work, I investigated moving `pointer-events: none` up the DOM tree so developers wouldn't be able to override it with the shadow part. In my testing, I was unable to see any difference in behavior with vs without `pointer-events: none`. Therefore, I removed it entirely.

feat(radio): add shadow part for label

---

packages/react-router/src/ReactRouter/ReactRouterViewStack.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/src/ReactRouter/utils/matchPath.ts
packages/react-router/test/base/src/pages/routing/Details.tsx
packages/react-router/test/base/tests/e2e/specs/routing.cy.js

Issue number: Resolves #26524 
---------
**Parameterized routes**: A route that includes one or more variables in the path segments, such as `/form/:index`. 
When an application routes from a parameterized route, to an intermediary route, to the same parameterized route, but with a different value/url, Ionic's routing logic is incorrectly reusing the view item from the first instance of the parameterized route instead of calculating that the matched path is different. This results in the wrong view item being recycled and rendered.
Another way of representing it:
- User navigates to `/form/0` which resolves `FormPage`
- User enters `0` into the form and submits the form
- User navigates to `/link`, which resolves `LinkPage`
- User navigates to `/form/1`, which resolves `FormPage`
- …

fix(react): router creates new view instances of parameterized routes

---

core/src/components.d.ts
core/src/components/input/input.tsx
core/src/components/searchbar/searchbar.tsx
core/src/components/textarea/textarea.tsx

Issue number: Related to #18132 
---------
The documentation about the `autofocus` prop is unclear and does not accurately reflect how it actually works across browsers and devices.
- The documentation for `autofocus` and `setFocus` are more detailed.
- The documentation links to the relevant page in the docs.

docs(input, searchbar, textarea): improve docs for managing focus

---

.github/labeler.yml
.github/workflows/label.yml

---------
The labeler action is currently failing: https://github.com/ionic-team/ionic-framework/actions/runs/7090913880/job/19298918578?pr=28622. This is happening due to a breaking change in v5 of the action.
We currently pull from `main` for this action so we are now receiving v5 of the action: https://github.com/ionic-team/ionic-framework/blob/fe3c3d500a2afd716ebde81a75b357b7c79d4920/.github/workflows/label.yml#L16
- This PR updates the action explicitly to v5 so we don't unexpectedly take on breaking changes
- This PR also updates the labeler yaml file to account for the v5 breaking changes

chore(ci): update labeler workflow for labeler@v5

---

packages/angular/common/src/providers/menu-controller.ts

Issue number: resolves #20053 
---------
There are a few methods that that are missing for the menu in the Angular packages. This leads to users to not being able to use methods like `isAnimating()`. 
- The missing methods have been added by implementing `MenuControllerI`.
Dev build: 7.5.8-dev.11701461830.1be851fd

fix(angular): add missing menu controller methods

---

CHANGELOG.md

We got some feedback in https://github.com/ionic-team/ionic-framework/pull/28146#issuecomment-1845005089 that it would be helpful to note the new item wrapping behavior in v7.6. I've updated the Github release, and this PR updates the Changelog file.

chore: note item behavior in 7.6 notes

---

core/src/components/radio/test/a11y/radio.e2e.ts

Skips the keyboard navigation test in the radio a11y due to it being flaky: https://github.com/ionic-team/ionic-framework/actions/runs/7131071726

test(radio): skip flaky radio tabbing test

---

packages/react-router/src/ReactRouter/IonRouter.tsx

Issue number: resolves #28673
---------
When reviewing https://github.com/ionic-team/ionic-framework/pull/28671 I noticed a bug where the custom animation was not used when going back after a replace.
`handleNavigate` will override whatever is in `incomingRouteParams`. Since we were passing `routeAnimation` (which is `undefined`), it was overriding the animation we set in `handleNavigateBack`.
- `routeAnimation` is no longer overridden
Dev build: `7.6.1-dev.11702048520.13c82dad`

fix(react): use custom animation when going back after a replace

---

core/CHANGELOG.md
core/src/components/input/input.tsx
core/src/components/input/test/clear-on-edit/input.e2e.ts
core/src/components/textarea/test/clear-on-edit/textarea.e2e.ts
core/src/components/textarea/textarea.tsx

Issue number: resolves #28633
---------
In https://github.com/ionic-team/ionic-framework/pull/28005 I introduced a fix that causes "clearOnEdit" to not clear input/textarea when the Tab key was pressed. However, there were several edge cases I missed. For instance, pressing the "shift" key and then the "tab" key would still clear the input because "shift" was not explicitly excluded.
- Input and textarea now explicitly ignores modifier keys that do not change the value of the input
- `didInputClearOnEdit` is not set to `true` when an ignored key is pressed. Otherwise, pressing an ignored key and then an accepted key would not cause the input to be cleared. For example, pressing "shift", releasing "shift", then pressing "A" should cause the input to still get cleared.
- Added test coverage …

fix(input, textarea): clearOnInput ignores key modifiers

---

packages/react-router/src/ReactRouter/IonRouter.tsx

Issue number: resolves #24260
---------
When replacing a route (`router.push(newRoute, 'none', 'replace')`) the `RouterDirection` from the route being replaced is being used (if it exists) instead of the new one the user specifies.
User-specified `RouteDirection` is used, if it exists. If it doesn't it falls back to the `RouteDirection` of the route being replaced.
Please see the following comment for why I think the current behavior is incorrect, and why this change is needed: https://github.com/ionic-team/ionic-framework/issues/24260#issuecomment-1078960780

fix(react): replacing route uses new route direction and animation

---

core/src/css/core.scss

Older versions of WebKit used an old `constant()` syntax for safe area variables: https://caniuse.com/?search=env
As of Safari 11.3, `env()` is supported instead. We haven't supported Safari 11 in years, so I think this is safe to remove.

chore: remove safari 11 code

---

.github/PULL_REQUEST_TEMPLATE.md

I've noticed a few instances where the team forgets to add the "resolves" keyword (or similar "closes"/"fixes" keywords) when linking a PR to an issue. GitHub will not link the PR with the issue and will not close the issue on PR merge unless one of these keywords is used.
I've updated the PR template to add the "resolves" keyword so team members don't need to worry about remembering to add it.

chore: add resolves to PR template

---

packages/react/src/components/utils/index.tsx

---------
Ionic React projects using `@types/react@18.2.43` or greater will run into a type-check error on build with `IonRouterOutlet` and potentially other components:
```
Property 'placeholder' is missing in type '{ children: Element[]; }' but required in type 'Pick<IonRouterOutlet & { basePath?: string | undefined; ref?: Ref<any> | undefined; ionPage?: boolean | undefined; } & IonicReactProps & Omit<...>, "color" | ... 254 more ... | "ionPage">'.
```
Definitely typed decided to make a breaking type change in a patch release: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b954269038de46b4b2f1756a9f2f020cbc66a326
- Patches the type to allow for compatibility between React v16, 17 and 18. 
1. Create a new Ionic react project with the "list" template.
2. Run …

fix(react): avoid type collision with @types/react@18.2.43 and greater

---

.github/PULL_REQUEST_TEMPLATE.md

The team had feedback during a sprint retro that the breaking change process documentation was a bit spread out. In particular, some team members were not clear that you need to a) update the breaking.md file and b) add the "BREAKING CHANGE" comment to the commit description.
This PR adds both of these things are comments for awareness.

chore: update PR template for breaking changes

---

core/src/utils/test/playwright/docs/best-practices.md

This best practice currently resides in our internal testing process docs. I think this is valuable information for contributors to have as well, so I've added it to our public best practices doc.

docs(test): add locale best practice

---

core/api.txt
core/src/components/picker/picker.tsx
packages/angular/src/directives/proxies.ts
packages/angular/standalone/src/directives/proxies.ts

When reviewing https://github.com/ionic-team/ionic-docs/pull/3321 I noticed that the `ionInputModeChange` event on `ion-picker` was documented. This is an internal API only used for text entry mode (which is also an internal API). This PR adds the `@internal` comment so it is not publicly documented.

chore(picker): mark ionInputModeChange as internal

---

core/api.txt
core/src/components.d.ts
core/src/components/refresher/refresher.tsx
packages/angular/src/directives/proxies.ts
packages/angular/standalone/src/directives/proxies.ts

Issue number: resolves #28716
---------
All components that have per-mode stylesheets can have their mode adjusted by setting `mode` on the component. We use the `setMode` function to determine which mode to use on the component: https://github.com/ionic-team/ionic-framework/blob/516b84475e5d78060f35fa2c4821efc712536353/core/src/global/ionic-global.ts#L75
While this works on refresher, it is missing the `virtualProp` jsdoc comment which causes it to not have the appropriate type information. As a result, when developers try to use a JS binding for `mode`, they will get compilation errors.
- Adds virtualProp for mode to refresher
I am considering this a bug fix instead of a feature. In non-TypeScript environments you can set `mode` on `ion-refresher` and it does change the mode. What's …

fix(refresher): mode property can be used in typescript

---

BREAKING.md

---------
The picker heading level is currently an `h2`, where the other component headings are `h4`.
- Updates the heading level for Picker to `h4`.

chore(breaking): update picker component heading level

---

core/src/components.d.ts
core/src/components/datetime/datetime.tsx
core/src/components/input/input.tsx
core/src/components/modal/modal.tsx
core/src/components/range/range.tsx
core/src/components/textarea/textarea.tsx

---------
In https://github.com/ionic-team/ionic-framework/issues/28694 there was some confusion around how to access `this` inside of a callback function passed to a property on Ionic components. The root issue was due to how the `this` context is determined with developers being responsible for setting the appropriate `this` context.
- While this isn't an Ionic bug, I think it's worth calling out this behavior so developers are aware of how to account for it.
Note: The link in the docs will not work until https://github.com/ionic-team/ionic-docs/pull/3333 is merged.

docs: account for this context

---

core/src/components/content/content.tsx
core/src/components/refresher/test/a11y/refresher.e2e.ts

---------
Maria noted that the way we set the main landmark is not correct and causes accessibility violations.
- Instead of rendering a main element inside of ion-content, the content itself is the main landmark.

fix(content): main landmark is set correctly

---

core/src/components/refresher-content/refresher-content.tsx
core/src/components/refresher/refresher.utils.ts

Issue number: resolves #28617
---------
We currently check to see if `webkitOverflowScrolling` is supported on the refresher's style object in order to enable to native iOS refresher. This works well for iOS, but it does not work for iPadOS. This is because this property was removed in iPadOS 13: https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes
> Disabled -webkit-overflow-scrolling: touch on iPad. All frames and scrollable overflow areas now use accelerated one-finger scrolling without changing stacking.
As a result, the native iOS refresher does not activate on iPadOS.
- I think it's safe to assume that `webkitOverflowScrolling` may be removed on iOS in the future too since it was already removed on iPadOS. As a result, I implemented a solution that …

fix(refresher): native ios refresher works on iPadOS

---

core/src/components/radio/test/a11y/radio.e2e.ts
core/src/components/radio/test/legacy/a11y/radio.e2e.ts

---------
The keyboard navigation tests for radio were disable due to flakiness with Safari when it came to the CI.
- Re-enabled the tests.
Debugging was done with a saved artifact.
The artifact didn't provide a clear reason of why it flakes. But it did seem that the test was tabbing before the Safari page finished loading. I've added a `waitFor()` to verify that the radios have rendered. This was done for Safari only to prevent any additional wait time. 
There is no great way to test this since it only flakes on GitHub.

test(radio): re-enable keyboard navigation

---

core/src/components/radio-group/radio-group.tsx

Issue number: resolves #28677
---------
Defining disabled a `@Prop() disabled = false` causes Stencil to mark this property as optional. This behavior is not desired on our end, but making the property required would be a breaking change. Additionally, the root issue is due to how Stencil resolves types. 
For example, `disabled` is [optional in the LocalJSX namespace](https://github.com/ionic-team/ionic-framework/blob/e96a1457a32646fa23c8218cb3cca4a8215ad115/core/src/components.d.ts#L6921) but [required in the Components namespace](https://github.com/ionic-team/ionic-framework/blob/e96a1457a32646fa23c8218cb3cca4a8215ad115/core/src/components.d.ts#L2239). Addressing this inside of Stencil is significant breaking change. As a result, the team has decided to compromise and support the falsy …

fix(radio-group): radio disabled prop can be undefined

---

core/src/components/input/input.scss

Issue number: resolves #28762
---------
Focused inputs have `pointer-events: none`. This code was added in https://github.com/ionic-team/ionic-framework/commit/e27452b789232c0a3222a03e75de1a9af19d3411 to address https://github.com/ionic-team/ionic-framework/issues/5536. However, this causes slotted buttons to not be clickable when the input is focused because pointer events have been removed.
This also causes the input to blur whenever you tap the label text.
This behavior only exists on `ion-input`. Textarea is not affected.
This code was added several years ago for the (now) legacy syntax. I don't have full confidence that this won't break the legacy input because there's not a lot of context around why specifically this code was added. As a result, I scoped these styles only to the …

fix(input): slotted buttons are clickable

---

core/src/components/app/app.tsx
core/src/components/menu/menu.tsx
core/src/utils/browser/index.ts
core/src/utils/config.ts
core/src/utils/hardware-back-button.ts
core/src/utils/overlays.ts
core/src/utils/test/hardware-back-button.spec.ts

Issue number: resolves #28703
---------
Users are unable to dismiss modals and menus via the hardware back button in a mobile web browser/PWA.
- This PR adds a new feature that allows developers to leverage the CloseWatcher API. This enables hardware back button support in web browsers/PWAs.
Dev build: `7.6.1-dev.11702569564.1746fa9f`
Full design doc: https://github.com/ionic-team/ionic-framework-design-documents/pull/205

feat: add experimental hardware back button support in browsers

---

core/src/css/themes/dark.always.scss
core/src/css/themes/dark.class.scss
core/src/css/themes/dark.scss
core/src/css/themes/dark.system.scss
core/src/css/utils.bundle.scss

---------
The dark theme is not exported for use in Ionic Framework apps
- The dark theme is usable in Ionic Framework apps via any of the following:
- The `ion-theme-dark` class (once the developer assigns this class to the `html` element in their app) via dark.class.css
- The `prefers-color-scheme` media query via dark.system.css
- Throughout the full app via dark.always.css
Usage:
```
@import '~@ionic/core/css/themes/dark.always.css';
/* @import '~@ionic/core/css/themes/dark.class.css'; */
/* @import '~@ionic/core/css/themes/dark.system.css'; */
```
replace `~@ionic/core` with the relevant package
Dev build: `7.5.8-dev.11704294569.1abc989d`
Note to reviewers: the design doc says to include these files in utils.bundle.scss. Doing this causes the dark theme to get …

feat(themes): add dark theme files and mixins

---

core/src/components/menu/menu.tsx
core/src/components/spinner/spinner-interface.ts
core/src/components/spinner/spinner.tsx
core/src/components/split-pane/split-pane.tsx
core/src/utils/helpers.ts
core/src/utils/transition/ios.transition.ts

---------
As part of FW-2832 the team has an initiative to remove much of the `any` usage in favor of stronger types. This will make modifications to this codebase safer as we will have access to proper type checking.
- Removed several `any` usages in favor of stronger types.
Note that not all of the `any` types within these files have been removed. I mainly stuck to the low hanging fruit 😄 
I intentionally made type changes that do not impact public APIs. Any incorrect type changes would cause our CI checks to fail.

chore: add strong types in several places

---

.github/workflows/release.yml

In https://github.com/ionic-team/ionic-framework/pull/28697 I moved the package-lock work to its own step to lets us re-run that if it fails. However, I forgot to checkout the project files in that step, so there was no `package-lock.json` file to update [resulting in an error](https://github.com/ionic-team/ionic-framework/actions/runs/7398703880/job/20128761433).

chore(ci): checkout files when updating package-lock

---

core/src/components/split-pane/split-pane.tsx

---------
As part of FW-2832 the team has an initiative to remove much of the `any` usage in favor of stronger types. This will make modifications to this codebase safer as we will have access to proper type checking.
- Removed the `any` case from window.matchMedia. This causes the linter to fail because `window.matchMedia` is always defined. I removed the check altogether. `matchMedia` is supported on all browsers that Ionic 7 supports. This should not cause any changes for Ionic developers, but I want to ship this a) in a separate patch and b) in a minor release to de-risk just in case there's an edge case I am not considering

chore: remove matchMedia check

---

.github/workflows/release.yml

The update-package-lock job did not configure Git credentials correctly. As a result, the job is unable to push the `package-lock.json` changes to the repo: https://github.com/ionic-team/ionic-framework/actions/runs/7476310958/job/20346663176
This PR configures the job with the correct credentials.

chore(ci): use correct github credentials for pushing

---

core/src/components/list/list.md.scss

---------
In MD mode, items in an inset list currently receive their own border radius, separate from the border radius also applied to the inset list itself. The original intent was likely to ensure that the corners of the items don't spill out of the list. However, the item's border radius is no longer needed, for two reasons:
1. MD has since added top/bottom padding to their lists ([spec](https://m2.material.io/components/lists#specs)), which we've mirrored. This means the borders no longer line up anyway.
2. Even if a developer removes the list's vertical padding (we set it on the host [here](https://github.com/ionic-team/ionic-framework/blob/535b8ed72486a1e94125c72b12d5b447b630f8c4/core/src/components/list/list.md.scss#L9), so it's easy to overwrite), inset lists …

fix(list): remove uneeded border radius from items in inset list

---

BREAKING.md
core/api.txt
core/src/components.d.ts
core/src/components/nav/nav.tsx
core/src/components/nav/test/nav-controller.spec.ts

Issue number: resolves #28826
---------
`getLength` used to be a public method on `ion-nav`. However, the `@Method` decorator was removed in https://github.com/ionic-team/ionic-framework/commit/1d46973785aa204e13a44a740c9df75751d9f88d#diff-4b2ac275268173207c99a590b0ced8b67dc3d697815eb51a3c0546ee7cb0c0aeR429-L445.
While the removal of `@Method` from `isAnimating` was likely intentional, the team thinks that removing it from `getLength` was an accident. Otherwise, it's challenging to call methods like `removeIndex` if you don't know how many items are in the stack. For example, if a developer wants to remove the second to last item, they need to know how many items are in the stack so they don't give an index that is out of bounds.
- `getLength` is now a public method
The team is …

fix(nav): getLength is part of the public API

---

packages/angular/src/index.ts

Issue number: resolves #28827
---------
This import was renamed to `IonBackButton` as part of https://github.com/ionic-team/ionic-framework/pull/28311/commits/9f20780d66a113410e5450139f8ecab3a9d4a0c9. However, we did not consider that some developers are importing this to use with `ViewChild`. While we should keep alignment with other component imports, we need to support the old import until we can make a breaking change in Ionic 8.
- Adds the old IonBackButtonDelegate import
Dev build: `7.6.5-dev.11705352188.1c6cdb08`

fix(angular): add old IonBackButtonDelegate import

---

core/src/components/select/select.tsx
core/src/components/select/test/select.spec.tsx

Issue number: resolves #28818
---------
Select has logic in place to prevent the overlay from opening when clicking the slotted content. As part of this, we need to deal with the `<label>` element dispatching another click that then bubbles up and causes the overlay to open when clicking the slotted content. We currently deal with this by calling `preventDefault` which prevents this extra event from being dispatched only when clicking the slotted content.
We also call `stopPropagation`. This code is not necessary, and in most cases should not have any adverse effects on developer applications. However, this does impact React applications due to how React handles events. When a developer places `onClick` on a slotted element, a native "click" listener is not immediately applied to that …

fix(select): click handlers on slotted content fire

---

core/src/components/segment/segment.tsx

Issue number: resolves #28816
---------
The value is set on Segment asynchronously when binding it in Angular. However, the timing works out such that the value changes after `connectedCallback` is fired but before any Stencil Watchers are configured. As a result, our `value` property watcher does not fire which causes `ionSelect` to not be emitted. Segment Buttons rely on this event to know when to update their state (if the value changes such that a segment button is now selected). This results in a checked segment button not appearing checked.
This is similar to other issues that have been fixed:
https://github.com/ionic-team/ionic-framework/pull/28510
https://github.com/ionic-team/ionic-framework/pull/28488
https://github.com/ionic-team/ionic-framework/pull/28526
- Segment now emits …

fix(segment): setting value via binding updates button state

---

core/src/components/picker-internal/picker-internal.tsx
core/src/components/picker-internal/test/keyboard-entry/picker-internal.e2e.ts

Issue number: resolves #28325
---------
When typing the time into the date picker pressing "Enter" does not close the on-screen keyboard.
- Pressing "Enter" closes the on-screen keyboard
Test:
⚠️ While I have a test for this, please also test this on a physical Android device.
1. Go to `src/components/datetime/test/basic`
2. Open the time picker (in any of the date times)
3. Tap the time to open the keyboard
4. Press "Enter" on Android. Observe that the keyboard closes.
Dev build: `7.6.6-dev.11705528328.1ef5e17b`

fix(datetime): enter closes keyboard when typing time

---

core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/multiple/datetime.e2e.ts

Issue number: resolves #28602
---------
We animate to the new date when the value is changed, but we do not account for multiple selection. This behavior is valuable for when the value is set asynchronously on a different month than what it shown.
However, this is confusing when there are multiple dates selected in different months, because we do not reasonably know which date to animate to.
Datetime no longer animates to the new value if more than one date is selected, and the selected dates aren't all in the same month.
An alternative strategy would be to always animate unless one of the selected dates is in the month currently being viewed. However, this would still mean guessing at which value the user wants to see, which we are trying to avoid.
Based on this PR: …

fix(datetime): do not animate to new value when multiple values in different months are set

---

core/src/css/core.scss

Issue number: resolves #28399
---------
As part of https://github.com/ionic-team/ionic-framework/pull/26976 I fixed an issue where `pointer-events: none` was not applied until after the menu open gesture finishes. This resolved a bug where scrolling was latching after the menu gesture starts.
However, I did not account for the edge case where scrolling latches _before_ `pointer-events: none` is applied in the DOM. Since scrolling has already latched then `pointer-events: none` does not change the scrolling behavior. This can happen if a user swipes up and to the right from the left edge of the screen.
- `overflow-y: hidden` is now applied to the scrollable content which will interrupt any scrolling when the menu is open.
Testing:
This bug fixes a timing issue where scrolling latches on …

fix(menu): improve reliability of main content not being scrollable when menu opens

---

core/src/components/button/test/basic/button.e2e.ts
core/src/components/datetime-button/test/basic/datetime-button.e2e.ts
core/src/components/datetime-button/test/disabled/datetime-button.e2e.ts
core/src/components/datetime-button/test/multiple/datetime-button.e2e.ts
core/src/components/datetime/test/a11y/datetime.e2e.ts
core/src/components/datetime/test/basic/datetime.e2e.ts
core/src/components/datetime/test/datetime.e2e.ts
core/src/components/datetime/test/disable-dates/datetime.e2e.ts
core/src/components/datetime/test/disabled/datetime.e2e.ts
core/src/components/datetime/test/display/datetime.e2e.ts
core/src/components/datetime/test/locale/datetime.e2e.ts
core/src/components/datetime/test/minmax/datetime.e2e.ts
core/src/components/datetime/test/month-year-picker/datetime.e2e.ts
core/src/components/datetime/test/multiple/datetime.e2e.ts
core/src/components/datetime/test/position/datetime.e2e.ts
core/src/components/datetime/test/prefer-wheel/datetime.e2e.ts
core/src/components/datetime/test/presentation/datetime.e2e.ts
core/src/components/datetime/test/readonly/datetime.e2e.ts
core/src/components/datetime/test/set-value/datetime.e2e.ts
core/src/components/datetime/test/time-label/datetime.e2e.ts
core/src/components/datetime/test/values/datetime.e2e.ts
core/src/components/header/test/condense/header.e2e.ts
core/src/components/modal/test/standalone/modal.e2e.ts
core/src/components/refresher/test/test.utils.ts
core/src/components/ripple-effect/test/basic/ripple-effect.e2e.ts

---------
There are some tests that use Playwright's `waitForSelector` [function](https://playwright.dev/docs/api/class-page#page-wait-for-selector). However, Playwright has informed the community to not use this function by labeling it as [discouraged](https://playwright.dev/docs/api/class-page#page-wait-for-selector).
- Replaced `waitForSelector` with the [recommended](https://playwright.dev/docs/api/class-page#page-wait-for-selector) `waitFor` [function](https://playwright.dev/docs/api/class-locator#locator-wait-for).
N/A

test(many): replace waitForSelector with waitFor

---

core/src/components/item/item.tsx
core/src/components/item/test/buttons/index.html
core/src/components/item/test/item.spec.tsx

Issue number: resolves #28525
---------
When navigated via tab-key, the ion-item is not highlighted correctly after switching from button=false to button=true.
Now, when dynamically changing the the `button` option to `True`, there's a `@watch` callback that will make sure the internal `isFocusable` `@state` will be updated.  
- A new unit test was added to item/test. As there was still any unit test for the `ion-item`, a new files was created - `item.spec.tsx`
New behavior in runtime:

fix(item): ensure button focus state on property change

---

packages/react/test/base/tests/e2e/specs/overlay-components/IonPicker.cy.ts
packages/react/test/base/tests/e2e/specs/overlay-hooks/useIonPicker.cy.ts

---------
The `IonPicker` tests in the React app were skipped due to a Stencil bug that has since been resolved.
Tests re-enabled.

test(react): re-enable picker tests

---

packages/react-router/rollup.config.mjs
packages/react/rollup.config.mjs

---------
React and React Router packages do not build correctly on Windows because certain dependencies were not marked as external.
- 3rd party packages are correctly marked as external

refactor(react, react-router): build works on windows

---

core/src/themes/ionic.theme.default.scss

---------
In https://github.com/ionic-team/ionic-framework/pull/28814, we updated the default and dark themes to define the stepped color tokens. This caused the light mode fallback colors to never apply when we added support for the new stepped colors to components such has datetime button.
For example, `date time-button` has a default theme fallback of [#edeef0](https://github.com/ionic-team/ionic-framework/blob/58639c7a1e0417c2b8bf7d709ea2efd600b44021/core/src/components/datetime-button/datetime-button.scss#L27).
When updating to support the new step colors, the syntax will be `var(--ion-color-step-300, var(--ion-background-color-step-300), #edeef0)`. However, since `--ion-background-color-step-300` is always defined, the fallback of `#edeef0` will never be used.
- …

fix: remove default light mode tokens

---

BREAKING.md
core/api.txt
core/src/components.d.ts
core/src/components/input/input.tsx
packages/angular/src/directives/proxies.ts
packages/vue/src/proxies.ts

---------
The `ion-input` component currently specifies a `size` attribute to align with the HTML `input` implementation. However, Ionic's custom appearance for MD and iOS is not compatible and should not be used with the `size` attribute: https://github.com/ionic-team/ionic-framework/issues/27945#issuecomment-1669702274.
- The `size` property has been removed from `ion-input`.
The `size` attribute has been removed from `ion-input`. As it was not compatible before, this is likely to have a minimal impact to developers. If your application is using the `size` attribute, replace the usage with CSS styling to control the width of the `ion-input`.

feat(input): remove size property in favor of CSS styling

---

core/src/components/input/input.scss

---------
Input has a couple of styles that were using the wrong step tokens. Non-text colors (background, border, etc) should be using `$background-color-step-*` while text colors (like color) should be using `$text-color-step-*`.
-  Updated the `color` to use `$text-color-step-*` instead of `$background-color-step-*`.
The correct number is to subtract wrong token number from 1000. For example:
```scss
// wrong
color: #{$background-color-step-550};
```
1000 - 550 = 450
```scss
// correct
color: #{$text-color-step-450};
```
No visual differences are expected.

refactor(input): update to use correct step tokens

---

core/src/components/alert/alert.md.vars.scss

---------
Alert is using the wrong type of step tokens for a couple styles -- only text elements should use `$text-color-step-*`, while everything else (including borders) should use `$background-color-step-*`.
Tokens updated, including changing the step values so the actual color resolved remains the same.

refactor(alert): use correct color step tokens

---

core/src/components/picker/picker.ios.scss

---------
The picker highlight only uses the `--ion-color-step-150` variable with a fallback to `#eeeeef`.
The picker highlight falls back to using the `--ion-background-color-step-150` variable if it is defined but prioritizes `--ion-color-step-150` if it is also defined. This is the new step color token added for high-contrast themes.
No visual diffs are expected.

refactor(picker): update to use new step token

---

core/src/components/segment-button/segment-button.ios.vars.scss

---------
The segment button checked indicator only uses the `--ion-color-step-350` variable with a fallback to the `--ion-background-color`.
The segment button checked indicator falls back to using the `--ion-background-color-step-350` variable if it is defined but prioritizes `--ion-color-step-350` if it is also defined. This is the new step color token added for high-contrast themes.
No visual diffs are expected.

refactor(segment-button): update to use new step token

---

core/src/components/toast/toast.md.vars.scss

---------
The toast container background and toast text color were using the following:
```scss
/// @prop - Background of the toast
$toast-md-background: $text-color-step-200 !default;
/// @prop - Color of the toast
$toast-md-color: $background-color-step-50 !default;
```
Which evaluated to:
```css
:host {
--background: var(--ion-color-step-800, var(--ion-text-color-step-200, #333333));
--color: var(--ion-color-step-50, var(--ion-background-color-step-50, #f2f2f2));
}
```
The variables have been updated so that the `background` variable is used for the background of the toast container and the `text` variable is used for the text color of the toast:
```scss
/// @prop - Background of the toast
$toast-md-background: $background-color-step-800 !default;
/// @prop - …
```

refactor(toast): use the correct step color tokens for background and text

---

core/src/components/modal/modal.scss

---------
The modal handle only uses the `--ion-color-step-350` variable with a fallback to `#c0c0be`.
The modal handle falls back to using the `--ion-background-color-step-350` variable if it is defined but prioritizes `--ion-color-step-350` if it is also defined. This is the new step color token added for high-contrast themes.
No visual diffs are expected.

refactor(modal): update to use new step token

---

core/src/components/modal/modal.tsx
core/src/components/modal/test/animations/modal.e2e.ts
core/src/utils/overlays.ts

Issue number: resolves #28352
---------
Not all animations are getting properly destroyed after they run. This means that styles can get stuck at the end value of their animation. 
Specifically for this reproduction (as reported in the bug ticket), if the modal animates from 1 to 0 opacity and then the modal gets reopened with a different animation where the opacity should be 1 throughout (i.e. the opacity isn't supposed to animate at all), the modal is invisible because the opacity got stuck at 0 and never got reset to the default value of 1.
This bug is probably causing some incorrect behavior on other edge cases with overlays, but this is the only one I've identified.
Note: you cannot reproduce this when using a modalController
1. Open a modal, e.g. [this …

fix(overlays): tear down animations after dismiss

---

core/src/components/textarea/textarea.scss

---------
Textarea has a couple of styles that were using the wrong step tokens. Non-text colors (background, border, etc) should be using `$background-color-step-*` while text colors (like color) should be using `$text-color-step-*`.
-  Updated the `color` to use `$text-color-step-*` instead of `$background-color-step-*`.
The correct number is to subtract wrong token number from 1000. For example:
```scss
// wrong
color: #{$background-color-step-550};
```
1000 - 550 = 450
```scss
// correct
color: #{$text-color-step-450};
```
No visual differences are expected.

refactor(textarea): update to use correct step tokens

---

packages/angular/package.json
packages/angular/scripts/build-core.js
packages/react/package.json
packages/react/scripts/copy.js
packages/vue/package.json
packages/vue/scripts/copy-css.js

---------
CSS is not copied from the `core/` package when running each respective framework package in watch mode. 
- Copies the global styles from the `core/` package to each respective framework package when running the build in watch mode. 
Note: This does not register a file watcher to copy CSS updates after the initial command is ran. This just avoids a scenario of the global styles being updated and the developer _not_ running a `pnpm build` prior to running `pnpm build.watch` and the global styles not being reflected in the framework package.

chore(angular,react,vue): copy css with build.watch

---

packages/angular/test/build.sh
packages/react/test/build.sh
packages/vue/test/build.sh

---------
- Improves the developer message when generating a test app to include the next steps to running the test app.

chore(test-apps): improve developer message with test apps

---

packages/angular/src/schematics/utils/config.ts

---------
`schematicOpts` has an intersection type in order to be backward compatible.
- Remove the added type since `SchematicOptions` type now includes `[property: string]: any;` with Angular 16.
`schematicOpts` has the same type, just a different way of getting it.
N/A

chore(angular): remove type merging for schematic options

---

core/src/components/breadcrumb/breadcrumb.ios.vars.scss
core/src/components/breadcrumb/breadcrumb.md.vars.scss
core/src/components/breadcrumb/breadcrumb.vars.scss

---------
The breadcrumbs use the `--ion-color-step` tokens or a fallback.
- The breadcrumb text colors use the `--ion-color-step` tokens or the `--ion-text-color-step` tokens or a fallback
- The breadcrumb background colors use the `--ion-color-step` tokens or the `--ion-background-color-step` tokens or a fallback

refactor(breadcrumb): use new step color tokens

---

core/src/components/refresher/refresher.ios.vars.scss
core/src/components/refresher/refresher.md.vars.scss

---------
The refresher uses the --ion-color-step tokens or a fallback.
- The refresher colors use the --ion-color-step tokens or the --ion-text-color-step tokens or a fallback
- The refresher background colors use the --ion-color-step tokens or the --ion-background-color-step tokens or a fallback

refactor(refresher): use new step color tokens

---

packages/angular/test/README.md

Issue number: None
---------
People adding a new Angular test app don't know they need to update the Stencil nightly build.
- Documentation exists for adding a new Angular version to the Stencil nightly build when creating a new Angular test app..
This is related to #28945

docs(angular test app): include instructions for updating nightly build

---

packages/angular/test/build.sh
packages/react/test/build.sh
packages/vue/test/build.sh

---------
The packages, Angular, React, and Vue, will accept any `app_dir` parameter when passing it to the build script. This can lead to a user to entering a directory that doesn't exist within `test/apps`. If this happens, then the build folder will include an incomplete test app.
For example:
1. `./build ng13`
2. This creates a `build/ng13` folder, but the folder only contains the contents from the `base` folder. This causes it to be incomplete.
- Provides a message that the provided app directory doesn't exist.
- Does not create the incomplete app when an invalid app directory is given.
N/A

refactor(angular, react, vue): add missing test app msg

---

packages/angular/test/base/src/app/standalone/value-accessors/value-accessor-test/value-accessor-test.component.ts

---------
Angular test app imports `CommonModule`
Angular test app imports `NgFor` since we dropped support for Angular 14
This can be tested locally by [building the Angular test app](https://github.com/ionic-team/ionic-framework/blob/FW-5196/packages/angular/test/README.md) in both `ng16` and `ng17` and running it to confirm it works properly.

refactor(angular): update test app to use NgFor instead of CommonModule

---

core/src/css/themes/high-contrast-dark.scss
core/src/css/themes/high-contrast-light.scss
core/src/themes/ionic.globals.scss

---------
Developers are unable to globally change the placeholder opacity for inputs, textareas, searchbars, and selects. This becomes particularly problematic when trying to apply a high contrast theme.
- Adds the `--ion-placeholder-opacity` with a fallback of `0.6` (this fallback is unchanged)
- Sets the `--ion-placeholder-opacity` to `0.8` for the high contrast light & dark themes
> [!NOTE]
> The ticket says to update the standard light and dark themes to define `--ion-placeholder-opacity: 0.6`, however, I did not do this because this is not different than the fallback and therefore does not need to be defined. 
Documentation pull request: https://github.com/ionic-team/ionic-docs/pull/3421

feat(theming): add a global --ion-placeholder-opacity variable

---

BREAKING.md
core/api.txt
core/src/components.d.ts
core/src/components/input/input.tsx
packages/angular/src/directives/proxies.ts
packages/vue/src/proxies.ts

---------
`ion-input` has a deprecated property: `accept`. This property was marked deprecated because the `file` value for `type` is not a valid value in Ionic Framework.
- Removed the `accept` property.
- Updated the breaking change to include this change.
`accept` can only be used when the input has a type of `file`. However, `file` is not a valid value in Ionic Framework so the `accept` property was removed.
[Related PR](https://github.com/ionic-team/ionic-framework/pull/25501)

refactor(input): remove accept property

---

packages/angular/standalone/src/providers/ionic-angular.ts

---------
`provideIonicAngular` in the standalone package is used to bootstrap Ionic and provide global config options, and should only be called at the application root. However, developers are currently able to accidentally use the provider at the Angular component level, which should not be done.
Wrapped the returned providers in [`makeEnvironmentProviders`](https://angular.io/api/core/makeEnvironmentProviders), an Angular API that prevents the providers from being used in a `@Component` decorator.
The `makeEnvironmentProviders` API was added in Angular 15, meaning 14 will no longer work. However, we're already dropping support for 14 and 15 in the base branch of this PR, so no additional updates to the breaking changes guide are needed.

fix(angular): prevent provideIonicAngular from being used at component level

---

.github/CONTRIBUTING.md
packages/angular/README.md
packages/angular/test/README.md
packages/react-router/README.md
packages/react-router/test/README.md
packages/react/README.md
packages/react/test/README.md
packages/vue-router/README.md
packages/vue/README.md
packages/vue/test/README.md

---------
The Readmes are all using `npm` in the building sections.
- The Readmes are all using `pnpm` in the building sections.
N/A

chore(angular, react, vue): update readmes for pnpm usage

---

core/src/themes/ionic.mixins.scss

---------
The `position` mixin checks if `inset-inline-start` is supported by the browser since v7 supports browsers that don't support `inset-inline-start`. If it's not then it would depend on `host-context` to apply the correct styles based on the app direction.
v8 supports browsers that does support `inset-inline-start` so the check is no longer needed.
N/A

refactor(position): remove host-context usage from mixin

---

core/src/components/refresher-content/refresher-content.tsx
core/src/components/refresher/test/a11y/refresher.e2e.ts

---------
`refresher-content` passes `aria-label` to the `ion-spinner`. This was done to improve web accessibility.
We realized that `ion-spinner` may not have the correct `role`. We plan to investigate to determine if we should continue using `role="progressbar"` or if the component is a decorative component. Based on that research, we will update the component.
In the mean time, the code reverts back to what v7 currently has until a proper solution is implemented.
- Removed the `aria-label` because the team will re-evaluate if the spinners should use `aria-hidden` instead.
N/A

refactor(refresher-content): remove the aria-label

---

BREAKING.md
core/src/components/toast/toast-interface.ts
core/src/components/toast/toast.tsx

---------
The deprecated `cssClass` is still part of `ToastButton` even though the buttons can be access through shadow parts.
- Removed `cssClass` from `ToastButton`
- Updated the Breaking Change file to inform developers that they can add their styles through the "button" shadow part.
N/A

refactor(toast): remove cssClass from ToastButton

---

packages/react/src/routing/PageManager.tsx

Issue number: resolves #28838
---------
In #28316 we resolved a longstanding misconfiguration where event listeners being added to the page were not removed. This was due to incorrect usage of `.bind` creating a new instance of the callback functions.
By removing the event listener for `ionViewDidLeave`, before the component has actually unmounted in react, resulted in the registered destroy callback to not fire: https://github.com/ionic-team/ionic-framework/blob/51c729eafc3b290a5daddf7f0ccffd0a2a9fe2aa/packages/react/src/contexts/IonLifeCycleContext.tsx#L208-L216 and https://github.com/ionic-team/ionic-framework/blob/51c729eafc3b290a5daddf7f0ccffd0a2a9fe2aa/packages/react/src/routing/ViewLifeCycleManager.tsx#L21-L32
This resulted in a scenario that using a `Redirect` could cause the …

fix(react): route with redirect will mount page

---

core/src/components.d.ts
core/src/components/action-sheet/action-sheet.tsx
core/src/components/alert/alert.tsx
core/src/components/loading/loading.tsx
core/src/components/modal/modal.tsx
core/src/components/picker/picker.tsx
core/src/components/popover/popover.tsx
core/src/components/toast/toast.tsx

In https://github.com/ionic-team/ionic-framework/issues/28981 there was some confusion surrounding how to remove an overlay from the DOM if it was never presented. The `dismiss` method will remove the overlay from the DOM, but only if the overlay is visible. Otherwise, it's a no-op.
This PR updates the `dismiss` method docs for each overlay component to note that developers can use the browser's remove method to remove the element from the DOM.

docs(overlays): clarify how to remove an overlay

---

core/src/components/toast/test/toast.spec.tsx

---------
Team members are running into unexpected errors running spec tests:
```
TypeError: Cannot read properties of undefined (reading '$instanceValues$')
```
This line is the culprit: https://github.com/ionic-team/ionic-framework/blob/f885a5526addab8abf93a95de8980e4ef78cbd36/core/src/components/toast/test/toast.spec.tsx#L108
We set the Ionic config for toastDuration to 5000. This means that on present a setTimeout callback will fire after 5000ms and dismiss the toast. For this test, this is fine because we never present the toast therefore the setTimeout  is never created.
The problem is that this config is not automatically reset between tests. As a result, when we have tests that only present the toast (and never dismiss it) the duration is also 5000 there: …

test(toast): reset config to avoid unnecessary setTimeouts

---

core/src/utils/overlays.ts
core/src/utils/test/overlays/overlays.e2e.ts

Issue number: resolves #28849
---------
If the developer tries to set focus to a custom element on overlay dismissal, Ionic will always override that focus.
- If focus is already set by developer during dismissal, then Ionic will not restore focus to previous element
In the before video, you can see the text box is focused by developer code when "Mention User" is tapped, which opens the keyboard. Shortly after that, when the bottom sheet fully dismisses, Ionic focuses the button, removing focus from the text box and hiding the keyboard.
In the after, Ionic detects that the developer has already focused the text box and does not change that focus.
|Before|After|
|---|---|
|<video src="https://github.com/ionic-team/ionic-framework/assets/2166114/47d55eff-29af-4019-ac3c-00f9fe722ca7"></video> …

fix(overlays): do not return focus if application has already moved focus manually

---

core/src/components/datetime/datetime.scss

---------
Ionic Framework has a patch implementation to workaround a Safari 14 bug that resulted in the calendar month jumping when opening/closing the month/year interface. 
This bug was fixed in Safari 15.
- Ionic v8 no longer supports Safari 14, so we can safely remove this patch code
- Calendar month does not jump when opening/closing the month/year interface with Safari/iOS 15-17
I tested on Sims for iOS 15-17. Tested against a physical device for iOS 17 as well.

chore(datetime): remove safari 14 intersection observer workaround

---

core/src/components/datetime/datetime.tsx

---------
This code was added to account for a Safari 14 issue that would cause datetime to render incorrectly. The Safari bug was fixed starting in Safari 15. However, Ionic v7 supported back to Safari 14.
More context is available [here](https://github.com/ionic-team/ionic-framework/pull/24421#discussion_r796113907)
- Removed the Safari 14 workarounds since Ionic v8 does not support Safari 14
I tested on iOS 15, 16, and 17 to verify that removing this hack does not cause any issues. Also verified that removing this hack does reproduce the issue on iOS 14 (to verify that I am reproducing the original issue correctly)

refactor(datetime): remove safari 14 hack

---

core/src/components/item/item.tsx

- Fix Internal issue (FW-5205) - Removed the build conditional in the `item` component since the previous issue is already fixed in Stencil.
---------
- No changes were made in terms of behavior.
- No changes were made in terms of behavior so it will work as before.
- Spec tests still pass even after this change (we can see below the results before and after the change)
- Ran the command `npm run test.spec src/components/item/test/item.spec.ts src/components/item/test/item.spec.tsx`

refactor(item): remove build conditional for test environment

---

core/src/components/datetime-button/datetime-button.tsx
core/src/components/datetime-button/test/basic/datetime-button.e2e.ts
core/src/components/datetime/utils/format.ts

---------
The Datetime Button has default date formatting that cannot be set by the developer.
- The developer can customize the date and time formatting for the Datetime Button
- A warning will be logged if they do not include the `date` or `time` object for formatOptions as needed for the presentation of the Datetime

feat(datetime-button): formatOptions for Datetime Button

---

.github/workflows/assign-issues.yml

This removes me from being auto-assigned issues while I am out of office.

chore: remove liam from auto-assign issues while out of office

---

core/src/components/buttons/buttons.tsx
core/src/components/label/label.tsx

---------
Previously, Stencil would allow content to project through to a component even when a slot was not present. However, with the changes in `extras.experimentalScopedSlotChanges`, this behavior was changed to hide elements without a destination slot - matching the behavior of a shadow encapsulated component.
As such, elements projected through the `ion-label` or `ion-buttons` components would no longer be visible in rendered output.
This commit adds an explicit `slot` tag to components in core leveraging "scoped" encapsulation with no rendered content (i.e. elements with only a `Host` tag and styles).

fix(core): add `slot` elements to scoped "wrapper" components

---

core/api.txt
core/src/components.d.ts
core/src/components/datetime-button/datetime-button.tsx
core/src/components/datetime-button/test/basic/datetime-button.e2e.ts
core/src/components/datetime-button/test/basic/index.html
core/src/components/datetime/datetime-interface.ts
core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/basic/datetime.e2e.ts
core/src/components/datetime/test/basic/index.html
core/src/components/datetime/test/format.spec.ts
core/src/components/datetime/utils/format.ts
core/src/components/datetime/utils/validate.ts
core/src/components/datetime/utils/warn.ts
packages/angular/src/directives/proxies.ts
packages/vue/src/proxies.ts

---------
The Datetime header, Datetime time button, and Datetime Button have default date formatting that cannot be set by the developer.
- The developer can customize the date and time formatting for the Datetime header and time button
- The developer can customize the date and time formatting for the Datetime Button
- A warning will appear in the console if they try to provide a time zone (the time zone will not get used)
- A warning will be logged if they do not include the date or time object for formatOptions as needed for the presentation of the Datetime
These changes have been reviewed in #29009 and #29059. This PR just adds them to the feature branch now that the separate tickets are complete.

feat(datetime): formatOptions property for Datetime

---

.github/workflows/actions/build-core-stencil-prerelease/action.yml

Set the `--debug` and `--verbose` flags on the Stencil Nightly CI build.
The Stencil nightly build doesn't provide all the information that it could!
This sets the `--debug` and `--verbose` flags when calling `npm run build` in the 'Build Ionic Core with Stencil Prerelease' github action, which is used by the workflow which installs nightly Stencil builds and builds framework with it, thereby checking for regressions.
This change will just ensure that this nightly build provides a bit more information.

chore(ci): add `--debug --verbose` to stencil nightly build

---

core/api.txt
core/src/components.d.ts
core/src/components/searchbar/searchbar.tsx
core/src/components/searchbar/test/searchbar.spec.ts
packages/angular/src/directives/proxies.ts
packages/vue/src/proxies.ts

Issue number: resolves #27606
---------
Certain attributes are not be inherited to the inner searchbar. Developers need control over these attributes to provide important context to users for things like language and text direction. Additionally, being able to control things like autocapitalize, maxlength, and minlength can help improve the user experience by a) guiding what should be entered into an input and b) removing autocapitalize where it's not appropriate. 
- Added autocapitalize, maxlength, and minlength properties
- lang and dir are global attributes, so adding them as properties will cause issues. However, developers can still set them as attributes and they will be inherited to the native `input` element. We also watch them so any changes to the attributes are also inherited …

feat(searchbar): autocapitalize, dir, lang, maxlength, and minlength are inherited to native input

---

core/src/components/checkbox/checkbox.tsx
core/src/components/checkbox/test/checkbox.spec.ts

Issue number: resolves Internal
---------
We are not ever explicitly setting `aria-checked`. For checked and unchecked states (i.e. `true` and `false` for aria-checked), we don't need to set `aria-checked` because an input with a type of 'checkbox' has built-in semantics making `aria-checked` redundant. 
However, when the checkbox is in an indeterminate state, `aria-checked` should have a value of 'mixed'. We are not currently ever setting it to 'mixed'. See [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked#description) for more details.
- The checkbox's `aria-checked` has a value of 'true' when it is checked
- The checkbox's `aria-checked` has a value of 'false' when it is unchecked
- The checkbox's `aria-checked` has a value of 'mixed' when it …

fix(checkbox): set aria-checked of indeterminate checkbox to 'mixed'

---

.github/workflows/release.yml

The cache for the `next` tag is not cleared on release. As a result, the Ionic 8 playgrounds break since the entry point is cached. The cached entry point references JS chunks that no longer exist.

chore(ci): clear JSDelivr cache for Ionic Next

---

packages/angular/common/src/directives/navigation/nav.ts

Issue number: resolves #29114
---------
The event types for `ion-nav` were not correctly applied to the angular component wrapper.
- `ionNavWillChange` and `ionNavDidChange` event types are added to `ion-nav` component wrapper in Angular.
Dev-build: `7.7.5-dev.11709823131.1d3df428`
Testing:
- Open reproduction on original issue
- Observe: Type errors for missing event properties 
- Install dev-build
- (May need to reload)
- Observe: Type errors are resolved

fix(angular): add ionNavWillChange and ionNavDidChange types for nav

---

core/src/utils/overlays.ts
core/src/utils/test/overlays/overlays.spec.ts

Issue number: resolves #29139 
---------
When implementing https://github.com/ionic-team/ionic-framework/pull/28997 we did not consider the case where a Toast could be presented. When presenting a Toast after presenting a Modal the linked change causes the Modal to be hidden from screen readers.
- If the top-most overlay is a Toast then the closest non-Toast overlay is also not hidden from screen readers. 
Dev build: `7.7.5-dev.11710260658.1fc29a6c`

fix(overlay): do not hide overlay if toast is presented

---

core/src/components/app/app.tsx
core/src/components/menu/menu.tsx
core/src/utils/hardware-back-button.ts
core/src/utils/overlays.ts

The variable was spelled incorrectly.

chore: fix typo with close watcher const

---

core/src/components.d.ts
core/src/components/toggle/toggle.tsx

Removes the extra backtick in the `alignment` property description that is causing formatting issues in the [Toggle documentation](https://ionicframework.com/docs/api/toggle#properties):

docs(toggle): remove extra backtick to fix formatting

---

core/src/components/datetime/datetime.tsx

Issue number: resolves #24542
---------
WebKit has a quirk where IntersectionObserver callbacks are delayed until after an accelerated animation finishes if the "root" specified in the config is the browser viewport (the default behavior if "root" is not specified) This means that when presenting a datetime in a modal on iOS the calendar body appears blank until the modal animation finishes.
- We can work around this issue by observing an element inside of the datetime component and using the datetime component itself as the root. To do this, I added an `.intersection-tracker` element inside of datetime. This element has a dimension of 0x0 so it should not affect component layout or functionality.
I opted to add this element instead of re-using an existing element because the existing …

perf(datetime): calendar body shows immediately in modal on ios

---

.github/COMPONENT-GUIDE.md

Updates the component guide to use the proper order for the `focused`, `hover`, and `activated` states. Reorders the sections based on the recommended order and adds emphasis and blockquotes to call out the order. 
I have created ticket [FW-6039](https://outsystemsrd.atlassian.net/browse/FW-6039) for investigating components that don't follow the recommended order here.

docs(contributing): update component guide with order for states

---

core/src/utils/test/playwright/docs/usage-instructions.md

Creates a link to the correct section of the docs. The old verbiage existed when the configuring step was in the section below.

docs(test): fix link for configuring docker for headed tests

---

core/api.txt
core/src/components.d.ts
core/src/components/searchbar/searchbar.tsx

Issue number: resolves #29193
---------
In an attempt to preserve backwards compatibility when adding `autocapitalize` to Searchbar, we used `!` to indicate that the prop was never undefined. The `autocapitalize` on `HTMLElement` expects this value to be a string and never undefined.
For the purposes of the property on Searchbar, setting this prop to one of the accepted values would constitute a breaking change because it would override the default browser behavior (which we previously relied upon). As a result, we used `!` to not set a default prop but inform TypeScript that this prop is always defined. This unintentionally made it so developers needed to define the `autocapitalize` property every time which is not what we want. 
- `autocapitalize` now defaults to the `'default'` …

fix(searchbar): autocapitalize is initialized correctly

---

core/src/utils/tap-click/index.ts

---------
[Amanda pointed out that the ripple effect for the Button inside of InputPasswordToggle was not working](https://github.com/ionic-team/ionic-framework/pull/29175#discussion_r1532627841). I found out that calling `ev.preventDefault` on `pointerdown` causes `mouseup` to not get fired. On desktop, we rely on `mouseup` to know when to add the ripple effect. (`touchend` is not impacted)
Interestingly, calling `ev.preventDefault` on `pointerdown` does **not** prevent `pointerup` from being fired. The idea here is that if we migrate the tap click utility to use the PointerEvents API instead of separate mouse/touch listeners we can keep the existing tap click behavior while also fixing the bug that Amanda noted.
- Tap click nows listens for the Pointer Events …

refactor(tap-click): use pointer events api

---

core/src/components/popover/popover.scss
core/src/components/popover/test/basic/popover.e2e.ts
core/src/css/core.scss

Issue number: resolves #29211
---------
In https://github.com/ionic-team/ionic-framework/pull/28861 I fixed a bug that caused `.popover-viewport` to have `overflow: hidden`. In reality, this code should have always applied but due to an incorrect selector it never did.
As it turns out in https://github.com/ionic-team/ionic-framework/issues/29211, some developers were relying on the broken behavior to build their applications. In particular, developers were using `ion-popover` without an `ion-content`. The linked change made it so that using popovers without `ion-content` were not scrollable.
After talking with @mapsandapps we think it makes sense to officially support this behavior. We support using [modals without `ion-content`](https://ionicframework.com/docs/api/modal#custom-dialogs), …

fix(popover): viewport can be scrolled if no content present

---

.github/CODEOWNERS

Remove myself as the codeowner of specific directories as this bypasses the random review assignment and automatically assigns me to any PRs changing these files.

chore: remove myself from codeowners

---

core/api.txt
core/src/components.d.ts
core/src/components/input/input.tsx
core/src/components/input/test/input.spec.ts
packages/angular/src/directives/proxies.ts
packages/vue/src/proxies.ts

Issue number: resolves #26974
---------
In https://github.com/ionic-team/ionic-framework/pull/26354 we updated the clear icon to use an ionicon instead of an hardcoded SVG. This has made it challenging to customize the icon.
- Added `clearInputIcon` property to allow developers to customize the ionicon used.

feat(input): add clearInputIcon property

---

core/api.txt
core/src/components.d.ts
core/src/components/content/content.tsx
core/src/components/content/test/content.spec.ts
packages/angular/src/directives/proxies.ts
packages/angular/standalone/src/directives/proxies.ts
packages/vue/src/proxies.ts

---------
Content in the `fixed` slot is always placed after the main content in the DOM.
- A new `fixedSlotPlacement` prop on Content allows developers to place fixed content either before or after the main content in the DOM
Dev build: `8.0.0-dev.11712072527.1dd97c66`
⚠️This feature will not be part of the v8.0 release. As a result, do not merge this into `feature-8.0`. However, I am putting this PR up based off `feature-8.0` so it can get reviewed by the team.

feat(content): add fixedSlotPlacement prop

---

packages/vue/src/vue-component-lib/utils.ts

I forgot to run the core build in https://github.com/ionic-team/ionic-framework/commit/f726c358682768412aab4d5e1ba23f17c8a52711, so the latest Vue output target wrapper was not generated.

chore: run build

---

.github/CONTRIBUTING.md

---------
Developers on a Windows environment using VS Code will experience an issue when using prettier, where files will be tracked as modified even though they have no actual diffs.
This is due to differences in how Unix based operating systems and Windows treat carriage returns.
- Updates the contributing guide to educate developers using VS Code on how to configure their local environment to not track additional diffs when formatting the codebase. 
This is the same documentation that exists on the ionic-docs repository for the same reason. I've applied co-authored-by credit to Netkow for his wonderful contribution to that documentation.

docs(contributing): using vscode on windows

---

core/package.json

---------
Ionic Framework developers make extensive use of multi-line comments in the Sass files. However these comments are not stripped from the generated output. 
This leads to a significant increase to the file size of CSS and can have an impact on runtime performance. 
For example: https://cdn.jsdelivr.net/npm/@ionic/core/css/core.css has 183 lines of comment blocks before a single line of CSS.
- Compresses the generated output from Sass → CSS to strip out multi-line comment blocks. 
- Developers can use [loud comments](https://sass-lang.com/documentation/syntax/comments/) if they want to include comments in the generated output.
- In the case of just the core.css file, the file size goes from 20kb to 10kb.
- The entire CSS global styles goes from 758 KB to 606kb. …

perf(styles): compress distributed global stylesheets

---

core/src/components/modal/gestures/sheet.ts

Issue number: Part of https://github.com/ionic-team/ionic-framework/issues/24583
---------
When a sheet modal is fully opened swiping down on the IonContent when the content is scrolled to top does not move the sheet modal down. This does not align with the card modal where doing the same actions causes the card modal to move down.
- Swiping down on the content now moves the sheet modal down as long as the content is scrolled to the top.
Dev build: `7.8.3-dev.11712114476.152fc43d`
Reviewers:
Please test this on physical iOS and Android devices. Please check the following:
1. When a modal is fully opened, ensure that users can still scroll down (i.e. swipe up on the content to scroll down).
2. When a modal is fully opened, ensure that users can swipe down on the modal to dismiss when the …

fix(modal): sheet modal can be swiped down on content

---

core/src/components/modal/gestures/sheet.ts

Issue number: Part of https://github.com/ionic-team/ionic-framework/issues/24583
---------
There is a noticeable delay between when users finish swiping and when scrolling is re-enabled. This is because the animation takes ~500ms to complete when finishing the swipe.
This does not align with how we [re-enable scrolling in the card modal](https://github.com/ionic-team/ionic-framework/blob/9b3cf9fbc2c5189871b2255d2d765e78509f5027/core/src/components/modal/gestures/swipe-to-close.ts#L262-L264). In the card modal, scrolling is re-enabled as soon as the gesture is released.
- To fix this, I aligned the behavior of the sheet modal with that of the card modal. As a result, whether or not the content is scrollable is now tied to the state of the gesture rather than the state of the animation.
Dev …

fix(modal): remove enable scrolling delay with sheet modal

---

core/src/components/input/input.ionic.scss

---------
The ionic input does not have a hover state.
Adds a hover state. 
We do not currently have a way to test hover states. See https://github.com/microsoft/playwright/issues/12077 for more information.

feat(input): add hover state to the ionic theme

---

core/src/components/card/card.ionic.scss
core/src/components/chip/chip.ionic.scss

---------
CI will fail randomly due to which stylesheet is processed last by rollup in Stencil. This leads to random failures. 
This is caused by some of the new ionic stylesheets not importing the same common stylesheet that included the CSS variable documentation.
- Temporarily copies and pastes the documentation blocks to the affected ionic stylesheets
- CI should no longer fail randomly when comparing the generated `api.txt` output
- Adds a technical debt track to track removing these changes once the bug in Stencil is resolved and released

chore(ci): stability for test-core-clean-build

---

core/src/css/palettes/dark.scss

Issue number: resolves #29219
---------
We got feedback that the current dark theme is a bit jarring when compared with native. In particular, devs are expecting the contrast to be white for many of these colors to match native iOS. Currently, text inside of a primary button is black on dark mode, but devs expect it to be white. Additionally, the dark mode colors appear to be too washed out when compared with their light mode counterparts.
The team discussed this and we think we can find a way to make the colors more in line with what devs expect while still allowing for AA color contrast levels.
- Adjusted the secondary and danger colors to be slightly more vibrant/inline with what developers expect in mobile apps while still meeting AA color contrast.
I intentionally did not change the …

fix(dark-palette): improve base colors

---

core/src/components/input/input.tsx

Issue number: resolves #29374
---------
When using Angular binding syntax, the `debounce` value can be set after `connectedCallback`, but before `componentDidLoad`. This results in the internal representation of the `debounce` value to be the default and the watch callback to never fire.
- The callback handler for `debounce` is called on component load, identical to what we do for the same exact reasons for  the input `type`.
- `debounce` will correctly reflect and apply the developers value when using binding syntax on initial load
Dev-build: `8.0.1-dev.11713879639.102f51a0`
Forked reproduction with the dev-build is available here: https://github.com/ionic-team/ionic-framework/issues/29374#issuecomment-2072377087

fix(input): debounce is set with binding syntax in angular on load

---

core/src/components/input/input.tsx
core/src/utils/input-shims/hacks/scroll-assist.ts

This backports to https://github.com/ionic-team/ionic-framework/pull/29366 to Ionic v7
Dev build: `7.8.6-dev.11713904893.12900883`

fix(input): clear button can be navigated using screen reader (#29366)

---

.github/workflows/release.yml

This PR adds a "v7-lts" NPM tag for backporting fixes to v7.

chore: add v7-lts option for backporting

---

.github/workflows/release.yml

This PR removes the v5 and v4 lts tags from the release scripts. The main branch should always be used to deploy to the latest/next tags and never in the past. Instead, the version branches have the option to deploy to their respective LTS tags.

chore: remove v5 and v4 lts tags

---

core/src/components/item/test/a11y/item.e2e.ts

The ticket was marked as done, but this one was missed.

test(item): re-enable nested interactive check

---

core/src/components.d.ts
core/src/components/accordion-group/accordion-group.tsx
core/src/components/checkbox/checkbox.tsx
core/src/components/datetime/datetime.tsx
core/src/components/input/input.tsx
core/src/components/picker-column/picker-column.tsx
core/src/components/radio-group/radio-group.tsx
core/src/components/range/range.tsx
core/src/components/searchbar/searchbar.tsx
core/src/components/segment/segment.tsx
core/src/components/select/select.tsx
core/src/components/textarea/textarea.tsx
core/src/components/toggle/toggle.tsx
packages/angular/src/directives/proxies.ts
packages/angular/standalone/src/directives/proxies.ts

Issue number: resolves https://github.com/ionic-team/ionic-docs/issues/3588
---------
The documentation around `ionChange` not being emitted when programmatically changing the property associated to the "value" is either inconsistent or missing from certain components.
- Adds the documentation to the missing components.
- Makes the documentation consistent across components.

docs(core): ionChange will not emit from programmatically changing value

---

core/package-lock.json
core/package.json

Issue number: resolves #29393
---------
With Stencil v4.17.1, in Angular apps Stencil's `MockDoc` will be bundled with the consumer's code resulting in a significant increase to the main chunk. 
|v8.0.0|
|---|
|![CleanShot 2024-04-29 at 11 14 36@2x](https://github.com/ionic-team/ionic-framework/assets/13732623/78d6dd63-3816-4da5-8ada-2bfa823a6800)|
|v8.0.1|
|---|
|![CleanShot 2024-04-29 at 11 15 38@2x](https://github.com/ionic-team/ionic-framework/assets/13732623/d21315a8-049f-4874-8a87-996feeb5bd12)|
- Updates to v4.17.2 of Stencil, which resolves this regression 🎉 
|Dev-build|
|---|
|![CleanShot 2024-04-29 at 11 17 50@2x](https://github.com/ionic-team/ionic-framework/assets/13732623/a54d1e4c-f9a7-4df9-9064-4b3ae875df11)|
Dev-build: `8.0.2-dev.11714402065.169342dc`

chore(deps): upgrade stencil to v4.17.2

---

core/src/components/datetime/datetime.tsx

Issue number: resolves #29198
---------
In https://github.com/ionic-team/ionic-framework/pull/27917 I failed to account for RTL. This caused the navigation with the arrow buttons to break because the scroll position was always < 2.
- Datetime now checks if the component is in RTL mode when creating the scrollLeft threshold.

fix(datetime): navigating months in RTL works correctly

---

core/src/components/select/select.tsx

Issue number: resolves #29234
---------
In certain scenarios, such as in Angular where the property binding is set a few frames after the element is rendered, the `ionStyle` event from `ion-select` can be emitted before `ion-item` has registered an event listener.
This results in situations like setting the `ion-select` as initially disabled can cause the item to not treat the element as not interactable (receives pointer events).
- Emits the `ionStyle` event when the `ion-select` is rendered.
- `ion-item` consistently detects the state of `ion-select` and applies the appropriate styles
Forked reproduction and dev-build available here: https://github.com/ionic-team/ionic-framework/issues/29234#issuecomment-2091866453

fix(angular): persist select disabled state in item

---

core/src/components/input/input.ionic.scss
core/src/components/input/input.tsx
core/src/components/input/test/basic/input.e2e.ts

---------
When a user tabs into the clear icon button within `ion-input`, it does not display a focus ring. This was displaying prior but this [PR](https://github.com/ionic-team/ionic-framework/commit/ee49824a84df7a7b002f41dab7b935fbcdb64946) caused it to stop displaying without realizing it.
- The focus ring now displays as intended.
This is for the `ionic` theme.

fix(input): add focus ring to the clear input button for ionic theme

---

core/src/themes/ionic.theme.default.ios.scss
docs/sass-guidelines.md

Remove a missed `!default` flag in the themes directory and update the Sass variable guidelines docs to eliminate the `!default` flag from the code examples, except for in the historic usage section which includes examples from previous versions where the `!default` flag was used.

chore(theming): remove Sass default flag & update guidelines

---

core/src/components/radio/radio.tsx

Issue number: resolves #29442
---------
The state does not stay consistent when the data used to render the radios are updated.
- The state updates after the component loads, this allows the value to be set after the radio is rendered.
Dev build: 8.1.1-dev.11714760012.1eab947e

fix(radio): persist checked state when items are updated in radio-group

---

.github/workflows/conventional-commit.yml

---------
The conventional commit check occurs to all PRs even for releases. Release PRs do not follow the same structure and causes a block when trying to merge them.
- `release` label has been marked as an `ignoreLabel`, this will let the conventional commit know that the PR has been marked to skip validation.
N/A

refactor(gh-action): add an ignore label to conventional commits

---

core/src/components/input/test/fill/input.e2e.ts

---------
The `.only` managed to get into the codebase. This is not the correct structure.
- Removed `.only` from the input test.
N/A

test(input): remove the .only within fill

---

core/src/components.d.ts
core/src/components/input/input.ionic.outline.scss
core/src/components/input/input.ionic.scss
core/src/components/input/input.tsx

---------
The shape styles are being applied when the `fill` is unset in the `ionic` theme. This is incorrect per the input UX requirements as shape should only apply when `fill` is set to `"outline"`. This is made apparent when looking at the existing styles for `disabled`.
- Only apply the shape styles to the `"outline"` fill
- Move the use of the `--background` css variable to the native wrapper since this is what we use to style both the disabled and readonly states
| Before | After |
| ---| ---|
| ![before](https://github.com/ionic-team/ionic-framework/assets/6577830/44b6e7e4-70f4-49d5-844f-a015b7284ed5) | ![after](https://github.com/ionic-team/ionic-framework/assets/6577830/06ac9431-17f4-4741-8ceb-19b40d8ba7d9) |
I am not sure why this wasn't caught with the …

fix(input): only apply the shape to the outline fill in ionic theme

---

core/src/global/config.ts
core/src/global/test/config-controller.spec.ts

Issue number: resolves #29479
---------
If an application includes a malformed URI, an Ionic Framework can "crash" due to an uncaught exception in parsing the URI for the Ionic config.
- Handle the malformed URI fallback if the config cannot be determined
- Added unit tests for this case

fix(core): malformed URIs will not throw exception

---

core/src/components/chip/chip.ionic.scss
core/src/components/chip/test/theme-ionic/index.html

---------
- Replaced old fixed values with new tokens.
- Added theme="ionic" to ionic test page.

refactor(chip): use the new tokens

---

packages/react/src/components/index.ts

Issue number: resolves #29518 
---------
IonInput in React apps can't import the correct type for typescript.  
Since it is in the file exported, people using IonInput can import the correct type.
-
-
-
- [x ] No
Liam DeBeasi told me it was a bug a couple days ago and pointed out to where it needed to be added.

refactor(react): export InputInputEventDetail type

---

core/.gitattributes

---------
add a .gitattributes configuration file to the repo. this will allow users of unix and windows machines to be able to commit to the repo without worrying about line endings.
previously, running the `lint` npm task in the core directory would cause the line endings to change locally. with this change, line endings should not change

chore(repo): add git attributes configuration

---

renovate.json5

Issue number:  N/A
---------
Renovate updates the Playwright packages. It's important that the Playwright within Docker and within core are the same version. However, the Playwright version within core does not update when Docker does.
- Added a `bump` to the Renovate config, this should allow Playwright within core to update regardless if the new version satisfies the range.
I was unable to test it locally since it will only trigger when the code is within `main`.

fix(playwright): bump packages upon new release

---

packages/vue/test/apps/vue3/package.json

---------
CI tests are failing because of a recent patch from Vue. They start to fail on Vue v3.4.28.
- Pinned Vue v3.4.27 until we can determine a fix.
N/A

chore(vue): pin version for test app

---

core/src/components/menu-button/menu-button.common.scss
core/src/components/menu-button/menu-button.ionic.scss
core/src/components/menu-button/menu-button.ios.scss
core/src/components/menu-button/menu-button.md.scss
core/src/components/menu-button/menu-button.native.scss
core/src/components/menu-button/menu-button.tsx

---------
This PR is being merged to ROU-10837 (ion-toolbar) where after a series of PR's are merged, the final PR will be done to next branch. This was done as most of these styles only make sense when used together in the context of the ion-toolbar, but there were a lot of changes that made sense to split in multiple PR's.
- Added new scss file for Ionic theme.
- Split the files between common and native.

feat(ion-menu-button): add ionic theme base styles for ion-menu-button

---

core/src/components/searchbar/searchbar.common.scss
core/src/components/searchbar/searchbar.ionic.scss
core/src/components/searchbar/searchbar.ios.scss
core/src/components/searchbar/searchbar.md.scss
core/src/components/searchbar/searchbar.native.scss
core/src/components/searchbar/searchbar.tsx

---------
This PR is being merged to ROU-10837 (ion-toolbar) where after a series of PR's are merged, the final PR will be done to next branch. This was done as most of these styles only make sense when used together in the context of the ion-toolbar, but there were a lot of changes that made sense to split in multiple PR's.
- Added new scss file for Ionic theme.
- Split the files between common and native.

feat(ion-searchbar): add ionic theme base styles for searchbar

---

core/src/components/buttons/buttons.common.scss
core/src/components/buttons/buttons.ionic.scss
core/src/components/buttons/buttons.ios.scss
core/src/components/buttons/buttons.md.scss
core/src/components/buttons/buttons.native.scss
core/src/components/buttons/buttons.tsx

---------
This PR is being merged to ROU-10837 (ion-toolbar) where after a series of PR's are merged, the final PR will be done to next branch. This was done as most of these styles only make sense when used together in the context of the ion-toolbar, but there were a lot of changes that made sense to split in multiple PR's.
- Added new scss file for Ionic theme.
- Split the files between common and native.

feat(ion-button): add base styles for ionic theme buttons

---

core/api.txt
core/src/components/item/item.tsx
packages/angular/test/base/e2e/src/lazy/popover.spec.ts
packages/angular/test/base/src/app/lazy/home-page/home-page.component.html
packages/angular/test/base/src/app/lazy/popover-inline/popover-inline.component.html
packages/angular/test/base/src/app/lazy/popover-inline/popover-inline.component.ts

Issue number: resolves #29640
---------
(Angular) If a list inside of a popover contains a disabled item and is included in the following way:
```html
<ion-list>
<ion-item [button]="true">Option 1</ion-item>
<ion-item [button]="true" [disabled]="true">Option 2</ion-item>
<ion-item [button]="true">Option 3</ion-item>
</ion-list>
```
when you try to navigate using the arrow down keys, it will stop at the disabled item instead of continuing over it.
Note that changing the item to the following will work:
```html
<ion-item [button]="true" disabled="true">Option 2</ion-item>
```
Reflect the `disabled` property in the item so that when items are queried in the popover, the arrow down key skips over the disabled item.
This can be tested in the Angular test app by following the documentation …

fix(angular): popover arrow navigation with disabled items

---

.github/workflows/actions/build-angular-server/action.yml
core/package-lock.json
core/package.json
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular-server/scripts/sync.sh

---------
This PR does a couple things:
**1 - Adds a `sync` command to get the latest `core` build in `angular-server`**
The release process for `angular-server` failed [here](https://github.com/ionic-team/ionic-framework/actions/runs/9686982182/job/26730689874). This failure was only made apparent because the Lerna command [here](https://github.com/ionic-team/ionic-framework/blob/52ff0505e86dc204cb2fd2fdaf67229e6eeb36f8/.github/workflows/actions/publish-npm/action.yml#L35) runs prior to building each package. 
This should have been caught by CI on the [update to @stencil/core to v4.19.0](https://github.com/ionic-team/ionic-framework/pull/29666), but the `angular-server` package is the only package that doesn't sync `core` before it builds. This PR adds a `sync` …

chore(angular-server): add sync github action and update @stencil/core to 4.19.1 in core

---

packages/vue/src/ionic-vue.ts

Issue number: https://github.com/ionic-team/ionic-framework/issues/29659
---------
while using `.use(IonicVue, {})`, the config object has no autocomplete.
- Add type autocomplete on plugin option in VueJS package.

feat(vue): add optional IonicConfig type parameter to IonicVue plugin

---

core/package-lock.json
core/package.json

Issue number: resolves #29681
---------
<details>
<summary>ionic-team/stencil (@&#8203;stencil/core)</summary>
[Compare Source](https://togithub.com/ionic-team/stencil/compare/v4.19.1...v4.19.2)
* **hydrate:** partially revert [#5838](https://github.com/ionic-team/stencil/issues/5838) ([#5876](https://github.com/ionic-team/stencil/issues/5876)) ([dfbc340](https://github.com/ionic-team/stencil/commit/dfbc34007a818eef418e2f312a9dd7a0fef81af6))
* **hydrate:** support server side rendering of components with listener ([#5877](https://github.com/ionic-team/stencil/issues/5877)) ([2c5b7f8](https://github.com/ionic-team/stencil/commit/2c5b7f8ecb9e999e3c584b3a1af5a317f035ae4d)), fixes [#5869](https://github.com/ionic-team/stencil/issues/5869)
* **testing:** add testing sub module to export map …

chore(deps): update dependency @stencil/core to v4.19.2

---

core/src/components/alert/alert.tsx
core/src/components/alert/test/alert.spec.tsx

Issue number: resolves #29704
---------
Setting the id of an alert via htmlAttributes doesn't work due to it being overwritten by the overlay id.
Setting the id of an alert via htmlAttributes works.
First time PR, long time fan. Please let me know if I missed any of the contributing guidelines, happy to change anything!

fix(alert): do not overwrite id set in htmlAttributes

---

packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/ionic-vue.ts

---------
In v3.2.46 [vue was updated](https://github.com/vuejs/core/pull/3969) to add support for a generic type argument to the `Plugin` type. In https://github.com/ionic-team/ionic-framework/pull/29637 Ionic's Vue plugin was updated to use the generic, but the`@ionic/vue` project is currently installing v3.2.37.
This results in a local type checking error and build error:
```
(!) Plugin typescript: @rollup/plugin-typescript TS2315: Type 'Plugin_2' is not generic.
src/ionic-vue.ts: (24:24)
24 export const IonicVue: Plugin<[IonicConfig?]> = {
```
- Bumps and pins the dev dependency of `vue` to `3.2.46`. There are other breaking changes that Vue has shipped in minor/patch cycles that prevents from updating to the latest. 
- Resolves the type checking error locally …

chore(vue): bump vue dev-deps to have generic type

---

packages/angular/common/src/overlays/modal.ts
packages/angular/common/src/overlays/popover.ts

Issue number: resolves #29728
---------
The `focusTrap` property was missed when adding focus trapping configuration to the modal and popover. This results in a type error when developers attempt to assign to the property.
- Adds `focusTrap` property to `ion-modal` and `ion-popover` for the angular component wrappers
- Resolves type warnings when using the property in angular
Dev-build: `8.2.6-dev.11721672792.195afb09`

fix(angular): add focusTrap prop to modal and popover

---

core/custom-rules/await-playwright-promise-assertion.js
core/src/components/accordion/test/disabled/accordion.e2e.ts
core/src/components/accordion/test/readonly/accordion.e2e.ts
core/src/components/modal/test/sheet/modal.e2e.ts
core/src/components/select/test/basic/select.e2e.ts
core/src/utils/animation/test/animationbuilder/animation.e2e.ts

---------
Ionic Framework has a set of custom lint assertions to avoid creating flaky Playwright tests by forgetting to await a promise. However the `click` method was not included in the original list of methods to check. 
- Developers will receive a lint error when forgetting to await click methods from Playwright
- Resolves existing tests where this lint issue was present

chore(playwright): add click method to promise assertion lint checks

---

packages/react/src/components/navigation/IonTabButton.tsx

Issue number: resolves #29174
---------
React throws tab errors with `IonTabButton` when binding to `onPointerDown`, `onTouchEnd` and `onTouchMove`
- Adds missing type definitions for `onPointerDown`, `onTouchEnd` and `onTouchMove` to `IonTaButton`
- React does not throw type errors when binding callback functions to these events
---------

fix(react): add onPointerDown, onTouchEnd, add onTouchMove

---

core/src/components/item/item.tsx

---------
Item includes `ion-anchor` in the list of clickable components it queries. This component was renamed to `ion-router-link` in [v5](https://github.com/ionic-team/ionic-framework/blob/main/BREAKING_ARCHIVE/v5.md#anchor).
Updates the reference to `ion-anchor` to `ion-router-link` in `ion-item`.

fix(item): router-link remains clickable with item cover

---

core/package-lock.json
core/package.json
packages/vue/scripts/sync.sh
packages/vue/src/vue-component-lib/utils.ts
packages/vue/test/base/src/views/Components.vue
packages/vue/test/base/src/views/Home.vue
packages/vue/test/base/src/views/Routing.vue
packages/vue/test/base/src/views/Tab1.vue
packages/vue/test/base/src/views/Tab2.vue
packages/vue/test/base/tests/e2e/specs/routing.cy.js

---------
Ionic Framework Vue components using `router-link` do not apply an `href` property which causes components to render `div` or `button` elements when they should render an `a`. This is inconsistent with the way Angular and Vue handle router link.
Updates `@stencil/vue-output-target` to latest which adds the code from the following PR: https://github.com/ionic-team/stencil-ds-output-targets/pull/446
The update in vue output target checks if `router-link` and `navManager` are defined so this fix only applies to Ionic Framework components. If both are defined then it adds the `href` property to the element with the value of `router-link`.
Dev build: `8.2.7-dev.11722629362.1ac136c4`

fix(vue): pass router-link value to href to properly render clickable elements

---

core/src/components/content/content.tsx
core/src/components/content/test/a11y/content.e2e.ts
core/src/components/footer/test/a11y/footer.e2e.ts
core/src/components/header/test/a11y/header.e2e.ts

---------
Setting a custom `role` on the `ion-content` element does not work.
- Inherit attributes for the content element which allows a custom `role` property to be set
- Adds e2e tests for content, header, and footer verifying that the proper roles are assigned
To test this PR:
1. Switch to the branch and navigate to the `core/` directory
1. Make sure to run `npx playwright install` if it has not been updated recenly
1. Run `npm run test.e2e src/components/content/test/a11y/`
1. Verify that the tests pass
1. Remove my fix in `core/src/components/content/content.tsx` and run the test again
1. Verify that the `should allow for custom role` tests fail

fix(content): allow custom roles and aria attributes to be set on content

---

packages/angular/common/src/directives/navigation/router-link-delegate.ts
packages/angular/test/base/e2e/src/lazy/router-link.spec.ts
packages/angular/test/base/e2e/src/standalone/router-link.spec.ts
packages/angular/test/base/src/app/lazy/router-link/router-link.component.html
packages/angular/test/base/src/app/standalone/router-link/router-link.component.html

Issue number: resolves #20632
---------
When using the `routerLink` directive in Angular, it automatically adds `tabindex="0"` to the element. This creates issues with Ionic components that render native button or anchor elements, as they have their own focus management. As a result, when navigating between list items with `routerLink` using the `Tab` key, you need to press the `Tab` key twice to move to the next item. This problem is illustrated in the following demo:
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/angular-blfa7h?file=src%2Fapp%2Fexample.component.html)
Related Angular issue: https://github.com/angular/angular/issues/28345
Updated our `RouterLinkDelegateDirective` to check if the element using `routerLink` …

fix(angular): remove the tabindex set by routerLink from Ionic components

---

core/src/components/menu/test/safe-area/menu.e2e.ts

The Playwright test for `core/src/components/menu/test/safe-area/menu.e2e.ts` started to fail after introducing the following patch to Stencil: [#5926](https://github.com/ionic-team/stencil/pull/5926). After debugging the situation it turns out that the test overwrites the first style in the `<head />` tag which turns out to be a component style that caused all screenshot test to fail.
Overwrite the existing style by adding a new style tag at the bottom of the page.
n/a

fix(test): fix Stencil Nightly build

---

core/src/components/tabs/tabs.tsx
packages/react/src/components/inner-proxies.ts
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/components/navigation/IonTabs.tsx
packages/react/test/base/src/App.tsx
packages/react/test/base/src/pages/Main.tsx
packages/react/test/base/src/pages/TabsBasic.tsx
packages/react/test/base/tests/e2e/specs/tabs/tabs.cy.ts

Issue number: part of #25184 
This PR does not completely close the issue since it only addresses the React portion. The other frameworks will be done through other PRs.
---------
React: Developers have to provide `IonRouterOutlet` to use `IonTabs`. This means that developers are forced to tie their tabs to a router.
- `IonTabs` can be used without a router outlet as long as `IonTab` is a child and `IonRouterOutlet` is not.
- Added a test.
- Added a test page: `/tabs-basic`
Developers who are still using `IonTabs` with `IonRouterOutlet` will not experience any changes. This feature PR introduces another option to use `IonTabs`, no changes for the current implementation.
Dev build: 8.2.8-dev.11724280606.1a8c11d4

feat(react): use tabs without router

---

docs/core/testing/usage-instructions.md

Adds more information to the testing documentation on how to execute individual tests or pause execution.

docs(testing): update testing instructions for debugging tests

---

packages/vue/test/base/tests/e2e/specs/tabs.cy.js

There are failing tabs tests in Vue causing other PRs against the same branch to fail ([#29801](https://github.com/ionic-team/ionic-framework/actions/runs/10565559141/job/29271455382?pr=29801), [#29802](https://github.com/ionic-team/ionic-framework/actions/runs/10565551697/job/29271222682?pr=29802)). This skips the tests with a ticket created to investigate why. This blocks other tickets.

test(vue): skip failing tabs tests

---

core/src/components/range/range.tsx

Issue number: resolves #29792
---------
When the user drags the range knob (most easily reproduced in fullscreen mode) and the gesture emits a current x position of `0`, the range incorrectly emits a value of `NaN`.
- `ion-range` does not emit `NaN` and instead emits the correct range value for the knob

fix(range): emit correct value when knob is at start of bar

---

core/src/components/datetime/datetime.tsx
core/src/components/datetime/test/basic/datetime.e2e.ts

Issue number: resolves #29669
---------
Setting `value` to an empty string on `<ion-datetime>` renders a May 2021 calendar:
```html
<ion-datetime value=""></ion-datetime>
```
Show the month and time for today's date when value is an empty string. This matches how a native `input` with `type="datetime-local"` works. 
This can be tested by removing my fix in `datetime.tsx` and running the e2e test for Datetime:
```bash
npm run test.e2e src/components/datetime/test/basic/datetime.e2e.ts
```
The `should display today's date and time when value is an empty string` test should fail. 
Alternatively, you can add a datetime with `value=""` and see the calendar before & after my fix.

fix(datetime): display today's date and time when value is an empty string

---

packages/react/src/components/navigation/IonTabBar.tsx
packages/vue/src/components/IonTabBar.ts
packages/vue/src/components/IonTabButton.ts

---------
React: Refreshes the app upon a tab button press and returns to the first tab content.
Vue: Does not render the tabs when the app doesn't use a router at all because of `ionRouter` not being defined.
- React: Users can press on the tab button without having the app refresh and displays the associated tab content.
- Vue: Renders the tabs when router is not present.
Dev build: 8.3.1-dev.11726094383.1cdbab6f
How to test:
I recommend using the playgrounds in the Ionic Framework docs repo since those playgrounds are setup to not have any routers at a high level.
1. Navigate to the [basic usage section](https://ionic-docs-git-rou-11138-ionic1.vercel.app/docs/api/tabs#basic-usage)
2. Select React
3. Open the StackBlitz example
4. Click on any tab button
5. Notice that …

fix(react, vue): add default value for navManager on tabs

---

packages/react/src/components/navigation/IonTabs.tsx

---------
As mentioned in this [PR](https://github.com/ionic-team/ionic-docs/pull/3797), React `IonTabs` requires `IonTabBar` do be a child, else it doesn't render and throws an error.
Angular, JS, and Vue doesn't have this requirement.
I didn't see any reason why React does not mimic the other frameworks. In order to keep consistency, I've updated the React tabs. This would allow `ion-tabs` and `ion-tab-bar` can be used as standalone elements as mentioned in the [docs](https://ionicframework.com/docs/api/tabs). 
- React follows the same structure as the other frameworks: `IonTabs` doesn't require `IonTabBar` to be a child to render.
Dev build: 8.3.1-dev.11726159792.1a6f49de
How to test:
1. Create a Ionic React app through the Ionic CLI with tabs as the starter
2. Run …

refactor(react): update tab-bar requirement on tabs

---

core/src/components/segment/segment.tsx

Issue number: resolves #29523
---------
The scrollable segment flickers on iOS physical devices or simulators when the active button is near the edge of the screen. The jump is due to the button being scrolled to the center and snaps back to the edge since the button was scrolled past the container.
- Switched to `scrollTo` provides for a smoother transition.
- Gave co author credit to the original reporter since they provided part of the solution
- No new tests were created since functionality stays the same and testing on Playwright would be impossible to recreate
Dev build: 8.3.2-dev.11726779768.16e1f1d2
How to test:
1. Create a new app through any starter
2. Add a scrollable segment with at least 6 buttons (code snippet example below)
3. Recommended to change the segment mode to `md` …

fix(segment): prevent flickering for scrollable on iOS

---

core/api.txt
core/src/components.d.ts
core/src/components/app/app.tsx
packages/angular/src/directives/proxies.ts
packages/angular/standalone/src/directives/proxies.ts

Issue number: resolves #29830
---------
The `setFocus` method on `ion-app` is marked internal.
Document the `setFocus` method as a way for developers to programmatically focus elements. 
The method isn’t new, it was just marked as internal, which prevented it from being documented. I can mark this as a `feat` though if anyone thinks it should be.
Related documentation PR: https://github.com/ionic-team/ionic-docs/pull/3842

docs(app): add setFocus to the documentation

---

packages/vue/src/components/IonTabBar.ts
packages/vue/src/components/IonTabs.ts

Issue number: resolves part of #29885
---------
Vue: Tab bar could be a standalone element within `ion-tabs` and would navigate without issues with a router outlet before v8.3:
```vue
<ion-tabs>
<ion-router-outlet></ion-router-outlet>
<TabBar></TabBar>
</ion-tabs>
```
It would work as if it was written as:
```vue
<ion-tabs>
<ion-router-outlet></ion-router-outlet>
<ion-tab-bar slot="bottom">
</ion-tab-bar>
</ion-tabs>
```
After v8.3, any `ion-tab-bar` that was not a direct child of `ion-tabs` would lose it's expected behavior when used with a router outlet. If a user clicked on a tab button, then the content would not be redirected to that expected view.
The Vue tab bar's `_hasRouterOutlet` prop has been modified to accept both Boolean and `undefined` values. When the value is `undefined`, …

fix(tabs, tab-bar): use standalone tab bar in Vue

---

core/scripts/testing/styles.css
core/src/components/popover/test/size/index.html

---------
Test styles causes native buttons to have [certain styling](https://github.com/ionic-team/ionic-framework/blob/main/core/scripts/testing/styles.css#L52-L64). This was done to spruce up the buttons used for testing purposes only. However, this ended up adding styles to native buttons within Ionic components.
- Test styles for native buttons are only applied to buttons that are not part of a Ionic component
How to test:
1. Run the project locally from the `main` branch
2. [Comment](https://github.com/ionic-team/ionic-framework/blob/5d208e9daacad63294489e0b1bd6ec2b2645babd/core/src/components/searchbar/searchbar.md.scss#L91) out `border: 0` from `.searchbar-clear-button` from the searchbar `md` theme file (`ios` also works)
3. Navigate to the basic test page: …

test(styles): update button styles for test pages

---

packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/components/navigation/IonTabs.tsx
packages/react/src/components/navigation/IonTabsContext.tsx

Issue number: resolves part of #29885, resolves #29924
---------
React: There are two issues here.
**Issue 1:**
Tab bar could be a standalone element within `IonTabs` and would navigate without issues with a router outlet before v8.3:
```vue
<IonTabs>
<IonRouterOutlet></IonRouterOutlet>
<IonTabBar></IonTabBar>
</IonTabs>
```
It would work as if it was written as:
```tsx
<IonTabs>
<IonRouterOutlet></IonRouterOutlet>
<IonTabBar slot="bottom">
</IonTabBar>
</IonTabs>
```
After v8.3, any `ion-tab-bar` that was not a direct child of `ion-tabs` would lose it's expected behavior when used with a router outlet. If a user clicked on a tab button, then the content would not be redirected to that expected view.
**Issue 2:**
Users can no longer add a `ref` to the `IonRouterOutlet`, it always returns …

fix(tabs, tab-bar): use standalone tab bar in React

---

core/src/css/ionic/core.ionic.scss

---------
- fix ion-statusbar css var fallback;
- CSS var --ion-statusbar-padding was not working because the Sass variable was not escaped.

fix(SafeAreas): fix iOS fallback

---

packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/components/navigation/IonTabs.tsx
packages/react/src/components/navigation/IonTabsContext.tsx
packages/vue/src/components/IonTabBar.ts
packages/vue/src/components/IonTabs.ts

Issue number: resolves #29885, resolves #29924
---------
React and Vue:
Tab bar could be a standalone element within `IonTabs` and would navigate without issues with a router outlet before v8.3:
```tsx
<IonTabs>
<IonRouterOutlet></IonRouterOutlet>
<IonTabBar></IonTabBar>
</IonTabs>
```
It would work as if it was written as:
```tsx
<IonTabs>
<IonRouterOutlet></IonRouterOutlet>
<IonTabBar slot="bottom">
</IonTabBar>
</IonTabs>
```
After v8.3, any `ion-tab-bar` that was not a direct child of `ion-tabs` would lose it's expected behavior when used with a router outlet. If a user clicked on a tab button, then the content would not be redirected to that expected view.
React only:
Users can no longer add a `ref` to the `IonRouterOutlet`, it always returns undefined.
```
<IonTabs>
<IonRouterOutlet …
```

fix(tabs, tab-bar): use standalone tab bar in Vue, React

---

core/api.txt
core/src/components.d.ts
core/src/components/menu/menu-interface.ts
core/src/components/menu/menu.tsx
core/src/components/menu/test/basic/index.html
core/src/components/menu/test/basic/menu.e2e.ts
core/src/components/modal/test/sheet/index.html
core/src/utils/menu-controller/index.ts
core/src/utils/overlays.ts
packages/angular/src/directives/proxies.ts
packages/angular/standalone/src/directives/proxies.ts

---------
The menu `ionWillClose` and `ionDidClose` events do not emit any details.
- Adds the `MenuCloseEventDetail` interface which includes an optional `role` property
- The `ionWillClose` and `ionDidClose` emit the `role` property for the following scenarios:
- A role of `'gesture'` when dragging the menu closed
- A role of `'backdrop'` when clicking on the backdrop to close the menu
- A role of `'backdrop'` when the the menu is closed using the escape key
- A role of `undefined` when the menu is closed from a button inside of the menu
[Preview](https://ionic-framework-git-rou-11148-ionic1.vercel.app/src/components/menu/test/basic)

feat(menu): add support for passing role to close events

---

core/src/components/modal/animations/sheet.ts
core/src/components/modal/modal.tsx

---------
This PR aims to fix an issue introduced in https://github.com/ionic-team/ionic-framework/pull/29932 where the enter animation for ionic theme was in a broken state when the modal's initial breakpoint value was lesser than the specified backdrop breakpoint. 
- The erroneous behaviour happened because the shouldShowBackdrop constant had a false value which was being taken into consideration when computing the backdrop opacity for the ionic theme. This PR fixes this by always transitioning the backdrop opacity from 0 to 0.7 once the modal appears, independently of the initial, current or activation breakpoint.

fix(modal): fix enter animation when the initial breakpoint value is less than the backdrop breakpoint

---

core/src/components/backdrop/backdrop.tsx

Issue number: resolves #29773
---------
Certain Chrome and Edge versions (confirmed: Chrome v127 and Edge v127) would indicate that the backdrop has an accessibility violation:
```
Blocked aria-hidden on a <ion-backdrop> element because the element that just received
focus must not be hidden from assistive technology users. Avoid using aria-hidden on a
focused element or its ancestor. Consider using the inert attribute instead, which will also
prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at
```
The error is happening because `tabindex` and `aria-hidden` are being passed to `ion-backdrop`. The `tabindex` attribute is used to make an element focusable, regardless of value. When `aria-hidden` is applied to an element, then the element is hidden …

fix(backdrop): remove tabindex for improved accessibility

---

packages/angular/standalone/src/directives/radio-group.ts

Issue number: resolves #29826
---------
When using `compareWith` on `ion-radio-group` in Ionic Angular Standalone the following error is thrown:
```
NG8002: Can't bind to 'compareWith' since it isn't a known property of 'ion-radio-group'.
```
- `compareWith` on `ion-radio-group` in Angular Standalone is available

fix(angular): add missing 'compareWith' input to standalone ion-radio-group

---

core/src/utils/overlays.ts

Issue number: stemmed from #29773
---------
Certain Chrome and Edge versions (confirmed: Chrome v127, v128, v129 and Edge v127) would indicate that certain elements have an accessibility violation:
```
Blocked aria-hidden on a "ELEMENT NAME" element because the element that just received
focus must not be hidden from assistive technology users. Avoid using aria-hidden on a
focused element or its ancestor. Consider using the inert attribute instead, which will also
prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at
```
This issue happens when a toast appears and the users clicks on any element that is not related to toast. This is due to the main content having an `aria-hidden` so users should not to be able to interact with any of those elements. …

fix(overlays): do not hide root when toast appears

---

core/src/components/input/input.tsx
core/src/components/input/test/bottom-content/index.html
core/src/components/input/test/bottom-content/input.e2e.ts
core/src/components/textarea/test/bottom-content/textarea.e2e.ts
core/src/components/textarea/textarea.tsx

---------
Screen readers do not announce helper and error text when user is focused on the input or textarea. This does not align with the accessibility guidelines.
- The appropriate `aria` tags are added to the native input and textarea in order to associate them to the helper and error texts.
- `aria-describedBy` will only be added to the native element based on helper or error text. If helper text exists then the helper text ID will be used. If the error text exists and the component has the `ion-touched ion-invalid` classes, then the error text ID will be used.
- `aria-invalid` will only be added if the error text exists and the component has the `ion-touched ion-invalid` classes.
- Added tests.
How to test:
1. Navigate to the [input …

fix(input, textarea): ensure screen readers announce helper and error text when focused

---

core/src/components/action-sheet/action-sheet.tsx
core/src/components/alert/alert.tsx
core/src/components/loading/loading.tsx
core/src/components/picker-legacy/picker.tsx

Issue number: resolves #29858
---------
When swiping between elements using Android TalkBack, a green box is shown for certain overlays and it gains focus at the beginning and end of those overlays: 
The `aria-hidden` attribute is now added to the focus trap divs to hide them from screen readers, without preventing these divs from trapping keyboard focus.
Dev build: `8.3.4-dev.11729882231.1b2e7f13`

fix(overlays): hide the focus trap div from screen readers

---

core/src/components/item/item.common.scss
core/src/components/radio/radio.common.scss
core/src/components/segment-button/segment-button.common.scss
core/src/components/spinner/spinner.common.scss
core/src/components/toast/toast.common.scss
core/src/themes/mixins.scss

---------
The mixins file is not using prefixing the string functions, resulting in the string function file needing to be imported to work in the `*.common.scss` files. 
Properly prefix the string function calls.
Steps to test:
1. Switch to the `next` branch
2. Navigate to the `core` directory in your terminal and run the local server
3. Open all `*.common.scss` files that import the following line and remove it:
```scss
@import "../../themes/functions.string";
```
4. See the error in the terminal: `$n: Invalid index 2 for a list with 1 elements.`
5. Switch to this branch, see the error is gone without the imports

refactor(scss): properly prefix string imports

---

core/src/components/segment-view/segment-view.tsx

Segment view does not contains styling once at ionic theme.
Same default style as md should be added.

fix(segment-view): add missing ionic theme fallback to the segment-view

---

core/src/components/segment/test/segment-events.e2e.ts

---------
There's a flaky test that was disabled for segment. It's been known that gesture tests are prone to be flaky. 
- Fixed the test by switching to the improved `dragElementBy` function
N/A

test(segment): fix flaky gesture test and re-enable

---

core/src/components/toast/toast.scss

Issue number: resolves #29998
---------
Applying a custom layout to `ion-toast::part(container)`, for example `width: 50%`, will make the part of the toast outside this element's bounds non-interactive for swiping gestures.
Can swipe from anywhere on the toast with custom layout applied to ::part(container)
| Before | After                                         |
|-------|-----------------------------------------------------|
|  <video src="https://github.com/user-attachments/assets/fc450066-5fb1-4fd9-bfbd-7f2cd55ce855"></video>  | <video src="https://github.com/user-attachments/assets/991f6a42-f6fe-479b-9f68-7e7e35dca799"></video> |

fix(toast): swipe gesture works with custom container layout

---

core/src/components/header/header.utils.ts
core/src/components/header/test/condense/header.e2e.ts

Issue number: resolves #29347 
---------
Focusable elements like buttons cannot be accessed within the `ion-header` when it's collapsed. They're only accessible once the small title is displayed.
- Moved the `aria-hidden` from the header to `ion-title`, this aligns with native.
- Updated existing test.
Dev build: `8.4.1-dev.11732064156.12837790`

fix(header): use aria attributes to hide small title when collapsed

---

core/src/utils/overlays.ts

---------
PR https://github.com/ionic-team/ionic-framework/pull/29951 would hide the overlays from screen readers while animating. This allows the element to navigate to its correct destination for screen readers to interact with. Otherwise, the focus rings would never appear. However, this ended up breaking the interaction for iOS.
- Overlays are hidden from screen readers while animating only if the platform is `android`. Since the original issue only applied to Android devices.
Dev build: `8.4.1-dev.11732033492.170e160c`
Test on iOS and Android devices.

fix(overlays): announce info after opening based on platform

---

core/src/components/accordion/accordion.ionic.scss
core/src/components/accordion/test/shape/index.html

---------
The animation is off for the `ionic` theme when using an accordion with text content.
- Moves the padding to the inner content element so the `offsetHeight` will be calculated properly and the animation will be smooth
[Preview](https://ionic-framework-git-rou-11362-ionic1.vercel.app/src/components/accordion/test/shape?ionic:theme=ionic)

fix(accordion): move padding to inner element to use proper animation

---

core/src/components/segment/segment.tsx

Issue number: resolves #30000 
---------
The "swipeable segments" feature does not work correctly in an Angular environment (tested with both standalone and module architecture). The issues is that the `ion-segment-view` element is not correctly "attached" to the segment since it does not exist at the time the `connectedCallback()` is first executed.
Added the logic to connect the `ion-segment-view` to the `componentDidLoad()` callback in addition to the `connectedCallback()`. The existing logic was left in place for the case where the element is removed and reattached to the DOM.
Dev Build: `8.4.2-dev.11733239325.140ef7c3`

fix(segment): add logic to connect to segment-view in `componentDidLoad()` callback

---

core/scripts/tokens/index.js
core/scripts/tokens/utils.js
core/src/foundations/ionic.utility.scss

---------
- Now the different border tokens will generate the utility-classes with the expected CSS attribute for each one!

fix(tokens): fixed border generated utilityclasses

---

.github/workflows/actions/build-angular-server/action.yml
.github/workflows/actions/build-angular/action.yml
.github/workflows/actions/build-core-stencil-prerelease/action.yml
.github/workflows/actions/build-core/action.yml
.github/workflows/actions/build-react-router/action.yml
.github/workflows/actions/build-react/action.yml
.github/workflows/actions/build-vue-router/action.yml
.github/workflows/actions/build-vue/action.yml
.github/workflows/actions/publish-npm/action.yml
.github/workflows/actions/test-core-clean-build/action.yml
.github/workflows/actions/test-core-lint/action.yml
.github/workflows/actions/test-core-screenshot/action.yml
.github/workflows/actions/test-core-spec/action.yml
.github/workflows/actions/test-react-e2e/action.yml
.github/workflows/actions/test-react-router-e2e/action.yml
.github/workflows/actions/test-vue-e2e/action.yml
.github/workflows/actions/update-reference-screenshots/action.yml

---------
Github actions are failing due to using node v18.
[Failing example](https://github.com/ionic-team/ionic-framework/actions/runs/12379078209/job/34552448830)
- Github actions have been updated to use node v20.
[Passing example](https://github.com/ionic-team/ionic-framework/actions/runs/12379780879/job/34554955539)
N/A

chore(ci): use node v20 for github actions

---

core/src/components/segment-button/segment-button.tsx
core/src/components/segment-view/test/basic/index.html

---------
When the `connectedCallback` method is called for a segment-button and its corresponding segment-content has not been created in that instant, a console error is thrown and the method returns.
- `connectedCallback` will now wait, at most 1 second, for the corresponding segment-content to be created.
- The new behaviour can be tested in segment-view/basic.

fix(segment-button): protect connectedCallback for when segment-content has not yet been created

---

core/src/components/segment-button/segment-button.tsx
core/src/components/segment-view/test/basic/index.html
core/src/utils/helpers.ts

---------
When the `connectedCallback` method is called for a segment-button and its corresponding segment-content has not been created in that instant, a console error is thrown and the method returns.
- `connectedCallback` will now wait, at most 1 second, for the corresponding segment-content to be created.
- The new behaviour can be tested in segment-view/basic.

fix(segment-button): protect connectedCallback for when segment-content has not yet been created (cherry-pick)

---

core/src/components.d.ts
core/src/components/app/app.tsx
core/src/utils/focus-visible.ts
core/src/utils/helpers.ts

---------
The `focusVisibleElement` function does not take into account that a user might use a custom `appRootSelector`. If they do, the the `setFocus` function will throw an error that it does not exist leading to focus not being established on the elements.
This error can be seen when opening a `ion-select` with a modal interface.
- Created a new function to reuse the focus logic within `ion-app` and for the custom app root selector. This will make sure that there will be consistency between both if that logic needs to change in the future.

fix(focusVisibleElement): set focus on custom appRootSelector

---

core/src/components/avatar/avatar.ionic.scss

---------
- Remove usage of :not() for the badge ionic sizes.

refactor(avatar): remove usage of :not()

---

core/src/utils/platform.ts
core/src/utils/test/platform.utils.ts

ref: https://github.com/ionic-team/capacitor/issues/7884
---------
`this.platform.is('capacitor')` returns `false` in Capacitor App.
`this.platform.is('capacitor')` returns as expected.
It might also need to be fixed.
https://github.com/ionic-team/ionic-framework/blob/14b6538d98303cb753d881ec6978fb98f53ed54c/core/src/utils/test/platform.utils.ts#L32

fix(capacitor): replace deprecated platform check method

---

core/src/components/toggle/toggle.tsx

---------
The blur and focus events do not trigger when clicking even though the value changes. Those events are only triggered when dragged.
This leads to Angular validation to not work accurately when clicking so the `ion-touched` is never added to the toggle since it relies on the blur event. 
- The blur and focus events also trigger on click. This follows the same logic as `ion-checkbox`.
How to test:
Recommendation to use `toggle/test/basic/index.html`: [Preview](https://ionic-framework-git-toggle-focus-ionic1.vercel.app/src/components/toggle/test/basic)
Add the following script:
```js
<script>
document.addEventListener('ionChange', () => {
console.log('toggle: ionChange')
});
document.addEventListener('ionFocus', () => {
console.log('toggle: ionFocus')
}); …
```

fix(toggle): trigger focus and blur on click

---

core/package-lock.json
core/package.json
packages/vue/package-lock.json
packages/vue/package.json
packages/vue/src/components/IonIcon.ts
packages/vue/src/components/IonNav.ts
packages/vue/src/proxies.ts

Issue number: fixes #30179
---------
There have been issues reported on version 8.4.3 related to the type information changing for Vue
This patch updates the Vue components to be correctly types using a new version of the output target.

fix(vue): update output target and resolve type issues

---

core/package-lock.json
core/package.json
packages/vue/package-lock.json
packages/vue/package.json

Issue number: resolves #30221
---------
We had to make a new release of the output target to ensure all Vue type fixes are shipped.
Pin to the latest output target.

fix(vue): pin Vue output target to latest release

---

core/src/components/infinite-scroll/test/top/infinite-scroll.e2e.ts

---------
Test is flaky with Safari but only on CI.
- Disabled test for now

test(infinite): disable flaky test when running in CI

---

core/src/components/modal/gestures/sheet.ts

---------
Currently, when a sheet is moved while `expandToScroll` is disabled, the DOM is queried excessively causing performance degradation.
We now cache the targeted element in `onStart` and refer to it in `onMove` and `onEnd`, preventing over-querying the DOM
This regression was introduced in #30257 and quickly highlighted by a member of the community

perf(sheet): fixing performance regression on modal sheets when expandToScroll is false

---

packages/angular/test/base/src/app/standalone/app-standalone/app.component.ts
packages/angular/test/base/src/app/standalone/router-link/router-link.component.ts
packages/angular/test/base/src/app/standalone/standalone.component.ts

---------
Currently the standalone test app for router-link in Angular imports all of `RouterModule` when it only needs to import `RouterLink` from `@angular/router`
Now, the Angular test app will import only what it needs from router instead of over-importing.
This PR helps align our Angular test apps with a more real-world implementation expectation

test(angular): fixing over-import of RouterModule in the standalone router-link test

---

core/src/components/range/range.tsx
core/src/components/range/test/range-events.e2e.ts

Issue number: resolves #29619 
---------
The `ionInput` emits for range even when the value hasn't changed. This does not match our documentation. It should only emit when the value changes (and continuously while the user is dragging the knob).
- Moved the emitter to the value watch function, to determine if the value has changed.
- Added a test
-
How to test:
1. Navigate to the [range basic HTML file](https://github.com/ionic-team/ionic-framework/blob/8ed08fcba59c9fde5c6d08d721fd1d00642de4f9/core/src/components/range/test/basic/index.html#L77)
2. Add the following script
```
const ionicRanges = document.querySelectorAll('ion-range');
ionicRanges.forEach(range => {  
range.addEventListener('ionInput', function(ev) {
console.log('ionInput', ev.currentTarget.value);
});
});
```
3. Navigate …

fix(range): emit ionInput when value changes

---

core/src/components/segment-button/segment-button.tsx
core/src/utils/helpers.ts

---------
Segment buttons do not consistently set themselves to a disabled state. When disabling them and rapidly refreshing the page, their state may vary—sometimes they appear disabled, and other times they do not.
This was due to this [PR](https://github.com/ionic-team/ionic-framework/pull/30138). The reason that this PR was created was due to the console errors being shown too early when segment buttons and contents were dynamically rendered.
- I reverted the changes added through the other PR since the `setTimeout` was causing the inconsistency. 
- By moving the console errors to `componentWillLoad`, it provides `ion-segment-content` time to render before the console errors are thrown.
Dev build: `8.5.2-dev.11742514102.1b51674d`
How to test:
1. Run the server …

fix(segment-button): ensure consistent disabled state for segment-content error handling

---

core/src/utils/overlays.ts
core/src/utils/test/overlays/overlays-scroll-blocking.spec.ts

Issue number: resolves #30112 
---------
When toast is presented, the `backdrop-no-scroll` class is added to the body when using Frameworks like Angular. It should not add this class as toast does not be setting focus trap as mentioned in the [comments](https://github.com/ionic-team/ionic-framework/blob/1cfa915e8fe362951c521bce970a9f5f10918ab2/core/src/utils/overlays.ts#L514-L520).
- Class is only added when the overlay that is presented is not a toast component.
- Test was added.
N/A

fix(overlays): exclude backdrop-no-scroll class when toast is presented

---

core/src/index.ts
core/src/utils/logging/test/logging.spec.ts

Issue number: resolves #30255
---------
`LogLevel` is not properly exported
Exports `LogLevel` in core
Dev build: `8.5.4-dev.11743715474.1eadbd25`

fix(config): properly export LogLevel

---

core/src/components/toggle/toggle.scss
core/src/components/toggle/toggle.tsx

---------
Currently, MacOS voice over on Safari does not recognize ion-toggle correctly and fails to highlight the element properly
By adding the role property to the host element, we're correctly identifying the toggle so Safari knows how to handle it.

fix(toggle): ensure proper visual selection when navigating via VoiceOver in Safari

---

core/src/components/modal/modal-interface.ts

Issue number: resolves #30356
---------
Cannot use expandToScroll property in ModalController.create
ExpandToScroll can be added without syntax problems

fix(modal): add expandToScroll property to ModalOptions

---

core/src/components/checkbox/checkbox.tsx
core/src/components/checkbox/test/basic/checkbox.e2e.ts
core/src/components/input/input.tsx
core/src/components/input/test/basic/input.e2e.ts
core/src/components/select/select.tsx
core/src/components/select/test/basic/select.e2e.ts
core/src/components/textarea/test/basic/textarea.e2e.ts
core/src/components/textarea/textarea.tsx
core/src/components/toggle/test/basic/toggle.e2e.ts
core/src/components/toggle/toggle.tsx

Issue number: resolves #30165
---------
Currently, several components will trigger their `onClick` twice if you click on their labels.
After this fix, the affected components will only trigger `onClick` once per click of their labels or click directly on the element.
The affected components are:
- Checkbox
- Select
- Textarea
- Toggle
- Input
I also tested radio and range but could not reproduce the issue for them.
Note that two of the components, checkbox and toggle, had to have special implementations for both their test and fix because of how the host component acts as the component for accessibility purposes.
Current dev build: `8.5.7-dev.11746044124.147aab6c`

fix(labels): prevent clicking a label from triggering onClick twice on several components

---

core/src/components/input/input.tsx
core/src/utils/input-shims/hacks/scroll-assist.ts

---------
If scroll assist is on (by default it is on for iOS mobile devices), then focus will be redirected to the input if a `focusIn` event fires within the component. This leads to some elements to not being accessible with screen readers.
For example: When the clear button is focused, focusin is dispatched and bubbles up to the ion-input. Our [scroll assist utility listens for focusin](https://github.com/ionic-team/ionic-framework/blob/2fc81ddc9b35d6909fd4b585079aedabbd659233/core/src/utils/input-shims/hacks/scroll-assist.ts#L135) to adjust the scroll position. It also causes the input to be re-focused. As a result, when swiping to the clear button with a screen reader, focus will be forcibly moved back to the input. This means that users cannot swipe away from …

fix(scroll-assist): allow focus on input's siblings

---

core/src/components/modal/gestures/sheet.ts

Issue number: resolves #30468
---------
Currently, if you use pointer events to drag the content of a sheet modal with `expandToScroll` disabled and have you have a footer and a dismiss button, then you use the dismiss button to close the modal, the footer will be stuck in its pinned position at the bottom of the screen.
Additionally, if you have multiple footers, only one of them properly gets pinned and unpinned.
- We now move footers back to their stationary position when we finish our drag event on modal content
- We support pinning and unpinning multiple footers at the same time now
Dev build: `8.6.1-dev.11749575087.1b86eb67`

fix(modal): reset footer positioning after content drag and multi-footer support

---

CHANGELOG.md
core/CHANGELOG.md
core/package-lock.json
core/package.json
core/src/components/fab/test/custom-size/fab.e2e.ts
core/src/components/item-sliding/item-sliding.tsx
core/src/components/modal/gestures/sheet.ts
core/src/components/popover/test/basic/popover.e2e.ts
lerna.json
packages/angular-server/CHANGELOG.md
packages/angular-server/package-lock.json
packages/angular-server/package.json
packages/angular/CHANGELOG.md
packages/angular/package-lock.json
packages/angular/package.json
packages/docs/CHANGELOG.md
packages/docs/package-lock.json
packages/docs/package.json
packages/react-router/CHANGELOG.md
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react/CHANGELOG.md
packages/react/package-lock.json
packages/react/package.json
packages/vue-router/CHANGELOG.md
packages/vue-router/package-lock.json
packages/vue-router/package.json
packages/vue/CHANGELOG.md
packages/vue/package-lock.json
packages/vue/package.json

chore(git): update next from main

---

core/src/components/picker-column/picker-column.tsx

Issue number: resolves #29672
---------
The issue on iOS 16 with `elementsFromPoint` is related to how it handles Shadow DOM retargeting when called from the document (global) context.
It leads to an `undefined` element that is required to trigger `ionChange`.
- Returns the top most element as a fallback only if the element has a tag of `'ion-picker-column-option'`.
Dev build: `8.6.2-dev.11749761258.1b46b6a9`

fix(picker-column): fallback to elementFromPoint for iOS 16 Shadow DOM bug

---

packages/angular/test/apps/ng20/package.json

---------
Angular 20 test app is using an unsupported Typescript version.
Angular 20 only supports Typescript 5.8+. I forgot to update it in an earlier [PR](https://github.com/ionic-team/ionic-framework/pull/30507).
- Upgraded TS to the proper version.
N/A

chore(angular): update typescript to support Angular 20

---

packages/angular/README.md
packages/angular/src/schematics/utils/config.ts

Issue number: resolves ionic-team/ionic-docs#2091
---------
Documentation to test `ng add` schematic for @ionic/angular is outdated & it fails when running with:
```
Invalid projectType for my-app: undefined
```
Fix the schematic to support the latest Angular build system & update the documentation for testing local Ionic Framework with `ng add`. 
_I am using `Angular CLI: 20.0.4`_
Run these commands first to see the error: 
```sh
ng new my-app --style=css --ssr=false --zoneless=false
cd my-app
ng add @ionic/angular --skip-confirmation
```
Switch to this branch (`fix-angular-schematics`) and then follow the [new steps](https://github.com/ionic-team/ionic-framework/blob/b9b345303c7e1446a990c11a8ae6f70c1f773493/packages/angular/README.md#testing-local-ionic-framework-with-ng-add) and …

fix(angular): update schematics to support Angular's latest build system

---

core/src/components/item/item.tsx
core/src/components/item/test/inputs/item.e2e.ts

Issue number: resolves #29763 
---------
If the nested content of an ion-item is conditionally rendered and goes from containing zero interactive elements to one or more, a render is not triggered in Angular and the item does not behave correctly for one or more nested inputs.
- A mutation observer is created in `connectedCallback()` to watch for changes in item's child list.  When the `childList` changes, two pieces of state that track whether the item needs to be interactive and whether there are multiple interactive elements are updated.
- Add `disconnectedCallback()` and logic to disconnect Mutation Observer.
- Create new function `totalNestedInputs()` with logic from existing `setMultipleInputs` function to be used for both `setMultipleInputs` and new function `setIsInteractive`.
I …

fix(item): allow nested content to be conditionally interactive

---

core/src/components/segment-content/segment-content.scss
core/src/components/segment-view/test/dynamic-height/index.html
core/src/components/segment-view/test/dynamic-height/segment-view.e2e.ts
core/src/components/segment-view/test/input/index.html

Issue number: resolves #30543
---------
On desktop Safari and Android the segment view is not switching to the right segment content when the height is dynamically set or read in as 0. This can be reproduced in the following StackBlitz on Android: https://6dhropnr-aheyyprl.stackblitz.io/
- Sets `min-height` to `1px` on `ion-segment-content` so that it continues to work with a dynamically set height
- Adds an e2e test for Safari to verify the correct content is displayed when it contains a dynamically loaded image
Dev build: `8.6.2-dev.11752524287.1d61cd78`
[Preview](https://ionic-framework-git-fw-6586-ionic1.vercel.app/src/components/segment-view/test/dynamic-height)

fix(segment-view): scroll to correct content when height is not set

---

core/package-lock.json
core/package.json

A major regression related to Reorder was found in Stencil v4.36. Downgrade Stencil until this can be resolved.

chore(deps): downgrade Stencil to v4.33.1

---

core/package-lock.json
core/package.json

Updating outsystems-design-tokens reference. This package removes the Inter font from being the default font, and replaced it with the respective system fonts.
The default font was Inter, that had to be loaded from Google CDN, causing CSP problems with default rules.
- Update to latest version of `outsystems-design-tokens` that no longer uses the Inter font.

chore(deps): update outsystems design tokens package

---

core/src/components/datetime/test/custom/datetime.e2e.ts
core/src/components/datetime/test/custom/index.html
core/src/components/datetime/test/datetime.e2e.ts
core/src/components/input-otp/test/separators/input-otp.e2e.ts

This fixes the flaky/failing tests here:
`should not have visual regressions with a custom styled calendar`
`should switch the calendar header when moving to a month with a different number of days`
You can run them locally using:
- `npm run test.e2e.docker src/components/datetime/test/datetime.e2e.ts -- --repeat-each=10`
- `npm run test.e2e.docker src/components/datetime/test/custom/datetime.e2e.ts -- --repeat-each=10`

test(core): fix flaky datetime and input-otp tests

---

packages/react/test/base/src/App.tsx
packages/react/test/base/src/pages/Icons.tsx
packages/react/test/base/src/pages/Inputs.tsx
packages/react/test/base/src/pages/Main.tsx
packages/react/test/base/src/pages/Tabs.tsx
packages/react/test/base/src/pages/TabsBasic.tsx
packages/react/test/base/src/pages/TabsDirectNavigation.tsx
packages/react/test/base/src/pages/navigation/NavComponent.tsx
packages/react/test/base/tests/e2e/specs/components/tabs-direct-navigation.cy.ts

---------
Manual navigation in the react tests is very finnicky
Improved react test navigation so it more consistently moves from page to page if you're manually reviewing react tests. This was done mostly by adding missing `ion-page` components, but also by adding an exact match to the main component. They're still pretty shaky and not great, but better than before.

test(react): general navigation improvement

---

.github/ionic-issue-bot.yml

The issue bot has several labels to move issues to other repositories. This is no longer needed as you can move issues using the Github interface now:

chore(bot): remove labels that move issues

---

docs/themes/README.md

---------
Separates the themes directory for each new modular theme. Documents the new structure.

refactor(themes): add modular themes directory structure and docs

---

core/src/components/back-button/back-button.tsx
core/src/components/breadcrumb/breadcrumb.tsx
core/src/components/button/button.tsx
core/src/components/card/card.tsx
core/src/components/fab-button/fab-button.tsx
core/src/components/item/item.tsx
core/src/components/router-link/router-link.tsx
core/src/global/ionic-global.ts
core/src/index.ts
core/src/themes/base/default.tokens.ts
core/src/utils/config.ts
core/src/utils/helpers.spec.ts
core/src/utils/helpers.ts
core/src/utils/theme.spec.ts
core/src/utils/theme.ts

---------
- Moves `openURL` out of the `theme` utils because it makes more sense in `helpers`
- Adds support for the default `default.tokens.ts` design tokens file
- Adds support for custom theme set globally and on a component 
Requires additional changes in order to test.

feat(themes): add support for modular themes and custom themes

---

core/src/components/select-modal/select-modal.ionic.scss

---------
When opening a ion-select with a modal interface, the first option is focused and, as such, has a border.
This happens because an ion-item is being rendered, which has a specific styling for focused stated.
When inside a `ion-select-modal`, we don't want this specific `ion-item` styling.

fix(select-modal): hide focus option's border for ionic theme

---

core/package.json
core/scripts/tokens/index.mjs
core/scripts/tokens/utils.mjs
core/src/foundations/ionic.vars.scss

- The variables when being generated from the tokens were causing the fallback to `$ion-font-family` to be with invalid format: 
```
$ion-font-family: var(
--token-font-family,
"-apple-system, system-ui, " Segoe UI ", Roboto, Helvetica, Arial, sans-serif, " Apple Color Emoji ", 
" Segoe UI Emoji", " Segoe UI Symbol "",
sans-serif
);
```
- Additionally the command to generate the css from the tokens, was not prepared to run on windows machines.
- Removed the added quotes to the variable coming from the tokens:
```
$ion-font-family: var(
--token-font-family, -apple-system, system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif,
"Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
);
```
- Changed the command `build.tokens` to run on windows
- Generated a new version of …

fix(font-family): fallback coming from tokens was badly formatted
