ionic-team/ionic-framework

js/utils/platform.js

Hope this makes it a little more clear on how to use the Platform methods as I was a little in doubt today on how they should be used.

Added usage information for Platform methods

---

scss/_items.scss
scss/_platform.scss

fix(css): add height to item-image and fix nav-bar

---

js/utils/events.js

- updates onGestures and offGesture methods to be correct.

docs(EventController): onGesture and offGesture corrections

---

js/angular/service/popover.js

The commas after $scope aren't needed.

Remove unrequired comma

---

README.md

Created a link for the 'Commit Conventions' leading to http://github.com/ajoslin/conventional-changelog

Created Commit Convention Link for README.srt

---

js/views/scrollView.js

Fix IE10 scroll issue. This addresses #2728

bug(scroll)

---

js/angular/directive/collectionRepeat.js

Fixes driftyco/ionic#2935
I wasn't quite sure which events would be most appropriate. Might `afterEnter` and `beforeLeave` be even better?

Bind collection-repeat resize on view enter/leave

---

bower.json
scripts/update-angular.sh

- Update bower.json to match dependencies used and
version numbers.

Add all angular dependencies to update-angular.sh

---

scss/_action-sheet.scss

Constrain action sheet width for better appearance on larger devices

---

js/angular/service/platform.js

Added the list of build-in hooks on the hardware back button and explained the connection between the existing actions and actions registered through `$ionicPlatform.registerBackButtonAction`. Also added an example describing how to selectively override existing actions.

docs($ionicPlatform) List back button priorities

---

js/angular/controller/navBarController.js
js/angular/controller/navViewController.js
js/angular/directive/headerFooterBar.js
scss/_bar.scss

fix(subHeader): removes borders on android subheaders

---

scss/_variables.scss

Add Segoe UI for windows phone devices

Add Segoe UI font

---

scss/_modal.scss

fix(css): fix header bar in modals with top tabs

---

README.md

README.md file has some consistency errors with the periods.

Consistency fix to README.md

---

CHANGELOG.md

Typo in link in ChangeLog.md

---

js/angular/controller/tabsController.js

Changed first letter of the first word in comment on line 38 to a capital letter to be consistent with other comments found in the file.

Formatted error on line 38 tabsController.js

---

js/views/sliderView.js

Successfully tested on browser, Windows Phone and Android. Still need to be tested on iOS. Could someone tell me if it's stil working fine on iOS?

Fix sliderview on Windows Phone devices

---

js/angular/service/viewSwitcher.js

This improves perceived performance, especially on Android, and fixes
https://github.com/driftyco/ionic/issues/3907

fix(viewSwitcher): greatly improved perceived performance by using ionic.requestAnimationFrame

---

js/angular/service/popover.js

Prevent the popover options to be overwritten (fix #3173)

---

js/angular/directive/navView.js

The sentence on line 51 was missing the word "if".

Add missing "if"

---

js/angular/directive/actionSheet.js
js/angular/service/actionSheet.js

actionsheet is good radio-like component, I add a little codes to extend it which can be also  checkbox-like.The changes as follows:
1. add a 'ng-class' :If the button clicked, it can change the style which is customized.
2. deliver buttons to function 'done' .

extension to support multiple selection

---

release/js/ionic-angular.js

Issue was occuring where the el.classList.add function was undefined.

Fixed bug with classlist being null

---

js/angular/service/modal.js

make consistent with surrounding comments....

nit whitespace

---

ionic/components/segment/test/swipe/index.ts
ionic/components/segment/test/swipe/main.html

move the pull request from ionic2 repo
original pull request: https://github.com/3dd13/ionic2/tree/swipe-segment
original issue: https://github.com/driftyco/ionic2/issues/871

combine segment and slides to have swipeable tabs

---

ionic/components/app/app.ts
ionic/components/icon/icon.ts
ionic/components/label/label.ts
ionic/components/label/test/basic/index.ts
ionic/components/label/test/basic/main.html
ionic/components/list/list.ts
ionic/components/option/option.ts
ionic/components/show-hide-when/show-hide-when.ts
ionic/components/slides/slides.ts
ionic/platform/platform.ts
ionic/platform/registry.ts
ionic/platform/storage/local-storage.ts
ionic/platform/storage/sql.ts
ionic/platform/storage/storage.ts

adding more types following the list of files listed in issue https://github.com/driftyco/ionic/issues/5016
1)
only added harmless types,
there was tricky ones that I didn't touch, e.g. the boolean or string getsetter for attribute (component @Input)
2)
after adding type, found a potential bug in getRegisteredComponent
the for loop is expecting an array, but it is actually object
3)
added one dummy test for label, to make sure it works after I add the types
4)
haven't tested everything in platform.ts files, but it looks like they are harmless since most of them are just any or Promise<any>

add more types to function parameters and return type

---

ionic/components/scroll/scroll.ts

Been trying to use scroll with scroll-y but to no avail, and I found out that the directive was listening for scrollY events.

fix(scroll): fix doc about scrollX and scrollY attributes

---

scss/_items.scss

https://github.com/driftyco/ionic/issues/4905

Closes #4905

---

ionic/platform/storage/storage.ts

Adds an `setJson()` method in Storage that can be used complementarily with `getJson()`.

v2: feat(Storage): adds setJson() method

---

ionic/components/action-sheet/action-sheet.ios.scss

- Top padding
- Title font size
- Background default color
- Background active color
- Button border when active.
Left: native iOS 9 Action Sheet
Right: ionic 2
Before fix:
After fix:

v2: Improves CSS style for ActionSheet in iOS

---

ionic/components/button/button.scss

^^ outline full buttons should not have border radius

Fixes border radius in full outline button

---

ionic/components/toolbar/toolbar.ts

added missing quotes to documentation and changed property "placement" to "position"

Documentation update toolbar.ts

---

ionic/components/modal/modal.ts

This addition shows how to access the data that is passed into the modal through the Modal.Create() method.

Show how to access data passed into the modal

---

ionic/platform/cordova.ios.scss

my previous PR was conceptually wrong...

fix(toolbar): toolbar padding when running in cordova iOS

---

ionic/util/util.ts

Array out of bounds check in getQuerystring util

fix(util): array length check

---

ionic/platform/storage/local-storage.ts
ionic/platform/storage/sql.ts
ionic/platform/storage/storage.ts

The current implementation of storage has a lot of duplicated code, bad code style and some typescript types are missing.
Also, it miss a method() to remove all the items in the storage engine.
- adds a clear() method
- refactors the SQL implementation
- adds more typescript types in the Storage Interface

v2: Refactors storage and adds clean() method

---

js/angular/directive/view.js

Updated documentation on state params
-
-
-
1.x
**Fixes**: #

added usage examples of accessing state params from life cycle events

---

js/angular/directive/navView.js

Documentation update reviewed by Adam
-
-
-
1.x
**Fixes**: #

updated documentation

---

ionic/components/button/button.ts

Addresses https://github.com/driftyco/ionic/issues/5938.

fix(button): normalize generated button class names

---

tooling/generator.js
tooling/generators/component/component.tmpl.ts
tooling/generators/directive/directive.tmpl.ts
tooling/generators/page/page.tmpl.ts
tooling/generators/pipe/pipe.tmpl.ts
tooling/generators/provider/provider.tmpl.js
tooling/generators/provider/provider.tmpl.ts
tooling/generators/tabs/tabs.tmpl.ts

This adds support to pass a --ts argument to ionic g to generate typescript code instead of ES6.
Supports PR driftyco/ionic-cli#888

Typescript generators

---

gulpfile.js

This adds a gulp task for creating nightly builds.
- Create a nightly dist-tag in npm for latest nightly build
- Nightly builds will have an 8 char hash appended for uniqueness
- 'publish.nightly' is the task name added
**Fixes**: #6138

Added publish.nightly task to gulp file.

---

js/utils/platform.js

Fix : An </ul> is displayed at the end of online doc.

Improve doc : User Agent and fix closed ul tag

---

gulpfile.js
ionic/components/img/img.ts
ionic/platform/platform.ts

This pr adds linting and unit tests to the preprelease gulp task.
- Include tslint task run within the prerelease gulp task
- Include karma test run within the prerelease gulp task
- Fix 2 typescript files that had tslint issues so that we can avoid the lint failures going forward.
**Fixes**: #5755

chore(build): add tslint and unit tests to prerelease gulp task

---

ionic/components/select/select.ts

update docs , incorrect closing tag
-
-
-
**Fixes**: #
incorrent closing tag

update select.ts docs

---

ionic/components/slides/slides.ts
ionic/components/slides/swiper-widget.d.ts

First pr, I'm using ionic 2 slides in a multi-step form and sliding to a specific slide is useful

feat(slides): add ability to slide to specific index

---

ionic/components/modal/modal.ts

Minor misspelled word fix on the file comment.
-
-
-
**Fixes**: #

Update modal.ts comments

---

js/angular/controller/refresherController.js
test/unit/angular/controller/refreshController.unit.js

Add translate3d instead translateY in refresherController.js
**Fixes**: #6016

Change translateY to 3d

---

ionic/util/keyboard.ts

spelling (chech -> check)

---

ionic/components/item/item-sliding-gesture.ts
scripts/karma/karma.conf.js

Fix a small typo in the item-sliding-gesture class

Fix a small typo in a function declaration

---

src/components/infinite-scroll/infinite-scroll.ts
src/components/virtual-scroll/virtual-scroll.ts

Fixing https://github.com/driftyco/ionic-site/issues/605

Fixing {{}} display issues

---

src/platform/storage/sql.ts

Add documentation to clear function

Update docs Sqlstorage

---

src/components/scroll/scroll.ts

corrected typo

---

src/components/picker/picker.ts

Fixes #6704
- add a receivingEvents variable
- refactors some code in picker.ts to make it more readable
- replaces:
```diff
-        '<div *ngFor="let c of d.columns" [col]="c" class="picker-col"> (change)="_colChange($event)"</div>' +
+        '<div *ngFor="let c of d.columns" [col]="c" class="picker-col" (change)="_colChange($event)"></div>' +
```
**Fixes**: #6704

fix(picker): safari fired pointerEnd() twice

---

src/components/modal/modal.ts

refactor(modal): import ElementRef, fix no-implicit-any error

refactor(modal): import ElementRef, fix no-implicit-any error

---

src/util/events.ts

Event documentation argument confusion
- This PR makes it so that the piece of code in the docs works as intended. Otherwise, the second console.log statement will result in an array output, instead of the intended user object.
**Ionic Version**: 2.0.0.beta-7
**Fixes**: https://github.com/driftyco/ionic-site/issues/544

Clean up confusion with Event arguments

---

src/components/modal/modal.ios.scss
src/components/modal/modal.md.scss
src/components/modal/modal.scss
src/components/modal/modal.ts
src/components/modal/modal.wp.scss

refactor(inset-modal): inset-modal fixes

---

src/components/item/item-sliding.ts
src/components/item/test/sliding/index.ts
src/components/item/test/sliding/main.html

Closes #5192 and adds more tests

fix(item): sliding item supports dynamic options + tests

---

src/components/modal/modal.ts

Enabling backdrop dismiss and escape key dismiss on Modals

feat(modal): background click and escape key dismiss

---

src/components/range/range.ts
src/components/range/test/basic/page1.html
src/components/searchbar/searchbar.ts
src/util/debouncer.ts

https://github.com/driftyco/ionic/issues/6894
- Adds debouncer input to range
- New debouncer helper, so we don't repeat code.
**Fixes**:  #6894

feat(range): (ionChange) event can be debounced

---

demos/loading/index.ts

Update Loading demo to match [Beta 10](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-beta-10) upgrade guide
- Add `ion-header` around `ion-navbar`
- Remove `*navbar` attribute

(demos) Loading - update demo to Beta 10

---

src/config/bootstrap.ts

Fixes ripple/activate in buttons
http://ghk.h-cdn.co/assets/cm/15/11/640x480/54ffe5266025c-dog1.jpg)

fix(bootstrap): tapclick is injected, probably

---

src/platform/storage/sql.ts

Provide clarification between WebSQL and SQLite

---

test/html/component-test.html
test/html/sidemenu-starter.html
test/html/tabs-starter.html

Just organize indentation and remove empty lines from start templates

Starter Templates: fix indentation and remove empty lines

---

src/animations/animation.ts

perf(animation): using will-change when progressStep()

---

tooling/generators/provider/provider.tmpl.js

Fixes a few trailing whitespaces and spacing issues.
Nothing important.
**Fixes**: none
**Updated from**: #6988

style(templates): fix style variations in tooling templates

---

src/components/label/label.scss
src/components/range/test/basic/page1.html

fix(range): ion-label stacked with ion-range

---

src/components/app/test/gesture-collision/index.ts
src/components/app/test/gesture-collision/main.html
src/components/app/test/gesture-collision/page1.html
src/components/item/item-reorder-gesture.ts
src/components/item/item-sliding-gesture.ts
src/components/item/item-sliding.ts
src/components/list/list.ts
src/components/menu/menu-gestures.ts
src/components/menu/menu.ts
src/components/menu/test/basic/page1.html
src/components/nav/nav-controller.ts
src/components/nav/nav-portal.ts
src/components/nav/nav.ts
src/components/nav/swipe-back.ts
src/components/picker/picker-component.ts
src/components/range/range.ts
src/components/refresher/refresher.ts
src/components/refresher/test/refresher.spec.ts
src/components/slides/test/loop/index.ts
src/components/tabs/tab.ts
src/components/toggle/toggle.ts
src/config/providers.ts
src/gestures/drag-gesture.ts
src/gestures/gesture-controller.ts
src/gestures/test/gesture-controller.spec.ts
src/index.ts
src/util/dom.ts
src/util/ui-event-manager.ts

Fixes: https://github.com/driftyco/ionic/issues/7120
Fixes: https://github.com/driftyco/ionic/issues/7075
Fixes: https://github.com/driftyco/ionic/issues/7011
Fixes: https://github.com/driftyco/ionic/issues/6726
Fixes: https://github.com/driftyco/ionic/issues/7120
Fixes: https://github.com/driftyco/ionic/issues/7066
Fixes: https://github.com/driftyco/ionic/issues/6913
Fixes: https://github.com/driftyco/ionic/issues/6958

New Gesture controller

---

src/components/app/test/gesture-collision/page1.html
src/components/item/item-sliding-gesture.ts
src/components/list/list.ts
src/components/menu/menu-gestures.ts
src/components/menu/menu.ts
src/components/nav/swipe-back.ts
src/components/refresher/refresher.ts
src/gestures/drag-gesture.ts
src/gestures/gesture-controller.ts
src/gestures/recognizers.ts
src/gestures/slide-edge-gesture.ts
src/gestures/slide-gesture.ts

refactor(gestures): dropping hammer for drag gestures

---

src/animations/animation.ts
src/components/app/test/animations/index.ts
src/components/menu/menu-controller.ts
src/components/menu/menu-gestures.ts
src/components/menu/menu-types.ts
src/components/menu/menu.ts
src/components/menu/test/basic/index.ts
src/components/menu/test/basic/main.html
src/components/modal/test/basic/index.ts

fix(menu): only one menu can be opened at a time

---

src/components/app/app.ts
src/platform/registry.ts

fix(backdrop): flicker in UIWebView

---

src/components/menu/menu.ios.scss
src/components/menu/menu.md.scss
src/components/menu/menu.scss
src/components/menu/menu.ts
src/components/menu/menu.wp.scss
src/gestures/slide-gesture.ts

- `display: none;` when menu is closed
- `ion-backdrop` is display: none when it is not used
- `ion-backdrop` is much smaller

perf(menu): several improvements

---

src/components/label/label.ts

Clarity of documentation.
A simple wording change.

Edit copy for clarity

---

js/angular/controller/sideMenuController.js

Sets leftShowing flag in SideMenuController only when amount of showing menu is greater than zero
- optimized settings of leftShowing and rightShowing flags in SideMenuController

fix(menu): proper setting of leftShowing flag

---

src/components/alert/test/basic/index.ts
src/components/alert/test/dismiss/index.ts

Adds test for opening an overlay component in `ionViewDidEnter`

chore(test): add test for overlays in viewDidEnter

---

src/gestures/ionic-gesture-config.ts

Fix angular style import gestures/IonicGestureConfig

Fix Angular style IonicGestureConfig

---

src/components/input/input.ts
src/components/scroll/scroll.ts
src/config/config.ts
tooling/generators/component/component.tmpl.html
tooling/generators/component/component.tmpl.js
tooling/generators/component/component.tmpl.ts
tooling/generators/directive/directive.tmpl.js
tooling/generators/directive/directive.tmpl.ts

Fixes typos, broken links, and missing info
- Update links in component and directive generator code comments
- Fix typo in input docs
- Add missing swipeBackEnabled option to config docs
- Update scrollY param docs for scroll
**Fixes**: #

Update docs and fix typos

---

src/components/item/item-reorder.scss

adds the ability to animate the reorder button.
2.x

feat(itemReorder): animate reorder button

---

src/components/item/item-sliding.ts

Typo error
- Typo
**Fixes**:  Change to "Combine"

Typo in the documentation

---

src/translation/translate.ts

Adds a deprecation notice for the translate service.

refactor(translate): add deprecation notice

---

src/components/toast/toast.ts

-
-
-
**Fixes**: #
The table is actually below not above.

Updated Direction For Table Placement

---

scripts/gulp/constants.ts
scripts/gulp/gulpfile.ts
scripts/gulp/tasks/e2e.ts
scripts/gulp/tasks/polyfill.source.ts
scripts/gulp/tasks/polyfill.ts
scripts/gulp/tasks/release.ts
scripts/gulp/util.ts

- Standalone polyfill task to copy polyfills to `scripts/polyfill`
- Separation of concerns
- Release and e2e have their own polyfill task

feat(polyfills): split up code and source polyfill task

---

scripts/gulp/util.ts

- add dom polyfills to be bundled

fix(polyfills): add dom polyfills

---

src/util/events.ts

docs(events): fix private functions

---

scripts/gulp/tasks/docs.ts

Fix typo task gulp -> docs
**Ionic Version**:  nightly

chore(docs): fix typo task docs deps

---

CHANGELOG.md

Fix quotes for copy & paste purposes.
-
-
-
**Fixes**: #

Swap smart quotes with dumb quotes

---

CHANGELOG.md

Clarified upgrade instructions

---

src/components/segment/segment.ts

-
-
-
**Fixes**: #
Closes #8371

fix(segment): add missing input

---

CHANGELOG.md

Added a link to a discussion where it is explained why change from private typescript keyword to public is necessary. This has made a lot of buzz in the community, so with that link people may understand that change better.

Improve docs

---

src/components/button/button.ios.scss
src/components/button/button.md.scss
src/components/button/button.ts
src/components/button/button.wp.scss
src/components/button/test/button.spec.ts
src/components/button/test/raised/main.html

Improvements of code and docs after refactoring rc0
- Delete @input fab;
- Adjust docs usage fab to ion-fab;
- Delete variables SASS not used;
- Delete @property fab-* docs;
- Link docs FabButton and FabContainer;
- Delete tests fab.
**Ionic Version**: rc0

Improvement Fab refactoring rc0

---

src/components/fab/fab.scss

docs(fab): add docs variables SASS

---

src/components/alert/alert.ios.scss
src/components/alert/alert.scss
src/components/input/input.scss
src/components/slides/slides.scss
src/themes/ionic.mixins.scss

I think this change makes sense, but Idk haha, but it was an easy change

refactor(css): appearance mixin

---

src/components/nav/test/basic/app-module.ts

**Ionic Version**: nightly
**Fixes**: #

style(test): add spacing in comment fix lint

---

src/components/nav/test/insert-views/app-module.ts

**Ionic Version**: nightly
**Fixes**: #

style(nav): fix linters tests missing semicolon and spaces

---

src/components/nav/test/basic/app-module.ts
src/transitions/transition-ios.ts
src/transitions/transition-md.ts

https://github.com/driftyco/ionic/issues/7171 #8436
**Fixes**: #7171

fix(transition): ios-transition can be used in MD/WP

---

src/components/infinite-scroll/infinite-scroll.ts
src/components/infinite-scroll/test/basic/app-module.ts
src/components/infinite-scroll/test/basic/main.html

feat(infinite-scroll): it can be enabled/disabled from a ng input

---

src/components/app/app-root.ts
src/components/modal/modal.ts

fix(modal): alerts do not trigger modal lifecycle events

---

src/navigation/deep-linker.ts
src/navigation/nav-util.ts
src/navigation/test/deep-linker.spec.ts

Still a few changes that I need to make regarding dynamic links
2.x

docs(deeplinker): add inital docs

---

CHANGELOG.md

fix(): dependencies for RC1 upgrade

---

src/platform/cordova.ios.scss
src/platform/cordova.md.scss
src/platform/cordova.scss
src/platform/cordova.wp.scss

fix(cordova): add Sass variables for md and wp statusbar padding

---

src/util/ionic-error-handler.ts

**Ionic Version**:  nightly
**Fixes**: #

style(IonicErrorHandler): fix lint delete space return

---

src/components/searchbar/searchbar.ts
src/components/searchbar/test/basic/main.html

**Ionic Version**: 2.0.0.rc-1
**Fixes**: #8855

fix(searchbar): positionElements to assign input mode fixes #8855

---

CHANGELOG.md

Updates changelog to avoid issue https://github.com/driftyco/ionic-app-scripts/issues/212.
- Dependencies updated to match https://github.com/driftyco/ionic2-app-base/blob/master/package.json.

Update package.json dependencies to avoid ionic-app-scripts issue #212

---

package.json

See https://github.com/driftyco/tslint-ionic-rules/commit/1852b90687ee74375a0cd98d23396f74bd0654c8
-
-
-
**Fixes**: #

chore(): bump version tslint-ionic-rules

---

src/components/action-sheet/action-sheet.ios.scss
src/components/action-sheet/action-sheet.md.scss
src/components/action-sheet/action-sheet.wp.scss
src/components/alert/alert.ios.scss
src/components/alert/alert.md.scss
src/components/alert/alert.wp.scss
src/components/card/card.ios.scss
src/components/card/card.md.scss
src/components/card/card.wp.scss
src/components/checkbox/checkbox.ios.scss
src/components/checkbox/checkbox.md.scss
src/components/checkbox/checkbox.wp.scss
src/components/content/content.ios.scss

Short description of sass variables for action sheet, alert, card, checkbox and content
- Description of sass variables

docs(): add variable descriptions

---

src/components/modal/modal.ios.scss
src/components/modal/modal.md.scss
src/components/modal/modal.scss
src/components/modal/modal.wp.scss

Add sass variables docs for modal component
- Docs for the sass variables

docs(modal): add sass variable descriptions

---

src/components/item/item.ios.scss
src/components/item/item.md.scss
src/components/item/item.wp.scss

Add sass variables docs for item component
- Docs for the sass variables

docs(item): add sass variable descriptions

---

src/components/input/input.ios.scss
src/components/input/input.md.scss
src/components/input/input.wp.scss

Add sass variables docs for input component
- Docs for the sass variables

docs(input): add sass variable descriptions

---

src/components/datetime/datetime.ios.scss
src/components/datetime/datetime.md.scss
src/components/datetime/datetime.wp.scss
src/components/input/input.ios.scss
src/components/input/input.md.scss
src/components/input/input.wp.scss

Add sass variables docs for DateTime component
- Docs for the sass variables

docs(datetime): add sass variable descriptions

---

src/transitions/transition-wp.ts

fixes the syntax of cubic-bezier easing
**Fixes**: # the syntax of cubic-bezier easing

fix(transition): syntax of cubic-bezier easing

---

src/components/nav/test/basic/app-module.ts
src/navigation/nav-controller-base.ts

See each commit for further info

Several navigation improvements

---

src/components/action-sheet/action-sheet-component.ts
src/components/alert/alert-component.ts
src/components/app/app-root.ts
src/components/app/app.ts
src/components/backdrop/backdrop.scss
src/components/backdrop/backdrop.ts
src/components/content/content.scss
src/components/item/item-sliding-gesture.ts
src/components/list/list.ts
src/components/loading/loading-component.ts
src/components/menu/menu-gestures.ts
src/components/menu/menu.ts
src/components/menu/test/basic/app-module.ts
src/components/menu/test/basic/modal.html
src/components/menu/test/basic/page1.html
src/components/modal/modal-component.ts
src/components/nav/test/basic/app-module.ts
src/components/picker/picker-component.ts
src/components/popover/popover-component.ts
src/components/refresher/refresher.ts
src/components/toolbar/toolbar-button.scss
src/gestures/gesture-controller.ts
src/gestures/test/gesture-controller.spec.ts
src/navigation/swipe-back.ts
src/platform/platform-registry.ts
src/util/mock-providers.ts

Gestures several

---

src/components/action-sheet/test/basic/app-module.ts
src/components/app/app-root.ts
src/components/nav/overlay-portal.ts
src/navigation/nav-controller-base.ts
src/navigation/nav-util.ts

1. http://localhost:8000/dist/e2e/action-sheet/basic/
2. Present Action Sheet 1
3. Press "Play"
3. Press "Play" (second time)
**Fixes**: #

fix(nav): zIndex in overlays

---

src/components/tap-click/tap-click.ts
src/platform/platform-registry.ts
src/platform/platform.ts

- improves drastically the responsiveness in WK and iOS Safari

perf(tapclick): tapPolyfill is only used in UIWebView!

---

src/themes/ionic.globals.scss

add variable for ionicons
-
-
-
**Fixes**: https://github.com/driftyco/ionic-app-scripts/issues/73

fix(fonts): change font variable

---

src/components/datetime/datetime.ts
src/components/picker/picker-component.ts
src/components/picker/picker.scss
src/components/picker/test/basic/app-module.ts

fix(picker): making touchable fill all the available space

---

src/components/button/button.ts
src/components/menu/menu-toggle.ts
src/components/menu/test/basic/app-module.ts
src/components/menu/test/basic/page1.html

fix(menu-toggle): move logic for css class to the menu toggle

---

src/components/action-sheet/test/basic/main.html
src/components/alert/alert.scss
src/components/app/app.scss
src/components/button/button.md.scss
src/components/button/button.scss
src/components/content/content.scss
src/components/fab/fab.scss
src/components/item/item.scss
src/components/loading/loading.scss
src/components/menu/menu.scss
src/components/modal/modal.scss
src/components/modal/test/basic/main.html
src/components/picker/picker.scss
src/components/toast/toast.scss
src/components/toolbar/toolbar.scss

perf(all): css containment

---

scripts/gulp/util.ts
src/components/app/app.scss
src/components/content/content.ts
src/components/tabs/tab.ts
src/components/tabs/tabs.ts
src/components/tabs/test/badges/app-module.ts
src/components/tabs/test/colors/app-module.ts
src/components/tabs/test/tab-bar-scenarios/app-module.ts
src/components/tap-click/tap-click.ts
src/util/util.ts

perf(tabs): fast switching

---

src/module.ts

Fixed a typo

---

src/components/action-sheet/test/basic/app-module.ts
src/components/alert/test/basic/app-module.ts
src/components/button/button.ios.scss
src/components/button/button.md.scss
src/components/button/button.ts
src/components/button/button.wp.scss
src/components/button/test/decorator/app-module.ts
src/components/button/test/decorator/e2e.ts
src/components/button/test/decorator/main.html
src/components/modal/test/basic/app-module.ts
src/components/toolbar/toolbar.ios.scss
src/components/toolbar/toolbar.md.scss
src/components/toolbar/toolbar.wp.scss

feat(button): emphasis decorator

---

src/components/tabs/tab.ts

I've just added a missing "/" 

Added missing "/" in closing tag

---

src/components/app/app.ts
src/components/app/test/app.spec.ts
src/components/menu/menu.ts
src/themes/ionic.globals.scss
src/themes/util.scss
src/util/click-block.ts

-
-
-
**Fixes**: #
references #9531

fix(clickblock): clickblock stays longer

---

src/components/item/test/buttons/app-module.ts
src/components/item/test/buttons/main.html
src/themes/normalize.scss

fix(item): tappable does not make ion-label pointer-event:none

---

src/components/loading/test/basic/app-module.ts
src/components/loading/test/basic/main.html
src/components/nav/overlay-portal.ts
src/components/note/note.ts
src/components/toast/test/basic/app-module.ts
src/components/toast/test/basic/main.html

Overlay dismiss fix

---

CHANGELOG.md

ionic storage 1.1.6 had an issue that caused a white screen for some users. Ionic storage 1.1.7 fixed this and this change updates our rc4 changelog to recommend updating to 1.1.7 . https://github.com/driftyco/ionic/issues/9677
- update version of ionic storage we recommend users updating too
**Fixes**: #9677

chore(changelog): recommend latest version of storage

---

src/components/avatar/avatar.ts

place to placed
- changed place to placed
-
-
**Fixes**: #

small typo

---

src/navigation/nav-controller-base.ts
src/navigation/view-controller.ts

Fix typos in comments for NavControllerBase and ViewController

---

src/components/slides/slides.ts
src/components/slides/test/options/app-module.ts
src/components/slides/test/options/main.html

Closes #9988
Exposes slidesPerView and spaceBetween. Also documents how to change
unexposed options
2.x
**Fixes**: #9988

feat(slides): expose more options

---

src/components/slides/slides.ts
src/components/slides/swiper/swiper-controller.ts
src/components/slides/swiper/swiper-events.ts
src/components/slides/swiper/swiper-transition.ts
src/components/slides/swiper/swiper.ts
src/components/slides/test/control/app-module.ts
src/components/slides/test/control/main.html

Adds functionality to Slides that was lost in the porting.
- Adds Swiper's Controller, which can be used to have one Swiper control another. (Ported from https://github.com/nolimits4web/Swiper/blob/master/src/js/controller.js)
**Ionic Version**: 2.0.0-rc.5
**Related**: #9933

feat(slides): swiper controller

---

demos/src/config/app.module.ts

Config demo was not updating when settings were saved.  
- Move the setting of config from the ApiDemoPage to ApiDemoApp
- Add injectable Config to ApiDemoPage and sett `this.config=config.settings()`
2.x
**Fixes**: #
#9413

fix(demos/config) fix for config page not updating. #9413

---

src/components/app/app.ts

- docs lifecycle events in App
- moar docs
-
-

docs(app): doc app-level lifecycle events

---

src/components/alert/alert.scss
src/components/input/input.scss

feat(input): add variables for alert and input placeholder color

---

src/components/input/input.ts

Typo
- Remove typo
**Fixes**: #

Removed typo

---

src/components/datetime/test/issues/app.module.ts
src/components/datetime/test/issues/main.html
src/components/split-pane/split-pane.ios.scss
src/components/split-pane/split-pane.md.scss
src/components/split-pane/split-pane.scss
src/components/split-pane/split-pane.wp.scss
src/components/split-pane/test/menus/app.module.ts
src/components/split-pane/test/menus/main.html
src/components/split-pane/test/tabs/app.module.ts
src/components/split-pane/test/tabs/main.html
src/components/tabs/tabs.ts

feat(split-pane): support for side=right

---

src/platform/platform.ts

There was an extra word posing a grammatical issue in the doc. 
Removed the word "its"
-
-
-
**Fixes**: #

Removed an extra word

---

src/navigation/nav-controller.ts

Update nav-controller.ts - typo.

---

src/components/app/app.scss

add pull-left/right/start/end
- `pull-left` = `float: left`
- `pull-right` = `float: right`
- `pull-start` = `float: (dir==ltr)? left: right`
- `pull-end` = `float: (dir==ltr)? right: left`

feat(rtl): add pull-left/right/start/end

---

src/components/app/app.scss

add text-start and text-end
- add text-start and text-end

feat(rtl): add text-start and text-end

---

src/components/segment/segment.ios.scss

add segment rtl support
Fixes:

fix(rtl): add segment rtl support

---

src/components/app/app.scss
src/components/app/test/utilities/app/app.component.ts
src/components/app/test/utilities/app/app.module.ts
src/components/app/test/utilities/app/main.ts
src/components/app/test/utilities/pages/root-page/root-page.html
src/components/app/test/utilities/pages/root-page/root-page.ts
src/components/grid/grid.mixins.scss
src/themes/ionic.mixins.scss

Adds responsive attributes for text alignment, transforms, and float.
- moves breakpoint mixins to the ionic.mixins file
- adds responsive attributes for text alignment, transform, and
floating elements
- adds ability to turn these off so they don’t get added to the css
file using sass variables
**Fixes**: #10567

feat(app): add responsive utility attributes

---

scripts/gulp/tasks/test.ts
scripts/karma/system.config.js
src/animations/animation.ts
src/components/app/test/app.spec.ts
src/components/nav/test/basic/pages/first-page/first-page.html
src/components/nav/test/nav.spec.ts
src/components/tabs/tab.ts
src/components/tabs/test/tabs.spec.ts
src/navigation/nav-controller-base.ts
src/navigation/nav-util.ts
src/navigation/test/deep-linker.spec.ts
src/navigation/test/nav-controller.spec.ts
src/navigation/test/overlay-proxy.spec.ts
src/navigation/view-controller.ts
src/transitions/transition-controller.ts
src/transitions/transition.ts
src/util/test/module-loader.spec.ts

fix(navcontroller): lazy loading is queued (WIP)

---

src/components/label/label.ios.scss
src/components/label/label.md.scss
src/components/label/label.wp.scss

Add RTL support to Floating labels
RTL support for floating labels
- added a scss code which set transform-origin to right for RTL direction on html.

floating label rtl fix

---

src/components/list/list.ios.scss
src/components/list/list.md.scss
src/components/list/list.wp.scss

RTL fix (scss changes) for list-header for wp, ios and android platform
- Add RTL rule for list-header
**Fixes**: #11211

fix(list-header): RTL fix for list-header

---

src/tap-click/haptic.ts

doc(haptic): fix typo

---

package.json
scripts/gulp/util.ts

chore(e2e): adds bonjour support

---

package.json

update to latest zone.js for faster start-up
-
-
-
**Fixes**: #

chore(dependencies): update to latest zone.js for faster start-up

---

README.md

- changed http links to https
- renamed Ionic 1.x to Ionic V1

docs(readme): http --> https + Ionic 1.x --> Ionic V1

---

.github/ISSUE_TEMPLATE.md

docs(issue): Ionic V1

---

src/navigation/nav-params.ts

Aligning the code sample to match the generated code from the CLI’s
page generator.

Updating variable naming

---

src/components/checkbox/checkbox.ts

- Add an example for how to do a function call when checkbox changed.
**Fixes**: #

docs(example): add advanced example

---

package.json

chore(package): Latest Angular release

---

src/components/menu/menu.ts

- fix https://github.com/driftyco/ionic-site/issues/1080

docs(Menu): fix link

---

src/components/segment/segment.ts

The `Segment` docs do not show a clear example on how to use the `ionChange` event.
Updated the example.

docs(segment): add usage for ionChange event

---

src/components/slides/swiper/swiper.ts

Better testability.
- add null check to prevent null dereference while testing with karma
**Fixes**: #11185

add null check for better testability

---

src/components/virtual-scroll/virtual-scroll.ts

fix(lint): remove unused import

---

src/components/toggle/toggle.ts

docs(api-tabs): renamed Angular 2 to Angular

---

src/components/tabs/tab.ts

docs(api-tabs): improved typo

---

src/components/slides/slides.ts

docs(api-slides): improve typo

---

src/platform/platform.ts

docs(api-platform): improve typo

---

src/navigation/nav-controller.ts

docs(api-navctrl): improve typo

---

src/components/checkbox/checkbox.ts

docs(api-checkbox): renamed Angular 2 to Angular

---

src/util/util.ts

Is this supposed to be hidden?

docs(): hide normalizeURL

---

src/components/chip/chip.ts

docs(api-checkbox): improve typo

---

.scss-lint.yml
src/components/input/input.scss
src/components/item/item.ios.scss
src/components/item/item.md.scss
src/components/item/item.wp.scss
src/components/searchbar/searchbar.ios.scss
src/components/searchbar/searchbar.md.scss
src/components/searchbar/searchbar.wp.scss
src/components/slides/slides.scss
src/components/toolbar/toolbar.md.scss
src/themes/ionic.mixins.scss

Bad background position on rtl

feat(background-position): add background position support for rtl

---

src/components/picker/picker.scss

fix(datetime): same on ltr and rtl

---

src/components/item/item.ios.scss
src/components/item/item.md.scss
src/components/item/item.wp.scss
src/components/searchbar/searchbar.ios.scss
src/components/searchbar/searchbar.md.scss
src/components/searchbar/searchbar.wp.scss
src/themes/ionic.functions.scss
src/themes/ionic.mixins.scss

Duplicate svg images for no reason
-
-
-
**Fixes**: #

feat(svg-background-image): support flipped on rtl

---

src/components/input/input.ts

fix(input): prevent duplicated tabIndex

---

CHANGELOG.md

CHANGELOG.md edit to update the app-scripts update cmd with `--save-dev` instead of `--save`

App-scripts cmd updated

---

src/components/tabs/tabs.ts

fix(navigation): handle null reference

---

src/config/config.ts

Add parameter for hiding extra padding when statusbar is hidden.
It adds a missing config param to complete the list.
- added param statusbarPadding including description
-
-
**Fixes**: #

docs(config): add statusbarpadding to config.ts

---

src/components/nav/nav-push.ts

same order as in constructor and per importance

docs(nav-push): Change property order

---

src/components/virtual-scroll/virtual-scroll.ts

fix minor grammar

---

src/components/modal/modal-controller.ts

docs(modal-controller): cosmetics

---

src/components/loading/loading-controller.ts

docs(toast-controller): cosmetics

---

src/util/events.ts

docs(events): cosmetics

---

src/components/alert/alert-controller.ts

- public dependency injection
- change let to const

docs(alert-controller): cosmetics

---

src/components/action-sheet/action-sheet-controller.ts

docs(action-sheet-controller): cosmetics

---

src/navigation/nav-params.ts

docs(nav-params): cosmetics

---

.github/ISSUE_TEMPLATE.md
package-lock.json
package.json
scripts/gulp/tasks/release.ts
src/components/action-sheet/action-sheet-controller.ts
src/components/action-sheet/action-sheet.ios.scss
src/components/alert/alert-controller.ts
src/components/content/content.scss
src/components/content/content.ts
src/components/item/item.ios.scss
src/components/loading/loading-controller.ts
src/components/modal/modal-controller.ts
src/components/picker/picker.scss
src/components/slides/slides.ts
src/components/tabs/tabs.ios.scss
src/components/toast/toast-controller.ts
src/components/toast/toast.ios.scss
src/navigation/nav-params.ts
src/platform/cordova.ios.scss
src/platform/cordova.md.scss
src/platform/cordova.scss
src/platform/cordova.wp.scss
src/platform/keyboard.ts
src/tap-click/haptic.ts
src/themes/ionic.mixins.scss
src/util/events.ts
src/util/ionic-error-handler.ts
tsconfig.json

Mostly adjustments around iOS11 and iPhoneX

WIP: iOS 11 adjustments

---

src/components/action-sheet/action-sheet.ios.scss
src/components/app/app-root.ts
src/components/content/content.scss
src/components/fab/fab.scss
src/components/item/item-reorder.scss
src/components/item/item-sliding.scss
src/components/item/item.ios.scss
src/components/list/list.ios.scss
src/components/picker/picker.scss
src/components/popover/popover-transitions.ts
src/components/popover/popover.ios.scss
src/components/toast/toast.ios.scss
src/components/toolbar/toolbar.ios.scss
src/platform/cordova.scss
src/themes/ionic.mixins.scss
src/util/module-loader.ts

feat(): better ios11 support

---

src/components/slides/test/images/app.module.ts

Update the Image test to the new HttpClient
3

refactor(slider-test): HttpClient

---

scripts/templates/provider/ts.tmpl

Update the default http import to the new HttpClient
3

refactor(provider-template): HttpClient

---

packages/angular/demo/.angular-cli.json
packages/angular/demo/README.md
packages/angular/demo/package-lock.json
packages/angular/demo/package.json

Allows for pulling @ionic/core either from NPM or using local build via `npm link`

chore(angluar/demo): use packaged @ionic/core

---

packages/angular/demo/src/app/alert/alert-page.component.ts
packages/angular/package-lock.json
packages/angular/src/providers/alert-controller.ts
packages/core/src/components.d.ts
packages/core/src/components/alert/alert.tsx
packages/core/src/index.d.ts
packages/core/src/utils/helpers.ts
packages/core/src/utils/overlay-constants.ts

Alert refactor

---

package-lock.json
package.json
src/components/alert/alert-component.ts
src/components/alert/alert-controller.ts

Fixes: #13488
Allows any input type to be disabled, not just checkbox or radio button.
**Fixes**: #13488

fix(alert): allow disabled text input

---

packages/core/src/components/popover-controller/popover-controller.tsx
packages/core/src/components/popover-controller/readme.md
packages/core/src/components/popover/animations/ios.enter.ts
packages/core/src/components/popover/animations/md.enter.ts
packages/core/src/components/popover/popover.tsx
packages/core/src/components/popover/test/basic/index.html

chore(): refactor popover animation

---

packages/core/package.json
packages/core/src/components/app/test/cordova/e2e.js
packages/core/src/components/app/test/cordova/index.html

Hellenium2

---

src/navigation/ionic-page.ts

Fix typo in navigation/ionic-page.ts#234
**Fixes**:

docs(ionic-page): fix typo on line 234

---

src/components/menu/menu.ts

Changed the wording of a sentence to use the proper tense of a word.
- Grammar fixes
-
-
**Fixes**: #

Fixed grammar of sentence

---

packages/angular/package-lock.json
packages/angular/package.json
packages/angular/src/router/outlet.ts
packages/angular/src/router/route-event-handler.ts
packages/angular/src/util/util.ts
packages/core/src/components.d.ts
packages/core/src/components/external-router-controller/external-router-controller.ts
packages/core/src/components/external-router-controller/readme.md
packages/core/src/components/tab/tab.tsx
packages/core/src/components/tabs/tabs.tsx
packages/core/src/utils/helpers.ts

External router controller

---

packages/core/src/components.d.ts
packages/core/src/components/back-button/back-button.ios.scss
packages/core/src/components/back-button/back-button.ios.vars.scss
packages/core/src/components/back-button/back-button.md.scss
packages/core/src/components/back-button/back-button.md.vars.scss
packages/core/src/components/back-button/back-button.scss
packages/core/src/components/back-button/back-button.tsx
packages/core/src/components/back-button/readme.md
packages/core/src/components/back-button/test/basic/index.html
packages/core/src/components/back-button/test/host-element/index.html
packages/core/src/components/back-button/test/standalone/index.html
packages/core/src/components/nav/nav.tsx
packages/core/src/components/nav/test/basic/index.html
packages/core/src/components/toolbar/toolbar.ios.scss
packages/core/src/components/toolbar/toolbar.md.scss

Core back button improvements3

---

CHANGELOG.md

Fix rxjs deep import example in CHANGELOG.md.
**Fixes**:

docs(changelog): fix rxjs deep import example

---

scripts/templates/page/html.tmpl

Proposed new template without extra lines

---

CHANGELOG.md
scripts/README.md
scripts/npm/README.md

URLs updated to use HTTPS protocol where appropriate to improve security and privacy.
-
-
-
**Fixes**: #13711

Update: HTTP -> HTTPS

---

src/components/modal/modal-controller.ts

Adds documentation to ModalController detailing `onWillDismiss`
- onWillDismiss was never mentioned in documentation but can be very useful for displaying content before animation occurs. Updated to include an example of onWillDismiss.
- Added comments above both onDidDismiss and OnWillDismiss to further explain how they work.
**Fixes**: #

Include an example demonstrating onWillDismiss

---

core/src/themes/ionic.mixins.scss

https://github.com/ionic-team/ionic/pull/12143

perf(scss): optimize multi dir

---

.github/PULL_REQUEST_TEMPLATE.md

add PR template v4.
**Ionic Version**: 4.0

add PR template Ionic Version v4.x

---

angular/test/nav/src/app/form-sample-page/form-sample-page.component.html
core/package-lock.json
core/src/components.d.ts
core/src/components/datetime/test/basic/index.html
core/src/components/datetime/test/preview/index.html
core/src/components/input/test/attributes/index.html
core/src/components/input/test/basic/index.html
core/src/components/input/test/preview/index.html
core/src/components/item/test/inputs/index.html
core/src/components/label/label.ios.scss
core/src/components/label/label.md.scss
core/src/components/label/label.scss
core/src/components/label/label.tsx
core/src/components/label/readme.md
core/src/components/label/test/basic/index.html
core/src/components/label/test/preview/index.html
core/src/components/label/test/standalone/index.html
core/src/components/list/test/inset/index.html
core/src/components/select/test/basic/index.html
core/src/components/select/test/multiple-value/index.html
core/src/components/select/test/single-value/index.html
core/src/components/textarea/readme.md

fix(label): using prop for position

---

angular/package-lock.json
angular/src/module.ts
angular/src/providers/config.ts
angular/src/providers/index.ts

Modifies the config provider to not break during AOT builds
-
-
-
**Fixes**: #

fix(angular): setup config provider correctly

---

core/src/components/datetime/datetime.tsx
core/src/components/input/input.tsx
core/src/components/item-divider/item-divider.md.scss
core/src/components/item/item.md.scss
core/src/components/label/label.ios.scss
core/src/components/label/label.md.scss
core/src/components/list/list.md.scss
core/src/components/select/select.tsx
core/src/components/select/test/single-value/index.html
core/src/components/textarea/textarea.tsx

fix(inputs): interactive rule to rule them all

---

core/src/components/slides/slides-vendor.scss
core/src/components/slides/slides.tsx
core/src/components/slides/test/basic/index.html
core/src/components/slides/vendor/swiper.d.ts
core/src/components/slides/vendor/swiper.js

This bumps the vendor bundle of swiper to the latest release
**Fixes**: #14505

feat(slides): update swiper to latest

---

core/src/components/alert/usage/angular.md

fix usage document in alert.
**Fixes**: #

chore(ugage): add name(attribule) in alert usage.

---

core/src/components/button/test/toolbar/index.html
core/src/components/buttons/buttons.ios.scss
core/src/components/buttons/buttons.md.scss
core/src/components/toolbar/toolbar.ios.vars.scss
core/src/components/toolbar/toolbar.md.vars.scss

fix(button): do not change border radius if round button in toolbar

---

core/src/components/menu/menu.scss

Allow the menu width to be modified using css variables.
- add --width css variable to menu
- add --small-width css variable to menu
**Ionic Version**: 4.0.0-beta.1

fix(menu): add width and small-width css variables

---

core/src/components/app/app.tsx
core/src/utils/platform.ts

Adds check for standalone mode 
resolves #15000

feat(core): add check for standalone mode

---

core/src/components/router/test/preview/index.html

Fixes small typo on beta docs
Changing pahe to path

Typo on ion-router

---

angular/src/directives/navigation/ion-router-outlet.ts
angular/src/directives/navigation/router-controller.ts
angular/src/directives/proxies.ts
angular/src/providers/nav-controller.ts
angular/test/testapp/src/app/popover/popover-page.component.ts
angular/test/testapp/src/app/simple-nav/simple-nav.component.ts

fix(angular): back navigation and back-button play better

---

core/src/components/button/usage/angular.md

Fix the ion-button usage documentation.
- ion-button usage docs update
**Fixes**: #

fix(docs): use shape property to get round buttons

---

angular/src/providers/platform.ts

docs(platform): respect PLATFORMS_MAP from core

---

src/components/segment/segment.ts

Added an example of the `mode` attribute on an `ion-segment`.

Added an example of the mode attribute

---

core/src/components/popover/usage/angular.md
core/src/components/popover/usage/javascript.md

Fix variable undefined errors

---

core/src/components/alert/readme.md

small typo with extra speechmark
-
-
-
**Fixes**: #

typo with extra speechmark

---

core/src/utils/haptic.ts

Add stronger typing with tuples
- Add hapticNotification type types
- Add hapticImpact type types
4

refactor(haptic): add tuple types

---

core/package.json

chore(): update stencil

---

angular/src/directives/proxies-list.txt
angular/src/directives/proxies.ts
angular/src/ionic-module.ts
core/src/components/tabbar/readme.md
core/src/components/tabs/readme.md
core/stencil.config.ts

fix(angular): generate proxies for ion-tabbar

---

core/src/components/radio/radio.md.scss
core/src/components/radio/radio.md.vars.scss

This updates the sizing and proportions of our radio input to match the updated Material Design spec.

fix(radio): match MD sizing

---

core/src/components/note/note.md.scss
core/src/components/note/note.md.vars.scss

Updates the font-size of note for MD per spec

fix(note): update note font size for MD

---

core/src/components/popover/popover.md.vars.scss

Updates the box-shadow of the popover to match the MD spec.

fix(popover): update the box shadow to match MD spec

---

angular/BREAKING.md

docs(breaking): update colors to core css

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/ionic-issue-bot.yml
README.md

These should be the necessary changes to move v3 source code & issues to the new home for Ionic 3: https://github.com/ionic-team/ionic-v3

chore: v3 move

---

core/src/components/checkbox/checkbox.ios.scss
core/src/components/checkbox/checkbox.md.scss
core/src/components/checkbox/checkbox.scss
core/src/components/checkbox/test/basic/index.html
core/src/components/datetime/datetime.scss
core/src/components/input/input.scss
core/src/components/range/range.scss
core/src/components/select/select.scss
core/src/components/textarea/textarea.scss
core/src/components/toggle/toggle.scss
core/src/themes/ionic.globals.scss

Fix checkbox

---

core/src/components/searchbar/searchbar.tsx

fixes #16143
-
-
-
**Fixes**: #

fix(searchbar): fix crash on cancel event

---

core/src/components/menu/menu.md.vars.scss

Updates menu box-shadow to match MD spec

fix(menu): update box-shadow for MD to match spec

---

core/src/components/alert/alert.ios.scss
core/src/components/alert/alert.md.scss
core/src/components/input/input.scss
core/src/components/searchbar/searchbar.scss
core/src/components/textarea/textarea.scss

Fix inputs edge

---

core/src/components/menu/test/basic/e2e.ts
core/src/components/menu/test/basic/index.html
core/src/components/menu/test/standalone/e2e.ts
core/src/components/menu/test/standalone/index.html

- Augments the menu component's tests to include buttons for non-automated usage
- Uses the push type for one of the menus.

test(menu): add buttons and test push type

---

core/src/components/action-sheet/action-sheet.scss
core/src/components/action-sheet/readme.md

docs(action-sheet): document custom properties

---

core/src/components/alert/alert.scss
core/src/components/alert/readme.md

docs(alert): document custom properties

---

core/src/components/searchbar/searchbar.md.scss
core/src/components/searchbar/searchbar.md.vars.scss

fix(searchbar): align cancel button to center with search icon position

---

core/src/components/list-header/list-header.md.scss
core/src/components/list-header/list-header.md.vars.scss

fix(list-header): match MD bottom margin, match MD text color

---

core/src/components/checkbox/checkbox.ios.vars.scss
core/src/components/checkbox/checkbox.md.vars.scss
core/src/components/checkbox/checkbox.scss

fix(checkbox): align vertically

---

core/src/components/tab-button/tab-button.tsx

fix(tab-button): layout is mutable

---

core/src/components.d.ts
core/src/components/action-sheet/action-sheet.md.scss
core/src/components/action-sheet/action-sheet.tsx
core/src/components/alert/alert.md.scss
core/src/components/alert/alert.tsx
core/src/components/button/button.ios.scss
core/src/components/button/button.md.scss
core/src/components/button/button.scss
core/src/components/fab-button/fab-button.md.scss
core/src/components/item/item.md.scss
core/src/components/ripple-effect/readme.md
core/src/components/ripple-effect/ripple-effect.scss
core/src/components/ripple-effect/ripple-effect.tsx
core/src/utils/tap-click.ts

fix(ripple-effect): follow MD spec

---

angular/src/directives/control-value-accessors/boolean-value-accessor.ts
angular/src/directives/control-value-accessors/value-accessor.ts
core/src/components/menu-controller/menu-controller.ts

Fix angular 

---

angular/src/directives/navigation/ion-router-outlet.ts
angular/src/directives/navigation/stack-controller.ts

fixes #16390
-
-
-
**Fixes**: #

fix(angular): fix tabs with useHash

---

core/package.json
core/src/components/app/app.tsx
core/src/components/ripple-effect/ripple-effect.tsx
core/src/utils/config.ts
core/src/utils/tap-click.ts

fixes #16379
-
-
-
**Fixes**: #

feat(ripple-effect): add option to disable ripple-effect

---

angular/src/directives/proxies.ts
core/api.txt
core/package.json
core/src/components.d.ts
core/src/components/button/button.scss
core/src/components/button/button.tsx
core/src/components/buttons/buttons.scss
core/src/components/ripple-effect/readme.md
core/src/components/ripple-effect/ripple-effect.scss
core/src/components/ripple-effect/ripple-effect.tsx
core/src/components/tab-button/readme.md
core/src/components/tab-button/tab-button.scss
core/src/components/tab-button/tab-button.tsx

feat(ripple): adds unbounded ripple-effect

---

core/api.txt
core/scripts/api-spec-generator.js

chore(): rename style to css-prop

---

angular/src/providers/platform.ts

fixes #15979
-
-
-
**Fixes**: #

fix(angular): es6 classes break in ie11

---

angular/README.md

docs(): add ng-add testing docs to readme

---

.circleci/config.yml
angular/src/directives/navigation/tab-delegate.ts
angular/test/test-app/e2e/src/inputs.e2e-spec.ts
angular/test/test-app/e2e/tsconfig.e2e.json
angular/test/test-app/package.json
angular/test/test-app/src/app/app-routing.module.ts
angular/test/test-app/src/app/app.module.ts
angular/test/test-app/src/app/home-page/home-page.component.html
angular/test/test-app/src/app/home-page/home-page.component.ts
angular/test/test-app/src/app/inputs/inputs.component.ts
angular/test/test-app/src/app/tabs/tabs.component.html
angular/test/test-app/src/app/tabs/tabs.component.ts
angular/test/test-app/src/tsconfig.app.json
angular/tsconfig.json
core/stencil.config.ts

test(angular): add CI

---

angular/src/directives/navigation/href-delegate.ts
angular/src/providers/nav-controller.ts
angular/test/test-app/e2e/src/router-link.e2e-spec.ts
angular/test/test-app/scripts/build-ionic.sh
core/src/utils/theme.ts

fix(angular): no animate in browser nav

---

core/src/components/segment-button/segment-button.scss
core/src/components/segment/segment.scss
core/src/components/segment/test/bug/index.html

Fix weird segment sizing

---

.circleci/config.yml
angular/package.json
angular/src/directives/navigation/href-delegate.ts
angular/src/directives/navigation/stack-controller.ts
angular/test/test-app/angular.json
angular/test/test-app/e2e/src/inputs.e2e-spec.ts
angular/test/test-app/e2e/src/modal.e2e-spec.ts
angular/test/test-app/e2e/src/router-link.e2e-spec.ts
angular/test/test-app/e2e/src/utils.ts
angular/test/test-app/package.json
angular/test/test-app/src/app/modal-example/modal-example.component.html
angular/test/test-app/src/app/modal-example/modal-example.component.ts
angular/test/test-app/src/app/router-link-page/router-link-page.component.html
angular/test/test-app/src/app/router-link-page/router-link-page.component.ts
angular/test/test-app/src/app/router-link/router-link.component.html
angular/test/test-app/src/app/router-link/router-link.component.ts
angular/test/test-app/src/app/tabs/tabs.component.ts
core/package.json
core/src/components/anchor/anchor.tsx
core/src/components/back-button/back-button.tsx
core/src/components/datetime/datetime-util.spec.ts
core/src/components/datetime/datetime-util.ts
core/src/components/datetime/datetime.tsx
core/src/components/fab-button/fab-button.tsx
core/src/components/item/item.tsx
core/src/components/picker-column/picker-column.tsx

Fix angular link 2

---

core/src/components/select-option/select-option.tsx
core/src/components/select/select.scss
core/src/css/core.scss

fixes #16580
-
-
-
**Fixes**: #

fix(select): selection-option is hidden in edge

---

core/api.txt
core/src/components/button/button.scss
core/src/components/modal/modal.ios.scss
core/src/components/modal/modal.md.scss
core/src/components/modal/modal.scss
core/src/components/modal/modal.tsx
core/src/components/modal/readme.md
core/src/components/modal/test/basic/index.html
core/src/components/modal/test/custom/e2e.ts
core/src/components/modal/test/custom/index.html
core/src/components/modal/test/standalone/index.html

feat(modal): add css vars

---

core/src/components/select-option/select-option.scss
core/src/components/select-option/select-option.tsx
core/src/themes/ionic.theme.default.ios.scss
core/src/themes/ionic.theme.default.md.scss

 feat(theme): default colors based in step colors

---

core/package.json
core/src/components.d.ts
core/src/components/nav/constants.ts
core/src/components/nav/nav-interface.ts
core/src/components/nav/nav.tsx
core/src/components/nav/test/nav-controller.spec.ts
core/src/components/nav/view-controller.ts
core/src/components/router-outlet/route-outlet.tsx
core/src/components/router/router.tsx
core/src/components/router/test/path.spec.tsx
core/src/components/router/utils/constants.ts
core/src/components/router/utils/dom.ts
core/src/components/router/utils/interface.ts
core/src/components/router/utils/path.ts
core/src/components/tabs/tabs.tsx
core/src/components/virtual-scroll/constants.ts
core/src/components/virtual-scroll/test/virtual-scroll-utils.spec.ts
core/src/components/virtual-scroll/virtual-scroll-interface.ts
core/src/components/virtual-scroll/virtual-scroll-utils.ts
core/src/components/virtual-scroll/virtual-scroll.tsx
core/src/index.ts
core/src/interface.d.ts
core/src/utils/transition.ts
core/tslint.json

fixes #16497
-
-
-
**Fixes**: #

refactor(all): avoid using export const enum

---

.circleci/config.yml
angular/src/providers/angular-delegate.ts
angular/src/providers/platform.ts
angular/src/util/util.ts

Fix some angular

---

angular/package.json
angular/src/directives/navigation/ion-back-button.ts
angular/src/directives/navigation/router-link-delegate.ts
angular/src/providers/nav-controller.ts
angular/test/test-app/e2e/src/tabs.e2e-spec.ts
angular/test/test-app/src/app/app-routing.module.ts
angular/test/test-app/src/app/tabs-lazy/tabs-lazy-routing.module.ts
angular/test/test-app/src/app/tabs-lazy/tabs-lazy.module.ts
angular/test/test-app/src/app/tabs-lazy/tabs-tab3/tabs-tab3.component.html
angular/test/test-app/src/app/tabs-lazy/tabs-tab3/tabs-tab3.component.ts
angular/test/test-app/src/app/tabs/tabs.component.html

Angular improvements

---

angular/tsconfig.json

chore(angular): use tslib

---

core/src/components/tab-bar/tab-bar.tsx

fixes #16419
-
-
-
**Fixes**: #

fix(tab-bar): hide on keyboard events

---

angular/test/test-app/e2e/src/tabs.e2e-spec.ts
angular/test/test-app/src/app/tabs-lazy/tabs-lazy-routing.module.ts
angular/test/test-app/src/app/tabs-lazy/tabs-lazy.module.ts
angular/test/test-app/src/app/tabs-lazy/tabs-tab3-nested/tabs-tab3-nested.component.html
angular/test/test-app/src/app/tabs-lazy/tabs-tab3-nested/tabs-tab3-nested.component.ts
angular/test/test-app/src/app/tabs-tab1/tabs-tab1.component.html

test(angular): lazy loading tabs

---

angular/src/directives/proxies.ts
core/api.txt
core/src/components.d.ts
core/src/components/item-divider/item-divider.scss
core/src/components/item-divider/item-divider.tsx
core/src/components/item-divider/readme.md

fix(item-divider): use prop for sticky

---

angular/BREAKING.md
core/src/components/tab-bar/readme.md
core/src/components/tab-bar/usage/angular.md
core/src/components/tab-button/readme.md
core/src/components/tab-button/usage/angular.md
core/src/components/tabs/readme.md

Fixes the docs after the latest refactor of tabs on Angular side
**Fixes**: #

docs(tabs): add changes after refactor

---

angular/src/directives/navigation/ion-router-outlet.ts
angular/src/directives/navigation/stack-controller.ts
angular/test/test-app/src/app/home-page/home-page.component.html
core/src/components/item/item.scss

fix(angular): swipe to go backs in tabs

---

angular/src/directives/navigation/ion-tabs.ts
angular/test/test-app/package-lock.json
angular/test/test-app/package.json

fixes #16722
-
-
-
**Fixes**: #

fix(angular): tab-bar slot=top

---

angular/src/directives/virtual-scroll/virtual-scroll.ts
angular/test/test-app/src/app/app-routing.module.ts
angular/test/test-app/src/app/app.module.ts
angular/test/test-app/src/app/home-page/home-page.component.html
angular/test/test-app/src/app/virtual-scroll-detail/virtual-scroll-detail.component.html
angular/test/test-app/src/app/virtual-scroll-detail/virtual-scroll-detail.component.ts
angular/test/test-app/src/app/virtual-scroll-inner/virtual-scroll-inner.component.html
angular/test/test-app/src/app/virtual-scroll-inner/virtual-scroll-inner.component.ts
angular/test/test-app/src/app/virtual-scroll/virtual-scroll.component.html
angular/test/test-app/src/app/virtual-scroll/virtual-scroll.component.ts

fixes #16725
fixes #16432
fixes #16023
fixes #14591
fixes #16050
fixes #15587
-
-
-
**Fixes**: #

fix(angular): virtual-scroll

---

core/src/components/datetime/datetime.tsx
core/src/components/select/select.tsx

fixes #16717
-
-
-
**Fixes**: #

fix(datetime): picker inherits mode

---

core/src/components/item/item.md.scss
core/src/components/item/item.md.vars.scss
core/src/components/label/label.md.vars.scss
core/src/components/list/test/icons/e2e.ts
core/src/components/list/test/icons/index.html

fixes #16643
| `Material Design` | `Ionic` |
| ------------------| --------|
| <img width="363" alt="screen shot 2018-12-14 at 5 06 00 pm" src="https://user-images.githubusercontent.com/6577830/50030849-91397400-ffc2-11e8-8bfe-040a786ec5cc.png"> | <img width="364" alt="screen shot 2018-12-14 at 5 05 25 pm" src="https://user-images.githubusercontent.com/6577830/50030475-7bc44a00-ffc2-11e8-8e34-ab45bdea2551.png"> |

fix(list): adjust label margin to align with the spec for md

---

core/src/components/nav/test/basic/index.html
core/src/components/progress-bar/test/basic/index.html
core/src/components/toolbar/toolbar.scss
core/src/css/core.scss
core/src/index.ts
core/src/themes/ionic.theme.default.md.scss
core/src/themes/test/css-variables/css/dark.css
core/src/themes/test/css-variables/index.html

fix(body): body background matches ion-content

---

angular/src/directives/navigation/ion-router-outlet.ts
angular/src/directives/navigation/stack-controller.ts
angular/test/test-app/e2e/src/nested-outlet.e2e-spec.ts
angular/test/test-app/e2e/src/utils.ts
angular/test/test-app/src/app/app-routing.module.ts
angular/test/test-app/src/app/app.module.ts
angular/test/test-app/src/app/home-page/home-page.component.html
angular/test/test-app/src/app/nested-outlet-page/nested-outlet-page.component.html
angular/test/test-app/src/app/nested-outlet-page/nested-outlet-page.component.ts
angular/test/test-app/src/app/nested-outlet-page2/nested-outlet-page2.component.html
angular/test/test-app/src/app/nested-outlet-page2/nested-outlet-page2.component.ts
angular/test/test-app/src/app/nested-outlet/nested-outlet.component.html
angular/test/test-app/src/app/nested-outlet/nested-outlet.component.ts
angular/test/test-app/src/app/tabs-tab1/tabs-tab1.component.html

fixes #16411
-
-
-
**Fixes**: #

fix(angular): fix sibling router-outlets

---

core/src/components/tab-bar/tab-bar.scss
core/src/components/tab-bar/test/scenarios/index.html

Fixes the selected color if tab bar is using a custom color
**Fixes**: #16761

fix(tab-bar): adds selected color if tab bar is using a color - Fixes #16761

---

core/package.json

fixes #16781
-
-
-
**Fixes**: #

chore(): update ionicons

---

angular/test/test-app/e2e/src/modal.e2e-spec.ts
angular/test/test-app/src/app/app.module.ts
angular/test/test-app/src/app/modal-example/modal-example.component.html
angular/test/test-app/src/app/modal-example/modal-example.component.ts
angular/test/test-app/src/app/modal/modal.component.html
angular/test/test-app/src/app/modal/modal.component.ts
angular/test/test-app/src/app/nav/nav.component.html
angular/test/test-app/src/app/nav/nav.component.ts
core/src/components/modal/readme.md
core/src/components/modal/usage/angular.md
core/src/components/modal/usage/javascript.md

test(angular): add e2e tests for ion-nav

---

angular/src/directives/navigation/ion-tabs.ts
angular/src/directives/navigation/router-link-delegate.ts
angular/src/directives/navigation/stack-controller.ts
angular/src/providers/nav-controller.ts

feat(angular): expose animationDirection

---

angular/src/directives/navigation/ion-router-outlet.ts
angular/src/directives/navigation/stack-controller.ts
angular/src/directives/navigation/stack-utils.ts
angular/src/providers/angular-delegate.ts
angular/test/test-app/e2e/src/router-link.e2e-spec.ts

fixes #16285
-
-
-
**Fixes**: #

fix(angular): router-outlet memory leak

---

core/src/components/nav/nav-interface.ts

fix(core): ts lint issue

---

CHANGELOG.md

docs(CHANGELOG): fix typo

---

react/README.md

docs(react): remove ion-animation from the list of components.

---

react/package.json

Updated dependency on np and updated ionic/core dependency to rc.

React dependencies

---

README.md
react/package.json

chore(react): update version after release.

---

angular/src/directives/proxies.ts
angular/src/directives/virtual-scroll/virtual-scroll.ts
angular/src/providers/platform.ts
angular/src/util/overlay.ts
angular/src/util/util.ts
core/package.json

perf(angular): proxy fast properties

---

core/api.txt
core/src/components.d.ts
core/src/components/action-sheet/action-sheet.scss
core/src/components/action-sheet/action-sheet.tsx
core/src/components/action-sheet/readme.md
core/src/components/alert/alert.scss
core/src/components/alert/alert.tsx
core/src/components/alert/readme.md
core/src/components/loading/loading.scss
core/src/components/loading/loading.tsx
core/src/components/loading/readme.md
core/src/components/menu-button/menu-button.scss
core/src/components/modal/modal.scss
core/src/components/modal/modal.tsx
core/src/components/modal/readme.md
core/src/components/picker/picker.scss
core/src/components/picker/picker.tsx
core/src/components/picker/readme.md
core/src/components/popover/popover.scss
core/src/components/popover/popover.tsx
core/src/components/popover/readme.md
core/src/components/toast/readme.md
core/src/components/toast/toast.scss
core/src/components/toast/toast.tsx
core/src/utils/overlays.ts

fixes #16685
-
-
-
**Fixes**: #

fix(overlays): make them hidden until presented

---

angular/src/directives/proxies.ts
core/api.txt
core/src/components.d.ts
core/src/components/tab-button/readme.md
core/src/components/tab-button/tab-button.tsx
core/src/components/tab/tab.tsx

fixes #16845
-
-
-
**Fixes**: #

fix(tab-button): allow standalone tab-button

---

angular/src/directives/navigation/ion-tabs.ts
angular/src/providers/nav-controller.ts
core/src/utils/overlays.ts

fixes #16917
-
-
-
**Fixes**: #

fix(tabs): fix goto root

---

core/src/components/ripple-effect/ripple-effect.scss
core/src/components/ripple-effect/test/basic/index.html

fix(ripple-effect): never capture click

---

angular/package.json

Fixed `@angular/router` dependency
Btw, wouldn't it be better to support all Angular 7 versions? 
```
"peerDependencies": {
"@angular-devkit/core": "^7.0.0",
"@angular-devkit/schematics": "^7.0.0",
"@angular/core": "^7.0.0",
"@angular/common": "^7.0.0",
"@angular/forms": "^7.0.0",
"@angular/router": "^7.0.0",
"@angular/compiler": "^7.0.0",
"@angular/compiler-cli": "^7.0.0",
"@angular/platform-browser": "^7.0.0",
"@angular/platform-browser-dynamic": "^7.0.0",
"rxjs": ">=6.2.0",
"zone.js": "^0.8.26"
},
```
And secoond I think we don't need all peerdepencies: `@angular/compiler , @angular/compiler-cli` are related to `@ionic/cli` and `zone.js, @angular/platform-browser, @angular/platform-browser-dynamic` also don't need to add as peerDep of `@ionic/angular`.
I would change it to
``` …
```

fix(angular): update @angular/router dependency #16990

---

core/src/components/item/item.tsx
core/src/components/item/test/icons/e2e.ts

fix(icon): fix rtl detail icon for ios

---

core/src/components/fab-button/fab-button.scss

fix(fab-button): add default padding for fab-button

---

core/src/components/item/test/lines/index.html
core/src/components/list/list.ios.scss
core/src/components/list/list.md.scss

:warning: Needs screenshot review :warning:
fixes #16900

fix(item): no lines on item should take precedence over list lines

---

angular/src/directives/proxies.ts
angular/test/test-app/e2e/src/slides.e2e-spec.ts
angular/test/test-app/e2e/src/view-child.e2e-spec.ts
angular/test/test-app/scripts/sync.sh
angular/test/test-app/src/app/home-page/home-page.component.html
angular/test/test-app/src/app/slides/slides.component.html
angular/test/test-app/src/app/slides/slides.component.ts
angular/test/test-app/src/app/view-child/view-child.component.html
angular/test/test-app/src/app/view-child/view-child.component.ts
core/api.txt
core/package.json
core/scripts/api-spec-generator.js

test(angular): add more ViewChild and event tests

---

angular/src/directives/navigation/ion-tabs.ts
angular/src/directives/proxies.ts
core/api.txt
core/src/components.d.ts
core/src/components/content/content.tsx
core/src/components/nav/nav.tsx
core/src/components/nav/readme.md
core/src/components/router-outlet/route-outlet.tsx
core/src/components/split-pane/readme.md
core/src/components/split-pane/split-pane.tsx
core/src/components/tabs/readme.md
core/src/components/tabs/tabs.tsx

refactor(all): remove ionChange in non-inputs

---

core/src/components/back-button/back-button.tsx

fix(rtl): fix rtl back button default

---

core/src/utils/tap-click.ts

Do not forget to remove this console log because it triggers so often ;)

fix(utils): remove console log

---

angular/src/providers/nav-controller.ts

fix(angular): hide some internal methods

---

core/src/components/content/content.scss

:warning: Needs testing and screenshot approval :warning:
Removes content layout contain to show fab on top of toolbar
Fixes #16780

fix(fab): removes content layout contain to show fab on top of toolbar

---

angular/src/providers/nav-controller.ts

fixes #17144
-
-
-
**Fixes**: #

fix(angular): navigateRoot + animated

---

angular/test/test-app/e2e/src/form.e2e-spec.ts
angular/test/test-app/src/app/form/form.component.html
angular/test/test-app/src/app/form/form.component.ts

test(angular): form tests

---

angular/src/directives/navigation/ion-router-outlet.ts
angular/src/directives/navigation/stack-controller.ts
angular/src/providers/nav-controller.ts
core/api.txt
core/src/components.d.ts
core/src/components/router/readme.md
core/src/components/router/router.tsx

fixes #16340
-
-
-
**Fixes**: #

feat(angular): add global pop()

---

core/src/components/item-sliding/item-sliding.tsx
core/src/components/menu/menu.tsx
core/src/components/nav/nav.tsx
core/src/components/picker-column/picker-column.tsx
core/src/components/range/range.tsx
core/src/components/refresher/refresher.tsx
core/src/components/reorder-group/reorder-group.tsx
core/src/components/router-outlet/route-outlet.tsx
core/src/components/toggle/toggle.tsx

fixes #16433
fixes #16974
-
-
-
**Fixes**: #

fix(gesture): destroy gesture handler when it's done

---

.scripts/release-dev.js
core/stencil.config.ts

chore(): fix release date of dev releases

---

angular/src/directives/proxies.ts
core/api.txt
core/src/components.d.ts
core/src/components/input/input.tsx
core/src/components/input/readme.md
core/src/components/searchbar/readme.md
core/src/components/searchbar/searchbar.tsx
core/src/components/textarea/readme.md
core/src/components/textarea/textarea.tsx

expose internal <input> element
fixes #17174
-
-
-
**Fixes**: #

feat(input): add getInputElement()

---

core/src/components/button/button.scss
core/src/components/fab-button/fab-button.scss

fix(button): avoid using attribute selectors for disabled

---

angular/src/directives/navigation/stack-controller.ts
angular/test/test-app/e2e/src/form.e2e-spec.ts
angular/test/test-app/e2e/src/navigation.e2e-spec.ts
angular/test/test-app/src/app/app-routing.module.ts
angular/test/test-app/src/app/app.module.ts
angular/test/test-app/src/app/navigation-page1/navigation-page1.component.html
angular/test/test-app/src/app/navigation-page1/navigation-page1.component.ts
angular/test/test-app/src/app/navigation-page2/navigation-page2.component.html
angular/test/test-app/src/app/navigation-page2/navigation-page2.component.ts
angular/test/test-app/src/app/navigation-page3/navigation-page3.component.html
angular/test/test-app/src/app/navigation-page3/navigation-page3.component.ts

WIP, finishing some automated e2e tests first
fixes #17194
fixes #16449
fixes #15413

fix(angular): race condition when fast navigation

---

angular/src/directives/proxies.ts
angular/test/test-app/src/app/navigation-page3/navigation-page3.component.ts
core/api.txt
core/src/components.d.ts
core/src/components/slides/readme.md
core/src/components/slides/slides.tsx

feat(slides): expose updateAutoHeight

---

react/package.json

React update

---

angular/scripts/rollup.config.js

Modify rollup.config.js to work with Windows
**Fixes**: #17227

fix(build): modify rollup.config.js to work with Windows

---

core/src/components/reorder-group/test/basic/index.html
core/src/components/reorder/reorder.tsx

fixes #17241
-
-
-
**Fixes**: #

fix(reorder): capture click event

---

core/src/components/modal/readme.md

just a typo fix!
- a typo fix
4.0.0+

retun -> return

---

core/src/components/searchbar/test/basic/e2e.ts
core/src/components/searchbar/test/basic/index.html

- gets focus test working properly
- adds a no cancel button focus test
this should prevent the regression in #17252 in the future

test(searchbar): update searchbar tests to take focused screenshots

---

core/src/utils/platform.ts
core/src/utils/test/platform.spec.ts

This PR adds base tests for verifying proper functionality of the base platform functions.
- Export `testUserAgent`
- Add tests for `testUserAgent()`, `getPlatforms()`, and `isPlatform()`
**Fixes**: #

test(platform): Add Platform tests

---

react/package.json

Create release of Ionic React.

ionic/react release 0.0.4

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/cli.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support_question.md

Updates the github issue templates to add one for documentation and fixes some beta links

chore(github): update issue templates

---

react/__mocks__/@ionic/core/loader/index.js
react/__mocks__/ionicons/index.js
react/jest.setup.js
react/package.json
react/src/components/IonLoading.tsx
react/src/components/IonPage.tsx
react/src/components/__tests__/IonRouterOutlet.tsx
react/src/components/__tests__/createComponent.tsx
react/src/components/__tests__/createControllerComponent.tsx
react/src/components/__tests__/createOverlayComponent.tsx
react/src/components/__tests__/utils.ts
react/src/components/createComponent.tsx
react/src/components/createControllerComponent.tsx
react/src/components/createOverlayComponent.tsx
react/src/components/index.ts
react/src/components/navigation/IonRouterOutlet.tsx
react/src/components/utils/controller-test-utils.ts
react/src/components/utils/index.ts
react/src/index.ts
react/src/register.ts
react/tsconfig.json

This pull request is to merge in changes to allow for react bindings to be tested with jest.

React tests

---

react/README.md
react/package.json

Increment the package.json and update the Readme file.

increment package.json and update readme

---

core/src/css/flex-utils.scss
core/src/css/float-elements.scss

:warning: This is important for React and Stencil Apps :warning:
fixes #17569

fix(css): add the missing css classes to flex and float utils

---

react/jest.setup.js

This pull request is to add matchMedia to jest because it is not supported by jsdom.

tests(react): Add matchMedia to jest setup.

---

core/src/components/loading/usage/vue.md

Add documentation for the `loading` component.

 docs(vue): add loading usage vue docs

---

core/src/components/action-sheet/readme.md
core/src/components/action-sheet/usage/vue.md
core/src/components/alert/readme.md
core/src/components/alert/usage/vue.md
core/src/components/loading/readme.md
core/src/components/loading/usage/vue.md
core/src/components/modal/readme.md
core/src/components/modal/usage/vue.md

Update markdown format for vue files to be html.

Fix md languages

---

react/README.md

Docs update to add capacitor info to react Readme.

docs(react): update readme to include capacitor info

---

core/src/components/item-divider/test/preview/index.html
core/src/components/item/test/basic/index.html
core/src/components/label/readme.md
core/src/components/label/usage/angular.md
core/src/components/label/usage/javascript.md
core/src/components/label/usage/react.md
core/src/components/label/usage/vue.md

closes ionic-team/ionic-docs#467

docs(label): update usage to place text-wrap on label

---

.scripts/common.js
CHANGELOG.md
angular/package.json
core/README.md
core/package.json
core/src/css/display.scss
docs/package.json

display was incorrectly using `-#{$infix}` where it should've been `#{$infix}`

fix(display): update to correct css classes

---

core/src/components.d.ts
core/src/components/datetime/datetime.tsx
core/src/components/datetime/readme.md
core/src/components/datetime/usage/angular.md

Update the usage examples of datetime for angular
Adds a more complete example to reduce confusion.

docs(): update datetime docs

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.md
angular/BREAKING.md
angular/src/schematics/add/files/root/theme/variables.css
core/src/themes/test/css-variables/css/default.css
core/src/themes/test/css-variables/css/oceanic.css
core/src/themes/test/css-variables/css/vibrant.css
docs/README.md
react/README.md

fix(): replace beta url

---

core/src/components/fab/test/test.utils.ts

Increase the fab timeout a bit for CI

test(fab): increase fab timeout

---

CHANGELOG.md
angular/package.json
core/README.md
core/package.json
docs/package.json

Release 4.2.0

---

core/src/components/modal/readme.md
core/src/components/modal/usage/angular.md

Fixes #17976 
- Fix typos
- Update Angular usage

Updating Modal component - Angular usage code

---

angular/BREAKING.md

Adds documentation in `BREAKING.md` about the new `shape` attribute on `ion-button`.
- Update the properties table
- Add old and new usage examples
**Ionic Version**: 4.2.0

docs(breaking): add ion-button shape attribute

---

core/src/components/input/input.tsx

fix(input): replace missing {} around button

---

core/src/components/action-sheet/test/test.utils.ts
core/src/components/alert/test/test.utils.ts
core/src/components/fab/test/test.utils.ts
core/src/components/loading/test/test.utils.ts
core/src/components/menu/test/test.utils.ts
core/src/components/modal/test/test.utils.ts
core/src/components/picker-column/test/test.utils.ts
core/src/components/popover/test/test.utils.ts
core/src/components/toast/test/basic/e2e.ts
core/src/components/toast/test/basic/index.html
core/src/components/toast/test/buttons/e2e.ts
core/src/components/toast/test/test.utils.ts
core/src/utils/test/utils.ts

Overlay tests had redundant screenshot names
- Removes additional mention of test in screen shot name (i.e. "alert: basic alert: basic")
- Also fixes one of the toast tests that kept failing

test(): remove custom screenshot names

---

core/src/components/textarea/test/basic/e2e.ts
core/src/components/textarea/test/basic/index.html
core/src/components/textarea/textarea.tsx

Issue Number: #17555 
Emits styles to the parent item on value change (in the watch) so that the item will get the proper class to float the label
Fixes #17555 and #17559

fix(textarea): float label when a value is changed async

---

core/src/components/action-sheet/test/basic/e2e.ts
core/src/components/alert/test/basic/e2e.ts

action sheet and alert RTL tests had the same name as the LTR tests, so screenshots were getting overridden
action sheet and alert RTL tests now have the `rtl:` label

fix(test): add rtl label to appropriate tests

---

core/src/components/toast/toast-interface.ts

ToastOptions interface did not include button array
- ToastOptions interface now includes button array
-
-

fix(toast): update toast interface to include buttons

---

core/src/components/slides/readme.md

Slides example had a few missing `swiper.` prefixes that caused TypeScript to complain
- Added the `swiper.` prefix where necessary

docs(slides): update usage for swiper

---

angular/src/directives/navigation/stack-controller.ts

Issue Number: https://github.com/ionic-team/ionic/issues/18082
- We now check for `getCurrentNavigation` first and then fall back to the pre 7.2 approach if users are using an older version of Angular

fix(angular): support replaceUrl with angular <7.2

---

core/src/utils/animation/animator.ts

Issue Number: https://github.com/ionic-team/ionic/issues/17729
- `animator.ts` also adds the webkit prefixed transform property along with the non-prefixed version

fix(): add prefixed transform for older versions of chrome

---

.scripts/common.js

Updates release scripts to reflect our current process

Update release scripts

---

core/src/components/loading/readme.md

Documentation references an option that does not exist.
Documentation no longer references an option that does not exist.

doc(loading): remove mention of undefined "content" property

---

core/api.txt
core/src/components/menu-button/menu-button.ios.scss
core/src/components/menu-button/menu-button.md.scss
core/src/components/menu-button/menu-button.scss
core/src/components/menu-button/readme.md

feat(menu-button): add css variables for padding

---

angular/test/test-app/e2e/src/tabs.e2e-spec.ts

- Test waits 1000ms instead of 600ms for checking tab title

test(angular): increase timeout for tab switch

---

angular/src/directives/navigation/ion-router-outlet.ts
angular/src/directives/navigation/stack-controller.ts

Issue Number: https://github.com/ionic-team/ionic/issues/18293
- When choosing which views to deactivate, `@ionic/angular` now considers the current url (i.e. where the user will end up once all navigation has been completed). This is useful if the user has queued up multiple navigations quickly (going back >1 time).
It is advised that https://github.com/ionic-team/ionic/pull/18298 be merged first.

fix(angular): ensure active page is not removed from change detection

---

core/src/components/datetime/readme.md

Issue Number: https://github.com/ionic-team/ionic/issues/18287
- Documentation is now clearer about how `ion-datetime` formats values

docs(datetime): timezone formatting

---

core/src/components/range/range.md.scss

Issue Number: references #17012

fix(range): update border radius on range pin for rtl

---

core/src/themes/ionic.functions.string.scss
core/src/themes/ionic.mixins.scss

fix(rtl): updates searchbar, fab and toggle icon positioning in rtl

---

core/src/components/segment-button/segment-button.scss
core/src/themes/ionic.functions.string.scss

Issue Number: references #17012
-
-
-

fix(segment): update segment border for rtl

---

angular/src/providers/nav-controller.ts

Issue Number: https://github.com/ionic-team/ionic/issues/18354
- Use the UrlSerializer instead of the hacky approach
-
-

fix(angular): account for query params and fragments within a string

---

CHANGELOG.md
angular/package.json
angular/src/providers/nav-controller.ts
core/README.md
core/package.json
docs/package.json

Release 4.4.2

---

core/src/components/datetime/datetime.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/18370
- Time columns are now updated on change

fix(datetime): recalculate time columns on change

---

core/src/components/tab-button/tab-button.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/18363
- When tab is selected, it can now be selected using a spacebar or enter press

fix(tabs): allow selection on enter and spacebar press

---

core/src/themes/ionic.theme.default.ios.scss
core/src/themes/ionic.theme.default.md.scss
core/src/themes/test/css-variables/css/oceanic.css

Issue Number: fixes #18449
-
-
-

fix(item): use a step color if the activated background is not set

---

core/src/components/action-sheet/action-sheet.ios.scss

style(action-sheet): remove extra parentheses

---

core/src/components/reorder-group/readme.md
core/src/components/reorder-group/usage/angular.md

docs(reorder-group): update doReorder method

---

core/src/components/back-button/back-button.ios.scss
core/src/components/back-button/back-button.ios.vars.scss
core/src/components/menu-button/menu-button.ios.scss

- adds hover and focused state to iOS menu button
references #17624
-
-
-

fix(button): use correct border-radius on menu & back button

---

CHANGELOG.md
angular/package.json
core/README.md
core/package.json
core/src/components/datetime/test/basic/e2e.ts
core/src/components/item/test/inputs/e2e.ts
core/src/components/toast/test/test.utils.ts
docs/package.json

Release 4.5.0

---

core/src/components/toolbar/readme.md

Issue Number: https://github.com/ionic-team/ionic/issues/18510#issuecomment-501404919
- Removed `no-border` reference

docs(toolbar): remove no-border reference

---

.github/PROCESS.md

- Updated process doc to reflect latest changes regarding the removal of the `stable` branch

chore(): revise process doc

---

.circleci/config.yml
angular/test/test-app/e2e/src/form.e2e-spec.ts
angular/test/test-app/e2e/src/inputs.e2e-spec.ts
angular/test/test-app/e2e/src/modal.e2e-spec.ts
angular/test/test-app/e2e/src/router-link.e2e-spec.ts
angular/test/test-app/e2e/src/slides.e2e-spec.ts
angular/test/test-app/e2e/src/tabs.e2e-spec.ts
angular/test/test-app/e2e/src/view-child.e2e-spec.ts
core/package.json
core/src/components/datetime/test/datetime.spec.ts
core/src/components/reorder-group/test/interactive/e2e.ts
core/src/components/tab-bar/test/basic/e2e.ts
core/src/utils/sanitization/test/index.html
core/stencil.config.ts
package.json

chore(): update to stencil 1.1

---

CHANGELOG.md
angular/package.json
core/README.md
core/package.json
docs/package.json

merge release-4.6.0

---

core/src/components/fab-button/fab-button.scss

Issue Number: fixes #18682
-
-
-

fix(fab-button): use correct opacity for a disabled button

---

core/src/components/menu-button/menu-button.ios.scss
core/src/components/menu-button/menu-button.md.scss
core/src/components/menu-button/test/basic/index.html

Issue Number: fixes #18667
- Moves the font-size to the parent menu button so that it can be set on the host
-
-

fix(menu-button): move font-size to host for easier customization

---

core/src/components/menu-button/menu-button.scss
core/src/components/menu-button/menu-button.tsx
core/src/components/menu-button/readme.md
core/src/components/menu-button/test/basic/index.html
core/src/components/menu-toggle/menu-toggle-util.ts
core/src/components/menu-toggle/menu-toggle.tsx
core/src/components/menu-toggle/readme.md
core/src/components/split-pane/test/basic/index.html

Issue Number: fixes #18666
- updates menu-button to use the host element
- moves menu-toggle logic to a utils file for menu button to share
- removes the dependency on menu-toggle
- adds an e2e test for an auto-hidden menu button

fix(menu-button): hide menu button when auto hide or split pane

---

core/src/themes/ionic.theme.default.ios.scss
core/src/themes/ionic.theme.default.md.scss
core/src/themes/test/css-variables/index.html

Issue Number: fixes #18658
- Fallback to the step color for MD if overlay background is not provided
- Updates the iOS overlay fallback to be lighter, closer to the default

fix(overlays): fallback to step color if overlay background variable is unset

---

.scripts/release.js
CHANGELOG.md
angular/package.json
core/README.md
core/package.json
docs/package.json

Release 4.6.2

---

react/package.json
react/src/components/IonApp.tsx
react/src/components/IonItem.tsx
react/src/components/index.ts
react/src/components/inner-proxies.ts
react/src/components/navigation/IonBackButton.tsx
react/src/components/navigation/IonTabBar.tsx
react/src/components/navigation/routing/IonRouterOutlet.tsx
react/src/components/navigation/routing/NavContext.ts
react/src/components/navigation/routing/ReactRouter/IonReactRouter.tsx
react/src/components/proxies.ts

React beta 7

---

angular/src/app-initialize.ts
angular/src/directives/control-value-accessors/value-accessor.ts
angular/src/util/util.ts

fix(inputs): apply ng form classes

---

core/src/components/textarea/textarea.tsx

-
-
-
Fixes https://github.com/ionic-team/ionic/issues/18744

fix(textarea): autogrow

---

angular/src/directives/navigation/ion-router-outlet.ts
angular/src/directives/navigation/stack-controller.ts
angular/src/providers/angular-delegate.ts
angular/test/test-app/e2e/src/router-link.e2e-spec.ts
angular/test/test-app/e2e/src/utils.ts
angular/test/test-app/src/app/alert/alert.component.html
angular/test/test-app/src/app/alert/alert.component.ts
angular/test/test-app/src/app/router-link-page/router-link-page.component.html
angular/test/test-app/src/app/router-link-page/router-link-page.component.ts
core/scripts/swiper.rollup.config.js

fix(router-outlet): attach entering view before first change detection

---

angular/src/providers/platform.ts
angular/test/test-app/e2e/src/providers.e2e-spec.ts
angular/test/test-app/src/app/providers/providers.component.html
angular/test/test-app/src/app/providers/providers.component.ts

fix(platform): wrap event listeners around zone

---

core/src/utils/tap-click.ts

fix(tap-click): ensure ripple is removed

---

core/src/components/datetime/datetime.tsx

fix(datetime): column validation

---

core/src/components/virtual-scroll/test/basic/e2e.ts
core/src/components/virtual-scroll/test/cards/e2e.ts
core/src/components/virtual-scroll/test/cards/index.html
core/src/components/virtual-scroll/virtual-scroll.scss

fix(virtual-scroll): make virtual-scroll css more specific

---

core/src/components/virtual-scroll/virtual-scroll.tsx

fix(virtual-scroll): rebuild cells on resizing

---

core/package.json

chore(): update @stencil/core to 1.2.1

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json

Merge changes from release-4.7.0 to master

---

.circleci/config.yml
angular/src/directives/navigation/stack-controller.ts
angular/src/util/ionic-router-reuse-strategy.ts
angular/test/test-app/e2e/src/tabs.e2e-spec.ts
angular/test/test-app/package-lock.json
angular/test/test-app/package.json
angular/test/test-app/src/app/alert/alert.component.ts
angular/test/test-app/src/app/app-routing.module.ts
angular/test/test-app/src/app/app.module.ts
angular/test/test-app/src/app/slides/slides.component.ts
angular/test/test-app/src/app/tabs-lazy/tabs-tab3-nested/tabs-tab3-nested.component.html
angular/test/test-app/src/app/tabs-lazy/tabs-tab3/tabs-tab3.component.html
angular/test/test-app/src/app/tabs-tab1-nested/tabs-tab1-nested.component.html
angular/test/test-app/src/app/tabs-tab1-nested/tabs-tab1-nested.component.ts
angular/test/test-app/src/app/tabs-tab1/tabs-tab1.component.html
angular/test/test-app/src/app/tabs-tab1/tabs-tab1.component.ts
angular/test/test-app/src/app/tabs-tab2/tabs-tab2.component.html
angular/test/test-app/src/app/tabs-tab2/tabs-tab2.component.ts
angular/test/test-app/src/app/tabs/tabs.module.ts
angular/test/test-app/src/app/tabs/tabs.router.module.ts
angular/test/test-app/src/app/view-child/view-child.component.ts
angular/test/test-app/src/app/virtual-scroll/virtual-scroll.component.ts

fix(router-outlet): never detach() the entering view

---

.circleci/config.yml
.scripts/release.js
CHANGELOG.md
angular/package.json
angular/src/directives/navigation/stack-controller.ts
angular/src/util/ionic-router-reuse-strategy.ts
angular/test/test-app/e2e/src/tabs.e2e-spec.ts
angular/test/test-app/package-lock.json
angular/test/test-app/package.json
angular/test/test-app/src/app/alert/alert.component.ts
angular/test/test-app/src/app/app-routing.module.ts
angular/test/test-app/src/app/app.module.ts
angular/test/test-app/src/app/slides/slides.component.ts
angular/test/test-app/src/app/tabs-lazy/tabs-tab3-nested/tabs-tab3-nested.component.html
angular/test/test-app/src/app/tabs-lazy/tabs-tab3/tabs-tab3.component.html
angular/test/test-app/src/app/tabs-tab1-nested/tabs-tab1-nested.component.html
angular/test/test-app/src/app/tabs-tab1-nested/tabs-tab1-nested.component.ts
angular/test/test-app/src/app/tabs-tab1/tabs-tab1.component.html
angular/test/test-app/src/app/tabs-tab1/tabs-tab1.component.ts
angular/test/test-app/src/app/tabs-tab2/tabs-tab2.component.html
angular/test/test-app/src/app/tabs-tab2/tabs-tab2.component.ts
angular/test/test-app/src/app/tabs/tabs.module.ts
angular/test/test-app/src/app/tabs/tabs.router.module.ts
angular/test/test-app/src/app/view-child/view-child.component.ts
angular/test/test-app/src/app/virtual-scroll/virtual-scroll.component.ts
core/package.json
docs/package.json

Release 4.7.1

---

core/src/components/searchbar/searchbar.tsx
core/src/components/searchbar/test/basic/index.html
core/src/components/searchbar/test/standalone/index.html
core/src/components/searchbar/test/toolbar/index.html

refactor(searchbar): add deprecation warnings for showCancelButton

---

core/src/components/nav-pop/readme.md

docs(nav-pop): fix typos & terminology

---

core/src/components/nav-set-root/readme.md

docs(nav-set-root): fix typos

---

core/src/components/item/test/reorder/index.html
core/src/components/reorder-group/reorder-group.tsx

fix(reorder): only move item if reorder happens

---

core/src/components/action-sheet/action-sheet.tsx
core/src/components/item-divider/item-divider.tsx
core/src/components/modal/modal.tsx

fix(): remove JSX array commas

---

angular/src/directives/control-value-accessors/boolean-value-accessor.ts
angular/src/directives/control-value-accessors/numeric-value-accesssor.ts
angular/src/directives/control-value-accessors/radio-value-accessor.ts
angular/src/directives/control-value-accessors/select-value-accessor.ts
angular/src/directives/control-value-accessors/text-value-accessor.ts
angular/src/directives/control-value-accessors/value-accessor.ts
angular/test/test-app/e2e/src/inputs.e2e-spec.ts
angular/test/test-app/src/app/inputs/inputs.component.html

fix(accessor): ngModel conflits with nested inputs

---

angular/src/providers/platform.ts

Issue Number: https://github.com/ionic-team/ionic/issues/18959
-
-
-

fix(platform): subscribeWithPriority trigger change detection

---

angular/src/app-initialize.ts
angular/src/directives/control-value-accessors/value-accessor.ts
angular/src/directives/virtual-scroll/virtual-scroll.ts
angular/src/providers/angular-delegate.ts
angular/src/providers/config.ts
angular/src/providers/dom-controller.ts
angular/src/providers/nav-controller.ts
angular/tslint.json

refactor(angular): use arrow functions

---

core/src/components/item/test/inputs/e2e.ts
core/src/components/range/range.tsx

fix(range): participate in <form>

---

angular/src/directives/navigation/stack-controller.ts
angular/test/test-app/e2e/protractor.conf.js
angular/test/test-app/e2e/src/navigation.e2e-spec.ts

fix(router): fix partial gesture

---

angular/test/test-app/e2e/src/navigation.e2e-spec.ts

chore(): disable swipe to go back e2e tests

---

CHANGELOG.md
angular/package.json
angular/test/test-app/e2e/src/navigation.e2e-spec.ts
core/package.json
docs/package.json

Release 4.7.2 merge to master

---

.scripts/release.js

chore(): add production build check

---

core/src/components/card-title/card-title.tsx
core/src/components/grid/grid.tsx

fix(): remove semicolons

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json

4.7.4 to master

---

core/src/components/action-sheet/readme.md

N/A
Updated property names and removed an option that doesn't appear to exist.

docs(action-sheet): Make property names match component

---

core/src/utils/platform.ts
core/src/utils/test/platform.spec.ts

refactor(platform): isPlatform() does not need window

---

core/src/components/virtual-scroll/test/cards/index.html

test(virtual-scroll): make cards test deterministic

---

core/src/utils/platform.ts

Issue Number: #19043 
Electron is now recognized as a platform.

fix(platform): set correct electron reg ex

---

core/src/utils/animation/animation.ts

Issue Number: There was a flickering on lower end devices that support Web Animations when using a gesture-based animation
- Removed the unneeded progressStep force (if an animation has fired `onFinish`, it has to be 100% done anyways)
- Replace `progressStep` for `setAnimationStep` thereby removing extra recursive calls.

fix(animations): resolve flickering issue on slower web animations

---

core/src/utils/animation/animation.ts

Issue Number: quickly swipe to go back multiple times sometimes would get you caught in a reset mid swipe
Only reset at the beginning of an animation (ensures nothing is left over from the last run)

perf(animation): improve reliability of reusing animation

---

core/src/components/menu/menu.tsx
core/src/components/nav/nav.tsx
core/src/components/router-outlet/route-outlet.tsx
core/src/utils/animation/animation.ts
core/src/utils/animation/cubic-bezier.ts
core/src/utils/animation/test/animation.spec.ts
core/src/utils/gesture/swipe-back.ts

Because the browser now handles animation playback in Ionic, we need to take extra steps to convert our `progressStep` values to account for any easing curves we use.
I have added utilities to help solve cubic bezier curve equations to get the appropriate step values so there is no flickering.
I am keeping this internal to Ionic for now as it needs more testing, but I have tests written and this has been tested against the curves for the menu and ios nav animations.

fix(animation): add cubic-bezier conversions for gesture animations

---

core/package.json
core/src/components/menu/menu.tsx
core/src/utils/animation/animation.ts

Bit of flickering on lower end devices w/ gesture based animations
- reduce animation padding timeout, wrap update in raf

perf(animation): reduce flickering when updating css animation on lower end devices

---

core/src/components/menu/menu.tsx

fix(animation): allow for quick swipes

---

core/src/utils/gesture/swipe-back.ts

fix(transition): update swipe back duration

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json

Release 4.8.0

---

README.md

fix(): updating link to react readme

---

angular/src/providers/events.ts

refactor(events): add deprecations

---

core/src/components/menu-button/menu-button.tsx
core/src/components/menu-toggle/menu-toggle-util.ts
core/src/components/menu-toggle/menu-toggle.tsx
core/src/components/menu-toggle/test/basic/index.html
core/src/components/menu/test/basic/index.html

fix(menu-toggle): use ESM menuController

---

angular/test/test-app/src/app/alert/alert.component.html
angular/test/test-app/src/app/modal-example/modal-example.component.html
angular/test/test-app/src/app/modal/modal.component.html
angular/test/test-app/src/app/providers/providers.component.html
angular/test/test-app/src/app/router-link-page/router-link-page.component.html
angular/test/test-app/src/app/router-link-page2/router-link-page2.component.html
angular/test/test-app/src/app/router-link-page3/router-link-page3.component.html
angular/test/test-app/src/app/router-link/router-link.component.html
angular/test/test-app/src/app/tabs-lazy/tabs-tab3-nested/tabs-tab3-nested.component.html
angular/test/test-app/src/app/tabs-lazy/tabs-tab3/tabs-tab3.component.html
angular/test/test-app/src/app/tabs-tab1-nested/tabs-tab1-nested.component.html
angular/test/test-app/src/app/view-child/view-child.component.html
angular/test/test-app/src/app/virtual-scroll-detail/virtual-scroll-detail.component.html
core/src/components/menu/readme.md
core/src/components/menu/usage/javascript.md
core/src/components/modal/readme.md
core/src/components/modal/usage/vue.md

docs(all): update usage of css utils

---

CHANGELOG.md

chore(): add missing change to CHANGELOG

---

core/src/css/core.scss
core/src/css/display.scss
core/src/css/float-elements.scss
core/src/css/padding.scss
core/src/css/structure.scss
core/src/css/text-alignment.scss
core/src/css/text-transformation.scss
core/src/css/typography.scss

chore(): fix css warnings

---

CHANGELOG.md
angular/package.json
core/package.json
core/src/utils/platform.ts
core/src/utils/test/platform.spec.ts
core/src/utils/test/platform.utils.ts
docs/package.json

* Add support for iPadOS
* add better test
* small tweak
-
-
-

Release 4.9.1

---

core/package.json
core/src/components/slides/swiper/swiper.bundle.js

chore(): update swiper

---

angular/src/app-initialize.ts

Fix angular double initialize

---

core/src/components/item-sliding/readme.md

docs(item-sliding): set headers to title case

---

core/src/components/item-group/readme.md

docs(item-group): add sliding item comment as docs

---

core/src/components/item-divider/readme.md

docs(item-divider): remove extra word "like"

---

angular/BREAKING.md

docs(breaking): fix minor grammar issues

---

core/src/utils/sanitization/index.ts

chore(): webpack does not some local variables

---

core/package.json

fix(ie): css variables

---

CHANGELOG.md

chore(): add experimental to large title

---

packages/react/src/components/createComponent.tsx

fix(react): adding href prop when routerLink is specified

---

core/src/components/popover-controller/readme.md
core/src/components/popover-controller/usage/javascript.md
core/src/components/popover/readme.md
core/src/components/popover/usage/javascript.md

Fix Object.assing typo

---

core/src/utils/animation/animation.ts
core/src/utils/animation/test/basic/index.html
core/src/utils/animation/test/chaining/index.html
core/src/utils/animation/test/display/index.html
core/src/utils/animation/test/gesture/index.html
core/src/utils/animation/test/hooks/index.html
core/src/utils/animation/test/multiple/index.html
core/src/utils/animation/test/reuse/index.html

The fallback timer for CSS Animations was firing too soon because it did not account for iterations
Fallback timer now accounts for iterations in animations

fix(animation): animation timer fallback now accounts for iterations

---

CHANGELOG.md

was already mentioned in the 4.9.1 changes

chore(): remove duplicate changelog item

---

core/src/components/searchbar/test/toolbar/index.html
core/src/components/toolbar/toolbar.ios.scss

Buttons were not aligned next to a searchbar due to the padding-top of the searchbar decreasing. 
Issue Number: fixes #19502 
Buttons are now aligned vertically and horizontally as if the searchbar was not there. 
| ---| ---|
| ![localhost_3333_src_components_searchbar_test_toolbar(iPhone 6_7_8) (2)](https://user-images.githubusercontent.com/6577830/66059716-7bbe1800-e50a-11e9-8169-c78a40adad74.png) | ![localhost_3333_src_components_searchbar_test_toolbar(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/6577830/66059573-3994d680-e50a-11e9-9719-e1ba47524388.png) |

fix(searchbar): update padding and button alignment

---

core/src/components/list/list.md.scss

Issue Number: https://github.com/ionic-team/ionic/issues/19507
- Revised the CSS logic so that the first item has a bottom border but not a top border

fix(list): add bottom border for first item in inset list

---

core/src/components/menu/menu.tsx
core/src/components/split-pane/split-pane.tsx

refactor(menu): deprecate main html attribute

---

core/src/utils/animation/animation-interface.ts
core/src/utils/animation/animation.ts

Renamed `AnimationOnFinishOptions` to `AnimationCallbackOptions` to prepare for https://github.com/ionic-team/ionic/issues/19548

refactor(animations): rename AnimationOnFinishOptions to AnimationCallbackOptions

---

core/src/components/header/header.utils.ts
core/src/utils/transition/ios.transition.ts

Issue Number: https://github.com/ionic-team/ionic/issues/19541
1. Check the correct bounding box in the IO handler
2. Account for any left/right offsets when doing nav transitions

fix(header): fix collapsing iOS header when using with split pane

---

core/api.txt
core/src/components/range/range.scss
core/src/components/range/readme.md

Documentation does not specify the CSS custom properties for the range pin
Added CSS custom properties for range pin

docs(range): add range pin CSS custom properties

---

CHANGELOG.md
angular/package.json
core/package.json
core/src/components/modal/test/test.utils.ts
core/src/utils/overlays.ts
docs/package.json

Release 4.10.2

---

core/src/components/content/content.tsx

fix(content): overscroll only in iOS

---

core/package.json
core/src/components/app/app.tsx
core/src/components/slides/slides.tsx
core/src/utils/helpers.ts
docs/.gitignore
docs/package.json

feat(): typed @ionic/docs

---

core/src/components/split-pane/split-pane.tsx

`main` already removed in `next`. Need to remove old deprecation warning.

refactor(split-pane): remove [main] deprecation warning

---

CHANGELOG.md
angular/package.json
core/package.json
core/src/components/content/content.tsx
core/src/components/searchbar/searchbar.ios.scss
core/src/components/searchbar/test/toolbar/index.html
core/src/components/toolbar/toolbar.ios.scss
docs/package.json

Release 4.10.3

---

CHANGELOG.md
angular/package.json
core/package.json
core/src/components/content/content.tsx
core/src/components/searchbar/searchbar.ios.scss
core/src/components/searchbar/test/toolbar/index.html
core/src/components/toolbar/toolbar.ios.scss
docs/package.json

master Release 4.10.3

---

core/src/utils/animation/animation.ts

Issue Number: #19629
Entire forEach is wrapped in an raf rather than each iteration. Should reduce the number of raf calls for animations with multiple elements.

perf(animations): wrap loop in raf call

---

.circleci/config.yml
angular/test/test-app/e2e/protractor.conf.js
core/src/components/footer/test/translucent/e2e.ts
core/src/components/header/test/translucent/e2e.ts
core/src/components/toast/test/buttons/e2e.ts
core/src/utils/test/modes/e2e.ts
core/src/utils/test/utils.ts

chore(tests): update tests and add e2e to ci

---

packages/react-router/package.json

React router move tslint to devdeps

---

.scripts/common.js

fix(build): properly update peer dependencies

---

packages/react/src/components/IonPicker.tsx
packages/react/src/components/index.ts
packages/react/src/components/proxies.ts

fix(react): add IonPicker as controller component, fixes #19620

---

packages/react/src/components/navigation/IonTabBar.tsx

fix(react): handle tab back nav better, fixes #19646

---

packages/react-router/src/ReactRouter/NavManager.tsx
packages/react/src/components/__tests__/IonTabs.spec.tsx
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/contexts/NavContext.ts

React fix tab nav

---

.scripts/common.js
CHANGELOG.md
angular/package.json
angular/test/test-app/e2e/protractor.conf.js
core/package.json
docs/package.json
packages/react-router/package.json
packages/react-router/src/ReactRouter/NavManager.tsx
packages/react/package.json
packages/react/src/components/IonPicker.tsx
packages/react/src/components/__tests__/IonTabs.spec.tsx
packages/react/src/components/index.ts
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/components/proxies.ts
packages/react/src/contexts/NavContext.ts

Release 4.11.1

---

.scripts/common.js

chore(release): npm link react package

---

core/src/utils/animation/animation.ts

The cleanup for CSS Animations is done in an raf, so the elements array may have already been emptied by the time to code runs.
Had the clean up function take a copy of the elements array before calling the raf.

fix(animations): ensure all elements are cleaned up when calling .destroy()

---

.github/PROCESS.md
.scripts/common.js
.scripts/prepare.js
.scripts/release.js
CHANGELOG.md
angular/package.json
angular/test/test-app/e2e/protractor.conf.js
core/package.json
docs/package.json
packages/react-router/package.json
packages/react/package.json

- adds support for changing the tag from `latest` to `next`
- checks the user's confirmation on the prepare and tag to end the script if the user selects no
- adds support for passing --dry-run to see what the publish will be
-
-
-

release 5.0.0-rc.0

---

core/src/components/header/header.tsx
core/src/components/header/header.utils.ts
core/src/components/tabs/test/basic/index.html

Issue Number: https://github.com/ionic-team/ionic/issues/19640
- Header now selects correct tab
- Also reduced the number of DOM reads/rights by moving the toolbar border animation to the intersection observer

fix(header): collapsible header works in tabs

---

core/src/components/title/readme.md
core/src/components/title/usage/angular.md
core/src/components/title/usage/javascript.md
core/src/components/title/usage/react.md
core/src/components/title/usage/vue.md

Issue Number: https://github.com/ionic-team/ionic/issues/19663
- Added an example on how to style collapse header w/ large title

docs(header): add collapse header styling details

---

packages/react-router/src/ReactRouter/IonReactHashRouter.tsx
packages/react-router/src/ReactRouter/IonReactRouter.tsx
packages/react-router/src/ReactRouter/NavManager.tsx
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/index.ts
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/contexts/NavContext.ts

fix(react): adding HashRouter to available ion routers

---

packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/ViewStacks.ts

fix(react): removing pages from DOM on nav, fixes #19701

---

packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/components/navigation/IonTabs.tsx

fix(react): adding change events to iontabs, fixes #19665

---

.scripts/common.js
CHANGELOG.md
angular/package.json
core/package.json
core/src/components/header/header.tsx
core/src/components/header/header.utils.ts
core/src/components/menu/menu.tsx
core/src/utils/animation/animation.ts
core/src/utils/animation/cubic-bezier.ts
core/src/utils/animation/test/animation.spec.ts
core/src/utils/transition/index.ts
core/src/utils/transition/ios.transition.ts
core/src/utils/transition/md.transition.ts
docs/package.json
packages/react-router/package.json
packages/react-router/src/ReactRouter/IonReactHashRouter.tsx
packages/react-router/src/ReactRouter/IonReactRouter.tsx
packages/react-router/src/ReactRouter/NavManager.tsx
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/ViewStacks.ts
packages/react-router/src/ReactRouter/index.ts
packages/react/package.json
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/components/navigation/IonTabs.tsx
packages/react/src/contexts/NavContext.ts

Release 4.11.2

---

CHANGELOG.md
packages/react-router/src/ReactRouter/IonReactHashRouter.tsx
packages/react-router/src/ReactRouter/IonReactRouter.tsx
packages/react-router/src/ReactRouter/NavManager.tsx
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/ViewStacks.ts
packages/react-router/src/ReactRouter/index.ts
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/components/navigation/IonTabs.tsx
packages/react/src/contexts/NavContext.ts

Sync 4.11.2

---

core/src/components/textarea/textarea.scss

Issue Number: fixes #19616
-
-
-

fix(textarea): remove padding from textarea placeholder

---

core/src/components/segment-button/segment-button.ios.scss
core/src/components/segment-button/segment-button.md.scss
core/src/components/segment-button/segment-button.scss
core/src/components/segment-button/segment-button.tsx
core/src/components/segment/segment.ios.scss
core/src/components/segment/segment.md.scss
core/src/components/segment/segment.scss
core/src/components/segment/segment.tsx
core/src/components/segment/test/custom/index.html

This updates the feature segment branch to add an indicator to each button and transition each one individually fixing the problem of not being able to work on different width segments & scrollable segments.

fix(segment): update indicator to be on each button

---

packages/react/src/components/createControllerComponent.tsx

React overlay loading 4.11.3

---

core/src/components/header/header.utils.ts
core/src/components/toolbar/test/title/index.html

Issue Number: https://github.com/ionic-team/ionic/issues/19773
- Translucent toolbars now work with collapsible header

fix(header): translucent toolbars now work with collapsible headers

---

core/src/utils/animation/animation-interface.ts
core/src/utils/animation/animation.ts
core/src/utils/animation/test/basic/index.html

Issue Number: https://github.com/ionic-team/ionic/issues/19550
- Added ability to provide a custom ID to make debugging easier

feat(animation): Animation Identifiers

---

angular/src/index.ts
angular/src/providers/animation-controller.ts

This exposes Ionic Animations in a more "Angular-y" fashion via the AnimationController. I will update the Animation Docs to show its usage.

feat(angular): Expose Ionic Animations via the AnimationController

---

core/src/components/toast/toast.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/19791
- Ensure toast fires cancel handler when dismissing

fix(toast): call handler on cancel

---

.scripts/common.js
CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/react-router/package.json
packages/react-router/src/ReactRouter/RouteManagerContext.ts
packages/react-router/src/ReactRouter/Router.tsx
packages/react/package.json
packages/react/src/components/createControllerComponent.tsx
packages/react/src/components/utils/attachProps.ts

Release 4.11.3

---

packages/react/README.md

After running `ionic integrations enable capacitor` the webDir is already set to "build" in the config file. This step is no longer needed.
-
-
-

doc(readme) - Updated README.md

---

packages/react/README.md

chore(react): removing beta verbiage from readme

---

core/src/components/menu/menu.tsx
core/src/utils/animation/animation-interface.ts
core/src/utils/animation/animation.ts

Tracking on CSS Animations should not take into account the delay since it's going to be overridden anyways
.
- Do not include delay when doing tracking
- Also exposed `step` for progressStep to accommodate browser quirks/flickering when resetting animations

fix(animation): track correctly when updating CSS Animation

---

core/src/components/tab/tab.tsx
core/src/components/tabs/tabs.tsx
core/src/components/tabs/test/standalone/index.html
core/src/utils/gesture/pointer-events.ts

chore(): fix tabs 

---

packages/react-router/src/ReactRouter/NavManager.tsx
packages/react/src/components/utils/index.tsx

fix(react): adding hardware back button support, fixes(19819)

---

core/src/components/header/header.ios.scss

Issue Number: https://github.com/ionic-team/ionic/issues/19839
- Toggle the visibility of the scroll header with `visibility: hidden` instead of `opacity: 0` to work around a bug in iOS Safari

fix(header): avoid flicker on ios when collapsing

---

packages/react-router/src/ReactRouter/Router.tsx

fix(react): add check to warn if no ionpage is found, fixes #19832

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/react-router/package.json
packages/react-router/src/ReactRouter/NavManager.tsx
packages/react-router/src/ReactRouter/RouteManagerContext.ts
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/src/utils/LocationHistory.ts
packages/react-router/tslint.json
packages/react/package.json
packages/react/src/components/createControllerComponent.tsx
packages/react/src/components/index.ts
packages/react/src/components/utils/index.tsx
packages/react/src/contexts/IonLifeCycleContext.tsx
packages/react/src/lifecycle/hooks.ts

Release 4.11.4

---

angular/src/directives/navigation/nav-params.ts

No Generic Type to navParams() while it is returned right now. 
- There is a generic type to navParams()
-
-

Generic Type to navigation parameters get()

---

core/src/components/menu/menu.tsx

change deprecated error message
`ion-split-pane` error message is suggest id name is be `main-content`. But `ion-menu` suggest id name is be `my-content` .
```
ion-split-pane-ios.entry.js:46 [DEPRECATED][ion-split-pane] Using the [main] attribute is deprecated, please use the "contentId" property instead:
BEFORE:
<ion-split-pane>
...
<div main>...</div>
</ion-split-pane>
AFTER:
<ion-split-pane contentId="main-content">
...
<div id="main-content">...</div>
</ion-split-pane>
```
```
[DEPRECATED][ion-menu] Using the [main] attribute is deprecated, please use the "contentId" property instead:
BEFORE:
<ion-menu>...</ion-menu>
<div main>...</div>
AFTER:
<ion-menu …
```

chore(menu): change deprecated error message

---

angular/src/index.ts
angular/src/providers/gesture-controller.ts
core/src/interface.d.ts

Gestures were only exposed in @ionic/core
Exposed gestures in @ionic/angular

feat(angular): expose Ionic Gesture via GestureController

---

core/api.txt
core/src/components/slides/readme.md
core/src/components/slides/slides.scss

docs(slides): document css vars

---

core/src/utils/gesture/index.ts

Issue Number: https://github.com/ionic-team/ionic/issues/19848
Disabling a gesture while in the middle of said gesture leave it at an inconsistent state as the gesture system things a gesture is already in progress and as a result does not let you start a new one.
This is commonly found when disabling gesture based Ionic components via a third party gesture (such as HammerJS).
- Reset the state of the gesture when disabling the gesture

fix(gesture): release gesture when disabling

---

CHANGELOG.md
angular/package.json
angular/src/providers/config.ts
core/package.json
docs/package.json
packages/react-router/package.json
packages/react/package.json
packages/react/src/contexts/IonLifeCycleContext.tsx
packages/react/src/lifecycle/hooks.ts
packages/react/tslint.json

Release 4.11.5

---

CHANGELOG.md
packages/react/src/contexts/IonLifeCycleContext.tsx
packages/react/src/lifecycle/hooks.ts
packages/react/tslint.json

Sync 4.11.5

---

core/src/components/header/header.tsx
core/src/components/header/header.utils.ts
core/src/components/toolbar/test/title/index.html
core/src/utils/transition/ios.transition.ts

Dev build `5.0.0-dev.201911141743.24e780d`
1. IO and scroll listener did not work properly with multiple toolbars
2. iOS transition did not account for multiple toolbars when determining animation translate
- Added a forEach to the header to toggle all toolbars, not just the first toolbar
- Adjusted iOS transition to account for the real title/back button top offsets when setting positioning of the fake title/back buttons.

fix(header): support collapsible header with multiple toolbars

---

core/src/components.d.ts
core/src/components/input/input.tsx
core/src/components/input/readme.md
core/src/components/searchbar/readme.md
core/src/components/searchbar/searchbar.tsx
core/src/components/textarea/readme.md
core/src/components/textarea/textarea.tsx

Changed ocurred to occurred in multiple files. 
Docs regenerated.

docs(core): fix occurred typo

---

core/src/css/text-alignment.scss
core/src/css/text-transformation.scss

Couple of the comments still mentioned the directives.

docs(deprecated-directives): update directive references

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/react-router/package.json
packages/react/package.json

5.0.0-beta.1

---

core/src/components/title/readme.md
core/src/components/title/usage/angular.md
core/src/components/title/usage/javascript.md
core/src/components/title/usage/react.md
core/src/components/title/usage/vue.md

fixes #19483
In order for the collapsible large title to work properly across different application setups and themes, `fullscreen="true"` on `ion-content` and `translucent="true"` on the main `ion-header` is required. This is, more or less, what native iOS apps do as well.
Users who do not do this (and use either a dark theme or a sidemenu component), will see some visual glitches with a whitespace at the top of the screen.
This is because we need to fade the entire main header toolbars out when the large title is not collapsed in order to stay compliant with the iOS spec. The iOS spec allows for the header to have a certain color, and to have the content background color …

docs(title): update large title docs to mention translucent and fullscreen requirements

---

core/src/utils/animation/animation-interface.ts
core/src/utils/animation/animation.ts

⚠️ Add Manu as co-author when merging
`progressEnd` web animations were not being updated properly 
1. Ensure `progressEnd` updates Web Animations
2. Update types.
3. Reorganize code a bit

fix(animation): properly update Web Animation, clean up types

---

core/src/components/tabs/readme.md

chore(react): fix tabs docs

---

packages/react-router/src/ReactRouter/NavManager.tsx
packages/react-router/src/ReactRouter/RouteManagerContext.ts
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/src/ReactRouter/View.tsx
packages/react-router/src/ReactRouter/ViewItem.ts
packages/react-router/src/ReactRouter/ViewStacks.ts
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/contexts/NavContext.ts

React viewitem clone

---

packages/react-router/package.json
packages/react-router/src/ReactRouter/NavManager.tsx
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/tslint.json
packages/react/package.json
packages/react/src/components/IonPage.tsx
packages/react/src/components/createControllerComponent.tsx
packages/react/src/components/createOverlayComponent.tsx
packages/react/tslint.json

React back button appear fix

---

core/src/components/progress-bar/readme.md

Changed "addditional" to "additional" on ion-progress-bar docs

---

core/src/utils/animation/animation-interface.ts
core/src/utils/animation/animation.ts

playSync and playAsync methods were deprecated in favor of the play method.
Removed playSync and playAsync method. Developers should use the play method instead.

chore(animations): remove deprecated methods

---

core/src/components/picker/picker.tsx

`this.getSelected()` was removed during the refactor here: https://github.com/ionic-team/ionic/commit/7988720b1cf46a651d9c140f0fe95726d3feb48c#diff-f5e2178ccdf7ab64bcb5f9c73cd67ee9L174-R182
Issue Number: https://github.com/ionic-team/ionic/issues/20036
- Pass the selected picker value to the handler

fix(picker): pass selected value to handler on dismiss

---

core/src/components/tabs/readme.md
packages/react-router/src/ReactRouter/IonRouteAction.ts
packages/react-router/src/ReactRouter/NavManager.tsx
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/src/ReactRouter/View.tsx
packages/react-router/src/ReactRouter/ViewItem.ts
packages/react-router/src/ReactRouter/ViewStacks.ts
packages/react-router/tslint.json
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/contexts/NavContext.ts

React router loading flash

---

packages/react-router/src/ReactRouter/NavManager.tsx
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/utils/LocationHistory.ts
packages/react/src/components/hrefprops.ts

fix(react): support for 'root' router direction, fixes #19982

---

CHANGELOG.md
angular/package.json
core/package.json
core/src/components/tabs/readme.md
docs/package.json
packages/react-router/package.json
packages/react-router/src/ReactRouter/IonRouteAction.ts
packages/react-router/src/ReactRouter/NavManager.tsx
packages/react-router/src/ReactRouter/RouteManagerContext.ts
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/src/ReactRouter/View.tsx
packages/react-router/src/ReactRouter/ViewItem.ts
packages/react-router/src/ReactRouter/ViewStacks.ts
packages/react-router/src/utils/LocationHistory.ts
packages/react-router/tslint.json
packages/react/package.json
packages/react/src/components/IonPage.tsx
packages/react/src/components/IonRouterOutlet.tsx
packages/react/src/components/IonicReactProps.ts
packages/react/src/components/createControllerComponent.tsx
packages/react/src/components/createOverlayComponent.tsx
packages/react/src/components/hrefprops.ts
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/src/contexts/NavContext.ts
packages/react/tslint.json

Release 4.11.6

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/react-router/package.json
packages/react/package.json

5.0.0-beta.2

---

packages/react-router/empty-module.js
packages/react-router/jest.setup.js
packages/react-router/package.json
packages/react-router/setupTests.ts
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/__tests__/Router.spec.tsx

fix(react): fire lifecycle events on initial render, fixes #20071

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/react-router/empty-module.js
packages/react-router/jest.setup.js
packages/react-router/package.json
packages/react-router/setupTests.ts
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/__tests__/Router.spec.tsx
packages/react/package.json

Release 4.11.7

---

core/src/components/item/readme.md
core/src/components/item/usage/angular.md
core/src/components/item/usage/javascript.md
core/src/components/item/usage/react.md
core/src/components/item/usage/vue.md

Currently the documentation is not showing how to create an ion-item button and show the ripple. This commit simply adds an example to add an ion-item with the attribute button to show a ripple.
- [N/A] Tests for the changes have been added (for bug fixes / features)
- [N/A] Build (`npm run build`) was run locally and any changes were pushed
- [N/A ] Lint (`npm run lint`) has passed locally and any fixes were made for failures
N/A
Simply modifies the documentation to add the "button" attribute to an ion-item.
N/A
N/A

ion-item button with ripple

---

core/src/components/toast/readme.md
packages/react/src/components/IonActionSheet.tsx
packages/react/src/components/IonToast.tsx

fix(react): fixing type of icon in ToastOptions, fixes #20100

---

core/api.txt
core/src/components/radio/radio.ios.scss
core/src/components/radio/radio.md.scss
core/src/components/radio/radio.scss
core/src/components/radio/readme.md
core/src/components/radio/test/basic/index.html

Issue Number: https://github.com/ionic-team/ionic/issues/17166#issuecomment-460770151
- Added --border-radius to customize the outer radio
- Added --border-radius-checked to customize the "dot" on the inside of the radio when checked

feat(radio): add --border-radius and --inner-border-radius variables

---

core/src/components/action-sheet/action-sheet.ios.scss
core/src/components/action-sheet/action-sheet.scss

Issue Number: https://github.com/ionic-team/ionic/issues/17311
- action sheets intended to be scrollable can now actually be scrolled on iOS
- account for safe areas when setting max height of action sheet

fix(action-sheet): action sheet now scrollable and accounts for safe areas on iOS

---

core/api.txt
core/src/components/menu/menu.tsx
core/src/components/split-pane/split-pane.tsx

Fixes https://github.com/ionic-team/stencil/issues/2119

fix(ssr): reflect content-id attribute

---

core/src/components/modal/animations/ios.enter.ts
core/src/components/modal/animations/ios.leave.ts
core/src/components/modal/modal.ios.scss
core/src/components/modal/test/spec/index.html

Updates animations to be closer to native

chore(core): better animations

---

core/src/components/picker-column/picker-column.tsx

Issue Number: #19659 
Select the closest picker option when releasing the picker column at rest.
This makes it easier to pick a specific option since it is closer to the behavior of the native iOS picker.

fix(picker): pick closest option at low velocity

---

angular/BREAKING.md

- Grid layout link points to correct page

docs(breaking) fix broken grid layout link

---

packages/react-router/src/ReactRouter/IonReactMemoryRouter.tsx
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/index.ts

fix(react): add missing react memory router

---

BREAKING.md
core/src/components/app/test/safe-area/index.html
core/src/components/menu-toggle/test/basic/index.html
core/src/components/menu-toggle/test/button/index.html
core/src/components/menu-toggle/test/list/index.html
core/src/components/menu/readme.md
core/src/components/menu/test/basic/index.html
core/src/components/menu/test/standalone/index.html
core/src/components/menu/test/test.utils.ts
core/src/components/menu/usage/angular.md
core/src/components/menu/usage/javascript.md
core/src/components/menu/usage/vue.md
core/src/components/modal/readme.md
core/src/components/modal/usage/vue.md
core/src/components/router-outlet/test/basic/index.html
core/src/components/split-pane/readme.md
core/src/components/split-pane/usage/angular.md
core/src/components/split-pane/usage/javascript.md
core/src/components/split-pane/usage/react.md
core/src/components/split-pane/usage/vue.md
core/src/components/toast/readme.md
core/src/utils/test/modes/index.html

This is just to add the breaking changes for v5 to a file that we can link to. They can still be listed in the changelog, but this is a more comprehensive overview of what's changed. 
Spoke with Ben and Kevin, we're going to move the ionicons list to the ionicons repo and link to that.

docs(breaking): add breaking changes for v5

---

packages/react-router/src/ReactRouter/IonReactMemoryRouter.tsx
packages/react-router/src/ReactRouter/Router.tsx

chore(react): updating types for location state to fix type errors

---

packages/react/src/components/IonIcon.tsx
packages/react/src/components/index.ts

fix(react): updating icon type and add caret to internal icons

---

core/src/components/title/readme.md
core/src/components/title/usage/angular.md
core/src/components/title/usage/javascript.md
core/src/components/title/usage/react.md
core/src/components/title/usage/vue.md

Issue Number: https://github.com/ionic-team/ionic/issues/20217
- Documentation now states that collapsible buttons in the content should be placed in the `end` slot as per the iOS spec.

docs(title): update button example with large title

---

packages/react/src/components/createOverlayComponent.tsx

fix(react): re attach props on update, fixes 20192

---

packages/react/src/components/IonActionSheet.tsx
packages/react/src/components/IonIcon.tsx
packages/react/src/components/IonToast.tsx
packages/react/src/components/index.ts
packages/react/src/components/navigation/IonBackButton.tsx

fix(react): update icon types to be a string as well, fixes #20229

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

5.0.0-beta.5

---

core/src/components/segment/segment.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20253
- Clicking disabled segment button no longer adds a ripple to the active non-disabled button.

fix(segment): clicking disabled button no longer adds ripple to active button

---

core/src/components/content/content.scss

Issue Number: #20258
- Set `min-height` on `#scroll-content`

fix(content): set min-height to allow for sticky headers

---

packages/react/src/components/createControllerComponent.tsx
packages/react/src/components/createOverlayComponent.tsx

fix(react): adding missing overlay component events, fixes #19923

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

Release 5.0.0-beta.6 / 5.0.0-rc.0

---

.github/ISSUE_TEMPLATE.md

chore(ISSUE_TEMPLATE): add v5 checkarea

---

angular/README.md
angular/package.json
angular/src/schematics/add/index.ts
angular/src/schematics/utils/config.ts

The `README.md` instructs the user to link the invalid directory.
The `npx schematics @ionic/angular:ng-add`  command generates an invalid `angular.json`. See my comment on the: https://github.com/ionic-team/ionic/commit/7af0198e2e5bdb48af401454181c1f06c2f876a7#r36943372
- The `README.md` instructs the user to link the `ionic/angular/dist` directory.
- The `npx schematics @ionic/angular:ng-add` generates a valid `angular.json` file.
cc: @mhartington

fix(angular): ng-add schematic

---

core/src/components/menu/menu.tsx
core/src/utils/animation/animation.ts

Issue Number: https://github.com/ionic-team/ionic/issues/20286
- Added greater precision to animation util
- Account for 0 corner case in menu

fix(menu): fix jump when dragging open

---

BREAKING.md

chore(): update breaking changes doc for ion-radio

---

CHANGELOG.md

merge release-4.11.10

---

core/src/components/toast/test/basic/index.html
core/src/components/toast/toast.scss

fix(toast): inherit color in cancel button for a toast with color

---

core/src/themes/ionic.mixins.scss

fix(components): inherit text indent in all components with text inherit

---

core/src/components/picker/picker-interface.ts

fix(picker): include showBackdrop in interface

---

core/src/components/refresher/refresher.utils.ts
core/src/components/refresher/test/basic/index.html

https://github.com/ionic-team/ionic/commit/32a7401576a9c91fdee66d2cede06b6a16884d35 converts camel case properties to dashed properties. The default now is for devs to use camel case.
- Updated stroke-dasharray to be strokeDasharray
- Updated test to match spec

fix(refresher): update animation for dashed property values

---

packages/react/src/components/CreateAnimation.tsx
packages/react/src/components/index.ts

Ionic React was missing a few type exports
Exported appropriate types for devs to use in their apps

fix(react): export proper types of animations and gestures

---

core/src/components/content/content.scss
core/src/components/content/content.tsx
core/src/components/refresher/refresher.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20305
- Move `#scroll-content` to be a parent of `.inner-scroll`
- Moved the `background` property from `.inner-scroll` to `#scroll-content`
- Updated iOS PTR to translate `.inner-scroll` instead of `#scroll-content`

fix(content): resolve height inheritance issues

---

core/src/components/backdrop/readme.md
core/src/components/backdrop/usage/vue.md
core/src/components/buttons/readme.md
core/src/components/buttons/usage/vue.md
core/src/components/checkbox/readme.md
core/src/components/checkbox/usage/vue.md
core/src/components/datetime/readme.md
core/src/components/datetime/usage/vue.md
core/src/components/input/readme.md
core/src/components/input/usage/vue.md
core/src/components/progress-bar/readme.md
core/src/components/progress-bar/usage/angular.md
core/src/components/progress-bar/usage/vue.md
core/src/components/select/readme.md
core/src/components/select/usage/vue.md
core/src/components/textarea/readme.md
core/src/components/textarea/usage/vue.md
core/src/components/thumbnail/readme.md
core/src/components/thumbnail/usage/angular.md
core/src/components/thumbnail/usage/vue.md
core/src/components/toggle/readme.md
core/src/components/toggle/usage/vue.md
core/src/components/toolbar/readme.md
core/src/components/toolbar/usage/vue.md

Per the Vue docs on Props, all properties should be kebab-case. This updates the usage section of all components to reflect this: https://vuejs.org/v2/guide/components-props.html
references #20296
I didn't update the Events (https://vuejs.org/v2/guide/components-props.html) because I need to verify how we're exposing them to Vue. 
-
-
-

docs(vue): update usage examples to kebab-case

---

core/src/components/grid/readme.md
core/src/components/grid/usage/angular.md
core/src/components/grid/usage/javascript.md
core/src/components/grid/usage/react.md
core/src/components/grid/usage/vue.md
core/src/components/modal/readme.md
core/src/components/modal/usage/vue.md

docs(grid): update usage to correct CSS utility classes

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

5.0.0-rc.1

---

core/src/components/refresher/refresher.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20320
- Checked to see if refresher was initialized before re-initializing
- Checked to see if scroll element existed before setting up refresher

fix(refresher): resolve undefined issues when updating component

---

core/src/components/content/readme.md
core/src/components/content/usage/angular.md
core/src/components/content/usage/javascript.md
core/src/components/content/usage/react.md
core/src/components/content/usage/vue.md

closes ionic-team/ionic-docs#731
-
-
-

docs(content): add information on fixed slots

---

core/src/components/radio/radio.tsx
core/src/components/radio/test/radio.spec.ts
core/src/components/radio/test/standalone/index.html

Issue Number: https://codepen.io/brandyscarney/pen/dyPEdZY
- Set default value of radio if `undefined`

fix(radio): set default radio value if undefined

---

core/src/components/loading/readme.md
core/src/components/loading/usage/angular.md
core/src/components/loading/usage/javascript.md
core/src/components/loading/usage/react.md
core/src/components/loading/usage/vue.md

closes ionic-team/ionic-docs#1200
-
-
-

docs(loading): update usage to fix code errors

---

core/src/components/select/readme.md
core/src/components/select/usage/react.md

closes ionic-team/ionic-docs#1095
-
-
-

docs(select): separate react usage by headings

---

core/src/components/radio-group/test/search/e2e.ts
core/src/components/radio-group/test/search/index.html
core/src/components/radio/radio.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20323
- `ion-radio` no longer clears the value of `ion-radio-group` in disconnectedCallback, keeping with the idea that value is controlled by the `ion-radio-group`.
- Added a new test

fix(radio): do not clear value of radio group from radio

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

merge release-5.0.0-rc.2

---

BREAKING.md
core/src/components/item/item.scss
core/src/components/select/readme.md
core/src/components/select/usage/react.md
core/src/themes/test/css-variables/css/dark.css
core/src/themes/test/css-variables/css/vibrant.css

docs(breaking): remove references to removed global css vars

---

core/src/components/segment/segment.ios.scss
core/src/components/segment/test/custom/index.html

fix(segment): allow background to be set on iOS segment in a toolbar

---

core/src/components/card/readme.md
core/src/components/card/usage/react.md
core/src/components/grid/readme.md
core/src/components/grid/usage/react.md
core/src/components/item/readme.md
core/src/components/item/usage/react.md
core/src/components/label/readme.md
core/src/components/label/usage/react.md
core/src/components/menu/readme.md
core/src/components/menu/usage/react.md

docs(react): update class usage to className

---

core/src/components/footer/footer.ios.scss
core/src/components/footer/footer.scss
core/src/components/header/header.ios.scss
core/src/components/header/header.scss
core/src/components/header/header.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20354
- CSS is targeted using `last-of-type` rather than `last-child`

fix(toolbar): properly apply safe area and border

---

BREAKING.md

chore(): update breaking docs for segment event

---

core/src/components/refresher/refresher.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20379
- Increased threshold for gesture from 0-->5

fix(refresher): ensure gesture does not interfere with item-sliding

---

core/src/components/header/header.ios.scss
core/src/components/header/header.ios.vars.scss

Issue Number: https://github.com/ionic-team/ionic/issues/20385
- Disabled backdrop-filter saturation until header is fully collapsed, avoiding the background color distortion

fix(header): backdrop filter no longer distorts content with collapsible header

---

core/package.json

chore(ionicons): update to official 5.0.0 release

---

core/src/components/content/content.tsx

`ionScroll` events were being emitted regardless of whether or not the `scrollEvents` prop was set to `true`.
- `ionScroll` events are only emitted if the `scrollEvents` prop is set to `true`

fix(content): only emit scroll events if enabled

---

packages/react/package.json

chore(react): update to ionicons v5 final

---

packages/react-router/src/ReactRouter/Router.tsx

dont remove pages when navigating between tabs, fixes #20398

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

5.0.0-rc.4

---

CHANGELOG.md
angular/package.json
core/package.json
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

5.0.0-rc.5

---

packages/react-router/src/ReactRouter/RouteManagerContext.ts
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/StackManager.tsx

fix(react): Do a better job matching up route to sync, fixes #20363

---

core/src/components/action-sheet/readme.md
core/src/components/alert/readme.md
core/src/components/loading/readme.md
core/src/components/menu/readme.md
core/src/components/menu/usage/javascript.md
core/src/components/modal/readme.md
core/src/components/modal/usage/javascript.md
core/src/components/popover/readme.md
core/src/components/toast/readme.md

Ionic 5 removed the controller components, but we still need to remove mention of them from the docs.
Docs no longer reference the controller components.

docs(): remove mention of controllers

---

packages/react-router/src/ReactRouter/RouteManagerContext.ts
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/src/ReactRouter/View.tsx

React redirect issue

---

core/src/components/card/card.scss
core/src/components/card/test/button/index.html

fix(card): inherit background in inner button

---

packages/react/src/components/IonIcon.tsx
packages/react/tslint.json

fix(react): icons with MD set should work in browser

---

core/src/components/modal/animations/ios.enter.ts

Issue Number: https://github.com/ionic-team/ionic/issues/20469
- Added "!important" when setting the black background color

fix(modal): prevent card style modal styles from being overridden 

---

core/src/components/modal/animations/ios.enter.ts
core/src/components/modal/animations/ios.leave.ts

Issue Number: https://github.com/ionic-team/ionic/issues/20475
- This only worked in Chrome because it supports `contain` - Safari does not. Added `overflow: hidden` to `ion-modal` when it is used as a `presentingElement`

fix(modal): presenting multiple card-style modals now adds border radius properly

---

packages/react/src/components/navigation/IonTabBar.tsx

fix(react): update paths when href changes in ion buttons, fixes #20321

---

core/src/components/input/input.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20442
- Check to make sure "Enter" key was not pressed before clearing text input

fix(input): do not clear input if "Enter" key pressed

---

core/src/components/col/readme.md
core/src/components/icon/readme.md
core/src/components/item/readme.md
core/src/components/row/readme.md

closes ionic-team/ionic-docs#1230
-
-
-

docs(grid): update usage from attributes to classes

---

packages/react-router/src/ReactRouter/RouteManagerContext.ts
packages/react-router/src/ReactRouter/Router.tsx
packages/react-router/src/ReactRouter/StackManager.tsx
packages/react-router/src/ReactRouter/View.tsx
packages/react/src/components/IonIcon.tsx
packages/react/src/components/navigation/IonTabBar.tsx
packages/react/tslint.json

React 4.11 merge

---

core/src/components/fab-button/fab-button.ios.scss
core/src/components/fab-button/fab-button.md.scss
core/src/components/fab-button/fab-button.scss
core/src/components/fab/test/states/index.html
core/src/components/tabs/test/basic/index.html

Go to a fab that opens a list, click to open it and then hover over the button and see that the close icon disappears. This is due to a missing `z-index` on the close icon. In addition, setting a custom `--color` requires setting all of the color state variables.
Show the close icon on top of the hover, focused, etc. states. Use the value of `var(--color)` for all color states.
I added a fab button that opens to this test: http://localhost:3333/src/components/fab/test/states?ionic:mode=ios
It's easier to reproduce on iOS because Material Design doesn't use background hover/focused color with opacity: 1.

fix(fab): show close icon on hover, focused, activated

---

core/src/components/segment-button/segment-button.ios.scss
core/src/components/segment/test/custom/index.html

Issue Number: https://github.com/ionic-team/ionic/issues/20539
- Border radius on iOS now applies to indicator

fix(segment): border radius applies to indicator on ios

---

core/src/components/segment/segment.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20533
- Check to see if animated and ripple effect are enabled before adding ripple effect

fix(segment): do not show ripple effect if disabled via config

---

core/src/components.d.ts
core/src/components/item-sliding/item-sliding.tsx
core/src/components/item-sliding/readme.md

Links in item-sliding point to https://ionicframework.com/docs/list/List which is invalid
They should point to https://ionicframework.com/docs/api/list

docs(item-sliding): fix link to list

---

core/src/components/menu/menu.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20467
- Check for the existence of at least 1 presented modal, if there is one do not allow swipe gesture to proceed.

fix(menu): swipe gesture should not open menu when a modal is displayed

---

core/src/components/buttons/buttons.ios.scss
core/src/components/toolbar/test/spec/index.html

fix(button): reduce font size of icon only button in toolbar on iOS

---

core/src/components/tab-bar/test/spec/index.html
core/src/components/tab-button/tab-button.ios.scss
core/src/themes/ionic.theme.default.ios.scss

fix(tab-bar): update ios icon and label design to match native

---

core/src/components/checkbox/readme.md
core/src/components/checkbox/usage/react.md
core/src/components/datetime/readme.md
core/src/components/datetime/usage/react.md
core/src/components/input/readme.md
core/src/components/input/usage/react.md
core/src/components/radio/readme.md
core/src/components/radio/usage/react.md
core/src/components/range/readme.md
core/src/components/range/usage/react.md
core/src/components/searchbar/readme.md
core/src/components/searchbar/usage/react.md
core/src/components/select/readme.md
core/src/components/select/usage/react.md
core/src/components/textarea/readme.md
core/src/components/textarea/usage/react.md
core/src/components/toggle/readme.md
core/src/components/toggle/usage/react.md

docs(react): updating react input usages with binding examples

---

core/src/components/button/usage/react.md

problem: when running usage example code, icons does not appear inside buttons
added: import { star } from 'ionicons/icons';
changed: name='star' --> icon={star}
when running usage example code, icons does not appear inside buttons
Icons now appears correctly
- added: import { star } from 'ionicons/icons';
- changed: name='star' --> icon={star}-

Update react.md - Fix icons in usage for IonButton

---

core/src/components/action-sheet/readme.md
core/src/components/action-sheet/usage/react.md
core/src/components/button/readme.md
core/src/components/button/usage/react.md
core/src/components/card/readme.md
core/src/components/card/usage/react.md
core/src/components/chip/readme.md
core/src/components/chip/usage/react.md
core/src/components/fab/readme.md
core/src/components/fab/usage/react.md
core/src/components/icon/usage/react.md
core/src/components/item/readme.md
core/src/components/item/usage/react.md
core/src/components/reorder-group/readme.md
core/src/components/reorder-group/usage/react.md
core/src/components/reorder/readme.md
core/src/components/reorder/usage/react.md
core/src/components/segment-button/readme.md
core/src/components/segment-button/usage/react.md
core/src/components/segment/readme.md
core/src/components/segment/usage/react.md
core/src/components/skeleton-text/readme.md
core/src/components/skeleton-text/usage/react.md
core/src/components/tab-bar/readme.md
core/src/components/tab-bar/usage/react.md
core/src/components/tab-button/readme.md
core/src/components/tab-button/usage/react.md
core/src/components/tabs/readme.md
core/src/components/tabs/usage/react.md

React icon doc fixes

---

core/src/components/modal/modal.tsx
core/src/components/modal/test/spec/index.html
core/src/utils/overlays.ts

Issue Number: https://github.com/ionic-team/ionic/issues/20577
- Check to see if user provided custom animation when creating
- Cleaned up leave animation logic
- Added test

fix(modal): allow swipe to close animation to be overridden

---

core/src/components/segment-button/segment-button.scss
core/src/components/segment/segment.tsx
core/src/components/segment/test/basic/index.html

Issue Number: https://github.com/ionic-team/ionic/issues/20466
- Account for older versions of chrome where certain properties are not defined

fix(segment): segment functions properly on android 5

---

core/src/components/segment-button/readme.md
core/src/components/segment-button/usage/angular.md
core/src/components/segment-button/usage/javascript.md
core/src/components/segment-button/usage/react.md
core/src/components/segment-button/usage/vue.md

docs(segment-button): update usage for v5

---

core/src/components/refresher/refresher.tsx

After ion-refresher procs other fixed content shifts permamently
Issue Number: 17949
-
-
-
https://github.com/ionic-team/ionic/issues/17949

fix(refresher): ensure that translate is cleaned up to avoid stacking context

---

core/src/utils/menu-controller/index.ts

Having a document w/o checking if it is defined breaks SSR.
- Check to make sure `document !== "undefined"` before setting up back button event listener

fix(menu): allow ssr to work properly with hardware back button updates

---

core/README.md

update npm version on CDN example to latest

---

core/src/utils/animation/animation.ts

Issue Number: https://github.com/ionic-team/ionic/issues/20602
- Reset temp flags when calling `stop` method

fix(animation): reset all temporary flags when interrupting an animation

---

core/package.json
packages/angular-server/src/ionic-server-module.ts

Components in SSR env will not account for native framework components.
Bumps stencil core which allows us to exclude components from the ssr hydration
-
-
-

feat(): support excluding components from ssr

---

packages/angular-server/src/ionic-server-module.ts

fix(): exclude components from ssr

---

core/src/components/segment-button/segment-button.scss

Issue Number: https://github.com/ionic-team/ionic/issues/20648
- Removed pointer events from indicator background and indicator

fix(segment): iOS mode segment now works on older Android devices

---

core/src/components/segment/segment.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20678
- Removed the `preventDefault`

fix(segment): allow routerLink to work on segment buttons

---

angular/test/test-app/package.json

chore(): set @nguniversal/builders dependency to exact version

---

core/src/components/button/button.scss
core/src/components/button/test/states/index.html

Issue Number: fixes #20726
-
-
-

fix(button): allow overflow to be overridden by the CSS variable

---

core/src/components/item/item.ios.vars.scss

Issue Number: fixes #20653
-
-
-

fix(item): apply proper margin left for slotted icon in RTL

---

angular/src/index.ts

Types were not properly exported
- Types are exported

fix(angular): export Animation and Gesture related types

---

angular/src/directives/navigation/ion-router-outlet.ts
angular/src/index.ts

Issue Number: https://github.com/ionic-team/ionic/issues/20764
- Added `animation` to input array in angular

fix(angular): respect animation property for ion-router-outlet

---

packages/react/src/components/CreateAnimation.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20771
- Allowed arrays in certain types

fix(react): expose correct type for CreateAnimation

---

core/src/components/segment/readme.md

Issue Number: https://github.com/ionic-team/ionic/issues/20692
- Explained purpose of scrollable segments better

docs(segment): clarify usage of scrollable segments

---

core/src/components/modal/modal.ios.scss
core/src/components/modal/modal.md.scss
core/src/components/modal/modal.scss

Issue Number: https://github.com/ionic-team/ionic/issues/20800
- Only apply box shadow/backdrop opacity styles to the first modal
iOS Changes:
| `master` | branch |
| --------- | ------- |
| ![modal-ios-before](https://user-images.githubusercontent.com/2721089/76891736-e0262700-685f-11ea-970d-ea69a02c8977.gif) | ![modal-ios-after](https://user-images.githubusercontent.com/2721089/76891742-e4eadb00-685f-11ea-96a6-653371fbcec2.gif) |
MD changes:
| `master` | branch |
| --------- | ------- |
| ![modal-md-before](https://user-images.githubusercontent.com/2721089/76891797-f633e780-685f-11ea-8718-12a3e0c8181b.gif) | ![modal-md-after](https://user-images.githubusercontent.com/2721089/7 …

fix(modal): backdrop and box shadows no longer stack when opening multiple modals

---

core/src/components/list/list.ios.scss
core/src/components/list/list.ios.vars.scss
core/src/components/list/test/icons/index.html

In iOS, if you have a list with a border on the last item, followed by another list, the bottom border of the previous list is hidden due to the negative margin
| Before | After |
| ---| ---|
| ![before](https://user-images.githubusercontent.com/6577830/76871945-1e145280-6842-11ea-9652-fa1e92fa22cf.png) | ![after](https://user-images.githubusercontent.com/6577830/76871937-1c4a8f00-6842-11ea-9ef8-648b89bf7e27.png) |

fix(list): show bottom border on last item in a list followed by a list

---

core/src/components/segment-button/segment-button.md.scss
core/src/components/segment/segment.md.scss
core/src/components/segment/test/spec/index.html

Issue Number: https://github.com/ionic-team/ionic/issues/20566
- Scrollable buttons now have expandable widths

fix(segment): automatically expand width for scrollable segment buttons

---

core/src/components/modal/animations/ios.enter.ts
core/src/components/modal/animations/md.enter.ts
core/src/components/modal/modal.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20827
- Always add `show-modal` class regardless of custom animation or stock animation.

chore(): add show-modal in component not in animation

---

core/src/css/core.scss

Issue Number: https://github.com/ionic-team/ionic/issues/20799
- Fixed the selector to properly remove padding

fix(modal): properly remove safe area padding on card-modal

---

core/src/components/item-divider/item-divider.ios.scss
core/src/components/item-divider/item-divider.ios.vars.scss
core/src/components/item-divider/item-divider.md.scss
core/src/components/item-divider/item-divider.md.vars.scss
core/src/components/item-divider/item-divider.scss
core/src/components/item-divider/test/spec/e2e.ts
core/src/components/item-divider/test/spec/index.html
core/src/components/item-group/item-group.ios.scss
core/src/components/item-group/item-group.md.scss

Updates to match native iOS design

fix(item-divider): update design to match native iOS

---

core/src/utils/transition/ios.transition.ts

- use `ion-title.large-title` instead of `ion-title[size=large]` for the query

fix(title): improve reliability of large title ios nav transition

---

core/src/css/core.scss

Issue Number: https://github.com/ionic-team/ionic/issues/20851
- .ion-page now inherits border-radius

fix(modal): properly apply border radius on card-style modal

---

angular/src/index.ts
core/src/index.ts
packages/react/src/components/index.ts

exported nav transition functions for devs to use as overrides

chore(): properly export ionic page transition functions

---

core/src/components/input/input.tsx
core/src/components/textarea/textarea.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/20843
- Fixes event emission for input/textarea so scroll assist now recognizes/registers the inputs

fix(): scroll assists now recognizes inputs on inner pages and modals

---

core/src/components/modal/modal.ios.scss

CSS did not target `.modal-card` when setting dimensions
CSS now targets `.modal-card` when setting dimensions

fix(modal): properly target card modal for iPadOS styles

---

CHANGELOG.md
angular/package.json
core/package.json
core/src/components/modal/modal.ios.scss
docs/package.json
packages/angular-server/package.json
packages/react-router/package.json
packages/react/package.json

Release 5.0.7

---

.scripts/release.js

chore(): generate correct change log

---

core/api.txt
core/src/components/toast/readme.md
core/src/components/toast/toast.scss

Issue Number: https://github.com/ionic-team/ionic/issues/20727
- Changed the wrapping for the toast message from `pre-wrap` to `pre-line`.

feat(toast): add white-space variable for toast message

---

core/src/utils/transition/ios.transition.ts

Issue Number: https://github.com/ionic-team/ionic/issues/20948
- Account for tabs where there is no tab selected

fix(ios): account for nested tabs with page transition

---

core/src/utils/animation/animation-interface.ts
core/src/utils/animation/animation.ts

blocks https://github.com/ionic-team/ionic-docs/pull/1347
Issue Number: https://github.com/ionic-team/ionic/issues/20610
- Ionic Animations w/ CSS Animations will now only clean up stylesheets unless a user explicitly requests it. This should bring a moderate performance improvement when opening/closing multiple of the same component as stylesheets can be safely reused without them being removed.

feat(animation): add option to clean up old animation stylesheets

---

core/src/utils/transition/ios.transition.ts

Issue Number: https://github.com/ionic-team/ionic/issues/20912
- Properly account for nested/tabbed applications when animating the leaving view content

fix(ios): properly animate content when navigating from a tabbed page

---

core/src/utils/transition/md.transition.ts

Issue Number: https://github.com/ionic-team/ionic/issues/21056
- This is a behavior that should really change in the animation util, but it's potentially a breaking change, so this is the workaround for now.

fix(md): do not display blank screen when using MD page transition and swipe gesture

---

core/src/components/action-sheet/action-sheet.ios.scss
core/src/components/action-sheet/action-sheet.ios.vars.scss

Issue Number: https://github.com/ionic-team/ionic/issues/21082
- Added correct css var

fix(action-sheet): show correct cancel button background on dark mode

---

core/scripts/api-spec-generator.js

chore(api): update api generator to include parts in public API

---

core/src/components/loading/loading.tsx

Issue Number: https://github.com/ionic-team/ionic/issues/21107
- Added aria-hidden to ion-spinner since it is decorative

fix(loading): screen readers no longer incorrect announce spinner

---

core/api.txt
core/src/components/select/readme.md
core/src/components/select/select.tsx

https://github.com/ionic-team/ionic/issues/20916
Discussed with the team and we decided we did not want to expose this right now.
- Removed icon-inner part

feat(select): add parts support for placeholder, icon, text

---

core/src/components/button/button.tsx

chore(button): remove shadow parts

---

.github/ionic-issue-bot.yml

chore(): add extra lines for ionitron message

---

.github/ionic-issue-bot.yml

chore(): change contributing link text

---

core/src/components/menu/menu.tsx
core/src/utils/gesture/index.ts

blocks https://github.com/ionic-team/ionic-docs/pull/1331
Issue Number: https://github.com/ionic-team/ionic/issues/20588
- Menu gets and blurs any active element when swiping to open menu

feat(gesture): add support for blurring active inputs on gesture start

---

core/src/utils/watch-options.ts

Issue Number: https://github.com/ionic-team/ionic/issues/21063
- Adds a typeof check when configuration MutationObserver

fix(select): account for MutationObserver when performing SSR

---

core/src/utils/overlays.ts

Issue Number: https://github.com/ionic-team/ionic/issues/21092
- Removed pointer events before starting dismiss animation

fix(overlays): prevent accidental clicks when dismissing overlays

---

angular/src/directives/navigation/ion-tabs.ts
angular/test/test-app/e2e/src/tabs.e2e-spec.ts

Issue Number: https://github.com/ionic-team/ionic/issues/21074 https://github.com/ionic-team/ionic/issues/19943
- Check to see if active view is the same as root view in the tab

fix(angular): do not navigate to same tab if already active

---

core/src/components/refresher/readme.md
core/src/components/refresher/usage/angular.md
core/src/components/refresher/usage/javascript.md
core/src/components/refresher/usage/react.md
core/src/components/refresher/usage/vue.md

closes ionic-team/ionic-docs#1263
-
-
-

docs(refresher): update usage to correct ionicons 5 icon

---

core/src/utils/native/haptic.ts

Issue Number: https://github.com/ionic-team/ionic/issues/21148
- Add proper check to see if plugin is supported or not

fix(all): use proper undefined check when using Haptics plugin

---

core/src/components/select/readme.md
core/src/components/select/usage/angular.md
core/src/components/select/usage/javascript.md
core/src/components/select/usage/react.md
core/src/components/select/usage/vue.md

docs(select): update headings to display properly in the docs

---

core/src/components/back-button/back-button.tsx

chore(): remove undocumented back button parts

---

core/src/components/action-sheet/action-sheet.scss
core/src/components/alert/alert.scss
core/src/components/loading/loading.scss
core/src/components/modal/modal.scss
core/src/components/picker/picker.scss
core/src/components/popover/popover.scss
core/src/components/toast/toast.scss

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21199
- Removed outline from host elements

fix(all): overlay components no longer display outline when focused

---

core/src/utils/transition/md.transition.ts

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21056
- Forgot to remove `afterStyles`

fix(md): do not hide page when swipe gesture is cancelled

---

core/src/components/refresher/refresher.tsx
core/src/utils/helpers.ts

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21229
- Add util function that selects either element's shadow root or the element itself

fix(refresher): correctly select shadow root on older browsers

---

core/src/utils/overlays.ts

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21238
- Check to see if `keyboardClose = true` before focusing overlay

fix(overlays): respect keyboardClose property when opening overlays

---

core/src/components/header/header.tsx

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21221
- Add IntersectionObserver check. Should also help with SSR

fix(header): do not error on collapsable header on devices that do not support IntersectionObserve

---

core/src/components/toggle/toggle.tsx

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21080
- Added aria-hidden to inner native button so it is not announced.

fix(toggle): screen readers now announce toggle properly

---

core/src/components/refresher/refresher.tsx
core/src/components/refresher/refresher.utils.ts

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21220
- Add a fallback timer to the transition since transitions do not "end" when the target element has `display: none` (I.e. when switching to another tab)

fix(refresher): refresher completes even after switching to a new tab

---

core/src/components/action-sheet/readme.md
core/src/components/action-sheet/usage/angular.md
core/src/components/action-sheet/usage/javascript.md
core/src/components/action-sheet/usage/react.md
core/src/components/action-sheet/usage/stencil.md
core/src/components/action-sheet/usage/vue.md
core/src/components/alert/readme.md
core/src/components/alert/usage/angular.md
core/src/components/alert/usage/javascript.md
core/src/components/alert/usage/react.md
core/src/components/alert/usage/stencil.md
core/src/components/alert/usage/vue.md
core/src/components/loading/readme.md
core/src/components/loading/usage/angular.md
core/src/components/loading/usage/javascript.md
core/src/components/loading/usage/react.md
core/src/components/loading/usage/stencil.md
core/src/components/loading/usage/vue.md
core/src/components/modal/readme.md
core/src/components/modal/usage/angular.md
core/src/components/modal/usage/javascript.md
core/src/components/modal/usage/react.md
core/src/components/modal/usage/stencil.md
core/src/components/modal/usage/vue.md
core/src/components/popover/readme.md
core/src/components/popover/usage/angular.md
core/src/components/popover/usage/javascript.md
core/src/components/popover/usage/react.md
core/src/components/popover/usage/stencil.md
core/src/components/textarea/readme.md

docs(overlays): add docs on customization in scoped overlays

---

core/src/components/content/content.scss

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21066
- Change 100% to 100vh so shadow covers footer area

fix(ios): transition shadow properly sized regardless of footer

---

core/src/components/datetime/datetime-util.ts
core/src/components/datetime/test/basic/index.html

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21191
- Check for YYYY values

fix(datetime): ensure year-only values are not affected by timezone when parsing

---

core/src/components/menu-button/menu-button.tsx

Issue Number: fixes https://github.com/ionic-team/ionic/issues/21315
- Add proper label

fix(menu-button): screen readers now properly announce menu button

---

.github/ionic-issue-bot.yml

chore(): update bot template to properly close issues

---

.github/ionic-issue-bot.yml

Reverts ionic-team/ionic#21330

chore(): revert changes until bot is updated
