- js/angular/service/slideBoxDelegate.js
I think some people may use slide box like in your example and not put it in a ion-view as is should.
> Update slide box documentation

- CONTRIBUTING.md
It wasn't plainly obvious to me, a newcomer, that I wasn't supposed to create issues manually. I just skimmed CONTRIBUTING.md, not realizing the links would take me off github and onto your issue creation thingy.
> Suggestion on CONTRIBUTING

- js/angular/service/history.js
We were getting the bug found [here](http://forum.ionicframework.com/t/cannot-set-property-forwardviewid-of-undefined/15512/2) occasionally. We could not create a reliable steps to reproduce.
I don't fully understand what the code I have edited is doing, but I can see a logical error.
It starts with `for (x=0 ...)` then does `hist.stack[x - 1]` (depending on an `if`). Negative array indexes are not allowed, so I have surrounded that part in an if statement - I assume it's ok to not set anything to null if the `hist.stack` array is going to be empty.
> Fix "'Cannot set property 'forwardViewId' of undefined'"

- js/utils/tap.js
An attemp to fix issue #1934 #2619
Using node.cloneNode() to clone last focused input, it will make cloned looks really same with original, except the cloned is readonly.
> test(tap): use cloneNode() to clone focused input.

- js/angular/service/history.js
when we upgrade the latest ionic.  it throw error due to  call function on undefined object . so add short circuit can be more robust .
> fix call function on the undefined object 

- js/utils/platform.js
It seems to me like either this `addEventlistener` isn't necessary, or the one on line 413.
> chore(platform): remove duplicate event listener attachment

- scss/_grid.scss
I use this class variation all over my ionic projects, so wanted to throw it into a PR.
Paddingless grids can be really useful for columned flexbox layouts - e.g.
> Adds .row-no-padding for padding-less grid layouts

- scss/_bar.scss
iOS is ok
On android the title is not correctly centered vertically when setting a custom bar height (e.g $bar-height: 64px;)
> line height android is not updated when setting a custom bar height. 

- scss/ionicons/ionicons.scss
Upon just updating my ionic app to the version ``Ionic Package: nightly 1.0.0-rc.0-nightly-1120 (2015-03-05)``, watching sass didn't seem to cooperate.
Ref: https://github.com/kevincobain2000/listof-app/commit/29a5a6e728838290d6bbb322318d7582fa6451d1
**Before**
```
>>> Change detected to: www/lib/ionic/scss/ionicons/ionicons.scss
error www/lib/ionic/scss/ionicons/ionicons.scss (Line 8: Invalid US-ASCII character "\xE2")
```
**After**
```
>>> Change detected to: www/lib/ionic/scss/ionicons/ionicons.scss
write www/css/app.css
write www/css/app.css.map
```
----
PS: Watching Sass
```
sass --watch scss/ionic.app.scss:www/css/app.css
```
> Fix: invalid US-ASCII character \xE2, when watching sass

- js/utils/platform.js
`cordova plugin add org.apache.cordova.statusbar` is required to use the statusbar methods
> Document requirements for statusbar methods

- js/angular/directive/tab.js
Like the issue #1276 if you have some nested tabs, you select a sub-tab
item, and you will active some other siblings, because when tabCtrl add
every new $scope, it does't has a initial attr $scope.$tabSelected, so
every unselected item will read the $tabSelected from inherited $parent,
but if the parent-tab has been actived, the all of its sub-tabs
will read this true property in $scope.$tabSelected. So I think we
should initialize the property $scope.$tabSelected before invoking
tabsCtrl.add(), and every tab-item will has a 'false' status for a
initial $scope.$tabSelected.
> fix: initialize $scope.$tabSelected when nested tabs selected.

- js/angular/directive/refresher.js
- js/utils/platform.js
Updated exit() to exitApp() for documentation as the name of the function is exitApp.
> Update exit() to exitApp()

- scss/ionicons/_ionicons-font.scss
This is a minimalist short term fix before a complete solution be implemented as was discussed in #2599.
> let ionicons load for WP8

- js/angular/controller/scrollController.js
Variable `levelsClimbed` was not used at all and is now removed with the PR.
Local variable `levelsClimbed` in `scrollController#anchorScroll`
> Remove unused local variable `levelsClimbed`

- scss/_bar.scss
Nothing serious, just a small fix.
That was the only instance where not the provided mixin was used.
> Fixed mixin usage for bar elements

- js/angular/service/popup.js
These two commits, add functionality to $ionicPopup.prompt()
* defaultText per issue #1589
* maxLength per issue #4704
> Feature add for issue #1589 and issue #4704

- js/utils/gestures.js
Fix on-hold callback that are not fired on Galaxy S6 and some other android 5.1 devices
See   https://github.com/driftyco/ionic/issues/4672
Maybe related to https://forum.ionicframework.com/t/issues-with-on-hold-event-on-android/14051/17
and https://forum.ionicframework.com/t/ionic-view-android-gesture-issues/21807
> fix on-hold for Some devices

- scss/_range.scss
Firefox ignores "outline: none;" on ranges, so a dotted rectangle is shown around focused range sliders.
This change hides that rectangle to bring the appearance in line with other browsers.
> Hide Firefox's focus outline on range inputs

- bower.json
This is proposed for two reasons:
1. pulling the JS file into compliance with the [bower.json spec](https://github.com/bower/spec/blob/master/json.md) ("The entry-point files necessary to use your package. Only one file per filetype."). I am not sure about how to handle the fonts.
2. making the build process simpler for use with [bower-main](https://www.npmjs.com/package/bower-main) or [bower-installer](https://www.npmjs.com/package/bower-installer), as they can read the main section and grab only what is required.
Thanks for a great framework!
> update main section of bower.json with bundle

- js/utils/tap.js
On Windows Phone 8.1 and 10, Ionic (1.1.1) invokes click events twice in certain situations (caused by the tap handler). This patch filters out these events on the affected element types.
Note: I recognise that Windows Phone is not currently officially supported. However, this is literally the only issue I've encountered when targeting Windows Phone - which is pretty good going for an unsupported platform.
> Prevent click events from firing twice on Windows Phone

- js/angular/controller/infiniteScrollController.js
This issue #3871 discusses the problem but it was closed without a solution. 
The problem was that the maximum scroll height and the current height were both 0 which made it appear like the scroll was at the bottom.
> Bug fix for repeated infinite scroll calling after a state change with native scrolling

- js/angular/controller/tabsController.js
- js/angular/service/tabsDelegate.js
- test/unit/angular/directive/tabs.unit.js
Ability to hide the tabs bar from a controller:
```js
$scope.$on('$ionicView.afterEnter', function () {
$ionicTabsDelegate.$getByHandle('my-tab-bar').showBar(false);
});
$scope.$on('$ionicView.beforeLeave', function () {
$ionicTabsDelegate.$getByHandle('my-tab-bar').showBar(true);
});
```
> Add ionicTabs#showBar() method to set/get whether the tabs bar is shown

- scss/_type.scss
The variables **$link-color** and **$link-hover-color** are not used in the Ionic style.
When you write a link directly in a ion-content it takes the ugly default blue color of the browser.
I suggest to used this variables to make links more friendlier :art:.
> fix(): add default link color

- js/angular/controller/scrollController.js
Sometimes, I don't know why yet, `scrollView` is undefined and this line rises an Error. This commit fix this problem, but don't fix what makes the `scrollView` undefined.
> fix(scroll): prevent 'cannot read from undefined' exception

- scss/_grid.scss
I was missing two column sizes in my projects, so maybe it could also be useful for everyone.
I added `col-60` and `col-40` for two reasons:
- `col-60` and `col-40` can be combined together
- `col-60` can be used with `col-offset-20` to center an element
> Added two more choices of column size: 40% and 60%

- js/angular/service/popup.js
I think that it might be nice to have access to the popup scope in the `onTap` method. I needed to do that because my popup contained a `Do not show again` check box that was bound to the popup's scope and I could not access its value at all, because popup calls `$new()` on its scope option, if one is passed. You can basically see my code below:
```
$ionicPopup.show({
scope: $scope,
title: 'Text',
template: '\
<div class="item item-text-wrap">\
\
<span>Annoying message.</span>\
</div>\
\
<ion-checkbox ng-model="doNotShow">Do Not Show Again</ion-checkbox>',
buttons: [{
text: 'Cancel'
},
{
text: 'Continue',
onTap: function(e) {
// `this` is now the popup object
// and we can have access to its scope nicely
if(this.scope.doNotShow) {
rememberNotToShow();
}	
return true;
}
}]
});
```
> Access popup scope in the tap event handlers

- js/angular/controller/scrollController.js
`resize()` is a promise, and the `$destroy` event can fire before it finishes, nulling out `scrollView` which subsequently throws an exception because we are trying to call methods on `null`.
> don't throw exceptions if the view is destroyed before the view is resized

- js/views/scrollView.js
Related issue: https://github.com/driftyco/ionic/issues/4208
I finally had some time to take a look at this and it was literally a 1 line fix. =D
Mousewheel scrolling works perfectly on touch devices now on Chrome, and I haven't found any adverse effects yet in my testing.
I'm still seeing really slow scrolling on Firefox though, but that's probably another issue entirely.
> Added mousewheel support for touch devices

- js/angular/directive/keyboardAttach.js
My background:
- newest ionic
- newest ionic cordova keyboard plugin installed
- iOS 8 + iPhone 5C
- debugging through Safari Emulator
What happens:
When focusing on the input in `<ion-footer-bar keyboard-attach>`, I get a `TypeError: undefined is not an object (evaluating 'e.detail.keyboardHeight')` error.
This bugfix fixes it.
> Fix `e.detail.keyboardHeight` undefined error in keyboardAttach directive

- js/angular/controller/refresherController.js
Make `ionRefresher` play ball when `onRefresh` function returns a promise.
> Make ionRefresher promise-friendly

- scss/_scaffolding.scss
Hello,
I'm currently trying to add a subfooter with a tabs but the actual CSS doesn't implement this feature.
I can see that the .has-footer.has-tabs doing the same thing but the directive is actually not generating those classes.
> Add Subfooter with tabs support

- js/angular/directive/exposeAsideWhen.js
Fixes issue #3600 by ensuring that the side menu changes position only when $window.matchMedia changes from valid to invalid and vice versa, rather than listening to every resize event to trigger a change.
Since Ionic broadcasts a resize event on every popover and modal show action, this ensures that opening a popover located in the side-menu does not close the side menu, which is an issue that has been mentioned in the following ionic forum posts:
1) http://forum.ionicframework.com/t/menu-left-closes-when-popover-show/21476
2) http://forum.ionicframework.com/t/bug-side-menu-with-expose-aside-when-will-close-by-itself-when-a-modal-or-popover-comes-up/14532
3) http://forum.ionicframework.com/t/popover-in-side-menu-how-to-stop-side-menu-close/12277
> exposeAsideWhen directive bug fix

- js/utils/tap.js
(/^(select|option)$/i).test(e.target.tagName) repeats 3 times in the code so I thought it'd be better to export it in its own helper function isSelectOrOption(tagName)
> (/^(select|option)$/i).test(e.target.tagName) exported in separate function

- scss/_popover.scss
The margin was not updated when the width was changed resulting in the popover being offset to the right.
> Center Wide Popover on larger Viewports

- js/angular/service/popup.js
While reading the docs, I noticed that the example code was hard to read due to lack of spacing.
This spacing was also inconsistent with other examples, which are more readable; for example, from [popover](https://github.com/driftyco/ionic/blob/master/js/angular/service/popover.js#L40-L52):
Also, added a missing semicolon to [line 46](https://github.com/driftyco/ionic/blob/master/js/angular/service/popup.js#L46).
> docs(popup): increased js readability

- js/utils/keyboard.js
Focusing a keyboard element sets `keyboardActiveElement`. If you blur,
this will trigger `resetScrollView` appropriately.
If you focus a non-keyboard element (such as a checkbox), `keyboardActiveElement` is set to
null *before* `keyboardHide` is called, so `resetScrollView` is not
triggered.
Mitigate this by keeping track of the last focused element to reset the
scroll view.
> fix(scrollView): reset scroll view when focusing non-keyboard element

- scss/_checkbox.scss
This contains a fix to issue: https://github.com/driftyco/ionic/issues/3900
Replicated issue in codepen: http://codepen.io/clemmakesapps/pen/WvOPmK
Demonstrated css fix in codepen: http://codepen.io/clemmakesapps/pen/YXQgqx
> Fix for ion checkbox right alignment issue on android

- scss/_form.scss
I have a select statement with long option names that get cut off in the traditional inline select, so I added in support for item-stacked-label and selects that put the select on a new line.
> Added support for .item-stacked-label and select statements

- js/angular/directive/slideBox.js
By default, because Ionic is using ngAnimate, when you use ngRepeat, angular will not destroy the DOM of the element straight away, but it will first add the css class: ng-leave to give the user a chance to set animation when deleting an item from the array.
This commit disables $animate for the slideBox element.
> fix(slidebox): removing an item breaks slidebox

- scss/_button-bar.scss
When having only one button in a buttonbar the left border had no radius
> Fixed border-radius when only one button exists in a button-bar

- js/angular/service/backdrop.js
This is to add a rootScope broadcast from the backdrop service. This is really useful in hybrid apps involving native views. E.g. native maps or camera.
Generally any time the backdrop is shown the developers wants this to be on top of everything and nothing below it to be clickable or receive input, this generally means sending a cordova message to native components telling them something is on top. This broadcast allows that to be easily implemented once for whenever the backdrop appears. Ionic already has something similar for modals.
> Add a broadcast for when the backdrop is shown or hidden

- js/utils/tap.js
It is a quick fix for enable video navigation for wp8 platform.
I'm not really sure if it is the right approach for this kind of problem.
But it's doing the job. Tested on Lumia 635.
> fix(video): add video native controls for wp8 platform

- js/angular/directive/content.js
The preLink function is using the compile attr param not the preLink $attr param for delegate-handle and locking attributes. This causes problems when using ion-content in an ng-repeat. The delegate-handle is properly set using the preLink attributes in other directives like ion-scroll. This does not address the issue of interpolation for delegate-handle but allows an additional directive to do so.
> Fix preLink function using compile attributes

- js/utils/poly.js
I know IE9 support isn't a priority, but initializing empty arrays for `ionic.CSS.TRANSITION will keep IE9 from choking when it gets here and finds an undefined variable:
```
var isWebkit = ionic.CSS.TRANSITION.indexOf('webkit') > -1;
```
Adding TRANSFORM too, for the same reason, although it wasn't causing any issues.
> Setup empty arrays before evaluating ionic.CSS

- js/angular/directive/exposeAsideWhen.js
This fix is link to the commit 8187367 (@msalcala11)
The resize handler was not triggered often enough, when the view is resize
(screen rotation for instance) the resize handler wasn't trigger.
Refs #4898
> fix(exposeWhenAside): trigger resize when screen dimension change

- ionic/components/icon/icon.ts
the symptom was described in issue https://github.com/driftyco/ionic/issues/4955
- when user view item detail page the first time, ion-icon is created and dom element is updated with first icon name
- when user view item detail page second time with a different icon name, the same dom element (with first icon name) is now added with the new icon name. The updated dom is still there because the page is cached.
The page cache behavior is described in nav-controller.ts:
* By default, pages are cached and left in the DOM if they are navigated away
* from but still in the navigation stack (the exiting page on a `push()` for
* example).  They are destroyed when removed from the navigation stack (on
* [pop()](#pop) or [setRoot()](#setRoot)).
add a ngOnDestroy function in ion-item directive which …
> add ngOnDestroy to ion-icon and remove added css class

- ionic/components/slides/slides.ts
moving the pull request from ionic2 to ionic:2.0
original pull request in ionic2 repo: https://github.com/driftyco/ionic2/pull/786
delay the Swiper initialization with setTimeout, in order to let Swiper find the DOM created with ion-slide ngFor
> v2: wrap swiper init code in set timeout

- package.js
This problem is described in #4766 
After this is fixed, it should be possible to publish the package to Atmosphere, the Meteor package repository.
> Icon fonts need to be Meteor assets

- ionic/components/menu/menu.ts
- ionic/components/menu/test/disable-swipe/index.ts
- ionic/components/menu/test/disable-swipe/main.html
- ionic/components/menu/test/disable-swipe/page1.html
1)
add swipeEnabled input to menu to set default swipeable of side menu
<ion-menu [content]="content" id="rightMenu" side="right" swipeEnabled="false">
2)
add swipeEnable() api to enable disable particular side menu swipeable
this.app.getComponent('rightMenu').swipeEnable(this.rightMenuSwipeEnabled);
> v2: enable / disable swipe gesture to open sidemenu

- ionic/components/searchbar/searchbar.ts
argument name did not match the variable name inside the function, it's changed from 'ev' to match the name 'event' of the variable used inside the function.
> ionic 2: fix(Searchbar):stopInput() argument name typo

- LICENSE
According to http://www.copyright.gov/circs/circ01.pdf (See screenshot of relevant section below) , listing the first year of publication in the copyright is necessary
This pull request reverts it back to 2013 (As it was in the commit when the MIT license was introduced cc38f014c366128 )
> Fix initial copyright year

- ionic/platform/storage/storage.ts
following the comments by @manucorporat in PR https://github.com/driftyco/ionic/pull/5091
changed the type to optional
> v2: mark parameters optional

- ionic/platform/storage/storage.ts
The current implementation pases a promise to JSON.parse() which is fundamentally wrong.
Also, JSON.parse() is caught without rethrowing the exception which makes very difficult to handle failure cases.
My fix allows this:
```ts
storage.getJson("key").then(json => {
// handle success case, json is a valid js object.
}).catch(error => {
// this is called if JSON or db access fails!
});
```
Note, please checkout https://github.com/driftyco/ionic/pull/4995
as well.
> ionic 2: fix(Storage): getJson() implementation

- js/utils/platform.js
> Resolve trigger.io - forge.js conflict

- ionic/platform/storage/local-storage.ts
- ionic/platform/storage/storage.ts
fixing the error found by @phavre because of the StorageEngine constructor changes:
https://github.com/driftyco/ionic/commit/07953672f53c793828f29d81101b46d6b88dfafa#commitcomment-15599683
> remove the error throwing in storage engine constructor

- js/angular/directive/slideBox.js
according to the angular api document, `$element` should be the first argument
> fix (ionSlideBox): only disable ngAnimate for slidebox and its children

- js/angular/directive/slides.js
When a `<ion-slide-page>` directive is destroyed, the slider is not updated.
This PR fix the issue related in #5120 adding a destroy event in the directive.
> Fix ionSlidePage destroy

- ionic/components/menu/menu-gestures.ts
The menu curently opens and closes at any angle of slide action. In case the menu has enough items
to create a vertical scrollbar it makes it impossible for the user the scroll vertically without
affecting the slide behavior of the menu. This fix restrains the menu open/close to a specific
angle.
#5180
> feat(menu): restrain menu slide start to a specific angle

- CHANGELOG.md
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting
https://github.com/manucorporat/ionic/blob/2.0/CHANGELOG.md
> v2: code and syntax highlighting in markdown

- README.md
Folder name is different in doc from the original folder name in 
change **js/angular-ui-router/**  to  **js/angular-ui/**
Thanks
> Folder name is different in doc from the original folder name in js/angular-ui/

- ionic/components/alert/alert.ios.scss
- ionic/components/alert/alert.md.scss
- ionic/components/alert/alert.scss
- ionic/components/alert/alert.ts
- ionic/components/alert/test/basic/index.ts
- ionic/components/alert/test/basic/main.html
Fixes this issue: https://github.com/driftyco/ionic/issues/5152
Now:
The `margin-right: -1px` is used to hide the `border-right: 1px` when the buttons are displayed in a column.
NOTE: I have not tested it, because i don't know how to get it working directly from the ionic repo, BUT i tested it manually in the chrome's debugger... so it should work.
@brandyscarney
> v2: Fixes #5152 Alert View with long button text

- ionic/components/alert/alert.ios.scss
Native iOS 9 UIAlertView on the left, ionic 2.0alpha53 on the right!
Before fix:
After fix:
^^ it is almost perfect now!!
Please review https://github.com/driftyco/ionic/pull/5268 as well!
> v2: Pixel perfect iOS Alert

- ionic/components/alert/alert.ts
- ionic/components/alert/test/basic/index.ts
- ionic/components/alert/test/basic/main.html
the option name is disableClickBackdropToDismiss
this is the sample usage:
let alert = Alert.create({
disableClickBackdropToDismiss: true
});
alert.setTitle('Disabled Backdrop Click'),
alert.setSubTitle('Subtitle'),
alert.setMessage('This is an alert message.'),
alert.addButton({
text: 'Cancel',
role: 'cancel',
handler: () => {
console.log('Confirm Cancel');
}
});
this.nav.present(alert);
> add an option to create alert which cannot be dismissed by clicking backdrop

- ionic/components/action-sheet/action-sheet.ios.scss
- ionic/components/alert/alert.ios.scss
- ionic/components/app/app.ios.scss
- ionic/components/button/button.ios.scss
- ionic/components/item/item.ios.scss
- ionic/components/list/list.ios.scss
- ionic/components/searchbar/searchbar.ios.scss
- ionic/components/tabs/tabs.ios.scss
- ionic/components/toolbar/toolbar.ios.scss
- ionic/globals.core.scss
I have found rendering artifacts that can be fixed changing the value to `0.5px`.
This commit does not change it, but I allows developers to configure it.
> feat: hairlines width can be configured with a sass variable

- ionic/components/action-sheet/action-sheet.ios.scss
- ionic/components/alert/alert.ios.scss
- ionic/components/button/button.ios.scss
- ionic/components/button/button.md.scss
- ionic/components/button/button.scss
- ionic/components/button/button.ts
- ionic/components/button/test/full/main.html
- ionic/components/item/item.ios.scss
- ionic/components/item/item.md.scss
- ionic/components/searchbar/searchbar.ios.scss
- ionic/themes/default.ios.scss
closes #5292
it also fixes a font kerning issue.
^^ safari
^^ safari
> refactor(button): refactors button's css to avoid using flex

- ionic/util/dom.ts
If requestAnimationFrame does not run within the `window` context, it causes `TypeError: Illegal invocation` every time that Ionic tries to use it. 
The change I made binds the `requestAnimationFrame` to the `window` so it will always runs from the correct context. 
Noticed it while trying to run Ionic 2 with Meteor 1.3-beta - for some reason (which I did not found yet..), `requestAnimationFrame` runs from another context instead of `window`.
> Fixed a bug caused by requestAnimationFrame did not run on the correct context

- js/angular/directive/slides.js
Hi ionic team.
I've got an issue today with `ionSlides`, using it in a `ui-view`. When leaving the view containing the slider, by loading another one into the `ui-view`, the `update` method of `ionSlides` was triggered and executed `_this.__slider.update()` in spite of the "falsy-check" just before. Indeed, the instance of the slider is kept even after the slider is destroyed (because of $scope `$destroy` event).
A simple PR to nullify the reference after the slider is destroyed.
In order for this piece of code to work properly:
this.update = function() {
$timeout(function() {
if (!_this.__slider) {
return;
}
// not called if the reference is properly nullified
_this.__slider.update();
[...]
> fix(nullRef): nullify reference to the destroyed slider

- ionic/components/button/button.scss
- ionic/components/item/item-sliding.scss
- ionic/components/item/test/sliding/main.html
closes #5352 
This is the magic css:
```css
ion-item-sliding:not([horizontal]) {
.button.button-icon-left {
font-size: 14px;
.button-inner {
flex-direction: column;
}
ion-icon {
padding-left: 0 !important;
padding-right: 0 !important;
padding-bottom: 0.3em;
}
}
}
```
It is very complete and "intelligent":
- If ion-item-sliding has a "horizontal" attribute, we displaying the options horizontally (like it is done currently)
- If button does not have an icon, it doesn't apply the vertical alignment.
- If button only has only an icon, it doesn't apply the vertical alignment.
> feat(ion-item-sliding): style icons on top of text in an option button

- ionic/components/button/button.ios.scss
- ionic/components/button/button.md.scss
- ionic/components/button/button.scss
- ionic/components/nav/test/basic/index.ts
- ionic/components/nav/test/insert-views/index.ts
- ionic/components/navbar/navbar.ts
- ionic/components/toolbar/test/scenarios/main.html
- ionic/components/toolbar/toolbar-button.scss
- ionic/components/toolbar/toolbar.ios.scss
- ionic/components/toolbar/toolbar.md.scss
- ionic/components/toolbar/toolbar.ts
- Bar button text is aligned with the `ion-title`:
- Go back button uses the inner span as flexbox.
- `<a button>` elements now can be used as bar buttons!!
- Regression fix: block/full buttons, now there are `display: block`, so margin is collapsed again
Snapshot:
http://ionic-snapshot-go.appspot.com/ionic2/snapshots/qqi/b2z/chrome_400x800
> fix(button): bar-button uses inner span as flexbox

- ionic/components/toolbar/toolbar.ios.scss
- ionic/platform/cordova.ios.scss
> fix(toolbar): fixes title aligment when cordova iOS style is applied

- ionic/platform/storage/sql.ts
Documentation claimed the remove() method took two parameters: key and value, whereas in reality it only takes one: the key to be removed, as one would expect.
> Corrected documented signature for remove() method

- ionic/decorators/app.ts
the config link was relative to the page rather than the domain. I think the added '/' should fix that.
> Update to decorators docs (bad link)

- ionic/decorators/app.ts
I have added a prodMode attribute to the @App decorator to be able to enable the Angular2 production mode.
@App({
template: '<ion-nav [root]="rootPage"></ion-nav>',
config: {},
prodMode: [true/false]
})
if true => enableProdMode is called before bootstrapping the app
> prodMode attribute in the @App decorator

- tooling/generators/page/index.js
Addresses https://github.com/driftyco/ionic/issues/5467
https://github.com/driftyco/ionic-cli/issues/773.
Adds the message: 
```
conference$ ionic g page test
√ Create app/pages/test/test.html
√ Create app/pages/test/test.js
√ Create app/pages/test/test.scss
Don't forget to add an import for test.scss in app/themes/app.core.scss:
@import ../pages/test/test.scss
```
Yes, we're assuming that app/themes/app.core.scss is where their styles are located, but I think it's fair to assume conventions when using generators.
@leonsas @adamdbradley look ok?
> feat(generators): add Sass import reminder to page generator

- ionic/components/slides/slides.ts
My first ever PR. Definitely need some guidance here. Will docs and tests need updating before this is merged?  This event may be useful for [parallax effects](http://www.joshmorony.com/how-to-create-a-directive-in-ionic-2-parallax-header/) in slides, where scroll events won't work.
> feat(slides): Added move event onSlideMove

- js/angular/directive/input.js
Fixes typo in `ion-input` closing tag.
> (docs): close ion-input tag correctly

- ionic/platform/storage/sql.ts
The v2 docs for SqlStorage, the sample isn't correct, this PR fix the string on the query example.
> docs(sqlStorage): string error in query example

- ionic/components/searchbar/searchbar.ts
Search bar won't hide the cancel button for android.
- Hide search-bar cancel button for android also
- Added `hideCancelButton` to example. 
**Fixes**: # Use `hideCancelButton` for Android as well 
Hide cancel button for android as well...
The example should help ng1 guys... I tried snake-case way too long.
> fix(searchbar): Hide cancle button for android

- demos/action-sheet/main.html
Added padding on the action sheet as described in issue #453
- padding attribute on </ion-content>
-
-
2.x
**Fixes**: #453 partially
this is for issue #453
> docs(demos): padding on action content

- ionic/components/content/content.ts
A function was renamed in 91df5f97eef9ed1d261e6642c2d9ab7e8cc4063c and made this example outdated
> docs(content): fix ion-content scroll event listener example

- ionic/components/tabs/tabs.ios.scss
- ionic/components/tabs/tabs.scss
- badge position adjusted
- icon/text position adjusted
Left: native (whatsapp)
**Center: after my PR**
Right: current ionic version
> fix(tabs): improves tabs style for iOS

- ionic/util/test/util.spec.ts
- ionic/util/util.ts
ignores empty query param in getQueryString
- filter out query params with no `=` character
**Fixes**: #5562
> fix(util): ignore empty query param in getQueryString

- ionic/util/keyboard.ts
Just a typo :)
**Fixes**: none
Typo that break color highlight on the website
> Typo on docs (v2)

- js/utils/events.js
> corrected break tag in events.js documentation

- ionic/components/alert/alert.ts
Minor docs spelling issue.
- change `chacked` to `checked`
> little typo, chacked -> checked

- ionic/components/infinite-scroll/infinite-scroll.ts
after the data of an already scrolled `ion-list` is reset, the value `_highestY` in [infinite-scroll.ts#L171](https://github.com/driftyco/ionic/blob/2.0/ionic/components/infinite-scroll/infinite-scroll.ts#L171) prevents infinite scrolling.
- added method to reset _highestY on demand (e.g. after receiving new data)
**Fixes**: #5677
> added method to reset _highestY

- ionic/platform/storage/sql.ts
StorageSql engine's get() method must not return the item but the value of the item.
@adamdbradley sorry about that :(
> fixes regression in my last refactor(Storage) PR.

- demos/events/main.html
- demos/id/main.html
- demos/menu/main.html
- ionic/components/menu/test/basic/main.html
- ionic/components/menu/test/disable-swipe/main.html
- ionic/components/menu/test/enable-disable/main.html
- ionic/components/menu/test/multiple/main.html
- ionic/components/menu/test/overlay/main.html
- ionic/components/menu/test/push/main.html
- ionic/components/menu/test/reveal/main.html
- ionic/components/nav/nav-controller.ts
- ionic/components/nav/nav.ts
- ionic/components/nav/test/nested/index.ts
`@Input()` has to be used in the angular component itself, not subclasses.
This PR also updates the documentation and demos.
**Fixes**: #5653
> fix(Nav): fixes swipeBackEnabled as attribute

- ionic/components/action-sheet/action-sheet.ios.scss
In safari the action-sheet buttons have a non-0 margin (not sure why). This PR normalizes how the buttons are rendered in safari and chrome.
It SHOULD NOT affect how the action-sheet looks in Chrome.
**Fixes**: #5828
> fix(action-sheet): action sheet button shortens when activated in Safari

- ionic/components/content/content.ts
This PR fixes the js error TypeError: Cannot read property 'removeEventListener'
- Having ion-refresher / ion-infinite-scroll on a page
- Navigate to another page
- Come back
**Fixes**: #5760
> fix(ion-infinite-scroll): Fix error leaving page

- js/angular/service/ionicConfig.js
Prevents view flashes on tab changes in Android
When android changes tabs, there was slight delay between the view
becoming the cached view and the new tab becoming the active view.
Similar to how iOS's tab swap animation works, passing in opacity
prevents the leaving view from disappearing too early, allowing
for a much smoother animation.
**Ionic Version**: 1.2.4
**Fixes**: #3907
> fix(view): prevent flicker when changing tabs on android

- js/angular/directive/refresher.js
Typo in documentation
`deprecated` instead of `depreicated`.
> Fix small typo in docblock

- ionic/components/slides/swiper-widget.d.ts
-
-
-
**Fixes**: #
Fix for tsc with 'noImplicitAny' option
> lacks return-type annotation, implicitly has an 'any' return type

- ionic/components/segment/segment.wp.scss
Inconsistent styling in Windows Phone when an ion-segment is used outside of a toolbar
- Let active-segment styles outside of a toolbar work on Windows Phone.  Matches behavior of iOS and Android
**Fixes**: #5994
In the iOS and Android styles the segment-activated class lives directly under segment-button.  However in the Windows Phone version these styles live only under toolbar, causing the styles to not be applied properly if the ion-segment is used outside of a toolbar.
> segment.wp: display active style outside toolbar

- ionic/components/app/structure.scss
- ionic/components/content/content.scss
- ionic/components/content/content.ts
- ionic/components/nav/test/basic/index.ts
- ionic/transitions/transition-ios.ts
More info here: https://github.com/driftyco/ionic/issues/5987#issuecomment-203509190
- Adds `<ion-fixed>`
- Changes $z-index-backdrop from 1 to 2
**Fixes**: #5987
closes #5987
> feat(ion-content): adds <ion-fixed> for non-scrollable page content

- js/angular/service/history.js
to avoid user double-page quick navigation.
> Fix #4369: reduce cache clearance timeout

- ionic/util/events.ts
Typo in docs
- Add an 's'
**Fixes**: #
The class name should be 'Events' instead of 'Event'
> Typo in docs

- ionic/components/virtual-scroll/virtual-scroll.ts
Fix Docs
wrong closing tag
-
-
-
**Fixes**: #
> update virtual-scroll docs

- ionic/components/button/button.ts
Clarifies that the `color` attribute is meant to be used only with predefined colors.
- Update the docs for the button's color attribute.
**Fixes**: #
It's not clear that the `color` attribute is meant to be used only with the predefined colors _(i.e. the ones from the `$colors` list in `app.variables.scss`)_. The users expect that the attribute can also be used with color values like `red` or `#FF0000` which is not supported. More details are available in [this forum post](https://forum.ionicframework.com/t/changing-button-color-or-icon-dynamically/37675/19).
> Clarify the purpose of the color attribute

- ionic/components/checkbox/checkbox.ts
Enables forms with ion-checkboxes to be submitted as normal forms (i.e. with the enter key)
Add attribute 'type="button"' to <button> tag. The missing attribute caused forms with
ion-checkboxes to not be submitted as a normal form
> fix(checkbox): add 'type="button"' to <button> tag

- ionic/components/input/input.ts
clearInput doc example had a typo, this fixes that typo
-
-
-
**Fixes**: #
clearInput property was on ion-item element instead of ion-input element in example
> Updated ion-input doc typo

- js/angular/service/history.js
solves issue #3750
Adds a method `$ionicHistory.removeBackView()` which removes the cached view, element, scope, and rejigs the history. I'm already using this in production in various use-cases. 
This predominantly solves the issue where in most angular applications you can use `$state.go('app.foo', { location: 'replace' })` except in ionic, the history is managed manually - this is the solution.
Would be good to have it part of the core!
I'm working on the method `$ionicHistory.removeFromHistory(stateName/id)` which we also need for our app - and the ionic community would also benefit from this going forward. Keep an eye out.
> [ionicHistory] add method to remove the back view

- js/angular/controller/spinnerController.js
When there are multiple instances of `<ion-spinner icon="android"></ion-spinner>`, and one of them is removed from the DOM, all others stop animating.
The issue is that the animation function uses `this` in a function that is not called as a constructor, which is therefore shared over all instances of the animation. This results in all of them stopping when `anim.stop = true` is called.
This change creates a new object as the state for each instance of the animation, instead of sharing the state.
Existing issues:
https://github.com/driftyco/ionic/issues/5156
https://github.com/driftyco/ionic/issues/4819
https://github.com/driftyco/ionic/pull/4827 (does not seem to solve the underlying issue)
Codepen demonstrating the issue: http://codepen.io/dennishn/pen/OMNybR (from #4819)
Affects at …
> Fix ion-spinner (android) stopping when another instance is removed

- js/angular/service/history.js
Swipe to go back attribute not being read because sometimes the view is
inside a second pane.
I have seen it countless times on the forums and in my own projects. I have noticed that the can-swipe-back="false" attribute doesn't actually stop the swiping action leading multiple people to have to not use the feature including myself for a while. I found that the element (ele) is actually a parent of the ion-view that *should* be targeted. This extra code I added should find the actual ion-view if it didn't pass the previous two tests, and then check the attribute.
> + Swipe to go back fix

- js/angular/directive/slides.js
According to the Swiper documentation, the pagination parameter can receive a string with a selector or directly the html element.
Passing directly the html element ensures that the pagination works with multiple sliders. Resolves #4837.
> fix(slides): Update slides(swiper) pagination for multiple use

- ionic/components/input/native-input.ts
- package.json
- tslint.json
New rule to prevent nested function declarations in our codebase that cause an issue with strict mode.
- add tslint-eslint-rules: https://www.npmjs.com/package/tslint-eslint-rules
- add nested function declarations rule
-
> rule to prevent nested function declaration

- ionic/components/action-sheet/action-sheet.ios.scss
- ionic/components/action-sheet/action-sheet.md.scss
- ionic/components/action-sheet/action-sheet.ts
- ionic/components/action-sheet/action-sheet.wp.scss
- ionic/components/select/select.ts
- ionic/components/select/test/single-value/index.ts
- ionic/components/select/test/single-value/main.html
- Adds a new "selected" role to `action-sheet`
- Adds an "interface" attribute to `ion-select`
- Allows using a action-sheet as interface for a ion-select
> feat(select): using action sheet as an ion-select interface

- ionic/components/app/normalize.scss
- ionic/components/item/test/buttons/main.html
If a button contains `<p>`, `<h1>` or any exotic element, the button is not properly activated if the user taps under such elements. This feels very unresponsive and laggy.
I am not sure making `<ion-label>` pointer-events: none is the correct solution, but this bug is real and it should be fixed somehow.
> fix(button): buttons don't get activated when ion-label contains some elements

- js/angular/service/modal.js
Don't show click-block-div unnecessarily on remove().
See [this comment and the following ones](https://github.com/driftyco/ionic/issues/4383#issuecomment-209810320)
It's just a small and reasonable change to `js/angular/service/modal.js`. 
**Fixes**: #4383
> fix(modal): Don't show click-block-div unnecessarily on remove()

- ionic/components/app/app.ts
- ionic/decorators/app.ts
Create a method to access the global app injector which contains references the bootstrapped providers
This feature simply sets a reference to the injector on the IonicApp class, so it can be referenced
by other components. This is sometimes necessary when injecting providers that depend on other
providers. This issue is discussed here
https://github.com/angular/angular/issues/4112#issuecomment-139381970, and Brandon Roberts' solution
of an appInjector() method has been used to solve a variety of dependency injection conflicts.
Unfortunately, it requires access to Angular's bootstrap() method, which Ionic handles in the @App
decorator. This fix will create a reference to the appInjector(), so it can be references from
within Ionic components.
closes #5973
> feat(confg): create reference to global app injector 

- tooling/generators/page/page.tmpl.ts
`nav` variable declaration redundancy
`this.nav = nav` is already present due to the `public nav: NavController` declaration, having it in the constructor as well is redundant
**Fixes**: #
> Removed redundant this.nav declaration

- CHANGELOG.md
Added a note about the removed parameter `platformName` of `platform.versions()`.
**Fixes**: #
> Added a note about platform.versions().

- ionic/platform/platform.ts
Updates the outdated API-docs for `platform.versions()`.
- Removed the `platformName` parameter from the API-docs for `platform.versions()`.
- Updated the information about the return value of `platform.versions()`.
**Fixes**: #
> Updated the API-docs for platform.versions().

- ionic/components/icon/icon.ts
Updates the link to the Ionicons _(according to commit: https://github.com/driftyco/ionic-site/commit/e75930d9324f4ab97d6e335ebca1ae009e60610d)_.
- Update of the Ionicons link in the `ion-icon` docs.
**Fixes**: #
> docs(ionicons): move to top level

- ionic/components/content/content.ts
Fixed the link to the Refresher component from the Content component.
> Fix link to Refresher docs

- ionic/components/button/button.ts
Allows setting the color and style button attributes at once and ensures that they are visualized as they are set in the code _(as shown in [this plunker demo](http://plnkr.co/edit/ycfx4XdBf2uYXtguwulQ?p=preview))_.
- Correctly resets the style to its default value.
- Adds array support to the color attribute which is also supported via multiple attributes.
- Correctly resets the color/style classes when updating color and style attributes.
**Fixes**: #6202
> Fixes #6202: allows setting the color and style button attributes at once.

- js/angular/controller/navViewController.js
- js/angular/directive/view.js
- js/angular/service/history.js
- js/angular/service/viewSwitcher.js
- test/html/lifecycle/TestEight.html
- test/html/lifecycle/TestFive.html
- test/html/lifecycle/TestFour.html
- test/html/lifecycle/TestNine.html
- test/html/lifecycle/TestOne.html
- test/html/lifecycle/TestSeven.html
- test/html/lifecycle/TestSix.html
- test/html/lifecycle/TestThree.html
- test/html/lifecycle/TestTwo.html
- test/html/lifecycle/testnine-debug/SimpleOne.html
- test/html/lifecycle/testnine-debug/SimpleTwo.html
- test/unit/angular/directive/navView.unit.js
> fix(lifecycle): lifecycle events fire reliably from the correct scope

- js/utils/tap.js
Unexplainably I have found element.dataset.tapDisabled to be unreliable. This
has been tested on iOS. element.getAttribute is also faster then
element.dataset so might as well just use it all the time.
Here is an example of what I was seeing. I can get this to happen by navigating around the app in the iOS simulator or on an iOS device. Note that this does not happen on the first load. Only after navigating around. The issue shows itself in a LeafletJS map where clicks are not passed to the map.
```
isElementTapDisabled: function(ele) {
if (ele && ele.nodeType === 1) {
var element = ele;
while (element) {
console.log('isElementTapDisabled looking at', element);
console.log('element has dataset', element.dataset);
console.log('element has dataset' + JSON.stringify(element.dataset, null, …
```
> fix(tap) use element.getAttribute rather then trying element.dataset first

- scss/_bar.scss
Just fix the `background-image` color gradient of the `bar-footer` when used with `bar-balanced` class.
No changes, just a typo fix.
**Ionic Version**: 1.3
**Fixes**: #6422
> fix(footer bar): fix a typo in footer bar styles using balanced class

- js/angular/controller/sideMenuController.js
Please see comments on this pull request 
https://github.com/driftyco/ionic/pull/2988
> Fix for issue 2521

- scss/_bar.scss
When you customize the SASS variables: `$bar-footer-height`, `$bar-subheader-height`, `$bar-subfooter-height`. If you set a title inside subheader, footer, and subfooter bar:
```html
<ion-header-bar class="bar-stable">
<h1 class="title">Header</h1>
</ion-header-bar>
<ion-header-bar class="bar-subheader bar-energized">
<h1 class="title">SubHeader</h1>
</ion-header-bar>
<ion-footer-bar class="bar-stable">
<h1 class="title">Footer</h1>
</ion-footer-bar>
<ion-footer-bar class="bar-energized bar-subfooter">
<h1 class="title">SubFooter</h1>
</ion-footer-bar>
```
The title have a wrong height!
ScreenShot to illustrate the problem:
> fix(bar): set correct title bar height

- ionic/components/radio/radio-button.ts
- ionic/components/radio/test/radio.spec.ts
- Radio Buttons throws errors on dismissal when it's not part of a radio group.
- check if the button is part of a group before trying to remove.
**Ionic Version**: 2.0.0-beta.6
**Fixes**: https://github.com/driftyco/ionic/issues/6466
> feat(radio-button) fix thrown error on dismiss solves #6466

- ionic/components/list/list.ts
Typo fix
Changed closeItems() name
> closeItems() typo

- ionic/components/picker/picker.ts
Under certain circustances the number of DOM children is not the same than the number of options,
this causes an exception by access to undefined during iteration.
This issue can be reproduced randomly, dragging a picker column in order to give it some inertia and then closing the modal while the items are still moving.
```
platform-browser.umd.js:962 EXCEPTION: TypeError: Cannot read property 'style' of undefinedBrowserDomAdapter.logError @ platform-browser.umd.js:962BrowserDomAdapter.logGroup @ platform-browser.umd.js:972ExceptionHandler.call @ core.umd.js:3696(anonymous function) @ core.umd.js:8951schedulerFn @ core.umd.js:6007SafeSubscriber.__tryOrUnsub @ Rx.js:10855SafeSubscriber.next @ Rx.js:10810Subscriber._next @ Rx.js:10766Subscriber.next @ Rx.js:10743Subject._finalNext @ …
```
> fix(picker): number of dom children != number of options

- js/angular/directive/slides.js
Correction in the documentation.
-
-
-
**Fixes**: #
Correction in the documentation of usage. The indexes were being accessed in data instead of data.slider (or $scope.slider).
> Correction of documentation.

- ionic/util/dom.ts
This will resolve issue  where unit tests bomb when ['bind'] is called on an undefined, non-polyfilled ```requestAnimationFrame``` function.
- Return the polyfill version of RAF when the native version is not found
**Fixes**: #6417 6417
When in a headless environment RAF may not be defined so we need to return the polyfilled version rather than letting the undefined function be called.
> Return Polyfill RAF When Native is Undefined

- scss/_variables.scss
Makes it possible to configure button style variables `$button-default-border` and `$button-default-active-border` from a user sass file. 
Just like all other ionic sass variables.
added `!default` flag to `$button-default-border` and `$button-default-active-border`
**Ionic Version**: 1.3.1
**Related to**: #5576
> Make button border style configurable

- README.md
- src/components/menu/menu.ts
Creates opened/closed events after a menu opens/closes. This allows code to watch for when the menu state changes. One example of this being useful is when using the native Cordova Maps Plugin, which needs to be set to "unclickable" whenever a DOM element is floating above it (otherwise, the map continues to get clicked in the background). 
- add opened/closed EventEmitters on Menu
2.0
**Fixes**: #
Fixes #5163
> EventEmitters on Menu open/close

- src/components/label/label.ts
There's a minor link broken, when I have time I may navigate all the docs searching for broken links like this.
- Minor doc link fix
> docs(label): minor link fix

- src/components/datetime/datetime.ts
datetime docs
documentation fix
**Fixes**: N/A
> [docs] Correct sentence related to the ngModel sets the value

- src/components/alert/alert.ts
Added clarifications about the `placeholder` and `label` input options, related to: https://forum.ionicframework.com/t/alerts-property-label-not-work/53335
- Added clarifications about the `placeholder` and `label` input options.
> Added clarifications about input options.

- src/components/slides/swiper-widget.d.ts
Build failures with TypeScript's `noImplicitAny` option enabled
- return value types for the slideNext, slidePrev, and slideTo functions of Swiper
> type return for Swiper slide functions

- src/components.core.scss
- src/components/action-sheet/action-sheet.ts
- src/components/action-sheet/test/basic/e2e.ts
- src/components/alert/alert.ts
- src/components/alert/alert.wp.scss
- src/components/backdrop/backdrop.scss
- src/components/backdrop/backdrop.ts
- src/components/loading/loading.scss
- src/components/loading/loading.ts
- src/components/menu/menu.scss
- src/components/menu/menu.ts
- src/components/modal/modal.scss
- src/components/modal/modal.ts
- src/components/modal/test/basic/index.ts
- src/components/picker/picker.ts
- src/components/popover/popover.scss
- src/components/popover/popover.ts
- src/components/scroll/scroll.scss
- src/components/toast/toast.ts
- src/config/directives.ts
- src/util/util.scss
New `ion-backdrop` component can prevent background scrolling fixing: #6656 in Alerts, Popover, actionsheet, loading...
- Replace all `<div class="backdrop" ...>` with `<ion-backdrop>`
- `MenuBackdrop` is not longed needed
- We don't longer have to listen for `touchmove` events!! performant solution
- Backdrop injects a class at `body` level in order to prevent scrolling:  
```css
body.stop-scroll scroll-content {
overflow-y: hidden;
overflow-x: hidden;
}
``` 
**Bonus:** this code was repeated all over the place, now it is much more compact.
Before:
```html
<div (click)="bdClick()" tappable disable-activated class="backdrop" role="presentation"></div>
```
After:
```html
<ion-backdrop (click)="bdClick()"></ion-backdrop>
```
**Fixes**: #6656
> fix(ion-backdrop): new ion-backdrop can prevent background scrolling

- src/platform/platform.ts
"hardware" is mistyped "hardward"
- Correct that. That's all.
> docs(platform): correct a minor typo of "hardware"

- src/components/range/range.ios.scss
- src/components/range/range.md.scss
- src/components/range/range.ts
- src/components/range/test/basic/page1.html
This PR allows range to be disabled + iOS style has been improved:
iOS before:
iOS after:
Disable state iOS:
Disable state MD:
> feat(range): range can be disabled

- src/components/app/app.ts
- src/components/app/test/app.spec.ts
- src/config/bootstrap.ts
Changes to the click block logic and tests.  We A) make sure the click block is enabled if in the config (is this typically in the config?) and then clean up of `setEnabled` logic.
> fix(click-block): fix for the click block logic

- src/components/range/range.ios.scss
- src/components/range/range.md.scss
Chore to fix `gulp validate` that wasn't working in 2.0 branch
> chore(range): sass validates now

- src/components/item/item-sliding-gesture.ts
- src/components/item/item-sliding.scss
- src/components/item/item-sliding.ts
- src/components/item/item.ts
- src/components/item/test/sliding/index.ts
- src/components/item/test/sliding/main.html
- src/components/list/list.ts
- src/config/directives.ts
Implements: feature(ion-item-sliding): Allow item also to swipe from left to right #5073
it should be 100% back compatible.
- adds an optional `side` attribute to `ion-item-options`
- I aggressively refactored the sliding code to try to make it more readable and simple.
- moved logic to external functions so they can be unit tested easily
This may cause new issues. I haven't tested the code for side effects, so please don't merge just yet.
Feel free to pull it locally and try it.
Example code:
```html
<ion-item-sliding #item>
<ion-item>Two-way sliding</ion-item>
<ion-item-options side="right">
<button primary (click)="archive(item)">Archive</button>
<button danger (click)="del(item)">Delete</button>
</ion-item-options>
<ion-item-options side="left">
<button secondary …
```
> feat(item): two-way sliding of items

- src/components/range/range.ts
closes #6802
- Easy fix, listening for window.mouseup event instead of body.mouseup
> fix(range): keeps sliding after releasing mouse outside the window

- gulpfile.js
- package.json
- scripts/npm/package.json
This pr will add es2015 modules to the publishing process.
- Update gulp to create es2015 modules in esm directory for publishing
- Update gulp-babel to use 6 so that we can rely on babel 6 transforms and presets
> chore(build): change gulp prepublish process to create es2015 modules

- src/components/menu/menu-gestures.ts
- src/components/menu/menu.ts
Fixes #5511
^ it works as expected now
It also prevents scrolling while swiping the menu
**Fixes**: #5511
> fix(menu): swiping menu distinguishes between opening and closing direction

- src/components/toast/toast.ts
- src/config/bootstrap.ts
If you open two or more toasts at a time, that have a duration, they will now all close when their duration runs out instead of being stuck open.
- Remove code from ionViewDidEnter and put inside ngAfterViewInit
**Fixes**: #6657
> fix(toast): close toasts when two or more are open

- src/components/nav/nav-controller.ts
Currently the documentation says, that you can pass the animation property. But which values are accepted is missing.
- updated the documentation
-
-
**Fixes**: #
…alues
> updated documentation of NavOptions.animation property

- js/angular/directive/navBar.js
There is a strange `</table>` tag in the documentation.
I think it is a typo.
Remove it.
> docs(nav-bar): Remove strange </table></br> tags

- src/components/nav/nav-controller.ts
The PR adds 700ms of padding to the duration if the keyboard is open.  Typically on iOS, it takes about ~550ms of time to close the keyboard on my iPhone 6S.  Once the transition is complete, the click block is disabled per the existing app logic.  Basically, this has minimal to none effect on Android.  On iOS, where it takes a bit to dismiss the keyboard, this prevents another transition from happening until the transition is complete, which will take ~550ms longer than usual when the keyboard is open.
> fix(navigation): keep the click block up longer if the keyboard is open

- src/components/toast/toast.ts
Toast will now be enabled even when other toasts, or other components that have `fireOtherLifecycleEvents` set to false, have been opened before.
- move `this.enable` to `ngAfterViewInit`
**Ionic Version**: 2.0.0
> fix(toast): toast will now be enabled

- src/components/virtual-scroll/virtual-scroll.ts
Change `#item` to `let item` syntax for the VirtualScroll component. This changed in beta7 due to the angular2 update to RC1. See https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#angular-update-to-200-rc1
**Ionic Version**: 2.0.0-beta.8
> Update virtual-scroll docs to use let syntax

- src/components/popover/popover.ts
- src/components/popover/test/basic/main.html
Popovers on elements that are positioned left:0 are now shown relative to the element instead of in the middle of the viewport.
- Get targetTop and targetLeft even when targetDim.left/targetDim.top is 0
- Update test to include popovers on buttons that are positioned left:0 and right:0
**Fixes**: #6896
> fix(popover): allow target element to be positioned at left:0

- src/components/menu/menu-types.ts
- src/components/menu/menu.scss
Using overlay type menu on side="right" causes the menu to be shown in the middle of the screen when rotating the device.
- Change CSS for right menu and logic for translateX
**Fixes**: #6740
> fix(Menu): fix right overlay menu when rotating device

- js/angular/directive/refresher.js
If the scroll.refreshComplete message is broadcast and the DOM has not been rendered, the refresher will throw.  We had a standard refresh that could be set by a pull, or simply a view activation. 
Check to see of the scrollView is present before calling a pullToRefresh.
**Fixes**: #
> Checks if scrollView is present

- src/components/input/native-input.ts
- src/components/nav/nav-controller.ts
- src/components/nav/nav.ts
- src/components/tabs/tab.ts
- src/components/tabs/test/advanced/index.ts
- src/components/tabs/test/advanced/tabs.html
https://github.com/driftyco/ionic/issues/6099
>No problem @manucorporat . I was able to reproduce it simply by switching the application to a tabs setup. I used the supplied tabs.ts and tabs.html. It seems that the swipeBackEnabled works when not using tabs, but is overridden when using tabs. Perhaps because tabs have their own navigation stack?
http://plnkr.co/edit/fB3VofAwyYoFcEF009Co
Note: I was using mobile safari on an iPhone to test this plunker. Let me know if there is a way around this for now. I can't seem to find one. I tried adding swipeBackEnabled to the actual tabs component and that didn't seem to work either." 
^ reported by @iaguilera14 (https://github.com/driftyco/ionic/issues/6099#issuecomment-226223015)
- swipeBackEnabled input work in `<ion-tab>`  
```html
<ion-tab …
```
> fix(tabs): swipeBackEnabled works with tabs as expected

- demos/item-sliding/index.ts
- demos/item-sliding/main.html
- scripts/demos/index.template.dev.html
- src/components/item/item-reorder-gesture.ts
- src/components/item/item-reorder.scss
- src/components/item/item-reorder.ts
- src/components/item/item-sliding-gesture.ts
- src/components/item/item-sliding.scss
- src/components/item/item-sliding.ts
- src/components/item/item.ts
- src/components/item/test/reorder/index.ts
- src/components/item/test/reorder/main.html
- src/components/list/list.ts
- src/config/directives.ts
- src/index.ts
- src/util/util.ts
- New `ion-list` attribute: `sliding`. Sliding can be disabled by setting:
`<ion-list sliding="false">`
- New `ItemBase` class for common methods between `Item` and `ItemSliding`
- SlidingItem animation should be slower
**Fixes**: #6845 (and more...)
> Sliding Items work with list reorder

- src/components/modal/modal.ts
Documentation fix - the Modal dialog documentation previously used the Page decorator. This was updated in 73635f393974dc6c44f69cf7814d22243f80a5c5 to use the Component decorator instead, but the Page import still exists. This commit removes it.
- Remove unused import in documentation
**Fixes**: #
The Page decorator usage was removed in 73635f393974dc6c44f69cf7814d22243f80a5c5, but the import is still there.
> (docs) Modal - remove unused Page component import

- src/components/nav/nav.ts
`ion-nav` docs refer to the deprecated Page decorator. The example code is already correct.
- Remove Page component reference in docs
> (docs) Nav - remove Page component reference

- src/util/feature-detect.ts
Currently `backdrop-filter` is only supported by Safari and it allows web developers to implement awesome background blur effects like a native iOS app
> feat(feature-detect): detects if backdrop-filter is supported

- src/components/button/test/basic/main.html
- src/components/content/content.ios.scss
https://github.com/driftyco/ionic/issues/5275
- New `no-bounce` attribute to disable over-scroll bouncing
**Fixes**: #5275
> feat(content): iOS only scroll bounce

- js/angular/directive/scroll.js
The onScrollComplete event is missing from ionScroll directive. This is very handy when using this directive with the paging option enabled. All the infrastructure to handle this event was done, just reusing it for this directive.
-
-
-
**Fixes**: #
> adding scroll-complete event to ionScroll directive

- demos/toast/index.ts
- src/components/alert/test/basic/index.ts
- src/components/alert/test/dismiss/index.ts
- src/components/datetime/datetime.ts
- src/components/loading/loading.ts
- src/components/loading/test/basic/index.ts
- src/components/modal/modal.ts
- src/components/modal/test/basic/index.ts
- src/components/nav/view-controller.ts
- src/components/popover/popover.ts
- src/components/select/select.ts
- src/components/toast/test/basic/index.ts
- src/components/toast/toast.ts
https://github.com/driftyco/ionic/issues/6702
- Adds a new onWillDismiss callback that is called before the animation begins. (it has the same signature than onDismiss)
**Fixes**: #6702
> feat(viewcontroller): adds onWillDismiss callback (0 delay)

- src/components/button/button.ios.scss
> fix(button): outline buttons does not have hairline borders in iOS

- src/components/tabs/tabs.ios.scss
Aligns content of ionTabs to the center
- add `  justify-content: center;` to tabs.ios.scss
**Ionic Version**: 1.x / 2.x 
2.x
> fix(ionTabs): center tabbar content

- src/components/slides/slides.ts
Slides that are on the first page of an app getting stuck and not being able to be swiped about 70% of the time
- add 300ms delays to two timeouts
> fix(): slides not rendering correctly

- src/components/loading/loading-component.ts
This resolves dismiss getting fired twice if the component is dismissed before the duration is complete.
- if there is a duration clear the timeout if the component is dismissed before the timeout has completed.
**Fixes**: #7197
> fix(loading): clear timeout if dismissed before timeout is done

- src/components/nav/nav-controller.ts
My IDE warned me that the parameter `insertPages` wasn't defined in JSDocs.
> docs(nav-controller): fix insertPages jsdocs

- js/views/scrollViewNative.js
Memory leak on scrollNative
Remove resetScrollView
**Fixes**: #4746
PS. I had created pull request about this before (#4807) but it was closed without any comments what-so-ever. While I understand that maintaining large open-source projects takes lots of time and resources, it is not very encouraging.
> fix(scroll): memory leak on document event listener

- src/components/picker/picker-component.ts
Fixes issue where picker options are stacked on iOS8
- added -webkit- vendor property for transform and transform duration
**Fixes**: #7319
> Fixed iOS 8 picker display issue

- src/util/datetime-util.ts
- src/util/test/datetime-util.spec.ts
Changes `twoDigit()` `threeDigit()` and `fourDigit()` utility functions in `datetime-util.ts` to strip provided number of negative signs.
2.0.0-beta-10
**Fixes**: #7358
> Fixed datetime util ISO string to handle negative timezone offsets

- src/animations/animation.ts
fix allowing to create `Animation` providing string element selector
- change the order of `if` blocks in `element` method as strings has also `length` and so the second block was never executed
> fix(animation): ele as string selector

- src/components/select/select.ts
Added ability set selected text like md-selected-text
Example:
**before**:
**after**:
```html
<ion-select [(ngModel)]="currency" [selectedText]="selectedText()">
<ion-option *ngFor="let cur of currencies;" [value]="cur">
{{cur.symbol}} ({{cur.code}}) {{cur.name}}
</ion-option>
</ion-select>
```
```ts
public selectedText() {
return this.currency.symbol;
}
```
//cc @adamdbradley @brandyscarney
> feat(select): add ability set selected text

- src/components/virtual-scroll/virtual-scroll.ts
- adds a note about not using ion-img outside of virtual scroll
> docs(): note about ion-img outside virtualscroll

- README.md
Current link in readme is broken.
Link to correct location of CONTRIBUTING.md
-
-
-
> docs(readme): fix link to CONTRIBUTING.md

- CHANGELOG.md
Angular RC5 just has been released, this cause the original install command to fail. I have added the required (RC4) version to the command.
- Update Install instructions
2.x
**Fixes**: #7647
> Update Ionic Beta 11 install instructions

- src/config/providers.ts
- src/gestures/ionic-gesture-config.ts
- src/gestures/test/ionic-gesture-config.spec.ts
This PR is tested (on iPhone 6s) and lets scrolling work with hammer gestures again.  swipe, pan, press, tap all work again and the app can scroll as needed.  Multi-touch gestures in the default config were "blocking" scrolling.
closes #6897
> fix(gestures): fixes scroll issue with hammer config

- src/components/toggle/toggle.ts
Ensures that disabled toggles doe not fire events or show animation.
Also check if toggle is disabled before firing the event and animating the toggle. 
**2.0.0-beta.32**
**Fixes**: #7559
> Ensures that disabled toggles doe not fire events or show animation.

- src/components/toolbar/toolbar.ts
> Fix path (nav->navbar) typo in docs

- src/components/popover/popover.ts
Was referring to using the NavController to present a popover.
- Updated wording to reference an instance of the PopoverController.
2.x
**Fixes**: #
n/a
> Updated instructions for presenting a popover.

- CHANGELOG.md
Upon testing the `npm install` command, npm install Ionic Beta 10 and `angular/forms 0.3.0`. `angular/forms 0.3.0` required angular RC-5, so a Missing Peer warning was issued.
I think it would be better to have them exact like the others
- Add exact beta 11 version to `ionic-angular`
- Add exact 0.2.0 version `@angular/forms`
> Update Changelog to use exact Ionic versions

- src/components/loading/loading.ts
- src/components/nav/view-controller.ts
The need to recreate loading dialogs to change their content
-setContent function
**Fixes**: #6103
> feat(loading): add setContent function

- src/components/virtual-scroll/virtual-scroll.ts
Clarifies the importance of providing approxItemHeight for virtual scroll
- Improve docs for approxItemHeight
- Add console.warn when aproxItemHeight is default value
**Fixes**: #
> Improve docs and add console.warn for approxItemHeight

- src/components/item/item-reorder.ts
Reorder template was using the wrong icon.
Change from menu icon to reorder icon.
2.x
**Fixes**: #
Reorder template is currently using the menu icon instead of reorder icon. I updated the template to use proper reorder icon.
> Update to use reorder icon

- src/components/item/item-reorder.scss
This fixes layers being made for each list item even when a user is not actually reordering when using reorder. This change means that `will-change` only gets applied when the user is actually reordering the list, and as soon as the user has "dropped" the item the layers get removed. Previous behavior created a layer for every list item even when a user was not reordering the list, causing high memory usage and bad scrolling perf. This has been tested on chrome 52 on desktop (the latest stable), and a Nexus 7 running Android 6.0.1 (completely stock).
The video below is of me using a reordered list with this fix with the layer viewer option in chrome dev tools on. 
[will-change-fix.zip](https://github.com/driftyco/ionic/files/412652/will-change-fix.zip)
> perf(item): apply will-change only when list is active

- src/components/item/item-sliding.ts
Fix type in `ion-sliding-item` API doc.
ionSiwpe -> ionSwipe
> Fix typo in Sliding Item Docs

- js/angular/service/modal.js
Currently, the modal-open class is removed when you remove a modal, even if there are still other modals visible. This PR will retain the modal-open class until there are no more visible modals.
- Check length of modalStack before removing the modal-open class
> Removes the 'modal-open' class from body only when there are no more modals shown

- src/components/menu/menu-gestures.ts
- src/components/menu/menu.ts
- src/gestures/slide-gesture.ts
- src/navigation/swipe-back.ts
#7629 
#8001
- setOpen() is noop while actively swiping 
- Menu swipe gesture is not captured if the menu is actively moving (being animated)
fixes #7629 #8001
> fix(menu): open/close race condition

- src/components/app/app.scss
Path to themes from src/components/app/app.scss is currently incorrect
-Changes filepath to correctly point to themes folder
**Fixes**: #
> fix(app): corected paths to theme from src/components/app/app.scss

- src/components/button/button.md.scss
- src/components/tap-click/ripple.ts
Before:
After:
- Pure transform-based animation without touching `left/top` css properties.
> perf(ripple): md ripple effect does not affect layout

- src/components/typography/typography.ts
The fore color of the button is being overwritten when it's applied on an a tag because of the 2 directives (text and button) that are setting the "color".
- Exclude ion-button on a selector
**Fixes**: #8249
> fix(ion-button): ion-button on a tag should be excluded

- src/components/content/content.ios.scss
$text-ios-color does not works
**Fixes**: #
> fix: $text-ios-color does not works

- src/components/fab/fab.ts
there's a typo about fab button placement
- change description from ```top``` to ```bottom``` to match the code
-
-
**Fixes**: #
> docs(FabContainer): fix typo of ion-fab placement in comment

- src/components/item/item.ts
A simple typo that made me stare at it for a while to realise it was a typo!
-
-
-
**Fixes**: #
Should be "display it naturally", not "display is naturally" ?
> docs(item component) fix typo

- src/components/spinner/spinner.ts
To assign color in ion-spinner
```<ion-spinner color="danger"></ion-spinner>```
Result in html
```
<ion-spinner color="danger" class="spinner-undefined-danger spinner-ios" ng-reflect-color="danger">
```
Expected
```
<ion-spinner color="danger" class="spinner-ios-danger spinner-ios" ng-reflect-color="danger">
```
See mode is how **undefined** in the concatenation of the **class**
**Fixes**: #8598
> fix(spinner): add input mode fix #8598

- src/components/icon/icon.ts
- src/components/icon/test/basic/main.html
- src/components/tabs/test/basic/app-module.ts
#8435
Before:  (red failing cases)
After:
> fix(icon): isActive="false" with ios mode

- src/components/backdrop/backdrop.ts
- src/components/content/content.ts
- src/components/menu/menu.scss
- src/components/menu/menu.ts
- src/components/menu/test/push/main.html
- src/components/tabs/tabs.ts
- src/transitions/page-transition.ts
Before fix:
footer and part of the content is hidden.
After:
fixes #8504
> fix(menu): menu's content is resized properly

- src/components/list/list.ios.scss
- src/components/list/test/inset/main.html
Fixes #8412 
After fix:
@brandyscarney can you review it?!
> fix(list): consecutive inset lists with headers

- src/components/searchbar/searchbar.ios.scss
- src/components/searchbar/searchbar.scss
- src/components/searchbar/searchbar.ts
- src/components/searchbar/test/basic/main.html
- src/components/searchbar/test/nav/app-module.ts
- src/components/searchbar/test/nav/modal.html
- src/components/searchbar/test/nav/search.html
DO NOT SQUASH (each commit is a bug fix)
**Fixes**:
#7010 
#6023
#7484
#7744
#7527
> feat(searchbar): searchbar animations can be disabled

- src/components/navbar/navbar.ts
This adjusts the text of the navbar documentation to fix a typo.
- fix a typo
> docs(navbar): fix a typo

- scripts/npm/package.json
This change will move all of Ionic's dependencies into peer dependencies.
Ionic acts as a plugin for Angular. Both Ionic and Angular are direct dependencies of the source project. According to the definition of when to use peerDependencies from NPM our code fits into this.
https://nodejs.org/en/blog/npm/peer-dependencies/
- Move Ionic's dependencies to peerDependencies in the package.json file
> chore(): move ionic's dependencies into peerDependencies.

- src/navigation/nav-controller-base.ts
- src/navigation/nav-util.ts
- src/navigation/test/nav-controller.spec.ts
- src/navigation/view-controller.ts
- src/transitions/transition.ts
- src/util/mock-providers.ts
Right now, the NavController does the canLeave/canEnter challenge only when the navigation change requires a transition.
1. Remove from stack
2. Evaluate if a transition is required
- if yes: canLeave/canEnter challenge -> continue transition
- if no: we are done
This logic leads to an important bug when canLeave or canEnter returns `false` (i.e. the transition has been cancelled) but the pages have been already removed from the stack.
This PR introduces a new logic (that of course passes all the current unit tests):
1. Evaluate if a transition is required
- if yes: canLeave/canEnter challenge -> continue
- if no: continue
2. Remove from stack
3. Evaluate if a transition is required (cached value from step one)
- if yes: transition -> done!
- if no: done
This way if canLeave returns …
> fix(nav): ionViewCanLeave does not break navigation

- src/components/tabs/tabs.ts
tabBadgeStyle input is not setting the correct class on the ion-badge. It is adding `badge-danger` rather than `badge-ios-danger`
- remove ngClss and use color input instead
**Fixes**: #8317
> fix(tabs) ion-badge not being given the proper color

- src/components/loading/loading-component.ts
- src/components/modal/modal-component.ts
- src/components/modal/test/basic/app-module.ts
- src/components/popover/popover-component.ts
- src/navigation/nav-controller-base.ts
- src/navigation/view-controller.ts
> fix(nav): ionViewDidLoad is called in modals

- src/components/popover/popover.ios.scss
Fixes the flipped arrow on iOS, when the popover opens above an element.
- Fixed class selector for popover-bottom
**Fixes**: #8419
> fix(popover): flipped arrow on iOS

- src/components/input/input.ios.scss
Issue that the width property is invalid ex;
`width: calc(100% - 8px - 0);` which is not a valid calc value.
- Add a part of the calculation using SASS, Add the margin-left and margin right using SASS and then subtract the total using the css calc function. Compiled down would be `calc(100% - 8px);` in case you have a left margin of 10px and right of 20px it would be `calc(100% - 30px);`
**Fixes**: #7388
> fix(input): text input width calculation

- src/components/fab/fab.scss
When setting the `$fab-mini-size` to be larger than normal, the buttons inside the `ion-fab-list` are not positioned correctly.
- Remove the horizontal margin from fab buttons in a top or bottom list
- Remove the vertical margin from fab buttons in a left or right list
> fix(fab): center fab list for larger buttons

- src/config/config.ts
In the config documentation there isn't explicit documentation on how to set the global mode for an application. I added the mode config property to the list of config properties.
- Adds 'mode' to list of config properties in config documentation
**Ionic Version**: 2.0.0-beta.8 and greater
**Fixes**: Issue mentioned here: https://github.com/driftyco/ionic/issues/5312
> Add mode config property to config readme

- src/navigation/view-controller.ts
Fix an  infinite loop on ViewController.dismiss(): on an android device (Nexus 7, android 5.1.1) dismissing a PopOver without this patch causes an infinite loop.
- replace deep copy with shallow copy, avoiding the possibility of an infinite loop due to recursive data structures
> Fix infinite loop (hang) in viewcontroller dismiss

- demos/src/button/page.html
Delete examples usage Fab (old) already exists in  [Fab Button](http://ionic-site-staging.herokuapp.com/docs/v2/components/#fabs)
**Fixes**: #
> chore(demos): delete examples Fab(old form) in component Button

- src/components/virtual-scroll/virtual-scroll.ts
this.approxItemHeight is undefined when update(true) is called first
see https://github.com/driftyco/ionic/issues/8311
- define this.approxItemHeight to default 40px before do this.update(true)
**Ionic Version**: 2.1.0
**Fixes**: https://github.com/driftyco/ionic/issues/8311
> Virtual Scroll fix: this.approxItemHeight is undefined when update(true) is called first

- src/components/spinner/spinner.ts
The current Ionic2 Documentation states that you select the spinner via CSS using `ionic-spinner svg`.
This is no longer the case per Mike: https://forum.ionicframework.com/t/ion-spinner-color/46324/6
- Just a simple CSS selector update
**Fixes**: #
> Changed CSS selector for ion-spinner

- src/components/button/button.ts
Boolean value inputs are documented to be a string.
- Change input docs to the correct type.
> docs(button): correct input types

- src/navigation/nav-controller.ts
ionViewCanLeave & ionViewCanEnter are mistakenly documented as ionCanViewLeave & ionCanViewEnter
Fix em.
**Ionic Version**:  2.x docs / api
**Fixes**: #
> Fix CanViews to ViewCans in Nav Guard section

- src/components/app/app.ts
- src/components/content/content.scss
- src/components/content/content.ts
- src/components/tap-click/activator.ts
- src/components/tap-click/tap-click.ts
- src/platform/platform-registry.ts
- src/util/ui-event-manager.ts
- refactors code using UIEventManager
- improved performance by using passive event listeners
- fixes isScrolling()
- click tolerance has been increased to match native behavior
- click is immediately prevented if the content is scrolled.
- Opening an alert SHOULD block scrolling in android, iOS WKWebview and desktop (safari and chrome).
- Opening an alert SHOULD NOT cause any kind of flickering in any platform.
- Click events SHOULD NOT be dispatched in buttons if the content is scrolled (even 1px).
- Buttons SHOULD NOT activate if scrolling immediately
> fix(tapclick): several improvements

- js/views/scrollViewNative.js
Incorrect ion-content height when the native keyboard appears for the first time. It happens to other users as well, as you can see in the related issue.
- Adjust the __originalContainerHeight in ionic.views.ScrollNative after first keyboard show in ionic.requestAnimationFrame callback.
**Fixes**: #6715
> Fix ion-content height after first keyboard show

- src/components/searchbar/searchbar.md.scss
Search bar don't show the cancel button for android.
Update css selector to match with searchbar html 
2.0.0-rc.1
**Fixes**: #
#8403
> fix(searchbar-md-cancel): fix always hide button

- src/components/refresher/refresher.scss
When using a Refresher, the content scroller gets a `transition: all;`. When using a header or footer on the same page, the content scroller's `margin-top` and/or `margin-bottom` are set. These margins are then animated in by the `transition` while they should render instantly. This margin animation is sometimes visible when a page gets loaded.
- Change the `transition` to only animate `transform`, as this is the only property that requires animating for the refresher.
> fix(refresher): only animate transform property

- js/utils/tap.js
When selecting the contentEditable element, the first tap does not focus the element.
Add additional clause to the if statement to exclude contentEditable from the `preventDefault()`
1.3.1
**Fixes**: #8741
> Exclude contentEditable from preventDefault on tapMouseDown()

- src/components/menu/menu.ts
- src/components/modal/modal-component.ts
- src/components/modal/test/basic/app-module.ts
- src/components/nav/test/basic/app-module.ts
- src/components/picker/picker-component.ts
- src/components/popover/popover-component.ts
- src/components/tabs/test/lifecyles/app-module.ts
- src/navigation/nav-controller-base.ts
- src/navigation/view-controller.ts
- Adds public willLoad lifecycle event: It will be called once BEFORE first change detection (i.e. before ngOnInit, ngAfterViewinit... )
- didLoad is called AFTER the component and his children has been fully initialized.
> fix(nav): adds public willLoad lifecycle event

- src/directives.ts
`ToolbarItem` was not actually exported which caused an NGC error. It is now exported properly.
- export `ToolbarItem`
> fix(): add missing export

- src/components/toolbar/toolbar-title.ts
This resolves a spelling mistake in the toolbar-title.ts docs
- Spelling mistake
**Fixes**: #
A basic spelling change in the toolbar-title.ts documentation (heder to header)
> Fix - Update spelling in toolbar-title.ts docs

- src/components/action-sheet/action-sheet.md.scss
- src/components/action-sheet/action-sheet.wp.scss
TOP: Native Material Design
BOTTOM: Ionic
BEFORE:
AFTER:
Actionsheet without header didn't follow the spec, now it does:
BEFORE:
AFTER:
fixes #8663
> fix(action-sheet): follows MD spec

- src/components/item/item-sliding-gesture.ts
- src/components/item/item-sliding.ts
Same technique used in this PR: https://github.com/driftyco/ionic/pull/8986
This PR should improves dramatically the performance in low end devices:
BEFORE:
AFTER:
**Fixes**: #
- Using new NativeRafDebouncer
- Events are not zone wrapped unless strictly necessary
> perf(item): improves performance of sliding item

- src/components/menu/menu-gestures.ts
- src/components/menu/menu.ts
> perf(menu): avoiding change detection when unneeded

- src/components/typography/typography.ts
The fore color of the item is being overwritten when it's applied on an a tag because of the 2 directives (text and item) that are setting the "color".
- Exclude ion-item on a tag
**Fixes**: #8293
> fix(typography): Exclude ion-item on a tags selector

- src/components/fab/fab.ios.scss
- src/components/fab/fab.md.scss
- src/components/fab/fab.wp.scss
- src/components/fab/test/basic/main.html
- src/components/item/test/text/main.html
- src/components/nav/test/nav-push-pop/main.html
- src/components/typography/test/basic/main.html
- src/components/typography/typography.ts
- Removes chained css from fab button
- Adds :not([ion-fab]) to typography selector
- Adds [ion-text] selector and adds deprecation warning for other selectors
- Adds commented out docs for typography, should remove comment with selectors
closes #8293
> refactor(typography): add `ion-text` attribute selector, deprecate others

- src/components/input/input.ts
fix typo in input's documentation
> docs(input): fix typo in documentation

- src/themes/ionic.globals.scss
This changes the default font path so that fonts can be loaded without having to have seperate variables in the users `variables.scss` file. This is a companion to https://github.com/driftyco/ionic-app-scripts/pull/152 and https://github.com/driftyco/ionic2-app-base/pull/92
- change default font path from '../fonts' to '../assets/fonts'
> fix(sass): change default font path

- src/components/nav/nav-push.ts
When using the NavPush directive there isn't a way to disable the nav. For example, while using a ion-card I was using `[navPush]` to go to the card detail page, and on the detail page I use the same card component, but don't want to push to anything. Not setting a page to the directive works, but there is an error thrown. 
Currently happening on click:
```
invalid page component: null
```
**Usage Example:**
So when `PushPage` is explicity set to a falsey value, nothing will happen.
``` typescript
@Input() isDetailPage;
PushPage: any = null
constructor() {
if (!this.isDeatilPage) {
this.PushPage = CardDetailPage
}
}
```
- Check for a page to push to before pushing.
2.x
**Fixes**: #
> [navPush] Check if the NavPush page exists onClick

- src/animations/animation.ts
-
-
-
**Fixes**: #
A very short animation could actually call didFinish before _beforeReadFn() since the animation is invalidated once it finishes
_beforeReadFn is never called.
NavigationController depends on this behavior to work properly.
Fixes #8842
> fix(animation): _beforeRead/Write is always called

- .scss-lint.yml
- src/components/picker/picker-component.ts
- src/components/picker/picker.ios.scss
- src/components/picker/picker.md.scss
- src/components/picker/picker.scss
- src/components/picker/picker.wp.scss
- src/config/mode-registry.ts
Changes: 
- Avoid using zone
- Direct DOM manipulation instead of relying on angular 2 change detection
- Touch events debouncing, avoids triggering rendering more than once per frame. 
- Simplified generated DOM by using raw `<button>` instead of `<button ion-button>`
- CSS containment. Avoids layer invalidation outside the picker boundaries
- Remove CSS properties that trigger layout invalidation in the element itself (font-size changes), replaced by transform: scale()`
- Minor JS code optimizations
BEFORE:
AFTER:
> perf(picker): improves performance of picker and datepicker (WIP)

- src/navigation/nav-controller.ts
A common feature is when people display an overlay component, they want to navigate from that.
But we don't document how to do that.
- Add note in NavController docs about overlay components
2.x
> docs(navController): add note about overlay components

- src/platform/platform-registry.ts
This fixes an issue where in Ionic 2 apps the native chrome functionality of auto scrolling when an input is focused does not currently work. This is a shorter term fix as the ultimate fix is to find what is causing the native chrome auto-scroll to not work in Ionic 2 apps. I have tested this on Android 5.1.1, 6.0.1 and 7.0. cc @mlynch @manucorporat 
- set `scrollAssist` on Android
**Fixes**: #6228
> fix(platform): enable scrollAssist on Android

- src/components/input/input-base.ts
- src/components/input/input.ts
- src/components/input/native-input.ts
> style(input): fix lints

- src/module.ts
With 2.1.2 compiler, ngc will fail if click block is not added to declarations
- add click block to ngModule declarations
-
-
2.x rc4
> fix(clickBlock): add clickblock to ngModule declarations

- src/components/fab/fab.scss
- src/themes/util.scss
1. IE does not support `calc` inside `transform` ([bug](https://connect.microsoft.com/IE/feedback/details/762719/css3-calc-bug-inside-transition-or-transform)). This causes the transform to fail and the `.click-block` to be active at all times, making Ionic apps unusable on IE. It looks there was a fallback in place without using `calc`, but that gets removed when building the Ionic source.
2. IE does not support the `initial` CSS value ([Can I Use](http://caniuse.com/css-initial-value)). This is used in [a few places](https://github.com/driftyco/ionic/search?l=SCSS&q=initial&utf8=%E2%9C%93), but in most cases it does not matter functionally (only visually). It *does* matter where it's used in the `ion-fab`, where a list that opens to the top is instead shown below.
I know IE is not …
> Improve IE support

- src/components/item/item-reorder.ts
- src/components/item/test/reorder/main.html
This allows to apply reordering inside template without importing any other helper functions
- adds additional method `applyTo` to $event  triggered by ionItemReorder
> feat(reorder): add `applyTo` method to `ionItemReorder` event

- src/platform/cordova.scss
Related Issue
https://github.com/driftyco/ionic/issues/9395
- The height and min-height is no longer applied to the toolbar when `.statusbar-padding` class is present.
**Fixes**: #
toolbar-statusbar-padding should only add padding-top
> fix(toolbar): do not apply height for .statusbar-padding

- src/components/app/app.ts
- src/components/nav/test/worst-case/app-module.ts
- src/components/tabs/tabs.ts
- src/navigation/nav-controller-base.ts
- src/navigation/test/view-controller.spec.ts
- src/navigation/view-controller.ts
This was not a high priority issue, but now the android hardware go back button is working and it heavily relies in the correct behavior of app.navPop().
Without this PR, navPop() is able to close modals, but `onDidDismiss()` and `onWillDismiss()` is not called.
fixes #8223
> fix(viewcontroller): onDidDismiss() is always called

- src/util/dom-controller.ts
Latest nightly throws me an error on serve.
```
[12:39:25]  typescript: node_modules/ionic-angular/util/dom-controller.d.ts, line: 2 
Call signature, which lacks return-type annotation, implicitly has an 'any' return type. 
L1:  export declare type DomCallback = {
L2:      (timeStamp: number);
L3:  };
[12:39:25]  transpile failed 
```
I'm using `"noImplicitAny": true` in my `tsconfig.json` `compilerOptions`, which some other developers will probably be using as well.
- Add an explicit `any` return type
**Ionic Version**: 2.0.0-rc.3-201612021933
> fix(util): replace implicit any in dom-controller

- src/components/virtual-scroll/virtual-util.ts
Same idea as #9511 from yesterday. Is it possible to have the tests for Ionic run with `noImplicitAny` to prevent this in the future?
Latest nightly throws me some errors on serve.
```
[10:01:32]  typescript: node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts, line: 22 
[10:01:32]  typescript: node_modules/ionic-angular/components/virtual-scroll/virtual-util.d.ts, line: 25 
Call signature, which lacks return-type annotation, implicitly has an 'any' return type. 
L21:  add: {
L22:      (name: string);
L23:  };
Call signature, which lacks return-type annotation, implicitly has an 'any' return type. 
L24:  remove: {
L25:      (name: string);
L26:  };
Call signature, which lacks return-type annotation, implicitly has an 'any' return type. 
L28:  setAttribute: {
L29: …
```
> fix(virtual-scroll): replace implicit any's

- src/components/tabs/tab.ts
Missing closing brace in the documentation
**Fixes**: #
closing tag was wrong
> Fixed a typo

- src/util/scroll-view.ts
Same as #9511 and #9530. Replaces an implicit any type with the correct type.
Is it possible to have the tests run with the `noImplicitAny` `tsconfig` option to prevent this in the future?
**Ionic Version**: 2.0.0-rc.3-201612080433
> fix(util): replace implicit any

- src/components/input/input.scss
- src/components/input/test/input-focus/main.html
Stops disabled inputs from acting like they have been focused
- add a css rule to prevent `.input-cover` from being focused
- add a disabled input to the input focus test
**Fixes**: #9070
> Disabled input fix

- CHANGELOG.md
There was a breaking change to the events API which is not listed in the changelog.
The documentation was changed here: https://github.com/driftyco/ionic/commit/cdf5dd71cdd0b5c54b54626ea8f351326a9bad1d
- Added an example of how to update to the new API
> chore(changelog): add breaking change to events in rc4

- src/components/datetime/datetime.ts
- src/components/datetime/test/basic/app-module.ts
- src/components/datetime/test/basic/main.html
- src/components/datetime/test/datetime.spec.ts
DO NOT SQUASH - this contains a commit from manu and me
Enables the ability to pass custom day values, fixes a bug when the current year does not exist in yearValues; it was disabling months when it shouldn’t.
Adds a unit test that will break if the default year is set to today’s year and it doesn’t exist in yearValues.
Fixes #7190
> fix(datetime): enable custom day values

- CHANGELOG.md
"devDependencies": {
"@ionic/app-scripts": "0.0.48",
}
should be
"devDependencies": {
"@ionic/app-scripts": "0.0.48",
"typescript": "2.0.6"
}
Missing dependency 
-
-
-
**Fixes**: #
> Changelog file RC3 section devDependencies missing typescript

- src/components/slides/swiper/swiper-events.ts
This fixes an issue where `Unable to preventDefault inside passive event listener invocation.` was getting thrown because we were using preventDefault inside a passive event listener. According to the current dom events spec passive events cannot use preventDefault. The fix for this was to make the touchmove listener not passive.
- make touchmove listener not passive
> chore(swiper): make touchmove listener not passive

- src/components/list/list.ios.scss
- src/components/list/list.md.scss
- src/components/list/list.scss
- src/components/list/list.wp.scss
The last input in a list will now have a border when not focused.
- Add a css rule to add a a border to the last input in a list
**Fixes**: #9619
> fix(list): fixes #9619

- src/util/scroll-view.ts
If the duration for scrollTo is 0, then the scroll never happens. The logic is scroll-view will produce `NaN`
- Check if the duration is less than 32
- If so, set the position right away and return the promise
2x
**Fixes**: #9864
> fix(scroll): handling low duration in scrollTo

- src/components/app/test/animations/app-module.ts
Originally this error was getting thrown when using the memory check button `EXCEPTION: Error in main.html:36:4 caused by: Cannot read property 'platform' of undefined`, this test fixes that issue so that platform is not undefined.
- change `this` to `self`
> test(animations): fix memory check

- src/components/app/test/animations/app-module.ts
This changes `platform` to `plt` to match our new naming standard for platform.
- change `platform` to `plt`
> test(animations): change platform to plt

- src/components/segment/test/swipe/app-module.ts
- src/components/segment/test/swipe/main.html
`ionDidChange` was deprecated and changed to `ionSlideDidChange`, this updates the test to reflect that change. Also `activeIndex` does not exist and should be `_activeIndex`
- change `ionDidChange` to `ionSlideDidChange`
- change `activeIndex` to `_activeIndex`
> test(segment): ionSlideDidChange and _activeIndex

- src/components/action-sheet/action-sheet-component.ts
- src/components/action-sheet/action-sheet.ts
- src/components/alert/alert-component.ts
- src/components/alert/alert.ts
- src/components/modal/modal-component.ts
- src/components/modal/modal.ts
- src/navigation/view-controller.ts
This adds the minClickBlockDuration nav option to the action sheet and modal. It also tweaks the duration to 400ms which from my testing with the emulator and an iPhone 5 running iOS 10 seems to be the magic number.
- change minClickBlockDuration to 400ms default
- add minClickBlockDuration to action sheet and modal
> chore(clickblock): add minClickBlockDuration to components

- src/components/app/test/app.spec.ts
Fixes two broken tests related to click block. The `setEnabled` method now takes a new parameter that defaults to 0, `minDuration`.
- Change test to account for the new minDuration param
> chore(tests): fix failing tests

- src/components/slides/slides.ts
Small typo's in the deprecation notice for `getSlider()`.
> fix(slides): deprecation notice typo's

- src/components/app/test/app.spec.ts
- adds tests for the new `minDuration` param
> test(clickblock): add new tests for minDuration

- CHANGELOG.md
Wonky "smart" quotes on the dependency for `sw-toolbox` in the changelog
> unsmarten quotes on sw-toolbox dep

- src/components/slides/slides.ts
Since rc5 and the slides api refactor, the doc is not up to date.
- Change the `pager` description.
- Change the `paginationType` input type.
**Ionic Version**: 2.0.0 RC5
> docs(slides): update slides docs

- src/components/content/content.ts
- src/platform/platform.ts
Build breaks if `noImplicitAny` is declared in `tsconfig.json`.
- add `void` return value to call signature of a few callbacks
**Ionic Version**: 2.0rc5
> add void return value for some callback signatures

- .gitignore
- scripts/gulp/util.ts
* Currently gulp runs the `ngc` by manually calling the `./node_modules/.bin/ngc` file (by assuming it's a node script)
This is not always correct, because often package managers like (npm or yarn) create bash files for the package binaries.
>  Using `resolve-bin` to properly determine the path to the *real* node script and then we can assume it's a node file.
* Also excluded the `yarn.lock` files in the repository. (Decided to use the wildcard, because `.lock` is very uncommon)
**Small Summary**
> This PR fixes the weird build issues on Windows machines (using Git Bash)
**Ionic Version**: V2
Fixes #8341
> chore: fix incorrect execution of node binaries

- src/components/slides/slides.ts
- src/components/slides/swiper/swiper-pagination.ts
- src/components/slides/test/options/app-module.ts
- src/components/slides/test/options/main.html
Closes #10002
Adds back option to define a custom pagination render for bullets 
-
-
-
2x
**Fixes**: #10002
> feat(slides): add option for paginationBulletRender

- src/components/item/item-sliding.ts
- src/components/item/test/sliding/app-module.ts
- src/components/item/test/sliding/main.html
Added items with the following use cases:
1. Sliding item without options
2. Sliding item with one set of dynamic options that toggle
3. Sliding item with two options, one dynamic
Removing my code will cause errors in all of the above examples.
Fixes #9914
> fix(item-sliding): don't error or allow swipes with no options

- src/navigation/nav-controller-base.ts
When pushing a page using `app.getRootNav().push(CoolPage)` you can now swipe this page back. Before this fix when pushing a page from the rootNav you could not swipe this page back.
- check that the length of `this._children` (the array of navs) is <= to 1
**Fixes**: #9558
> fix(nav): swipe back after getRootNav().push

- src/components/tabs/tabs.ts
Update deeplinker's updateNav after tabSwitchEnd so deeplinker gets the
right active navchild.
Url is not correct after selecting tabs.
**Fixes**: #10032
> Fix url is not correct after selecting tabs

- src/components/input/input.ts
- src/components/input/test/clear-input/app.module.ts
- src/components/input/test/clear-input/main.html
If the input has a `formControlName` or `ngModel` on it then `onChange` is not called so `checkHasValue` doesn't get called. This PR calls `checkHasValue` so that the clear input will work.
Also adds an input without ngModel/formControlName and inputs with formControlName to the clear-input test
Fixes #9077
> fix(input): show clearInput on inputs with ngModel/formControlName

- src/components/input/input.ts
- src/components/input/test/placeholder-labels/app.module.ts
- src/components/input/test/placeholder-labels/main.html
This also adds to placeholder test an input and textarea with readonly that can be toggled.
Fixes #6408
> fix(input): pass readonly from ion-input down to native input

- src/components/input/input.ts
- src/components/input/native-input.ts
- src/components/input/test/floating-labels/app.module.ts
- src/components/input/test/floating-labels/main.html
If you open the test here: http://localhost:8000/dist/e2e/input/floating-labels/
The 4th input has dynamic min, max, step values that can be toggled. Click on the input field and use the arrow keys to step up or down.
closes #10189
> feat(input): add max, min, step as inputs and pass to native

- src/platform/test/platform.spec.ts
This PR modifies unit tests around `platform.is()`. This is related to https://github.com/driftyco/ionic/issues/10209. I am not able to reproduce this issue, but just to cover our bases more I have modified our unit tests to be a little more thorough as the user agent, especially in iOS, has changed a good bit recently.
- modify unit tests in platform to test newer user agents
> test(platform): new user agent tests

- src/components/input/input.scss
- src/components/input/input.ts
Adds the disabled attribute to the parent input/textarea, also fixes
where disabled textareas were focusable regardless of where disabled
was set.
Testing this:
- Use http://localhost:8000/dist/e2e/input/form-inputs/
- There are two disabled inputs via formControl under the "Form w/ disabled inputs" header
- There are two disabled via attribute (one toggle) at the bottom
fixes #10155
> fix(input): don't allow focus when disabled is set

- src/components/content/content.ts
This checks for a use case where `this._scroll` may be undefined in certain cases. If it is undefined we simply return and if it is not undefined then we set `scrollEvent` and continue on.
Also, scrollEvent is now a `let` instead of a `const` as `const`s have to be initialized upon declaration as per the ES2015 spec.
- check for `this._scroll`
**Fixes**: #10186
> fix(content): check for this._scroll

- src/components/segment/segment.ts
Add Input property disabled to IonSegmentButton documentation.
-
-
-
**Fixes**: #
> Add Input property disabled to IonSegmentButton documentation.

- src/platform/platform.ts
- src/platform/test/platform.spec.ts
UiWebView on an iPad pro has a bug where it has an iPhone user agent: https://forums.developer.apple.com/thread/25948 . The good thing is that `navigator.platform` correctly returns `iPad` so we can use that to detect when the user is on an iPad pro.
- add extra check for iPad pro
- add a unit test to prove it works
**Fixes**: #10209
> Platform is fix

- package.json
- scripts/gulp/declarations.d.ts
- scripts/gulp/tasks/release.ts
**IMPORTANT:**
You need to comment out the code in the following tasks and replace them with a log for testing: https://github.com/driftyco/ionic/blob/chore-release-prompt/scripts/gulp/tasks/release.ts#L72-L113
Testing this:
1. Run `gulp release`, select any release type, select either yes or abort release
- if yes:
- verify the changelog and package.json updated
- verify the tasks to publish npm and github were called
- if no:
- verify nothing was updated and the tasks to publish weren't called
2. Run `gulp release.test`, select any release type, select either yes or abort release
- if yes:
- verify the changelog and package.json updated
- verify the tasks to publish npm and github were **NOT** called
- if no:
- verify nothing was updated and the tasks to publish weren't called
Closes …
> chore(release): add prompt for release to select release type

- src/components/checkbox/checkbox.ts
- src/components/checkbox/test/basic/app.module.ts
- src/components/checkbox/test/basic/main.html
- src/components/toggle/toggle.ts
fixes #9730
testing:
go to the `checkbox/basic` test, click on the `checked` item and watch the values update, click `disabled` and then click `checked` and make sure it still updates the value but not when clicking on the disabled item.
> fix(toggle/checkbox): allow value to be updated when disabled

- src/components/alert/alert.ios.scss
- src/components/alert/alert.md.scss
- src/components/alert/alert.wp.scss
There is no variable to style alert checkbox and radio button text color. This is essential when changing the background color of the alert.
- Add sass variables
**Fixes**: #10301
> feat(alert): add sass variables for checkbox and radio button text color

- src/components/content/content.ts
- src/components/refresher/test/navigation/app.module.ts
- src/components/refresher/test/navigation/main.html
- src/components/refresher/test/navigation/page2.html
This fixes an issue where the content class may try to change a style on a scroll element after that scroll element has been destroyed. One way this could be reproduced (which i have added an e2e test for here) is to start a refresher, and then `setRoot`, which destroys the scroll element that content would have been trying to tweak.
- Add an e2e test for refresher that can be used to test for this issue.
- Add a check to make sure that a scroll element exists before trying to change its style
**Fixes**: #10220
> fix(content): check for scroll element

- src/platform/platform.ts
- src/platform/test/platform.spec.ts
This fixes an issue where dimensions were not getting measured right when the window was resized to be smaller. This caused issues with our new desktop support.
- Make sure dimensions get measured correctly when the window is resized both smaller and bigger
- Add new unit tests that cover the `width()` and `height()` methods and also window resizing
> Resize fix

- src/themes/ionic.globals.scss
Confusion
- Remove unused SCSS variable ($z-index-menu-backdrop)
2.x
**Fixes**: Confusion
> chore(menu): remove unused $z-index-menu-backdrop

- src/components/alert/alert.ts
add : `import { AlertController } from 'ionic-angular';` in usage section
Help user to implement alert in ionic 2
- add : `import { AlertController } from 'ionic-angular';` in usage section
> Improve documentation of AlertController

- src/components/grid/row.ts
It fixes a typo. I did not create an issue as suggested by the guidelines, I thought it would not be useful.
> typo in the doc: horrizontally -> horizontally

- src/components/slides/slides.ts
In the slidePrev, slideNext, and slideTo docs it still shows the old event names.
- Simple documentation change of old event names to new ones.
> Fix references to old event names

- src/components/virtual-scroll/virtual-scroll.ts
Fixes the broken link to ion-img docs in [Virtual Scroll docs page](https://ionicframework.com/docs/v2/api/components/virtual-scroll/VirtualScroll/#images-within-virtual-scroll).
- Change the hyperlink of ion-img to correct one.
**Ionic Version**: 2.1.0
**Fixes**: #10554
> fix(docs): broken url to ion-img in virtual scroll docs

- src/components/radio/radio.md.scss
Resizing of the radio button icon using `$radio-md-icon-width` and `$radio-md-icon-height` variables in Android platform was incorrect. The inner round shifted to the right-bottom position.
- Fixed width and height calculation of the inner round.
> Incorrect .radio-inner width/height calculation

- package.json
- src/index.ts
Updates our Angular dependency to 2.4.8. Also updates rx and zone to what Angular 2.4.8 requires.
- Update Angular to 2.4.8
- Update rxjs to 5.0.1
- Update zone.js to 0.7.2
**Fixes**: #10422
> chore(angular): update to 2.4.8

- src/components/split-pane/split-pane.ts
Fixed typo in word "also".
**Ionic Version**: 2.2
> fixed typo in split-pane.ts documentation

- src/components/label/label.scss
- src/components/select/select.ts
- src/components/select/test/multiple-value/main.html
- src/components/select/test/single-value/main.html
This makes floating labels work with ion-select, instead of behaving like stacked labels.
- fix(select): make floating labels work for ion-select
**Fixes**: #10751
> fix(select): make floating labels work for ion-select

- src/components/range/range.ts
Currently, there is no way to know if `ionic-range` is being focused or not.
- Add an output event called `ionDragEnd` to `ion-range`, that is being triggered when the range is being left (pointer up)
- `<ion-range (ionDragEnd)="onDragEnd($event)"></ion-range>`
**Ionic Version**: 2.2.0
**Fixes**: This feature request: https://github.com/driftyco/ionic/issues/10760
> Added ionDragEnd output event to be emitted on leave for ion-range

- src/components/alert/alert-component.ts
- src/components/alert/alert-options.ts
- src/components/alert/alert.ts
- src/components/alert/test/basic/app.module.ts
We cannot set currently min & max attributes for inputs used in Alerts.
It can be quite useful for input of type "date".
- add min & max attributes to AlertCmp
- add an input date with min & max set to the alert e2e test (function doPrompt())
- add an input date without min nor max set to the alert e2e test (function doPrompt())
**Ionic Version**: 2.1.0
**Fixes**: #10590
> feat(alert): add attributes min & max to alert inputs

- src/components/virtual-scroll/virtual-scroll.ts
This fixes issue as described in #9722 that still exists in 2.0.0-final
**Fixes**: #9722
> fix(virtualscroll): Populate nodes at correct height

- src/util/scroll-view.ts
InifiniteScroll done not works in firefox.
Event.timeStamp is always 0 in firefox.
- https://github.com/driftyco/ionic/blob/master/src/components/infinite-scroll/infinite-scroll.ts#L217
- https://bugzilla.mozilla.org/show_bug.cgi?id=238041
**Fixes**: #9596
> fix(infinite-scroll): event.timeStamp polyfill for firefox

- src/components/slides/swiper/swiper-events.ts
Closes #10577
Slide fail to swipe when platform via query params.
This lets touch events be simulated is ionicPlatform is set.
2.x
**Fixes**: #10577
> fix(slides): simulate touch events for query params

- src/util/scroll-view.ts
Regression caused by 7e9bad5
Details in #10816
- Do not set initialized before checking it
**Ionic Version**: 2.2.0-201703161917
**Fixes**: #10816
> fix(scroll-view): do not set initialized until it is enabled

- src/components/alert/alert-options.ts
Commit 46fe1ff53cfc2cfef152b560d01882eebca8c678 defined the `AlertButton` interface for the `buttons` array, but it's missing the `cssClass` property as described in the **Button options** section of the docs: http://ionicframework.com/docs/v2/api/components/alert/AlertController/#advanced
- Add the `cssClass` property to the `AlertButton` interface.
2.3.0
**Fixes**: #
> fix(alert): add missing cssClass property for buttons

- circle.yml
- scripts/docs/deploy.sh
- scripts/gulp/tasks/demos.prod.ts
- scripts/gulp/tasks/docs.ts
CI builds on Circle CI take around 2 hours. Mostly because of the time is takes to build all 41 demos. Sometimes it's over 2 hours. 
Current: https://circleci.com/gh/driftyco/ionic/6142
New: https://circleci.com/gh/driftyco/ionic/6156
- Upgrade to Circle CI v2
- Modify the `gulp demos.prod` task to allow `batch` and `batches` parameters
- Modify the `gulp docs.demos` task to operate independently of `gulp demos.prod`
> chore(CI): upgrade to Circle CI v2 and leverage multiple containers for demo builds 

- src/components/datetime/datetime.ts
- src/components/picker/picker-component.ts
The datepicker component will emit ioncancel event on backdrop click
If dismiss was received with role backdrop, emit ioncancel
-
-
-
2.x
**Fixes**: #
> fix(datetime): emit ioncancel event on backdrop click for datetime

- src/components/slides/swiper/swiper-pagination.ts
Fixes the issues referenced. Swiping back on a slider with looping enabled now correctly sets the active bullet. 
e2e tested with `gulp e2e.watch --f=slides/loop` and looks good 👍 
- The slider now handles negative index values by indicating the position starting at end.
**Ionic Version**:  2.x / 3.x
**Fixes**: #10826 #10883
> fix(slides): negative number indicates position starting at end

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Now that v3 is officially in beta, this is needed for bug reports / pull requests
- Added v3 for issues template
> docs(.github): add v3 for github documents

- src/components/modal/modal-component.ts
- src/components/modal/modal-options.ts
- src/components/modal/test/basic/pages/modal-pass-data/modal-pass-data.scss
- src/components/modal/test/basic/pages/page-one/page-one.ts
Can pass one cssClass or multiple (same as our other overlays). Added a cssClass to the basic modal test which adds 2 classes to the first modal (click the first button) and styles the font color of the modal content blue.
Closes #10020
> feat(modal): add cssClass to modal options

- src/platform/platform.ts
The doc did not mention a required parameter for setLang(), updateDocument
- Added the missing parameter to the doc
> Added a missing parameter in the doc in setLang()

- src/components/select/select.ts
The current documentation has `selected="true"` combined with `ngModel` binding, but this does not work. In fact, the demo on the page does not use `selected`. I removed this from the example code.
I also added a paragraph explaining how to set an option as selected.
- Update documentation and example for `ion-select`
> Correctly document usage for selected elements

- scripts/templates/page/module.ts.tmpl
When using *ionic g page ...* the result page module file is using IonicModule and it should use IonicPageModule instead.
- Changed the page module tempate to use IonicPageModule.
**Fixes**: #11076
> fix(ci-page-template) replace IonicModule with IonicPageModule

- src/components/nav/nav-push.ts
Error: Property 'params' does not exist on type MyPage.
- Declare params on MyPage
**Fixes**: #
> docs(nav-push): Declare params variables

- src/components/slides/slides.ts
Reading the documentation and following along left me lost as to why the .lockNextSlides() was not working, this was because it required a boolean parameter that was not reflected in the documentation. This PR adds the JSDoc @param to show that the function requires a boolean parameter. Does not include a definition for the single parameters so this may cause issue in the theme of the docs template.
- Updated documentation to include @params 
v2
**Fixes**: #
> Update documentation for ion-slide

- src/components/item/item-options.ts
fix the side of item-options component when rtl
**Fixes partially**: #11115
> fix(item-options): rtl better suport

- src/components/tabs/tabs.ts
getComponent() returns a ViewController, so we must reference the
component property when checking against the active component
Ionic Version: 3.x
> fix(tabs): invalid active component detection

- src/platform/platform-registry.ts
- src/platform/platform-utils.ts
- src/platform/test/platform.spec.ts
The ionic platform running in electron doesn't detect that it's running there and never fires the `device ready` event. This change aims to introduce the electron platform as an available platform and resolve the platform ready when the page has loaded (like the browser).  (First PR to 2.0, let me know if there's anything else I need to do!)
- Add the isElectron platform utility
- Add the electron platform to the registry
**Ionic Version**: 2.2
**Fixes**: #6274
> feat(platform): add the handler electron platform ready

- scripts/docs/deploy.sh
- scripts/gulp/constants.ts
- scripts/gulp/tasks/docs.ts
Updates a JSON file that ionicframework.com now uses to identify what the latest release is.
- create a necessary new vars following @danbucholtz conventions
- create a new `docs.homepageVersionUpdate` gulp task 
- call the gulp task during a site deploy when a release is detected
> chore(CI): Updating ionicframework homepage automatically on release

- src/components/slides/swiper/swiper.ts
add condition, to check if slider exist before remove
bug on fast rerendering  #10830
- check if slider exist before clean
**Ionic Version**: 2.2.1
**Fixes**: #10830
> fix : "ion-slides" - fast rerendering causes a crash

- src/components/datetime/test/basic/pages/root-page/root-page.html
- src/components/datetime/test/datetime.spec.ts
A breaking change, unfortunately, snuck into datetime recently where we were returning an object when it should have been a string. This e2e and unit tests ensure that we always return a string.
- add unit tests to datetime
- add an extra e2e test to datetime
> test(datetime): add unit tests to make sure we return a string when we should

- src/components/item/item-reorder-gesture.ts
Item reordering is incorrect in RTL
- add 100 instead of subtract 100 when RTL
**Fixes**: https://github.com/driftyco/ionic/issues/11211
> fix(rtl): change item reorder offset for RTL

- src/components/select/select.ts
Allows for the ability to close an ion-select component programatically. This is made possible by make `overlay` a property of the component class. For context, `overlay` is the variable that stores the reference to the action sheet, alert, or popover used to display the select component.
- added `private _overlay` property.
- added `close()` method to the select component class
**Fixes**: #11318
> implement ability to close select programmatically

- package.json
In Angular 4.1 are no breaking changes. The update should be no problem.
- Angular 4.1
- zone.js 0.8.9
- app-scripts 1.3.5
3.x
> chore(package.json): update to latest Angular release

- src/components/select/select-popover-component.ts
- src/components/select/select.ts
#11480 
- avoid fireing `ionChage` as it is already fired by button value setter
- add `handler` to `SelectPopoverOption` 
- fire `input.ionSelect.emit(input.value)` instead of  `this.ionChange.emit(value)` to be consistent with `alert` and `action-sheet` 
**Fixes**: #11480
> avoid fireing ionChange event twice and fire ionSelect event to be consistant with the remaining select interfaces

- src/navigation/nav-controller-base.ts
- src/navigation/test/nav-controller.spec.ts
When calling `popToRoot` on the root view itself, the root view will no longer be removed.
Demo of current state: http://plnkr.co/edit/7rWOPzOb3rUftEN0nYx6?p=preview
I spent quite some time looking through the code, but I'm not 100% sure if this fix is in the right place. I noticed that `ti.removeCount` was 0, but `ti.leavingRequiresTransition` (and therefore `ti.requiresTransition`) were true, which I assume should not be the case since there should be no transition.
I was able to fix the bug in many different places, but this one seemed to fit best.
Issue: #11500
> fix(navcontrollerbase): popToRoot should not remove root view

- src/components/virtual-scroll/test/basic/app.module.ts
- src/components/virtual-scroll/test/basic/main.html
- src/components/virtual-scroll/virtual-scroll.ts
VirtualScroll trackByFn has no effect due to the random order that Angular interprets input values.
Virtual TrackByFn is changed into as setter input, that redefines the change detection mechanism as soon as trackBy is parsed, to take into account the provided function
**Fixes**: #7531
Related to #11294
> fix(VirtualScroll): initialise differ with trackByFn

- src/components/select/select.ts
- src/navigation/overlay-proxy.ts
- src/navigation/view-controller.ts
Clearified onDidDismiss(...) and onWillDismiss(...) callback signature.
Resolves possible confusion what to expect from the callback.
- Changed "Function"-type to "(value: any, role: string) => void"-type, 'cause this is the only signature which is called.
**Fixes**: #11512
> refactor(ViewController): Improved signature of on*Dismiss(...)

- scripts/README.md
- Snapshot does not work anywhere except for a very specific environment
- Snapshot seems to also depend on the java JDK
> docs(snapshot): missing vital info

- src/components/virtual-scroll/test/basic/app.module.ts
- src/components/virtual-scroll/test/basic/main.html
- src/components/virtual-scroll/virtual-scroll.ts
> perf(virtual-list): relaxed restrictions for fast path

- src/components/datetime/datetime.ts
- src/components/datetime/test/datetime.spec.ts
- src/components/datetime/test/labels/pages/root-page/root-page.html
- src/components/datetime/test/labels/pages/root-page/root-page.ts
Fixes #11547
- 016064e: fix(datetime): Fix floating label with empty ion-datetime
3.x
**Fixes**: #11547
> fix(datetime): Fix floating label with empty ion-datetime

- src/components/alert/alert-controller.ts
Added an importation for use the alert controller on line 52.
The example code did not include an import statement for use the component.
- Add an import statement.
**Fixes**: #11567
> The components was not imported in demo code.

- src/components/searchbar/searchbar.ts
The latest release introduced a signature mismatch in Searchbar causing AOT builds to fail. The PR fixes this.
- Update the `inputBlurred` method call in template to match the signature in the class
- Update the `inputFocused` method call in template to match the signature in the class
**Fixes**: #11598
> Fix method signature mismatch in template & class

- src/components/searchbar/searchbar.ios.scss
#11342 changed the padding left to be padding right
Change reference: https://github.com/driftyco/ionic/pull/11342/files#diff-2f6627d4c874dfc1d437dfeb446ea85eR142
cc @brandyscarney
> fix(searchbar): searchbar padding should be on the left

- .github/ISSUE_TEMPLATE.md
People using Ionic v1.x and opening issues here
Like - https://github.com/driftyco/ionic/issues/11264, https://github.com/driftyco/ionic/issues/11725
- Add a link to v1 repo
> docs(issue): add reference to ionic v1 for v1.x issues

- src/components/loading/loading-options.ts
Removes unused and undocumented option from LoadingOptions that causes confusion when auto-complete suggested by IDEs.
- Removes LoadingOptions.delay?
> refactor(loading): remove unused delay option

- src/components/range/range.ts
- src/components/range/test/basic/pages/root-page/root-page.html
- src/components/range/test/basic/pages/root-page/root-page.ts
Setting min or max of an ion-range doesn't update the UI.
- Refresh UI when min or max are set
**Fixes**: #11719
> fix(Range): setting min/max should update UI

- src/components/toolbar/toolbar.ts
The link to the Navbar API Doc was broken
- `../../navbar/Navbar` -> `../Navbar/` (`../../tabbar/Navbar`)
- this link is on the page twice
> Fix Navbar link

- src/components/toolbar/toolbar.ios.scss
fixes #7671 where the ios back button isn't clickable with a segment in the header
just add a z-index to the ios specific style. this mimics the way the ion-buttons component handles staying above the segment buttons as well.
**Fixes**: #
> Allow ios back button to be clicked when segment buttons are in the nav bar

- src/components/virtual-scroll/virtual-scroll.ts
The `virtualScroll` input setter can be called first, which calls initializes `_differ` with the default `virtualTrackBy` function. When the `virtualTrackBy` input setter is called later, `_differ` is no longer blank, and so the input `virtualTrackBy` is not used.
Do not check whether `_differ` is undefined in the `virtualTrackBy` setter.
**Fixes**: Issue #7531, PR #11492
> fix(VirtualScroll): initialize trackByFn reference

- src/components/modal/modal-controller.ts
Adds documentation for cssClass option to ModalController.create
**Fixes**: #10020 (doesn't actually fix it, just documents the prior fix)
> Document cssClass option to ModalController

- src/components/alert/alert.md.scss
- src/components/card/card.ios.scss
- src/components/card/card.md.scss
- src/components/card/card.wp.scss
- src/components/datetime/datetime.ios.scss
- src/components/datetime/datetime.md.scss
- src/components/datetime/datetime.wp.scss
- src/components/input/input.ios.scss
- src/components/list/list.ios.scss
- src/components/list/list.md.scss
- src/components/list/list.wp.scss
- src/components/select/select.ios.scss
- src/components/select/select.md.scss
- src/themes/ionic.theme.dark.ios.scss
- src/themes/ionic.theme.dark.md.scss
- src/themes/ionic.theme.dark.wp.scss
- src/themes/ionic.theme.default.ios.scss
- src/themes/ionic.theme.default.md.scss
- src/themes/ionic.theme.default.wp.scss
Missing `!default` on the latest rtl compatible variables introduced by a30379b.
These were the cases I could find, I might have missed some. Maybe it's possible to add a test that checks if all Ionic variables have a `!default`?
PS: please squash these commits 😬
**Ionic Version**: 3.3.0
> fix(): allow overriding variables

- src/components/searchbar/searchbar.ts
The issue is reproducible on the [demo page](http://ionicframework.com/docs/components/#searchbar):
- type something (for example `Aviv`)
- go to the beginning of the field
- type something (for example `Tel `)
- after typing the first char (`T`), the caret unexpectedly moves to the end of the field, and the field finally contains `TAvivel ` instead of `Tel Aviv`.
- In `_inputUpdated`, before updating the value of the input, check whether the assignment is useful.
**Ionic Version**: 3.2.1
> fix(searchbar): caret moving to the end when typing

- scripts/templates/component/module.ts.tmpl
Wrong import statement
- change IonicPageModule to IonicModule
3.x
**Fixes**: #
#11838
> refactor(template): fix component template

- src/components/content/content.scss
You can see the `ion-refresher` text when you're not supposed to see it. It happens when a page has `ion-refresher` and the content is really small (in this example, a single `ion-item`),
Examples:
Inherit background from parent to hide the content behind `.scroll-content` (i.e Refresher, Infinite Scroll.. etc). 
The fix is only for `ion-content.has-refresher > .scroll-content`. It might be a good idea to apply this fix to the `.scroll-content` selector.
Here's what it looks like with the fix:
> fix(content): scroll content should inherit background

- CHANGELOG.md
- package.json
- scripts/polyfill/readme.md
- scripts/templates/provider/ts.tmpl
- src/components/segment/segment.ts
- src/navigation/nav-controller.ts
I want to eliminate the V2 Tag from Angular like we did with Ionic 2
> docs(): rename Angular 2 to Angular

- src/components/button/test/block/pages/page-one/page-one.html
- src/components/button/test/full/pages/page-one/page-one.html
- src/components/button/test/icons/pages/page-one/page-one.html
- src/components/card/test/advanced/pages/root-page/root-page.html
- src/components/card/test/colors/pages/root-page/root-page.html
- src/components/card/test/map/main.html
- src/components/card/test/social/main.html
- src/components/content/test/basic/pages/page-five/page-five.html
- src/components/content/test/basic/pages/page-four/page-four.html
- src/components/content/test/basic/pages/page-one/page-one.html
- src/components/content/test/basic/pages/page-three/page-three.html
- src/components/content/test/fullscreen/pages/page-five/page-five.html
- src/components/content/test/fullscreen/pages/page-four/page-four.html
- src/components/content/test/fullscreen/pages/page-one/page-one.html
- src/components/content/test/fullscreen/pages/page-three/page-three.html
- src/components/icon/test/basic/main.html
- src/components/icon/test/basic/pages/root-page/root-page.html
- src/components/item/test/buttons/pages/root-page/root-page.html
- src/components/item/test/colors/pages/root-page/root-page.html
- src/components/item/test/reorder/pages/root-page/root-page.html
- src/components/item/test/sliding/pages/root-page/root-page.html
- src/components/list/test/header-scenarios/pages/main/main.html
- src/components/loading/test/basic/pages/page-one/page-one.html
- src/components/loading/test/basic/pages/page-two/page-two.html
- src/components/tabs/test/badges/app/app.component.html
- src/components/tabs/test/colors/app/app.component.html
- src/components/tabs/test/tab-bar-scenarios/app/app.component.html
- src/components/toolbar/test/colors/pages/root-page/root-page.html
- src/components/toolbar/test/scenarios/pages/root-page/root-page.html
- e2e did not use `icon-start`/`icon-end`
- Find & replace all `icon-left` and `icon-right`
> feat(icon): compliment icon-side PR in test files

- src/components/select/select.ts
When using ion-select with popover interface, it does not support the cssClass in "selectOptions" attribute.
- support property cssClass in selectOptions 
**Fixes**: #
#11695
> fix(ionSelect): support cssClass for popover interface

- src/components/menu/menu.scss
- A better base case to show how to use `multi-dir` correctly on disabled properties
**Fixes**: #
> refactor(menu): move lint disable inside multi-dir

- src/components/alert/alert-component.ts
Opening a select without options in it and then pressing Okay resulted in the bound model being set to `{}`
The current code instantiates an empty object and attempts to put values of any text inputs in that object. I've added a check to determine if that object has any properties in it and, if it does not, it returns `undefined` instead of that empty object. 
**Ionic Version**:3.x
**Fixes**: #10435
> fix(select): make select with no options return undefined when OK is pressed

- src/components/loading/loading-component.ts
- src/components/loading/loading-controller.ts
- src/components/loading/loading-options.ts
- src/components/loading/loading.ts
- src/components/loading/test/basic/pages/page-one/page-one.html
- src/components/loading/test/basic/pages/page-one/page-one.ts
Add enableBackdropDismiss to Loading.
- Loading indicator can now be dismissed by the user if `enableBackdropDismiss` option is set.
3.x
**Fixes**: #7975
> feat(loading): add enableBackdropDismiss to Loading

- src/components/snapshot/test/basic/components/assistive-touch/assistive-popover/assistive-popover.html
- src/components/snapshot/test/basic/components/assistive-touch/assistive-popover/assistive-popover.module.ts
- src/components/snapshot/test/basic/components/assistive-touch/assistive-popover/assistive-popover.ts
- src/components/snapshot/test/basic/components/assistive-touch/assistive-touch.module.ts
- src/components/snapshot/test/basic/components/assistive-touch/assistive-touch.ts
RTL for all tests when using `e2e.watch --f=snapshot/basic`
**Fixes**: #
> feat(snapshot): add assistive popover to change direction

- package.json
zone.js 0.8.12 fixes some bugs and one especially for the ios platform
https://github.com/angular/zone.js/issues/802
> chore(zone.js): fix ios9 error

- src/components/split-pane/split-pane.scss
side=left always on left
side=start dynamically on start
side=end dynamically on end
side=right always on right
**Fixes**: #
> fix(split-pane): correct split-pane menu side order

- src/components/segment/segment.ios.scss
- src/themes/ionic.mixins.scss
Border radius does not behave like margin/padding with 4 variables
- remove property call, use simpler logic
**Fixes**: #
> fix(border-radius): remove @property logic

- src/components/loading/loading.ios.scss
- src/components/loading/loading.md.scss
- src/components/loading/loading.wp.scss
Just a quick replace of a fixed width margin with the main margin variable for content
> Use margin variable

- src/components/content/content.ts
- src/components/refresher/refresher.ts
- src/components/refresher/test/refresher.spec.ts
See #10994
- When `Content` has a `Refresher`, the calculated top margin is reduced by 1px to hide the border.
**Fixes**: #10994
> fix(refresher): border should only show when pulled

- src/components/input/input.ts
Checking out the amazing keyboard/input refactor by @manucorporat, I came across some inconsistencies in the attributes that are supported for `ion-input` and `ion-textarea`.
- Add `autocomplete` and `autocorrect` attributes for which the `Input()`s already exist.
- Add `maxlength`, `spellcheck` and `autocapitalize` on `ion-textarea`s as well.
**Ionic Version**: 3.x (nightly)
> fix(input): use all supported attributes on both textareas and inputs

- src/components/input/input.ts
Really nice to see autofocus has arrived in Ionic! I've been using a directive for this until now. In that directive I'm using a delay of 800ms, which works consistently every time.
Trying the latest nightly I found the autofocus fails about one third of the times with iOS transitions. Changing it to 800ms fixes it for me.
It could also be nice to make this a config setting, because someone might be using custom transitions that take longer.
- Change autofocus delay from 650ms to 800ms
**Ionic Version**: 3.x (nightly)
> fix(input): slightly longer delay for autofocus

- src/components/action-sheet/action-sheet-component.ts
- src/components/alert/alert-component.ts
- src/components/app/app.ts
- src/components/app/overlay-portal.ts
- src/components/loading/loading-component.ts
- src/components/nav/nav.ts
- src/components/nav/test/nav.spec.ts
- src/components/picker/picker-component.ts
- src/components/popover/popover-component.ts
- src/components/tabs/tab.ts
- src/components/toast/toast.ts
- src/navigation/nav-controller-base.ts
- src/util/mock-providers.ts
NavControllerBase is able to close the keyboard automatically, there is not a good point to call:
this.plt.focusOutActiveElement() on each overlay component (alert, actionsheet, picker, modal)
> refactor(overlay): simplify focusOutActiveElement

- src/components/item/item-sliding.ts
> fix(sliding-item): ionSwipe event is fired

- src/components/content/content.ts
Fix tiny typo on content docs page.
> docs(content): typo Sroll => Scroll

- src/components/toast/toast-controller.ts
Cannot use ToastController without knowing from where to import it
The doc is incomplete because this code won't work without first importing the class.  This is a common occurrence across virtually all of the Ionic docs.  This is the one that got me today, so I thought I'd fix it.
- add import to code example in doc
> Add import information

- scripts/docs/processors/jekyll.js
- scripts/docs/templates/common.template.html
This makes it possible to link to sub-sections of the markdown-generated API documentation on the website.  In the past, users had to manually enter the hash in the URL if they wanted to do this.
Resolves https://github.com/ionic-team/ionic-site/issues/1195, resolves https://github.com/ionic-team/ionic-site/issues/689, resolves https://github.com/ionic-team/ionic-site/issues/557
- When generating documentation, it adds HTML for the anchor link inside of an `<h3>` tag and surrounds the entire thing with newlines.
> chore(docs): add anchor links to documentation sub-sections

- src/components/list/list.md.scss
Remove margin of MD buttons in ion-item-options to make it the same as iOS. I haven't found anything in the [material guidelines](https://material.io/guidelines/components/lists-controls.html#lists-controls-types-of-list-controls) that justifies this margin.
(click image to enlarge)
> fix(list): remove margin of MD buttons in ion-item-options

- src/components/input/input.ts
Currently, the documentation for `autocomplete` and `autocorrect` is incorrectly set to the same as the `placeholder` documentation with the incorrect description: 
```
@input {string} Instructional text that shows before the input has a value.
```
- Correct the documentation for both `@Input` attributes.
- `autocomplete`: `@input {string} Set the input's autocomplete property. Values: `"on"`, `"off"`.`
- `autocorrect`: `@input {string} Set the input's autocorrect property. Values: `"on"`, `"off"`.`
**Fixes**: #12609
> docs(input): correct the `autocomplete` and `autocorrect` description

- src/components/tabs/tab.ts
- src/navigation/deep-linker.ts
- src/navigation/nav-controller-base.ts
- src/navigation/nav-controller.ts
- src/navigation/nav-util.ts
- src/util/mock-providers.ts
fixes https://github.com/ionic-team/ionic/issues/12499
> fix(navigation): done transition callback

- src/components/datetime/datetime.ts
> fix(docs): date-time docs typo.

- src/components/toolbar/toolbar-header.ts
Fixes a spelling error in the description
- remove the word 'the' where it shouldn't be
3.x
> docs(toolbar): fix a spelling error for toolbar-header

- src/navigation/nav-params.ts
Added the import statement that goes with using NavParams. This statement is typically given on other doc pages, but wasn't on this one.
Improves consistency across doc pages, and provides critical information about using the documented feature.
- Add import statement
**Fixes**: #
> docs(nav-params): include import statements

- src/components/content/content.ts
A simple, easily missed typo in `ion-content` docs: simply adds correct tense to "need" in description, first paragraph.
- replace "need" with "needed"
> docs(content): fix typo "need" in docs

- src/components/modal/modal-controller.ts
Fix very minor capitalization typo in the modal-controller documentation
> docs(modal): fix improper capitalization

- src/components/modal/modal-controller.ts
I added documentation on how to use a modal container component in an Ionic app. This has had a lot of discussion in #8151, and is minimally documented, so I took a stab at documenting it.
- add documentation on navigating inside modal
**Ionic Version**: 1.x / 2.x / **3.x**
**Fixes**: #8151
> docs(modal): add docs for using nav in modal

- src/components/checkbox/checkbox.ts
- src/components/segment/segment.ts
- src/util/base-input.ts
- src/util/input-tester.ts
This is a replacement for PR #12315 that takes inputs that do not blur into account. The purpose of this PR is to make the application of ng-touched consistent with its application in Angular.
- For inputs such as the standard text input, trigger ng-touched on blur not change
**Fixes**: #12102
> fix(input): mark ion-input touched on blur instead of changed

- src/components/menu/menu-toggle.ts
Navbar link in MenuToggle docs was wrong
> docs(MenuToggle): fix navbar link

- demos/src/searchbar/pages/page-one/page-one.ts
To get value from search input, it must be ev.target.value
-
-
-
**Fixes**: #
> docs(demos): add event target to searchbar demo

- src/components/slides/slides.ts
Clarify how zoom works so users do not have to dig through the swiper docs in order to figure it out.
- Clarify how zoom works
**Fixes**: # 12861
> docs(slides): clarify how zooming works

- src/components/datetime/datetime.ts
- src/components/datetime/test/basic/pages/root-page/root-page.html
- src/components/datetime/test/basic/pages/root-page/root-page.ts
- src/components/datetime/test/datetime.spec.ts
When datetime input has max value greater than current date its by default selected when datetime picker is opened.
Added **pickerDefault** input which is selected if datetime has no value.
3.x
> feat(datetime): add default picker value input

- src/components/alert/alert-component.ts
- src/components/input/input.ts
- src/components/searchbar/searchbar.ts
When having any input, no matter the direction of the app, writing ltr should be on the left, writing rtl should be on the right.
This is the behavior of most inputs across the web 
- add `dir="auto"` to all of the inputs across the system
> feat(input): add dir attribute for different language directions

- package.json
Updates the dependencies to the latest Angular release
- Angular 4.4.4
- TypeScript 2.3.4
-
3.x
> chore(dependencies): bump Angular

- src/components/tabs/tabs.ts
During tab changes when there's no transition, `app` doesn't receive `viewDidEnter` or `viewDidLeave` which are only fired during a transition. This adds those calls to tabs after a selection has completed.
**Fixes**: #11694
> fix(tabs): emit viewDidEnter and viewDidLeave on app during tab change. ≈

- src/navigation/nav-controller.ts
Update comment in Nav Guards when pushing new view.
Comment was the same as leaving a view. 'leave' to 'enter'. Correct ?
Little typo fix in documentation on Nav Guards
- Change nav-controller.ts comment navguards view enter example
-
-
**Fixes**: #
> Update nav-controller.ts Nav Guards comment

- src/components/slides/swiper/swiper-events.ts
For desktop only, using swipe on ion-slides is broken when multiples ion-slides are present (https://github.com/ionic-team/ionic/issues/12008)
Change the swiper listener target to `touchEventsTarget` instead of `plt.doc()`
**Fixes**: #
> fix(ion-slides) Swipe ion-slides is broken when multiples ion-slides are used

- src/components/datetime/datetime.ts
- src/components/datetime/test/basic/pages/root-page/root-page.html
- src/components/datetime/test/basic/pages/root-page/root-page.ts
Passing `buttons` in `pickerOptions` to the DateTime component will drop the handler functions because of the `deepCopy`. 
- Uses the spread operator instead of the deepCopy function.
- Adds pickerOptions to one of the examples in the e2e test
**Fixes**: #11641
> fix(datetime): use spread operator to copy pickerOptions

- src/components/virtual-scroll/virtual-scroll.ts
When changing tab or navigate to a different page than the one containing a virtual scroll component, virtual scroll is still running and specifically the part that listens for window resize events. When you resize the window in the other screen for some reason (open keyboard, change orientation, resize browser), that event is triggered in virtual scroll and tries to re-calculate the virtual scroll component. Unfortunately all the numbers that it takes into account then are wrong, as it is not visible.
Stop calculating virtual scroll dimensions while it is out of view. This is the first step into a more complete approach, as when virtual scroll gets back into view, resize should be triggered then in case the viewport is still altered by the previous resize events. …
> fix(VirtualScroll): stop from resizing while out of view

- src/tap-click/tap-click.ts
The .activated class is kept on a activable element when the finger or mouse is released on an non-activable element (#13044)
Keep previous activatableEle between pointerStart and pointerEnd method
**Fixes**: #13044
> fix(tap-click): activated state is kept on activable element

- src/components/alert/alert-component.ts
When creating a new alert which has an input text field it doesn't get focused.
Wrap the focus() method of the input element in a setTimeout so that the web component
has enough time to initialize. This effectively defers the work until the end of the execution queue.
-
-
-
**Ionic Version**: 3.8.0
**Fixes**: #12784
> fix(alert): focus input after it is ready

- package.json
Upgrades the rxjs dep to 5.5.0. No breaking changes!
Upgrades Angular to the latest release
fix #13266
> chore(package): bump angular and rxjs

- packages/core/src/components/alert/alert.tsx
Allows for other input types besides just checkbox and radio button to be disabled.
Core version of change made here:
https://github.com/ionic-team/ionic/pull/13521
**Fixes**: #13488
> fix(alert): allow disabled for any type of input

- src/navigation/nav-controller.ts
Warn IonicPage Lifecycle events are only available on IonicPage component, others components need Angular Lifecycle Hooks.
In the NavController documentation, only Ionic Page Lifecycle events are present. At first, we have the impression that these events replace the Angular Lifecycle hooks, but that's not the case!
Add warn
**Ionic Version**: 3
> Warn about IonicPage Lifecycle

- src/platform/cordova.scss
Fixes applying the `safe-area-inset-bottom` twice when there is both a footer and bottom tabs.
- Overrides footer rule when there are bottom tabs, as they already have the `safe-area-inset-bottom` fix applied.
3.9.2
**Fixes**: #13615
> fix(cordova): don't apply safe area to footer if there are bottom tabs

- packages/core/src/components/button/button.ios.scss
- packages/core/src/components/button/button.ios.vars.scss
- packages/core/src/components/button/button.md.scss
- packages/core/src/components/button/button.md.vars.scss
- packages/core/src/components/button/button.scss
- packages/core/src/components/button/button.tsx
- packages/core/src/components/button/readme.md
- packages/core/src/themes/util.scss
This removes our global focus styles and adds local focus management and styles for `ion-button`.
- Remove global `:focus, :active { outline: none; }`
- Add focus management for `ion-button` to handle keyboard navigation
- Add ios/md focus styles to `ion-button`
> feat(button) localize focus management and styles

- packages/core/src/components.d.ts
- packages/core/src/components/input/input.tsx
- packages/core/src/components/input/readme.md
- packages/core/src/components/range/range.tsx
- packages/core/src/components/searchbar/searchbar.tsx
- packages/core/src/components/textarea/readme.md
- packages/core/src/components/textarea/textarea.tsx
- packages/core/src/utils/helpers.ts
🚧 
This adds a debounce helper and uses it to debounce `ionInput`/`ionChange` events several types of inputs.
> feat(inputs) debounce input and change events

- packages/core/src/components/action-sheet/action-sheet.ios.scss
- packages/core/src/components/action-sheet/action-sheet.ios.vars.scss
- packages/core/src/components/action-sheet/action-sheet.md.scss
- packages/core/src/components/action-sheet/action-sheet.md.vars.scss
- packages/core/src/components/button/button.ios.scss
- packages/core/src/components/button/button.ios.vars.scss
- packages/core/src/components/button/button.md.scss
- packages/core/src/components/button/button.md.vars.scss
- packages/core/src/components/button/button.scss
- packages/core/src/components/chip/chip.ios.scss
- packages/core/src/components/chip/chip.md.scss
- packages/core/src/components/chip/chip.scss
- packages/core/src/components/chip/chip.vars.scss
- packages/core/src/components/fab-button/fab-button.scss
- packages/core/src/components/item/item.scss
- packages/core/src/components/range/range.scss
🚧  **WIP - DO NOT MERGE**
This remove extra icon styles from various components now that `ion-icon` has new styles.
Remove extra icon styles from:
> fix(icon) remove extra icon styles

- packages/core/src/components/action-sheet/action-sheet.scss
- packages/core/src/components/alert/alert.scss
- packages/core/src/components/chip-button/chip-button.scss
- packages/core/src/components/fab-button/fab-button.scss
- packages/core/src/components/input/input.scss
- packages/core/src/components/radio/radio.scss
- packages/core/src/components/range/range.scss
- packages/core/src/components/searchbar/searchbar.scss
- packages/core/src/components/segment/segment.scss
- packages/core/src/components/textarea/textarea.scss
- packages/core/src/components/toolbar/toolbar.scss
This removes the default focus outline from certain components. Previously, we used a global rule for this, but that has performance implications and breaks encapsulation for standalone use.
```css
*:active,
*:focus {
outline: none;
}
```
This affects these components:
- action-sheet
- alert
- chip-button
- fab-button
- input
- radio
- range
- searchbar
- segment
- textarea
- toolbar
> fix() remove default focus styles

- packages/core/src/components/checkbox/checkbox.tsx
This refactors the checkbox component. It should work correctly in forms now and also sets checked more declaratively on the native input.
- Replace a custom timeout with the `debounce` helper.
- Instead of keeping native/component in sync manually, just pass attributes.
- Instead of setting a default value, set a default name and let value be the native default of `"on"`.
> refactor(checkbox) form usage and declarative set

- packages/core/src/components/toggle/toggle.tsx
This refactors the toggle component. It should work correctly in forms now and also sets checked more declaratively on the native input. This also brings toggle inline with checkbox, which recently got a similar refactor in #13898.
> refactor(toggle) form usage and declarative set

- packages/core/src/components/radio-group/radio-group.tsx
- packages/core/src/components/radio-group/test/basic/index.html
Resolves issue where disabling the radio-group does not disable the radio buttons.
- Propagate the disabled value from the group down to the radios in the group.
> fix(radio-group): propagate the disabled attribute

- src/components/action-sheet/action-sheet-controller.ts
I've fixed a small grammatical error in the docs for ActionSheetController.
> Fix a small typo in the ActionSheetController documentation

- src/components/alert/alert-controller.ts
There are various inaccurate examples on SO and elsewhere that suggest that onDismiss() can be used to detect dismissal of alert controllers.
This documentation showed neither the old nor new way to get this...
- Example of use of onDidDismiss()
- Explanation
**Fixes**: #
> docs: demonstrate use of onDidDismiss() with Alert

- src/components/menu/menu.ts
Spelling error in documentation
- Fixed spelling - 'it will belongs to' to 'it will belong to'
> Spelling fix

- src/components/app/menu-controller.ts
links to _menu API docs_ wasn't working on <https://ionicframework.com/docs/api/components/app/MenuController/>
- just some fixed links/URLs :)
**Fixes**: #
> fixed links to menu API docs in MenuController docs

- packages/core/src/components/nav/nav.tsx
Awaits for components to be hydrated before continuing with the animation
-
-
-
**Fixes**: #
> fix(nav): wait for components to be ready

- src/components/slides/slides.scss
Values for swiper pagination bullet and progress bar backgrounds were hard-coded to ionic blue. Should use app theme primary colors.
- switch hard-coded sass color to variable
> fix(sass): use sass variables for slide background values

- src/navigation/nav-controller.ts
fix Link on `<ion-navbar>`
Fix Current docs that linked to 404 page
-
-
-
**Fixes**: #
> Fix linked to 404

- src/components/item/item-sliding.ts
(ionSwipe) is shown in the doc as being on <ion-item-sliding> but in the code it is on <ion-item-options>. I spent over 2 hours trying to figure out why the event wasn't firing
-Moved (ionSwipe) to correct element in documentation.
-
-
**Fixes**: #1213
> Fixed Critical Documentation Issue

- src/navigation/ionic-page.ts
The docs incorrectly state how segments get their default names. See commit https://github.com/ionic-team/ionic-app-scripts/commit/5a97ba5b8bf125f741cc46ace7d45ccdbdf7bfac.
Add note about name and segment properties needing to be unique. See commit https://github.com/ionic-team/ionic-app-scripts/commit/63c4c7ff1878a2c123de43d6240bfbe2e5fe8077
> docs: fix error re: default segment naming

- src/platform/platform.ts
Electron platform is not documented.
- Add missing `electron` platform to the platform's list
**Fixes**: #
> Add missing `electron` platform to the platform's list

- src/components/input/input.ts
There was no example before, and so it wasn't clear that you need to use ( ) around the event name in order for this to work.
> Added an example of attaching an event handler function.

- core/README.md
- core/scripts/readme.md
Minor change, just fixing obvious typos
Thanks!
4.x
> docs: minor typos fixed in readmes

- react/package-lock.json
- react/package.json
- react/src/react-framework-delegate.ts
The `FrameworkDelegate` in `@ionic/react` no longer matches the expected behavior of a Framework Delegate.  `attachViewToDom` resolves to an object, rather than just the element created, as is the new expected behavior of the method.
- Removed the specific TypeScript version from `package.json`, instead relying on the version from `@stencil/core`
- This behavior is the same as from `@ionic/core`
- This is required in order to build the project, as it fails to compile using the old TS version
- Generated a `package-lock.json`
- Also present in `@ionic/core`, and a best practice
- The Framework Delegate's `attachViewToDom` now resolves to just the element created
**Fixes**: #14165
> Fixing the FrameworkDelegate in @ionic/core

- core/src/components/item-options/item-options.tsx
- core/src/components/item-options/readme.md
- core/src/components/item-sliding/readme.md
As mentioned in https://github.com/ionic-team/ionic/issues/14293#issuecomment-380559751, this PR replaces the remaining obsolete references to `side` values `"left"` and `"right"` by the new values `"start"` and `"end"`, and the associated swipe direction description.
- Reword description of swipe direction in `item-sliding` + link to `item-options` docs.
- Replace possible values description in `item-options`'s `side` Prop by new values.
- Add a table in `item-options` to describe effect of `side` value in button position and swipe direction to reveal them.
**Ionic Version**: ~~1.x / 2.x / 3.x~~ / **4.x**
**Fixes**: helps the documentation part of #14293, but does not fix the missing side bug.
> docs(item-sliding): use new side values start and end

- core/src/components/toast/animations/ios.enter.ts
- core/src/components/toast/animations/ios.leave.ts
Check if constant/env are supported before using it in calc for the toast animation
To reproduce the issue, open the following url in Chrome on the `master` branch: http://localhost:3333/src/components/toast/test/basic
Try to open one of the `top` or `bottom` toasts in `ios` mode and you will see nothing happens.
> fix(toast): only use constant and env if supported

- core/src/components/toast/usage/angular.md
The create method returns a promise. Other examples deal with this using async-await, so I did the same thing in this instance.
Typo in documentation
- Just fixing the typo. Only touches documentation.
**Fixes**: No issue opened, because I think it's such a small change. If you need me to open it, please tell me.
> Typo in toast component angular usage example

- angular/src/directives/navigation/ion-router-outlet.ts
Remove a console.log. I think that it was there by mistake
**Ionic Version**:  4.x
**Fixes**: #
> chore(nav): Remove console.log

- core/src/components/action-sheet/usage/angular.md
- core/src/components/alert/usage/angular.md
- core/src/components/backdrop/usage/angular.md
- core/src/components/loading/usage/angular.md
- core/src/components/popover/usage/angular.md
- core/src/components/segment-button/usage/angular.md
- core/src/components/segment/usage/angular.md
- core/src/components/select/usage/angular.md
The usage docs in the new docs have pretty typescript syntax highlighting, but that only works if they're told that the code is typescript
- change every angular example in the usage section to be marked as typescript
-
-
4.x
**Fixes**: #
> docs(usage): setting angular usage example to be typescript

- core/src/components/fab-list/readme.md
Hi again,
Since https://github.com/ionic-team/ionic/commit/a203534b27c86104313daacee8365b306dfcfbcb released in `@ionic/core` (v4) [`v4.0.0-alpha.2`](https://github.com/ionic-team/ionic/releases/tag/v4.0.0-alpha.2), FAB List `side` attribute now uses `"start"` and `"end"` values instead of `"left"` and `"right"`, for RTL support.
However, the FAB List [README page top table](https://github.com/ionic-team/ionic/tree/v4.0.0-alpha.2/core/src/components/fab-list) has not been updated accordingly ([latest version](https://github.com/ionic-team/ionic/tree/v4.0.0-alpha.6/core/src/components/fab-list)).
- Replace in README top table `side` attribute `"left"` and `"right"` values by `"start"` and `"end"`.
- Update example FAB usage with `vertical` and `horizontal` attributes instead of directly …
> docs(fabList): update README to start+end sides and FAB horizontal+vertical attrs

- CHANGELOG.md
there is a typo in the changelog of 4.0.0-beta.7
- add a missing 'r' so angular is correctly written
**Ionic Version**:  4.x
> fix(CHANGELOG.md): typo in 4.0.0-beta.7

- core/src/components/action-sheet/usage/angular.md
- core/src/components/alert/usage/angular.md
- core/src/components/backdrop/usage/angular.md
- core/src/components/loading/usage/angular.md
- core/src/components/popover/usage/angular.md
- core/src/components/segment-button/usage/angular.md
- core/src/components/segment/usage/angular.md
- core/src/components/select/usage/angular.md
- core/src/components/toast/usage/angular.md
This is a continuation of #14469. I had one file that I had forgotten to save. 
- change toast angular usage example to be flagged as TS
-
-
4.x
**Fixes**: #
> docs(usage): one last usage example to typescript

- angular/src/providers/platform.ts
According to [cordova documentation](https://cordova.apache.org/docs/en/latest/cordova/events/events.html#deviceready), `addEventListener` call for `deviceready` event should be done on `document` object. `platform.ready()` does not resolve on device if this change is not made.
- Change the `deviceready` subscription from `window` to `document`.
**Fixes**: #
> fix(angular) correct subscription to cordova ready event

- angular/BREAKING.md
ion-label has new new position attribute like documented in https://beta.ionicframework.com/docs/api/label
we write about fixed, stacked and floating, we are not sure what's about the inline parameter. Inline should be the default one, so NO position attribute listed, right?
4.x
> docs(breaking): add ion-label new position attribute

- angular/BREAKING.md
The component is no longer an argument. Explain the breakage.
- add information about the change with old and new usages
**Ionic Version**:  4.x
**Fixes**:  n/a
> docs(modal): add breaking change to create method arguments

- src/components/fab/fab.ts
From "it has to wrapped" to "it has to be wrapped".
This corrects a grammar mistake on the first paragraph of the [FabButton page](https://ionicframework.com/docs/api/components/fab/FabButton/).
- Change the text _"it has to wrapped"_ to _"it has to be wrapped"_.
**Fixes**: #
> docs(FabButton): correct grammar mistake

- core/src/components/list/list.ios.scss
Fixes an issue where list items in ios mode still had lines with `lines="none"` set.
- Don't apply this scss rule that sets border width, if lines="none".
**Fixes**: #14769
> fix(list): scss for lines="none" on ios

- core/src/components/content/content.scss
Makes height of content available for childs.
- add height: 100%; to scroll-inner class of content component.
**Ionic Version**:   4.x
**Fixes**: #14771
> feat(content): set height to make it accessible for childs

- core/src/components/loading/usage/angular.md
LoadingOptions in the loadingController takes "content" as a parameter instead of "message"
Change "message" by "content"
> Correct loadingController options parameter

- angular/src/directives/navigation/ion-router-outlet.ts
(stack !== 'false' OR stack !== false) will always be TRUE. That OR should be an AND.
Stack Attribute was not working on `ion-router-outlet`
> fix(router-outlet): fix stack attribute detection

- core/src/components/header/usage/javascript.md
The header still has an old example of `ion-navbar`.
Update docs with breaking change.
-
-
-
**Fixes**: #
> Replace ion-navbar with ion-toolbar

- core/src/components/content/content.scss
- core/src/components/tab-button/tab-button.ios.scss
- core/src/components/tab-button/tab-button.md.scss
- core/src/components/tab-button/tab-button.md.vars.scss
- core/src/components/tab-button/tab-button.scss
- core/src/components/tab-button/tab-button.tsx
- core/src/components/tabbar/tabbar.ios.scss
- core/src/components/tabbar/tabbar.md.scss
- core/src/components/tabbar/tabbar.md.vars.scss
- core/src/components/tabbar/tabbar.scss
- core/src/components/tabs/test/colors/index.html
:rocket: Ready to merge :rocket:
Here is the current snapshot diff between master and this branch: https://ionic-snapshot-go.appspot.com/ionic-core/snapshots/v95/tdm/chrome_400x800
fixes #14611
> fix(tabs): fix the tabbar layout so it works with shadow DOM

- core/src/components/virtual-scroll/readme.md
example docs from `<ion-list [virtualScroll]="items">` to `<ion-virtual-scroll [items]="items">` mainly.
> doc: fix code examples from deprecated [virtualScroll] to [items]

- core/src/components/card/card.ios.scss
- core/src/components/card/card.md.scss
- core/src/components/item/item.ios.scss
- core/src/components/item/item.md.scss
I might be mistaken, but I believe the card and item components were referencing `--ion-item-background` instead of `--ion-item-background-color`.
- item.ios.scss: --ion-item-background > --ion-item-background-color
- item.md.scss: --ion-item-background > --ion-item-background-color
- card.ios.scss: --ion-item-background > --ion-item-background-color
- card.md.scss: --ion-item-background > --ion-item-background-color
4.x
> fix(css): ion-item-background > ion-item-background-color

- core/src/global/config.ts
This resolves https://github.com/ionic-team/ionic/issues/15202 respectively it fix the definition of `scrollAssist` in `config.ts` by declaring it as `boolean` instead of `string` as introduced in v4.beta-3
v4
> fix: Fix scrollAssist boolean instead of string definition

- core/src/components/action-sheet/usage/angular.md
- core/src/components/icon/readme.md
The header value was using ".
Short description of what this resolves:
tslint was highlighting this as an issue.
Changes proposed in this pull request:
" => '
Ionic Version: 1.x / 2.x / 3.x / 4.x
4.x
Fixes: -
> Replacing " with ' in sample code

- core/src/components/virtual-scroll/virtual-scroll.tsx
remove console.log message with the viewportOffset which is executed on every virtual scroll update
> fix(virtual-scroll): remove console.log message

- angular/BREAKING.md
> Update BREAKING.md-Add missed menu title in the list

- core/src/components/datetime/datetime-util.ts
Currently, if all the values in `ion-datetime` are `0`, it doesn't render any text. 
E.g. `<ion-datetime displayFormat="HH:mm" value="00:00"></ion-datetime>` doesn't render any text, even tough "00:00" is a valid time.
- allow values to be zero
**Fixes**: #
> fix(datetime): allow values to be zero

- core/src/components/button/usage/javascript.md
Fix the ion-button JS usage documentation.
- ion-button JS usage docs update
**Fixes**: #
> fix(docs): use shape property to get round buttons

- core/src/components/reorder-group/reorder-group.tsx
Adds an event hook for when a user reorders an item inside an `ion-reorder-group`. Example output is similar to:
```
{
fromIndex: 2
toIndex: 1
}
```
- Adds `(ionItemReorder)` event 
**Fixes**: #14640
> v4 - Adds ionItemReorder event to ion-reorder-group

- core/src/components/col/col.tsx
- core/src/components/col/readme.md
Safari ignores alternate values for --ion-grid-columns when determining col width, reverting always to the default 12.
- Use a equivalent way of calling CSS.supports() that works with custom variables in Safari, cause at the moment is partially broken in WebKit: https://bugs.webkit.org/show_bug.cgi?id=154669
**Ionic Version**: 4.0-beta.3
More details here:
https://github.com/ionic-team/ionic/issues/14562#issuecomment-414072347
> fix(grid): working check for CSS custom variables in Safari

- core/src/components/card-header/card-header.scss
The current scss implementation of card headers assumes that long text should be hidden by default. For designs that can't guarantee content length, it is better to default to wrapping long text.
To get around the current implementation, developers must remember to add the 'text-wrap' attribute to every instance of <card-header>, which invites gaps in coverage once projects mature with many pages. That, or they will have to overwrite the card header component's properties.
- Remove css that assumes long content should hide instead of wrap.
Before:
After:
> card header text wraps by default

- .github/PROCESS.md
- .github/ionic-issue-bot.yml
Implements the noReply automated workflow via the ionic-issue-bot
- will close and lock "needs reply" issues after 30 without a reply
- once a reply is entered, "needs reply" label is removed and "has reply" label is applied
- items with "has reply" are ignored by the stale sweeper
The general workflow from the perspective of our devs:
1. determines that more data is needed
1. Ionic dev writes a comment (important to do this FIRST)
1. Ionic dev add "needs reply" label (important to do this SECOND)
1. ideally, someone (anyone) replies and "needs reply" is replaced with "has reply"
1. Ionic dev determines if reply is adequate and processes further or perhaps repeats the "needs reply" bits
> chore(bot): implement the noReply automated workflow

- CHANGELOG.md
> docs(changelog): add missing text-transformation-css import

- core/src/utils/media.ts
Short description of what this resolves:
Correct breakpoint will be returned so ion-col is working correctly
Ionic Version: 4.0
Closes #15495
> fix(core): matchBreakpoint will return true if breakPoint is empty string

- core/src/components/infinite-scroll/usage/angular.md
Added import statements to make the angular typescript example easier to adopt for individual use cases.
Improves documentation
- Added missing import statements in infinite scroll component
**Fixes**: #
> Updated InfiniteScroll Angular docs

- core/src/components/range/range.tsx
- core/src/components/range/test/basic/index.html
When dynamically updating the min and max props of a range, the component is not updated correctly. This can be shown easily by connecting the min or max to the value of another range.
- watch for changes to the `min` and `max` props, and call `updateRatio()` as it's already done for the `value` prop
**Fixes**: #15511
> Update range ratio when new min/max are passed

- core/src/components/slides/slides.tsx
I do not know if this is a good practice what I made. So you do not have to merge it, if there are better ways to do it.
Methods of slides component wait until swiper is initialized
- Added a readyPromise which will be resolved after swiper is initialized
- Methods wait until swiper is initialized
**Fixes**: #15575
> fix(slides): Methods wait for execution until swiper is initialized

- core/src/components/router/readme.md
Just fixes two typoes in the `ion-router` docs.
> docs(ion-router): fix some typos

- core/src/utils/overlays.ts
When listening to `ionBackButton` events, only registers the `backbutton` handler if there is actually an overlay. This will give a chance to handlers with lower priority to eventually run.
- in the `ionBackButton` listener for overlays, only register the handler if there is actually an overlay
**Ionic Version**: 4.0.0-beta.11
**Fixes**:  #15601
> fix(overlay): register backbutton handler only when needed

- core/src/components/virtual-scroll/readme.md
Fix small typos
- Change `performimg` to `performing`
- Change `comparision` to `comparison`
4
> docs(virtual-scroll): fix typos

- core/src/components.d.ts
- core/src/components/route/readme.md
- core/src/components/route/route.tsx
Fixes a small typo
- Change `internaly` to `internally`
4
> docs(route): fix typo

- angular/BREAKING.md
- angular/src/providers/menu-controller.ts
Fixes a small typo
- Change `programatically` to `programmatically`
4
> docs(menu-controler): fix typo

- core/src/components/textarea/test/preview/index.html
Adds the correct label position property
- Add correct properties
4
> docs(textarea): fix label positions

- core/src/components/fab-list/readme.md
Fixes a small typo
- Change `specifiy ` to `specify `
4
> docs(fab-list): fix typo

- core/src/components/img/readme.md
Fixes a small typo
- Change `lazyily ` to `lazily`
4
> docs(img): fix typo

- core/src/components/platform/readme.md
The is method of Platform takes 'desktop' instead on 'windows'
Update the documentation
Ionic 4
> is method takes 'desktop' instead on 'windows'

- angular/src/providers/platform.ts
`platform.resize` doesn't emit an event upon resizing, because it was bound to `document` instead of `window`.
> fix: resize events will emit again in platform.resize

- core/src/components/button/button.ios.scss
- core/src/components/buttons/buttons.ios.scss
- core/src/components/searchbar/searchbar.ios.scss
- core/src/components/tabbar/tab-button.scss
Fix the problem with buttons on iOS not loosing the opacity when clicked
- use @media (any-hover: hover) to detect if device supports any kind of hover 
**Ionic Version**:  4.x
**Fixes**: #15667, #14934
> fix(button): disable :hover on non supported devices

- core/src/components/avatar/test/preview/index.html
Fixes the "ugly" avatar component preview
- Add `padding` to `ioni-content`
4
> docs(avatar): refactor component preview

- .github/CONTRIBUTING.md
Fixes a broken link on CONTRIBUTING.md
Changes it for the correct anchor
> fix(docs): Fix commit link on CONTRIBUTING.md

- core/src/components/col/col.tsx
Resolve a bug when using the component ion-col with a stencil app on IE11
Related to issue #15881 
- update ion-col component
> fix(col): fix CSS is undefined error on IE11

- core/package.json
If rollup is not installed as global dependency, you cannot execute `npm run build` (because it runs `build.vendor`). So I added rollup as dev dependency
> chore: Add rollup as dev dependency

- core/src/components/menu-button/menu-button.ios.scss
- core/src/components/menu-button/menu-button.md.scss
- core/src/components/menu-button/menu-button.scss
The menu-button was not visible if the toolbar got the primary color.
Should it merged? It's just a first step because the back-button has already MANY css variables, the menu button has not. So I think the menu button has to be extended afterwards. So this PR only fixes the color!
- Menu Button is now visible
**Fixes**: #15546 #15545
> fix(menu-button): Not visible if toolbar has primary color

- core/src/components/popover/readme.md
Popover controller link reference not found
Link to Ionic Framework documentation
-
-
-
**Fixes**: #16019
> Popover documentation links

- core/src/components/tab-bar/tab-bar.scss
- core/src/components/tab-bar/test/scenarios/index.html
Aligns the tab-bar text to the center by default
**Ionic Version**: 1.x / 2.x / 3.x / <b>4.x</b>
**Fixes**: #15273
| `master`   | `fix-tab-bar-align` |
| -----------| --------------------|
> fix(tab-bar): align tab text to the center

- core/src/components/action-sheet/action-sheet.md.scss
- core/src/components/action-sheet/action-sheet.md.vars.scss
- core/src/components/action-sheet/test/spec/e2e.ts
- core/src/components/action-sheet/test/spec/index.html
- core/src/themes/ionic.theme.default.md.scss
- core/src/themes/ionic.theme.default.scss
Modifies the Action Sheet styles (background, button height, colors, etc) to match the Material Design Spec: https://material.io/design/components/sheets-bottom.html
- Updates Action Sheet styles for Material Design
- Modifies overlay background to #fff (affects alert too)
- Adds a "spec" e2e test which can be used to compare against the spec
| `master` | `fix-action-sheet-design` |
| ---------| --------------------------|
| ![](https://user-images.githubusercontent.com/6577830/47680895-7dff5000-db9e-11e8-870d-801372a23ab5.png) | ![](https://user-images.githubusercontent.com/6577830/47681372-ab98c900-db9f-11e8-971c-1ae648d57f26.png) |
Comparison with the Material Design spec:
> fix(action-sheet): update action sheet design to match MD spec

- core/src/components/footer/footer.md.scss
- core/src/components/footer/footer.md.vars.scss
- core/src/components/header/header.md.scss
- core/src/components/header/header.md.vars.scss
- core/src/components/toolbar/test/spec/e2e.ts
- core/src/components/toolbar/test/spec/index.html
Updates the Material Design header box-shadow to match the spec.
| `master` | `fix-header-footer-box-shadow` |
| ----------| ---------------------------------|
| ![](https://user-images.githubusercontent.com/6577830/47748135-71433080-dc60-11e8-8319-b7714ecf6a27.png) | ![](https://user-images.githubusercontent.com/6577830/47748082-55d82580-dc60-11e8-87a9-9f137d95e3bc.png) |
> fix(header): update box shadow to match MD spec

- src/components/menu/menu.ts
"Navbar" links on https://ionicframework.com/docs/api/components/menu/Menu/ are deadlinks and are redirected to https://ionicframework.com/docs/v1/api/components/navbar/Navbar.
This patch corrects the two deadlinks to their where they are actually residing at.
- Fix deadlinks
**Fixes**: Deadlinks
> Fix deadlink to Navbar docs

- core/src/components/button/button.md.scss
- core/src/components/button/button.md.vars.scss
This adjusts our Material Design button to match the updated spec for:
- transition timing
- outline border styles
- clear/outline hover background color
> fix(button): match MD spec timing, outline, hover

- .circleci/config.yml
We were using `circleci/node:latest-browsers` as the Docker image, and I believe it was recently updated to Node 11, which is not supported by our version of node-sass.
> chore(ci): lock in node version

- core/src/components/tab-bar/readme.md
- core/src/components/tab-bar/tab-bar.scss
- core/src/components/tab-button/readme.md
- core/src/components/tab-button/tab-button.scss
This adds documentation for the custom properties in the new tabs API. The `ion-tabs` and `ion-tab` components are mostly style-less, so that leaves `ion-tab-bar` and `ion-tab-button`. **Note** that I skipped documenting tab-button's `--badge-end` property to suggest we reconsider that naming.
> docs(tabs): document custom properties

- core/src/components/range/range.md.vars.scss
This increases the horizontal padding on Material Design
range to prevent clipping within item.
> fix(range): increase MD horizontal padding

- core/src/components/segment-button/segment-button.ios.scss
- core/src/components/segment-button/segment-button.ios.vars.scss
- core/src/components/segment-button/segment-button.md.scss
- core/src/components/segment-button/segment-button.md.vars.scss
- core/src/components/segment/segment.ios.scss
- core/src/components/segment/segment.md.scss
- core/src/components/segment/segment.md.vars.scss
- core/src/components/segment/test/toolbar/index.html
Currently the segment does not use the available toolbar color variables:
```
--ion-toolbar-color
--ion-toolbar-color-activated
```
I _could_ have made it use these but then we run into the problem of not being able to customize only the segment buttons (separate from the text or buttons) when they're unchecked or checked. For example, in order to recreate the following:
We would need to be able to pass an opacity to the unchecked color. Without the user specifying the opacity or passing an rgb, we can't manipulate only the single color. So basically we needed to add another variable in order to keep the buttons in a toolbar one color `#ffffff` and the unchecked segment buttons another color `rgba(255, 255, 255, .6)`. Thus I have added the following CSS globals to customize segment …
> fix(segment): adds global variables for targeting segment in toolbar

- core/src/components/toast/toast.scss
Fixes longer toasts by changing `white-space: pre` to `white-space: pre-wrap`
**Ionic Version**: 4.0.0
**Fixes**: #16360
> fix(toast): Make longer toasts available with pre-wrap

- core/src/components/buttons/buttons.md.scss
This fixes an issue where a Material Design button would disappear when focused within a toolbar with a color attribute.
> fix(toolbar): match MD button spec

- CHANGELOG.md
Should be `@angular-devkit/core` and `@angular-devkit/schematics` not be `~7.0.5`, also your starter template is using ~7.0.0 https://github.com/ionic-team/starters/blob/master/angular/base/package.json
> docs(): wrong dev imports for beta.16

- angular/src/directives/navigation/href-delegate.ts
- angular/src/directives/navigation/ion-back-button.ts
- angular/src/directives/navigation/stack-controller.ts
- angular/src/directives/navigation/tabs-delegate.ts
- angular/src/directives/virtual-scroll/virtual-scroll.ts
- angular/src/providers/nav-controller.ts
refactor: use ng7 features for direction detection
-
-
-
**Fixes**: #
> fix(angular): tune routerLink default behaviour

- angular/src/directives/control-value-accessors/boolean-value-accessor.ts
Default value should be false, not empty string. If empty string was given and checkbox was part of angular form, it was checked by default.
> fix(angular): default value of BooleanValueAccessor should be false

- core/src/components/toolbar/test/translucent/index.html
- core/src/themes/ionic.theme.default.ios.scss
- core/src/themes/ionic.theme.default.md.scss
fixes #16384
BREAKING CHANGES
The default background color for the Toolbar and Tab Bar is now white (#fff).
This can be changed by overriding the following CSS variables:
```
--ion-toolbar-background
--ion-tab-bar-background
--ion-tab-bar-background-focused
```
See https://beta.ionicframework.com/docs/theming/css-variables for more information.
> fix(themes): update default toolbar and tab background to #fff

- core/src/components/range/range.ios.scss
- core/src/components/range/range.md.scss
- core/src/components/range/test/basic/index.html
This adds margins between the range slider and its slotted content, such as labels or icons.
> fix(range): add slot margins

- angular/BREAKING.md
Adds documentation to breaking changes on what replaces the `showWhen` / `hideWhen` directives (in v3) and the `ion-show-when` / `ion-hide-when` components (in v4).
closes #15776
closes #16214
> docs(breaking): add show-when and hide-when to breaking

- core/src/components/tabs/readme.md
On a call with someone who noted that our documentation has some broken links and specifically pointed out this link, so I don't know if there are others, but this one appears to just be a casing issue so far as I can tell.
> fix(tabs): update link

- core/src/components/button/button.scss
Fixes a problem with `contain: strict` on ion-button on expand full and block.
I think that `contain: content;` should work on all other use cases like  `contain: strict`, but the screenshot tests will show us :)
**Fixes**: #16552
> fix(button): Contain strict to contain content

- core/src/components/loading/loading.tsx
backdropDismiss wasn't set correctly
**Ionic Version**:  4.0.0-beta.17
**Fixes**: #16527
> fix(loading): add backdropDismiss closes #16527
